import type { SlashCategory } from "@/lib/ai-prompts/types";

export const SLASH_CATEGORIES: SlashCategory[] = [
  {
    title: "Learning",
    commands: [
      { cmd: "/learn", desc: "learn any topic" },
      { cmd: "/roadmap", desc: "learning roadmap" },
      { cmd: "/resources", desc: "best resources" },
      { cmd: "/books", desc: "recommended books" },
      { cmd: "/courses", desc: "top courses" },
      { cmd: "/practice", desc: "practice plan" },
      { cmd: "/explain", desc: "simplify topic" },
      { cmd: "/quiz", desc: "test your knowledge" },
      { cmd: "/flashcards", desc: "memory cards" },
      { cmd: "/summary", desc: "summarize topic" },
      { cmd: "/teach", desc: "teach back method" },
      { cmd: "/revision", desc: "revision system" },
    ],
  },
  {
    title: "Advanced Prompt Control",
    commands: [
      { cmd: "/role", desc: "assign role" },
      { cmd: "/context", desc: "give context" },
      { cmd: "/constraints", desc: "set limits" },
      { cmd: "/format", desc: "define format" },
      { cmd: "/tone", desc: "choose tone" },
      { cmd: "/style", desc: "writing style" },
      { cmd: "/examples", desc: "provide examples" },
      { cmd: "/step", desc: "force step thinking" },
      { cmd: "/iterate", desc: "improve response" },
      { cmd: "/critic", desc: "self critique" },
      { cmd: "/refine", desc: "refine output" },
      { cmd: "/retry", desc: "regenerate response" },
    ],
  },
  {
    title: "Personal Branding",
    commands: [
      { cmd: "/niche", desc: "define niche" },
      { cmd: "/audience", desc: "target audience" },
      { cmd: "/bio", desc: "optimize bio" },
      { cmd: "/positioning", desc: "brand positioning" },
      { cmd: "/contentplan", desc: "content strategy" },
      { cmd: "/voice", desc: "brand voice" },
      { cmd: "/story", desc: "personal story" },
      { cmd: "/authority", desc: "build authority" },
      { cmd: "/consistency", desc: "posting system" },
      { cmd: "/monetize", desc: "monetization ideas" },
      { cmd: "/network", desc: "networking strategy" },
      { cmd: "/growth", desc: "personal growth plan" },
    ],
  },
  {
    title: "Business / Strategy",
    commands: [
      { cmd: "/idea", desc: "generate business ideas" },
      { cmd: "/validate", desc: "validate idea" },
      { cmd: "/businessplan", desc: "full business plan" },
      { cmd: "/gtm", desc: "go to market strategy" },
      { cmd: "/pricing", desc: "pricing strategy" },
      { cmd: "/revenue", desc: "revenue streams" },
      { cmd: "/costcut", desc: "reduce costs" },
      { cmd: "/growth", desc: "growth strategy" },
      { cmd: "/scaling", desc: "scale business" },
      { cmd: "/positioning", desc: "brand positioning" },
      { cmd: "/usp", desc: "unique selling point" },
      { cmd: "/competition", desc: "competitor analysis" },
    ],
  },
  {
    title: "Execution / Output Modes",
    commands: [
      { cmd: "/ghost", desc: "final answer only, no explanation" },
      { cmd: "/minimal", desc: "shortest possible response" },
      { cmd: "/brief", desc: "3 to 5 lines max" },
      { cmd: "/expand", desc: "detailed explanation" },
      { cmd: "/stepbystep", desc: "clear steps" },
      { cmd: "/checklist", desc: "actionable checklist" },
      { cmd: "/framework", desc: "structured framework" },
      { cmd: "/blueprint", desc: "implementation plan" },
      { cmd: "/playbook", desc: "repeatable system" },
      { cmd: "/roadmap", desc: "timeline based steps" },
      { cmd: "/draft", desc: "rough first version" },
      { cmd: "/polish", desc: "clean and refine output" },
    ],
  },
  {
    title: "Coding / Tech",
    commands: [
      { cmd: "/debug", desc: "find bugs" },
      { cmd: "/refactor", desc: "clean code" },
      { cmd: "/optimizecode", desc: "improve performance" },
      { cmd: "/systemdesign", desc: "architecture design" },
      { cmd: "/api", desc: "API structure" },
      { cmd: "/database", desc: "DB design" },
      { cmd: "/scalability", desc: "scaling approach" },
      { cmd: "/security", desc: "security checks" },
      { cmd: "/testcases", desc: "generate tests" },
      { cmd: "/pseudocode", desc: "logic only" },
      { cmd: "/explain", desc: "explain code simply" },
      { cmd: "/review", desc: "full code review" },
    ],
  },
];
