export interface KafkaConcept {
  id: number;
  section: string;
  title: string;
  tagline: string;
  description: string;
  note?: string;
  diagram?: string;
  example: string;
  tip: string;
  tags: string[];
}

export const KAFKA_SECTIONS = [
  "Introduction",
  "Core Concepts",
  "Producers & Consumers",
  "Reliability",
  "Performance",
  "Patterns",
] as const;

export const KAFKA_CONCEPTS: KafkaConcept[] = [

  // ─────────────────────────────────────────────
  // INTRODUCTION
  // ─────────────────────────────────────────────
  {
    id: 1,
    section: "Introduction",
    title: "What is Apache Kafka?",
    tagline: "A distributed event streaming platform built for high throughput and replay",
    description:
      "Apache Kafka is an <b>event streaming platform</b>. Unlike a traditional message queue where messages are deleted after being read, Kafka stores events in an append-only log and lets any consumer read them — even days or weeks later.\n\nThink of Kafka like a river:\n• Events (water) keep flowing in from producers upstream\n• The river (Kafka) holds the water in a long channel — it does not drain immediately\n• Any number of consumers can stand at different points in the river and read the water that passed by\n• You can even rewind and read from the start of the river\n\n<b>Why was Kafka created?</b>\n\nKafka was built at LinkedIn in 2011 to handle activity tracking — millions of page views, clicks, and profile updates per second. Traditional message queues like RabbitMQ could not sustain that throughput. LinkedIn needed something that:\n• Handles millions of messages per second\n• Keeps messages for days or weeks (not just until consumed)\n• Lets multiple independent teams read the same stream at their own pace\n• Survives server failures without losing data\n\n<b>The key difference from a traditional queue</b>\n\nIn a traditional queue (like RabbitMQ):\n• Producer sends a message → Queue holds it → Consumer reads it → Message is deleted\n• Once a consumer reads a message, it is gone\n\nIn Kafka:\n• Producer sends an event → Kafka appends it to a log → Consumers read it by tracking their own position\n• The event stays in Kafka for a configurable retention period (default 7 days)\n• Multiple consumers can read the same event independently\n\n<b>Common use cases</b>\n\n• Real-time analytics — stream clicks, purchases, sensor readings to dashboards\n• Event sourcing — record every state change as an immutable event log\n• Log aggregation — collect logs from hundreds of servers into one stream\n• Change data capture (CDC) — stream database changes to other systems\n• Microservice communication — decouple services via event streams",
    note:
      "The single biggest difference from RabbitMQ: messages in Kafka are NOT deleted after consumption. They live in a durable log. This makes Kafka ideal for event replay, audit trails, and building multiple independent consumers on the same stream. If you just need a simple task queue, RabbitMQ is usually simpler.",
    diagram:
      "  TRADITIONAL QUEUE (RabbitMQ model)\n\n  Producer ──► [Queue] ──► Consumer\n                 ↑\n            Message deleted\n            after consumer reads it\n\n  ─────────────────────────────────────────────────────────\n\n  KAFKA (Append-only event log)\n\n  Producer ──► [Topic: user-events]\n               │\n               │  offset→  0     1     2     3     4     5\n               │          [evt] [evt] [evt] [evt] [evt] [evt]  ◄── new events appended here\n               │\n               ├──► Consumer A (analytics team)   reads at offset 5\n               ├──► Consumer B (billing service)   reads at offset 3\n               └──► Consumer C (new team replay)   reads from offset 0\n\n  Each consumer tracks its own position. Events stay in the log.",
    example:
      "// Node.js — connect to Kafka using the 'kafkajs' library\n// Install: npm install kafkajs\n\nconst { Kafka } = require('kafkajs');\n\n// Create a Kafka client — point it at your broker(s)\nconst kafka = new Kafka({\n  clientId: 'my-app',             // identifies this application in logs\n  brokers: ['localhost:9092'],    // list of broker addresses\n});\n\n// ── PRODUCER (publish an event) ─────────────────────────────────\nconst producer = kafka.producer();\n\nasync function publishEvent() {\n  await producer.connect();\n\n  await producer.send({\n    topic: 'user-events',\n    messages: [\n      {\n        key: 'user-42',                         // key routes to a partition\n        value: JSON.stringify({\n          type: 'PAGE_VIEW',\n          userId: 42,\n          page: '/dashboard',\n        }),\n      },\n    ],\n  });\n\n  console.log('Event published');\n  await producer.disconnect();\n}\n\npublishEvent();\n\n// ── CONSUMER (read events) ──────────────────────────────────────\nconst consumer = kafka.consumer({ groupId: 'analytics-service' });\n\nasync function startConsumer() {\n  await consumer.connect();\n  await consumer.subscribe({ topic: 'user-events', fromBeginning: false });\n\n  await consumer.run({\n    eachMessage: async ({ topic, partition, message }) => {\n      const event = JSON.parse(message.value.toString());\n      console.log(`Received: ${event.type} from user ${event.userId}`);\n      // Kafka auto-commits the offset after eachMessage returns\n    },\n  });\n}\n\nstartConsumer();",
    tip: "In interviews, lead with: 'Kafka is an append-only event log, not a traditional queue. The biggest difference is that messages are not deleted after consumption — they are retained so any consumer can replay them.' Then contrast with RabbitMQ to show you understand when to use each.",
    tags: ["Apache Kafka", "Event Streaming", "Append-only Log", "High Throughput", "Event Replay"],
  },

  // ─────────────────────────────────────────────
  // CORE CONCEPTS
  // ─────────────────────────────────────────────
  {
    id: 2,
    section: "Core Concepts",
    title: "Topics, Partitions & Offsets",
    tagline: "How Kafka organises and stores events for parallel, ordered processing",
    description:
      "<b>Topic</b>\n\nA topic is a named category for events — similar to a database table or a folder. All events about user activity go into the `user-events` topic. All payment events go into the `payments` topic. Producers write to a topic; consumers read from a topic.\n\n<b>Partition</b>\n\nA topic is split into one or more partitions. Each partition is an independent, ordered log of events.\n\nPartitions exist for two reasons:\n• <b>Scalability</b> — different partitions can live on different brokers (servers), so writing and reading can happen in parallel\n• <b>Parallelism</b> — different consumers in the same group can each read a separate partition at the same time\n\n<b>Offset</b>\n\nEach event inside a partition gets a sequential number called an offset — starting from 0. The offset is how consumers track their progress: 'I have read up to offset 42 in partition 0.'\n\n<b>Message ordering</b>\n\nKafka guarantees ordering only within a single partition — not across partitions. If you need all events for a specific user to be in order, use the user ID as the message key. Kafka will always send events with the same key to the same partition.\n\n<b>How many partitions?</b>\n\nStart with the same number of partitions as your expected maximum consumer instances. More partitions = more parallelism, but also more memory and file handles on the broker. A common starting point: 3 to 12 partitions per topic.",
    note:
      "Think of a topic as a bookshelf, partitions as individual shelves, and offsets as the position of each book on the shelf. You can read book #5 on shelf #2 any time — it stays there until the retention period expires.",
    diagram:
      "  Topic: 'orders'  (3 partitions)\n\n  Partition 0:  [0: order#1] [1: order#4] [2: order#7] [3: order#10] ...\n  Partition 1:  [0: order#2] [1: order#5] [2: order#8] [3: order#11] ...\n  Partition 2:  [0: order#3] [1: order#6] [2: order#9] [3: order#12] ...\n                                                         ↑\n                                                    new events appended here\n\n  Message key 'user-99' always hashes to Partition 1\n  → all events for user-99 arrive in order within Partition 1\n\n  Consumer Group (3 consumers, 3 partitions → 1:1 assignment)\n  Consumer 1 ──reads──► Partition 0\n  Consumer 2 ──reads──► Partition 1\n  Consumer 3 ──reads──► Partition 2",
    example:
      "// Creating a topic with specific partition count (admin API)\n\nconst { Kafka } = require('kafkajs');\nconst kafka = new Kafka({ clientId: 'admin', brokers: ['localhost:9092'] });\n\nasync function createTopic() {\n  const admin = kafka.admin();\n  await admin.connect();\n\n  await admin.createTopics({\n    topics: [\n      {\n        topic: 'orders',\n        numPartitions: 3,         // 3 parallel partitions\n        replicationFactor: 2,    // 2 copies of each partition\n      },\n    ],\n  });\n\n  console.log('Topic created');\n  await admin.disconnect();\n}\n\ncreateTopics();\n\n// Publishing with a key → same key always goes to same partition\nconst producer = kafka.producer();\nawait producer.connect();\n\nawait producer.send({\n  topic: 'orders',\n  messages: [\n    {\n      key: 'user-99',           // key ensures order for this user\n      value: JSON.stringify({ orderId: 555, userId: 99, total: 49.99 }),\n    },\n  ],\n});\n\nawait producer.disconnect();",
    tip: "When asked 'how does Kafka scale?', the answer is: partitions. More partitions = more consumers in a group = more parallelism. Each partition is an independent ordered log. A consumer group with 5 consumers and a 3-partition topic means 2 consumers will be idle — never more consumers than partitions.",
    tags: ["Topic", "Partition", "Offset", "Ordering", "Scalability", "Message Key"],
  },

  // ─────────────────────────────────────────────
  // PRODUCERS & CONSUMERS
  // ─────────────────────────────────────────────
  {
    id: 3,
    section: "Producers & Consumers",
    title: "Producers — Writing Events to Kafka",
    tagline: "How applications publish events: keys, partitioning, batching, and acks",
    description:
      "A producer is any application that writes events to a Kafka topic.\n\n<b>How a producer sends a message</b>\n\n1. The producer creates a `ProducerRecord` with a topic, an optional key, and a value\n2. The partitioner decides which partition to send to:\n   • If a key is provided: `hash(key) % numPartitions` → deterministic assignment\n   • If no key: round-robin across partitions\n3. The record is added to a local buffer (the record accumulator)\n4. The buffer is flushed as a batch to the broker\n\n<b>Producer acknowledgments (acks)</b>\n\n`acks` controls how many broker replicas must confirm receipt before the producer considers the message sent:\n\n• `acks: 0` — Fire and forget. No wait for confirmation. Fastest, but messages can be lost if the broker restarts.\n• `acks: 1` — Wait for the leader replica to confirm. Good balance of speed and safety.\n• `acks: all` (or `-1`) — Wait for all in-sync replicas (ISR) to confirm. Slowest, safest. Use in production.\n\n<b>Batching and compression</b>\n\nProducers batch multiple messages before sending to reduce network round-trips. You can also enable compression (`gzip`, `snappy`, `lz4`, `zstd`) to reduce the size of batches — especially useful for large volumes of similar events.\n\n<b>Idempotent producer</b>\n\nBy default, if a network error causes the producer to retry, the same message can arrive twice. Set `idempotent: true` to enable exactly-once delivery at the producer level. Kafka deduplicates retried messages automatically.",
    note:
      "For production, always use `acks: 'all'` + `idempotent: true`. This combination ensures no messages are lost and no duplicates are created on retries, without needing distributed transactions.",
    diagram:
      "  Producer flow:\n\n  App code\n    │\n    │  producer.send({ topic, key, value })\n    ↓\n  Partitioner\n    │  key present? → hash(key) % partitions → Partition N\n    │  no key?      → round-robin            → Partition 0,1,2...\n    ↓\n  Record Accumulator (in-memory buffer)\n    │  batches messages to reduce network calls\n    ↓\n  Network send (batch) ──► Kafka Broker (Leader for Partition N)\n                                │\n                       acks=all │──► Follower Replica 1 ──► ack\n                                │──► Follower Replica 2 ──► ack\n                                │\n                           all acks received\n                                │\n                         ◄── confirm to producer",
    example:
      "// Production-ready producer with acks, idempotent, and compression\n\nconst { Kafka, CompressionTypes } = require('kafkajs');\n\nconst kafka = new Kafka({ clientId: 'order-service', brokers: ['broker1:9092', 'broker2:9092'] });\n\nconst producer = kafka.producer({\n  idempotent: true,             // prevents duplicate messages on retry\n  transactionTimeout: 30000,\n});\n\nasync function publishOrder(order) {\n  await producer.connect();\n\n  const result = await producer.send({\n    topic: 'orders',\n    compression: CompressionTypes.GZIP,  // compress the batch\n    messages: [\n      {\n        key: String(order.userId),        // same user → same partition → in-order\n        value: JSON.stringify(order),\n        headers: {\n          'event-type': 'ORDER_PLACED',\n          'source-service': 'order-service',\n        },\n      },\n    ],\n    acks: -1,                   // acks: 'all' — wait for all in-sync replicas\n  });\n\n  console.log('Published to partition:', result[0].partition, 'offset:', result[0].baseOffset);\n  await producer.disconnect();\n}\n\npublishOrder({ userId: 99, orderId: 555, total: 49.99 });",
    tip: "The three levers for producer reliability are: `acks`, `retries`, and `idempotent`. Set `acks: -1` + `idempotent: true` + `retries: 5` for production. The idempotent flag tells Kafka to deduplicate retries using a producer ID + sequence number, giving you at-least-once delivery that behaves like exactly-once.",
    tags: ["Producer", "Acks", "Partitioner", "Batching", "Idempotent", "Compression"],
  },

  {
    id: 4,
    section: "Producers & Consumers",
    title: "Consumers & Consumer Groups",
    tagline: "How services read events — groups, partition assignment, and offset commits",
    description:
      "A consumer is any application that reads events from a Kafka topic.\n\n<b>How a consumer reads</b>\n\n1. Consumer subscribes to a topic\n2. Kafka assigns one or more partitions to this consumer\n3. Consumer polls the broker in a loop: 'give me the next batch of messages'\n4. After processing, consumer commits its offset — 'I have processed up to offset 42'\n5. If the consumer crashes and restarts, it reads from the last committed offset\n\n<b>Consumer Groups — the key to parallel processing</b>\n\nA consumer group is a set of consumers that cooperate to read a topic. Kafka enforces a rule:\n\n<b>Each partition is assigned to exactly one consumer in the group at a time.</b>\n\nThis means:\n• 3 partitions + 3 consumers = each consumer reads 1 partition (perfect parallelism)\n• 3 partitions + 1 consumer = that one consumer reads all 3 partitions\n• 3 partitions + 5 consumers = 3 consumers active, 2 idle (extra consumers are standby)\n\n<b>Multiple groups, independent reads</b>\n\nTwo different consumer groups reading the same topic each get their own independent cursor. Group A being at offset 100 has no effect on Group B at offset 20. This is fundamentally different from RabbitMQ where multiple consumers compete for the same messages.\n\n<b>Rebalancing</b>\n\nWhen a consumer joins or leaves a group, Kafka triggers a rebalance — it redistributes partition assignments among all current consumers. During a rebalance, processing pauses briefly. Use the `CooperativeStickyAssignor` to minimise rebalance disruption.",
    note:
      "Consumer groups are how Kafka scales consumption horizontally. Add more consumer instances (up to the partition count) and each one takes a share of the partitions. This is different from RabbitMQ's competing consumers — in Kafka, you choose which group reads which topic, and each group gets its own independent view of the full stream.",
    diagram:
      "  Topic: 'payments'  (4 partitions: P0, P1, P2, P3)\n\n  ─── Group A: 'billing-service' (2 consumers) ───\n  Consumer-1 ──reads──► P0, P1\n  Consumer-2 ──reads──► P2, P3\n\n  ─── Group B: 'fraud-detection' (4 consumers) ───\n  Consumer-1 ──reads──► P0\n  Consumer-2 ──reads──► P1\n  Consumer-3 ──reads──► P2\n  Consumer-4 ──reads──► P3\n\n  Both groups read ALL events independently.\n  billing-service at offset 500 does NOT affect fraud-detection at offset 300.\n\n  ─── What happens when Consumer-1 in Group A crashes? ───\n  Kafka rebalances → Consumer-2 now reads P0, P1, P2, P3",
    example:
      "// Consumer group reading from a topic with manual offset commit\n\nconst { Kafka } = require('kafkajs');\nconst kafka = new Kafka({ clientId: 'billing', brokers: ['localhost:9092'] });\n\nconst consumer = kafka.consumer({\n  groupId: 'billing-service',   // group name — shared across all billing instances\n  sessionTimeout: 30000,        // if no heartbeat in 30s, Kafka marks this consumer dead\n});\n\nasync function start() {\n  await consumer.connect();\n\n  // fromBeginning: true → read all existing events when first joining\n  // fromBeginning: false → start from newest events only\n  await consumer.subscribe({ topic: 'payments', fromBeginning: false });\n\n  await consumer.run({\n    // autoCommit: true by default — offset committed after eachMessage returns\n    eachMessage: async ({ topic, partition, message }) => {\n      const payment = JSON.parse(message.value.toString());\n      console.log(\n        `[P${partition} offset ${message.offset}] Payment: $${payment.amount} from user ${payment.userId}`\n      );\n      // Process the payment...\n      await processBillingRecord(payment);\n      // Offset is auto-committed after this function returns successfully\n    },\n  });\n}\n\nstart().catch(console.error);\n\n// To run a second consumer in the same group:\n// Just start another process with groupId: 'billing-service'\n// Kafka automatically assigns different partitions to each instance",
    tip: "When designing consumer groups, think about the unit of work you want to parallelise. If you have 12 partitions and want 12-way parallelism, deploy 12 consumer instances with the same groupId. If you add a 13th, it sits idle until one of the 12 fails. The partition count is your parallelism ceiling.",
    tags: ["Consumer Group", "Partition Assignment", "Offset Commit", "Rebalancing", "Parallelism"],
  },

  // ─────────────────────────────────────────────
  // CORE CONCEPTS
  // ─────────────────────────────────────────────
  {
    id: 5,
    section: "Core Concepts",
    title: "Brokers, Clusters & Replication",
    tagline: "How Kafka survives server failures: leaders, followers, and ISR",
    description:
      "A broker is a single Kafka server. A cluster is a group of brokers that work together.\n\n<b>Why multiple brokers?</b>\n\n• <b>Fault tolerance</b> — if one broker crashes, others keep serving traffic\n• <b>Scalability</b> — different partitions can be stored on different brokers, spreading the load\n\n<b>Partition leaders and followers</b>\n\nFor each partition, one broker is the leader and one or more brokers are followers:\n• All writes go to the leader\n• Followers continuously copy events from the leader\n• If the leader crashes, Kafka automatically elects a new leader from the followers\n\n<b>Replication factor</b>\n\nThe replication factor tells Kafka how many copies of each partition to keep:\n• `replicationFactor: 1` — no redundancy. Data is lost if that broker dies.\n• `replicationFactor: 2` — one leader + one follower. Survives 1 broker failure.\n• `replicationFactor: 3` — one leader + two followers. Survives 2 broker failures. Standard for production.\n\n<b>In-Sync Replicas (ISR)</b>\n\nISR is the set of follower replicas that are up-to-date with the leader. If a follower falls too far behind (due to slowness or network issues), it is removed from the ISR.\n\n`min.insync.replicas` (usually set to 2) tells Kafka: 'Do not accept a write unless at least 2 replicas are in-sync.' Combined with `acks: all`, this guarantees a write is not acknowledged until it is safely on 2 replicas.\n\n<b>ZooKeeper and KRaft</b>\n\nHistorically, Kafka used ZooKeeper to manage cluster metadata (leader elections, partition assignments). Since Kafka 3.3+, the KRaft mode replaces ZooKeeper — Kafka manages its own metadata internally, simplifying setup and operations.",
    note:
      "For production: use `replicationFactor: 3` and `min.insync.replicas: 2`. This combination tolerates one broker failure while still writing safely. With 3 replicas and min ISR of 2, even if one follower is slow or temporarily offline, writes proceed. Only when 2 replicas are down will the producer get an error.",
    diagram:
      "  Kafka Cluster: 3 brokers  |  Topic 'orders', 3 partitions, replicationFactor=3\n\n  Broker 1              Broker 2              Broker 3\n  ┌──────────────┐      ┌──────────────┐      ┌──────────────┐\n  │ P0 [LEADER]  │      │ P0 [FOLLOWER] │      │ P0 [FOLLOWER] │\n  │ P1 [FOLLOWER]│      │ P1 [LEADER]  │      │ P1 [FOLLOWER] │\n  │ P2 [FOLLOWER]│      │ P2 [FOLLOWER] │      │ P2 [LEADER]  │\n  └──────────────┘      └──────────────┘      └──────────────┘\n         │                     ↑\n  writes ──────────────────────┘  (followers replicate from leader)\n\n  If Broker 1 crashes:\n  → Kafka elects Broker 2 or 3 as new leader for P0\n  → No data lost (replication factor = 3)\n  → No manual intervention needed",
    example:
      "// Checking cluster metadata and partition leaders (kafkajs admin API)\n\nconst { Kafka } = require('kafkajs');\nconst kafka = new Kafka({ clientId: 'admin', brokers: ['broker1:9092', 'broker2:9092', 'broker3:9092'] });\n\nasync function inspectCluster() {\n  const admin = kafka.admin();\n  await admin.connect();\n\n  // Fetch topic metadata — shows partition leaders and replicas\n  const metadata = await admin.fetchTopicMetadata({ topics: ['orders'] });\n\n  metadata.topics.forEach((topic) => {\n    console.log('Topic:', topic.name);\n    topic.partitions.forEach((p) => {\n      console.log(\n        `  Partition ${p.partitionId}: leader=broker${p.leader}, replicas=${p.replicas}, isr=${p.isr}`\n      );\n    });\n  });\n\n  // Fetch consumer group offsets\n  const offsets = await admin.fetchOffsets({\n    groupId: 'billing-service',\n    topics: ['payments'],\n  });\n  console.log('Group offsets:', offsets);\n\n  await admin.disconnect();\n}\n\ninspectCluster();",
    tip: "The formula to remember for reliability: `replicationFactor: 3` + `min.insync.replicas: 2` + `acks: -1`. This is Kafka's 'no-data-loss' triple. In interviews: 'replication factor is how many copies; ISR is how many must be up-to-date; acks=all means the producer waits until all ISR replicas confirm.'",
    tags: ["Broker", "Cluster", "Replication Factor", "Leader", "Follower", "ISR", "KRaft"],
  },

  // ─────────────────────────────────────────────
  // RELIABILITY
  // ─────────────────────────────────────────────
  {
    id: 6,
    section: "Reliability",
    title: "Message Delivery Guarantees",
    tagline: "At-most-once, at-least-once, and exactly-once — what each means in practice",
    description:
      "Kafka supports three delivery semantics. Understanding them is critical for choosing the right configuration.\n\n<b>At-most-once (fire and forget)</b>\n\n• The producer sends a message and does not wait for confirmation\n• The consumer commits the offset before processing\n• If something crashes mid-process, the message is skipped — it will not be retried\n• Result: messages may be lost. Never processed twice, but sometimes not processed at all.\n• Use when: losing some events is acceptable (logging, metrics)\n\n<b>At-least-once (the default)</b>\n\n• The producer retries on failure → the same message may arrive twice\n• The consumer commits the offset after processing\n• If the consumer crashes after processing but before committing, it reprocesses the message\n• Result: no messages are lost. But the consumer might process the same message more than once.\n• Use when: you can make your consumer idempotent (processing the same event twice gives the same result)\n\n<b>Exactly-once (the gold standard)</b>\n\n• Uses Kafka Transactions — the producer wraps multiple sends in a transaction\n• Either all messages in the transaction are committed, or none are\n• Kafka deduplicates retried producer sends using a producer ID + sequence number\n• Result: every message is processed exactly once, end-to-end\n• Use when: financial transactions, billing, inventory updates — anything where duplicates cause real harm\n\n<b>How to make at-least-once safe</b>\n\nIn practice, most teams use at-least-once + idempotent consumers. An idempotent consumer processes a message and checks: 'Have I already handled event ID X?' If yes, it skips. This is simpler than full Kafka Transactions and covers most use cases.",
    note:
      "The recommendation for most production systems: at-least-once delivery + idempotent processing on the consumer side. Full exactly-once Kafka Transactions are powerful but add operational complexity. Design your consumers to be idempotent (use a processed-event ID table in your database) and you get the safety of exactly-once without the overhead.",
    diagram:
      "  AT-MOST-ONCE (can lose messages)\n  Producer ──sends──► Broker  (no retry on failure)\n  Consumer: commit offset → process → (crash here = message skipped)\n\n  ─────────────────────────────────────────────────────────────\n\n  AT-LEAST-ONCE (can duplicate messages)\n  Producer: retries on failure → message may arrive twice\n  Consumer: process → commit offset  (crash before commit = reprocess)\n\n  ─────────────────────────────────────────────────────────────\n\n  EXACTLY-ONCE (safe, more complex)\n  Producer: idempotent=true + transactional ID\n    → Kafka assigns producer ID + sequence number\n    → duplicate sends are deduplicated by the broker\n  Consumer: use read_committed isolation level\n    → only sees committed transactions",
    example:
      "// Exactly-once producer using Kafka Transactions\n\nconst { Kafka } = require('kafkajs');\nconst kafka = new Kafka({ clientId: 'payment-service', brokers: ['localhost:9092'] });\n\nconst producer = kafka.producer({\n  transactional: true,\n  transactionalId: 'payment-service-1',  // unique per producer instance\n  idempotent: true,\n  maxInFlightRequests: 1,               // required for idempotent+transactional\n});\n\nasync function processPaymentExactlyOnce(payment) {\n  await producer.connect();\n\n  await producer.transaction(async (transaction) => {\n    // All sends in this block are atomic\n    await transaction.send({\n      topic: 'payment-confirmed',\n      messages: [{ key: String(payment.userId), value: JSON.stringify(payment) }],\n    });\n\n    await transaction.send({\n      topic: 'audit-log',\n      messages: [{ value: JSON.stringify({ event: 'PAYMENT_PROCESSED', ...payment }) }],\n    });\n\n    // Both sends are committed together, or neither is\n    await transaction.commit();\n  });\n}\n\nprocessPaymentExactlyOnce({ userId: 99, amount: 49.99 });\n\n// At-least-once with idempotent consumer (simpler, usually good enough)\nasync function handleMessage(event, db) {\n  const alreadyProcessed = await db.query(\n    'SELECT 1 FROM processed_events WHERE event_id = $1',\n    [event.id]\n  );\n  if (alreadyProcessed.rows.length > 0) return; // skip duplicate\n\n  await db.query('INSERT INTO orders ...');\n  await db.query('INSERT INTO processed_events (event_id) VALUES ($1)', [event.id]);\n}",
    tip: "For interviews: 'Exactly-once in Kafka requires three things: idempotent producer (dedup at broker level), Kafka Transactions (atomic multi-topic sends), and read_committed isolation on the consumer. But for 90% of use cases, at-least-once + idempotent consumer processing is simpler and safe enough.'",
    tags: ["At-least-once", "Exactly-once", "At-most-once", "Idempotent Producer", "Transactions"],
  },

  {
    id: 7,
    section: "Reliability",
    title: "Log Retention & Event Replay",
    tagline: "The superpower of Kafka: messages stay in the log and can be re-read any time",
    description:
      "This is the feature that makes Kafka fundamentally different from all other message queues. In Kafka, consuming a message does not delete it. Events stay in the log and can be replayed.\n\n<b>How retention works</b>\n\nKafka keeps events for a configurable retention period:\n• `retention.ms` — keep events for this many milliseconds (default: 7 days)\n• `retention.bytes` — keep events until the total log size reaches this limit\n• Either limit triggers deletion of the oldest segments\n\nYou can also use log compaction for topics where only the latest value per key matters (like a settings store). Compaction keeps the most recent event for each key, removing older duplicates.\n\n<b>What event replay enables</b>\n\n• <b>New service onboarding</b> — A new microservice joins the team. It can read all historical events from `fromBeginning: true` and rebuild its own state from scratch — no backfill scripts needed.\n• <b>Debugging production bugs</b> — A bug corrupted some data? Replay the event stream through the fixed code to reconstruct correct state.\n• <b>A/B testing processors</b> — Run two versions of a consumer on the same historical stream and compare outputs before deploying.\n• <b>Audit log</b> — Every change to the system is preserved in Kafka. Replay at any time to answer 'what happened at 3pm on Tuesday?'\n\n<b>Seeking to a specific position</b>\n\nConsumers can seek to:\n• The beginning of the log — process all events ever\n• The end of the log — process only new events\n• A specific offset — replay from event #500\n• A specific timestamp — replay from events after 2024-01-01",
    note:
      "Event replay is Kafka's most powerful differentiator. When you need to launch a new service that depends on historical data, in Kafka you just say 'subscribe from the beginning'. In a traditional queue, that data is gone. This is why Kafka is the foundation of event-driven architectures and event sourcing.",
    diagram:
      "  Topic: 'orders'  Retention: 7 days\n\n  offset: 0  ... 100 ... 500 ... 1000 ... 5000 (latest)\n            [oldest]                        [newest]\n                │                               │\n                │←── 7-day window ──────────────│\n\n  Consumer A (billing):         starts at offset 4800 (recent only)\n  Consumer B (new analytics):   seeks to offset 0 (replay all 7 days)\n  Consumer C (debugging):       seeks to timestamp '2024-06-01T00:00:00Z'\n\n  LOG COMPACTION (different from time-based retention)\n  Key: 'user-99'\n  [offset 0: {name:'Alice'}] [offset 50: {name:'Alicia'}] [offset 200: {name:'Ali'}]\n                                                               ↑\n  After compaction: only offset 200 is kept — latest value per key",
    example:
      "// Replay from the beginning of a topic\n\nconst consumer = kafka.consumer({ groupId: 'new-analytics-service' });\n\nawait consumer.connect();\nawait consumer.subscribe({ topic: 'orders', fromBeginning: true }); // replay ALL events\n\nawait consumer.run({\n  eachMessage: async ({ message }) => {\n    const order = JSON.parse(message.value.toString());\n    await analyticsDb.insert(order); // rebuild analytics from scratch\n  },\n});\n\n// ── Seek to a specific offset ────────────────────────────────────\n// Useful for debugging — replay from a known-good offset\nawait consumer.seek({ topic: 'orders', partition: 0, offset: '500' });\n\n// ── Seek to a specific timestamp ─────────────────────────────────\nconst admin = kafka.admin();\nawait admin.connect();\n\nconst targetTimestamp = new Date('2024-06-01T00:00:00Z').getTime();\nconst offsets = await admin.fetchTopicOffsetsByTime('orders', targetTimestamp);\n\n// offsets = [{ partition: 0, offset: '1234' }, { partition: 1, offset: '987' }]\n// Then seek each consumer to the returned offset before starting consumer.run()\n\nawait admin.disconnect();\n\n// ── Log compaction topic (keeps latest value per key) ────────────\nawait admin.createTopics({\n  topics: [{\n    topic: 'user-profiles',\n    configEntries: [\n      { name: 'cleanup.policy', value: 'compact' },   // compaction instead of time-based deletion\n      { name: 'min.cleanable.dirty.ratio', value: '0.1' },\n    ],\n  }],\n});",
    tip: "When asked 'how is Kafka different from a database?', say: 'Kafka is a log optimised for writes and sequential reads. A database is optimised for random reads and updates. Kafka stores events; a database stores current state. Many systems use Kafka as the source of truth and rebuild database state by replaying the log.'",
    tags: ["Log Retention", "Event Replay", "Log Compaction", "Seek", "Event Sourcing", "Audit Log"],
  },

  // ─────────────────────────────────────────────
  // PERFORMANCE
  // ─────────────────────────────────────────────
  {
    id: 8,
    section: "Performance",
    title: "Why Kafka Is Fast",
    tagline: "Sequential writes, page cache, zero-copy, and batching — the four pillars of Kafka speed",
    description:
      "Kafka can handle millions of messages per second on commodity hardware. Here is why:\n\n<b>1. Append-only sequential disk writes</b>\n\nKafka only appends to the end of log files — it never seeks backward or updates existing records. Sequential disk writes are dramatically faster than random writes. On a modern SSD, sequential writes can sustain 500 MB/s or more — close to network speed.\n\n<b>2. OS page cache instead of a heap</b>\n\nKafka delegates caching to the operating system page cache rather than maintaining its own in-memory cache. The OS is extremely good at caching recently accessed disk pages. This means:\n• Kafka uses very little JVM heap (less GC pressure)\n• Hot data is served from RAM automatically, without extra code\n• A broker restart does not lose the cache (OS page cache persists across process restarts)\n\n<b>3. Zero-copy transfer</b>\n\nNormally, reading data from disk to network requires 4 copies: disk → kernel buffer → user space → kernel socket buffer → network. Kafka uses the `sendfile()` system call which bypasses user space entirely: disk → kernel buffer → network. This halves the CPU cost of sending data to consumers.\n\n<b>4. Batching and compression</b>\n\nProducers batch multiple messages into a single network request. Consumers fetch batches of messages in one poll. Combining batching with compression (snappy or lz4 is a good balance) dramatically reduces both network bandwidth and broker CPU usage.\n\n<b>Back-pressure</b>\n\nIf a consumer is slow, it just reads less frequently. The broker does not need to do any work to buffer or redeliver — the events are already on disk waiting. This makes Kafka inherently back-pressure-friendly.",
    note:
      "Kafka's architecture deliberately trades flexibility for throughput. The append-only log, sequential I/O, and zero-copy are all constraints that enable extreme performance. This is why Kafka is the right tool when you need millions of events per second — and why simpler tools like RabbitMQ are often better for lower-volume, complex routing scenarios.",
    diagram:
      "  NORMAL disk-to-network path (4 copies)\n  Disk → [kernel buffer] → [user space buffer] → [kernel socket buffer] → Network\n           (1 copy)           (2 copies)                (3,4 copies)\n\n  KAFKA zero-copy sendfile() path (2 copies, bypasses user space)\n  Disk → [kernel buffer] ───────────────────────────────────► Network\n           (1 copy)          sendfile() system call\n\n  ─────────────────────────────────────────────────────────────\n\n  BATCHING effect on throughput:\n  Without batching: 1000 messages = 1000 network requests\n  With batching:    1000 messages = 10 network requests (batch of 100 each)\n                    → 100x fewer round-trips → much higher throughput\n\n  linger.ms=5: producer waits up to 5ms to accumulate a batch before sending",
    example:
      "// Tuning producer for maximum throughput\n\nconst producer = kafka.producer({\n  // Batching settings\n  // linger.ms: wait up to 10ms for more messages before sending a batch\n  // batch.size: max bytes per batch (default 16KB, increase for high throughput)\n});\n\nawait producer.connect();\n\nawait producer.send({\n  topic: 'events',\n  compression: CompressionTypes.SNAPPY,  // fast compression, good ratio\n  messages: orders.map((order) => ({\n    key: String(order.userId),\n    value: JSON.stringify(order),\n  })),\n  // Sending many messages in one call → kafkajs batches them automatically\n});\n\n// ── Tuning consumer for high throughput ─────────────────────────\nconst consumer = kafka.consumer({\n  groupId: 'high-throughput-consumer',\n  maxWaitTimeInMs: 100,   // wait up to 100ms for a full batch before returning\n  minBytes: 1,            // minimum bytes to fetch per request\n  maxBytes: 10 * 1024 * 1024,  // max 10MB per fetch (increase for large batches)\n});\n\nawait consumer.run({\n  partitionsConsumedConcurrently: 3,   // process 3 partitions concurrently\n  eachBatch: async ({ batch, resolveOffset, heartbeat }) => {\n    // Process a batch of messages at once (more efficient than eachMessage)\n    for (const message of batch.messages) {\n      const event = JSON.parse(message.value.toString());\n      await processEvent(event);\n      resolveOffset(message.offset);\n      await heartbeat(); // prevent session timeout during long batches\n    }\n  },\n});",
    tip: "For throughput-critical systems, switch from `eachMessage` to `eachBatch` in your consumer. This processes a full batch of messages at once instead of one-by-one, dramatically reducing the per-message overhead. On the producer side, sending arrays of messages in a single `producer.send()` call lets kafkajs batch them efficiently.",
    tags: ["Performance", "Sequential Writes", "Zero-Copy", "Page Cache", "Batching", "Throughput"],
  },

  // ─────────────────────────────────────────────
  // PATTERNS
  // ─────────────────────────────────────────────
  {
    id: 9,
    section: "Patterns",
    title: "Kafka vs RabbitMQ — When to Use Which",
    tagline: "Choosing the right messaging tool: event streaming vs message queuing",
    description:
      "Kafka and RabbitMQ are both messaging systems, but they are designed for different problems. Choosing wrong leads to over-engineering or under-engineering.\n\n<b>Use Kafka when:</b>\n\n• You need <b>event replay</b> — new services must process historical events when they join\n• You need <b>high throughput</b> — millions of messages per second\n• You need <b>multiple independent consumers</b> on the same stream (analytics, billing, and fraud detection all reading payments)\n• You are building <b>event sourcing</b> — the Kafka log is the source of truth\n• You need <b>stream processing</b> — real-time aggregations, joins, or transformations (Kafka Streams, Flink)\n• You need a <b>durable audit log</b> — everything that ever happened, queryable by time\n\n<b>Use RabbitMQ when:</b>\n\n• You need <b>complex routing</b> — different messages go to different queues based on routing keys or headers\n• You need <b>per-message acknowledgment and requeue</b> — fine-grained control over retries\n• You need <b>Dead Letter Queues (DLX)</b> with sophisticated retry logic out of the box\n• You have a <b>classic task queue</b> pattern — background jobs, email sending, image processing\n• You need <b>request-reply</b> messaging (RPC over messaging)\n• Your team wants a <b>simpler operational model</b> — RabbitMQ is easier to set up and reason about for low-to-medium volume\n\n<b>Can you use both?</b>\n\nAbsolutely. Many production systems use both:\n• Kafka for the high-volume event stream backbone (order events, clickstream)\n• RabbitMQ for task queues triggered by those events (send email, resize image)\n\n<b>The one-sentence decision rule</b>\n\nIf you need to replay events or stream to multiple independent consumers → Kafka. If you need complex routing, per-message control, or a simple task queue → RabbitMQ.",
    note:
      "Neither tool is universally better. The mistake to avoid is using Kafka for a simple background job queue (overkill) or using RabbitMQ for event sourcing where you need replay (wrong tool). Match the tool to the problem: stream vs queue.",
    diagram:
      "  ┌──────────────────────────────┬──────────────────────────────┐\n  │         KAFKA                │        RABBITMQ              │\n  ├──────────────────────────────┼──────────────────────────────┤\n  │ Append-only log              │ Delete-on-consume queue       │\n  │ Messages retained (7 days)   │ Messages deleted after ack    │\n  │ Consumers track own offset   │ Broker tracks delivery        │\n  │ Multiple groups, same stream │ Competing consumers           │\n  │ Replay from any offset       │ No replay (gone after read)   │\n  │ Millions of msgs/sec         │ Thousands of msgs/sec         │\n  │ Partition-based routing      │ Exchange/routing key routing  │\n  │ Simple delivery semantics    │ Per-message ack/nack/requeue  │\n  ├──────────────────────────────┼──────────────────────────────┤\n  │ Best for: event streaming,   │ Best for: task queues,        │\n  │ event sourcing, analytics,   │ email/jobs, complex routing,  │\n  │ audit logs, CDC              │ RPC, DLX retry patterns       │\n  └──────────────────────────────┴──────────────────────────────┘",
    example:
      "// PATTERN 1: Kafka for event stream + RabbitMQ for task queue\n//\n// Step 1: Order service publishes to Kafka\nconst kafkaProducer = kafka.producer();\nawait kafkaProducer.send({\n  topic: 'order-events',\n  messages: [{ key: String(order.id), value: JSON.stringify({ type: 'ORDER_PLACED', ...order }) }],\n});\n\n// Step 2: Email service subscribes to Kafka and enqueues RabbitMQ task\nconst kafkaConsumer = kafka.consumer({ groupId: 'email-trigger-service' });\nawait kafkaConsumer.run({\n  eachMessage: async ({ message }) => {\n    const event = JSON.parse(message.value.toString());\n    if (event.type === 'ORDER_PLACED') {\n      // Enqueue to RabbitMQ for reliable email delivery with retry logic\n      channel.sendToQueue('email.jobs', Buffer.from(JSON.stringify({\n        to: event.customerEmail,\n        template: 'order-confirmation',\n        orderId: event.id,\n      })), { persistent: true });\n    }\n  },\n});\n\n// Step 3: Email worker reads from RabbitMQ with per-message ack/nack\nchannel.consume('email.jobs', async (msg) => {\n  try {\n    await sendEmail(JSON.parse(msg.content.toString()));\n    channel.ack(msg);\n  } catch (err) {\n    channel.nack(msg, false, true); // requeue for retry\n  }\n});",
    tip: "When asked 'Kafka or RabbitMQ?' in an interview, do not just pick one. Say: 'It depends on whether you need event replay and multiple independent consumers (Kafka) or complex routing and fine-grained message control (RabbitMQ). They solve different problems and are often used together in the same system.'",
    tags: ["Kafka vs RabbitMQ", "Event Streaming", "Task Queue", "Architecture", "Decision Guide"],
  },
];

export const KAFKA_CONCEPT_COUNT = KAFKA_CONCEPTS.length;
