export interface SqlConcept {
  id: number;
  section: string;
  title: string;
  tagline: string;
  description: string;
  example: string;
  tip: string;
}

export const SQL_SECTIONS = [
  "Basics",
  "Querying",
  "Relationships",
  "Constraints & Design",
  "Transactions",
] as const;

export const SQL_CONCEPTS: SqlConcept[] = [
  {
    id: 1,
    section: "Basics",
    title: "What is a Database?",
    tagline: "Structured, persistent storage that your application can query reliably at any scale.",
    description:
      "A database is an organised collection of data that can be stored, retrieved, updated, and deleted efficiently. Think of it like a digital filing cabinet: every drawer has a label, every folder has a name, and nothing gets lost — even if you turn the server off and back on.\n\nA spreadsheet like Google Sheets might look similar at first. It has rows, it has columns, you can sort and filter. But spreadsheets break down quickly: they struggle with millions of rows, they have no real access control, they can't enforce rules like \"this field must always have a value\", and they weren't designed for multiple users writing data at the same time. Databases solve all of that.\n\nRelational databases organise data into tables — rows and columns — with a powerful query language called SQL (Structured Query Language) on top. The \"relational\" part means tables can reference each other, and you can combine them in queries.\n\nThe most popular relational databases are:\n- PostgreSQL — open-source, feature-rich, the professional standard for most modern apps\n- MySQL / MariaDB — the most widely deployed database in the world, used by WordPress, Facebook (historically), and millions of web apps\n- SQLite — a lightweight file-based database built into most programming languages, perfect for mobile apps and local development\n- Microsoft SQL Server and Oracle — common in enterprise environments\n\nYour application connects to the database through a database driver or ORM (Object-Relational Mapper). The app sends SQL queries as text, the database executes them, and sends back the results. Every major app you use — Instagram, Spotify, your bank — stores its core data in a relational database.",
    example:
      "-- A spreadsheet might store contacts like this (flat, no rules):\n-- Name | Email        | Phone\n-- Rajan | r@x.com     | 9800000001\n-- Rajan | r@x.com     | 9800000001  <-- duplicate! no protection\n\n-- A relational database with enforced structure:\nCREATE TABLE contacts (\n  id         INT PRIMARY KEY AUTO_INCREMENT,\n  name       VARCHAR(100) NOT NULL,\n  email      VARCHAR(255) UNIQUE NOT NULL,  -- no duplicates allowed\n  phone      VARCHAR(20),\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n-- This will FAIL because the email is already taken:\nINSERT INTO contacts (name, email) VALUES ('Rajan', 'r@x.com');\nINSERT INTO contacts (name, email) VALUES ('Rajan', 'r@x.com');\n-- Error: Duplicate entry 'r@x.com' for key 'email'",
    tip: "When someone asks 'why not just use a spreadsheet or a JSON file?', the answer is: scale, integrity, and concurrency. A spreadsheet with 10 users writing simultaneously is chaos. A flat JSON file has no query language. A database handles thousands of concurrent writes safely, enforces data rules automatically, and lets you answer complex questions across millions of rows in milliseconds.",
  },
  {
    id: 2,
    section: "Basics",
    title: "Tables & Rows",
    tagline: "Tables are the containers; rows are the individual records inside them.",
    description:
      "A table is the fundamental unit of storage in a relational database. You can think of it like a single sheet inside a spreadsheet. Each table stores one type of entity — users, orders, products, messages — and has a fixed set of columns that define what information each row holds.\n\nA row (also called a record or tuple) represents one specific instance of that entity. If the table is \"users\", each row is one user. If the table is \"orders\", each row is one order. Rows are added with INSERT, modified with UPDATE, and removed with DELETE as your application runs.\n\nA database usually contains many tables, and those tables are linked together through shared values (foreign keys). For example, an e-commerce app might have a \"users\" table, an \"orders\" table, and an \"order_items\" table — with each order linking back to a user, and each order item linking back to an order.\n\nNaming conventions matter:\n- Table names should be lowercase, plural nouns: users, products, orders, order_items\n- Column names should be lowercase with underscores: first_name, created_at, is_active\n- Avoid spaces and special characters in names\n- Be consistent — if one table uses created_at, every table should use created_at, not createdAt or date_created\n\nA real app might have dozens or hundreds of tables, but each one should represent exactly one concept. Keeping tables focused makes queries cleaner and the schema easier to understand.",
    example:
      "-- The users table:\n-- id | name    | email             | created_at\n--  1 | Rajan   | rajan@example.com | 2024-01-15 09:00:00\n--  2 | Aisha   | aisha@example.com | 2024-01-16 14:30:00\n--  3 | Carlos  | carlos@example.com| 2024-01-17 11:15:00\n\n-- The orders table:\n-- id | user_id | total  | status    | created_at\n--  1 |       1 | 49.99  | shipped   | 2024-01-20\n--  2 |       1 | 12.50  | pending   | 2024-01-22\n--  3 |       2 | 89.00  | delivered | 2024-01-21\n\n-- user_id in orders links back to id in users.\n-- Rajan (id=1) has two orders. Aisha (id=2) has one.",
    tip: "A good mental model: a database is a workbook, a table is a sheet, and a row is a single data entry. This analogy breaks down at scale, but it is perfect for getting started. The key leap beyond spreadsheets is that tables can reference each other — one row in orders can point to one row in users, and the database enforces that relationship.",
  },
  {
    id: 3,
    section: "Basics",
    title: "Columns & Data Types",
    tagline: "Columns define the shape of your data; data types enforce what's allowed in each field.",
    description:
      "Every column in a table has a name and a data type. The data type tells the database what kind of value can be stored in that column — a number, text, a date, true/false. The database rejects values that do not match the declared type.\n\nCommon data types:\n- INT — whole numbers. Use for IDs, counts, quantities, ages. BIGINT for very large numbers (over ~2 billion).\n- DECIMAL(p, s) — precise decimal numbers. p = total digits, s = digits after the decimal point. Always use DECIMAL for money — never FLOAT or DOUBLE, which have rounding errors.\n- VARCHAR(n) — variable-length text, up to n characters. Use for names, emails, status strings, short text. Faster to index than TEXT.\n- TEXT — unlimited text. Use for long content: blog posts, comments, descriptions. Cannot be fully indexed.\n- BOOLEAN — true or false. Some databases store it as TINYINT(1) under the hood.\n- DATE — a calendar date: 2024-01-15. No time component.\n- DATETIME / TIMESTAMP — a date and time: 2024-01-15 09:30:00. TIMESTAMP is stored in UTC and converts to the server's timezone on read. DATETIME stores exactly what you give it.\n- ENUM('a','b','c') — restricts the column to a fixed set of allowed string values. Simple but hard to change later — use a CHECK constraint or a lookup table if the values might grow.\n- JSON — stores a JSON object or array. Supported natively in MySQL 5.7+ and PostgreSQL (as JSONB). Useful for flexible, semi-structured data.\n\nChoosing the right type matters for storage size, performance, and data integrity. A few common mistakes:\n- Storing phone numbers as INT — strips leading zeros, fails on +1-800 format. Always VARCHAR.\n- Storing prices as FLOAT — 0.1 + 0.2 = 0.30000000000000004. Use DECIMAL(10, 2).\n- Using TEXT for everything — TEXT columns cannot be fully indexed, making WHERE text_col = 'x' very slow.",
    example:
      "CREATE TABLE products (\n  id           INT PRIMARY KEY AUTO_INCREMENT,\n  name         VARCHAR(200) NOT NULL,\n  description  TEXT,\n  price        DECIMAL(10, 2) NOT NULL,  -- 10 total digits, 2 after decimal\n  quantity     INT NOT NULL DEFAULT 0,\n  is_active    BOOLEAN NOT NULL DEFAULT TRUE,\n  category     ENUM('electronics','clothing','food') NOT NULL,\n  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP\n                 ON UPDATE CURRENT_TIMESTAMP\n);\n\n-- DECIMAL example — safe for money:\nINSERT INTO products (name, price) VALUES ('Laptop', 1299.99);\n\n-- FLOAT example — dangerous for money:\n-- SELECT 0.1 + 0.2;  --> 0.30000000000000004  (don't do this)",
    tip: "A quick rule of thumb: VARCHAR for short text (under ~500 chars), TEXT for long content, DECIMAL for money, INT for whole numbers, TIMESTAMP for when something happened. If you are unsure between DATETIME and TIMESTAMP, use TIMESTAMP — it stores in UTC so time zone conversions are handled automatically.",
  },
  {
    id: 4,
    section: "Basics",
    title: "Primary Key",
    tagline: "The unique identifier for every row — the row's permanent address in the table.",
    description:
      "A primary key is a column (or combination of columns) that uniquely identifies each row in a table. No two rows can share the same primary key value, and it can never be NULL. It is the \"address\" of a row — how you reference it from other tables and how you look it up directly.\n\nThe most common pattern is an auto-incremented integer column named \"id\". The database automatically assigns the next available integer each time a new row is inserted — 1, 2, 3, and so on. You never have to think about it.\n\nPrimary keys automatically get an index, which makes lookups by primary key extremely fast — even in tables with tens of millions of rows.\n\nAuto-increment integer vs UUID:\n- Auto-increment INT (or BIGINT): smaller (4 or 8 bytes), faster to index, sequential (insert order is predictable), but only unique within one database. Use for most apps.\n- UUID (e.g. 550e8400-e29b-41d4-a716-446655440000): 16 bytes, globally unique across databases and servers, harder to guess (more secure), but random insertions fragment the B-tree index causing slower writes. Use when you need global uniqueness (distributed systems, publicly exposed IDs).\n\nComposite primary keys use two or more columns together as the primary key. Common in junction tables (like a \"likes\" table where the primary key is (user_id, post_id)).\n\nNatural vs surrogate keys: a natural key is a real-world identifier (like a government ID or ISBN). A surrogate key is an artificial ID created just for the database (like auto-increment id). Surrogate keys are almost always the better choice — natural keys change, have exceptions, and are often longer.",
    example:
      "-- Standard auto-increment primary key:\nCREATE TABLE users (\n  id    INT PRIMARY KEY AUTO_INCREMENT,\n  name  VARCHAR(100) NOT NULL,\n  email VARCHAR(255) UNIQUE NOT NULL\n);\n\nINSERT INTO users (name, email) VALUES ('Rajan', 'r@x.com');\nINSERT INTO users (name, email) VALUES ('Aisha', 'a@x.com');\n-- id is assigned automatically: 1, 2\n\nSELECT * FROM users WHERE id = 1;  -- instant lookup via index\n\n-- UUID primary key (PostgreSQL syntax):\nCREATE TABLE sessions (\n  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id    INT NOT NULL,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n-- Composite primary key (junction table):\nCREATE TABLE user_roles (\n  user_id INT NOT NULL,\n  role_id INT NOT NULL,\n  PRIMARY KEY (user_id, role_id)  -- combination must be unique\n);",
    tip: "Use BIGINT instead of INT for primary keys in any table that might grow large. INT supports up to ~2.1 billion rows — that sounds like a lot, but a high-traffic app can hit it. BIGINT supports over 9 quintillion rows. The cost is 4 extra bytes per row — almost always worth it.",
  },
  {
    id: 5,
    section: "Querying",
    title: "SELECT",
    tagline: "The most important SQL statement — read data from one or more tables.",
    description:
      "SELECT is how you read data from a database. It is the most frequently used SQL statement by far. Every page load in a web app likely triggers dozens of SELECT queries.\n\nThe basic structure is: SELECT columns FROM table. You can select specific columns by name, or use * to get all columns. Always prefer specific column names in production code — SELECT * is convenient for exploration but has downsides: it returns data you may not need (wasting bandwidth), it breaks code that expects a fixed set of columns when the schema changes, and it can accidentally expose sensitive fields.\n\nAliasing with AS lets you rename a column in the result. This is useful for clarity or when a column name is too long to type repeatedly in a query.\n\nAggregate functions compute a single value from many rows:\n- COUNT(*) — count of all rows\n- COUNT(column) — count of non-NULL values in that column\n- SUM(column) — sum of all values\n- AVG(column) — average value\n- MIN(column) / MAX(column) — smallest or largest value\n\nGROUP BY groups rows with the same value in a column, so aggregate functions operate per group rather than across all rows.\n\nHAVING filters groups after grouping — it is to GROUP BY what WHERE is to individual rows. You can't use WHERE to filter on aggregate values (like COUNT), so HAVING fills that role.\n\nDISTINCT removes duplicate rows from the result.\n\nSQL is not case-sensitive for keywords, but the strong convention is to write keywords in uppercase (SELECT, FROM, WHERE) and identifiers in lowercase. It makes queries much easier to scan.",
    example:
      "-- All columns (exploration only):\nSELECT * FROM users;\n\n-- Specific columns:\nSELECT name, email FROM users;\n\n-- Aliases:\nSELECT name AS full_name, email AS contact_email FROM users;\n\n-- Aggregate: total order value per user:\nSELECT\n  user_id,\n  COUNT(*)       AS order_count,\n  SUM(total)     AS total_spent,\n  AVG(total)     AS avg_order_value,\n  MAX(total)     AS biggest_order\nFROM orders\nGROUP BY user_id;\n\n-- HAVING: only users who spent more than $100 total:\nSELECT user_id, SUM(total) AS total_spent\nFROM orders\nGROUP BY user_id\nHAVING SUM(total) > 100;\n\n-- DISTINCT: unique countries in user base:\nSELECT DISTINCT country FROM users;\n\n-- Computed column:\nSELECT name, price, price * 1.13 AS price_with_tax FROM products;",
    tip: "The order SQL clauses must appear in: SELECT → FROM → JOIN → WHERE → GROUP BY → HAVING → ORDER BY → LIMIT. Memorise this order — writing them out of sequence causes a syntax error. The database also evaluates them mostly in this order, which explains why you cannot use a SELECT alias in a WHERE clause (WHERE is evaluated before SELECT).",
  },
  {
    id: 6,
    section: "Querying",
    title: "WHERE",
    tagline: "Filter rows so you only get back exactly what you need.",
    description:
      "The WHERE clause filters rows based on one or more conditions. Without WHERE, SELECT returns every row in the table. Without WHERE on UPDATE or DELETE, every row in the table is modified or deleted. WHERE is the most important clause to get right.\n\nComparison operators:\n- = equal to\n- != or <> not equal to\n- > greater than, < less than, >= greater than or equal, <= less than or equal\n\nCombining conditions:\n- AND — both conditions must be true\n- OR — either condition must be true\n- NOT — negates a condition\n- Use parentheses to control precedence: AND binds tighter than OR, so (a OR b) AND c is different from a OR (b AND c)\n\nSpecial operators:\n- LIKE — pattern matching. % matches any sequence of characters, _ matches exactly one character. WHERE name LIKE 'Ra%' matches Rajan, Rahul, Raquel. Case-insensitive in MySQL by default.\n- IN (list) — shorthand for multiple OR conditions. WHERE country IN ('Nepal', 'India', 'Japan') is much cleaner than three OR clauses.\n- BETWEEN a AND b — inclusive range. WHERE price BETWEEN 10 AND 50.\n- IS NULL — checks for the absence of a value. You cannot use = NULL because NULL = NULL is not true in SQL — it returns NULL. Always use IS NULL or IS NOT NULL.\n\nWHERE applies to SELECT, UPDATE, and DELETE. The golden rule: always verify your WHERE clause before running a destructive operation in production.",
    example:
      "-- Basic comparison:\nSELECT * FROM users WHERE age > 18;\n\n-- Multiple conditions with AND:\nSELECT name, email FROM users\nWHERE status = 'active' AND role = 'admin';\n\n-- OR with parentheses for clarity:\nSELECT * FROM users\nWHERE (country = 'Nepal' OR country = 'Japan')\n  AND is_active = TRUE;\n\n-- LIKE pattern match:\nSELECT * FROM users WHERE name LIKE 'Ra%';   -- starts with Ra\nSELECT * FROM users WHERE email LIKE '%@gmail.com'; -- Gmail users\n\n-- IN shorthand:\nSELECT * FROM users\nWHERE country IN ('Nepal', 'India', 'Japan');\n\n-- BETWEEN (inclusive):\nSELECT * FROM products WHERE price BETWEEN 10.00 AND 50.00;\n\n-- NULL checks:\nSELECT * FROM users WHERE phone IS NULL;       -- no phone number\nSELECT * FROM users WHERE deleted_at IS NOT NULL; -- soft-deleted rows\n\n-- WRONG: this never returns anything\nSELECT * FROM users WHERE phone = NULL;",
    tip: "Before running any UPDATE or DELETE in production, first run the equivalent SELECT with the exact same WHERE clause. Verify the row count and spot-check a few rows. This two-second habit has saved countless engineers from destroying production data. Many teams require this as a mandatory step in their runbook.",
  },
  {
    id: 7,
    section: "Querying",
    title: "INSERT",
    tagline: "Add one or more new rows to a table.",
    description:
      "INSERT INTO adds new rows to a table. You specify the table name, the columns you are setting, and the corresponding values. Columns you omit get their DEFAULT value (if one is defined) or NULL — if the column is NOT NULL with no default, the INSERT fails.\n\nYou can insert multiple rows in a single statement by providing multiple value groups separated by commas. This is significantly faster than individual INSERTs because it reduces round-trips to the database.\n\nINSERT ... ON DUPLICATE KEY UPDATE (MySQL) or INSERT ... ON CONFLICT DO UPDATE (PostgreSQL) is the upsert pattern: insert a row if it doesn't exist, update it if it does. This is very useful for operations like \"increment a counter if the row exists, create it with count=1 if it doesn't\".\n\nINSERT ... SELECT copies rows from one query result directly into another table. Useful for data migrations and backups.\n\nSQL injection: never build an INSERT statement by concatenating user input into a SQL string. Use parameterised queries (prepared statements) — your database driver or ORM handles this. Concatenation allows an attacker to inject arbitrary SQL and destroy or read your data.",
    example:
      "-- Single row insert:\nINSERT INTO users (name, email)\nVALUES ('Rajan', 'rajan@example.com');\n\n-- Multi-row insert (much faster than 3 separate INSERTs):\nINSERT INTO users (name, email) VALUES\n  ('Aisha',  'aisha@example.com'),\n  ('Carlos', 'carlos@example.com'),\n  ('Mei',    'mei@example.com');\n\n-- Upsert (MySQL): insert or update page view counter:\nINSERT INTO page_views (page_slug, views)\nVALUES ('home', 1)\nON DUPLICATE KEY UPDATE views = views + 1;\n\n-- Upsert (PostgreSQL):\nINSERT INTO page_views (page_slug, views)\nVALUES ('home', 1)\nON CONFLICT (page_slug)\nDO UPDATE SET views = page_views.views + 1;\n\n-- INSERT ... SELECT (copy active users to archive):\nINSERT INTO users_archive (id, name, email)\nSELECT id, name, email FROM users\nWHERE deleted_at IS NOT NULL;\n\n-- NEVER do this (SQL injection risk):\n-- query = \"INSERT INTO users (name) VALUES ('\" + userInput + \"')\"",
    tip: "After an INSERT, most databases let you retrieve the auto-generated primary key immediately. In MySQL: SELECT LAST_INSERT_ID(). In PostgreSQL: add RETURNING id to your INSERT statement. Most ORMs expose this automatically. Knowing the new ID is essential for then inserting related rows.",
  },
  {
    id: 8,
    section: "Querying",
    title: "UPDATE",
    tagline: "Modify the values of existing rows — always with a WHERE clause.",
    description:
      "UPDATE changes the values of one or more columns in rows that match a WHERE condition. It does not add new rows or remove them — it modifies existing ones.\n\nThe SET clause lists which columns to change and their new values. Multiple columns are separated by commas.\n\nThe golden rule: always include a WHERE clause. UPDATE without WHERE modifies every single row in the table. This is the kind of mistake that causes production incidents and very stressful nights. Some database clients (like MySQL Workbench) refuse to run an UPDATE without WHERE unless you disable a safe-mode setting.\n\nYou can use expressions in SET — not just literal values. SET balance = balance - 100 deducts from the current balance. SET updated_at = CURRENT_TIMESTAMP stamps the current time. These are very common patterns.\n\nUPDATE can also join to another table to use its values in the SET clause, though the syntax differs between MySQL and PostgreSQL. This is useful when you need to update rows in one table based on data in another.\n\nAffected rows: most database drivers return the number of rows actually changed by an UPDATE. If 0 rows were affected when you expected 1, the WHERE condition probably didn't match anything — which may indicate a bug (wrong ID, wrong status).",
    example:
      "-- Update a single field:\nUPDATE users\nSET email = 'new@example.com'\nWHERE id = 1;\n\n-- Update multiple columns at once:\nUPDATE users\nSET email      = 'new@example.com',\n    name       = 'Rajan Magar',\n    updated_at = CURRENT_TIMESTAMP\nWHERE id = 1;\n\n-- Arithmetic in SET:\nUPDATE accounts\nSET balance = balance - 100.00\nWHERE id = 42;\n\n-- Update based on a condition (not just one row):\nUPDATE users\nSET status = 'inactive'\nWHERE last_login_at < '2023-01-01';\n\n-- Conditional update with CASE:\nUPDATE products\nSET price = CASE\n  WHEN category = 'electronics' THEN price * 0.90  -- 10% off\n  WHEN category = 'clothing'    THEN price * 0.80  -- 20% off\n  ELSE price\nEND\nWHERE is_on_sale = TRUE;\n\n-- DANGER — no WHERE = updates ALL rows:\n-- UPDATE users SET status = 'inactive';",
    tip: "Before running an UPDATE in production, run SELECT COUNT(*) FROM table WHERE [your condition] first. Confirm the count matches how many rows you intend to update. Then run the UPDATE. This discipline prevents accidentally modifying 10,000 rows when you meant to change 1.",
  },
  {
    id: 9,
    section: "Querying",
    title: "DELETE",
    tagline: "Remove rows permanently — or use soft deletes to keep a safety net.",
    description:
      "DELETE removes rows from a table permanently. Like UPDATE, it requires a WHERE clause to target specific rows. Without WHERE, DELETE removes every row — leaving you with a completely empty table. This is the most destructive SQL statement and must be used with care.\n\nDELETE vs TRUNCATE:\n- DELETE removes rows one by one, fires any triggers, and can be rolled back inside a transaction.\n- TRUNCATE removes all rows instantly by deallocating the data pages. It is much faster on large tables, but cannot be rolled back in most databases (MySQL being an exception within a transaction) and resets auto-increment counters.\n- Use DELETE with WHERE for targeted removals. Use TRUNCATE only when you want to wipe an entire table and know exactly what you are doing.\n\nCascading deletes: if a foreign key is defined with ON DELETE CASCADE, deleting a parent row automatically deletes all child rows referencing it. For example, deleting a user automatically deletes all their posts. This is convenient but dangerous — a single DELETE can remove vastly more data than you intended. Prefer explicit deletes or ON DELETE RESTRICT (the default, which blocks deletion of a parent with children).\n\nSoft deletes are a safer alternative for most production systems. Instead of actually removing the row, you set a deleted_at timestamp column to the current time. Queries filter deleted_at IS NULL so soft-deleted rows are invisible to normal operations. Benefits: you can recover accidentally deleted data, you maintain an audit trail, and foreign key references stay intact. The downside is that tables grow larger over time and every query needs the IS NULL filter.",
    example:
      "-- Delete one specific row:\nDELETE FROM users WHERE id = 42;\n\n-- Delete rows matching a condition:\nDELETE FROM sessions WHERE expires_at < NOW();\n\n-- DANGER — deletes the entire table's data:\n-- DELETE FROM users;\n\n-- Soft delete (safer for production):\nALTER TABLE users ADD COLUMN deleted_at TIMESTAMP NULL;\n\nUPDATE users\nSET deleted_at = CURRENT_TIMESTAMP\nWHERE id = 42;\n\n-- All normal queries must filter out soft-deleted rows:\nSELECT * FROM users WHERE deleted_at IS NULL;\n\n-- To restore a soft-deleted user:\nUPDATE users SET deleted_at = NULL WHERE id = 42;\n\n-- TRUNCATE (wipe entire table, resets auto-increment):\nTRUNCATE TABLE sessions;",
    tip: "In production, prefer soft deletes unless you have a specific reason to hard-delete (GDPR erasure requests, for example). Most bugs are discovered after the fact, and soft deletes give you a recovery window. If you do hard delete, always do it inside a transaction so you can ROLLBACK if something goes wrong.",
  },
  {
    id: 10,
    section: "Querying",
    title: "ORDER BY & LIMIT",
    tagline: "Sort results and control how many rows come back.",
    description:
      "ORDER BY sorts the result set by one or more columns. You specify a column and a direction: ASC (ascending — smallest to largest, A to Z, oldest to newest) or DESC (descending — largest to smallest, Z to A, newest to oldest). ASC is the default if you omit the direction.\n\nWithout ORDER BY, the database can return rows in any order — and that order can change between queries, depending on which internal optimisation path the query planner chose. Never rely on the \"natural\" order of rows. If order matters, always specify it explicitly.\n\nYou can sort by multiple columns: ORDER BY country ASC, name ASC sorts by country first, then by name within each country.\n\nLIMIT caps the number of rows returned. This is essential for pagination and for performance — fetching 10 rows instead of 10,000 is a massive difference in memory and network usage.\n\nOFFSET skips the first N rows before returning results. LIMIT 10 OFFSET 20 returns rows 21–30. This is \"offset-based pagination\" and is simple to implement but has a performance problem at large depths: the database still has to scan and discard all the skipped rows. For deep pagination (page 5000+), cursor-based pagination (WHERE id > last_seen_id LIMIT 10) is dramatically faster.\n\nSELECT TOP n (SQL Server) and FETCH FIRST n ROWS ONLY (standard SQL) are alternative syntaxes for LIMIT in different databases.",
    example:
      "-- 10 most recently created users:\nSELECT id, name, created_at\nFROM users\nORDER BY created_at DESC\nLIMIT 10;\n\n-- 5 cheapest active products:\nSELECT name, price\nFROM products\nWHERE is_active = TRUE\nORDER BY price ASC\nLIMIT 5;\n\n-- Sort by multiple columns (country first, then name):\nSELECT name, country FROM users\nORDER BY country ASC, name ASC;\n\n-- Offset pagination — page 3, 10 rows per page:\n-- Page 1: OFFSET 0, Page 2: OFFSET 10, Page 3: OFFSET 20\nSELECT * FROM posts\nORDER BY created_at DESC\nLIMIT 10 OFFSET 20;\n\n-- Cursor-based pagination (faster at depth):\nSELECT * FROM posts\nWHERE id < 500   -- cursor: last seen id from previous page\nORDER BY id DESC\nLIMIT 10;",
    tip: "Offset pagination gets slower as the page number increases because the database scans and discards all the preceding rows on every query. For infinite scroll feeds (Twitter, Instagram), cursor-based pagination is the standard approach — it stays O(log n) regardless of page depth, as long as there is an index on the cursor column.",
  },
  {
    id: 11,
    section: "Relationships",
    title: "Foreign Key",
    tagline: "Links a column in one table to the primary key of another, enforcing referential integrity.",
    description:
      "A foreign key is a column in one table that references the primary key of another table. It creates a formal, enforced relationship: the value in the foreign key column must either exist in the referenced table or be NULL.\n\nFor example, a posts table has a user_id column that references users.id. The database enforces:\n1. You cannot insert a post with a user_id that doesn't exist in users.\n2. You cannot delete a user who still has posts (unless you configure cascading behaviour).\n\nThis prevents orphaned rows — data that references something that no longer exists.\n\nCascade options control what happens when a referenced row is deleted or updated:\n- ON DELETE RESTRICT (default): blocks the delete if child rows exist. Safest — forces you to handle the relationship explicitly.\n- ON DELETE CASCADE: automatically deletes all child rows when the parent is deleted. Convenient but dangerous — one DELETE can silently cascade and remove far more data than intended.\n- ON DELETE SET NULL: sets the foreign key column to NULL on child rows when the parent is deleted. Useful when the relationship is optional (a post whose author was deleted can still exist).\n- ON DELETE SET DEFAULT: sets the column to its default value.\n- ON UPDATE CASCADE: if the parent's primary key changes (rare with auto-increment), updates all foreign key references automatically.\n\nNaming convention: name the foreign key column after the referenced table + _id: user_id, order_id, category_id. This makes relationships obvious at a glance.",
    example:
      "CREATE TABLE users (\n  id   INT PRIMARY KEY AUTO_INCREMENT,\n  name VARCHAR(100) NOT NULL\n);\n\nCREATE TABLE posts (\n  id      INT PRIMARY KEY AUTO_INCREMENT,\n  user_id INT NOT NULL,\n  title   VARCHAR(255) NOT NULL,\n  body    TEXT,\n  FOREIGN KEY (user_id) REFERENCES users(id)\n    ON DELETE CASCADE   -- delete user -> all their posts deleted too\n);\n\nCREATE TABLE comments (\n  id      INT PRIMARY KEY AUTO_INCREMENT,\n  post_id INT NOT NULL,\n  user_id INT,          -- nullable: user can be deleted, comment stays\n  body    TEXT NOT NULL,\n  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL\n);\n\n-- This FAILS: user 999 does not exist:\nINSERT INTO posts (user_id, title) VALUES (999, 'Ghost Post');\n-- Error: Cannot add or update a child row: a foreign key constraint fails",
    tip: "Always index your foreign key columns (user_id, order_id, etc.). Without an index, any query that joins on the foreign key or deletes a parent row has to do a full table scan on the child table to find matching rows. Most databases don't add this index automatically — you need to create it manually.",
  },
  {
    id: 12,
    section: "Relationships",
    title: "INNER JOIN",
    tagline: "Combine two tables — returning only rows that have a match in both.",
    description:
      "A JOIN combines rows from two (or more) tables into a single result, based on a related column — typically a foreign key matching a primary key. INNER JOIN is the most common type.\n\nINNER JOIN returns only rows where there is a match in both tables based on the ON condition. Think of it as the intersection in a Venn diagram. If a user has no posts, they do not appear in an INNER JOIN between users and posts. If a post's user_id doesn't match any user (orphaned row), that post doesn't appear either.\n\nYou can join more than two tables in a single query — just add more JOIN clauses. Each JOIN adds another table to the result.\n\nWhen column names are the same in both tables (like id), you must prefix them with the table name or alias to avoid ambiguity: u.id, p.id. Failing to do this causes an error (\"Column 'id' in field list is ambiguous\").\n\nAliases (AS, or just a short name after the table name) make JOIN queries much more readable: FROM users u INNER JOIN posts p ON u.id = p.user_id.\n\nThe USING clause is a shorthand when the join column has the same name in both tables: JOIN posts USING (user_id) instead of JOIN posts ON users.user_id = posts.user_id.\n\nSelf-join: a table joining to itself. Used for hierarchical data like an employee table where each row has a manager_id that references another row in the same table.",
    example:
      "-- Basic: each post with its author's name:\nSELECT\n  u.name  AS author,\n  p.title AS post_title,\n  p.created_at\nFROM users u\nINNER JOIN posts p ON u.id = p.user_id\nORDER BY p.created_at DESC;\n\n-- Three-table join: post + author + category:\nSELECT\n  u.name       AS author,\n  p.title      AS post_title,\n  c.name       AS category\nFROM posts p\nINNER JOIN users      u ON u.id = p.user_id\nINNER JOIN categories c ON c.id = p.category_id\nWHERE p.is_published = TRUE;\n\n-- Self-join: employee and their manager:\nSELECT\n  e.name        AS employee,\n  m.name        AS manager\nFROM employees e\nINNER JOIN employees m ON m.id = e.manager_id;\n\n-- USING shorthand (both tables have user_id column):\nSELECT u.name, o.total\nFROM users u\nINNER JOIN orders o USING (user_id);",
    tip: "INNER JOIN is the default type — you can write just JOIN and it means INNER JOIN. But writing INNER JOIN explicitly makes your intent clear to anyone reading the query. Always use table aliases in multi-table queries. u.id is much less error-prone than id when you have four tables joined together.",
  },
  {
    id: 13,
    section: "Relationships",
    title: "LEFT JOIN",
    tagline: "Keep all rows from the left table — even if there's no matching row on the right.",
    description:
      "A LEFT JOIN (also called LEFT OUTER JOIN) returns all rows from the left table, and the matching rows from the right table. If there is no match on the right, the right-side columns come back as NULL.\n\nThe left table is the one in the FROM clause. The right table is the one after the JOIN keyword.\n\nThis is the essential difference from INNER JOIN: INNER JOIN silently drops rows with no match. LEFT JOIN preserves them, with NULLs for the missing right-side data. This distinction is critical for reports and analytics.\n\nCommon use cases:\n- Show all users including those with no orders\n- Show all products including those with no reviews\n- Count related rows per parent (including zero counts)\n- Find rows that have no related data (anti-join pattern)\n\nAnti-join pattern: LEFT JOIN + WHERE right_table.id IS NULL finds rows in the left table that have NO match in the right table. This is equivalent to NOT IN or NOT EXISTS but often more readable and sometimes more performant.\n\nRIGHT JOIN is the mirror image: all rows from the right table, NULLs where there is no left match. In practice, you can always rewrite a RIGHT JOIN as a LEFT JOIN by swapping the table order — most engineers prefer LEFT JOINs for consistency.\n\nFULL OUTER JOIN returns all rows from both tables, with NULLs where there is no match on either side. Not supported in MySQL natively (you can simulate it with UNION of LEFT JOIN and RIGHT JOIN).",
    example:
      "-- All users and their order count (including users with 0 orders):\nSELECT\n  u.name,\n  COUNT(o.id) AS order_count,\n  COALESCE(SUM(o.total), 0) AS total_spent\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.id, u.name;\n\n-- Anti-join: users who have NEVER placed an order:\nSELECT u.name, u.email\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.id IS NULL;\n\n-- Multiple LEFT JOINs:\nSELECT\n  u.name,\n  COUNT(DISTINCT o.id)  AS orders,\n  COUNT(DISTINCT r.id)  AS reviews\nFROM users u\nLEFT JOIN orders  o ON u.id = o.user_id\nLEFT JOIN reviews r ON u.id = r.user_id\nGROUP BY u.id, u.name;",
    tip: "COALESCE(value, fallback) is your best friend with LEFT JOINs. When the right side is NULL (no match), aggregate functions like SUM return NULL — not 0. COALESCE(SUM(o.total), 0) converts that NULL to 0, which is almost always what you want for display purposes.",
  },
  {
    id: 14,
    section: "Constraints & Design",
    title: "UNIQUE Constraint",
    tagline: "Guarantee no two rows share the same value in this column — enforced at the DB level.",
    description:
      "A UNIQUE constraint ensures that every value in a column (or combination of columns) is distinct across all rows in the table. The database rejects any INSERT or UPDATE that would create a duplicate.\n\nThe most common use case is email addresses on a users table — you want to prevent two accounts from sharing the same email. Without a UNIQUE constraint, this can happen due to race conditions: two registration requests arriving simultaneously can both pass an application-level check and both insert successfully.\n\nA UNIQUE column can hold NULL values (unless also marked NOT NULL). In most databases, multiple NULLs are allowed in a UNIQUE column because NULL means \"unknown\" — and two unknowns are not considered equal. This differs from a PRIMARY KEY, which cannot be NULL at all.\n\nComposite UNIQUE constraints span multiple columns — the combination must be unique, not each column individually. The classic example is a \"likes\" or \"follows\" table: (follower_id, followed_id) must be unique so a user can only follow another user once. Neither column alone needs to be unique.\n\nUnique constraints automatically create an index on that column, which also speeds up lookups by that value.\n\nAdding a UNIQUE constraint to an existing table with duplicate data will fail — you must deduplicate first.",
    example:
      "-- Single-column UNIQUE:\nCREATE TABLE users (\n  id       INT PRIMARY KEY AUTO_INCREMENT,\n  email    VARCHAR(255) UNIQUE NOT NULL,\n  username VARCHAR(50)  UNIQUE NOT NULL\n);\n\n-- This second INSERT fails:\nINSERT INTO users (email, username) VALUES ('r@x.com', 'rajan');\nINSERT INTO users (email, username) VALUES ('r@x.com', 'rajan2');\n-- Error: Duplicate entry 'r@x.com' for key 'users.email'\n\n-- Composite UNIQUE: a user can only follow another user once:\nCREATE TABLE follows (\n  follower_id INT NOT NULL,\n  followed_id INT NOT NULL,\n  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (follower_id, followed_id),  -- composite PK = unique + not null\n  FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,\n  FOREIGN KEY (followed_id) REFERENCES users(id) ON DELETE CASCADE\n);\n\n-- Add UNIQUE to existing table:\nALTER TABLE users ADD UNIQUE (email);\n\n-- Handle duplicate gracefully (MySQL):\nINSERT INTO users (email, username)\nVALUES ('r@x.com', 'rajan')\nON DUPLICATE KEY UPDATE username = 'rajan_updated';",
    tip: "Never rely only on application-level uniqueness checks. Two simultaneous requests can both pass the \"is this email taken?\" check and both insert. The UNIQUE constraint in the database is the only guarantee. Catch the duplicate key error in your application and return a friendly message like \"This email is already registered.\"",
  },
  {
    id: 15,
    section: "Constraints & Design",
    title: "NOT NULL & DEFAULT",
    tagline: "NOT NULL makes a column required; DEFAULT provides a sensible starting value.",
    description:
      "NULL in SQL means the absence of a value — not zero, not an empty string, not false. It means \"unknown\" or \"not provided\". This distinction matters because NULL behaves differently from other values: NULL = NULL evaluates to NULL (not true), and NULL in arithmetic returns NULL (1 + NULL = NULL).\n\nNOT NULL prevents a column from storing NULL. It makes the column required — every row must provide a value. If an INSERT omits a NOT NULL column that has no DEFAULT, the database rejects it with an error.\n\nDEFAULT specifies the value to use when none is provided in an INSERT. Common defaults:\n- DEFAULT 0 for counters\n- DEFAULT TRUE or DEFAULT FALSE for boolean flags\n- DEFAULT 'pending' for status columns\n- DEFAULT CURRENT_TIMESTAMP for created_at\n- DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP for updated_at (MySQL) — automatically updates on every UPDATE\n\nNULL in aggregates: COUNT(*) counts all rows including those with NULLs. COUNT(column) counts only non-NULL values. SUM, AVG, MIN, MAX all ignore NULLs. This can lead to surprising results — a SUM over a column where half the rows are NULL still works, but only sums the non-NULL values.\n\nCOALESCE(a, b, c) returns the first non-NULL argument. COALESCE(nickname, first_name, 'Anonymous') is a common pattern for displaying a user's preferred name.\n\nNULLIF(a, b) returns NULL if a equals b, otherwise returns a. Useful for avoiding division by zero: total / NULLIF(count, 0).",
    example:
      "CREATE TABLE orders (\n  id           INT PRIMARY KEY AUTO_INCREMENT,\n  user_id      INT NOT NULL,             -- required, no default\n  status       VARCHAR(20) NOT NULL\n                 DEFAULT 'pending',       -- required, defaults to pending\n  total        DECIMAL(10,2) NOT NULL,    -- required\n  notes        TEXT,                      -- optional (nullable)\n  created_at   TIMESTAMP NOT NULL\n                 DEFAULT CURRENT_TIMESTAMP,\n  updated_at   TIMESTAMP NOT NULL\n                 DEFAULT CURRENT_TIMESTAMP\n                 ON UPDATE CURRENT_TIMESTAMP  -- auto-updates on change\n);\n\n-- Works: status and timestamps use defaults:\nINSERT INTO orders (user_id, total) VALUES (1, 49.99);\n\n-- Fails: total is NOT NULL and has no default:\nINSERT INTO orders (user_id) VALUES (1);\n\n-- COALESCE for display:\nSELECT COALESCE(nickname, first_name, 'Anonymous') AS display_name\nFROM users;\n\n-- Avoid division by zero:\nSELECT total_revenue / NULLIF(order_count, 0) AS avg_order_value\nFROM stats;",
    tip: "A general principle: keep your schema as NOT NULL as possible. Nullable columns complicate every query that touches them (you always need to handle the IS NULL case), make aggregations behave unexpectedly, and signal unclear data modelling. Only allow NULL when the absence of a value has a real, distinct meaning in your domain — like a user's middle name or a product's expiry date.",
  },
  {
    id: 16,
    section: "Constraints & Design",
    title: "CHECK Constraint",
    tagline: "Validate data at the database level — your last line of defence against bad data.",
    description:
      "A CHECK constraint defines a condition that every row must satisfy. The database evaluates the condition on every INSERT and UPDATE and rejects the operation if the condition is false. This happens at the storage layer — before the data ever reaches your application.\n\nThis is the most underused feature in beginner SQL. Most developers validate data only in the application (in request handlers, form validators, or ORM hooks). But application-level validation can fail: bugs slip through, migration scripts bypass the API, direct database access skips validation entirely. CHECK constraints protect data integrity regardless of how the data arrives.\n\nCommon use cases:\n- Numeric bounds: CHECK (balance >= 0), CHECK (age BETWEEN 0 AND 150), CHECK (rating BETWEEN 1 AND 5)\n- Date logic: CHECK (ends_at > starts_at), CHECK (birth_date < CURRENT_DATE)\n- String values: CHECK (status IN ('pending', 'active', 'cancelled'))\n- Format rules: CHECK (LENGTH(password_hash) = 60) for bcrypt hashes\n\nNOTE: CHECK constraints on expressions involving CURRENT_DATE or functions can behave differently across databases and are not always enforced reliably in older MySQL versions. Test in your specific database.\n\nENUM type is an alternative to CHECK (status IN (...)), but ENUMs are harder to modify later — adding a value requires an ALTER TABLE. A VARCHAR with a CHECK constraint is more flexible.",
    example:
      "-- Numeric constraint: balance can never go negative:\nCREATE TABLE bank_accounts (\n  id      INT PRIMARY KEY AUTO_INCREMENT,\n  owner   VARCHAR(100) NOT NULL,\n  balance DECIMAL(12, 2) NOT NULL DEFAULT 0.00,\n  CHECK (balance >= 0)\n);\n\n-- Date logic constraint:\nCREATE TABLE events (\n  id        INT PRIMARY KEY AUTO_INCREMENT,\n  title     VARCHAR(255) NOT NULL,\n  starts_at DATETIME NOT NULL,\n  ends_at   DATETIME NOT NULL,\n  CHECK (ends_at > starts_at)\n);\n\n-- Status allow-list:\nCREATE TABLE orders (\n  id     INT PRIMARY KEY AUTO_INCREMENT,\n  status VARCHAR(20) NOT NULL DEFAULT 'pending',\n  CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled'))\n);\n\n-- Rating between 1 and 5:\nCREATE TABLE reviews (\n  id     INT PRIMARY KEY AUTO_INCREMENT,\n  rating TINYINT NOT NULL,\n  body   TEXT,\n  CHECK (rating BETWEEN 1 AND 5)\n);\n\n-- This INSERT fails:\nINSERT INTO bank_accounts (owner, balance) VALUES ('Rajan', -500);\n-- Error: Check constraint 'balance >= 0' is violated.",
    tip: "Think of constraints as layers of defence. Application validation handles user experience (real-time feedback). Database constraints handle integrity (absolute guarantee). You want both. Application validation prevents bad requests from reaching the database. Database constraints catch anything that slips through — from bugs, scripts, or direct access.",
  },
  {
    id: 17,
    section: "Constraints & Design",
    title: "Indexes",
    tagline: "A hidden data structure that makes query lookups dramatically faster.",
    description:
      "An index is a separate data structure maintained alongside a table to speed up data retrieval. Without an index, a query like WHERE email = 'x@x.com' requires the database to scan every single row from start to finish — an O(n) full table scan. On a 10-million-row table, that might mean examining all 10 million rows to find one. With an index on email, the database jumps directly to the matching row — O(log n) using a B-tree structure, which means a 10-million-row table requires roughly 23 comparisons instead of 10 million.\n\nIndexes are created automatically for:\n- PRIMARY KEY columns (always indexed)\n- UNIQUE constraint columns (always indexed)\n\nFor all other columns, you add indexes manually based on your query patterns. The most important columns to index are those in WHERE clauses, JOIN ON conditions, and ORDER BY clauses.\n\nB-tree index (the default): stores data in a sorted tree structure. Excellent for range queries (BETWEEN, >, <) and equality checks (=). Used for almost everything.\n\nHash index: stores a hash of the key, not the key itself. Extremely fast for equality lookups (=) but cannot be used for range queries at all. Rarely used explicitly.\n\nComposite (multi-column) index: an index on two or more columns. A composite index on (user_id, created_at) makes the query WHERE user_id = 5 ORDER BY created_at DESC very fast. The column order in a composite index matters — the index can only be used left-to-right. An index on (a, b, c) helps queries filtering on a, or a+b, or a+b+c — but not b alone.\n\nCovering index: when all columns a query needs are in the index itself, the database doesn't even need to look at the main table. This is called an index-only scan and is extremely fast.\n\nIndex trade-offs: indexes speed up reads but slow down writes. Every INSERT, UPDATE, or DELETE on an indexed column must also update the index. A table with 20 indexes can be very slow to write to. Only index what you actually query — don't index every column by default.\n\nEXPLAIN (MySQL/PostgreSQL) shows how the database plans to execute a query. If you see \"type: ALL\" in MySQL or \"Seq Scan\" in PostgreSQL, the query is doing a full table scan and you probably need an index.",
    example:
      "-- Index a frequently queried column:\nCREATE INDEX idx_users_email ON users (email);\n\n-- Composite index for a common JOIN + filter:\nCREATE INDEX idx_posts_user_created\n  ON posts (user_id, created_at DESC);\n\n-- This query now uses the composite index:\nSELECT title, created_at\nFROM posts\nWHERE user_id = 42\nORDER BY created_at DESC\nLIMIT 10;\n\n-- Check execution plan (MySQL):\nEXPLAIN SELECT * FROM users WHERE email = 'r@x.com';\n-- Look for: type = 'ref' or 'const' (good) vs 'ALL' (bad)\n\n-- Check execution plan (PostgreSQL):\nEXPLAIN ANALYZE SELECT * FROM users WHERE email = 'r@x.com';\n-- Look for: Index Scan (good) vs Seq Scan (bad)\n\n-- Drop an index:\nDROP INDEX idx_users_email ON users;\n\n-- See all indexes on a table (MySQL):\nSHOW INDEX FROM users;",
    tip: "A practical indexing strategy: start with no indexes except the automatic ones (PK + UNIQUE). Run your application and identify slow queries using slow query logs or EXPLAIN. Add indexes for the specific queries that are slow. This is better than pre-emptively indexing everything — you avoid slowing down writes for indexes that are never used.",
  },
  {
    id: 18,
    section: "Transactions",
    title: "ACID Transactions",
    tagline: "Group multiple SQL operations into one all-or-nothing unit with four safety guarantees.",
    description:
      "A transaction is a sequence of SQL operations that are treated as a single indivisible unit. Either all of them succeed and are saved permanently, or none of them do and everything is rolled back to the state before the transaction began. There is no halfway state.\n\nACID stands for four properties that every transaction must uphold:\n\nAtomicity — \"all or nothing\". If any operation in the transaction fails (error, constraint violation, application crash), all previous operations in that transaction are rolled back. A bank transfer that debits Account A and credits Account B is atomic — if the credit fails for any reason, the debit is also undone. No money disappears.\n\nConsistency — the database moves from one valid state to another valid state. All constraints (NOT NULL, UNIQUE, FOREIGN KEY, CHECK) are still satisfied after the transaction commits. A transaction that would violate any constraint is rejected entirely.\n\nIsolation — concurrent transactions do not see each other's uncommitted changes. If two users are modifying data at the same time, each sees a consistent snapshot as if the other is not there. Isolation is controlled by \"isolation levels\" — the higher the level, the stricter the isolation:\n- READ UNCOMMITTED: can see uncommitted changes from other transactions (\"dirty reads\") — almost never used\n- READ COMMITTED: only sees committed data, but a second read in the same transaction might return different results if another transaction committed between the two reads (\"non-repeatable reads\")\n- REPEATABLE READ (MySQL default): the same row always returns the same data within one transaction, even if another transaction committed a change\n- SERIALIZABLE: the strictest level — transactions execute as if they were completely sequential, eliminating all anomalies but with the lowest throughput\n\nDurability — once a transaction commits, it is permanently saved even if the server crashes immediately after. The database uses a write-ahead log (WAL) to ensure this — changes are written to a durable log before being applied, so they can be replayed after a crash.\n\nSAVEPOINT lets you create checkpoints within a transaction and roll back to them without rolling back the entire transaction. Useful for complex multi-step operations where you want to retry part of the work without starting over.\n\nDeadlocks: if two transactions each hold a lock the other needs, they both wait forever — a deadlock. The database detects this and kills one of the transactions. Your application should catch the deadlock error and retry the transaction.",
    example:
      "-- A safe bank transfer using a transaction:\nBEGIN;\n\n-- Step 1: deduct from sender\nUPDATE accounts\nSET balance = balance - 500.00\nWHERE id = 1 AND balance >= 500.00;  -- only deduct if enough balance\n\n-- Step 2: add to receiver\nUPDATE accounts\nSET balance = balance + 500.00\nWHERE id = 2;\n\n-- Both succeeded: make it permanent\nCOMMIT;\n\n-- If anything went wrong, undo everything:\n-- ROLLBACK;\n\n-- Using SAVEPOINT for partial rollback:\nBEGIN;\n\nINSERT INTO orders (user_id, total) VALUES (1, 100.00);\n\nSAVEPOINT after_order;\n\nINSERT INTO order_items (order_id, product_id, quantity) VALUES (1, 5, 2);\n\n-- Oops, product 5 is out of stock:\nROLLBACK TO SAVEPOINT after_order;\n-- The order row is still there, only the item was rolled back\n\nCOMMIT;  -- commit the order without the item",
    tip: "Keep transactions as short as possible. Long-running transactions hold locks on rows, blocking other queries from reading or writing those rows. In a busy application, a transaction that takes 5 seconds can cause a backlog of hundreds of waiting queries. Do your validation and preparation before BEGIN, and COMMIT as quickly as possible after the actual data changes.",
  },
];

export const SQL_CONCEPT_COUNT = SQL_CONCEPTS.length;
