export interface MongoConcept {
  id: number;
  section: string;
  title: string;
  tagline: string;
  description: string;
  example: string;
  tip: string;
}

export const MONGO_SECTIONS = [
  "NoSQL Fundamentals",
  "CRUD Operations",
  "Querying",
  "Aggregation",
  "Indexing",
  "Schema Design",
  "Transactions & Reliability",
  "Scaling",
] as const;

export const MONGO_CONCEPTS: MongoConcept[] = [
  // ─── NoSQL Fundamentals ───────────────────────────────────────────
  {
    id: 1,
    section: "NoSQL Fundamentals",
    title: "What is NoSQL?",
    tagline: "A family of databases that trade rigid tables for flexible, scalable data models.",
    description:
      "NoSQL stands for \"Not Only SQL\" — not a rejection of SQL, but a recognition that the relational model is not always the best fit. NoSQL databases emerged around 2007–2010 when companies like Google, Amazon, and Facebook hit the limits of what a single relational database could handle at web scale.\n\nRelational databases enforce a fixed schema: every row must have the same columns, data types are strict, and adding a column to a billion-row table is painful. They scale vertically (bigger server) which has a hard ceiling. Joining many tables gets expensive.\n\nNoSQL databases trade some of those guarantees for flexibility and horizontal scalability. The main categories:\n\nDocument stores (MongoDB, CouchDB): data is stored as JSON-like documents. No fixed schema — each document can have different fields. Great for content, user profiles, product catalogs.\n\nKey-value stores (Redis, DynamoDB): the simplest model — a dictionary. Extremely fast. Great for caches, sessions, leaderboards.\n\nWide-column stores (Cassandra, HBase): data organized into column families. Optimised for time-series data, write-heavy workloads, and massive scale across many nodes.\n\nGraph databases (Neo4j): data stored as nodes and edges. Optimised for highly connected data — social graphs, recommendation engines, fraud detection.\n\nWhen to choose NoSQL over SQL:\n- Your data shape is variable or evolving quickly (different products have different attributes)\n- You need horizontal scaling across many servers\n- You need extremely high write throughput\n- Your data is naturally hierarchical or document-shaped\n\nWhen to stick with SQL:\n- You need strong ACID guarantees across multiple related entities\n- Your data is highly relational (many-to-many, complex joins)\n- You need ad-hoc querying and reporting\n- Your team knows SQL well and scale is not an issue yet",
    example:
      "// SQL: rigid schema — every row must match exactly\n// users table: id | name | email | age\n// Cannot add a 'preferences' object without ALTER TABLE\n\n// MongoDB: flexible document — each can look different\ndb.users.insertMany([\n  {\n    name: 'Rajan',\n    email: 'rajan@x.com',\n    preferences: { theme: 'dark', language: 'np' }\n  },\n  {\n    name: 'Aisha',\n    email: 'aisha@x.com',\n    age: 25,\n    address: { city: 'Kathmandu', country: 'Nepal' }\n    // No preferences field — that is fine\n  }\n]);\n// No schema change needed. No migration. Just write.",
    tip: "The biggest misconception about NoSQL: it does not mean 'no schema'. It means schema is not enforced by the database engine — your application code becomes responsible for it. This is faster for development but dangerous at scale without schema validation. MongoDB supports JSON Schema validation you should use in production.",
  },
  {
    id: 2,
    section: "NoSQL Fundamentals",
    title: "Documents & Collections",
    tagline: "Collections are like tables; documents are like rows — but far more flexible.",
    description:
      "A document is a single record in MongoDB. It is stored as BSON (Binary JSON) — a JSON-like format that supports additional data types. Each document is a key-value map where values can be strings, numbers, booleans, arrays, nested objects, dates, or ObjectIds.\n\nA collection is a group of documents, analogous to a table in SQL. Collections do not enforce a schema by default — documents in the same collection can have completely different structures. In practice, documents in a collection are related and share most of the same fields.\n\nKey differences from SQL tables:\n- No ALTER TABLE needed to add a field. Just include it in the next insert.\n- Documents can have nested objects and arrays, eliminating many JOINs.\n- Every document automatically gets a unique _id field (the primary key).\n- A document can be up to 16MB in size.\n\nA database in MongoDB is a container for collections, just as a database in PostgreSQL is a container for tables. One MongoDB instance can host many databases.\n\nNaming conventions:\n- Collection names: lowercase, plural, camelCase or snake_case — users, blogPosts, order_items\n- Field names: camelCase is the MongoDB convention — firstName, createdAt, userId\n\nSwitching databases and collections:\n- use myapp — selects the database (creates it if it doesn't exist)\n- db.users — accesses the users collection\n- db.createCollection('users') — explicitly creates a collection with options",
    example:
      "// Switch to database:\nuse myapp\n\n// A document in the 'users' collection:\n{\n  _id: ObjectId('65f1a2b3c4d5e6f7a8b9c0d1'),\n  name: 'Rajan Magar',\n  email: 'rajan@x.com',\n  age: 28,\n  address: {\n    city: 'Kathmandu',\n    country: 'Nepal'\n  },\n  tags: ['developer', 'learner'],\n  createdAt: ISODate('2024-01-15T09:00:00Z')\n}\n\n// A document in the 'products' collection — completely different shape:\n{\n  _id: ObjectId('...'),\n  name: 'Laptop Pro',\n  price: 1299.99,\n  specs: {\n    ram: '16GB',\n    storage: '512GB SSD',\n    display: '15.6 inch'\n  },\n  inStock: true,\n  categories: ['electronics', 'computers']\n}\n\n// List all collections in the current database:\nshow collections\n\n// Create collection with validation:\ndb.createCollection('users', {\n  validator: {\n    $jsonSchema: {\n      required: ['name', 'email'],\n      properties: {\n        email: { bsonType: 'string' }\n      }\n    }\n  }\n});",
    tip: "The 16MB document size limit is almost never a problem in practice, but it guides one design decision: do not embed unbounded arrays in a document. A blog post document should not contain an array of all its comments if it could have thousands. Once a document approaches that limit, writes slow down. Put high-volume sub-documents in their own collection.",
  },
  {
    id: 3,
    section: "NoSQL Fundamentals",
    title: "BSON & Data Types",
    tagline: "MongoDB's binary storage format — a superset of JSON with richer types.",
    description:
      "BSON (Binary JSON) is the format MongoDB uses to store documents on disk and transfer them over the network. It looks like JSON but supports types that JSON does not: dates, binary data, ObjectIds, regular expressions, and 64-bit integers.\n\nCore BSON types and when to use them:\n\nString — UTF-8 text. For names, emails, status values.\n\nInt32 / Int64 — whole numbers. Int32 for counts under ~2 billion; Int64 (NumberLong) for large integers like timestamps in milliseconds.\n\nDouble — 64-bit floating point. Avoid for money (use Decimal128 instead).\n\nDecimal128 — high-precision decimal. Always use for monetary amounts to avoid floating-point rounding errors.\n\nBoolean — true or false.\n\nDate — stores a UTC moment as milliseconds since epoch. Always use Date, not strings, for timestamps. This enables date-aware operators ($gt on dates, $dateToString in aggregations).\n\nArray — an ordered list of any values, including nested documents. MongoDB can index array elements and query into them directly.\n\nObject (embedded document) — a nested key-value document. Access with dot notation: 'address.city'.\n\nObjectId — a 12-byte unique identifier auto-generated for the _id field. Encodes a timestamp, machine ID, process ID, and counter — so ObjectIds are sortable by creation time.\n\nNull — the absence of a value. Distinct from a field not existing at all.\n\nRegularExpression — stored as a native regex, usable in queries.\n\nBinary data — for storing files, images, or hashed values directly in a document (use only for small blobs — large files belong in object storage like S3).",
    example:
      "// Document showing common BSON types:\n{\n  _id:       ObjectId('65f1a2b3c4d5e6f7a8b9c0d1'),  // ObjectId\n  name:      'Rajan',                               // String\n  age:       28,                                    // Int32\n  balance:   NumberDecimal('1250.50'),               // Decimal128\n  isActive:  true,                                  // Boolean\n  score:     9.8,                                   // Double\n  tags:      ['admin', 'beta-user'],                // Array\n  address: {                                        // Embedded object\n    city:    'Kathmandu',\n    country: 'Nepal'\n  },\n  createdAt: ISODate('2024-01-15T09:00:00Z'),       // Date\n  deletedAt: null                                   // Null\n}\n\n// Querying by date range (works because it's stored as Date, not string):\ndb.users.find({\n  createdAt: {\n    $gte: ISODate('2024-01-01'),\n    $lt:  ISODate('2024-02-01')\n  }\n});\n\n// Accessing nested field with dot notation:\ndb.users.find({ 'address.city': 'Kathmandu' });\n\n// ObjectId encodes creation time:\nObjectId('65f1a2b3c4d5e6f7a8b9c0d1').getTimestamp()\n// -> ISODate('2024-03-13T...')",
    tip: "Always store dates as BSON Date objects, never as strings like '2024-01-15'. String comparison ('2024-02-01' > '2024-01-31') accidentally works for ISO 8601 strings, but you lose all date arithmetic operators, timezone conversion, and time-based index features. The moment you need to query 'all events in January', string dates become a nightmare.",
  },
  {
    id: 4,
    section: "NoSQL Fundamentals",
    title: "ObjectId & _id",
    tagline: "Every document's built-in unique identifier — auto-generated, sortable, and globally unique.",
    description:
      "Every MongoDB document must have an _id field. It acts as the primary key — unique within the collection, always indexed, and never NULL. If you do not provide _id when inserting, MongoDB generates an ObjectId automatically.\n\nObjectId anatomy (12 bytes total):\n- Bytes 0–3: Unix timestamp (seconds since epoch) — makes ObjectIds sortable by creation time\n- Bytes 4–8: Random value unique to the machine and process\n- Bytes 9–11: Incrementing counter (starts at a random value per process)\n\nThis structure guarantees global uniqueness even across distributed systems without coordination. Two different MongoDB instances can generate ObjectIds at the same millisecond and they will not collide.\n\nObjectId as a timestamp: because the first 4 bytes encode the creation time, you can extract when a document was created from its _id — without a separate createdAt field. ObjectId('65f1a2b3c4d5e6f7a8b9c0d1').getTimestamp().\n\nYou can use your own _id: MongoDB accepts any unique value as _id — a custom string, integer, UUID, or composite object. Use this when the data already has a natural unique identifier (like a username or government ID) and you want to avoid a separate index.\n\nCustom _id examples:\n- { _id: 'rajan-magar' } — use username as _id (saves a separate unique index on username)\n- { _id: { country: 'NP', code: '12345' } } — composite key\n\nReferences between collections: when document A in one collection needs to reference document B in another, store B's _id in A. This is the NoSQL equivalent of a foreign key — but without automatic enforcement. Your application must manage referential integrity.",
    example:
      "// Auto-generated ObjectId:\ndb.users.insertOne({ name: 'Rajan', email: 'r@x.com' });\n// -> { acknowledged: true, insertedId: ObjectId('65f1...') }\n\n// Extract timestamp from ObjectId:\nconst id = ObjectId('65f1a2b3c4d5e6f7a8b9c0d1');\nid.getTimestamp(); // ISODate('2024-03-13T10:42:11.000Z')\n\n// Custom _id (username as primary key):\ndb.users.insertOne({\n  _id: 'rajan-magar',   // custom string id\n  name: 'Rajan',\n  email: 'r@x.com'\n});\n\n// Find by _id:\ndb.users.findOne({ _id: ObjectId('65f1a2b3c4d5e6f7a8b9c0d1') });\ndb.users.findOne({ _id: 'rajan-magar' }); // for custom string id\n\n// Cross-collection reference (like a foreign key):\n// posts document references user:\n{\n  _id: ObjectId('...'),\n  title: 'My First Post',\n  authorId: ObjectId('65f1a2b3c4d5e6f7a8b9c0d1'), // user's _id\n  body: '...'\n}\n// To get author: db.users.findOne({ _id: post.authorId })",
    tip: "Sorting by _id is equivalent to sorting by insertion time when using ObjectIds — because the timestamp is the leading bytes. This makes _id a free creation-time sort key: db.posts.find().sort({ _id: -1 }).limit(10) retrieves the 10 most recently inserted posts without a separate createdAt index.",
  },

  // ─── CRUD Operations ──────────────────────────────────────────────
  {
    id: 5,
    section: "CRUD Operations",
    title: "insertOne & insertMany",
    tagline: "Add one or many documents to a collection in a single call.",
    description:
      "insertOne(document) adds a single document to a collection. It returns an object with acknowledged: true and the insertedId of the new document. If you include an _id in the document, MongoDB uses it; otherwise it generates an ObjectId.\n\ninsertMany([ doc1, doc2, ... ]) inserts multiple documents in a single round-trip. It returns all insertedIds. This is dramatically faster than calling insertOne in a loop — one network round-trip vs N round-trips.\n\nOrdered vs unordered inserts: by default, insertMany is ordered — it inserts documents in sequence and stops at the first error (e.g. duplicate _id). If you pass { ordered: false }, MongoDB attempts all inserts and reports all errors at the end, even if some succeeded. Use unordered for bulk imports where you want to skip duplicates rather than abort.\n\nAutomatic schema: collections do not need to be created before inserting. The first insert into a collection creates it automatically. Same for databases — use myapp followed by an insert creates the database.\n\nInsert vs upsert: insertOne will fail with a duplicate key error if a document with that _id already exists. To insert-or-update, use updateOne with the upsert option.\n\nWrite concern: controls how many nodes in a replica set must confirm the write before MongoDB returns success. { writeConcern: { w: 'majority' } } waits for a majority of replica set members to acknowledge — the safest option for critical data.",
    example:
      "// Insert a single document:\ndb.users.insertOne({\n  name:      'Rajan Magar',\n  email:     'rajan@x.com',\n  createdAt: new Date()\n});\n// Returns: { acknowledged: true, insertedId: ObjectId('...') }\n\n// Insert with a custom _id:\ndb.users.insertOne({\n  _id:   'rajan-magar',\n  name:  'Rajan',\n  email: 'rajan@x.com'\n});\n\n// Insert multiple documents (one round-trip):\ndb.users.insertMany([\n  { name: 'Aisha',  email: 'aisha@x.com',  role: 'admin'  },\n  { name: 'Carlos', email: 'carlos@x.com', role: 'user'   },\n  { name: 'Mei',    email: 'mei@x.com',    role: 'user'   },\n]);\n// Returns: { acknowledged: true, insertedIds: { 0: ObjectId, 1: ObjectId, 2: ObjectId } }\n\n// Unordered bulk insert — skip duplicates, don't abort:\ndb.products.insertMany(products, { ordered: false });\n\n// With write concern (wait for majority replica confirmation):\ndb.orders.insertOne(\n  { userId: id, total: 99.99 },\n  { writeConcern: { w: 'majority' } }\n);",
    tip: "Never loop insertOne in application code when inserting multiple documents. A loop of 1000 insertOne calls costs 1000 network round-trips. One insertMany call costs 1. At 1ms per round-trip, that is 1 second vs 1ms. For truly large bulk imports (millions of documents), use mongoimport or the Bulk API for maximum throughput.",
  },
  {
    id: 6,
    section: "CRUD Operations",
    title: "find & findOne",
    tagline: "Read documents from a collection — with or without filters.",
    description:
      "find(filter) returns a cursor — a pointer to the matching documents. A cursor is lazy: it doesn't transfer all documents immediately. You iterate over it or chain methods (sort, limit, skip) before fetching. Call .toArray() or iterate with forEach to get the actual documents.\n\nfindOne(filter) returns the first matching document directly (not a cursor), or null if none found. Use it when you expect exactly one result — looking up by _id, email, or any unique field.\n\nThe filter is an object that specifies the conditions. An empty filter {} matches all documents. A filter with multiple fields is an implicit AND — all conditions must match.\n\nAccessing nested fields: use dot notation in strings. { 'address.city': 'Kathmandu' } matches documents where address.city equals 'Kathmandu'. Without quotes on the dot path, JavaScript would interpret it as a nested object.\n\nQuerying inside arrays: if a field is an array, MongoDB automatically checks if any array element matches the filter value. { tags: 'admin' } matches any document where the tags array contains 'admin' — you do not need a special operator.\n\nCursor methods:\n- .sort({ field: 1 }) — ascending (1) or descending (-1)\n- .limit(n) — return at most n documents\n- .skip(n) — skip first n documents (for pagination)\n- .count() — count matching documents (deprecated in newer drivers; use countDocuments)\n- .toArray() — fetch all results into memory as an array\n- .forEach(fn) — iterate one document at a time",
    example:
      "// Find all documents (returns cursor):\ndb.users.find({});\n\n// Find with a filter:\ndb.users.find({ role: 'admin' });\n\n// Find one by _id (most common lookup):\ndb.users.findOne({ _id: ObjectId('65f1a2b3c4d5e6f7a8b9c0d1') });\n\n// Find one by unique field:\ndb.users.findOne({ email: 'rajan@x.com' });\n\n// Multiple conditions (implicit AND):\ndb.users.find({ role: 'admin', isActive: true });\n\n// Nested field (dot notation):\ndb.users.find({ 'address.city': 'Kathmandu' });\n\n// Array field — finds documents where tags includes 'admin':\ndb.users.find({ tags: 'admin' });\n\n// Sort, limit, skip:\ndb.posts\n  .find({ isPublished: true })\n  .sort({ createdAt: -1 })\n  .limit(10)\n  .skip(20);   // page 3 of 10 results per page\n\n// Count matching documents:\ndb.users.countDocuments({ role: 'admin' });\n\n// Iterate with forEach (memory-efficient for large results):\ndb.users.find({ isActive: true }).forEach(user => {\n  print(user.name);\n});",
    tip: "findOne returns null when nothing matches — not an error. Always check for null before accessing properties: const user = await db.users.findOne(...); if (!user) return res.status(404).json({ error: 'Not found' }). Accessing user.name when user is null throws a TypeError that crashes your endpoint.",
  },
  {
    id: 7,
    section: "CRUD Operations",
    title: "Query Operators",
    tagline: "Filter documents with conditions beyond simple equality — ranges, lists, patterns, and logic.",
    description:
      "Query operators let you express complex filter conditions. They are prefixed with $ and go inside the filter object.\n\nComparison operators:\n- $eq: { age: { $eq: 25 } } — equal to (same as { age: 25 })\n- $ne: not equal\n- $gt / $gte: greater than / greater than or equal\n- $lt / $lte: less than / less than or equal\n- $in: { role: { $in: ['admin', 'moderator'] } } — value is in the array\n- $nin: value is NOT in the array\n\nLogical operators:\n- $and: [ condition1, condition2 ] — both must be true. Implicit AND (multiple fields) is usually clearer.\n- $or: [ condition1, condition2 ] — at least one must be true\n- $not: { age: { $not: { $gt: 18 } } } — negates a condition\n- $nor: [ c1, c2 ] — none must be true\n\nElement operators:\n- $exists: { phone: { $exists: true } } — field is present in the document\n- $type: { age: { $type: 'number' } } — field has a specific BSON type\n\nArray operators:\n- $all: { tags: { $all: ['admin', 'active'] } } — array contains all listed values\n- $size: { tags: { $size: 3 } } — array has exactly this many elements\n- $elemMatch: { scores: { $elemMatch: { $gt: 80, $lt: 90 } } } — at least one array element satisfies all given conditions\n\nText and regex:\n- $regex: { name: { $regex: /^Raj/i } } — matches a regex pattern. Prefix queries (/^Raj/) use an index; arbitrary patterns do not.\n- $text: requires a text index; enables full-text search with stemming and stop words.",
    example:
      "// Comparison:\ndb.products.find({ price: { $lt: 100 } });\ndb.products.find({ price: { $gte: 50, $lte: 200 } });\ndb.users.find({ role: { $in: ['admin', 'moderator'] } });\n\n// OR condition:\ndb.users.find({\n  $or: [\n    { country: 'Nepal' },\n    { country: 'Japan' }\n  ]\n});\n\n// Exists check (user has a phone number):\ndb.users.find({ phone: { $exists: true } });\n\n// Array operators:\ndb.posts.find({ tags: { $all: ['mongodb', 'tutorial'] } });\ndb.posts.find({ tags: { $size: 3 } });\n\n// elemMatch: find users with a score between 80 and 90:\ndb.students.find({\n  scores: { $elemMatch: { $gt: 80, $lt: 90 } }\n});\n\n// Regex (case-insensitive prefix search):\ndb.users.find({ name: { $regex: /^raj/i } });\n\n// NOT operator:\ndb.users.find({ age: { $not: { $lt: 18 } } });\n// Returns users where age >= 18 OR age field does not exist",
    tip: "The $in operator is the NoSQL equivalent of SQL's IN (...) and is much cleaner than a long $or chain. { status: { $in: ['pending', 'processing'] } } replaces three $or clauses. It also performs better than $or because the query planner can optimise $in against an index more efficiently than multiple $or conditions.",
  },
  {
    id: 8,
    section: "CRUD Operations",
    title: "updateOne & Update Operators",
    tagline: "Modify specific fields in an existing document without replacing the whole thing.",
    description:
      "updateOne(filter, update) modifies the first document matching the filter. updateMany(filter, update) modifies all matching documents. Neither replaces the entire document — they apply targeted changes using update operators.\n\nCritical rule: always use update operators (like $set). If you pass a plain object without an operator — updateOne(filter, { name: 'New' }) — MongoDB replaces the entire document with { name: 'New' }, deleting all other fields. This is the most common destructive mistake with MongoDB updates.\n\nCore update operators:\n- $set: { $set: { name: 'Rajan', age: 28 } } — set specific fields. Creates the field if it doesn't exist.\n- $unset: { $unset: { tempField: '' } } — remove a field from the document\n- $inc: { $inc: { views: 1, score: -5 } } — increment or decrement a numeric field atomically\n- $push: { $push: { tags: 'new-tag' } } — append a value to an array\n- $pull: { $pull: { tags: 'old-tag' } } — remove all matching values from an array\n- $addToSet: { $addToSet: { tags: 'unique-tag' } } — append to an array only if the value is not already present\n- $pop: { $pop: { items: 1 } } — remove the last (1) or first (-1) element from an array\n- $rename: { $rename: { 'oldName': 'newName' } } — rename a field\n- $currentDate: { $currentDate: { updatedAt: true } } — set a field to the current date\n\nUpsert: pass { upsert: true } as the third argument. If no document matches the filter, MongoDB creates a new one. The new document is built from the filter conditions plus the update operations.",
    example:
      "// Set specific fields (does NOT replace the document):\ndb.users.updateOne(\n  { _id: ObjectId('65f1...') },\n  { $set: { name: 'Rajan Magar', updatedAt: new Date() } }\n);\n\n// Increment a counter atomically:\ndb.posts.updateOne(\n  { _id: postId },\n  { $inc: { views: 1 } }\n);\n\n// Add a tag only if not already present:\ndb.users.updateOne(\n  { _id: userId },\n  { $addToSet: { tags: 'verified' } }\n);\n\n// Remove a field:\ndb.users.updateOne(\n  { _id: userId },\n  { $unset: { resetToken: '' } }\n);\n\n// DANGER: this REPLACES the entire document!\n// db.users.updateOne({ _id: userId }, { name: 'New' });\n// -> Document becomes { _id: ..., name: 'New' } — everything else deleted!\n\n// Upsert: create if not found, update if found:\ndb.userStats.updateOne(\n  { userId: userId },\n  { $inc: { loginCount: 1 }, $currentDate: { lastLogin: true } },\n  { upsert: true }\n);\n\n// Update all matching documents:\ndb.users.updateMany(\n  { role: 'guest' },\n  { $set: { isActive: false } }\n);",
    tip: "$inc is atomic — it reads and writes the value in a single operation with no race condition. If two requests both $inc views on the same post simultaneously, both increments are guaranteed to apply. This is the correct way to implement counters. The application-level pattern (read → add 1 → write) is NOT atomic and will lose increments under concurrent load.",
  },
  {
    id: 9,
    section: "CRUD Operations",
    title: "deleteOne & deleteMany",
    tagline: "Remove documents by filter — always verify your filter first.",
    description:
      "deleteOne(filter) removes the first document that matches the filter. deleteMany(filter) removes all matching documents. Both return an object with deletedCount showing how many documents were removed.\n\nThe golden rule: always verify your filter before deleting. Run a find with the same filter first and confirm the result set. deleteMany({}) deletes every document in the collection — the equivalent of SQL's DELETE without WHERE.\n\ndeleteOne vs deleteMany:\n- Use deleteOne when you are certain there is only one match (deleting by _id, for example)\n- Use deleteMany to remove a batch (deleting all expired sessions, all soft-deleted records older than 30 days)\n\nSoft deletes are the safer production pattern. Instead of physically removing documents, set a deletedAt field and filter it out of all queries. This gives you a recovery window, maintains referential integrity, and provides an audit trail. Hard deletes should only be used for GDPR erasure requests or data that genuinely has no value after removal.\n\ndrop() removes the entire collection including its indexes — faster than deleteMany({}) for full wipe, but unrecoverable. Use only in test teardown or deliberate destructive operations.\n\nFinding deleted documents in soft-delete system: all normal queries add { deletedAt: null } or { deletedAt: { $exists: false } } to the filter. Partial indexes (indexes with a filter expression) can make this extremely efficient — an index with { deletedAt: { $exists: false } } in its partial filter expression only indexes active documents.",
    example:
      "// Delete one by _id (safest pattern):\ndb.users.deleteOne({ _id: ObjectId('65f1a2b3c4d5e6f7a8b9c0d1') });\n// Returns: { acknowledged: true, deletedCount: 1 }\n\n// Delete many (expired sessions):\ndb.sessions.deleteMany({\n  expiresAt: { $lt: new Date() }\n});\n\n// DANGER: deletes ALL documents:\n// db.users.deleteMany({});\n\n// Soft delete (recommended for production):\ndb.users.updateOne(\n  { _id: userId },\n  { $set: { deletedAt: new Date() } }\n);\n\n// Query active (non-deleted) users:\ndb.users.find({ deletedAt: { $exists: false } });\n// OR:\ndb.users.find({ deletedAt: null });\n\n// Restore a soft-deleted user:\ndb.users.updateOne(\n  { _id: userId },\n  { $unset: { deletedAt: '' } }\n);\n\n// Drop the entire collection (irreversible):\ndb.tempData.drop();\n\n// Verify before deleting (always do this first):\ndb.sessions.countDocuments({ expiresAt: { $lt: new Date() } });\n// Confirm count, then run deleteMany",
    tip: "Always run countDocuments with the same filter before a deleteMany in production. A 5-second check that shows 150 documents matches your expectation of ~150 expired sessions. Finding 1,500,000 documents tells you the filter is wrong. This habit prevents the kind of incident that ends careers.",
  },

  // ─── Querying ─────────────────────────────────────────────────────
  {
    id: 10,
    section: "Querying",
    title: "Projection & Sorting",
    tagline: "Control which fields come back and in what order — essential for performance.",
    description:
      "Projection tells MongoDB which fields to include or exclude in the result. By default, find returns all fields. With projection, you return only what you need — reducing network payload and memory use.\n\nInclusion projection: { field: 1 } includes only the listed fields (plus _id by default). All unlisted fields are excluded.\n\nExclusion projection: { field: 0 } excludes listed fields. All other fields are included. You cannot mix inclusions and exclusions in one projection (except for _id).\n\nExcluding _id: { _id: 0, name: 1, email: 1 } — the only valid mix of 0 and 1 is excluding _id while including other fields.\n\nWhen to use projection:\n- API responses: never return password hashes, internal flags, or sensitive fields to clients\n- Performance: if a document has 50 fields but your query only needs 3, projection avoids transferring the other 47\n- Covered queries: if all projected fields are in a compound index, MongoDB can return the result entirely from the index without reading the main collection\n\nProjecting nested fields: { 'address.city': 1 } returns only the city field inside the address subdocument.\n\nSorting: .sort({ field: 1 }) for ascending, .sort({ field: -1 }) for descending. Multiple fields: .sort({ country: 1, name: 1 }) — sort by country first, then by name within each country.\n\nFor sort performance: sorting on an indexed field avoids an in-memory sort. Without an index, MongoDB sorts all matching documents in memory. There is a 100MB limit on in-memory sort — queries that exceed it fail unless you add an index or use .allowDiskUse(true).",
    example:
      "// Return only name and email (excludes all other fields):\ndb.users.find({}, { name: 1, email: 1 });\n// Result: { _id: ..., name: 'Rajan', email: 'r@x.com' }\n\n// Include name and email, exclude _id:\ndb.users.find({}, { _id: 0, name: 1, email: 1 });\n// Result: { name: 'Rajan', email: 'r@x.com' }\n\n// Exclude a sensitive field (return everything except passwordHash):\ndb.users.find({}, { passwordHash: 0, resetToken: 0 });\n\n// Project a nested field:\ndb.users.find({}, { name: 1, 'address.city': 1 });\n// Result: { _id: ..., name: 'Rajan', address: { city: 'Kathmandu' } }\n\n// Sort ascending by name:\ndb.users.find().sort({ name: 1 });\n\n// Sort descending by createdAt (newest first):\ndb.posts.find().sort({ createdAt: -1 });\n\n// Multi-key sort (country ASC, name ASC within each country):\ndb.users.find().sort({ country: 1, name: 1 });\n\n// Combined: filter + project + sort + limit (the full pattern):\ndb.products\n  .find({ isActive: true }, { name: 1, price: 1, _id: 0 })\n  .sort({ price: 1 })\n  .limit(20);",
    tip: "Never return sensitive fields in API responses without explicit exclusion in the projection. A common security bug: a developer adds a passwordHash field to the users collection and forgets to exclude it from every find. The safe default is an explicit inclusion projection — return only the fields you know are safe, never return everything and selectively exclude.",
  },

  // ─── Aggregation ──────────────────────────────────────────────────
  {
    id: 11,
    section: "Aggregation",
    title: "Aggregation Pipeline",
    tagline: "A multi-stage data processing pipeline — MongoDB's answer to SQL's GROUP BY, JOIN, and more.",
    description:
      "The aggregation pipeline is the most powerful feature in MongoDB. It processes documents through a sequence of stages — each stage transforms its input and passes the result to the next. This enables complex analytics, transformations, and joins entirely inside the database.\n\ndb.collection.aggregate([ stage1, stage2, stage3 ]) takes an array of stage objects. Documents flow through in order.\n\nCore stages:\n\n$match — filter documents. Equivalent to WHERE. Always put $match as early as possible to reduce the number of documents flowing through later stages. A $match on an indexed field at the start is extremely fast.\n\n$project — reshape documents: include/exclude fields, compute new fields, rename fields. More powerful than find projection — can compute expressions, concatenate strings, extract date parts.\n\n$group — group documents by a key and apply aggregate operators. Equivalent to GROUP BY + aggregates. The _id field of $group specifies the grouping key.\n\n$sort — sort documents. Equivalent to ORDER BY. Sorting on an indexed field before $group is fast.\n\n$limit / $skip — control result count. Use $limit early to reduce pipeline work when you only need the top N.\n\n$unwind — deconstructs an array field — turns one document with an array of N elements into N separate documents, one per element. Essential before grouping on array contents.\n\n$lookup — joins another collection. Equivalent to LEFT JOIN.\n\n$addFields — add or overwrite fields without removing others. Simpler than $project when you just want to add fields.\n\n$count — counts documents and outputs a single document with the count.\n\nPipeline optimization: MongoDB optimizes some pipelines automatically (e.g. $match + $sort before $group can use an index). Always use $match first to filter early.",
    example:
      "// Count orders per status:\ndb.orders.aggregate([\n  { $group: {\n      _id: '$status',\n      count: { $sum: 1 }\n  }}\n]);\n// [{ _id: 'pending', count: 42 }, { _id: 'shipped', count: 137 }]\n\n// Total revenue per user (filter + group + sort):\ndb.orders.aggregate([\n  { $match: { status: 'delivered' } },          // stage 1: filter\n  { $group: {                                    // stage 2: group\n      _id: '$userId',\n      totalRevenue: { $sum: '$total' },\n      orderCount:   { $sum: 1 },\n      avgOrder:     { $avg: '$total' }\n  }},\n  { $sort: { totalRevenue: -1 } },              // stage 3: sort\n  { $limit: 10 }                                // stage 4: top 10\n]);\n\n// $addFields: add a computed field:\ndb.products.aggregate([\n  { $addFields: {\n      priceWithTax: { $multiply: ['$price', 1.13] }\n  }}\n]);\n\n// $unwind: one document per tag:\ndb.posts.aggregate([\n  { $unwind: '$tags' },\n  { $group: { _id: '$tags', count: { $sum: 1 } } },\n  { $sort: { count: -1 } }\n]);\n// -> [{ _id: 'mongodb', count: 42 }, { _id: 'tutorial', count: 38 }, ...]",
    tip: "The single most important aggregation performance rule: put $match as the first stage whenever possible, and put $match on indexed fields. If $match appears after $group, you are grouping millions of documents and then discarding most. If $match is first, you reduce the documents entering $group from millions to thousands. This can be a 100× speed difference.",
  },
  {
    id: 12,
    section: "Aggregation",
    title: "$group & Accumulator Operators",
    tagline: "Collapse many documents into grouped summaries with counts, sums, averages, and more.",
    description:
      "$group is the core aggregation stage. It groups input documents by a specified _id expression and computes accumulated values for each group using accumulator operators.\n\nThe _id field of $group defines the grouping key:\n- { $group: { _id: '$status' } } — one group per distinct status value\n- { $group: { _id: null } } — all documents in one group (aggregate across the whole collection)\n- { $group: { _id: { year: { $year: '$createdAt' }, month: { $month: '$createdAt' } } } } — group by year+month\n\nAccumulator operators (used inside $group):\n- $sum: 1 — count documents in each group\n- $sum: '$amount' — sum a numeric field\n- $avg: '$amount' — average value\n- $min / $max: minimum or maximum value\n- $first / $last: first or last value in the group (only meaningful if documents are pre-sorted)\n- $push: accumulate all values into an array (e.g. collect all order IDs for each user)\n- $addToSet: like $push but deduplicates\n- $count — equivalent to $sum: 1\n\n$project after $group is used to rename the _id field or compute additional output fields.\n\n$having equivalent: use a $match stage after $group to filter groups by their computed values — exactly like HAVING in SQL. { $match: { totalRevenue: { $gt: 1000 } } } after a $group keeps only high-value groups.",
    example:
      "// Total count and revenue per status:\ndb.orders.aggregate([\n  { $group: {\n      _id: '$status',\n      count:   { $sum: 1 },\n      revenue: { $sum: '$total' },\n      avgOrder:{ $avg: '$total' },\n      maxOrder:{ $max: '$total' }\n  }}\n]);\n\n// Overall totals (all documents in one group):\ndb.orders.aggregate([\n  { $group: {\n      _id:          null,\n      totalOrders:  { $sum: 1 },\n      totalRevenue: { $sum: '$total' }\n  }}\n]);\n\n// Group by year and month:\ndb.orders.aggregate([\n  { $group: {\n      _id: {\n        year:  { $year:  '$createdAt' },\n        month: { $month: '$createdAt' }\n      },\n      revenue: { $sum: '$total' },\n      orders:  { $sum: 1 }\n  }},\n  { $sort: { '_id.year': 1, '_id.month': 1 } }\n]);\n\n// $having equivalent: groups with revenue > 1000:\ndb.orders.aggregate([\n  { $group: { _id: '$userId', revenue: { $sum: '$total' } } },\n  { $match: { revenue: { $gt: 1000 } } }   // filter groups\n]);\n\n// Collect all product IDs per order:\ndb.orderItems.aggregate([\n  { $group: {\n      _id: '$orderId',\n      products: { $push: '$productId' }\n  }}\n]);",
    tip: "{ $group: { _id: null, total: { $sum: '$amount' } } } is the aggregation equivalent of SELECT SUM(amount) FROM table — no grouping, just one aggregate over the whole collection. This is the pattern for dashboard total cards ('Total Revenue: $1,234,567') without any grouping key.",
  },
  {
    id: 13,
    section: "Aggregation",
    title: "$lookup (Join)",
    tagline: "Join another collection in the aggregation pipeline — MongoDB's LEFT JOIN.",
    description:
      "$lookup performs a left outer join between the current collection and another. For each document in the pipeline, it looks up matching documents in the foreign collection and adds them as a nested array.\n\nBasic $lookup syntax:\n- from: the collection to join\n- localField: the field in the current document to match on\n- foreignField: the field in the foreign collection to match against\n- as: the name of the new array field containing matched documents\n\nIf there are no matches, the as array is empty — this is the LEFT JOIN behaviour. An INNER JOIN equivalent requires adding a $match after $lookup to filter out empty arrays: { $match: { joinedField: { $ne: [] } } }.\n\n$unwind after $lookup: $lookup always produces an array in the as field. If you joined on a one-to-one relationship (like looking up a single author by ID), use $unwind to flatten the single-element array into an embedded document.\n\nPipeline $lookup (more powerful): instead of simple equality, you can use a pipeline sub-expression in $lookup to apply filters, projections, and even nested aggregations on the joined collection before merging. This is the syntax for complex joins.\n\nPerformance: $lookup on large collections is expensive. The foreign field must be indexed for $lookup to be fast — without an index, $lookup does a collection scan for every document. Add an index on the foreignField before using $lookup in production.",
    example:
      "// Join orders with user details:\ndb.orders.aggregate([\n  { $lookup: {\n      from:         'users',\n      localField:   'userId',\n      foreignField: '_id',\n      as:           'user'\n  }},\n  { $unwind: '$user' }    // flatten single-element array\n]);\n// Each order now has: { ..., user: { _id, name, email } }\n\n// INNER JOIN equivalent (only orders with a matching user):\ndb.orders.aggregate([\n  { $lookup: {\n      from: 'users', localField: 'userId',\n      foreignField: '_id', as: 'user'\n  }},\n  { $match: { user: { $ne: [] } } }\n]);\n\n// Three-collection join (orders -> users + products):\ndb.orders.aggregate([\n  { $lookup: {\n      from: 'users', localField: 'userId',\n      foreignField: '_id', as: 'user'\n  }},\n  { $lookup: {\n      from: 'products', localField: 'productId',\n      foreignField: '_id', as: 'product'\n  }},\n  { $unwind: '$user' },\n  { $unwind: '$product' },\n  { $project: {\n      'user.name': 1, 'product.name': 1, total: 1\n  }}\n]);\n\n// Pipeline $lookup with filter on joined collection:\ndb.users.aggregate([\n  { $lookup: {\n      from: 'orders',\n      let:  { uid: '$_id' },\n      pipeline: [\n        { $match: { $expr: { $eq: ['$userId', '$$uid'] } } },\n        { $match: { status: 'delivered' } },\n        { $project: { total: 1 } }\n      ],\n      as: 'deliveredOrders'\n  }}\n]);",
    tip: "If you find yourself using $lookup frequently for the same relationship, that is a signal to reconsider your schema. MongoDB performs best when related data is embedded in the same document. $lookup is designed for occasional cross-collection queries, not for replacing every JOIN in a relational model. Heavy $lookup usage often means your data model is still thinking relationally.",
  },

  // ─── Indexing ─────────────────────────────────────────────────────
  {
    id: 14,
    section: "Indexing",
    title: "Indexes in MongoDB",
    tagline: "B-tree structures that make queries fast — create them on every field you filter or sort by.",
    description:
      "MongoDB indexes work the same way as SQL B-tree indexes — they maintain a sorted data structure of field values with pointers to documents, enabling O(log n) lookups instead of O(n) collection scans.\n\nBy default, every collection has exactly one index: the _id index. Every other field you query, sort, or join on must be manually indexed.\n\nCreating an index: db.collection.createIndex({ field: 1 }) — 1 for ascending, -1 for descending. For most single-field indexes the direction doesn't matter for equality queries, but matters for sort-only queries.\n\nIndex types:\n- Single field: { email: 1 } — the standard case\n- Compound: { userId: 1, createdAt: -1 } — multiple fields (order matters)\n- Multikey: automatically created when the indexed field is an array. MongoDB indexes each array element individually.\n- Text: { content: 'text' } — enables full-text search with $text operator\n- Hashed: { _id: 'hashed' } — used for hash-based sharding; equality only, no range queries\n- Geospatial: { location: '2dsphere' } — for geographic queries ($near, $within)\n- TTL: { expiresAt: 1 }, { expireAfterSeconds: 0 } — automatically deletes documents when the date field passes\n- Wildcard: { '$**': 1 } — indexes all fields; useful for dynamic schemas but expensive\n\nListing and dropping indexes:\n- db.collection.getIndexes() — show all indexes\n- db.collection.dropIndex('index_name') — remove one index\n- db.collection.dropIndexes() — remove all indexes except _id\n\nExplain: db.collection.find(filter).explain('executionStats') shows whether the query used an index (IXSCAN = index scan, COLLSCAN = collection scan) and how many documents it examined.",
    example:
      "// Create a single-field index:\ndb.users.createIndex({ email: 1 });\ndb.users.createIndex({ email: 1 }, { unique: true }); // unique constraint\n\n// Compound index (userId equality + createdAt sort):\ndb.posts.createIndex({ userId: 1, createdAt: -1 });\n\n// Sparse index (only index documents where field exists):\ndb.users.createIndex(\n  { phone: 1 },\n  { sparse: true }  // documents without 'phone' are not indexed\n);\n\n// Partial index (only index active users):\ndb.users.createIndex(\n  { email: 1 },\n  { partialFilterExpression: { isActive: { $eq: true } } }\n);\n\n// TTL index (auto-delete documents 24h after createdAt):\ndb.sessions.createIndex(\n  { createdAt: 1 },\n  { expireAfterSeconds: 86400 }\n);\n\n// Text index for full-text search:\ndb.articles.createIndex({ title: 'text', body: 'text' });\ndb.articles.find({ $text: { $search: 'mongodb tutorial' } });\n\n// Check if query uses index:\ndb.users.find({ email: 'r@x.com' }).explain('executionStats');\n// Look for: 'stage': 'IXSCAN' (good) vs 'COLLSCAN' (bad)\n\n// Show all indexes:\ndb.users.getIndexes();",
    tip: "The most important field to index is the one you look up users by in your authentication flow. If every API request calls db.users.findOne({ email: req.email }), that query runs hundreds of times per second. Without an index on email, every call scans the entire users collection. One createIndex({ email: 1 }) call makes those queries instant.",
  },
  {
    id: 15,
    section: "Indexing",
    title: "Compound & Multikey Indexes",
    tagline: "Index multiple fields together, or automatically index every element of an array.",
    description:
      "Compound indexes index two or more fields together. They enable queries that filter or sort on multiple fields to use one index instead of none.\n\nCompound index key order follows the same leftmost prefix rule as SQL: an index on (a, b, c) supports queries on a, a+b, and a+b+c — but not b alone or c alone. Put equality fields before range fields before sort fields.\n\nESR rule (Equality, Sort, Range): when designing compound indexes, put Equality conditions first, Sort fields second, Range conditions last. This is the optimal order for the query planner.\n\nIndex direction in compounds: for a compound index used in sorting, the direction of each field matters. An index on (userId: 1, createdAt: -1) supports ORDER BY userId ASC, createdAt DESC. The reverse (userId: -1, createdAt: 1) supports ORDER BY userId DESC, createdAt ASC. For equality fields, direction rarely matters.\n\nMultikey indexes: when you index a field that contains an array, MongoDB creates a multikey index — it indexes each array element separately. For example, indexing the tags field (which is an array) creates an index entry for each tag in each document. A query { tags: 'admin' } uses this index to find documents where any element of tags equals 'admin'.\n\nMultikey index restrictions: you cannot create a compound index where more than one field is an array in the same document. MongoDB raises an error if you try to insert a document where two compound-indexed fields are both arrays.\n\nSparse vs partial indexes: a sparse index skips documents where the indexed field doesn't exist. A partial index skips documents that don't match a filter expression. Partial indexes are more flexible and should be preferred for most sparse scenarios.",
    example:
      "// Compound index for: filter by userId + sort by createdAt:\ndb.posts.createIndex({ userId: 1, createdAt: -1 });\n\n// This query uses the index perfectly:\ndb.posts.find({ userId: ObjectId('...') })\n  .sort({ createdAt: -1 })\n  .limit(20);\n\n// ESR rule in action:\n// Query: status = 'active' AND price range AND sort by name\ndb.products.createIndex({ status: 1, name: 1, price: 1 });\n// Equality (status) first, Sort (name) second, Range (price) last ✓\n\n// Multikey index on array field:\ndb.posts.createIndex({ tags: 1 });\n// Indexes: ['mongodb','tutorial'] -> two entries: 'mongodb', 'tutorial'\n\n// Query uses multikey index:\ndb.posts.find({ tags: 'mongodb' });     // uses index ✓\ndb.posts.find({ tags: { $all: ['mongodb', 'tutorial'] } }); // uses index ✓\n\n// Compound with array — INVALID (two array fields):\n// db.posts.createIndex({ tags: 1, categories: 1 });\n// Error if any document has both tags AND categories as arrays\n\n// Partial index (only index in-stock products):\ndb.products.createIndex(\n  { price: 1, category: 1 },\n  { partialFilterExpression: { inStock: true } }\n);\n// Smaller index, faster queries for in-stock search",
    tip: "Use explain() to verify your compound indexes are actually being used. A common mistake: creating a compound index on (a, b) but writing queries that filter only on b. The index cannot be used — b alone is not the leftmost prefix. You need a separate index on b, or to rewrite queries to always include a in the filter.",
  },
  {
    id: 16,
    section: "Indexing",
    title: "TTL Indexes",
    tagline: "Automatically expire and delete documents after a set time — built-in data lifecycle management.",
    description:
      "A TTL (Time-To-Live) index tells MongoDB to automatically delete documents once a specified amount of time has passed since a date field in the document. This removes the need for a cron job or scheduled task to clean up old data.\n\nHow it works: you create a single-field index on a Date field with the expireAfterSeconds option. A background process (TTLMonitor) runs approximately every 60 seconds, scans the TTL index, and deletes documents where the date field is older than expireAfterSeconds ago.\n\nTwo patterns:\n1. expireAfterSeconds > 0: documents expire N seconds after the date in the indexed field. { createdAt: 1 }, { expireAfterSeconds: 3600 } deletes documents 1 hour after createdAt.\n2. expireAfterSeconds: 0: documents expire at the exact date stored in the field. { expiresAt: 1 }, { expireAfterSeconds: 0 } deletes documents at the moment expiresAt is reached. This is ideal for sessions or tokens with a specific expiry time.\n\nUse cases:\n- Session tokens (expire after 30 days of inactivity)\n- Email verification tokens (expire after 24 hours)\n- Temporary files or upload records\n- Analytics events or logs older than N days\n- Rate limiting counters that reset periodically\n\nLimitations:\n- TTL only works on single-field indexes (not compound)\n- The field must be a BSON Date type or an array of Dates\n- Deletion is approximate — the monitor runs every ~60 seconds, so documents may live up to 60 seconds past their expiry time\n- TTL deletes are not instant for large backlogs — MongoDB throttles deletions to avoid overloading the server",
    example:
      "// Session expires 30 days after creation:\ndb.sessions.createIndex(\n  { createdAt: 1 },\n  { expireAfterSeconds: 60 * 60 * 24 * 30 }  // 30 days in seconds\n);\n\n// Insert a session:\ndb.sessions.insertOne({\n  userId:    ObjectId('...'),\n  token:     'abc123',\n  createdAt: new Date()  // TTL starts from here\n});\n// MongoDB auto-deletes this document 30 days after createdAt\n\n// Email verification token with specific expiry time:\ndb.verificationTokens.createIndex(\n  { expiresAt: 1 },\n  { expireAfterSeconds: 0 }  // delete AT the expiresAt time\n);\n\n// Insert a token that expires in 24 hours:\nconst tomorrow = new Date();\ntomorrow.setDate(tomorrow.getDate() + 1);\n\ndb.verificationTokens.insertOne({\n  userId:    userId,\n  token:     crypto.randomBytes(32).toString('hex'),\n  expiresAt: tomorrow  // will be deleted at this exact time\n});\n\n// Log entries older than 7 days are automatically deleted:\ndb.logs.createIndex(\n  { createdAt: 1 },\n  { expireAfterSeconds: 60 * 60 * 24 * 7 }\n);",
    tip: "TTL indexes completely replace the most common use case for cron jobs in MongoDB-backed apps: cleaning up stale sessions, expired tokens, and old temporary records. One createIndex call sets up a self-maintaining data lifecycle. No scheduler, no query, no monitoring needed.",
  },

  // ─── Schema Design ────────────────────────────────────────────────
  {
    id: 17,
    section: "Schema Design",
    title: "Embedding vs Referencing",
    tagline: "The most important MongoDB design decision: store related data together or in separate collections?",
    description:
      "In relational databases, related data is always split into separate tables and joined with foreign keys. In MongoDB, you have a choice: embed related data inside the parent document, or reference it from a separate collection.\n\nEmbedding (denormalization): store related data as nested objects or arrays inside the parent document. A user document can contain their address, preferences, and most-recent activity all in one.\n\nWhen to embed:\n- The data is always read together (you always need the address when you display the user)\n- The relationship is one-to-one or one-to-few (a user has 1 address, a post has a few tags)\n- The embedded data does not grow unboundedly\n- Atomic updates to parent and child together are important\n\nAdvantages of embedding: one query to fetch everything. Atomic writes (a single updateOne can change parent and child). No JOIN overhead. Better read performance.\n\nReferencing (normalization): store a reference (the _id) of a related document. A post stores authorId that points to a document in the users collection. To get the author, you make a second query or use $lookup.\n\nWhen to reference:\n- The related data is large and not always needed\n- The related data is shared across many documents (one user appears in thousands of post authors)\n- The array could grow without bound (a post's comments)\n- The related data is queried and updated independently\n\nAdvantages of referencing: smaller documents (faster reads when you don't need the related data). No duplication (update the user once, reflected everywhere). Enables independent querying and indexing of the related collection.\n\nHybrid: embed the most frequently accessed fields (author name, author avatar) alongside a reference to the full author document. This is the \"extended reference pattern\" — fast reads with the ability to get full detail when needed.",
    example:
      "// EMBEDDING: address is always shown with user\n// Good: small, bounded, always accessed together\n{\n  _id: ObjectId('...'),\n  name: 'Rajan',\n  email: 'r@x.com',\n  address: {              // embedded document\n    street: '123 Main St',\n    city: 'Kathmandu',\n    country: 'Nepal'\n  },\n  preferences: { theme: 'dark', language: 'en' }\n}\n\n// REFERENCING: comments live in their own collection\n// Good: unbounded array, queried/paginated independently\n// posts collection:\n{ _id: ObjectId('post1'), title: 'My Post', authorId: ObjectId('user1') }\n\n// comments collection:\n{ _id: ObjectId('...'), postId: ObjectId('post1'), body: 'Great!', userId: ObjectId('user2') }\n{ _id: ObjectId('...'), postId: ObjectId('post1'), body: 'Thanks!', userId: ObjectId('user1') }\n\n// HYBRID (extended reference): embed author name+avatar for fast display,\n// keep reference for full detail\n{\n  _id: ObjectId('post1'),\n  title: 'My Post',\n  author: {\n    _id:    ObjectId('user1'),   // reference\n    name:   'Rajan',            // cached fields for fast display\n    avatar: '/avatars/rajan.jpg'\n  }\n}",
    tip: "The golden MongoDB embedding rule: if you always query the data together, embed it. If the data has its own lifecycle, is queried independently, or is unbounded in size, reference it. A practical test: 'Would I ever want to page through this data separately?' If yes — separate collection. If no — embed.",
  },
  {
    id: 18,
    section: "Schema Design",
    title: "One-to-Many & Many-to-Many Patterns",
    tagline: "How to model the most common real-world relationships in a document database.",
    description:
      "Relational databases handle all relationships with foreign keys and JOIN tables. MongoDB requires more deliberate design — the right pattern depends on the size and access patterns of the relationship.\n\n--- One-to-Few (Embed) ---\nA user has 1–5 phone numbers. A post has 3–10 tags. These are small, bounded, and accessed with the parent. Embed as arrays in the parent document.\n\n--- One-to-Many (Reference from Child) ---\nA blog has thousands of posts. An order has hundreds of line items. The 'many' side is large, paginated, and queried independently. Store the parent's _id in each child document (post has blogId, comment has postId). Query children by parent ID with a filter.\n\n--- One-to-Many (Subset Pattern) ---\nA product has 1000 reviews, but you only ever display the 5 most recent on the product page. Embed the top 5 reviews in the product document for fast display, and store all reviews in a separate reviews collection. Update the embedded subset when a new review is posted. This avoids loading all 1000 reviews just to show 5.\n\n--- Many-to-Many ---\nStudents enrolled in courses. Users following other users. Two approaches:\n\n1. Junction collection: like a SQL JOIN table. An enrollments collection with studentId and courseId. Simple, scalable, supports additional attributes (enrolledAt, grade).\n\n2. Arrays of references: store an array of course IDs in each student document, and an array of student IDs in each course document. Simple for small sets, but maintaining both arrays in sync on every enroll/unenroll requires two updateOne calls (or a transaction).\n\n3. Asymmetric: only maintain the reference on one side — the side you query from most. Students have [ courseIds ] but courses don't have [ studentIds ]. To get all students in a course: find({ courseIds: courseId }). Requires an index on courseIds.",
    example:
      "// One-to-Few: tags embedded in post\n{\n  _id: ObjectId('...'),\n  title: 'MongoDB Guide',\n  tags: ['mongodb', 'database', 'nosql']  // small bounded array\n}\n\n// One-to-Many: comments reference post\n// comment document:\n{ postId: ObjectId('post1'), body: 'Great post!', userId: ObjectId('...') }\n\n// Query all comments for a post:\ndb.comments.find({ postId: postId }).sort({ createdAt: -1 }).limit(20);\n// Requires index: db.comments.createIndex({ postId: 1, createdAt: -1 })\n\n// Subset pattern: top 5 reviews embedded, all in reviews collection:\n// product document:\n{\n  _id: ObjectId('...'),\n  name: 'Laptop',\n  topReviews: [   // fast display subset\n    { userId: ObjectId('...'), rating: 5, body: 'Amazing!' },\n    { userId: ObjectId('...'), rating: 4, body: 'Good value' }\n  ]\n}\n// reviews collection has all reviews for full listing / analytics\n\n// Many-to-many via junction collection:\n// enrollments collection:\n{\n  studentId:  ObjectId('s1'),\n  courseId:   ObjectId('c1'),\n  enrolledAt: ISODate('2024-01-15'),\n  grade:      'A'\n}\ndb.enrollments.createIndex({ studentId: 1 });\ndb.enrollments.createIndex({ courseId: 1 });\n\n// Courses for a student:\ndb.enrollments.find({ studentId: userId });\n// Students in a course:\ndb.enrollments.find({ courseId: courseId });",
    tip: "The most common MongoDB schema mistake is using arrays of references that grow unboundedly: a user document with an array of all their post IDs. That array grows forever, making the user document larger on every post. Use a junction collection or reference from the child (post has userId) instead. The rule: large arrays belong in their own collection.",
  },

  // ─── Transactions & Reliability ───────────────────────────────────
  {
    id: 19,
    section: "Transactions & Reliability",
    title: "Transactions",
    tagline: "Multi-document ACID transactions — all or nothing across multiple collections.",
    description:
      "MongoDB 4.0+ supports multi-document ACID transactions. Before this, each individual document operation was atomic, but operations across multiple documents were not. Transactions close this gap.\n\nSingle-document atomicity (always available): a single insertOne, updateOne, or deleteOne is always atomic — either the full operation applies or none of it does. This is why embedding related data helps: updating a parent and its embedded children is always a single atomic operation.\n\nMulti-document transactions (4.0+): needed when you must atomically modify multiple documents in one or more collections. The classic example is a bank transfer: debit one account and credit another — both must succeed or neither should.\n\nTransaction basics:\n1. Start a session: const session = db.getMongo().startSession()\n2. Begin transaction: session.startTransaction()\n3. Run operations, passing session to each one\n4. Commit: session.commitTransaction()\n5. On error: session.abortTransaction()\n\nTransactions in MongoDB use a snapshot isolation level (similar to PostgreSQL's REPEATABLE READ). Within a transaction, reads see a consistent snapshot of the data as it existed at transaction start.\n\nImportant caveats:\n- Transactions have a 60-second time limit by default\n- Transactions carry higher overhead than non-transactional operations — use them only when genuinely needed\n- For standalone (non-replica set) MongoDB, transactions are not supported. Use replica set mode even in development when you need transactions.\n- Operations inside a transaction take locks; long transactions cause contention\n- Prefer schema design that avoids the need for multi-document transactions (embed related data)",
    example:
      "// Node.js multi-document transaction:\nconst session = client.startSession();\n\ntry {\n  session.startTransaction();\n\n  // Debit sender:\n  await db.collection('accounts').updateOne(\n    { _id: senderId, balance: { $gte: 500 } },\n    { $inc: { balance: -500 } },\n    { session }\n  );\n\n  // Credit receiver:\n  await db.collection('accounts').updateOne(\n    { _id: receiverId },\n    { $inc: { balance: 500 } },\n    { session }\n  );\n\n  // Record the transfer:\n  await db.collection('transfers').insertOne({\n    from: senderId, to: receiverId,\n    amount: 500, createdAt: new Date()\n  }, { session });\n\n  await session.commitTransaction();\n\n} catch (err) {\n  await session.abortTransaction();\n  throw err;\n\n} finally {\n  session.endSession();\n}\n\n// In the Mongo shell:\nconst session = db.getMongo().startSession();\nsession.startTransaction();\ndb.accounts.updateOne({ _id: 'A' }, { $inc: { balance: -100 } }, { session });\ndb.accounts.updateOne({ _id: 'B' }, { $inc: { balance:  100 } }, { session });\nsession.commitTransaction();",
    tip: "The best way to reduce transaction usage is good schema design. If you embed a user's address inside the user document, updating name+address is a single atomic updateOne — no transaction needed. Multi-document transactions are the escape hatch for when you genuinely cannot avoid cross-document atomicity, not the first tool to reach for.",
  },
  {
    id: 20,
    section: "Transactions & Reliability",
    title: "Replica Sets",
    tagline: "Automatic replication and failover — the foundation of MongoDB high availability.",
    description:
      "A replica set is a group of MongoDB instances that maintain identical copies of the same data. One node is the primary (handles all writes). The rest are secondaries (replicate from primary, can serve reads). If the primary goes down, the secondaries automatically elect a new primary within seconds — no manual intervention required.\n\nMinimum replica set: 3 nodes (1 primary + 2 secondaries, or 1 primary + 1 secondary + 1 arbiter). The odd number ensures a majority can be reached for elections. Never run a 2-node replica set — if either node goes down, no majority exists and the remaining node becomes read-only.\n\nReplication process: every write to the primary is recorded in the oplog (operations log) — a capped collection that acts like MongoDB's WAL. Secondaries continuously read the oplog and replay the operations on their own data. This is asynchronous by default.\n\nRead preferences — where reads are routed:\n- primary (default): all reads go to primary. Consistent, no replication lag.\n- primaryPreferred: primary if available, secondary otherwise.\n- secondary: reads distributed across secondaries. May return slightly stale data. Use for analytics queries that don't need the very latest data.\n- nearest: route to the node with the lowest network latency (geographic reads).\n\nWrite concern:\n- w: 1 (default): acknowledged after primary writes. Risk: data loss if primary crashes before replication.\n- w: 'majority': acknowledged after majority of nodes write. No data loss even if one node fails. Slightly higher write latency.\n\nChange streams: replica sets expose change streams — a real-time stream of all insert/update/delete events. Applications subscribe to changes and react in real-time without polling. Requires replica set mode (not standalone).",
    example:
      "// Start a replica set (mongosh):\n// Initiate with 3 members:\nrs.initiate({\n  _id: 'myReplicaSet',\n  members: [\n    { _id: 0, host: 'mongo1:27017' },\n    { _id: 1, host: 'mongo2:27017' },\n    { _id: 2, host: 'mongo3:27017' }\n  ]\n});\n\n// Check replica set status:\nrs.status();\n// Shows: primary, secondaries, health, optime, replication lag\n\n// Write concern — wait for majority:\ndb.orders.insertOne(\n  { userId: id, total: 99.99 },\n  { writeConcern: { w: 'majority', wtimeout: 5000 } }\n);\n\n// Read from secondary (stale reads OK for this analytics query):\ndb.getMongo().setReadPref('secondary');\ndb.orders.aggregate([/* heavy analytics */]);\n\n// Change stream — listen for new orders in real-time:\nconst stream = db.orders.watch([{ $match: { operationType: 'insert' } }]);\nstream.on('change', (change) => {\n  console.log('New order:', change.fullDocument);\n  // trigger notification, update cache, etc.\n});",
    tip: "Run a 3-node replica set even in development and staging, not just production. Many features require it: multi-document transactions, change streams, and proper write concern testing. Also, discovering that your deployment model doesn't support transactions in production after you've written transaction-dependent code is a painful surprise. Use the same topology everywhere.",
  },

  // ─── Scaling ──────────────────────────────────────────────────────
  {
    id: 21,
    section: "Scaling",
    title: "Sharding",
    tagline: "Horizontally partition data across multiple servers when one machine isn't enough.",
    description:
      "Sharding in MongoDB distributes data across multiple shards — each shard is a separate replica set holding a portion of the collection's data. Together, they form a sharded cluster. A mongos router receives queries, determines which shards to contact, and merges results.\n\nShard key: the field (or compound field) used to distribute documents across shards. Choosing the right shard key is the most important decision in a sharded MongoDB deployment — it cannot be changed later without migrating the entire collection.\n\nSharding strategies:\n\nHashed sharding: MongoDB hashes the shard key value and distributes documents evenly based on the hash. Best for write-heavy workloads where you need uniform distribution. Cannot do efficient range queries on the shard key.\n\nRanged sharding: documents are divided into contiguous ranges of shard key values. Efficient for range queries. Risk: monotonically increasing shard keys (like timestamp or auto-increment) cause all new writes to hit the same shard (hot shard problem).\n\nZone sharding: manually assign ranges of shard key values to specific shards. Used for geographic locality (Europe data on EU shards) or tiered storage.\n\nShard key selection rules:\n- High cardinality: enough distinct values to distribute data across shards (avoid boolean or low-cardinality fields)\n- Low frequency: avoid shard keys where a few values account for most documents\n- Avoid monotonically increasing: timestamps and ObjectIds cause write hotspots in ranged sharding (use hashed sharding for these)\n- Query isolation: ideally queries include the shard key so the router can target one shard, not broadcast to all\n\nBroadcast queries: queries without the shard key must be sent to all shards (scatter-gather), each returns results, mongos merges. This is slower than targeted queries but still works.\n\nWhen to shard: MongoDB recommends sharding when your working set (data + indexes) no longer fits in the RAM of your largest practical server, or when write throughput exceeds a single primary's capacity. Start with a single replica set and add sharding only when needed.",
    example:
      "// Enable sharding on a database:\nsh.enableSharding('myapp');\n\n// Shard a collection by userId (hashed — even distribution):\nsh.shardCollection('myapp.orders', { userId: 'hashed' });\n\n// Shard by region + createdAt (ranged — range queries on region):\nsh.shardCollection('myapp.events', { region: 1, createdAt: 1 });\n\n// Check sharding status:\nsh.status();\n// Shows: shards, chunks, balancer status, data distribution\n\n// A targeted query (includes shard key) — fast:\ndb.orders.find({ userId: ObjectId('...') });\n// -> mongos routes to exactly one shard\n\n// A broadcast query (no shard key) — slower:\ndb.orders.find({ status: 'pending' });\n// -> mongos broadcasts to all shards, merges results\n\n// Zone sharding: EU users go to EU shard:\nsh.addShardTag('shard01', 'EU');\nsh.addTagRange(\n  'myapp.users',\n  { region: 'EU', userId: MinKey },\n  { region: 'EU', userId: MaxKey },\n  'EU'\n);",
    tip: "The ObjectId is a terrible shard key for ranged sharding because it is monotonically increasing — all new documents get the same highest-range chunk, making one shard absorb all writes. For ranged sharding on ObjectId-like keys, use hashed sharding instead. Better yet, choose a shard key that reflects your access pattern: if you always query by userId, shard by userId.",
  },
];

export const MONGO_CONCEPT_COUNT = MONGO_CONCEPTS.length;
