export type EnglishExample = {
  en: string;
  np: string;
};

export type EnglishWord = {
  word: string;
  pos: string;
  meaning: string;
  meaning_np: string;
  examples: EnglishExample[];
};

export type EnglishDay = {
  day: number;
  category: string;
  words: EnglishWord[];
};

export const ENGLISH_MEANING_DAYS: EnglishDay[] = [
  {
    day: 1,
    category: "Feelings & Attitudes",
    words: [
      {
        word: "anxious",
        pos: "adjective",
        meaning: "Worried or nervous about something uncertain",
        meaning_np: "चिन्तित, बेचैन",
        examples: [{ en: "She felt anxious before the job interview.", np: "नोकरीको अन्तर्वार्ता अघि उनी बेचैन थिइन्।" }],
      },
      {
        word: "genuine",
        pos: "adjective",
        meaning: "Truly what it appears to be; sincere and real",
        meaning_np: "असली, सच्चा",
        examples: [{ en: "His apology seemed genuine, so she forgave him.", np: "उसको माफी सच्ची लागेकोले उसले माफ गरी।" }],
      },
      {
        word: "reluctant",
        pos: "adjective",
        meaning: "Unwilling to do something; hesitant",
        meaning_np: "अनिच्छुक, हिचकिचाउने",
        examples: [{ en: "He was reluctant to ask for help at first.", np: "पहिलेमा उसले सहयोग माग्न हिचकिचाएको थियो।" }],
      },
      {
        word: "subtle",
        pos: "adjective",
        meaning: "Not obvious; delicate and hard to notice",
        meaning_np: "सूक्ष्म, गाह्रो बुझ्ने",
        examples: [{ en: "There was a subtle difference in tone between the two emails.", np: "दुई इमेलहरूको टोनमा सूक्ष्म अन्तर थियो।" }],
      },
      {
        word: "candid",
        pos: "adjective",
        meaning: "Honest and direct, even if it's uncomfortable",
        meaning_np: "खुलस्त, इमानदार",
        examples: [{ en: "She gave me a candid opinion about my presentation.", np: "उसले मेरो प्रस्तुतीबारे खुलस्त राय दिइन्।" }],
      },
      {
        word: "diligent",
        pos: "adjective",
        meaning: "Careful and hardworking in everything you do",
        meaning_np: "मेहनती, परिश्रमी",
        examples: [{ en: "A diligent student reviews notes every evening.", np: "एक मेहनती विद्यार्थीले हरेक साँझ नोट्स हेर्छ।" }],
      },
      {
        word: "acknowledge",
        pos: "verb",
        meaning: "To accept or admit that something is true",
        meaning_np: "स्वीकार गर्नु, मान्नु",
        examples: [{ en: "He acknowledged that he had made a mistake.", np: "उसले गल्ती गरेको स्वीकार गर्‍यो।" }],
      },
      {
        word: "grasp",
        pos: "verb",
        meaning: "To understand something fully; also to hold tightly",
        meaning_np: "बुझ्नु, समात्नु",
        examples: [{ en: "It took me a while to grasp how the system works.", np: "प्रणाली कसरी काम गर्छ भनेर बुझ्न मलाई केही समय लाग्यो।" }],
      },
      {
        word: "persist",
        pos: "verb",
        meaning: "To keep doing something despite obstacles or difficulty",
        meaning_np: "जारी राख्नु, दृढ रहनु",
        examples: [{ en: "Despite failing twice, she persisted and passed the exam.", np: "दुई पटक असफल भएपछि पनि उनी दृढ रहिन् र परीक्षा पास गरिन्।" }],
      },
      {
        word: "elaborate",
        pos: "verb / adjective",
        meaning: "To explain in more detail; also, complex and detailed",
        meaning_np: "विस्तार गर्नु; जटिल, विस्तृत",
        examples: [{ en: "Can you elaborate on what you mean by 'urgent'?", np: "'जरुरी' भनेर के बुझाउनुभयो, थप विस्तार गर्नुहोस्न?", }],
      },
      {
        word: "concise",
        pos: "adjective",
        meaning: "Short and clear, without unnecessary words",
        meaning_np: "संक्षिप्त र स्पष्ट",
        examples: [{ en: "Please keep your summary concise — under five lines.", np: "कृपया आफ्नो सारांश संक्षिप्त राख्नुस् — पाँच लाइनभन्दा कम।" }],
      },
      {
        word: "pivot",
        pos: "verb / noun",
        meaning: "To turn or change direction; a key turning point",
        meaning_np: "दिशा परिवर्तन गर्नु; महत्त्वपूर्ण मोड",
        examples: [{ en: "After losing clients, the startup had to pivot its strategy.", np: "ग्राहक गुमाएपछि स्टार्टअपले आफ्नो रणनीति परिवर्तन गर्नु पर्‍यो।" }],
      },
      {
        word: "apprehensive",
        pos: "adjective",
        meaning: "Feeling worried or fearful about something that might happen",
        meaning_np: "चिन्तित, डराएको",
        examples: [{ en: "He felt apprehensive about meeting his new boss for the first time.", np: "नयाँ बसलाई पहिलो पटक भेट्दा उसलाई चिन्ता लाग्यो।" }],
      },
      {
        word: "indifferent",
        pos: "adjective",
        meaning: "Having no particular interest or concern about something",
        meaning_np: "उदासीन, वास्ता नगर्ने",
        examples: [{ en: "She seemed indifferent to the news, as if it didn't matter to her.", np: "उनी समाचारप्रति उदासीन देखिइन्, मानौं यसले उनलाई केही फरक पार्दैन।" }],
      },
      {
        word: "earnest",
        pos: "adjective",
        meaning: "Showing sincere and serious intention",
        meaning_np: "निष्ठावान, गम्भीर",
        examples: [{ en: "He made an earnest attempt to repair their friendship.", np: "उसले उनीहरूको मित्रता सुधार्न निष्ठावान प्रयास गर्‍यो।" }],
      },
      {
        word: "contemplate",
        pos: "verb",
        meaning: "To think about something deeply and carefully",
        meaning_np: "गहिरो सोच्नु, विचार गर्नु",
        examples: [{ en: "She sat by the window, contemplating her next career move.", np: "उनी झ्यालनेर बसेर आफ्नो अर्को करियर कदमबारे गहिरो सोच्दै थिइन्।" }],
      },
      {
        word: "skepticism",
        pos: "noun",
        meaning: "A doubting or questioning attitude toward claims",
        meaning_np: "शंका, अविश्वास",
        examples: [{ en: "His skepticism made him question every promise the salesman made.", np: "उसको शंकाले उसलाई विक्रेताको हरेक वाचामाथि प्रश्न उठाउन बाध्य बनायो।" }],
      },
    ],
  },
  {
    day: 2,
    category: "Work & Professional Life",
    words: [
      {
        word: "delegate",
        pos: "verb",
        meaning: "To assign a task or responsibility to someone else",
        meaning_np: "जिम्मेवारी सुम्पनु, काम दिनु",
        examples: [{ en: "A good manager knows when to delegate tasks to the team.", np: "एक राम्रो व्यवस्थापकलाई थाहा हुन्छ कहिले काम टोलीलाई सुम्पने।" }],
      },
      {
        word: "negotiate",
        pos: "verb",
        meaning: "To discuss something to reach a mutual agreement",
        meaning_np: "वार्ता गर्नु, सम्झौता गर्नु",
        examples: [{ en: "She negotiated a higher salary before accepting the offer.", np: "अफर स्वीकार गर्नु अघि उनले उच्च तलबको वार्ता गरिन्।" }],
      },
      {
        word: "collaborate",
        pos: "verb",
        meaning: "To work together with others toward a common goal",
        meaning_np: "सहकार्य गर्नु, मिलेर काम गर्नु",
        examples: [{ en: "The two teams collaborated to finish the project on time.", np: "दुई टोलीले समयमा प्रोजेक्ट सक्न सहकार्य गरे।" }],
      },
      {
        word: "initiative",
        pos: "noun",
        meaning: "The ability to start something without being told to",
        meaning_np: "स्वयम् सुरुवात गर्ने क्षमता, पहल",
        examples: [{ en: "She took the initiative to fix the bug before anyone noticed.", np: "कसैले थाहा पाउनु अघि नै उनले बग ठीक गर्ने पहल लिइन्।" }],
      },
      {
        word: "streamline",
        pos: "verb",
        meaning: "To make a process simpler and more efficient",
        meaning_np: "सरल बनाउनु, दक्षता बढाउनु",
        examples: [{ en: "We need to streamline the onboarding process for new staff.", np: "नयाँ कर्मचारीहरूको अनबोर्डिङ प्रक्रिया सरल बनाउन जरुरी छ।" }],
      },
      {
        word: "transparent",
        pos: "adjective",
        meaning: "Open, honest, and easy to understand",
        meaning_np: "पारदर्शी, खुला",
        examples: [{ en: "The company was transparent about its financial struggles.", np: "कम्पनी आफ्ना आर्थिक कठिनाइबारे पारदर्शी थियो।" }],
      },
      {
        word: "comprehensive",
        pos: "adjective",
        meaning: "Covering all aspects; thorough and complete",
        meaning_np: "समग्र, सम्पूर्ण",
        examples: [{ en: "He wrote a comprehensive report covering every department.", np: "उसले प्रत्येक विभाग समेट्ने समग्र रिपोर्ट लेख्यो।" }],
      },
      {
        word: "insight",
        pos: "noun",
        meaning: "A deep, accurate understanding of something",
        meaning_np: "गहन बुझाइ, अन्तरदृष्टि",
        examples: [{ en: "The survey gave us valuable insight into customer behavior.", np: "सर्वेक्षणले हामीलाई ग्राहकको व्यवहारबारे मूल्यवान बुझाइ दियो।" }],
      },
      {
        word: "leverage",
        pos: "verb / noun",
        meaning: "To use something to its maximum advantage",
        meaning_np: "फाइदा उठाउनु; उत्तोलन",
        examples: [{ en: "They leveraged social media to grow their brand quickly.", np: "उनीहरूले आफ्नो ब्रान्ड छिटो बढाउन सोसल मिडियाको फाइदा उठाए।" }],
      },
      {
        word: "deadline",
        pos: "noun",
        meaning: "The latest time by which something must be done",
        meaning_np: "अन्तिम समयसीमा",
        examples: [{ en: "Missing a deadline can damage your professional reputation.", np: "समयसीमा छुटाउनुले तपाईंको व्यावसायिक प्रतिष्ठा बिगार्न सक्छ।" }],
      },
      {
        word: "compromise",
        pos: "verb / noun",
        meaning: "To settle a disagreement by both sides giving up something",
        meaning_np: "सम्झौता गर्नु; मध्यम बाटो",
        examples: [{ en: "We compromised on the price and both sides were satisfied.", np: "हामीले मूल्यमा सम्झौता गर्‍यौं र दुवै पक्ष सन्तुष्ट भए।" }],
      },
      {
        word: "prioritize",
        pos: "verb",
        meaning: "To deal with the most important things first",
        meaning_np: "प्राथमिकता दिनु",
        examples: [{ en: "Learn to prioritize your tasks or you'll always feel behind.", np: "आफ्ना कामलाई प्राथमिकता दिन सिक्नुस् नत्र तपाईंलाई सधैं ढिलाइ भएको महसुस हुनेछ।" }],
      },
      {
        word: "onboard",
        pos: "verb",
        meaning: "To integrate a new employee into an organization",
        meaning_np: "नयाँ कर्मचारीलाई समावेश गर्नु",
        examples: [{ en: "The HR team spent a full week onboarding the new hires.", np: "मानव संसाधन टोलीले नयाँ कर्मचारीहरूलाई समावेश गर्न पूरा हप्ता खर्च गर्‍यो।" }],
      },
      {
        word: "accountable",
        pos: "adjective",
        meaning: "Responsible for one's actions and required to explain them",
        meaning_np: "जवाफदेही",
        examples: [{ en: "Every team member is accountable for meeting their own targets.", np: "हरेक टोली सदस्य आफ्नो लक्ष्य पूरा गर्न जवाफदेही हुन्छ।" }],
      },
      {
        word: "feedback",
        pos: "noun",
        meaning: "Information or opinions given about performance or work",
        meaning_np: "प्रतिक्रिया, सुझाव",
        examples: [{ en: "She asked her manager for honest feedback on her presentation.", np: "उनले आफ्नो प्रस्तुतीबारे इमानदार प्रतिक्रियाका लागि आफ्नो प्रबन्धकलाई सोधिन्।" }],
      },
      {
        word: "proactive",
        pos: "adjective",
        meaning: "Acting in advance to deal with an expected problem",
        meaning_np: "सक्रिय, पहिले नै तयार हुने",
        examples: [{ en: "A proactive employee solves problems before they escalate.", np: "एक सक्रिय कर्मचारीले समस्या बढ्नु अघि नै समाधान गर्छ।" }],
      },
      {
        word: "workload",
        pos: "noun",
        meaning: "The amount of work assigned to or expected of a person",
        meaning_np: "कामको बोझ",
        examples: [{ en: "Her workload doubled after two colleagues left the company.", np: "दुई सहकर्मी कम्पनी छाडेपछि उनको कामको बोझ दोब्बर भयो।" }],
      },
    ],
  },
  {
    day: 3,
    category: "Relationships & Social Life",
    words: [
      {
        word: "empathy",
        pos: "noun",
        meaning: "The ability to understand and share another person's feelings",
        meaning_np: "सहानुभूति, अरूको भावना बुझ्ने क्षमता",
        examples: [{ en: "Empathy is essential for building strong friendships.", np: "बलियो मित्रता बनाउनका लागि सहानुभूति आवश्यक छ।" }],
      },
      {
        word: "confront",
        pos: "verb",
        meaning: "To face a problem or person directly and boldly",
        meaning_np: "सामना गर्नु, सिधा भेट्नु",
        examples: [{ en: "She finally confronted her colleague about the missing credit.", np: "उनले अन्तमा सहकर्मीसँग छुटेको श्रेयबारे सामना गरिन्।" }],
      },
      {
        word: "reconcile",
        pos: "verb",
        meaning: "To restore a friendly relationship after a disagreement",
        meaning_np: "मेलमिलाप गर्नु, सम्बन्ध ठीक गर्नु",
        examples: [{ en: "After weeks of silence, the two brothers reconciled.", np: "हप्तौंको मौनता पछि दुई भाइले मेलमिलाप गरे।" }],
      },
      {
        word: "sincere",
        pos: "adjective",
        meaning: "Genuinely meant; not fake or pretending",
        meaning_np: "इमानदार, सच्चा",
        examples: [{ en: "A sincere thank-you means more than a formal one.", np: "इमानदार धन्यवाद औपचारिक धन्यवादभन्दा बढी अर्थपूर्ण हुन्छ।" }],
      },
      {
        word: "mutual",
        pos: "adjective",
        meaning: "Shared equally by two or more people",
        meaning_np: "आपसी, पारस्परिक",
        examples: [{ en: "Their friendship is based on mutual respect and trust.", np: "उनीहरूको मित्रता आपसी सम्मान र विश्वासमा आधारित छ।" }],
      },
      {
        word: "boundary",
        pos: "noun",
        meaning: "A limit that defines what is acceptable in a relationship",
        meaning_np: "सीमा, हद",
        examples: [{ en: "Setting healthy boundaries is a sign of self-respect.", np: "स्वस्थ सीमा तय गर्नु आत्मसम्मानको संकेत हो।" }],
      },
      {
        word: "resentment",
        pos: "noun",
        meaning: "A bitter feeling of anger caused by unfair treatment",
        meaning_np: "नाराजगी, मनमा गाँस्सिएको रिस",
        examples: [{ en: "Holding resentment only hurts the person feeling it.", np: "नाराजगी राख्नुले केवल त्यसलाई नै दुखाउँछ जसले महसुस गर्छ।" }],
      },
      {
        word: "tolerate",
        pos: "verb",
        meaning: "To allow something without actively opposing it",
        meaning_np: "सहनु, बर्दास्त गर्नु",
        examples: [{ en: "She couldn't tolerate the noise from the upstairs neighbour.", np: "उनी माथिल्लो छिमेकीको आवाज सहन सकिनन्।" }],
      },
      {
        word: "commitment",
        pos: "noun",
        meaning: "A promise or obligation to do something reliably",
        meaning_np: "प्रतिबद्धता, वाचा",
        examples: [{ en: "Marriage is a lifelong commitment to another person.", np: "विवाह अर्को व्यक्तिप्रतिको जीवनभरको प्रतिबद्धता हो।" }],
      },
      {
        word: "mediate",
        pos: "verb",
        meaning: "To help two sides settle a disagreement",
        meaning_np: "मध्यस्थता गर्नु",
        examples: [{ en: "A neutral friend was asked to mediate the dispute.", np: "विवाद मिलाउन एक तटस्थ साथीलाई भनियो।" }],
      },
      {
        word: "awkward",
        pos: "adjective",
        meaning: "Uncomfortable, embarrassing, or hard to deal with",
        meaning_np: "अप्ठ्यारो, असहज",
        examples: [{ en: "Running into your ex at a party can feel really awkward.", np: "पार्टीमा पूर्व प्रेमीलाई भेट्नु साँच्चै अप्ठ्यारो महसुस हुन सक्छ।" }],
      },
      {
        word: "appreciate",
        pos: "verb",
        meaning: "To recognize and be grateful for someone's value or effort",
        meaning_np: "सराहना गर्नु, कदर गर्नु",
        examples: [{ en: "I really appreciate how much effort you put into this.", np: "तपाईंले यसमा कति मेहनत गर्नुभयो, म साँच्चै कदर गर्छु।" }],
      },
      {
        word: "affection",
        pos: "noun",
        meaning: "A gentle feeling of fondness or love toward someone",
        meaning_np: "स्नेह, माया",
        examples: [{ en: "Grandparents often show deep affection toward their grandchildren.", np: "हजुरबा-हजुरआमाले प्रायः नातिनातिनाप्रति गहिरो स्नेह देखाउँछन्।" }],
      },
      {
        word: "betray",
        pos: "verb",
        meaning: "To be disloyal to someone who trusted you",
        meaning_np: "विश्वासघात गर्नु",
        examples: [{ en: "He felt betrayed when his best friend shared his secret.", np: "आफ्नो साथीले रहस्य फुटाउँदा उसले विश्वासघात महसुस गर्‍यो।" }],
      },
      {
        word: "companionship",
        pos: "noun",
        meaning: "A feeling of friendship and being together with someone",
        meaning_np: "सङ्गत, साथ",
        examples: [{ en: "Pets can provide comfort and companionship to people living alone.", np: "पाल्तु जनावरले एक्लै बस्ने मानिसलाई सान्त्वना र साथ दिन सक्छन्।" }],
      },
      {
        word: "considerate",
        pos: "adjective",
        meaning: "Thinking carefully about the feelings of others",
        meaning_np: "विचारशील, अरूको ख्याल राख्ने",
        examples: [{ en: "A considerate host always checks if guests need anything.", np: "एक विचारशील मेजबानले सधैं पाहुनालाई केही चाहियो कि भनेर हेर्छन्।" }],
      },
      {
        word: "estrange",
        pos: "verb",
        meaning: "To cause someone to become distant or unfriendly",
        meaning_np: "टाढा हुनु, सम्बन्ध बिग्रनु",
        examples: [{ en: "A long argument estranged the two former best friends.", np: "लामो झगडाले दुई पूर्व घनिष्ठ साथीहरूको सम्बन्ध बिगार्‍यो।" }],
      },
    ],
  },
  {
    day: 4,
    category: "Technology & Daily Habits",
    words: [
      {
        word: "overwhelm",
        pos: "verb",
        meaning: "To give someone too much to handle; to flood with input",
        meaning_np: "अभिभूत गर्नु, थिच्नु",
        examples: [{ en: "The amount of unread emails can quickly overwhelm you.", np: "नपढेका इमेलहरूको संख्याले तपाईंलाई छिट्टै थिच्न सक्छ।" }],
      },
      {
        word: "integrate",
        pos: "verb",
        meaning: "To combine parts into a working whole",
        meaning_np: "एकीकृत गर्नु, जोड्नु",
        examples: [{ en: "The app integrates with your calendar and reminds you automatically.", np: "एपले तपाईंको क्यालेन्डरसँग जोडिन्छ र स्वचालित रूपमा सम्झाउँछ।" }],
      },
      {
        word: "efficient",
        pos: "adjective",
        meaning: "Achieving results with minimum wasted time or effort",
        meaning_np: "दक्ष, कम समयमा बढी काम गर्ने",
        examples: [{ en: "Using shortcuts makes you more efficient at your job.", np: "शर्टकट प्रयोग गर्नुले तपाईंलाई काममा बढी दक्ष बनाउँछ।" }],
      },
      {
        word: "accessible",
        pos: "adjective",
        meaning: "Easy to reach, use, or understand",
        meaning_np: "सहज पहुँचयोग्य",
        examples: [{ en: "Good design makes technology accessible to everyone.", np: "राम्रो डिजाइनले प्रविधिलाई सबैका लागि सहज पहुँचयोग्य बनाउँछ।" }],
      },
      {
        word: "monitor",
        pos: "verb",
        meaning: "To watch something closely over time",
        meaning_np: "निगरानी गर्नु, हेर्नु",
        examples: [{ en: "He monitors his screen time to avoid getting distracted.", np: "ध्यान भड्किन नदिन उनले आफ्नो स्क्रिन समय निगरानी गर्छन्।" }],
      },
      {
        word: "analyze",
        pos: "verb",
        meaning: "To examine something in detail to understand it better",
        meaning_np: "विश्लेषण गर्नु",
        examples: [{ en: "She analyzed the data before making any decisions.", np: "कुनै निर्णय लिनु अघि उनले डेटाको विश्लेषण गरिन्।" }],
      },
      {
        word: "customize",
        pos: "verb",
        meaning: "To change something to fit personal needs or preferences",
        meaning_np: "व्यक्तिगत रूपमा मिलाउनु",
        examples: [{ en: "You can customize the app's theme to dark mode.", np: "तपाईंले एपको थिम डार्क मोडमा मिलाउन सक्नुहुन्छ।" }],
      },
      {
        word: "authenticate",
        pos: "verb",
        meaning: "To verify that someone is who they claim to be",
        meaning_np: "प्रमाणीकरण गर्नु",
        examples: [{ en: "Use two-factor authentication to protect your account.", np: "आफ्नो खाता सुरक्षित गर्न दुई-चरण प्रमाणीकरण प्रयोग गर्नुस्।" }],
      },
      {
        word: "privacy",
        pos: "noun",
        meaning: "The right to keep personal information or life out of public view",
        meaning_np: "गोपनीयता, एकान्त",
        examples: [{ en: "Read the app's privacy policy before sharing your data.", np: "आफ्नो डेटा साझा गर्नु अघि एपको गोपनीयता नीति पढ्नुस्।" }],
      },
      {
        word: "distraction",
        pos: "noun",
        meaning: "Something that takes attention away from what you're doing",
        meaning_np: "ध्यान भड्काउने कुरा",
        examples: [{ en: "Put your phone on silent to avoid distractions while studying.", np: "पढ्दा ध्यान नभड्कोस् भनेर फोन साइलेन्टमा राख्नुस्।" }],
      },
      {
        word: "automate",
        pos: "verb",
        meaning: "To make a process run on its own without manual effort",
        meaning_np: "स्वचालित गर्नु",
        examples: [{ en: "He automated the weekly report so it sends itself every Friday.", np: "उसले साप्ताहिक रिपोर्ट स्वचालित बनायो ताकि यो हरेक शुक्रवार आफैँ पठाउँछ।" }],
      },
      {
        word: "update",
        pos: "verb / noun",
        meaning: "To bring something to a newer or better state",
        meaning_np: "अपडेट गर्नु; ताजा जानकारी",
        examples: [{ en: "Always update your software to fix security vulnerabilities.", np: "सुरक्षा कमजोरीहरू ठीक गर्न सधैँ सफ्टवेयर अपडेट गर्नुस्।" }],
      },
      {
        word: "optimize",
        pos: "verb",
        meaning: "To make something as effective or useful as possible",
        meaning_np: "अनुकूलन गर्नु",
        examples: [{ en: "Developers optimize the app to load faster on slow networks.", np: "विकासकर्ताहरूले सुस्त नेटवर्कमा पनि छिटो चल्नेगरी एप अनुकूलन गर्छन्।" }],
      },
      {
        word: "glitch",
        pos: "noun",
        meaning: "A small, temporary fault or malfunction",
        meaning_np: "सानो त्रुटि, खराबी",
        examples: [{ en: "A software glitch caused the app to crash during checkout.", np: "सफ्टवेयरको सानो त्रुटिले चेकआउटको बेला एप क्र्यास भयो।" }],
      },
      {
        word: "habitual",
        pos: "adjective",
        meaning: "Done regularly as a fixed practice or habit",
        meaning_np: "बानी परेको, नियमित",
        examples: [{ en: "Checking his phone first thing every morning became habitual for him.", np: "हरेक बिहान सबैभन्दा पहिले फोन हेर्नु उसको बानी बन्यो।" }],
      },
      {
        word: "declutter",
        pos: "verb",
        meaning: "To remove unnecessary items to make something simpler",
        meaning_np: "अनावश्यक कुरा हटाउनु, सफा गर्नु",
        examples: [{ en: "She spent Sunday decluttering her phone's home screen.", np: "उनले आइतबार आफ्नो फोनको होम स्क्रिन सफा गर्न बिताइन्।" }],
      },
      {
        word: "streamlined",
        pos: "adjective",
        meaning: "Made simpler and more efficient by removing unnecessary steps",
        meaning_np: "सरल र दक्ष बनाइएको",
        examples: [{ en: "The new streamlined checkout process takes only two clicks.", np: "नयाँ सरल चेकआउट प्रक्रियामा जम्मा दुई क्लिक मात्र लाग्छ।" }],
      },
    ],
  },
  {
    day: 5,
    category: "Health & Wellbeing",
    words: [
      {
        word: "chronic",
        pos: "adjective",
        meaning: "Persisting for a long time; not going away easily",
        meaning_np: "दीर्घकालीन, पुरानो",
        examples: [{ en: "Chronic stress can seriously damage your immune system.", np: "दीर्घकालीन तनावले तपाईंको रोगप्रतिरोधी प्रणालीलाई गम्भीर क्षति पुर्‍याउन सक्छ।" }],
      },
      {
        word: "remedy",
        pos: "noun / verb",
        meaning: "A treatment or solution for a problem or illness",
        meaning_np: "उपचार, उपाय",
        examples: [{ en: "Ginger tea is a popular remedy for an upset stomach.", np: "अदुवाको चिया पेट खराब हुँदाको लोकप्रिय उपाय हो।" }],
      },
      {
        word: "vigorous",
        pos: "adjective",
        meaning: "Strong, active, and full of energy",
        meaning_np: "जोसिलो, सक्रिय",
        examples: [{ en: "Thirty minutes of vigorous exercise daily improves mood significantly.", np: "दैनिक ३० मिनेटको जोसिलो व्यायामले मनोदशा उल्लेखनीय रूपमा सुधार गर्छ।" }],
      },
      {
        word: "sedentary",
        pos: "adjective",
        meaning: "Involving a lot of sitting and little physical movement",
        meaning_np: "निष्क्रिय, धेरै बस्ने",
        examples: [{ en: "A sedentary lifestyle is linked to a higher risk of heart disease.", np: "निष्क्रिय जीवनशैली हृदयरोगको उच्च जोखिमसँग जोडिएको छ।" }],
      },
      {
        word: "symptom",
        pos: "noun",
        meaning: "A sign that indicates you may be sick",
        meaning_np: "लक्षण",
        examples: [{ en: "Fatigue and headache are common symptoms of dehydration.", np: "थकान र टाउकोदुखाइ निर्जलीकरणका सामान्य लक्षणहरू हुन्।" }],
      },
      {
        word: "exhausted",
        pos: "adjective",
        meaning: "Completely drained of energy; very tired",
        meaning_np: "थकित, अत्यन्त थाकेको",
        examples: [{ en: "She was exhausted after working a double shift at the hospital.", np: "अस्पतालमा डबल शिफ्ट काम गरेपछि उनी अत्यन्त थाकिन्।" }],
      },
      {
        word: "immunity",
        pos: "noun",
        meaning: "The body's ability to resist infection and disease",
        meaning_np: "प्रतिरक्षा, रोग प्रतिरोधक क्षमता",
        examples: [{ en: "Good sleep helps build strong immunity against viruses.", np: "राम्रो निद्राले भाइरस विरुद्ध बलियो प्रतिरक्षा निर्माण गर्न मद्दत गर्छ।" }],
      },
      {
        word: "insomnia",
        pos: "noun",
        meaning: "The inability to fall asleep or stay asleep",
        meaning_np: "निद्रा न आउने समस्या, अनिद्रा",
        examples: [{ en: "Insomnia affects millions of people who rely on screens at night.", np: "रातमा स्क्रिनमा भर पर्ने लाखौं मानिसलाई अनिद्राले असर गर्छ।" }],
      },
      {
        word: "recover",
        pos: "verb",
        meaning: "To return to a normal state after illness or difficulty",
        meaning_np: "निको हुनु, सुधार हुनु",
        examples: [{ en: "It took him two weeks to fully recover from the flu.", np: "फ्लुबाट पूर्ण निको हुन उसलाई दुई हप्ता लाग्यो।" }],
      },
      {
        word: "diagnose",
        pos: "verb",
        meaning: "To identify the nature of an illness through examination",
        meaning_np: "रोग पत्ता लगाउनु, निदान गर्नु",
        examples: [{ en: "The doctor diagnosed her with vitamin D deficiency.", np: "डाक्टरले उनलाई भिटामिन डी कमीको निदान गरे।" }],
      },
      {
        word: "prescribe",
        pos: "verb",
        meaning: "To officially recommend medicine or treatment",
        meaning_np: "औषधि लेख्नु, प्रिस्क्रिप्सन दिनु",
        examples: [{ en: "The doctor prescribed iron tablets for her anaemia.", np: "डाक्टरले उनको एनिमियाका लागि फलाम चक्की प्रेस्क्राइब गरे।" }],
      },
      {
        word: "ailment",
        pos: "noun",
        meaning: "A mild illness or health complaint",
        meaning_np: "सामान्य रोग, अस्वस्थता",
        examples: [{ en: "Back pain is a common ailment among office workers.", np: "पीठदुखाइ कार्यालय कर्मचारीहरूमा एक सामान्य अस्वस्थता हो।" }],
      },
      {
        word: "nourish",
        pos: "verb",
        meaning: "To provide the food or care necessary for health and growth",
        meaning_np: "पोषण दिनु",
        examples: [{ en: "Eating leafy greens helps nourish your body with essential vitamins.", np: "हरियो सागपात खानाले शरीरलाई आवश्यक भिटामिनले पोषण दिन्छ।" }],
      },
      {
        word: "dehydrated",
        pos: "adjective",
        meaning: "Lacking sufficient water in the body",
        meaning_np: "पानीको कमी भएको, निर्जलित",
        examples: [{ en: "He felt dizzy because he was severely dehydrated after the hike.", np: "पदयात्रापछि गम्भीर रूपमा निर्जलित भएकोले उसलाई चक्कर लाग्यो।" }],
      },
      {
        word: "stamina",
        pos: "noun",
        meaning: "The physical or mental strength to sustain effort for a long time",
        meaning_np: "सहनशक्ति, स्टामिना",
        examples: [{ en: "Regular running builds the stamina needed for a marathon.", np: "नियमित दौडले म्याराथनका लागि आवश्यक सहनशक्ति निर्माण गर्छ।" }],
      },
      {
        word: "soothe",
        pos: "verb",
        meaning: "To gently calm or relieve pain or distress",
        meaning_np: "शान्त पार्नु, आराम दिनु",
        examples: [{ en: "Warm tea can soothe a sore throat almost instantly.", np: "न्यानो चियाले घाँटी दुखाइलाई झट्टै आराम दिन सक्छ।" }],
      },
      {
        word: "hygiene",
        pos: "noun",
        meaning: "Practices that keep you and your surroundings clean and healthy",
        meaning_np: "सरसफाइ, स्वच्छता",
        examples: [{ en: "Good hygiene, like washing your hands, prevents many illnesses.", np: "हात धुने जस्ता राम्रो सरसफाइले धेरै रोगबाट बचाउँछ।" }],
      },
    ],
  },
  {
    day: 6,
    category: "Money & Everyday Finance",
    words: [
      {
        word: "budget",
        pos: "noun / verb",
        meaning: "A plan for how to spend money; to plan spending carefully",
        meaning_np: "बजेट; खर्च योजना बनाउनु",
        examples: [{ en: "Stick to a monthly budget to avoid running out of money.", np: "पैसा सकिन नदिन मासिक बजेट अपनाउनुस्।" }],
      },
      {
        word: "invest",
        pos: "verb",
        meaning: "To put money into something expecting a future profit",
        meaning_np: "लगानी गर्नु",
        examples: [{ en: "Investing early gives your money more time to grow.", np: "चाँडो लगानी गर्नाले तपाईंको पैसालाई बढ्ने बढी समय मिल्छ।" }],
      },
      {
        word: "expense",
        pos: "noun",
        meaning: "Money spent on something; a cost",
        meaning_np: "खर्च",
        examples: [{ en: "Track every expense if you want to understand your spending.", np: "आफ्नो खर्च बुझ्न चाहनुहुन्छ भने हरेक खर्च ट्र्याक गर्नुस्।" }],
      },
      {
        word: "debt",
        pos: "noun",
        meaning: "Money that is owed to someone else",
        meaning_np: "ऋण",
        examples: [{ en: "Pay off high-interest debt before saving aggressively.", np: "आक्रामक रूपमा बचत गर्नु अघि उच्च-ब्याजको ऋण तिर्नुस्।" }],
      },
      {
        word: "surplus",
        pos: "noun",
        meaning: "An amount left over after needs have been met",
        meaning_np: "बाँकी रकम, अधिक",
        examples: [{ en: "Put any monthly surplus straight into your savings account.", np: "कुनै पनि मासिक बाँकी रकम सिधै बचत खातामा हाल्नुस्।" }],
      },
      {
        word: "inflation",
        pos: "noun",
        meaning: "The rate at which prices rise over time",
        meaning_np: "मुद्रास्फीति, मूल्य वृद्धि",
        examples: [{ en: "High inflation means your savings buy less every year.", np: "उच्च मुद्रास्फीतिको अर्थ हो तपाईंको बचतले हरेक वर्ष कम किन्न सक्छ।" }],
      },
      {
        word: "transaction",
        pos: "noun",
        meaning: "An exchange of money or goods between two parties",
        meaning_np: "कारोबार, लेनदेन",
        examples: [{ en: "Check your bank statement to review all recent transactions.", np: "हालका सबै कारोबारहरू समीक्षा गर्न आफ्नो बैंक विवरण हेर्नुस्।" }],
      },
      {
        word: "afford",
        pos: "verb",
        meaning: "To have enough money to pay for something",
        meaning_np: "सक्नु, पैसा हुनु",
        examples: [{ en: "He couldn't afford a new laptop, so he bought a second-hand one.", np: "उसले नयाँ ल्यापटप किन्न सकेन, त्यसैले पुरानो एउटा किन्यो।" }],
      },
      {
        word: "mortgage",
        pos: "noun",
        meaning: "A loan taken to buy property, paid back over many years",
        meaning_np: "घर धितो ऋण",
        examples: [{ en: "They took out a 25-year mortgage to buy their first home.", np: "उनीहरूले आफ्नो पहिलो घर किन्न २५ वर्षको धितो ऋण लिए।" }],
      },
      {
        word: "dividend",
        pos: "noun",
        meaning: "A portion of profits paid to shareholders",
        meaning_np: "लाभांश",
        examples: [{ en: "She receives a quarterly dividend from her stock investments.", np: "उनले आफ्नो शेयर लगानीबाट त्रैमासिक लाभांश पाउँछिन्।" }],
      },
      {
        word: "frugal",
        pos: "adjective",
        meaning: "Careful about spending money; avoiding waste",
        meaning_np: "मितव्ययी, किफायती",
        examples: [{ en: "Living frugally during your twenties sets you up for life.", np: "बीसौं वर्षमा मितव्ययी जीवन बाँच्नुले तपाईंको भविष्य सुनिश्चित गर्छ।" }],
      },
      {
        word: "withdraw",
        pos: "verb",
        meaning: "To take money out of an account",
        meaning_np: "निकाल्नु, फिर्ता लिनु",
        examples: [{ en: "She withdrew cash from the ATM before the trip.", np: "यात्रा अघि उनले एटिएमबाट नगद निकालिन्।" }],
      },
      {
        word: "revenue",
        pos: "noun",
        meaning: "The total income generated by a business before expenses",
        meaning_np: "राजस्व, आम्दानी",
        examples: [{ en: "The company's revenue grew by twenty percent last quarter.", np: "कम्पनीको राजस्व गएको त्रैमासमा बीस प्रतिशतले बढ्यो।" }],
      },
      {
        word: "installment",
        pos: "noun",
        meaning: "One of several parts into which a payment is divided",
        meaning_np: "किस्ता",
        examples: [{ en: "She is paying for her phone in monthly installments.", np: "उनले आफ्नो फोनको भुक्तानी मासिक किस्तामा गरिरहेकी छिन्।" }],
      },
      {
        word: "thrifty",
        pos: "adjective",
        meaning: "Careful with money; avoiding unnecessary spending",
        meaning_np: "किफायती, मितव्ययी",
        examples: [{ en: "His thrifty habits helped him save enough for a house deposit.", np: "उसको किफायती बानीले उसलाई घरको डिपोजिटका लागि पर्याप्त बचत गर्न मद्दत गर्‍यो।" }],
      },
      {
        word: "liability",
        pos: "noun",
        meaning: "A debt or financial obligation owed by a person or company",
        meaning_np: "दायित्व, ऋण भार",
        examples: [{ en: "The company listed all its liabilities in the annual report.", np: "कम्पनीले आफ्ना सबै दायित्वहरू वार्षिक प्रतिवेदनमा उल्लेख गर्‍यो।" }],
      },
      {
        word: "reimburse",
        pos: "verb",
        meaning: "To repay someone money they have spent",
        meaning_np: "फिर्ता तिर्नु, क्षतिपूर्ति दिनु",
        examples: [{ en: "The company will reimburse you for any travel expenses.", np: "कम्पनीले तपाईंको यात्रा खर्च फिर्ता तिर्नेछ।" }],
      },
    ],
  },
  {
    day: 7,
    category: "Describing People & Character",
    words: [
      {
        word: "ambitious",
        pos: "adjective",
        meaning: "Having a strong desire to achieve success",
        meaning_np: "महत्वाकांक्षी",
        examples: [{ en: "She is ambitious and rarely settles for less than her best.", np: "उनी महत्वाकांक्षी छिन् र आफ्नो सर्वश्रेष्ठभन्दा कम मा शायदै सन्तुष्ट हुन्छिन्।" }],
      },
      {
        word: "pragmatic",
        pos: "adjective",
        meaning: "Dealing with things in a practical, realistic way",
        meaning_np: "व्यावहारिक, यथार्थवादी",
        examples: [{ en: "A pragmatic leader focuses on results, not ideals.", np: "एक व्यावहारिक नेता आदर्शहरू नभई परिणामहरूमा ध्यान केन्द्रित गर्छ।" }],
      },
      {
        word: "skeptical",
        pos: "adjective",
        meaning: "Not easily convinced; questioning claims before believing",
        meaning_np: "शंकालु, सन्देहास्पद",
        examples: [{ en: "He was skeptical about the deal and asked for more details.", np: "उनी सम्झौताप्रति शंकालु थिए र थप विवरण माग गरे।" }],
      },
      {
        word: "resilient",
        pos: "adjective",
        meaning: "Able to recover quickly from difficulties",
        meaning_np: "लचिलो, फर्कन सक्ने",
        examples: [{ en: "Resilient people see failure as a stepping stone, not a dead end.", np: "लचिलो मानिसहरूले असफलतालाई अवरोध नभई सिँढीको रूपमा देख्छन्।" }],
      },
      {
        word: "impulsive",
        pos: "adjective",
        meaning: "Acting suddenly without thinking things through",
        meaning_np: "आवेगी, बिना सोची गर्ने",
        examples: [{ en: "Impulsive purchases are the biggest threat to any budget.", np: "आवेगी खरिद जुनसुकै बजेटको लागि सबैभन्दा ठूलो खतरा हो।" }],
      },
      {
        word: "versatile",
        pos: "adjective",
        meaning: "Able to adapt to many different tasks or situations",
        meaning_np: "बहुमुखी, विविध काम गर्न सक्ने",
        examples: [{ en: "A versatile employee is valuable in any organisation.", np: "एक बहुमुखी कर्मचारी जुनसुकै संस्थामा मूल्यवान हुन्छ।" }],
      },
      {
        word: "meticulous",
        pos: "adjective",
        meaning: "Very careful and precise, paying attention to every detail",
        meaning_np: "सूक्ष्म, अत्यन्त सावधान",
        examples: [{ en: "Her meticulous editing made the article much cleaner.", np: "उनको सूक्ष्म सम्पादनले लेखलाई धेरै सफा बनायो।" }],
      },
      {
        word: "assertive",
        pos: "adjective",
        meaning: "Confidently expressing opinions and needs without being aggressive",
        meaning_np: "आत्मविश्वासी, दृढ",
        examples: [{ en: "Being assertive at work helps you get what you deserve.", np: "कामठाउँमा दृढ हुनुले तपाईंलाई आफूले पाउनु पर्ने कुरा पाउन मद्दत गर्छ।" }],
      },
      {
        word: "tenacious",
        pos: "adjective",
        meaning: "Refusing to give up; holding firm to goals",
        meaning_np: "अडिग, दृढ",
        examples: [{ en: "A tenacious entrepreneur keeps going after every rejection.", np: "एक अडिग उद्यमी हरेक अस्वीकृति पछि पनि अगाडि बढ्छ।" }],
      },
      {
        word: "eloquent",
        pos: "adjective",
        meaning: "Expressing ideas clearly and persuasively in speech or writing",
        meaning_np: "वाक्पटु, प्रभावशाली बोल्ने",
        examples: [{ en: "Her eloquent speech moved everyone in the room.", np: "उनको प्रभावशाली भाषणले कोठाका सबैलाई छोयो।" }],
      },
      {
        word: "complacent",
        pos: "adjective",
        meaning: "Too satisfied with the current situation; not trying to improve",
        meaning_np: "आत्मसन्तुष्ट, बेवास्ता",
        examples: [{ en: "Don't get complacent just because things are going well right now.", np: "अहिले राम्रो भइरहेको छ भनेर आत्मसन्तुष्ट नहोस्।" }],
      },
      {
        word: "prudent",
        pos: "adjective",
        meaning: "Showing wise and careful judgment in practical matters",
        meaning_np: "विवेकी, सतर्क",
        examples: [{ en: "It is prudent to save at least three months of expenses.", np: "कम्तीमा तीन महिनाको खर्च बचाउनु विवेकपूर्ण हो।" }],
      },
      {
        word: "humble",
        pos: "adjective",
        meaning: "Not proud or arrogant; modest about one's abilities",
        meaning_np: "विनम्र, नम्र",
        examples: [{ en: "Despite his success, he remained humble and thanked his whole team.", np: "सफलता पाए पनि उनी विनम्र रहे र आफ्नो सम्पूर्ण टोलीलाई धन्यवाद दिए।" }],
      },
      {
        word: "stubborn",
        pos: "adjective",
        meaning: "Refusing to change one's mind or approach despite reasons to do so",
        meaning_np: "हठी, जिद्दी",
        examples: [{ en: "He is too stubborn to admit when he's wrong.", np: "उनी आफू गलत हुँदा पनि स्वीकार गर्न नसक्ने जति हठी छन्।" }],
      },
      {
        word: "compassionate",
        pos: "adjective",
        meaning: "Feeling or showing sympathy and concern for others",
        meaning_np: "दयालु, करुणामय",
        examples: [{ en: "The compassionate nurse stayed late to comfort worried families.", np: "दयालु नर्स चिन्तित परिवारहरूलाई सान्त्वना दिन ढिलासम्म बसिन्।" }],
      },
      {
        word: "arrogant",
        pos: "adjective",
        meaning: "Having an exaggerated sense of one's own importance",
        meaning_np: "घमण्डी, अहंकारी",
        examples: [{ en: "His arrogant attitude made it hard for the team to trust him.", np: "उसको घमण्डी व्यवहारले टोलीलाई उसमाथि विश्वास गर्न गाह्रो बनायो।" }],
      },
      {
        word: "sociable",
        pos: "adjective",
        meaning: "Enjoying the company of others; friendly and outgoing",
        meaning_np: "मिलनसार स्वभावको",
        examples: [{ en: "Being naturally sociable, she made friends within minutes at the party.", np: "स्वाभाविक रूपमा मिलनसार भएकोले उनले पार्टीमा मिनेटभित्रै साथीहरू बनाइन्।" }],
      },
    ],
  },
];
