export type SpeakSwap = {
  id: number;
  basic: string;
  upgraded: string;
};

export const SPEAK_LIKE_A_PRO: SpeakSwap[] = [
  { id: 1, basic: "Oh My God!", upgraded: "Holy Moly!" },
  { id: 2, basic: "I forgot.", upgraded: "It slipped my mind." },
  { id: 3, basic: "Excuse me, what did you say?", upgraded: "I'm sorry, come again?" },
  { id: 4, basic: "You're so beautiful.", upgraded: "You're drop dead gorgeous." },
  { id: 5, basic: "Calm down.", upgraded: "Take it easy." },
  { id: 6, basic: "I'm listening.", upgraded: "I'm all ears." },
  { id: 7, basic: "It's not difficult.", upgraded: "It's a piece of cake." },
  { id: 8, basic: "I agree with you.", upgraded: "We're on the same page." },
  { id: 9, basic: "Thank you very much.", upgraded: "I really appreciate it." },
  { id: 10, basic: "OK", upgraded: "Sounds good" },
  { id: 11, basic: "No", upgraded: "Nah" },
  { id: 12, basic: "Yes", upgraded: "Yep" },
  { id: 13, basic: "Thanks", upgraded: "Cheers" },
  { id: 14, basic: "Stop it", upgraded: "Cut it out" },
  { id: 15, basic: "Be quick", upgraded: "Chop-chop" },
  { id: 16, basic: "Wait", upgraded: "Hold on" },
  { id: 17, basic: "Calm down", upgraded: "Chill out" },
  { id: 18, basic: "Good job", upgraded: "Nice one" },
  { id: 19, basic: "Be quiet", upgraded: "Zip on it" },
  { id: 20, basic: "Hurry up", upgraded: "Step on it" },
  { id: 21, basic: "Not sure", upgraded: "Beats me" },
  { id: 22, basic: "You first.", upgraded: "After you." },
  { id: 23, basic: "I'm very excited.", upgraded: "I'm pumped up." },
  { id: 24, basic: "I'm a bit busy.", upgraded: "I'm a bit tied up." },
  { id: 25, basic: "Think about it.", upgraded: "Sleep on it." },
  { id: 26, basic: "Move a bit.", upgraded: "Scoot over." },
  { id: 27, basic: "Don't touch.", upgraded: "Hands off." },
  { id: 28, basic: "She's very jealous.", upgraded: "She's green with envy." },
  { id: 29, basic: "I made a mistake.", upgraded: "I screwed up." },
  { id: 30, basic: "How are you?", upgraded: "How have you been?" },
  { id: 31, basic: "I am fine.", upgraded: "I'm doing great, thanks for asking!" },
  { id: 32, basic: "What are you doing?", upgraded: "What are you up to?" },
  { id: 33, basic: "Nice to meet you.", upgraded: "Pleasure to meet you." },
  { id: 34, basic: "I woke up late.", upgraded: "I overslept today." },
  { id: 35, basic: "I am eating lunch.", upgraded: "I'm grabbing a quick bite." },
  { id: 36, basic: "I am very busy.", upgraded: "I'm swamped with work." },
  { id: 37, basic: "Let's go outside.", upgraded: "Let's step out for some fresh air." },
  { id: 38, basic: "I am happy.", upgraded: "I'm on cloud nine." },
  { id: 39, basic: "I am sad.", upgraded: "I'm feeling down." },
  { id: 40, basic: "I don't know.", upgraded: "I have no clue." },
  { id: 41, basic: "It's very important.", upgraded: "It's absolutely crucial." },
  { id: 42, basic: "Help me.", upgraded: "Could you lend me a hand?" },
  { id: 43, basic: "Wait a minute.", upgraded: "Hold on for a sec." },
  { id: 44, basic: "Can you repeat?", upgraded: "Could you say that again?" },
  { id: 45, basic: "Let's start.", upgraded: "Let's get the ball rolling." },
  { id: 46, basic: "I am tired.", upgraded: "I'm completely worn out." },
  { id: 47, basic: "It's too expensive.", upgraded: "It costs a fortune." },
  { id: 48, basic: "I'm going to sleep.", upgraded: "I'm hitting the sack." },
  { id: 49, basic: "I understand.", upgraded: "That makes sense." },
];

export type FullFormEntry = {
  id: number;
  word: string;
  fullForm: string;
};

/** Popular "backronyms" — fun/motivational expansions, not official etymologies. */
export const FULL_FORMS: FullFormEntry[] = [
  { id: 1, word: "OK", fullForm: "Objection Killed" },
  { id: 2, word: "NEWS", fullForm: "North East West South" },
  { id: 3, word: "NEWSPAPER", fullForm: "North East West South Past And Present Events Report" },
  { id: 4, word: "AIM", fullForm: "Ambition In Mind" },
  { id: 5, word: "EAT", fullForm: "Energy And Taste" },
  { id: 6, word: "TEA", fullForm: "Taste and Energy Admitted" },
  { id: 7, word: "BYE", fullForm: "Be with You Everytime" },
  { id: 8, word: "PEN", fullForm: "Power Enriched in Nib" },
  { id: 9, word: "PAPER", fullForm: "Past and Present Events Record" },
  { id: 10, word: "SMILE", fullForm: "Sweet Memories in Lips Expression" },
  { id: 11, word: "DATE", fullForm: "Day and Time Evolution" },
  { id: 12, word: "BUS", fullForm: "Big Utility System" },
  { id: 13, word: "CAR", fullForm: "Comfortable and Reliable" },
  { id: 14, word: "LIFE", fullForm: "Love Is For Everyone" },
  { id: 15, word: "LOVE", fullForm: "Lots of Valuable Emotions" },
  { id: 16, word: "FAMILY", fullForm: "Father And Mother I Love You" },
  { id: 17, word: "JOKE", fullForm: "Joy of Kids Entertainment" },
  { id: 18, word: "FAIL", fullForm: "First Attempt In Learning" },
  { id: 19, word: "NO", fullForm: "Next Opportunity" },
  { id: 20, word: "YES", fullForm: "Your Encouraging Source" },
  { id: 21, word: "END", fullForm: "Effort Never Dies" },
];

export const UPGRADE_YOUR_ENGLISH: SpeakSwap[] = [
  { id: 1, basic: "But", upgraded: "However" },
  { id: 2, basic: "So", upgraded: "Therefore" },
  { id: 3, basic: "And", upgraded: "Moreover" },
  { id: 4, basic: "Also", upgraded: "In addition" },
  { id: 5, basic: "Like", upgraded: "Such as" },
  { id: 6, basic: "Get", upgraded: "Obtain" },
  { id: 7, basic: "Help", upgraded: "Assist" },
  { id: 8, basic: "Buy", upgraded: "Purchase" },
  { id: 9, basic: "Show", upgraded: "Demonstrate" },
  { id: 10, basic: "Start", upgraded: "Commence" },
  { id: 11, basic: "End", upgraded: "Conclude" },
  { id: 12, basic: "Try", upgraded: "Attempt" },
  { id: 13, basic: "Tell", upgraded: "Inform" },
  { id: 14, basic: "Need", upgraded: "Require" },
  { id: 15, basic: "Give", upgraded: "Provide" },
  { id: 16, basic: "Fix", upgraded: "Resolve" },
  { id: 17, basic: "Use", upgraded: "Utilize" },
  { id: 18, basic: "Ask", upgraded: "Inquire" },
  { id: 19, basic: "Talk", upgraded: "Converse" },
  { id: 20, basic: "Think", upgraded: "Consider" },
];
