import type { JapaneseDialogueLine } from "@/lib/japanese-learning/types";

/** One practice line — readings are romaji for shadowing. */
function L(speaker: string, ja: string, reading: string, en: string): JapaneseDialogueLine {
  return { speaker, ja, reading, en };
}

/**
 * Extra scripted turns appended after each day’s seed dialogue.
 * Content follows Minna I lesson grammar / particles (not the old shared “CD homework” filler).
 */
export const N5_MINNA_PRACTICE_TAIL: Record<number, JapaneseDialogueLine[]> = {
  1: [
    L("田中", "わたしはたなかです。がくせいです。", "Watashi wa Tanaka desu. Gakusei desu.", "I’m Tanaka. I’m a student."),
    L("山田", "わたしはやまだです。せんせいですか。", "Watashi wa Yamada desu. Sensei desu ka.", "I’m Yamada. Are you a teacher?"),
    L("田中", "いいえ、がくせいです。", "Iie, gakusei desu.", "No, I’m a student."),
    L("山田", "そうですか。なんねんせいですか。", "Sō desu ka. Nan nensei desu ka.", "I see. What year are you?"),
    L("田中", "いちねんせいです。やまださんは？", "Ichi nensei desu. Yamada-san wa?", "I’m a first-year. How about you, Yamada?"),
    L("山田", "にねんせいです。", "Ni nensei desu.", "I’m a second-year."),
    L("田中", "アメリカじんですか。", "Amerikajin desu ka.", "Are you American?"),
    L("山田", "いいえ、かんこくじんです。", "Iie, Kankokujin desu.", "No, I’m Korean."),
    L("田中", "にほんごはむずかしいですか。", "Nihongo wa muzukashii desu ka.", "Is Japanese difficult?"),
    L("山田", "すこしむずかしいです。でもおもしろいです。", "Sukoshi muzukashii desu. Demo omoshiroi desu.", "A little difficult. But it’s interesting."),
    L("田中", "わたしもそうです。", "Watashi mo sō desu.", "Me too."),
    L("山田", "せんせいはにほんじんですか。", "Sensei wa Nihonjin desu ka.", "Is the teacher Japanese?"),
    L("田中", "はい、にほんじんです。", "Hai, Nihonjin desu.", "Yes, they’re Japanese."),
    L("山田", "じゃあ、あとでじしょをみます。", "Jā, atode jisho o mimasu.", "Then I’ll look at the dictionary later."),
    L("田中", "いっしょにいきませんか。", "Issho ni ikimasen ka.", "Won’t you go together?"),
    L("山田", "はい、いきます。", "Hai, ikimasu.", "Yes, I’ll go."),
    L("田中", "どうぞよろしくおねがいします。", "Dōzo yoroshiku onegaishimasu.", "Nice to meet you / please treat me well."),
    L("山田", "こちらこそ、よろしくおねがいします。", "Kochira koso, yoroshiku onegaishimasu.", "Same here — pleased to meet you."),
    L("田中", "じかんですね。", "Jikan desu ne.", "It’s time, isn’t it."),
    L("山田", "はい、またあした。", "Hai, mata ashita.", "Yes — see you tomorrow."),
  ],
  2: [
    L("店員", "いらっしゃいませ。", "Irasshaimase.", "Welcome."),
    L("客", "これはなんですか。", "Kore wa nan desu ka.", "What is this?"),
    L("店員", "それはじしょです。", "Sore wa jisho desu.", "That’s a dictionary."),
    L("客", "あれはなんですか。", "Are wa nan desu ka.", "What is that (over there)?"),
    L("店員", "あれはざっしです。", "Are wa zasshi desu.", "That’s a magazine."),
    L("客", "このペンはいくらですか。", "Kono pen wa ikura desu ka.", "How much is this pen?"),
    L("店員", "ひゃくえんです。", "Hyaku en desu.", "It’s 100 yen."),
    L("客", "そのかばんはいくらですか。", "Sono kaban wa ikura desu ka.", "How much is that bag?"),
    L("店員", "さんぜんごひゃくえんです。", "Sanzen gohyaku en desu.", "It’s 3,500 yen."),
    L("客", "このノートもやすいですね。", "Kono nōto mo yasui desu ne.", "This notebook is cheap too, isn’t it."),
    L("店員", "はい、やすいです。", "Hai, yasui desu.", "Yes, it’s cheap."),
    L("客", "それをください。", "Sore o kudasai.", "I’ll take that one, please."),
    L("店員", "ありがとうございます。", "Arigatō gozaimasu.", "Thank you."),
    L("客", "あのかさはいくらですか。", "Ano kasa wa ikura desu ka.", "How much is that umbrella over there?"),
    L("店員", "いちせんはっぴゃくえんです。", "Ichi sen happyaku en desu.", "It’s 1,800 yen."),
    L("客", "じゃあ、これとあれをください。", "Jā, kore to are o kudasai.", "Then I’ll take this and that one over there, please."),
    L("店員", "かしこまりました。", "Kashikomarimashita.", "Certainly."),
    L("客", "いっしょにいくらですか。", "Issho ni ikura desu ka.", "How much is it altogether?"),
    L("店員", "にせんひゃくえんです。", "Ni sen hyaku en desu.", "It’s 2,200 yen."),
    L("客", "ありがとうございました。", "Arigatō gozaimashita.", "Thank you very much."),
  ],
  3: [
    L("A", "つくえのうえになにがありますか。", "Tsukue no ue ni nani ga arimasu ka.", "What is on the desk?"),
    L("B", "ほんとペンがあります。", "Hon to pen ga arimasu.", "There is a book and a pen."),
    L("A", "かばんのなかにケータイがありますか。", "Kaban no naka ni kētai ga arimasu ka.", "Is there a phone in the bag?"),
    L("B", "はい、あります。", "Hai, arimasu.", "Yes, there is."),
    L("A", "へやのとなりにだれがいますか。", "Heya no tonari ni dare ga imasu ka.", "Who is next to the room?"),
    L("B", "せんせいがいます。", "Sensei ga imasu.", "The teacher is there."),
    L("A", "いすのしたにかぎがありますか。", "Isu no shita ni kagi ga arimasu ka.", "Is there a key under the chair?"),
    L("B", "いいえ、ありません。", "Iie, arimasen.", "No, there isn’t."),
    L("A", "まどのちかくにいすがあります。", "Mado no chikaku ni isu ga arimasu.", "There’s a chair near the window."),
    L("B", "そうですか。いいへやですね。", "Sō desu ka. Ii heya desu ne.", "I see. It’s a nice room, isn’t it."),
    L("A", "ほんだなのうえにもほんがあります。", "Hondana no ue ni mo hon ga arimasu.", "There are books on the bookshelf too."),
    L("B", "たくさんありますね。", "Takusan arimasu ne.", "There are a lot, aren’t there."),
    L("A", "こっぷはテーブルのうえにあります。", "Koppu wa tēburu no ue ni arimasu.", "The cup is on the table."),
    L("B", "みずもありますか。", "Mizu mo arimasu ka.", "Is there water too?"),
    L("A", "はい、れいぞうこのなかにあります。", "Hai, reizōko no naka ni arimasu.", "Yes, it’s in the fridge."),
    L("B", "ありがとうございます。", "Arigatō gozaimasu.", "Thank you."),
    L("A", "じゃあ、ここでべんきょうします。", "Jā, koko de benkyō shimasu.", "Then I’ll study here."),
    L("B", "いいですね。", "Ii desu ne.", "Sounds good."),
    L("A", "またあとで。", "Mata atode.", "See you later."),
    L("B", "はい、また。", "Hai, mata.", "Yes, see you."),
  ],
  4: [
    L("A", "まいにちなにをしますか。", "Mainichi nani o shimasu ka.", "What do you do every day?"),
    L("B", "あさジムでうんどうします。", "Asa jimu de undō shimasu.", "In the morning I exercise at the gym."),
    L("A", "きのうはなにをしましたか。", "Kinō wa nani o shimashita ka.", "What did you do yesterday?"),
    L("B", "きのうはコーヒーをのみました。", "Kinō wa kōhī o nomimashita.", "Yesterday I drank coffee."),
    L("A", "パンもたべましたか。", "Pan mo tabemashita ka.", "Did you eat bread too?"),
    L("B", "はい、パンもたべました。", "Hai, pan mo tabemashita.", "Yes, I ate bread too."),
    L("A", "きょうはべんきょうしますか。", "Kyō wa benkyō shimasu ka.", "Will you study today?"),
    L("B", "はい、よるべんきょうします。", "Hai, yoru benkyō shimasu.", "Yes, I’ll study at night."),
    L("A", "テレビをみますか。", "Terebi o mimasu ka.", "Will you watch TV?"),
    L("B", "いいえ、みません。", "Iie, mimasen.", "No, I won’t watch it."),
    L("A", "しんぶんはよみましたか。", "Shinbun wa yomimashita ka.", "Did you read the newspaper?"),
    L("B", "いいえ、よみませんでした。", "Iie, yomimasen deshita.", "No, I didn’t read it."),
    L("A", "しごとはなにをしますか。", "Shigoto wa nani o shimasu ka.", "What do you do for work?"),
    L("B", "メールをかきます。", "Mēru o kakimasu.", "I write emails."),
    L("A", "きのうもメールをかきましたか。", "Kinō mo mēru o kakimashita ka.", "Did you write emails yesterday too?"),
    L("B", "はい、たくさんかきました。", "Hai, takusan kakimashita.", "Yes, I wrote a lot."),
    L("A", "おつかれさまです。", "Otsukaresama desu.", "Good work / thanks for your effort."),
    L("B", "ありがとうございます。", "Arigatō gozaimasu.", "Thank you."),
    L("A", "またあした。", "Mata ashita.", "See you tomorrow."),
    L("B", "はい、また。", "Hai, mata.", "Yes, see you."),
  ],
  5: [
    L("A", "あしたどこへいきますか。", "Ashita doko e ikimasu ka.", "Where will you go tomorrow?"),
    L("B", "がっこうへいきます。", "Gakkō e ikimasu.", "I’ll go to school."),
    L("A", "なんでいきますか。", "Nan de ikimasu ka.", "How will you go?"),
    L("B", "ちかてつでいきます。", "Chikatetsu de ikimasu.", "I’ll go by subway."),
    L("A", "わたしはバスでいきます。", "Watashi wa basu de ikimasu.", "I’ll go by bus."),
    L("B", "ともだちといきますか。", "Tomodachi to ikimasu ka.", "Will you go with a friend?"),
    L("A", "いいえ、ひとりでいきます。", "Iie, hitori de ikimasu.", "No, I’ll go alone."),
    L("B", "いつかえりますか。", "Itsu kaerimasu ka.", "When will you come back?"),
    L("A", "ごごろくじにいえへかえります。", "Gogo rokuji ni ie e kaerimasu.", "I’ll return home at 6 p.m."),
    L("B", "いいですね。", "Ii desu ne.", "That’s nice."),
    L("A", "きょうはうみへいきません。", "Kyō wa umi e ikimasen.", "I’m not going to the sea today."),
    L("B", "どうしてですか。", "Dōshite desu ka.", "Why?"),
    L("A", "あめですから。", "Ame desu kara.", "Because it’s raining."),
    L("B", "そうですか。", "Sō desu ka.", "I see."),
    L("A", "じゃあ、えきまであるいていきます。", "Jā, eki made aruite ikimasu.", "Then I’ll walk as far as the station."),
    L("B", "あるいてですか。", "Aruite desu ka.", "On foot?"),
    L("A", "はい、ちかいですから。", "Hai, chikai desu kara.", "Yes, because it’s close."),
    L("B", "きをつけてください。", "Ki o tsukete kudasai.", "Please take care."),
    L("A", "ありがとうございます。", "Arigatō gozaimasu.", "Thank you."),
    L("B", "いってらっしゃい。", "Itterasshai.", "Have a good trip (said to someone leaving)."),
  ],
  6: [
    L("A", "あさごはんになにをたべますか。", "Asagohan ni nani o tabemasu ka.", "What do you eat for breakfast?"),
    L("B", "パンをたべます。", "Pan o tabemasu.", "I eat bread."),
    L("A", "のみものはなにをのみますか。", "Nomimono wa nani o nomimasu ka.", "What will you drink?"),
    L("B", "みずをのみます。", "Mizu o nomimasu.", "I’ll drink water."),
    L("A", "きょうひるはどこでたべますか。", "Kyō hiru wa doko de tabemasu ka.", "Where will you eat lunch today?"),
    L("B", "レストランでパスタをたべます。", "Resutoran de pasuta o tabemasu.", "I’ll eat pasta at a restaurant."),
    L("A", "コーヒーものみますか。", "Kōhī mo nomimasu ka.", "Will you drink coffee too?"),
    L("B", "はい、コーヒーをのみます。", "Hai, kōhī o nomimasu.", "Yes, I’ll drink coffee."),
    L("A", "うちでゆうはんをつくります。", "Uchi de yūhan o tsukurimasu.", "I’ll make dinner at home."),
    L("B", "なにをつくりますか。", "Nani o tsukurimasu ka.", "What will you make?"),
    L("A", "サラダとスープをつくります。", "Sarada to sūpu o tsukurimasu.", "I’ll make salad and soup."),
    L("B", "おいしそうですね。", "Oishisō desu ne.", "Sounds delicious."),
    L("A", "デザートにケーキをたべます。", "Dezāto ni kēki o tabemasu.", "For dessert I’ll eat cake."),
    L("B", "わたしもケーキがすきです。", "Watashi mo kēki ga suki desu.", "I like cake too."),
    L("A", "じゃあ、いっしょにたべませんか。", "Jā, issho ni tabemasen ka.", "Then won’t we eat together?"),
    L("B", "いいですね。", "Ii desu ne.", "Sounds good."),
    L("A", "みずをもういっぱいのみます。", "Mizu o mō ippai nomimasu.", "I’ll drink one more glass of water."),
    L("B", "きをつけてください。", "Ki o tsukete kudasai.", "Please take care."),
    L("A", "ありがとう。", "Arigatō.", "Thanks."),
    L("B", "どういたしまして。", "Dō itashimashite.", "You’re welcome."),
  ],
  7: [
    L("A", "ともだちにプレゼントをあげました。", "Tomodachi ni purezento o agemashita.", "I gave a present to my friend."),
    L("B", "なにをあげましたか。", "Nani o agemashita ka.", "What did you give?"),
    L("A", "かさをあげました。", "Kasa o agemashita.", "I gave an umbrella."),
    L("B", "せんせいにメールをもらいましたか。", "Sensei ni mēru o moraimashita ka.", "Did you receive an email from the teacher?"),
    L("A", "はい、もらいました。", "Hai, moraimashita.", "Yes, I received one."),
    L("B", "かぞくにてがみをもらいますか。", "Kazoku ni tegami o moraimasu ka.", "Will you get a letter from your family?"),
    L("A", "はい、らいしゅうもらいます。", "Hai, raishū moraimasu.", "Yes, I’ll get one next week."),
    L("B", "おとうさんにほんをあげますか。", "Otōsan ni hon o agemasu ka.", "Will you give your father a book?"),
    L("A", "はい、あげます。", "Hai, agemasu.", "Yes, I will."),
    L("B", "おかあさんにもプレゼントをあげますか。", "Okāsan ni mo purezento o agemasu ka.", "Will you give your mother a present too?"),
    L("A", "はい、はなもあげます。", "Hai, hana mo agemasu.", "Yes, I’ll give flowers too."),
    L("B", "やさしいですね。", "Yasashii desu ne.", "That’s kind of you."),
    L("A", "せんせいにノートをもらいました。", "Sensei ni nōto o moraimashita.", "I received a notebook from the teacher."),
    L("B", "なんとかいてありますか。", "Nanto kaite arimasu ka.", "What is written on it?"),
    L("A", "がんばってとかいてあります。", "Ganbatte to kaite arimasu.", "It says “do your best”."),
    L("B", "いいせんせいですね。", "Ii sensei desu ne.", "That’s a good teacher."),
    L("A", "ともだちにもメールをもらいました。", "Tomodachi ni mo mēru o moraimashita.", "I got an email from a friend too."),
    L("B", "たのしそうです。", "Tanoshisō desu.", "Sounds fun."),
    L("A", "じゃあ、またメールします。", "Jā, mata mēru shimasu.", "Then I’ll email again later."),
    L("B", "はい、また。", "Hai, mata.", "OK, talk again."),
  ],
  8: [
    L("A", "このバッグはあたらしいですか。", "Kono baggu wa atarashii desu ka.", "Is this bag new?"),
    L("B", "はい、あたらしいです。", "Hai, atarashii desu.", "Yes, it’s new."),
    L("A", "そのへやはしずかですか。", "Sono heya wa shizuka desu ka.", "Is that room quiet?"),
    L("B", "いいえ、あまりしずかじゃありません。", "Iie, amari shizuka ja arimasen.", "No, it’s not very quiet."),
    L("A", "このレストランはきれいですね。", "Kono resutoran wa kirei desu ne.", "This restaurant is clean/pretty, isn’t it."),
    L("B", "ええ、きれいなてんです。", "Ee, kirei na mise desu.", "Yes, it’s a nice shop."),
    L("A", "コーヒーはあついですか。", "Kōhī wa atsui desu ka.", "Is the coffee hot?"),
    L("B", "いいえ、すこしつめたいです。", "Iie, sukoshi tsumetai desu.", "No, it’s a little cold."),
    L("A", "このケーキはおいしいです。", "Kono kēki wa oishii desu.", "This cake is delicious."),
    L("B", "わたしもおいしいとおもいます。", "Watashi mo oishii to omoimasu.", "I think it’s delicious too."),
    L("A", "がくせいはげんきですか。", "Gakusei wa genki desu ka.", "Are the students well / lively?"),
    L("B", "はい、みんなげんきです。", "Hai, minna genki desu.", "Yes, everyone is fine."),
    L("A", "このくるまはおおきいですね。", "Kono kuruma wa ōkii desu ne.", "This car is big, isn’t it."),
    L("B", "でも、やすいです。", "Demo, yasui desu.", "But it’s cheap."),
    L("A", "そのとけいはたかいですか。", "Sono tokei wa takai desu ka.", "Is that watch expensive?"),
    L("B", "はい、ちょっとたかいです。", "Hai, chotto takai desu.", "Yes, it’s a bit expensive."),
    L("A", "じゃあ、やすいのをみます。", "Jā, yasui no o mimasu.", "Then I’ll look at a cheap one."),
    L("B", "いいですね。", "Ii desu ne.", "Good idea."),
    L("A", "ありがとう。", "Arigatō.", "Thanks."),
    L("B", "どういたしまして。", "Dō itashimashite.", "You’re welcome."),
  ],
  9: [
    L("A", "スポーツはなにがすきですか。", "Supōtsu wa nani ga suki desu ka.", "What sport do you like?"),
    L("B", "サッカーがすきです。", "Sakkā ga suki desu.", "I like soccer."),
    L("A", "ピアノはじょうずですか。", "Piano wa jōzu desu ka.", "Are you good at the piano?"),
    L("B", "いいえ、あまりじょうずじゃありません。", "Iie, amari jōzu ja arimasen.", "No, I’m not very good."),
    L("A", "えいごがわかりますか。", "Eigo ga wakarimasu ka.", "Do you understand English?"),
    L("B", "すこしわかります。", "Sukoshi wakarimasu.", "I understand a little."),
    L("A", "にほんごはむずかしいですから、べんきょうします。", "Nihongo wa muzukashii desu kara, benkyō shimasu.", "Because Japanese is difficult, I study."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "おんがくがきらいですか。", "Ongaku ga kirai desu ka.", "Do you dislike music?"),
    L("B", "いいえ、すきです。", "Iie, suki desu.", "No, I like it."),
    L("A", "りょうりはへたですか。", "Ryōri wa heta desu ka.", "Are you bad at cooking?"),
    L("B", "はい、へたです。", "Hai, heta desu.", "Yes, I’m bad at it."),
    L("A", "じゃあ、いっしょにりょうりをべんきょうしましょう。", "Jā, issho ni ryōri o benkyō shimashō.", "Then let’s study cooking together."),
    L("B", "いいですね。", "Ii desu ne.", "Sounds good."),
    L("A", "サッカーがじょうずなともだちがいます。", "Sakkā ga jōzu na tomodachi ga imasu.", "I have a friend who’s good at soccer."),
    L("B", "そうですか。", "Sō desu ka.", "I see."),
    L("A", "えいごのえいががすきです。", "Eigo no eiga ga suki desu.", "I like English movies."),
    L("B", "わたしもすきです。", "Watashi mo suki desu.", "I like them too."),
    L("A", "またあとでね。", "Mata atode ne.", "See you later."),
    L("B", "はい、また。", "Hai, mata.", "OK, bye."),
  ],
  10: [
    L("A", "にわにだれがいますか。", "Niwa ni dare ga imasu ka.", "Who is in the yard?"),
    L("B", "こどもがいます。", "Kodomo ga imasu.", "There are children."),
    L("A", "いぬもいますか。", "Inu mo imasu ka.", "Is there a dog too?"),
    L("B", "はい、いぬもいます。", "Hai, inu mo imasu.", "Yes, there’s a dog too."),
    L("A", "こうえんにねこがいますか。", "Kōen ni neko ga imasu ka.", "Is there a cat in the park?"),
    L("B", "いいえ、いません。", "Iie, imasen.", "No, there isn’t."),
    L("A", "テーブルのうえにコップがありますね。", "Tēburu no ue ni koppu ga arimasu ne.", "There’s a cup on the table, right?"),
    L("B", "はい、みずがあります。", "Hai, mizu ga arimasu.", "Yes, there’s water."),
    L("A", "へやのなかにテレビがありますか。", "Heya no naka ni terebi ga arimasu ka.", "Is there a TV in the room?"),
    L("B", "はい、あります。", "Hai, arimasu.", "Yes, there is."),
    L("A", "いすのとなりにかばんがあります。", "Isu no tonari ni kaban ga arimasu.", "There’s a bag next to the chair."),
    L("B", "だれのかばんですか。", "Dare no kaban desu ka.", "Whose bag is it?"),
    L("A", "やまださんのかばんです。", "Yamada-san no kaban desu.", "It’s Yamada’s bag."),
    L("B", "そうですか。", "Sō desu ka.", "I see."),
    L("A", "がっこうにせんせいがいます。", "Gakkō ni sensei ga imasu.", "The teacher is at school."),
    L("B", "がくせいもいますか。", "Gakusei mo imasu ka.", "Are there students too?"),
    L("A", "はい、たくさんいます。", "Hai, takusan imasu.", "Yes, there are many."),
    L("B", "にぎやかですね。", "Nigiyaka desu ne.", "It’s lively, isn’t it."),
    L("A", "じゃあ、いきましょう。", "Jā, ikimashō.", "Let’s go."),
    L("B", "はい。", "Hai.", "OK."),
  ],
  11: [
    L("客", "ケーキをひとつください。", "Kēki o hitotsu kudasai.", "One cake, please."),
    L("店員", "はい、にひゃくえんです。", "Hai, nihyaku en desu.", "Yes — 200 yen."),
    L("客", "ビールをさんぼんください。", "Bīru o sanbon kudasai.", "Three bottles of beer, please."),
    L("店員", "かしこまりました。", "Kashikomarimashita.", "Certainly."),
    L("客", "みずをふたつください。", "Mizu o futatsu kudasai.", "Two waters, please."),
    L("店員", "いっしょにごひゃくえんです。", "Issho gohyaku en desu.", "Together that’s 500 yen."),
    L("客", "このりんごをよっつください。", "Kono ringo o yottsu kudasai.", "Four apples, please."),
    L("店員", "はい、よっつですね。", "Hai, yottsu desu ne.", "Yes, four, right?"),
    L("店員", "おにぎりはいくつですか。", "Onigiri wa ikutsu desu ka.", "How many rice balls?"),
    L("客", "みっつください。", "Mittsu kudasai.", "Three, please."),
    L("店員", "はい、かしこまりました。", "Hai, kashikomarimashita.", "Yes, certainly."),
    L("客", "あとでざっしもひとつください。", "Ato de zasshi mo hitotsu kudasai.", "Later I’ll take one magazine too, please."),
    L("店員", "ありがとうございます。", "Arigatō gozaimasu.", "Thank you."),
    L("客", "おつりはいくらですか。", "Otsuri wa ikura desu ka.", "How much is the change?"),
    L("店員", "ひゃくえんです。", "Hyaku en desu.", "100 yen."),
    L("客", "ありがとうございました。", "Arigatō gozaimashita.", "Thank you very much."),
    L("店員", "またどうぞ。", "Mata dōzo.", "Please come again."),
    L("客", "ひとつだけすみません。", "Hitotsu dake sumimasen.", "Sorry — just one more thing."),
    L("店員", "はい。", "Hai.", "Yes?"),
    L("客", "ざっしをいっさつください。", "Zasshi o issatsu kudasai.", "One magazine, please."),
    L("店員", "はい、ごじゅうえんです。", "Hai, gojū en desu.", "Yes — 50 yen."),
  ],
  12: [
    L("A", "きのうはひまでしたか。", "Kinō wa hima deshita ka.", "Were you free yesterday?"),
    L("B", "はい、ひまでした。", "Hai, hima deshita.", "Yes, I was free."),
    L("A", "ホテルはどちらがやすかったですか。", "Hoteru wa dochira ga yasukatta desu ka.", "Which hotel was cheaper?"),
    L("B", "こちらのほうがやすかったです。", "Kochira no hō ga yasukatta desu.", "This side was cheaper."),
    L("A", "おんせんはどこがいちばんよかったですか。", "Onsen wa doko ga ichiban yokatta desu ka.", "Which onsen was best?"),
    L("B", "やまのほうがよかったです。", "Yama no hō ga yokatta desu.", "The one in the mountains was better."),
    L("A", "きのうよりきょうのほうがあついです。", "Kinō yori kyō no hō ga atsui desu.", "Today is hotter than yesterday."),
    L("B", "そうですね。", "Sō desu ne.", "That’s right."),
    L("A", "バスよりでんしゃのほうがはやかったです。", "Basu yori densha no hō ga hayakatta desu.", "The train was faster than the bus."),
    L("B", "じゃあ、あしたもでんしゃにします。", "Jā, ashita mo densha ni shimasu.", "Then I’ll take the train tomorrow too."),
    L("A", "このコーヒーのほうがあまいです。", "Kono kōhī no hō ga amai desu.", "This coffee is sweeter."),
    L("B", "わたしはすっぱいのがすきです。", "Watashi wa suppai no ga suki desu.", "I like sour ones."),
    L("A", "きのうのばんごはんはからかったです。", "Kinō no bangohan wa karakatta desu.", "Yesterday’s dinner was spicy."),
    L("B", "でもおいしかったです。", "Demo oishikatta desu.", "But it was delicious."),
    L("A", "いちばんたかかったのはどれですか。", "Ichiban takakatta no wa dore desu ka.", "Which was the most expensive?"),
    L("B", "ケーキでした。", "Kēki deshita.", "The cake."),
    L("A", "そうですか。", "Sō desu ka.", "I see."),
    L("B", "いちばんやすかったのはパンです。", "Ichiban yasukatta no wa pan desu.", "The cheapest was bread."),
    L("A", "ありがとう。", "Arigatō.", "Thanks."),
    L("B", "どういたしまして。", "Dō itashimashite.", "You’re welcome."),
  ],
  13: [
    L("A", "なにがほしいですか。", "Nani ga hoshii desu ka.", "What do you want?"),
    L("B", "ギターがほしいです。", "Gitā ga hoshii desu.", "I want a guitar."),
    L("A", "きょうなにをしたいですか。", "Kyō nani o shitai desu ka.", "What do you want to do today?"),
    L("B", "しょくじをつくりたいです。", "Shokuji o tsukuritai desu.", "I want to cook a meal."),
    L("A", "あしたどこへいきますか。", "Ashita doko e ikimasu ka.", "Where will you go tomorrow?"),
    L("B", "えいがをみにいきます。", "Eiga o mi ni ikimasu.", "I’ll go to watch a movie."),
    L("A", "だれとえいがをみにいきますか。", "Dare to eiga o mi ni ikimasu ka.", "Who will you go to the movies with?"),
    L("B", "ともだちといきます。", "Tomodachi to ikimasu.", "With a friend."),
    L("A", "にほんへりょこうしたいですか。", "Nihon e ryokō shitai desu ka.", "Do you want to travel to Japan?"),
    L("B", "はい、ぜひいきたいです。", "Hai, zehi ikitai desu.", "Yes, I really want to go."),
    L("A", "なにをかいたいですか。", "Nani o kakitai desu ka.", "What do you want to write?"),
    L("B", "てがみをかきたいです。", "Tegami o kakitai desu.", "I want to write a letter."),
    L("A", "しんぶんをよみたいですか。", "Shinbun o yomitai desu ka.", "Do you want to read the newspaper?"),
    L("B", "いいえ、じかんがありません。", "Iie, jikan ga arimasen.", "No, I don’t have time."),
    L("A", "じゃあ、いっしょにコーヒーをのみにいきませんか。", "Jā, issho ni kōhī o nomi ni ikimasen ka.", "Then won’t we go for coffee together?"),
    L("B", "いいですね。", "Ii desu ne.", "Sounds good."),
    L("A", "あたらしいかばんがほしいです。", "Atarashii kaban ga hoshii desu.", "I want a new bag."),
    L("B", "いっしょにみにいきましょう。", "Issho ni mi ni ikimashō.", "Let’s go look together."),
    L("A", "はい。", "Hai.", "OK."),
    L("B", "じゃあ、あした。", "Jā, ashita.", "Then tomorrow."),
  ],
  14: [
    L("A", "もうはみがきをしましたか。", "Mō hamigaki o shimashita ka.", "Have you already brushed your teeth?"),
    L("B", "はい、しました。", "Hai, shimashita.", "Yes, I have."),
    L("A", "ドアをしめてください。", "Doa o shimete kudasai.", "Please close the door."),
    L("B", "はい、しめます。", "Hai, shimemasu.", "Yes, I will."),
    L("A", "まってください。", "Matte kudasai.", "Please wait."),
    L("B", "わかりました。", "Wakarimashita.", "Understood."),
    L("A", "コピーをとっていますか。", "Kopī o totte imasu ka.", "Are you making a copy?"),
    L("B", "はい、いまとっています。", "Hai, ima totte imasu.", "Yes, I’m making one now."),
    L("A", "てがみをかいていますか。", "Tegami o kaite imasu ka.", "Are you writing a letter?"),
    L("B", "いいえ、メールをかいています。", "Iie, mēru o kaite imasu.", "No, I’m writing an email."),
    L("A", "ここにすわってもいいですか。", "Koko ni suwatte mo ii desu ka.", "May I sit here?"),
    L("B", "はい、すわってください。", "Hai, suwatte kudasai.", "Yes, please sit."),
    L("A", "まどをあけてください。", "Mado o akete kudasai.", "Please open the window."),
    L("B", "はい、あけます。", "Hai, akemasu.", "Yes, I’ll open it."),
    L("A", "テレビをみていますか。", "Terebi o mite imasu ka.", "Are you watching TV?"),
    L("B", "いいえ、べんきょうしています。", "Iie, benkyō shite imasu.", "No, I’m studying."),
    L("A", "じゃあ、しずかにしてください。", "Jā, shizuka ni shite kudasai.", "Then please be quiet."),
    L("B", "すみません。", "Sumimasen.", "Sorry."),
    L("A", "だいじょうぶです。", "Daijōbu desu.", "It’s OK."),
    L("B", "ありがとうございます。", "Arigatō gozaimasu.", "Thank you."),
  ],
  15: [
    L("客", "しゃしんをとってもいいですか。", "Shashin o totte mo ii desu ka.", "May I take photos?"),
    L("店員", "はい、いいです。", "Hai, ii desu.", "Yes, you may."),
    L("A", "ここではたばこをすってはいけません。", "Koko de wa tabako o sutte wa ikemasen.", "You must not smoke here."),
    L("B", "わかりました。", "Wakarimashita.", "Understood."),
    L("A", "おしゃべりしてはいけません。", "Oshaberi shite wa ikemasen.", "You must not chat."),
    L("B", "すみません。", "Sumimasen.", "Sorry."),
    L("客", "はいってもいいですか。", "Haitte mo ii desu ka.", "May I come in?"),
    L("先生", "はい、どうぞ。", "Hai, dōzo.", "Yes, please."),
    L("A", "スマホをみてもいいですか。", "Sumaho o mite mo ii desu ka.", "May I look at my phone?"),
    L("B", "いいえ、だめです。", "Iie, dame desu.", "No, you may not."),
    L("A", "ここでたべてもいいですか。", "Koko de tabete mo ii desu ka.", "May I eat here?"),
    L("B", "はい、いいですよ。", "Hai, ii desu yo.", "Yes, that’s fine."),
    L("A", "みちをわたってはいけません。", "Michi o watatte wa ikemasen.", "You must not cross the road (here)."),
    L("B", "きをつけます。", "Ki o tsukemasu.", "I’ll be careful."),
    L("客", "みずをのんでもいいですか。", "Mizu o nonde mo ii desu ka.", "May I drink water?"),
    L("店員", "はい、どうぞ。", "Hai, dōzo.", "Yes, go ahead."),
    L("A", "ここではおさけをのんではいけません。", "Koko de wa osake o nonde wa ikemasen.", "You must not drink alcohol here."),
    L("B", "わかりました。", "Wakarimashita.", "Understood."),
    L("A", "ありがとうございます。", "Arigatō gozaimasu.", "Thank you."),
    L("B", "どういたしまして。", "Dō itashimashite.", "You’re welcome."),
  ],
  16: [
    L("A", "シャワーをあびてからねます。", "Shawā o abite kara nemasu.", "After showering I sleep."),
    L("B", "ごはんをたべてから？", "Gohan o tabete kara?", "After eating?"),
    L("A", "はい、たべてからねます。", "Hai, tabete kara nemasu.", "Yes, after eating I sleep."),
    L("B", "きのうはどうでしたか。", "Kinō wa dō deshita ka.", "How was yesterday?"),
    L("A", "びょうきだったからやすみました。", "Byōki datta kara yasumimashita.", "Because I was sick I took a day off."),
    L("B", "いまはだいじょうぶですか。", "Ima wa daijōbu desu ka.", "Are you OK now?"),
    L("A", "はい、だいじょうぶです。", "Hai, daijōbu desu.", "Yes, I’m fine."),
    L("B", "あさおきてからジムへいきますか。", "Asa okite kara jimu e ikimasu ka.", "After waking up do you go to the gym?"),
    L("A", "いいえ、はたらいてからいきます。", "Iie, hataraite kara ikimasu.", "No, I go after working."),
    L("B", "そうですか。", "Sō desu ka.", "I see."),
    L("A", "はみがきをしてからでかけます。", "Hamigaki o shite kara dekakemasu.", "After brushing my teeth I go out."),
    L("B", "いいくせですね。", "Ii kuse desu ne.", "That’s a good habit."),
    L("A", "あめだったからバスでいきました。", "Ame datta kara basu de ikimashita.", "Because it was raining I went by bus."),
    L("B", "じゃあ、きょうはあるきますか。", "Jā, kyō wa arukimasu ka.", "Then will you walk today?"),
    L("A", "はい、はれているからあるきます。", "Hai, harete iru kara arukimasu.", "Yes, because it’s sunny I’ll walk."),
    L("B", "きをつけてください。", "Ki o tsukete kudasai.", "Please take care."),
    L("A", "コーヒーをのんでからべんきょうします。", "Kōhī o nonde kara benkyō shimasu.", "After drinking coffee I study."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "じゃあ、いっしょに。", "Jā, issho ni.", "Then together."),
    L("B", "はい。", "Hai.", "OK."),
  ],
  17: [
    L("A", "バスにのらなくてもいいです。", "Basu ni noranakute mo ii desu.", "You don’t have to take the bus."),
    L("B", "あるいてもいいですか。", "Aruite mo ii desu ka.", "May I walk?"),
    L("A", "はい、いいです。", "Hai, ii desu.", "Yes, that’s fine."),
    L("B", "ろうかをはしらないでください。", "Rōka o hashiranaide kudasai.", "Please don’t run in the hallway."),
    L("A", "わかりました。", "Wakarimashita.", "Understood."),
    L("B", "おそくかえらないでください。", "Osoku kaeranaide kudasai.", "Please don’t come home late."),
    L("A", "はい、きをつけます。", "Hai, ki o tsukemasu.", "Yes, I’ll be careful."),
    L("B", "しゃしんをとらないでください。", "Shashin o toranaide kudasai.", "Please don’t take photos."),
    L("A", "すみません。", "Sumimasen.", "Sorry."),
    L("B", "けいたいをみないでください。", "Keitai o minaide kudasai.", "Please don’t look at your phone."),
    L("A", "はい、みません。", "Hai, mimasen.", "OK, I won’t look."),
    L("B", "しずかにしてください。", "Shizuka ni shite kudasai.", "Please be quiet."),
    L("A", "あ、すみません。", "A, sumimasen.", "Oh, sorry."),
    L("B", "だいじょうぶです。", "Daijōbu desu.", "It’s OK."),
    L("A", "しゅくだいをしなくてもいいですか。", "Shukudai o shinakute mo ii desu ka.", "Do I not have to do homework?"),
    L("B", "いいえ、しなくてはいけません。", "Iie, shinakute wa ikemasen.", "No — you must do it."),
    L("A", "わかりました。", "Wakarimashita.", "Understood."),
    L("B", "がんばってください。", "Ganbatte kudasai.", "Please do your best."),
    L("A", "はい。", "Hai.", "Yes."),
    L("B", "ありがとう。", "Arigatō.", "Thanks."),
  ],
  18: [
    L("A", "にほんごをはなすことができますか。", "Nihongo o hanasu koto ga dekimasu ka.", "Can you speak Japanese?"),
    L("B", "すこしはなすことができます。", "Sukoshi hanasu koto ga dekimasu.", "I can speak a little."),
    L("A", "ピアノをひくことができますか。", "Piano o hiku koto ga dekimasu ka.", "Can you play the piano?"),
    L("B", "いいえ、できません。", "Iie, dekimasen.", "No, I can’t."),
    L("A", "ねるまえにほんをよみます。", "Neru mae ni hon o yomimasu.", "Before sleeping I read a book."),
    L("B", "わたしはシャワーをあびるまえにうがいをします。", "Watashi wa shawā o abiru mae ni ugai o shimasu.", "Before taking a shower I gargle."),
    L("A", "しごとのあとにジョギングをします。", "Shigoto no ato ni jogingu o shimasu.", "After work I jog."),
    L("B", "いいですね。", "Ii desu ne.", "Nice."),
    L("A", "かんじをかくことがまだできません。", "Kanji o kaku koto ga mada dekimasen.", "I still can’t write kanji."),
    L("B", "れんしゅうすればできます。", "Renshū sureba dekimasu.", "If you practise, you can."),
    L("A", "スイミングにいくまえにたべません。", "Suimingu ni iku mae ni tabemasen.", "Before going swimming I don’t eat."),
    L("B", "きをつけていますね。", "Ki o tsukete imasu ne.", "You’re careful, aren’t you."),
    L("A", "えいごでメールをかくことができます。", "Eigo de mēru o kaku koto ga dekimasu.", "I can write emails in English."),
    L("B", "すごいですね。", "Sugoi desu ne.", "That’s amazing."),
    L("A", "でんしゃにのるまえにきっぷをかいます。", "Densha ni noru mae ni kippu o kaimasu.", "Before getting on the train I buy a ticket."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "じゃあ、いっしょにいきましょう。", "Jā, issho ni ikimashō.", "Let’s go together."),
    L("B", "はい。", "Hai.", "OK."),
    L("A", "ありがとう。", "Arigatō.", "Thanks."),
    L("B", "どういたしまして。", "Dō itashimashite.", "You’re welcome."),
  ],
  19: [
    L("A", "きょうとへいったことがありますか。", "Kyōto e itta koto ga arimasu ka.", "Have you ever been to Kyoto?"),
    L("B", "はい、あります。", "Hai, arimasu.", "Yes, I have."),
    L("A", "すしをたべたことがありますか。", "Sushi o tabeta koto ga arimasu ka.", "Have you ever eaten sushi?"),
    L("B", "いいえ、ありません。", "Iie, arimasen.", "No, I haven’t."),
    L("A", "べんきょうがもっとすきになりました。", "Benkyō ga motto suki ni narimashita.", "I came to like studying more."),
    L("B", "なぜですか。", "Naze desu ka.", "Why?"),
    L("A", "せんせいがやさしかったからです。", "Sensei ga yasashikatta kara desu.", "Because the teacher was kind."),
    L("B", "いいせんせいですね。", "Ii sensei desu ne.", "That’s a good teacher."),
    L("A", "にほんごがじょうずになりました。", "Nihongo ga jōzu ni narimashita.", "My Japanese got better."),
    L("B", "がんばりましたね。", "Ganbarimashita ne.", "You worked hard."),
    L("A", "ふゆはさむくなります。", "Fuyu wa samuku narimasu.", "In winter it gets cold."),
    L("B", "そうですね。", "Sō desu ne.", "That’s right."),
    L("A", "にほんへいったことがあります。", "Nihon e itta koto ga arimasu.", "I’ve been to Japan before."),
    L("B", "いついきましたか。", "Itsu ikimashita ka.", "When did you go?"),
    L("A", "きょねんいきました。", "Kyonen ikimashita.", "I went last year."),
    L("B", "すごいですね。", "Sugoi desu ne.", "Amazing."),
    L("A", "スキーもしたことがあります。", "Sukī mo shita koto ga arimasu.", "I’ve also skied before."),
    L("B", "じょうずでしたか。", "Jōzu deshita ka.", "Were you good at it?"),
    L("A", "まあまあでした。", "Māmā deshita.", "So-so."),
    L("B", "またきいてください。", "Mata kiite kudasai.", "Ask me again sometime."),
  ],
  20: [
    L("A", "きょうはやすみだ。", "Kyō wa yasumi da.", "Today’s a day off."),
    L("B", "いいな。", "Ii na.", "Lucky you."),
    L("A", "あしたテストがあるんだ。", "Ashita tesuto ga arun da.", "There’s a test tomorrow."),
    L("B", "そうなの？", "Sō nano?", "Really?"),
    L("A", "うん、だいじょうぶだとおもう。", "Un, daijōbu da to omou.", "Yeah, I think it’ll be OK."),
    L("B", "がんばって。", "Ganbatte.", "Good luck."),
    L("A", "このカフェ、しずかだね。", "Kono kafe, shizuka da ne.", "This café’s quiet, huh."),
    L("B", "うん、きれいだし。", "Un, kirei dashi.", "Yeah, and it’s nice."),
    L("A", "コーヒー、おいしいじゃない？", "Kōhī, oishii ja nai?", "The coffee’s good, isn’t it?"),
    L("B", "おいしいよ。", "Oishii yo.", "It’s good."),
    L("A", "でも、たかいんだ。", "Demo, takai n da.", "But it’s expensive."),
    L("B", "まあね。", "Mā ne.", "Well, yeah."),
    L("A", "じゃあ、つぎはやすいところにいこう。", "Jā, tsugi wa yasui tokoro ni ikō.", "Then next time let’s go somewhere cheap."),
    L("B", "いいよ。", "Ii yo.", "Sure."),
    L("A", "あしたははれるかな。", "Ashita wa hareru kana.", "I wonder if it’ll clear up tomorrow."),
    L("B", "うんうん。", "Un un.", "Mm-hmm."),
    L("A", "そろそろかえる。", "Sorosoro kaeru.", "I’ll head home soon."),
    L("B", "またね。", "Mata ne.", "See you."),
    L("A", "またあした。", "Mata ashita.", "See you tomorrow."),
    L("B", "ばいばい。", "Baibai.", "Bye."),
  ],
  21: [
    L("A", "あしたはあめだとおもいます。", "Ashita wa ame da to omoimasu.", "I think it will rain tomorrow."),
    L("B", "わたしははれるとおもいます。", "Watashi wa hareru to omoimasu.", "I think it’ll clear up."),
    L("A", "ヤマダさんはエンジニアだとおもいます。", "Yamada-san wa enjinia da to omoimasu.", "I think Yamada is an engineer."),
    L("B", "そうかもしれません。", "Sō kamoshiremasen.", "That may be so."),
    L("A", "このてすとはむずかしいとおもいます。", "Kono tesuto wa muzukashii to omoimasu.", "I think this test is hard."),
    L("B", "わたしもそうおもいます。", "Watashi mo sō omoimasu.", "I think so too."),
    L("A", "かれはやさしいひとだとおもいます。", "Kare wa yasashii hito da to omoimasu.", "I think he’s a kind person."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "にほんごのべんきょうはたのしいとおもいます。", "Nihongo no benkyō wa tanoshii to omoimasu.", "I think studying Japanese is fun."),
    L("B", "いいですね。", "Ii desu ne.", "That’s nice."),
    L("A", "きょうははやくおわるとおもいます。", "Kyō wa hayaku owaru to omoimasu.", "I think today will end early."),
    L("B", "そうだといいですね。", "Sō da to ii desu ne.", "I hope so."),
    L("A", "このほんはおもしろいとききました。", "Kono hon wa omoshiroi to kikimashita.", "I heard this book is interesting."),
    L("B", "じゃあ、よみたいです。", "Jā, yomitai desu.", "Then I want to read it."),
    L("A", "テストはかんたんだとおもいます。", "Tesuto wa kantan da to omoimasu.", "I think the test is easy."),
    L("B", "ほんとうですか。", "Hontō desu ka.", "Really?"),
    L("A", "うそです。", "Uso desu.", "I’m kidding."),
    L("B", "もう。", "Mō.", "Geez."),
    L("A", "じゃあ、がんばりましょう。", "Jā, ganbarimashō.", "Let’s do our best."),
    L("B", "はい。", "Hai.", "OK."),
  ],
  22: [
    L("A", "これはせんせいがかいたえです。", "Kore wa sensei ga kaita e desu.", "This is a picture the teacher drew."),
    L("B", "じょうずなえですね。", "Jōzu na e desu ne.", "It’s a skilled drawing."),
    L("A", "おおきいペンをかったひとがいます。", "Ōkii pen o katta hito ga imasu.", "There is someone who bought a big pen."),
    L("B", "どんなひとですか。", "Donna hito desu ka.", "What kind of person?"),
    L("A", "あかいぼうしをかぶったひとです。", "Akai bōshi o kabutta hito desu.", "A person wearing a red hat."),
    L("B", "わかりました。", "Wakarimashita.", "Understood."),
    L("A", "きのうかったほんをよみました。", "Kinō katta hon o yomimashita.", "I read the book I bought yesterday."),
    L("B", "おもしろかったですか。", "Omoshirokatta desu ka.", "Was it interesting?"),
    L("A", "はい、とてもおもしろかったです。", "Hai, totemo omoshirokatta desu.", "Yes, it was very interesting."),
    L("B", "わたしもよみたいです。", "Watashi mo yomitai desu.", "I want to read it too."),
    L("A", "メールをおくったひとはだれですか。", "Mēru o okutta hito wa dare desu ka.", "Who is the person who sent the email?"),
    L("B", "やまださんです。", "Yamada-san desu.", "It’s Yamada."),
    L("A", "ここにあるかさはだれのかさですか。", "Koko ni aru kasa wa dare no kasa desu ka.", "Whose umbrella is this here?"),
    L("B", "わたしのかさです。", "Watashi no kasa desu.", "It’s my umbrella."),
    L("A", "すみません。", "Sumimasen.", "Excuse me."),
    L("B", "いいえ。", "Iie.", "No problem."),
    L("A", "あしたわたすほんをもってきてください。", "Ashita watasu hon o motte kite kudasai.", "Please bring the book I’ll lend you tomorrow."),
    L("B", "はい、わかりました。", "Hai, wakarimashita.", "Yes, understood."),
    L("A", "ありがとう。", "Arigatō.", "Thanks."),
    L("B", "どういたしまして。", "Dō itashimashite.", "You’re welcome."),
  ],
  23: [
    L("A", "ひまなときにジムへいきます。", "Hima na toki ni jimu e ikimasu.", "When I’m free I go to the gym."),
    L("B", "いそがしいときは？", "Isogashii toki wa?", "When you’re busy?"),
    L("A", "いそがしいときはいきません。", "Isogashii toki wa ikimasen.", "When I’m busy I don’t go."),
    L("B", "あめがふるときはなにをしますか。", "Ame ga furu toki wa nani o shimasu ka.", "When it rains what do you do?"),
    L("A", "うちでべんきょうします。", "Uchi de benkyō shimasu.", "I study at home."),
    L("B", "はれているときは？", "Harete iru toki wa?", "When it’s sunny?"),
    L("A", "さんぽします。", "Sanpo shimasu.", "I take a walk."),
    L("B", "いいですね。", "Ii desu ne.", "Nice."),
    L("A", "がくせいだったときアルバイトをしました。", "Gakusei datta toki arubaito o shimashita.", "When I was a student I did a part-time job."),
    L("B", "どんなアルバイトでしたか。", "Donna arubaito deshita ka.", "What kind of job was it?"),
    L("A", "コンビニでした。", "Konbini deshita.", "It was at a convenience store."),
    L("B", "たいへんでしたね。", "Taihen deshita ne.", "That must have been tough."),
    L("A", "ねむいときコーヒーをのみます。", "Nemui toki kōhī o nomimasu.", "When I’m sleepy I drink coffee."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "やすみのときによくりょこうします。", "Yasumi no toki ni yoku ryokō shimasu.", "On days off I often travel."),
    L("B", "どこへいきますか。", "Doko e ikimasu ka.", "Where do you go?"),
    L("A", "いろいろです。", "Iroiro desu.", "Various places."),
    L("B", "すごいですね。", "Sugoi desu ne.", "Amazing."),
    L("A", "じゃあ、また。", "Jā, mata.", "See you."),
    L("B", "はい。", "Hai.", "OK."),
  ],
  24: [
    L("A", "ともだちにケーキをつくってあげました。", "Tomodachi ni kēki o tsukutte agemashita.", "I made a cake for my friend."),
    L("B", "やさしいですね。", "Yasashii desu ne.", "That’s kind."),
    L("A", "せんせいにメールをおくってもらいました。", "Sensei ni mēru o okutte moraimashita.", "I had the teacher send an email (for me)."),
    L("B", "たすかりましたね。", "Tasukarimashita ne.", "That helped, didn’t it."),
    L("A", "かさをかしてくれました。", "Kasa o kashite kuremashita.", "They lent me an umbrella."),
    L("B", "いいひとですね。", "Ii hito desu ne.", "That’s a good person."),
    L("A", "じしょをかしてあげました。", "Jisho o kashite agemashita.", "I lent a dictionary."),
    L("B", "ありがとう。", "Arigatō.", "Thanks."),
    L("A", "えいごをおしえてもらいました。", "Eigo o oshiete moraimashita.", "I was taught English (by someone)."),
    L("B", "じょうずになりましたね。", "Jōzu ni narimashita ne.", "You’ve gotten good."),
    L("A", "でんわをかけてくれました。", "Denwa o kakete kuremashita.", "They called for me / placed a call for me."),
    L("B", "やさしいですね。", "Yasashii desu ne.", "That’s kind."),
    L("A", "つくりかたをおしえてあげました。", "Tsukurikata o oshiete agemashita.", "I taught how to make it."),
    L("B", "おかげでできました。", "Okage de dekimashita.", "Thanks to you I could do it."),
    L("A", "いっしょにいってもらいます。", "Issho ni itte moraimasu.", "I’ll have them go with me."),
    L("B", "いいですね。", "Ii desu ne.", "Sounds good."),
    L("A", "じゃあ、あしたね。", "Jā, ashita ne.", "See you tomorrow."),
    L("B", "はい。", "Hai.", "OK."),
    L("A", "ありがとうございました。", "Arigatō gozaimashita.", "Thank you very much."),
    L("B", "こちらこそ。", "Kochira koso.", "Same here."),
  ],
  25: [
    L("A", "ひまだったらゲームをしましょう。", "Hima dattara gēmu o shimashō.", "If we’re free let’s play games."),
    L("B", "いいよ。", "Ii yo.", "Sure."),
    L("A", "あめでもいきます。", "Ame demo ikimasu.", "Even if it rains I’ll go."),
    L("B", "つよいですね。", "Tsuyoi desu ne.", "You’re strong-willed."),
    L("A", "やすかったらかいます。", "Yasukattara kaimasu.", "If it’s cheap I’ll buy it."),
    L("B", "わかりました。", "Wakarimashita.", "OK."),
    L("A", "まにあわなかったらどうしますか。", "Maniawanakattara dō shimasu ka.", "What will you do if you don’t make it in time?"),
    L("B", "タクシーにのります。", "Takushī ni norimasu.", "I’ll take a taxi."),
    L("A", "ねむくてもべんきょうします。", "Nemuku te mo benkyō shimasu.", "Even if I’m sleepy I’ll study."),
    L("B", "がんばってください。", "Ganbatte kudasai.", "Do your best."),
    L("A", "きにいらなかったらかえします。", "Kiniiranakattara kaeshimasu.", "If I don’t like it I’ll return it."),
    L("B", "いいですね。", "Ii desu ne.", "That’s sensible."),
    L("A", "てすとがむずかしくてもがんばります。", "Tesuto ga muzukashiku te mo ganbarimasu.", "Even if the test is hard I’ll try."),
    L("B", "しんじています。", "Shinjite imasu.", "I believe in you."),
    L("A", "じかんがあったらコーヒーをのみましょう。", "Jikan ga attara kōhī o nomimashō.", "If we have time let’s have coffee."),
    L("B", "はい。", "Hai.", "Yes."),
    L("A", "おつかれさまでした。", "Otsukaresama deshita.", "Good work today."),
    L("B", "おつかれさまでした。", "Otsukaresama deshita.", "Good work."),
    L("A", "またね。", "Mata ne.", "See you."),
    L("B", "また。", "Mata.", "Bye."),
  ],
};

/** Sprint days 26–30: mixed review dialogues (no single Minna lesson). */
export const N5_SPRINT_PRACTICE_TAIL: Partial<Record<number, JapaneseDialogueLine[]>> = {
  26: [
    L("A", "きょうはぶんけいをふくしゅうします。", "Kyō wa bunkei o fukushū shimasu.", "Today we’ll review grammar patterns."),
    L("B", "「は」と「が」のちがいがまだよくわかりません。", "Wa to ga no chigai ga mada yoku wakarimasen.", "I still don’t clearly get the difference between は and が."),
    L("A", "ぜんたいのわだいには「は」。あたらしいじょうほうには「が」がよくでます。", "Zentai no wadai ni wa wa. Atarashii jōhō ni wa ga ga yoku demasu.", "は sets the overall topic; が often appears for new information."),
    L("B", "「を」はどうですか。", "O wa dō desu ka.", "How about を?"),
    L("A", "どうさのたいしょうです。", "Dōsa no taishō desu.", "It’s the target of an action."),
    L("B", "にとでは？", "Ni to de wa?", "How about に and で?"),
    L("A", "「に」はばしょやじかん。「で」はやりかたやどうぐです。", "Ni wa basho ya jikan. De wa yarikata ya dōgu desu.", "に marks place/time; で marks means or tools."),
    L("B", "もういちどれんしゅうします。", "Mō ichido renshū shimasu.", "I’ll practise again."),
    L("A", "いっしょにドリルをしましょう。", "Issho ni doriru o shimashō.", "Let’s do drills together."),
    L("B", "はい。", "Hai.", "OK."),
    L("A", "かのじょはがくせいです。にほんごがじょうずです。", "Kanojo wa gakusei desu. Nihongo ga jōzu desu.", "She’s a student. She’s good at Japanese."),
    L("B", "えいごは？", "Eigo wa?", "How about English?"),
    L("A", "えいごはすこしだけはなせます。", "Eigo wa sukoshi dake hanasemasu.", "She can speak only a little English."),
    L("B", "なるほど。", "Naruhodo.", "I see."),
    L("A", "テストでははやくえらぶことがじゅうようです。", "Tesuto de wa hayaku erabu koto ga jūyō desu.", "On the test, choosing quickly is important."),
    L("B", "きをつけます。", "Ki o tsukemasu.", "I’ll be careful."),
    L("A", "じゃあ、もういちど。", "Jā, mō ichido.", "Then once more."),
    L("B", "おねがいします。", "Onegaishimasu.", "Please."),
    L("A", "がんばりましょう。", "Ganbarimashō.", "Let’s do our best."),
    L("B", "はい。", "Hai.", "Yes."),
  ],
  27: [
    L("A", "ちょうかいではまえにキーワードをかきます。", "Chōkai de wa mae ni kīwādo o kakimasu.", "In listening I write keywords first."),
    L("B", "いいですね。", "Ii desu ne.", "Good idea."),
    L("A", "ききとれなかったらすぐえらびます。", "Kikitorenakattara sugu erabimasu.", "If I miss it I choose quickly."),
    L("B", "ペースがだいじですね。", "Pēsu ga daiji desu ne.", "Pace matters, doesn’t it."),
    L("A", "だいいちかいはぜんたいのイメージです。", "Dai ichi kai wa zentai no imēji desu.", "The first time is for the overall image."),
    L("B", "にかいめは？", "Ni kai me wa?", "The second time?"),
    L("A", "しょうさいをききます。", "Shōsai o kikimasu.", "I listen for details."),
    L("B", "わたしもやってみます。", "Watashi mo yatte mimasu.", "I’ll try that too."),
    L("A", "すうじとじかんをとくにききます。", "Sūji to jikan o toku ni kikimasu.", "I especially listen for numbers and times."),
    L("B", "たしかにでますね。", "Tashika ni demasu ne.", "They do come up a lot."),
    L("A", "まちがえてもつぎにすすみます。", "Machigete mo tsugi ni susumimasu.", "Even if I’m wrong I move on."),
    L("B", "それがだいじですね。", "Sore ga daiji desu ne.", "That’s what matters."),
    L("A", "れんしゅうでもじかんをはかりましょう。", "Renshū de mo jikan o hakarimashō.", "Let’s time ourselves in practice too."),
    L("B", "はい。", "Hai.", "OK."),
    L("A", "きょうはニュースをききます。", "Kyō wa nyūsu o kikimasu.", "Today we’ll listen to the news."),
    L("B", "はやいですね。", "Hayai desu ne.", "It’s fast, isn’t it."),
    L("A", "だかられいてんきゅうばいそくでききます。", "Dakara rei ten kyū-bai soku de kikimasu.", "So I listen at 0.9× speed."),
    L("B", "なるほど。", "Naruhodo.", "I see."),
    L("A", "がんばりましょう。", "Ganbarimashō.", "Let’s do our best."),
    L("B", "はい。", "Hai.", "Yes."),
  ],
  28: [
    L("A", "きょうはかんじのスピードれんしゅうです。", "Kyō wa kanji no supīdo renshū desu.", "Today is kanji speed practice."),
    L("B", "よみかたをおぼえます。", "Yomikata o oboemasu.", "I’ll memorize readings."),
    L("A", "かいてからよみます。", "Kaite kara yomimasu.", "After writing I read aloud."),
    L("B", "いいですね。", "Ii desu ne.", "Nice."),
    L("A", "おなじぶんをさんかいかきます。", "Onaji bun o sankai kakimasu.", "I write the same sentence three times."),
    L("B", "かきじゅんもおぼえますね。", "Kakijun mo oboemasu ne.", "You memorize stroke order too."),
    L("A", "まちがえたらすぐなおします。", "Machigaetara sugu naoshimasu.", "If I make a mistake I fix it right away."),
    L("B", "きをつけます。", "Ki o tsukemasu.", "I’ll be careful."),
    L("A", "じかんをはかってかきます。", "Jikan o hakatte kakimasu.", "I write while timing myself."),
    L("B", "はやくなりますか。", "Hayaku narimasu ka.", "Do you get faster?"),
    L("A", "はい、だんだんはやくなります。", "Hai, dan dan hayaku narimasu.", "Yes, gradually I get faster."),
    L("B", "すごいですね。", "Sugoi desu ne.", "Amazing."),
    L("A", "たんごカードもつかいます。", "Tango kādo mo tsukaimasu.", "I use vocabulary cards too."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "まいにちじゅうぷんだけでもいいです。", "Mainichi juppun dake demo ii desu.", "Even just ten minutes every day is fine."),
    L("B", "つづけることがだいじですね。", "Tsuzukeru koto ga daiji desu ne.", "Continuing is what matters."),
    L("A", "そうですね。", "Sō desu ne.", "That’s right."),
    L("B", "がんばります。", "Ganbarimasu.", "I’ll try."),
    L("A", "いっしょにがんばりましょう。", "Issho ni ganbarimashō.", "Let’s do our best together."),
    L("B", "はい。", "Hai.", "OK."),
  ],
  29: [
    L("A", "ぶんしょうでは「は」がしゅだいになることがおおいです。", "Bunshō de wa wa shudai ni naru koto ga ōi desu.", "In passages は often marks the main theme."),
    L("B", "「が」はどうですか。", "Ga wa dō desu ka.", "How about が?"),
    L("A", "ぶんによります。", "Bun ni yorimasu.", "It depends on the sentence."),
    L("B", "よみながら「は」をさがします。", "Yominagara wa o sagashimasu.", "While reading I look for は."),
    L("A", "しつもんのこたえはたいていぶんのおわりです。", "Shitsumon no kotae wa taitei bun no owari desu.", "The answer to the question is usually at the end of the sentence."),
    L("B", "なるほど。", "Naruhodo.", "I see."),
    L("A", "れんしゅうではマークをつけます。", "Renshū de wa māku o tsukemasu.", "In practice I mark particles."),
    L("B", "いいほうほうですね。", "Ii hōhō desu ne.", "That’s a good method."),
    L("A", "ばしょを「に」でしめすぶんもあります。", "Basho o ni de shimesu bun mo arimasu.", "Some sentences mark place with に."),
    L("B", "くらべます。", "Kurabemasu.", "I’ll compare."),
    L("A", "じかんがないときはあとでかえります。", "Jikan ga nai toki wa atode kaerimasu.", "When there’s no time I come back later."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "もういちどよみます。", "Mō ichido yomimasu.", "I read one more time."),
    L("B", "はい。", "Hai.", "OK."),
    L("A", "テストではゆっくりよみます。", "Tesuto de wa yukkuri yomimasu.", "On the test I read slowly."),
    L("B", "きをつけます。", "Ki o tsukemasu.", "I’ll be careful."),
    L("A", "がんばりましょう。", "Ganbarimashō.", "Let’s do our best."),
    L("B", "はい。", "Hai.", "Yes."),
    L("A", "ありがとう。", "Arigatō.", "Thanks."),
    L("B", "どういたしまして。", "Dō itashimashite.", "You’re welcome."),
  ],
  30: [
    L("A", "あしたはもぎテストです。", "Ashita wa mogi tesuto desu.", "Tomorrow is a mock exam."),
    L("B", "きんちょうします。", "Kinchō shimasu.", "I’m nervous."),
    L("A", "しっぱいしてもべんきょうはつづきます。", "Shippai shite mo benkyō wa tsuzukimasu.", "Even if you fail, studying continues."),
    L("B", "そうですね。", "Sō desu ne.", "That’s true."),
    L("A", "まずはねるじかんをたもちます。", "Mazu wa neru jikan o tamochimasu.", "First I’ll keep sleep time."),
    L("B", "いいですね。", "Ii desu ne.", "Good."),
    L("A", "あさごはんをたべます。", "Asagohan o tabemasu.", "I’ll eat breakfast."),
    L("B", "わたしもです。", "Watashi mo desu.", "Me too."),
    L("A", "じしょととけいをもっていきます。", "Jisho to tokei o motte ikimasu.", "I’ll bring a dictionary and a watch."),
    L("B", "きをつけてください。", "Ki o tsukete kudasai.", "Take care."),
    L("A", "しけんではさわらないでください。", "Shiken de wa sawaranaide kudasai.", "During the exam please don’t touch (your phone)."),
    L("B", "はい。", "Hai.", "OK."),
    L("A", "おわったらかんしゃします。", "Owattara kansha shimasu.", "When it’s over I’ll feel grateful."),
    L("B", "いいきもちですね。", "Ii kimochi desu ne.", "That’s a good mindset."),
    L("A", "いままでありがとう。", "Ima made arigatō.", "Thanks for everything so far."),
    L("B", "こちらこそ。", "Kochira koso.", "Same here."),
    L("A", "じゃあ、がんばりましょう。", "Jā, ganbarimashō.", "Let’s do our best."),
    L("B", "はい。", "Hai.", "Yes."),
    L("A", "またね。", "Mata ne.", "See you."),
    L("B", "また。", "Mata.", "Bye."),
  ],
};
