import type { ReactModuleOutline } from "@/lib/react-learning/react-curriculum-types";

/**
 * React learning outline (topics and video lengths) for the Programming hub.
 * Use as a syllabus checklist alongside your course videos.
 */
export const REACT_PROGRAMMING_OUTLINE: ReactModuleOutline[] = [
  {
    id: "getting-started",
    title: "Getting Started",
    sectionDuration: "3m",
    lessons: [
      { title: "Welcome" },
      { title: "Prerequisites" },
      { title: "Source Code" },
      { title: "Questions and Support" },
      { title: "Connect with Me" },
    ],
  },
  {
    id: "getting-started-react",
    title: "Getting Started with React",
    sectionDuration: "18m",
    lessons: [
      { title: "What is React" },
      { title: "Setting Up the Development Environment" },
      { title: "Creating a React App" },
      { title: "Project Structure" },
      { title: "Creating a React Component" },
      { title: "How React Works" },
      { title: "React Ecosystem" },
      { title: "Summary" },
      { title: "Side Note: My VSCode Theme" },
    ],
  },
  {
    id: "building-components",
    title: "Building Components",
    sectionDuration: "58m",
    lessons: [
      { title: "Introduction", duration: "0m 35s" },
      { title: "Creating a ListGroup Component", duration: "5m 36s" },
      { title: "Fragments", duration: "2m 28s" },
      { title: "Rendering Lists", duration: "3m 30s" },
      { title: "Conditional Rendering", duration: "5m 25s" },
      { title: "Handling Events", duration: "6m 07s" },
      { title: "Managing State", duration: "6m 03s" },
      { title: "Passing Data via Props", duration: "3m 58s" },
      { title: "Passing Functions via Props", duration: "3m 46s" },
      { title: "State vs Props", duration: "1m 33s" },
      { title: "Passing Children", duration: "5m 05s" },
      { title: "Inspecting Components with React Dev Tools", duration: "2m 10s" },
      { title: "Exercise- Building a Button Component", duration: "7m 02s" },
      { title: "Exercise- Showing an Alert", duration: "5m 02s" },
      { title: "Summary" },
    ],
  },
  {
    id: "styling-components",
    title: "Styling Components",
    sectionDuration: "32m",
    lessons: [
      { title: "Introduction", duration: "0m 26s" },
      { title: "Vanilla CSS", duration: "4m 11s" },
      { title: "CSS Modules", duration: "3m 45s" },
      { title: "CSS-in-JS", duration: "7m 51s" },
      { title: "Separation of Concerns", duration: "2m 30s" },
      { title: "Inline Styles", duration: "1m 02s" },
      { title: "Popular UI Libraries", duration: "2m 03s" },
      { title: "Adding Icons", duration: "1m 52s" },
      { title: "Exercise- Using CSS Modules", duration: "3m 00s" },
      { title: "Building a Like Component", duration: "5m 19s" },
      { title: "Summary" },
    ],
  },
  {
    id: "managing-state",
    title: "Managing Component State",
    sectionDuration: "41m",
    lessons: [
      { title: "Introduction", duration: "0m 25s" },
      { title: "Understanding the State Hook", duration: "4m 28s" },
      { title: "Choosing the State Structure", duration: "2m 56s" },
      { title: "Keeping Components Pure", duration: "2m 03s" },
      { title: "Understanding the Strict Mode", duration: "2m 42s" },
      { title: "Updating Objects", duration: "2m 21s" },
      { title: "Updating Nested Objects", duration: "2m 15s" },
      { title: "Updating Arrays", duration: "1m 49s" },
      { title: "Updating Array of Objects", duration: "1m 46s" },
      { title: "Simplifying Update Logic with Immer", duration: "2m 56s" },
      { title: "Sharing State between Components", duration: "6m 22s" },
      { title: "Exercise- Updating State", duration: "4m 49s" },
      { title: "Exercise- Building an ExpandableText Component", duration: "6m 22s" },
      { title: "Summary" },
    ],
  },
  {
    id: "building-forms",
    title: "Building Forms",
    sectionDuration: "1h",
    lessons: [
      { title: "Introduction", duration: "0m 24s" },
      { title: "Building a Form", duration: "3m 45s" },
      { title: "Handling Form Submission", duration: "2m 23s" },
      { title: "Accessing Input Fields", duration: "5m 46s" },
      { title: "Controlled Components", duration: "4m 33s" },
      { title: "Managing Forms with React Hook Form", duration: "4m 33s" },
      { title: "Applying Validation", duration: "5m 38s" },
      { title: "Schema based Validation with Zod", duration: "7m 33s" },
      { title: "Disabling the Submit Button", duration: "0m 45s" },
      { title: "Project- Expense Tracker", duration: "1m 23s" },
      { title: "Building ExpenseList", duration: "10m 28s" },
      { title: "Building ExpenseFilter", duration: "5m 51s" },
      { title: "Building the Expense Form", duration: "4m 36s" },
      { title: "Integrating with React Hook Form and Zod", duration: "9m 54s" },
      { title: "Adding an Expense", duration: "3m 35s" },
      { title: "Summary" },
      { title: "A Quick Note" },
    ],
  },
  {
    id: "connecting-backend",
    title: "Connecting to the Backend",
    sectionDuration: "1h",
    lessons: [
      { title: "Introduction", duration: "0m 53s" },
      { title: "Understanding the Effect Hook", duration: "3m 50s" },
      { title: "Effect Dependencies", duration: "8m 34s" },
      { title: "Effect Clean Up", duration: "2m 30s" },
      { title: "Fetching Data", duration: "5m 32s" },
      { title: "Understanding HTTP Requests", duration: "3m 02s" },
      { title: "Handling Errors", duration: "2m 03s" },
      { title: "Working with Async and Await", duration: "4m 21s" },
      { title: "Cancelling a Fetch Request", duration: "2m 27s" },
      { title: "Showing a Loading Indicator", duration: "3m 02s" },
      { title: "Deleting Data", duration: "5m 50s" },
      { title: "Creating Data", duration: "5m 09s" },
      { title: "Updating Data", duration: "5m 25s" },
      { title: "Extracting a Reusable API Client", duration: "3m 55s" },
      { title: "Extracting the User Service", duration: "8m 22s" },
      { title: "Creating a Generic HTTP Service", duration: "8m 00s" },
      { title: "Creating a Custom Data Fetching Hook", duration: "3m 53s" },
      { title: "Summary" },
    ],
  },
  {
    id: "project-game-discovery",
    title: "Project: Building a Video Game Discovery App",
    sectionDuration: "3h",
    lessons: [
      { title: "What We'll Build", duration: "1m 23s" },
      { title: "Source Code" },
      { title: "Up for a Challenge?" },
      { title: "Setting Up the Project", duration: "1m 31s" },
      { title: "Installing Chakra UI", duration: "5m 00s" },
      { title: "Creating a Responsive Layout", duration: "4m 53s" },
      { title: "Building the Navigation Bar", duration: "3m 58s" },
      { title: "Implementing the Dark Mode", duration: "2m 44s" },
      { title: "Building the Color Mode Switch", duration: "3m 36s" },
      { title: "Fetching the Games", duration: "8m 19s" },
      { title: "Creating a Custom Hook for Fetching Games", duration: "4m 59s" },
      { title: "Building Game Cards", duration: "6m 08s" },
      { title: "Displaying Platform Icons", duration: "13m 42s" },
      { title: "Displaying Critic Score", duration: "4m 20s" },
      { title: "Getting Optimized Images", duration: "3m 56s" },
      { title: "Improving User Experience with Loading Skeletons", duration: "5m 37s" },
      { title: "Refactor- Removing Duplicated Styles", duration: "2m 34s" },
      { title: "Fetching the Genres", duration: "4m 31s" },
      { title: "Creating a Generic Data Fetching Hook", duration: "6m 42s" },
      { title: "Displaying the Genres", duration: "8m 52s" },
      { title: "Showing a Spinner", duration: "1m 27s" },
      { title: "Filtering Games by Genre", duration: "12m 33s" },
      { title: "Highlighting the Selected Genre", duration: "1m 43s" },
      { title: "Building Platform Selector", duration: "4m 30s" },
      { title: "Filtering Games by Platform", duration: "6m 15s" },
      { title: "Refactoring- Extracting a Query Object", duration: "5m 11s" },
      { title: "Building Sort Selector", duration: "2m 59s" },
      { title: "Sorting Games", duration: "8m 10s" },
      { title: "Handling Games without an Image", duration: "1m 07s" },
      { title: "Fixing the Issue with Chakra Menus", duration: "1m 28s" },
      { title: "Building Search Input", duration: "2m 38s" },
      { title: "Searching Games", duration: "6m 05s" },
      { title: "Adding a Dynamic Heading", duration: "4m 38s" },
      { title: "Cleaning Up the Genres", duration: "2m 20s" },
      { title: "Cleaning Up the Game Cards", duration: "1m 23s" },
      { title: "Adding Emojis", duration: "5m 35s" },
      { title: "Shipping Static Data", duration: "3m 16s" },
      { title: "Customizing the Chakra Theme", duration: "2m 57s" },
      { title: "Refactoring Game Grid", duration: "0m 56s" },
      { title: "Building for Production", duration: "2m 49s" },
      { title: "Deploying to Vercel", duration: "4m 42s" },
    ],
  },
];

export function reactCurriculumLessonCount(modules: ReactModuleOutline[]): number {
  return modules.reduce((n, m) => n + m.lessons.length, 0);
}
