import type { QAFlashcardItem } from "@/lib/qa-flashcards-types";

export const LOKSEWA_ETHNIC_GROUPS_QA: QAFlashcardItem[] = [
  {
    id: 1,
    questionEn: "Which is considered the oldest indigenous ethnic group of Nepal?",
    questionNe: "नेपालको आदिवासी चरित्रको सबैभन्दा पुरानो जाति कसलाई मानिन्छ?",
    answerEn: "Raute",
    answerNe: "राउटे",
  },
  {
    id: 2,
    questionEn: "Which ethnic group believes that touching money is sinful?",
    questionNe: "पैसा छुँदा पाप लाग्छ भन्ने विश्वास कुन जातिमा रहेको छ?",
    answerEn: "Raute",
    answerNe: "राउटे",
  },
  {
    id: 3,
    questionEn: "Chandi Puja is a festival of which ethnic group?",
    questionNe: "चण्डी पूजा कुन जातिको पर्व हो?",
    answerEn: "Rai",
    answerNe: "राई",
  },
  {
    id: 4,
    questionEn: "In which group's wedding is a black umbrella carried with the groom considered mandatory?",
    questionNe: "कुन जातिको विवाहमा दुलहाको साथ कालो छाता अनिवार्य मानिन्छ?",
    answerEn: "Rai",
    answerNe: "राई",
  },
  {
    id: 5,
    questionEn: "Where do the Meche people live?",
    questionNe: "मेचे जातिहरूको बसोबास कहाँ रहेको छ?",
    answerEn: "Jhapa",
    answerNe: "झापा",
  },
  {
    id: 6,
    questionEn: "Which ethnic group worships the siudi plant as a clan deity?",
    questionNe: "सिउडीको बोटलाई कुलदेवताको रूपमा पूजा गर्ने जाति कुन हो?",
    answerEn: "Meche",
    answerNe: "मेचे",
  },
  {
    id: 7,
    questionEn: "What is the clan deity of the Musahar called?",
    questionNe: "मुसहरको कुलदेवतालाई के भनिन्छ?",
    answerEn: "Dinabhadri",
    answerNe: "दिनाभद्री",
  },
  {
    id: 8,
    questionEn: "What is the black garment covering Muslim women from head to foot called?",
    questionNe: "मुस्लिम महिलाहरूले शिरदेखि पाउसम्म छोपिने गरी लगाउने कालो कपडालाई के भनिन्छ?",
    answerEn: "Burqa",
    answerNe: "बुर्का",
  },
  {
    id: 9,
    questionEn: "Where do the Munda people live?",
    questionNe: "मुण्डा जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Jhapa",
    answerNe: "झापा",
  },
  {
    id: 10,
    questionEn: "Where do the Mugali people live?",
    questionNe: "मुगाली जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Mugu",
    answerNe: "मुगु",
  },
  {
    id: 11,
    questionEn: "Where do the Marphali people live?",
    questionNe: "मार्फाली जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Mustang (between Tukuche and Kagbeni)",
    answerNe: "मुस्ताङ (टुकुचे र कागबेनीको बिचमा)",
  },
  {
    id: 12,
    questionEn: "Terimin is a festival of which ethnic group?",
    questionNe: "तेरिमिन कुन जातिको चाड हो?",
    answerEn: "Marphali",
    answerNe: "मार्फाली",
  },
  {
    id: 13,
    questionEn: "Gangaur Puja is associated with which community?",
    questionNe: "गणगौर पूजा कुन जातिसँग सम्बन्धित छ?",
    answerEn: "Marwari",
    answerNe: "मारवाडी",
  },
  {
    id: 14,
    questionEn: "In which community is it customary to give one rupee and a small container at the first viewing of a newborn?",
    questionNe: "बच्चा जन्मिएपछि अनुहार हेर्दा एक रुपैयाँ र एक ढक्की दिने चलन कुन जातिमा रहेको छ?",
    answerEn: "Marwari",
    answerNe: "मारवाडी",
  },
  {
    id: 15,
    questionEn: "In which community is a donkey worshipped before the groom departs for the wedding?",
    questionNe: "विवाहमा दुलहा अन्माउनु अघि गधाको पूजा गर्ने चलन कुन जातिमा रहेको छ?",
    answerEn: "Marwari",
    answerNe: "मारवाडी",
  },
  {
    id: 16,
    questionEn: "What is the clan deity of the Majhi called?",
    questionNe: "माझीहरूको कुलदेवतालाई के भनिन्छ?",
    answerEn: "Bhimsen",
    answerNe: "भीमसेन",
  },
  {
    id: 17,
    questionEn: "Who is the greatest deity of the Majhi people?",
    questionNe: "माझी जातिको सबैभन्दा ठुलो देवता कुन हुन्?",
    answerEn: "Bhimsen",
    answerNe: "भीमसेन",
  },
  {
    id: 18,
    questionEn: "In which group is the deceased's cot placed upturned over the grave?",
    questionNe: "मृतकको चिहानमाथि मृतकको खटिया उत्तानो पारेर राख्ने चलन कुन जातिमा छ?",
    answerEn: "Majhi",
    answerNe: "माझी",
  },
  {
    id: 19,
    questionEn: "Which Nepali ethnic group is thought to be closely related to the Magyars of Hungary?",
    questionNe: "हंगेरीका आदिवासी मग्यारसँग नजिकको सम्बन्ध रहेको मानिने नेपालको जाति कुन हो?",
    answerEn: "Magar",
    answerNe: "मगर",
  },
  {
    id: 20,
    questionEn: "What is a Magar priest called?",
    questionNe: "मगरको पुरोहितलाई के भनिन्छ?",
    answerEn: "Bhusal",
    answerNe: "भुसाल",
  },
  {
    id: 21,
    questionEn: "What is the region inhabited by the Magar called?",
    questionNe: "मगरहरूको बसोबास रहेको क्षेत्रलाई के भनिन्छ?",
    answerEn: "Magarat",
    answerNe: "मगरात",
  },
  {
    id: 22,
    questionEn: "What is the region inhabited by the Bhote called?",
    questionNe: "भोटे जातिहरू बसोबास गरेको क्षेत्रलाई के भनिन्छ?",
    answerEn: "Jadan",
    answerNe: "जडान",
  },
  {
    id: 23,
    questionEn: "What is the region inhabited by the Bantar called?",
    questionNe: "बाँतर जातिहरू बसोबास गर्ने क्षेत्रलाई के भनिन्छ?",
    answerEn: "Dihiwar",
    answerNe: "डिहिवार",
  },
  {
    id: 24,
    questionEn: "In which group is forgiveness sought from the bride's parents after an elopement?",
    questionNe: "केटी भगाएपछि केटीको बाबुआमासँग माफी माग्ने चलन कुन जातिमा रहेको छ?",
    answerEn: "Bahra Gaunle",
    answerNe: "बाह्र गाउँले",
  },
  {
    id: 25,
    questionEn: "Where do the Bahra Gaunle people live?",
    questionNe: "बाह्र गाउँले जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Mustang",
    answerNe: "मुस्ताङ",
  },
  {
    id: 26,
    questionEn: "Which ethnic group worships the wind god as its clan deity?",
    questionNe: "कुलदेवताको रूपमा वायु देवताको पूजा गर्ने जाति कुन हो?",
    answerEn: "Baram",
    answerNe: "बराम",
  },
  {
    id: 27,
    questionEn: "What is the language spoken by the Baram people called?",
    questionNe: "बराम जातिले बोल्ने भाषालाई के भनिन्छ?",
    answerEn: "Baram",
    answerNe: "बराम",
  },
  {
    id: 28,
    questionEn: "In which group is marriage by abduction of the bride practised?",
    questionNe: "केटीको अपहरण गरेर विवाह गर्ने चलन कुन जातिमा रहेको छ?",
    answerEn: "Punel",
    answerNe: "पुनेल",
  },
  {
    id: 29,
    questionEn: "Where do the Pahari people live?",
    questionNe: "पहरी जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Kavrepalanchok",
    answerNe: "काभ्रेपलाञ्चोक",
  },
  {
    id: 30,
    questionEn: "Which ethnic group considers soybeans and ginger sacred?",
    questionNe: "भटमास र अदुवालाई पवित्र मान्ने जाति कुन हो?",
    answerEn: "Pahari",
    answerNe: "पहरी",
  },
  {
    id: 31,
    questionEn: "What is the gold head ornament worn by Newar women called?",
    questionNe: "नेवार महिलाहरूले टाउकोमा लगाउने सुनको गहनालाई के भनिन्छ?",
    answerEn: "Bulin",
    answerNe: "बुलिन",
  },
  {
    id: 32,
    questionEn: "What do the Newar people call Gosaikunda?",
    questionNe: "नेवार जातिले गोसाइँकुण्डलाई के भन्दछन्?",
    answerEn: "Shilutirtha",
    answerNe: "शिलुतिर्थ",
  },
  {
    id: 33,
    questionEn: "What is the script of the Newar language called?",
    questionNe: "नेवार भाषाको लिपिलाई के भनिन्छ?",
    answerEn: "Ranjana script",
    answerNe: "रञ्जना लिपि",
  },
  {
    id: 34,
    questionEn: "Which group is known as the Limbu or Kirat of the Madhesh?",
    questionNe: "मधेशका लिम्बु वा मधेशका किराँत भनेर चिनिने जाति कुन हो?",
    answerEn: "Dhimal",
    answerNe: "धिमाल",
  },
  {
    id: 35,
    questionEn: "In which ethnic group is the betel-nut marriage custom practised?",
    questionNe: "सुपारी विवाहको चलन कुन जातिमा रहेको छ?",
    answerEn: "Dhimal",
    answerNe: "धिमाल",
  },
  {
    id: 36,
    questionEn: "Which group measures the couple's height with a stick before marriage and considers equal height most auspicious?",
    questionNe: "विवाहपूर्व केटाकेटीको उचाइ लौरोले नापी बराबर भएमा विवाहको लागि सर्वोत्तम ठान्ने जाति कुन हो?",
    answerEn: "Dhanuk",
    answerNe: "धानुक",
  },
  {
    id: 37,
    questionEn: "Where do the Dhanuk people live?",
    questionNe: "धानुक जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "The Terai region",
    answerNe: "तराई क्षेत्रमा",
  },
  {
    id: 38,
    questionEn: "Which ethnic group is known for preferring rice cultivation?",
    questionNe: "धानको खेती गर्न रुचाउने जाति भन्नाले कुन जातिलाई चिनिन्छ?",
    answerEn: "Dhanuk",
    answerNe: "धानुक",
  },
  {
    id: 39,
    questionEn: "Which group performs the Bhangeri Puja by sacrificing a female goat?",
    questionNe: "पाठीको बलि दिएर भंगेरी पूजा गर्ने जाति कुन हो?",
    answerEn: "Dura",
    answerNe: "दुरा",
  },
  {
    id: 40,
    questionEn: "In which group is the old fire extinguished and a new one lit on New Year's day?",
    questionNe: "नयाँ वर्षको दिन पुरानो आगो निभाई नयाँ आगो बाल्ने चलन कुन जातिमा रहेको छ?",
    answerEn: "Darai",
    answerNe: "दराई",
  },
  {
    id: 41,
    questionEn: "Chudka is a popular song of which ethnic group?",
    questionNe: "चुड्का कुन जातिको लोकप्रिय गीत हो?",
    answerEn: "Darai",
    answerNe: "दराई",
  },
  {
    id: 42,
    questionEn: "What is the tutelary deity of the Danuwar called?",
    questionNe: "दनुवार जातिको इष्टदेवतालाई के भनिन्छ?",
    answerEn: "Sahles",
    answerNe: "सहलेस",
  },
  {
    id: 43,
    questionEn: "The Sahles dance is associated with which ethnic group?",
    questionNe: "सहलेस नाच कुन जातिसँग सम्बन्धित छ?",
    answerEn: "Danuwar",
    answerNe: "दनुवार",
  },
  {
    id: 44,
    questionEn: "What is the region inhabited by the Tharu called?",
    questionNe: "थारूहरू बसोबास गर्ने क्षेत्रलाई के भनिन्छ?",
    answerEn: "Tharuwan",
    answerNe: "थारुवान",
  },
  {
    id: 45,
    questionEn: "What are the Tharu of Dang district called?",
    questionNe: "दाङ जिल्लामा बसोबास गर्ने थारूलाई के भनिन्छ?",
    answerEn: "Dagaura Tharu",
    answerNe: "डगौरा थारू",
  },
  {
    id: 46,
    questionEn: "The Maharwa dance is associated with which ethnic group?",
    questionNe: "महर्वा नृत्य कुन जातिसँग सम्बन्धित छ?",
    answerEn: "Tharu",
    answerNe: "थारू",
  },
  {
    id: 47,
    questionEn: "What is the custom of a live-in son-in-law called among the Tharu?",
    questionNe: "थारू समुदायमा घरज्वाइँ बस्ने चलनलाई के भनिन्छ?",
    answerEn: "Bhwarpaithana",
    answerNe: "भ्वाँरपैठना",
  },
  {
    id: 48,
    questionEn: "Which ethnic group is known for holding on to its property rather than giving it away?",
    questionNe: "आफ्नो सम्पत्ति अरूलाई नदिई थामी राख्ने जाति भन्नाले कुन जातिलाई चिनिन्छ?",
    answerEn: "Thami",
    answerNe: "थामी",
  },
  {
    id: 49,
    questionEn: "In which month is the Toranlha festival celebrated?",
    questionNe: "तोरनल्ह पर्व कुन महिनामा मनाइन्छ?",
    answerEn: "Falgun",
    answerNe: "फागुन",
  },
  {
    id: 50,
    questionEn: "Which festival do the Thakali celebrate on Fagu Purnima?",
    questionNe: "थकाली जातिहरूले फागुपूर्णिमामा मनाउने चाड कुन हो?",
    answerEn: "Toranlha",
    answerNe: "तोरनल्ह",
  },
  {
    id: 51,
    questionEn: "Where do the Teen Gaunle people live?",
    questionNe: "तीन गाउँले जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Three villages of Mustang — Syang, Chimang and Thini",
    answerNe: "मुस्ताङका तीन गाउँ — स्याङ, चिमाङ र थिनिमा",
  },
  {
    id: 52,
    questionEn: "Bhoteselo is associated with which ethnic group?",
    questionNe: "भोटेसेलो कुन जातिसँग सम्बन्धित छ?",
    answerEn: "Tamang",
    answerNe: "तामाङ",
  },
  {
    id: 53,
    questionEn: "The Saraswati dance is associated with which ethnic group?",
    questionNe: "सरस्वती नाच कुन जातिसँग सम्बन्धित छ?",
    answerEn: "Tamang",
    answerNe: "तामाङ",
  },
  {
    id: 54,
    questionEn: "In which group are 108 lamps lit during funeral rites?",
    questionNe: "मृत्यु संस्कार गर्दा १०८ बत्ती बाल्ने चलन कुन जातिमा रहेको छ?",
    answerEn: "Tamang",
    answerNe: "तामाङ",
  },
  {
    id: 55,
    questionEn: "In which group is the Ghewa performed as a funeral rite?",
    questionNe: "मृत्यु संस्कारमा घेवा गर्ने चलन कुन जातिमा रहेको छ?",
    answerEn: "Tamang",
    answerNe: "तामाङ",
  },
  {
    id: 56,
    questionEn: "What is the lighting of 108 lamps during the Tamang Ghewa called?",
    questionNe: "तामाङ जातिले मृत्यु संस्कारमा घेवा गर्दा १०८ बत्ती बाल्ने कार्यलाई के भनिन्छ?",
    answerEn: "Gyamja",
    answerNe: "ग्याम्जा",
  },
  {
    id: 57,
    questionEn: "Where do the Tapkegola people live?",
    questionNe: "ताप्केगोला जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Taplejung",
    answerNe: "ताप्लेजुङ",
  },
  {
    id: 58,
    questionEn: "Where do the Tangbe people live?",
    questionNe: "ताङ्वे जातिको बसोबास कहाँ रहेको छ?",
    answerEn: "Mustang",
    answerNe: "मुस्ताङ",
  },
  {
    id: 59,
    questionEn: "In which group is the corpse cut and fed to vultures?",
    questionNe: "मरेको लास काटेर गिद्धलाई खुवाउने चलन कुन जातिमा रहेको छ?",
    answerEn: "Dolpo",
    answerNe: "डोल्पो",
  },
  {
    id: 60,
    questionEn: "What form of marriage is practised among the Dolpo?",
    questionNe: "डोल्पो जातिमा कस्तो विवाह प्रथा रहेको छ?",
    answerEn: "Polyandry",
    answerNe: "बहुपति",
  },
  {
    id: 61,
    questionEn: "Which ethnic group rings its bell held upturned?",
    questionNe: "घण्टी बजाउँदा उत्तानो परेर बजाउने जाति कुन हो?",
    answerEn: "Dolpo",
    answerNe: "डोल्पो",
  },
  {
    id: 62,
    questionEn: "In which group do bride and groom exchange vermilion at the wedding?",
    questionNe: "विवाहमा सिन्दुर साटासाट गर्ने चलन कुन जातिमा रहेको छ?",
    answerEn: "Jhangad",
    answerNe: "झाँगड",
  },
  {
    id: 63,
    questionEn: "What is the person who settles disputes among the Jhangad called?",
    questionNe: "झाँगड जातिहरूमा झगडा मिलाउने व्यक्तिलाई के भनिन्छ?",
    answerEn: "Bhaijyan",
    answerNe: "भाईज्यान",
  },
  {
    id: 64,
    questionEn: "Which ethnic group is known as the Praja?",
    questionNe: "प्रजा जाति भन्नाले कुन जातिलाई चिनिन्छ?",
    answerEn: "Chepang",
    answerNe: "चेपाङ",
  },
  {
    id: 65,
    questionEn: "By what other name are the Chepang known?",
    questionNe: "चेपाङ जातिलाई अर्को के नामले चिनिन्छ?",
    answerEn: "Praja",
    answerNe: "प्रजा",
  },
  {
    id: 66,
    questionEn: "Which ethnic group goes to ask for a bride on a Tuesday?",
    questionNe: "केटी माग्न जाँदा मंगलबार पारेर जाने जाति कुन हो?",
    answerEn: "Chepang",
    answerNe: "चेपाङ",
  },
];
