import type { QAFlashcardItem } from "@/lib/qa-flashcards-types";

export const LOKSEWA_GEOGRAPHY_QA: QAFlashcardItem[] = [
  {
    id: 1,
    questionEn: "Which is the most explored/observed natural satellite?",
    questionNe: "सबैभन्दा बढी खोज गरिएको उपग्रह कुन हो?",
    answerEn: "The Moon",
    answerNe: "चन्द्रमा",
  },
  {
    id: 2,
    questionEn: "Which was the first spacecraft to reach the Moon's surface?",
    questionNe: "चन्द्र धरातलमा पुग्ने पहिलो अन्तरिक्ष यान कुन हो?",
    answerEn: "Luna 2",
    answerNe: "लुना २",
  },
  {
    id: 3,
    questionEn: "In which year did Luna 2 reach the Moon?",
    questionNe: "लुना २ चन्द्रमामा कुन सालमा पुग्यो?",
    answerEn: "In 1959",
    answerNe: "सन् १९५९",
  },
  {
    id: 4,
    questionEn: "Who was the first person to walk/step on the Moon's surface?",
    questionNe: "चन्द्रमाको धरातलमा पाइला टेक्ने पहिलो व्यक्ति को हुन्?",
    answerEn: "Neil Armstrong",
    answerNe: "निल आर्मस्ट्रङ",
  },
  {
    id: 5,
    questionEn: "Which country was Neil Armstrong from?",
    questionNe: "निल आर्मस्ट्रङ कुन देशका हुन्?",
    answerEn: "America (USA)",
    answerNe: "अमेरिकाका",
  },
  {
    id: 6,
    questionEn: "How many astronauts went on the first crewed Moon mission (Apollo 11)?",
    questionNe: "पहिलो मानवसहित चन्द्र अभियान (एपोलो ११) मा कति जना गएका थिए?",
    answerEn: "3 people",
    answerNe: "३ जना",
  },
  {
    id: 7,
    questionEn: "Who were the three astronauts on the Apollo 11 mission?",
    questionNe: "एपोलो ११ अभियानमा गएका तीन जना अन्तरिक्षयात्री को को थिए?",
    answerEn: "Neil Armstrong, Edwin Aldrin, Michael Collins (Collins did not descend to the lunar surface)",
    answerNe: "निल आर्मस्ट्रङ, एडविन एल्ड्रिन, माइकल कोलिन्स (कोलिन्स चन्द्र धरातलमा ओर्लेनन्)",
  },
  {
    id: 8,
    questionEn: "On what date did humans first land on the Moon?",
    questionNe: "मानिस पहिलो पटक चन्द्रमामा कहिले पुगे?",
    answerEn: "On 21 July 1969",
    answerNe: "सन् १९६९ जुलाई २१ मा",
  },
  {
    id: 9,
    questionEn: "Which spacecraft carried the first humans to the Moon?",
    questionNe: "पहिलो पटक मानिसलाई चन्द्रमामा कुन यानले पुर्‍यायो?",
    answerEn: "\"Apollo 11\"",
    answerNe: "\"एपोलो ११\"",
  },
  {
    id: 10,
    questionEn: "Where is the \"Sea of Tranquility\" located?",
    questionNe: "\"Sea of Tranquility\" कहाँ पर्छ?",
    answerEn: "On the Moon (the site where Apollo 11 landed)",
    answerNe: "चन्द्रमामा (एपोलो ११ उत्रेको ठाउँ)",
  },
  {
    id: 11,
    questionEn: "What is a \"nanosecond\"?",
    questionNe: "\"Nano Second\" के हो?",
    answerEn: "A unit for measuring time (1 nanosecond = one-billionth of a second)",
    answerNe: "समय नाप्ने एकाई (1 नानो सेकेन्ड = सेकेन्डको एक अर्बौँ भाग)",
  },
  {
    id: 12,
    questionEn: "Who announced the Apollo Moon-landing mission?",
    questionNe: "एपोलो अभियानको घोषणा कसले गरे?",
    answerEn: "American President John F. Kennedy",
    answerNe: "अमेरिकी राष्ट्रपति जोन एफ. केनेडीले",
  },
  {
    id: 13,
    questionEn: "What is meant by a \"satellite\"?",
    questionNe: "उपग्रह भन्नाले के बुझिन्छ?",
    answerEn: "Bodies that revolve around planets (satellites also revolve around the Sun along with their planet)",
    answerNe: "ग्रहहरुको परिक्रमा गर्ने पिण्डहरु (उपग्रहहरुले ग्रहको साथसाथै सूर्यको पनि परिक्रमा गर्दछन्)",
  },
  {
    id: 14,
    questionEn: "How many types of satellites are there?",
    questionNe: "उपग्रह कति किसिमका हुन्छन्?",
    answerEn: "Two types — natural and artificial (man-made)",
    answerNe: "२ किसिमका — प्राकृतिक र कृतिम (मानव निर्मित)",
  },
  {
    id: 15,
    questionEn: "How many moons does Jupiter, the planet with the most moons, have?",
    questionNe: "सबैभन्दा बढी उपग्रह हुने ग्रह वृहस्पतिका कति उपग्रह छन्?",
    answerEn: "67 (note: this figure is outdated — Jupiter now has ~95 confirmed moons, and Saturn (~146) holds the record for the most moons)",
    answerNe: "६७ (नोट: यो पुरानो तथ्याङ्क हो — वृहस्पतिका हाल ~९५ पुष्टि भएका उपग्रह छन्, र सबैभन्दा बढी उपग्रह भएको ग्रह शनि (~१४६) हो)",
  },
  {
    id: 16,
    questionEn: "What is the largest satellite in the solar system?",
    questionNe: "सौर्य मण्डलको सबैभन्दा ठुलो उपग्रह कुन हो?",
    answerEn: "Ganymede (a moon of Jupiter)",
    answerNe: "गेनिमेड (वृहस्पतिको उपग्रह)",
  },
  {
    id: 17,
    questionEn: "What is the smallest satellite in the solar system?",
    questionNe: "सौर्य मण्डलको सबैभन्दा सानो उपग्रह कुन हो?",
    answerEn: "Deimos (a moon of Mars)",
    answerNe: "डिमोस (मंगलको उपग्रह)",
  },
  {
    id: 18,
    questionEn: "How many satellites have been discovered so far?",
    questionNe: "हालसम्म पत्ता लागेका उपग्रहहरु कति छन्?",
    answerEn: "181 — 173 from 8 planets plus those of 5 dwarf planets (note: outdated — the count has since risen well above 300)",
    answerNe: "१८१ — ८ ओटा ग्रहका १७३ र ५ ओटा फुच्चे ग्रहका सहित (नोट: यो पुरानो तथ्याङ्क हो — हाल संख्या ३०० भन्दा माथि पुगिसकेको छ)",
  },
  {
    id: 19,
    questionEn: "Which planet has satellites that orbit in the opposite (retrograde) direction?",
    questionNe: "आफ्ना उपग्रहहरुले विपरित दिशाबाट परिक्रमा गर्ने ग्रह कुन हो?",
    answerEn: "Neptune (its moon Triton has a retrograde orbit)",
    answerNe: "बरुण (Neptune) — यसको उपग्रह ट्राइटनले विपरित दिशामा परिक्रमा गर्छ",
  },
  {
    id: 20,
    questionEn: "Which scientist discovered that the orbits of planets and satellites are elliptical?",
    questionNe: "ग्रह र उपग्रहको कक्ष दिर्घ वृताकार रुपमा रहेको कुरा पत्ता लगाउने वैज्ञानिक को हुन्?",
    answerEn: "Johannes Kepler",
    answerNe: "जोहानस केपलर",
  },
  {
    id: 21,
    questionEn: "Which planets have no satellites?",
    questionNe: "उपग्रह नहुने ग्रहहरु कुन कुन हुन्?",
    answerEn: "Mercury and Venus",
    answerNe: "बुध र शुक्र",
  },
  {
    id: 22,
    questionEn: "What is the highest mountain on the Moon?",
    questionNe: "चन्द्रमाको सबैभन्दा अग्लो पहाड कुन हो?",
    answerEn: "Dörfel Peak (debated — modern measurements often name Mons Huygens, ~5.5 km, as the tallest identified lunar mountain)",
    answerNe: "डार्फल पिक (विवादित — आधुनिक मापनले प्रायः Mons Huygens, ~५.५ किमी, लाई सबैभन्दा अग्लो चन्द्र पहाड मान्छ)",
  },
  {
    id: 23,
    questionEn: "What was the first artificial satellite launched from Earth for commercial purposes?",
    questionNe: "पृथ्वीबाट अन्तरिक्षमा व्यापारीक प्रयोजनका लागि प्रक्षेपण गरिएको पहिलो कृतिम भू-उपग्रह कुन हो?",
    answerEn: "INTELSAT-I, popularly known as \"Early Bird\"",
    answerNe: "INTELSAT-I, जसको प्रचलित नाम \"Early Bird\" हो",
  },
  {
    id: 24,
    questionEn: "When was the first commercial artificial satellite (INTELSAT-I / Early Bird) launched?",
    questionNe: "व्यापारीक प्रयोजनका लागि प्रक्षेपण गरिएको पहिलो कृतिम भू-उपग्रह (INTELSAT-I / Early Bird) कहिले प्रक्षेपण गरिएको थियो?",
    answerEn: "6 April 1965",
    answerNe: "सन् १९६५ अप्रिल ६",
  },
  {
    id: 25,
    questionEn: "Which country launched the first commercial artificial satellite (INTELSAT-I / Early Bird)?",
    questionNe: "व्यापारीक प्रयोजनका लागि प्रक्षेपण गरिएको पहिलो कृतिम भू-उपग्रह (INTELSAT-I / Early Bird) कुन देशले प्रक्षेपण गर्‍यो?",
    answerEn: "The USA",
    answerNe: "USA (संयुक्त राज्य अमेरिका)",
  },
  {
    id: 26,
    questionEn: "What is Mercury's distance from the Sun?",
    questionNe: "बुध ग्रह सूर्यबाट कति टाढा छ?",
    answerEn: "About 5 crore 76 lakh km (57.6 million km), i.e. 0.4 AU away",
    answerNe: "करिब ५ करोड ७६ लाख कि.मि. (०.४ AU) टाढा",
  },
  {
    id: 27,
    questionEn: "How long does Mercury take to revolve around the Sun?",
    questionNe: "बुध ग्रहलाई सूर्यको परिक्रमा गर्न कति समय लाग्छ?",
    answerEn: "87.97 days (about 88 days)",
    answerNe: "८७.९७ दिन (करिब ८८ दिन)",
  },
  {
    id: 28,
    questionEn: "What is Mercury's orbital (revolution) speed?",
    questionNe: "बुध ग्रहको परिक्रमण गति कति हो?",
    answerEn: "48 km per second",
    answerNe: "४८ कि.मि. प्रति सेकेण्ड",
  },
  {
    id: 29,
    questionEn: "How many moons (satellites) does Mercury have?",
    questionNe: "बुध ग्रहको कति वटा उपग्रह छन्?",
    answerEn: "None",
    answerNe: "छैन (कुनै पनि छैन)",
  },
  {
    id: 30,
    questionEn: "What is the average temperature of Mercury?",
    questionNe: "बुध ग्रहको औसत तापक्रम कति हो?",
    answerEn: "333 degrees Centigrade",
    answerNe: "३३३ डिग्री सेन्ट्रिग्रेड",
  },
  {
    id: 31,
    questionEn: "How long does Mercury take to rotate on its own axis?",
    questionNe: "बुध ग्रहलाई आफ्नो अक्षमा घुम्न कति समय लाग्छ?",
    answerEn: "58.65 days",
    answerNe: "५८.६५ दिन",
  },
  {
    id: 32,
    questionEn: "How did Mercury get its name?",
    questionNe: "बुध ग्रहको नामाकरण कसरी भयो?",
    answerEn: "It is named after Mercury, the Roman mythological god who was the messenger and news-carrier of the gods",
    answerNe: "रोमन पौराणिक कथामा उल्लेखित देवताहरूका सञ्चार तथा समाचारका बाहक देवता Mercury का नामबाट नामाकरण गरिएको",
  },
  {
    id: 33,
    questionEn: "What else is Mercury called according to Roman mythology?",
    questionNe: "रोमन पुराणकथा अनुसार बुध ग्रहलाई अरू के भनिन्छ?",
    answerEn: "It is also called the \"Messenger of God\"",
    answerNe: "यसलाई \"Messenger Of God\" पनि भनिन्छ",
  },
  {
    id: 34,
    questionEn: "Which was the first spacecraft to orbit (revolve around) Mercury?",
    questionNe: "बुध ग्रहलाई परिक्रमा गर्ने प्रथम यान कुन हो?",
    answerEn: "MESSENGER",
    answerNe: "मेसेन्जर (MESSENGER)",
  },
  {
    id: 35,
    questionEn: "Which was the first spacecraft ever sent to Mercury?",
    questionNe: "बुध ग्रहमा सर्वप्रथम पठाइएको यान कुन हो?",
    answerEn: "Mariner 10",
    answerNe: "मेरिनर १०",
  },
  {
    id: 36,
    questionEn: "How many spacecraft did America send under the Mariner program?",
    questionNe: "मेरिनर कार्यक्रम अन्तर्गत अमेरिकाले कति वटा यान पठायो?",
    answerEn: "10 spacecraft",
    answerNe: "१० ओटा",
  },
  {
    id: 37,
    questionEn: "During what period were the Mariner spacecraft sent?",
    questionNe: "मेरिनर यानहरू कहिलेदेखि कहिलेसम्म पठाइयो?",
    answerEn: "From 22 July 1962 to 3 November 1973",
    answerNe: "सन् १९६२ जुलाई २२ देखि ३ नोभेम्बर १९७३ सम्म",
  },
  {
    id: 38,
    questionEn: "For what purpose were the Mariner spacecraft sent?",
    questionNe: "मेरिनर यानहरू केका लागि पठाइयो?",
    answerEn: "For the study of the planets Mars, Mercury and Venus",
    answerNe: "मंगल, बुध र शुक्र ग्रहको अध्ययनका लागि",
  },
  {
    id: 39,
    questionEn: "What is the Caloris Basin on Mercury?",
    questionNe: "क्यालोरिस बेसिन (बोसिन) के हो?",
    answerEn: "It is a large crater (pit) on Mercury, occupying about 0.055 of the Earth's total volume",
    answerNe: "बुध ग्रहमा भएको ठुलो खाल्डो, जुन पृथ्वीको कुल आयतनको ०.०५५ भाग रहेको छ",
  },
  {
    id: 40,
    questionEn: "What are the main characteristics of Mercury?",
    questionNe: "बुध ग्रहका मुख्य विशेषताहरू के के हुन्?",
    answerEn: "Smallest planet in the solar system; closest planet to the Sun; hot on one side and cold on the other; two-thirds of it faces the Sun; the same side always faces the Sun while orbiting; has no atmosphere and no satellites",
    answerNe: "सौर्य परिवारको सबैभन्दा सानो ग्रह; सूर्यबाट सबभन्दा नजिक रहेको ग्रह; एकापट्टि तातो र अर्कोपट्टि चिसो; दुई तिहाइ भाग सूर्यतिर रहेको; अक्ष भ्रमण गर्दा सधैं एउटै भाग सूर्यतिर फर्किरहने; वायुमण्डल र उपग्रह छैन",
  },
  {
    id: 41,
    questionEn: "What is the diameter of Mercury?",
    questionNe: "बुध ग्रहको ब्यास कति छ?",
    answerEn: "4851.3 km",
    answerNe: "४८५१.३ कि.मि.",
  },
  {
    id: 42,
    questionEn: "According to Roman mythology, which planet is called the \"Messenger of Gods\"?",
    questionNe: "रोमन पुराणकथा अनुसार कुन ग्रहलाई \"Messenger Of Gods\" भनिन्छ?",
    answerEn: "Mercury",
    answerNe: "बुध",
  },
  {
    id: 43,
    questionEn: "Which is the smallest planet in the solar system?",
    questionNe: "सौर्य परिवारको सबैभन्दा सानो ग्रह कुन हो?",
    answerEn: "Mercury",
    answerNe: "बुध",
  },
  {
    id: 44,
    questionEn: "Which planet is hot on one side and cold on the other?",
    questionNe: "एकातिर तातो र अर्कोतिर चिसो ग्रह कुन हो?",
    answerEn: "Mercury — because two-thirds of it stays facing the Sun",
    answerNe: "बुध (दुई तिहाइ भाग सूर्यतिर रहेकोले)",
  },
  {
    id: 45,
    questionEn: "Which planet always keeps the same side facing the Sun while rotating on its axis?",
    questionNe: "अक्ष भ्रमण गर्दा सधैं एउटै भाग सूर्यतिर फर्किरहने ग्रह कुन हो?",
    answerEn: "Mercury",
    answerNe: "बुध",
  },
  {
    id: 46,
    questionEn: "Which planet has no atmosphere?",
    questionNe: "वायुमण्डल नभएको ग्रह कुन हो?",
    answerEn: "Mercury",
    answerNe: "बुध",
  },
];

export const LOKSEWA_GEOGRAPHY_QA_COUNT = LOKSEWA_GEOGRAPHY_QA.length;
