import type { QAFlashcardItem } from "@/lib/qa-flashcards-types";

export const LOKSEWA_GEOGRAPHY_QA: QAFlashcardItem[] = [
  {
    id: 1,
    questionEn: "Which is the most explored/observed natural satellite?",
    questionNe: "सबैभन्दा बढी खोज गरिएको उपग्रह कुन हो?",
    answerEn: "The Moon",
    answerNe: "चन्द्रमा",
  },
  {
    id: 2,
    questionEn: "Which was the first spacecraft to reach the Moon's surface?",
    questionNe: "चन्द्र धरातलमा पुग्ने पहिलो अन्तरिक्ष यान कुन हो?",
    answerEn: "Luna 2",
    answerNe: "लुना २",
  },
  {
    id: 3,
    questionEn: "In which year did Luna 2 reach the Moon?",
    questionNe: "लुना २ चन्द्रमामा कुन सालमा पुग्यो?",
    answerEn: "In 1959",
    answerNe: "सन् १९५९",
  },
  {
    id: 4,
    questionEn: "Who was the first person to walk/step on the Moon's surface?",
    questionNe: "चन्द्रमाको धरातलमा पाइला टेक्ने पहिलो व्यक्ति को हुन्?",
    answerEn: "Neil Armstrong",
    answerNe: "निल आर्मस्ट्रङ",
  },
  {
    id: 5,
    questionEn: "Which country was Neil Armstrong from?",
    questionNe: "निल आर्मस्ट्रङ कुन देशका हुन्?",
    answerEn: "America (USA)",
    answerNe: "अमेरिकाका",
  },
  {
    id: 6,
    questionEn: "How many astronauts went on the first crewed Moon mission (Apollo 11)?",
    questionNe: "पहिलो मानवसहित चन्द्र अभियान (एपोलो ११) मा कति जना गएका थिए?",
    answerEn: "3 people",
    answerNe: "३ जना",
  },
  {
    id: 7,
    questionEn: "Who were the three astronauts on the Apollo 11 mission?",
    questionNe: "एपोलो ११ अभियानमा गएका तीन जना अन्तरिक्षयात्री को को थिए?",
    answerEn: "Neil Armstrong, Edwin Aldrin, Michael Collins (Collins did not descend to the lunar surface)",
    answerNe: "निल आर्मस्ट्रङ, एडविन एल्ड्रिन, माइकल कोलिन्स (कोलिन्स चन्द्र धरातलमा ओर्लेनन्)",
  },
  {
    id: 8,
    questionEn: "On what date did humans first land on the Moon?",
    questionNe: "मानिस पहिलो पटक चन्द्रमामा कहिले पुगे?",
    answerEn: "On 21 July 1969",
    answerNe: "सन् १९६९ जुलाई २१ मा",
  },
  {
    id: 9,
    questionEn: "Which spacecraft carried the first humans to the Moon?",
    questionNe: "पहिलो पटक मानिसलाई चन्द्रमामा कुन यानले पुर्‍यायो?",
    answerEn: "\"Apollo 11\"",
    answerNe: "\"एपोलो ११\"",
  },
  {
    id: 10,
    questionEn: "Where is the \"Sea of Tranquility\" located?",
    questionNe: "\"Sea of Tranquility\" कहाँ पर्छ?",
    answerEn: "On the Moon (the site where Apollo 11 landed)",
    answerNe: "चन्द्रमामा (एपोलो ११ उत्रेको ठाउँ)",
  },
  {
    id: 11,
    questionEn: "What is a \"nanosecond\"?",
    questionNe: "\"Nano Second\" के हो?",
    answerEn: "A unit for measuring time (1 nanosecond = one-billionth of a second)",
    answerNe: "समय नाप्ने एकाई (1 नानो सेकेन्ड = सेकेन्डको एक अर्बौँ भाग)",
  },
  {
    id: 12,
    questionEn: "Who announced the Apollo Moon-landing mission?",
    questionNe: "एपोलो अभियानको घोषणा कसले गरे?",
    answerEn: "American President John F. Kennedy",
    answerNe: "अमेरिकी राष्ट्रपति जोन एफ. केनेडीले",
  },
  {
    id: 13,
    questionEn: "What is meant by a \"satellite\"?",
    questionNe: "उपग्रह भन्नाले के बुझिन्छ?",
    answerEn: "Bodies that revolve around planets (satellites also revolve around the Sun along with their planet)",
    answerNe: "ग्रहहरुको परिक्रमा गर्ने पिण्डहरु (उपग्रहहरुले ग्रहको साथसाथै सूर्यको पनि परिक्रमा गर्दछन्)",
  },
  {
    id: 14,
    questionEn: "How many types of satellites are there?",
    questionNe: "उपग्रह कति किसिमका हुन्छन्?",
    answerEn: "Two types — natural and artificial (man-made)",
    answerNe: "२ किसिमका — प्राकृतिक र कृतिम (मानव निर्मित)",
  },
  {
    id: 15,
    questionEn: "How many moons does Jupiter, the planet with the most moons, have?",
    questionNe: "सबैभन्दा बढी उपग्रह हुने ग्रह वृहस्पतिका कति उपग्रह छन्?",
    answerEn: "67 (note: this figure is outdated — Jupiter now has ~95 confirmed moons, and Saturn (~146) holds the record for the most moons)",
    answerNe: "६७ (नोट: यो पुरानो तथ्याङ्क हो — वृहस्पतिका हाल ~९५ पुष्टि भएका उपग्रह छन्, र सबैभन्दा बढी उपग्रह भएको ग्रह शनि (~१४६) हो)",
  },
  {
    id: 16,
    questionEn: "What is the largest satellite in the solar system?",
    questionNe: "सौर्य मण्डलको सबैभन्दा ठुलो उपग्रह कुन हो?",
    answerEn: "Ganymede (a moon of Jupiter)",
    answerNe: "गेनिमेड (वृहस्पतिको उपग्रह)",
  },
  {
    id: 17,
    questionEn: "What is the smallest satellite in the solar system?",
    questionNe: "सौर्य मण्डलको सबैभन्दा सानो उपग्रह कुन हो?",
    answerEn: "Deimos (a moon of Mars)",
    answerNe: "डिमोस (मंगलको उपग्रह)",
  },
  {
    id: 18,
    questionEn: "How many satellites have been discovered so far?",
    questionNe: "हालसम्म पत्ता लागेका उपग्रहहरु कति छन्?",
    answerEn: "181 — 173 from 8 planets plus those of 5 dwarf planets (note: outdated — the count has since risen well above 300)",
    answerNe: "१८१ — ८ ओटा ग्रहका १७३ र ५ ओटा फुच्चे ग्रहका सहित (नोट: यो पुरानो तथ्याङ्क हो — हाल संख्या ३०० भन्दा माथि पुगिसकेको छ)",
  },
  {
    id: 19,
    questionEn: "Which planet has satellites that orbit in the opposite (retrograde) direction?",
    questionNe: "आफ्ना उपग्रहहरुले विपरित दिशाबाट परिक्रमा गर्ने ग्रह कुन हो?",
    answerEn: "Neptune (its moon Triton has a retrograde orbit)",
    answerNe: "बरुण (Neptune) — यसको उपग्रह ट्राइटनले विपरित दिशामा परिक्रमा गर्छ",
  },
  {
    id: 20,
    questionEn: "Which scientist discovered that the orbits of planets and satellites are elliptical?",
    questionNe: "ग्रह र उपग्रहको कक्ष दिर्घ वृताकार रुपमा रहेको कुरा पत्ता लगाउने वैज्ञानिक को हुन्?",
    answerEn: "Johannes Kepler",
    answerNe: "जोहानस केपलर",
  },
  {
    id: 21,
    questionEn: "Which planets have no satellites?",
    questionNe: "उपग्रह नहुने ग्रहहरु कुन कुन हुन्?",
    answerEn: "Mercury and Venus",
    answerNe: "बुध र शुक्र",
  },
  {
    id: 22,
    questionEn: "What is the highest mountain on the Moon?",
    questionNe: "चन्द्रमाको सबैभन्दा अग्लो पहाड कुन हो?",
    answerEn: "Dörfel Peak (debated — modern measurements often name Mons Huygens, ~5.5 km, as the tallest identified lunar mountain)",
    answerNe: "डार्फल पिक (विवादित — आधुनिक मापनले प्रायः Mons Huygens, ~५.५ किमी, लाई सबैभन्दा अग्लो चन्द्र पहाड मान्छ)",
  },
  {
    id: 23,
    questionEn: "What was the first artificial satellite launched from Earth for commercial purposes?",
    questionNe: "पृथ्वीबाट अन्तरिक्षमा व्यापारीक प्रयोजनका लागि प्रक्षेपण गरिएको पहिलो कृतिम भू-उपग्रह कुन हो?",
    answerEn: "INTELSAT-I, popularly known as \"Early Bird\"",
    answerNe: "INTELSAT-I, जसको प्रचलित नाम \"Early Bird\" हो",
  },
  {
    id: 24,
    questionEn: "When was the first commercial artificial satellite (INTELSAT-I / Early Bird) launched?",
    questionNe: "व्यापारीक प्रयोजनका लागि प्रक्षेपण गरिएको पहिलो कृतिम भू-उपग्रह (INTELSAT-I / Early Bird) कहिले प्रक्षेपण गरिएको थियो?",
    answerEn: "6 April 1965",
    answerNe: "सन् १९६५ अप्रिल ६",
  },
  {
    id: 25,
    questionEn: "Which country launched the first commercial artificial satellite (INTELSAT-I / Early Bird)?",
    questionNe: "व्यापारीक प्रयोजनका लागि प्रक्षेपण गरिएको पहिलो कृतिम भू-उपग्रह (INTELSAT-I / Early Bird) कुन देशले प्रक्षेपण गर्‍यो?",
    answerEn: "The USA",
    answerNe: "USA (संयुक्त राज्य अमेरिका)",
  },
];

export const LOKSEWA_GEOGRAPHY_QA_COUNT = LOKSEWA_GEOGRAPHY_QA.length;
