import type { QAFlashcardItem } from "@/lib/qa-flashcards-types";

export const LOKSEWA_PRODUCTS_QA: QAFlashcardItem[] = [
  {
    id: 1,
    questionEn: "Which place in Nepal is famous for pears (naaspaati)?",
    questionNe: "नेपालको कुन ठाउँ नासपातीको लागि प्रसिद्ध छ?",
    answerEn: "Phaping, Kathmandu",
    answerNe: "फर्पिङ, काठमाण्डौं",
  },
  {
    id: 2,
    questionEn: "Which district of Nepal is famous for the black cap (kaalo topi)?",
    questionNe: "नेपालको कुन जिल्ला कालो टोपीको लागि प्रसिद्ध छ?",
    answerEn: "Bhaktapur",
    answerNe: "भक्तपुर",
  },
  {
    id: 3,
    questionEn: "Which place in Nepal is famous for the Dhaka cap (Dhaka topi)?",
    questionNe: "ढाका टोपीको लागि नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Palpa",
    answerNe: "पाल्पा",
  },
  {
    id: 4,
    questionEn: "Which river of Nepal is famous for Shaligram?",
    questionNe: "नेपालको कुन नदी शालिग्रामका लागि प्रसिद्ध छ?",
    answerEn: "Kaligandaki",
    answerNe: "कालीगण्डकी",
  },
  {
    id: 5,
    questionEn: "Which place in Nepal is famous for clay pots (maataaka bhaandaa)?",
    questionNe: "माटाका भाँडाका लागि प्रसिद्ध स्थान कुन हो?",
    answerEn: "Bhaktapur",
    answerNe: "भक्तपुर",
  },
  {
    id: 6,
    questionEn: "Which place is famous for Om Khora?",
    questionNe: "ओम्खोराका लागि प्रसिद्ध स्थान कुन हो?",
    answerEn: "Palpa",
    answerNe: "पाल्पा",
  },
  {
    id: 7,
    questionEn: "Which place in Nepal is famous for sugarcane (ukhu)?",
    questionNe: "उखुका लागी प्रसिद्ध स्थान कुन हो?",
    answerEn: "Dhunibeshi",
    answerNe: "धुनिवेशी",
  },
  {
    id: 8,
    questionEn: "Which place is famous for radish (mulaa) in Nepal?",
    questionNe: "मूलाका लागी नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Chitlang",
    answerNe: "चित्लाङ",
  },
  {
    id: 9,
    questionEn: "Which district of Nepal is famous for khukuri?",
    questionNe: "खुकुरीको लागी नेपालको प्रसिद्ध जिल्ला कुन हो?",
    answerEn: "Bhojpur",
    answerNe: "भोजपुर",
  },
  {
    id: 10,
    questionEn: "Which place in Nepal is famous for karuwa (water jug)?",
    questionNe: "करुवाका लागी प्रसिद्ध स्थान कुन हो?",
    answerEn: "Palpa",
    answerNe: "पाल्पा",
  },
  {
    id: 11,
    questionEn: "Which place in Nepal is famous for yogurt (dahi)?",
    questionNe: "दहिको लागी नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Bhaktapur",
    answerNe: "भक्तपुर",
  },
  {
    id: 12,
    questionEn: "Which place is famous for guava (amba)?",
    questionNe: "अम्बाका लागी प्रसिद्ध स्थान कुन हो?",
    answerEn: "Dhunibeshi",
    answerNe: "धुनीबेसी",
  },
  {
    id: 13,
    questionEn: "Which place in Nepal is famous for beaten rice (chiura)?",
    questionNe: "चिउराका लागी नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Tikanibode",
    answerNe: "टिकनीबोडे",
  },
  {
    id: 14,
    questionEn: "Which place in Nepal is famous for rice (chaamal)?",
    questionNe: "चामलका लागी प्रसिद्ध नेपालको स्थान कुन हो?",
    answerEn: "Sikarbeshi, Nuwakot",
    answerNe: "सिकरबेसी, नुवाकोट",
  },
  {
    id: 15,
    questionEn: "Which district of Nepal is famous for wood contracting/carving (kaathko theki)?",
    questionNe: "काठको ठेकीका लागी नेपालको प्रसिद्ध जिल्ला कुन हो?",
    answerEn: "Makwanpur",
    answerNe: "मकवानपुर",
  },
  {
    id: 16,
    questionEn: "Which place is famous for handwoven cloth (gharbuna kapadaa)?",
    questionNe: "घरबुना कपडाका लागि प्रसिद्ध स्थान कुन हो?",
    answerEn: "Kirtipur",
    answerNe: "कीर्तिपुर",
  },
  {
    id: 17,
    questionEn: "Which place in Nepal is famous for cooking oil (khaane tel)?",
    questionNe: "खाने तेलका लागी नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Khokana",
    answerNe: "खोकना",
  },
  {
    id: 18,
    questionEn: "Which place is famous for mustard (torii)?",
    questionNe: "तोरीको लागी प्रसिद्ध स्थान कुन हो?",
    answerEn: "Chitwan",
    answerNe: "चितवन",
  },
  {
    id: 19,
    questionEn: "Which place in Nepal is famous for leather (chhaalaa)?",
    questionNe: "छालाको लागि नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Dailekh",
    answerNe: "दैलेख",
  },
  {
    id: 20,
    questionEn: "Which place is famous for chaaku?",
    questionNe: "चाकुका लागी प्रसिद्ध स्थान कुन हो?",
    answerEn: "Tokha, Kathmandu",
    answerNe: "टोखा, काठमाण्डौं",
  },
  {
    id: 21,
    questionEn: "Which district of Nepal is famous for coffee farming?",
    questionNe: "कफी खेतिका लागी नेपालको प्रसिद्ध जिल्ला कुन हो?",
    answerEn: "Gulmi",
    answerNe: "गुल्मी",
  },
  {
    id: 22,
    questionEn: "Which districts are famous for cotton (kapaas)?",
    questionNe: "कपासका लागी प्रसिद्ध जिल्लाहरू कुन कुन हुन्?",
    answerEn: "Banke, Bardiya, Dang",
    answerNe: "बाँके, बर्दिया, दाङ",
  },
  {
    id: 23,
    questionEn: "Which place is famous for khuwa?",
    questionNe: "खुवाका लागी प्रसिद्ध स्थान कुन हो?",
    answerEn: "Thecho, Lalitpur",
    answerNe: "ठेचो, ललितपुर",
  },
  {
    id: 24,
    questionEn: "Which places in Nepal are famous for oranges (suntala)?",
    questionNe: "सुन्तलाको लागी नेपालको प्रसिद्ध स्थानहरू कुन कुन हुन्?",
    answerEn: "Syangja, Pokhara, Dhankuta",
    answerNe: "स्याङ्जा, पोखरा, धनकुटा",
  },
  {
    id: 25,
    questionEn: "What is Dailekh famous for?",
    questionNe: "दैलेख केका लागी प्रसिद्ध छ?",
    answerEn: "Leather (chhaalaa)",
    answerNe: "छाला",
  },
  {
    id: 26,
    questionEn: "Which places in Nepal are famous for apples (syau)?",
    questionNe: "स्याउका लागी नेपालको प्रसिद्ध स्थानहरू कुन कुन हुन्?",
    answerEn: "Humla, Jumla, Mustang",
    answerNe: "हुम्ला, जुम्ला, मुस्ताङ",
  },
  {
    id: 27,
    questionEn: "Which place in Nepal is famous for cardamom (alaichi)?",
    questionNe: "अलैंचीका लागी नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Taplejung — the district that produces the most cardamom",
    answerNe: "ताप्लेजुङ (यो सबैभन्दा धेरै अलैंची उत्पादन हुने जिल्ला हो)",
  },
  {
    id: 28,
    questionEn: "Which place in Nepal is famous for ginger (aduwa)?",
    questionNe: "अदुवाको लागी नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Maalneta, Salyan",
    answerNe: "मालनेटा, सल्यान",
  },
  {
    id: 29,
    questionEn: "Which place in Nepal is famous for taapke?",
    questionNe: "ताप्केका लागि नेपालको प्रसिद्ध स्थान कुन हो?",
    answerEn: "Birgunj, Parsa",
    answerNe: "पर्साको वीरगन्ज",
  },
  {
    id: 30,
    questionEn: "Which places in Nepal are famous for fish (maachhaa)?",
    questionNe: "माछाका लागी नेपालको प्रसिद्ध स्थानहरू कुन कुन हुन्?",
    answerEn: "Baahrabise, Kulekhani",
    answerNe: "बाह्रबिसे, कुलेखानी",
  },
  {
    id: 31,
    questionEn: "Which districts of Nepal are famous for radi-pakhi (woolen blankets)?",
    questionNe: "राडीपाखीका लागी नेपालको प्रसिद्ध जिल्लाहरू कुन कुन हुन्?",
    answerEn: "Okhaldhunga, Baglung",
    answerNe: "ओखलढुङ्गा, बाग्लुङ",
  },
];

export const LOKSEWA_PRODUCTS_QA_COUNT = LOKSEWA_PRODUCTS_QA.length;
