import type { MetadataRoute } from "next";
import { DSA_BASIC_PROBLEMS } from "@/lib/dsa/dsa-problems";
import { FICTION_BOOKS } from "@/lib/library/fiction-books";
import { SOFTWARE_ENGINEERING_BOOKS } from "@/lib/library/software-engineering-books";
import { IT_OFFICER_CONCEPTS } from "@/lib/loksewa-learning/it-officer-syllabus-data";

const siteUrl = "https://learn.rajanmidun.com.np";

const routes = [
  "/",
  "/focus",
  "/blog",
  "/blog/ai-engineer-roadmap-2027",
  "/blog/cicd-github-actions-beginners",
  "/blog/software-engineering-career-ai-era",
  "/learn",
  "/learn/ai-prompts",
  "/learn/backend-engineering",
  "/learn/code-review",
  "/learn/code-review/javascript",
  "/learn/code-review/laravel",
  "/learn/code-review/python",
  "/learn/code-review/react",
  "/learn/code-review/typescript",
  "/learn/compiler",
  "/learn/devops",
  "/learn/devotion",
  "/learn/discipline",
  "/learn/dsa",
  "/learn/dsa/basic",
  "/learn/duolingo",
  "/learn/english-meaning",
  "/learn/exercise",
  "/learn/focus-goals",
  "/learn/focus-music",
  "/learn/git-7-days",
  "/learn/japanese-interview",
  "/learn/japanese-n3",
  "/learn/japanese-n4",
  "/learn/japanese-n5",
  "/learn/javascript",
  "/learn/kafka",
  "/learn/language",
  "/learn/laravel",
  "/learn/loksewa",
  "/learn/loksewa/ethnic-groups",
  "/learn/loksewa/geography",
  "/learn/loksewa/gk",
  "/learn/loksewa/it-officer",
  "/learn/loksewa/products",
  "/learn/mongodb",
  "/learn/motivation",
  "/learn/nestjs",
  "/learn/nextjs",
  "/learn/nodejs",
  "/learn/personal-development",
  "/learn/programming",
  "/learn/python",
  "/learn/rabbitmq",
  "/learn/react",
  "/learn/react-native",
  "/learn/speak-like-pro",
  "/learn/sql",
  "/learn/supabase",
  "/learn/survival-phrases",
  "/learn/system-design",
  "/learn/tongue-twister",
  "/library",
  "/library/business/the-innovators-dilemma",
  "/library/fiction/animal-farm",
  "/library/fiction/frankenstein",
  "/library/fiction/peter-pan-and-wendy",
  "/library/fiction/the-jungle-book",
  "/library/fiction/the-wizard-of-oz",
  "/library/finance/a-random-walk-down-wall-street",
  "/library/finance/finance-book",
  "/library/finance/i-will-teach-you-to-be-rich",
  "/library/finance/the-intelligent-investor",
  "/library/finance/the-millionaire-next-door",
  "/library/finance/the-psychology-of-money",
  "/library/finance/the-richest-man-in-babylon",
  "/library/finance/the-simple-path-to-wealth",
  "/library/finance/the-total-money-makeover",
  "/library/finance/your-money-or-your-life",
  "/library/nepali/gaukhane-katha",
  "/library/nepali/maile-dekheko-darbar",
  "/library/personal-development/atomic-habits",
  "/library/personal-development/eat-that-frog",
  "/library/personal-development/how-to-win-friends",
  "/library/personal-development/mindset",
  "/library/personal-development/power-of-your-subconscious-mind",
  "/library/personal-development/the-7-habits",
  "/library/personal-development/the-mountain-is-you",
  "/library/personal-development/think-again",
  "/library/personal-development/thinking-fast-and-slow",
  "/library/software-engineering",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const entries: MetadataRoute.Sitemap = routes.map((route) => ({
    url: new URL(route, siteUrl).toString(),
    changeFrequency: route.startsWith("/blog") ? "monthly" : "weekly",
    priority: route === "/" ? 1 : route === "/learn" || route === "/library" ? 0.9 : 0.7,
  }));

  return [
    ...entries,
    ...DSA_BASIC_PROBLEMS.map(({ slug }) => ({ url: `${siteUrl}/learn/dsa/basic/${slug}`, changeFrequency: "weekly" as const, priority: 0.7 })),
    ...IT_OFFICER_CONCEPTS.map(({ slug }) => ({ url: `${siteUrl}/learn/loksewa/it-officer/${slug}`, changeFrequency: "weekly" as const, priority: 0.7 })),
    ...FICTION_BOOKS.map(({ slug }) => ({ url: `${siteUrl}/library/fiction/${slug}`, changeFrequency: "monthly" as const, priority: 0.6 })),
    ...SOFTWARE_ENGINEERING_BOOKS.map(({ slug }) => ({ url: `${siteUrl}/library/software-engineering/${slug}`, changeFrequency: "monthly" as const, priority: 0.6 })),
  ];
}
