import type { RoadmapDayDetail } from "./challenge-data";

export const DAY_4_DETAIL = {
  overview: [
    "REST is not the only answer. Day 4 compares the three dominant API paradigms — REST, GraphQL, and gRPC — so you can choose deliberately rather than by default. Beyond the protocol, you will learn the patterns that make any API maintainable: consistent pagination, filtering, error shapes, rate limiting, idempotency, and backward-compatible versioning.",
    "By the end you should design a paginated, versioned REST or GraphQL API, write a Protobuf service definition, and explain why idempotency keys matter for payment flows.",
  ],
  sections: [
    {
      title: "REST vs GraphQL vs gRPC — picking the right tool",
      blocks: [
        {
          type: "paragraph",
          text: "All three solve the same problem — getting data between a client and a server — but they optimise for different things: REST for simplicity and cacheability, GraphQL for flexible client-driven queries, gRPC for performance and strong contracts in internal services.",
        },
        { type: "diagram", id: "rest-graphql-grpc" },
        {
          type: "table",
          caption: "Choose based on your consumers, not personal preference.",
          headers: ["Dimension", "REST", "GraphQL", "gRPC"],
          rows: [
            [
              "Protocol",
              "HTTP/1.1 or HTTP/2, text (JSON/XML)",
              "HTTP/1.1 or HTTP/2, JSON",
              "HTTP/2, binary (Protobuf)",
            ],
            [
              "Schema / contract",
              "OpenAPI (optional but recommended)",
              "Strongly typed SDL — schema is the contract",
              "Protobuf `.proto` — strongly typed, versioned",
            ],
            [
              "Data fetching",
              "Server decides shape; clients may over/under-fetch",
              "Clients declare exactly the fields they need",
              "Defined by the server in `.proto`; no flexibility",
            ],
            [
              "Caching",
              "HTTP caching (ETags, CDN) works natively",
              "Hard — queries are POST, vary infinitely",
              "No HTTP-layer caching; application-level only",
            ],
            [
              "Streaming",
              "SSE or WebSocket bolt-on",
              "Subscriptions over WebSocket",
              "Bidirectional streaming built in",
            ],
            [
              "Best for",
              "Public APIs, mobile clients, simple CRUD",
              "BFF (backend-for-frontend), complex UIs, multiple clients",
              "Internal microservices, high-throughput, polyglot services",
            ],
          ],
        },
        {
          type: "list",
          variant: "bullet",
          items: [
            "Default to REST for a first public API — every HTTP client can use it and CDNs cache it for free.",
            "Add GraphQL at the BFF layer when you have many clients (web, iOS, Android) that need different shapes of the same data.",
            "Use gRPC for inter-service calls where latency and throughput matter and you control both ends.",
          ],
        },
      ],
    },
    {
      title: "GraphQL — schema design and the N+1 problem",
      blocks: [
        {
          type: "paragraph",
          text: "GraphQL's schema is the source of truth. Every type, field, and resolver is explicit. The client declares the shape it wants; the server fulfils it. This eliminates over-fetching (getting fields you do not use) and under-fetching (needing a second request for related data).",
        },
        {
          type: "code",
          title: "GraphQL schema — social app",
          code: [
            "type User {",
            "  id:        ID!",
            "  username:  String!",
            "  email:     String!",
            "  posts(first: Int, after: String): PostConnection!",
            "  followers: [User!]!",
            "}",
            "",
            "type Post {",
            "  id:        ID!",
            "  author:    User!",
            "  title:     String!",
            "  body:      String!",
            "  tags:      [String!]!",
            "  createdAt: DateTime!",
            "  likes:     Int!",
            "}",
            "",
            "type PostConnection {",
            "  edges:    [PostEdge!]!",
            "  pageInfo: PageInfo!",
            "}",
            "",
            "type PostEdge {",
            "  cursor: String!",
            "  node:   Post!",
            "}",
            "",
            "type PageInfo {",
            "  hasNextPage:     Boolean!",
            "  hasPreviousPage: Boolean!",
            "  startCursor:     String",
            "  endCursor:       String",
            "}",
            "",
            "type Query {",
            "  user(id: ID!):           User",
            "  feed(first: Int, after: String): PostConnection!",
            "}",
            "",
            "type Mutation {",
            "  createPost(input: CreatePostInput!): Post!",
            "  likePost(postId: ID!):               Post!",
            "}",
            "",
            "type Subscription {",
            "  postLiked(postId: ID!): Post!",
            "}",
            "",
            "input CreatePostInput {",
            "  title: String!",
            "  body:  String!",
            "  tags:  [String!]",
            "}",
          ].join("\n"),
        },
        {
          type: "paragraph",
          text: "The N+1 problem: fetching 10 posts triggers 10 separate queries for each post's author — 11 round trips total. Fix with DataLoader: batch all author lookups into one `SELECT ... WHERE id IN (...)` per request tick.",
        },
        {
          type: "code",
          title: "DataLoader — batch + cache per request",
          code: [
            "import DataLoader from 'dataloader';",
            "",
            "// Created once per request (never shared across requests)",
            "const userLoader = new DataLoader(async (ids: readonly string[]) => {",
            "  const users = await db.query(",
            "    'SELECT * FROM users WHERE id = ANY($1)', [ids]",
            "  );",
            "  // DataLoader requires results in the same order as ids",
            "  return ids.map(id => users.find(u => u.id === id) ?? null);",
            "});",
            "",
            "// Resolver — called once per Post, batched automatically",
            "const resolvers = {",
            "  Post: {",
            "    author: (post) => userLoader.load(post.authorId),",
            "  },",
            "};",
            "",
            "// 10 posts → 10 loader.load() calls → 1 batched SQL query",
          ].join("\n"),
        },
      ],
    },
    {
      title: "gRPC — Protobuf definitions and streaming",
      blocks: [
        {
          type: "paragraph",
          text: "gRPC uses Protocol Buffers (Protobuf) as the IDL and wire format. The `.proto` file is the contract — generate client and server stubs in any supported language. Binary encoding is 3–10× smaller than JSON and faster to serialise.",
        },
        {
          type: "code",
          title: "posts.proto — service definition",
          code: [
            'syntax = "proto3";',
            "package posts.v1;",
            "",
            "// Run: protoc --go_out=. --go-grpc_out=. posts.proto",
            "",
            "service PostService {",
            "  // Unary RPC",
            "  rpc GetPost    (GetPostRequest)    returns (Post);",
            "  // Server streaming — live feed",
            "  rpc WatchFeed  (WatchFeedRequest)  returns (stream Post);",
            "  // Client streaming — bulk import",
            "  rpc ImportPosts(stream Post)        returns (ImportResult);",
            "  // Bidirectional streaming — chat",
            "  rpc Chat       (stream ChatMessage) returns (stream ChatMessage);",
            "}",
            "",
            "message Post {",
            "  string id         = 1;",
            "  string author_id  = 2;",
            "  string title      = 3;",
            "  string body       = 4;",
            "  repeated string tags = 5;",
            "  int64  created_at = 6; // unix millis",
            "}",
            "",
            "message GetPostRequest  { string id = 1; }",
            "message WatchFeedRequest{ string user_id = 1; }",
            "message ImportResult    { int32 imported = 1; repeated string errors = 2; }",
            "message ChatMessage     { string user_id = 1; string text = 2; int64 ts = 3; }",
          ].join("\n"),
        },
        {
          type: "list",
          variant: "bullet",
          items: [
            "Field numbers (= 1, = 2 …) are stable identifiers on the wire — never reuse or remove a field number for backward compatibility.",
            "Use `optional` or `oneof` for fields that may be absent; `proto3` makes all scalar fields zero-valued by default (not null).",
            "gRPC-Web bridges gRPC to browser clients via an Envoy proxy — browsers cannot speak raw HTTP/2 framing.",
            "Deadlines + cancellation are first-class: always set a deadline on every RPC call to prevent cascading hangs.",
          ],
        },
      ],
    },
    {
      title: "Pagination — offset vs cursor",
      blocks: [
        {
          type: "paragraph",
          text: "Offset pagination (`?page=3&limit=20`) is simple but breaks under concurrent writes — new rows inserted on page 1 shift every subsequent page, causing duplicates or skips. Cursor pagination uses a stable pointer into the ordered result set.",
        },
        { type: "diagram", id: "cursor-pagination" },
        {
          type: "table",
          headers: ["Strategy", "How", "Pros", "Cons"],
          rows: [
            [
              "Offset / page",
              "`LIMIT 20 OFFSET 40`",
              "Simple, random access, easy UI",
              "Drifts on inserts/deletes; full scan to offset on large tables",
            ],
            [
              "Cursor (keyset)",
              "`WHERE created_at < $cursor ORDER BY created_at DESC LIMIT 20`",
              "Stable, O(log n) with index, handles concurrent writes",
              "No random page jump; cursor must be kept by the client",
            ],
            [
              "Seek / keyset (composite)",
              "`WHERE (created_at, id) < ($ts, $id)` — tie-break with id",
              "Consistent even with duplicate timestamps",
              "More complex WHERE clause",
            ],
          ],
        },
        {
          type: "code",
          title: "Cursor pagination — REST endpoint",
          code: [
            "// Encode cursor as base64(JSON) to hide internals",
            "const encodeCursor = (row) =>",
            "  Buffer.from(JSON.stringify({ ts: row.created_at, id: row.id })).toString('base64url');",
            "",
            "const decodeCursor = (cursor) =>",
            "  JSON.parse(Buffer.from(cursor, 'base64url').toString());",
            "",
            "// GET /api/v1/posts?limit=20&after=<cursor>",
            "app.get('/api/v1/posts', async (req, res) => {",
            "  const limit = Math.min(Number(req.query.limit) || 20, 100);",
            "  const cursor = req.query.after ? decodeCursor(req.query.after) : null;",
            "",
            "  const rows = await db.query(`",
            "    SELECT * FROM posts",
            "    WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1, $2::bigint))",
            "    ORDER BY created_at DESC, id DESC",
            "    LIMIT $3",
            "  `, [cursor?.ts ?? null, cursor?.id ?? null, limit + 1]);",
            "",
            "  const hasNext = rows.length > limit;",
            "  const data    = rows.slice(0, limit);",
            "",
            "  res.json({",
            "    data,",
            "    pagination: {",
            "      hasNextPage: hasNext,",
            "      endCursor:   hasNext ? encodeCursor(data.at(-1)) : null,",
            "    },",
            "  });",
            "});",
          ].join("\n"),
        },
      ],
    },
    {
      title: "Filtering, sorting, and field selection",
      blocks: [
        {
          type: "code",
          title: "Conventions for REST query params",
          code: [
            "# Filtering — use field names directly, keep it simple",
            "GET /posts?status=published&author_id=42",
            "",
            "# Range filters with operators",
            "GET /posts?created_after=2024-01-01&created_before=2024-06-01",
            "",
            "# Sorting — prefix with '-' for descending",
            "GET /posts?sort=-created_at,title      # created_at DESC, title ASC",
            "",
            "# Sparse fieldsets — reduce response size",
            "GET /posts?fields=id,title,created_at",
            "",
            "# Pagination",
            "GET /posts?limit=20&after=<cursor>",
            "",
            "# Combined",
            "GET /posts?status=published&sort=-created_at&limit=20&after=<cursor>",
          ].join("\n"),
        },
        {
          type: "list",
          variant: "bullet",
          items: [
            "Never trust raw filter values in SQL — always parameterise. Validate that sort fields are in an allowlist before interpolating into ORDER BY.",
            "Expose a `?search=` param for full-text; route it to `tsvector` / Elasticsearch, not `ILIKE '%x%'`.",
            "Document every filter and sort field in OpenAPI — clients should not guess.",
          ],
        },
      ],
    },
    {
      title: "Rate limiting — algorithms and headers",
      blocks: [
        {
          type: "paragraph",
          text: "Rate limiting protects your API from abuse and accidental overload. Apply it at the API gateway or middleware layer, keyed by user id, IP, or API key depending on trust level.",
        },
        { type: "diagram", id: "rate-limit-token-bucket" },
        {
          type: "table",
          headers: ["Algorithm", "How it works", "Best for"],
          rows: [
            [
              "Token bucket",
              "Bucket holds up to N tokens; refilled at rate R/sec. Each request consumes one token. Allows bursts up to bucket capacity.",
              "Most APIs — smooth average with controlled bursts",
            ],
            [
              "Leaky bucket",
              "Requests queue; processed at fixed rate. Excess requests are dropped.",
              "Smoothing bursty traffic into uniform output",
            ],
            [
              "Fixed window",
              "Count resets every window (e.g. 100 req/min). Simple with Redis INCR + EXPIRE.",
              "Simple use cases; can double-spend at window boundary",
            ],
            [
              "Sliding window log",
              "Log timestamps; count within rolling window. Accurate, memory-heavy.",
              "Strict accuracy at low traffic",
            ],
            [
              "Sliding window counter",
              "Blend current + previous window counts by elapsed fraction. Accurate at low memory.",
              "Production default (Cloudflare, Redis rate-limiter)",
            ],
          ],
        },
        {
          type: "code",
          title: "Standard rate-limit response headers",
          code: [
            "HTTP/1.1 429 Too Many Requests",
            "Content-Type: application/json",
            "RateLimit-Limit:     100",
            "RateLimit-Remaining: 0",
            "RateLimit-Reset:     1717200060   # Unix timestamp",
            "Retry-After:         37           # seconds",
            "",
            '{ "error": "rate_limit_exceeded", "retry_after": 37 }',
            "",
            "# IETF draft RateLimit headers (RFC 9110 successor):",
            "RateLimit: limit=100, remaining=0, reset=37",
          ].join("\n"),
        },
      ],
    },
    {
      title: "Idempotency keys",
      blocks: [
        {
          type: "paragraph",
          text: "Network failures are inevitable. When a client retries a POST (create payment, place order, send email), the server may execute it twice if it has no memory of the first attempt. An idempotency key lets the server deduplicate retries safely.",
        },
        {
          type: "code",
          title: "Idempotency key — server implementation",
          code: [
            "// Client sends a UUID in the header",
            "// POST /payments",
            "// Idempotency-Key: 018f1c3e-7b5a-7000-8e4d-2a1b3c4d5e6f",
            "",
            "app.post('/payments', async (req, res) => {",
            "  const key = req.headers['idempotency-key'];",
            "  if (!key) return res.status(400).json({ error: 'Idempotency-Key required' });",
            "",
            "  // 1. Check cache (Redis TTL = 24h)",
            "  const cached = await redis.get(`idem:${key}`);",
            "  if (cached) {",
            "    return res.status(200).json(JSON.parse(cached)); // replay stored response",
            "  }",
            "",
            "  // 2. Process (charge card, debit inventory, …)",
            "  const result = await processPayment(req.body);",
            "",
            "  // 3. Store response before returning",
            "  await redis.set(`idem:${key}`, JSON.stringify(result), 'EX', 86400);",
            "  res.status(201).json(result);",
            "});",
            "",
            "// Second identical request → same key → cached response returned",
            "// Network retry-safe: exactly-once semantics from client's perspective",
          ].join("\n"),
        },
        {
          type: "list",
          variant: "bullet",
          items: [
            "Scope keys per user — a key from user A must not collide with user B's key.",
            "Store the full response (status + body), not just a flag — replay the exact original response.",
            "TTL of 24h is typical for payments; for inventory ops, match your SLA.",
            "Return `409 Conflict` if the same key is used with a different request body.",
          ],
        },
      ],
    },
    {
      title: "Consistent error payloads (RFC 9457)",
      blocks: [
        {
          type: "paragraph",
          text: "Inconsistent error shapes are one of the most painful API anti-patterns. Every error from every endpoint should have the same JSON structure so clients can handle them generically. RFC 9457 (`application/problem+json`) is the standard.",
        },
        {
          type: "code",
          title: "Validation error — structured details array",
          code: [
            "HTTP/1.1 422 Unprocessable Entity",
            "Content-Type: application/problem+json",
            "",
            "{",
            '  "type":     "https://api.example.com/errors/validation",',
            '  "title":    "Validation failed",',
            '  "status":   422,',
            '  "instance": "/api/v1/posts",',
            '  "errors": [',
            '    { "field": "title", "code": "required",   "message": "Title is required." },',
            '    { "field": "body",  "code": "min_length", "message": "Body must be at least 10 chars.", "min": 10 }',
            "  ]",
            "}",
            "",
            "# GraphQL error shape (Apollo / Yoga convention)",
            "{",
            '  "errors": [',
            "    {",
            '      "message": "Title is required.",',
            '      "locations": [{ "line": 2, "column": 3 }],',
            '      "path": ["createPost"],',
            '      "extensions": { "code": "BAD_USER_INPUT", "field": "title" }',
            "    }",
            "  ]",
            "}",
          ].join("\n"),
        },
        {
          type: "list",
          variant: "bullet",
          items: [
            "Always include `type` (a stable URI), `title` (human readable), and `status` (HTTP code).",
            "Add `instance` (the request path) so logs correlate errors to specific calls.",
            "Validation errors should list every failing field — never stop at the first error.",
            "Never expose stack traces, SQL errors, or internal class names in production responses.",
          ],
        },
      ],
    },
    {
      title: "Backward compatibility and versioning",
      blocks: [
        {
          type: "paragraph",
          text: "Breaking changes force every caller to update at once. Prefer additive changes and use versioning only for true breaking changes — not every release.",
        },
        {
          type: "table",
          caption: "Safe vs breaking changes — know the difference.",
          headers: ["Change", "Safe?", "Why"],
          rows: [
            [
              "Add a new optional field to a response",
              "✅ Safe",
              "Existing clients ignore unknown fields",
            ],
            [
              "Add a new optional request parameter",
              "✅ Safe",
              "Existing clients do not send it",
            ],
            [
              "Add a new endpoint",
              "✅ Safe",
              "Existing clients do not call it",
            ],
            [
              "Remove a response field",
              "❌ Breaking",
              "Clients that read it will fail or crash",
            ],
            [
              "Rename a field",
              "❌ Breaking",
              "Same as remove + add from client's perspective",
            ],
            [
              "Change a field's type (string → int)",
              "❌ Breaking",
              "Clients will fail to parse",
            ],
            [
              "Change enum values / error codes",
              "❌ Breaking",
              "Clients that switch on them break",
            ],
            [
              "Make an optional field required",
              "❌ Breaking",
              "Existing callers that omit it now get 400",
            ],
          ],
        },
        {
          type: "list",
          variant: "number",
          items: [
            "Prefer URI versioning (`/v2/`) for REST — visible, easy to route, easy to sunset.",
            "For GraphQL: use `@deprecated` directives and provide a migration path before removal.",
            "For Protobuf: never remove or reuse field numbers. Add new fields; mark old ones deprecated in a comment.",
            "Run a changelog and publish a sunset date (HTTP `Sunset` header) before removing a version.",
          ],
        },
      ],
    },
    {
      title: "Exercises",
      blocks: [
        {
          type: "list",
          variant: "number",
          items: [
            "Cursor pagination — implement the `/posts` endpoint above; seed 10k rows and verify that concurrent inserts do not cause duplicates across pages.",
            "GraphQL + DataLoader — spin up Apollo Server with the social schema; confirm with query logs that N posts resolve the author with 1 SQL query instead of N.",
            "gRPC stub — write `posts.proto` with a unary `GetPost` and a server-streaming `WatchFeed`; generate stubs and write a client that calls both.",
            "Idempotency — build the `/payments` endpoint; fire the same request twice with the same key and assert the second call returns the cached response without hitting the payment processor again.",
          ],
        },
        {
          type: "paragraph",
          text: "Being able to demo cursor pagination stability live — inserting rows mid-page and showing no duplicates — is a stronger interview signal than theory alone.",
        },
      ],
    },
  ],
  faq: [
    {
      question:
        "What are the main differences between REST, GraphQL, and gRPC?",
      tag: "REST vs GraphQL vs gRPC",
      answer: [
        "REST: resource-oriented URLs, HTTP verbs as actions, JSON over HTTP. Works with any client. Native HTTP caching. Best for public APIs and simple CRUD where cacheability matters.",
        "GraphQL: single endpoint, client-specified queries. Eliminates over/under-fetching. Strong typed schema. Hard to cache at HTTP layer (queries are POST). Best for BFF (backend-for-frontend) layers serving multiple client types with different data needs.",
        "gRPC: Protobuf binary encoding over HTTP/2. 3–10× smaller payloads than JSON, fast serialisation, streaming built in. Requires code generation from `.proto`. Best for internal microservice-to-microservice calls where you control both ends and performance matters.",
      ].join("\n\n"),
      callout:
        "REST for public APIs. GraphQL at the BFF layer. gRPC for internal services.",
    },
    {
      question: "When should you use GraphQL over REST?",
      tag: "GraphQL use cases",
      answer: [
        "GraphQL pays off when you have multiple clients (web, iOS, Android, third-party) that need different shapes of the same underlying data. Instead of maintaining multiple REST endpoints or adding query params to control the response shape, clients declare exactly what they need.",
        "Other good fits: dashboards with complex, deeply nested data; rapid UI iteration where the backend schema stays stable but client data needs evolve; real-time features via subscriptions.",
        "GraphQL adds complexity: you need a DataLoader layer to prevent N+1 queries, persisted queries for CDN caching, query depth/complexity limits to prevent abuse, and a schema management workflow. Do not add it speculatively.",
      ].join("\n\n"),
      callout:
        "GraphQL shines when many clients need different shapes of the same data. It adds real complexity — add it with intention.",
    },
    {
      question:
        "What is the N+1 problem in GraphQL and how does DataLoader solve it?",
      tag: "N+1 and DataLoader",
      answer: [
        "When you fetch a list of N posts and each post's resolver independently queries the database for its author, you make N separate SQL calls — one per post, plus one for the list itself = N+1 round trips.",
        "DataLoader solves this by batching: all `loader.load(authorId)` calls within the same event loop tick are collected and fired as a single `SELECT ... WHERE id IN (...)`. It also caches results per request, so the same author loaded by two different posts is only fetched once.",
        "Key rule: create a new DataLoader instance per request (never share across requests — that would cache stale data for other users). Pass it via context in Apollo/Yoga.",
      ].join("\n\n"),
      callout:
        "DataLoader: batch all loads in one tick → one SQL query. New instance per request.",
    },
    {
      question:
        "What is cursor-based pagination and why is it better than offset?",
      tag: "Cursor vs offset pagination",
      answer: [
        "Offset pagination (`LIMIT 20 OFFSET 60`) works by skipping rows. When new rows are inserted or deleted between page loads, the offset shifts — you see duplicates or skip rows. On large tables, OFFSET also forces a full scan to the skip point.",
        "Cursor pagination uses a stable pointer (usually a base64-encoded value of the last row's sort key). The query becomes `WHERE (created_at, id) < ($cursor_ts, $cursor_id) ORDER BY created_at DESC LIMIT 20` — the database can use an index to seek directly to the cursor position.",
        "The trade-off: no random page access (you cannot jump to page 7), and the client must store and forward the cursor. For infinite-scroll and feed-style UIs this is almost always the right choice.",
      ].join("\n\n"),
      callout:
        "Cursor = stable pointer into sorted results. Offset = skip N rows. Cursor wins for feeds and concurrent data.",
    },
    {
      question:
        "What is a Protobuf field number and why can you never reuse one?",
      tag: "Protobuf field numbers",
      answer: [
        "Field numbers are the actual identifiers on the wire — Protobuf does not encode field names. A field tagged `= 1` in the `.proto` is encoded as tag 1 in every serialised message.",
        "If you remove field 1 and add a new field also tagged `= 1` with a different type, old clients reading the new message will interpret the bytes as the old type and corrupt data. Old messages read by new code will fill the new field with garbage.",
        "The rule: mark unused fields `reserved` to prevent accidental reuse. Never change a field's type. Add new fields with new numbers. Deprecate old fields with a comment — remove them from code, but keep the number reserved.",
      ].join("\n\n"),
      callout:
        "Field numbers are the wire identity. Reserved them when removing — never reuse.",
    },
    {
      question: "What is an idempotency key and when do you need one?",
      tag: "Idempotency keys",
      answer: [
        "An idempotency key is a client-generated unique token (UUID v7 recommended) sent in a request header. The server stores the response keyed by that token. On a retry with the same key, the server returns the stored response without re-executing the side effect.",
        "You need idempotency keys on any non-idempotent operation where network failures can cause duplicate execution: payments, order placement, inventory deduction, email sending, webhook delivery.",
        "Implementation: check key in Redis before processing. If found, return cached response. If not, process and store before returning. Scope keys per user to prevent cross-user conflicts. Set a TTL (24h typical for payments).",
      ].join("\n\n"),
      callout:
        "Client sends UUID → server deduplicates on retry. Required for payments and any operation with real-world side effects.",
    },
    {
      question: "What rate limiting algorithms are used in production?",
      tag: "Rate limiting algorithms",
      answer: [
        "Token bucket (most common): a bucket holds up to N tokens, refilled at R per second. Each request consumes one token. Allows bursts up to bucket capacity while enforcing a long-term average rate. Redis implementation: `INCR` + `EXPIRE` or the `redis-cell` module.",
        "Sliding window counter: blend the previous window's count weighted by how much of the current window has elapsed. More accurate than fixed windows (no double-spend at window boundaries) at low memory cost. Used by Cloudflare and the Redis rate-limiter library.",
        "Fixed window: simplest — increment a counter per window, reset on expiry. Can allow 2× the rate at the window boundary (last second of window + first second of next). Good enough for loose limits.",
      ].join("\n\n"),
      callout:
        "Token bucket for burst-tolerant limits. Sliding window counter for accuracy. Fixed window for simplicity.",
    },
    {
      question: "What HTTP headers should a rate-limited response include?",
      tag: "Rate limit headers",
      answer: [
        "Return `429 Too Many Requests` with: `RateLimit-Limit` (the limit), `RateLimit-Remaining` (tokens left), `RateLimit-Reset` (Unix timestamp or seconds until reset), and `Retry-After` (seconds the client should wait).",
        "The IETF draft standardises a single `RateLimit` header: `RateLimit: limit=100, remaining=0, reset=37`. Cloudflare, GitHub, and Stripe all use variants of the multi-header form.",
        "Also send these headers on successful responses so clients can track their budget proactively and back off before hitting the limit.",
      ].join("\n\n"),
      callout:
        "Always send Retry-After on 429. Send RateLimit-Remaining on every response so clients can self-throttle.",
    },
    {
      question: "What makes a REST API change backward-compatible?",
      tag: "Backward compatibility",
      answer: [
        "Safe (additive): adding new optional fields to responses, adding new optional request parameters, adding new endpoints. Existing clients ignore unknown fields (Postel's law).",
        "Breaking: removing or renaming a field, changing a field's type, making an optional param required, changing the meaning of a status code or enum value.",
        "Strategy: treat your API schema as a public interface. Use `@deprecated` in GraphQL. Use `reserved` in Protobuf. Publish a sunset date via the HTTP `Sunset` header before removing a REST version. Run contract tests against every client before shipping.",
      ].join("\n\n"),
      callout:
        "Add freely. Remove with a sunset date. Never rename a live field in one shot.",
    },
    {
      question:
        "What is the difference between authentication and authorisation in APIs?",
      tag: "AuthN vs AuthZ",
      answer: [
        "Authentication (AuthN): confirming who the caller is. The API verifies a credential — JWT signature, API key, OAuth token — and resolves it to an identity (user id, service account).",
        "Authorisation (AuthZ): deciding what that identity is allowed to do. After you know who the caller is, you check if they have permission to perform the requested action on the requested resource.",
        "A request can fail AuthN (no token → 401) or pass AuthN but fail AuthZ (valid token, wrong role → 403). Never skip AuthZ because AuthN passed — they are separate checks.",
      ].join("\n\n"),
      callout:
        "AuthN: who are you? AuthZ: what are you allowed to do? 401 = unauthenticated, 403 = unauthorised.",
    },
    {
      question:
        "How do you handle filtering safely in REST — avoiding SQL injection?",
      tag: "Safe filtering",
      answer: [
        "Always parameterise filter values — never interpolate them into SQL strings. Use an ORM's query builder or `$1` placeholders in raw SQL.",
        "Validate sort fields against a hard-coded allowlist before using them in an ORDER BY clause. `ORDER BY ${req.query.sort}` is injectable; `ORDER BY ${ALLOWED_SORT_FIELDS.includes(sort) ? sort : 'created_at'}` is safe.",
        "For complex filter expressions (e.g. `?filter[status][in][]=published&filter[status][in][]=draft`), parse into a query object first, validate each field and operator, then build the parameterised query. Libraries like `qs` help parse nested query strings.",
      ].join("\n\n"),
      callout:
        "Parameterise values. Allowlist sort/filter field names. Never interpolate user input into SQL.",
    },
    {
      question: "What is an API gateway and what does it do?",
      tag: "API gateway",
      answer: [
        "An API gateway is a reverse proxy that sits in front of your services and handles cross-cutting concerns: authentication, rate limiting, TLS termination, request routing, response caching, logging, and observability.",
        "Common gateways: AWS API Gateway, Kong, Envoy, Nginx, Traefik, Cloudflare Workers. They centralise policies so individual services do not implement them independently.",
        "At small scale a gateway can be overkill — a single well-configured Nginx handles most of the above. At microservice scale, a gateway prevents every service from reimplementing auth and rate limiting differently.",
      ].join("\n\n"),
      callout:
        "Gateway = auth + rate limiting + routing in one place. Avoids reimplementing cross-cutting concerns in every service.",
    },
    {
      question: "What is the Relay pagination spec and should I follow it?",
      tag: "Relay cursor spec",
      answer: [
        "The Relay Cursor Connections Specification defines a standard shape for paginated GraphQL responses: a `Connection` type with `edges` (array of `{ cursor, node }`), `pageInfo` (`hasNextPage`, `hasPreviousPage`, `startCursor`, `endCursor`), and optional `totalCount`.",
        "Following it means any Relay-compatible client works out of the box, and your pagination shape is predictable across the whole schema. The cost is verbosity — clients must navigate `edges[0].node` instead of a flat array.",
        "For non-Relay clients (Apollo, URQL, custom fetches), a simpler shape `{ data: [...], pagination: { hasNextPage, endCursor } }` is usually cleaner. Choose Relay spec when you use the Relay client or want maximum interoperability.",
      ].join("\n\n"),
      callout:
        "Use Relay spec for Relay clients or ecosystem compatibility. Use a simpler shape for everything else.",
    },
  ],
  bullets: [
    "Implement cursor pagination on `/posts`; insert a row mid-page and confirm no duplicates appear across page boundaries.",
    "Write a `posts.proto` with one unary and one server-streaming RPC; generate Go or Node stubs and make a real call.",
    "Before Day 5: explain the token bucket algorithm, the difference between AuthN and AuthZ, and why idempotency keys need a per-user scope.",
  ],
} satisfies RoadmapDayDetail;
