export type DuolingoExample = {
  ja: string;
  en: string;
  np: string;
};

export type DuolingoWord = {
  word: string;
  reading?: string;
  meaning_en: string;
  meaning_np: string;
  examples: DuolingoExample[];
};

export type DuolingoDay = {
  day: number;
  words: DuolingoWord[];
};

export const DUOLINGO_DAYS: DuolingoDay[] = [
  {
    day: 1,
    words: [
      {
        word: "ホーム",
        meaning_en: "Platform",
        meaning_np: "प्लेटफर्म",
        examples: [{ ja: "ホームはあそこです。", en: "The platform is over there.", np: "प्लेटफर्म त्यहाँ छ।" }],
      },
      {
        word: "改札口",
        reading: "かいさつぐち",
        meaning_en: "Ticket gate",
        meaning_np: "टिकट गेट",
        examples: [{ ja: "改札口は一階です。", en: "The ticket gate is on the first floor.", np: "टिकट गेट पहिलो तलामा छ।" }],
      },
      {
        word: "終点",
        reading: "しゅうてん",
        meaning_en: "Final stop",
        meaning_np: "अन्तिम स्टप",
        examples: [{ ja: "ここは終点ですか。", en: "Is this the final stop?", np: "यो अन्तिम स्टप हो?" }],
      },
      {
        word: "上野公園",
        reading: "うえのこうえん",
        meaning_en: "Ueno Park",
        meaning_np: "उएनो पार्क",
        examples: [{ ja: "上野公園はいいです。", en: "Ueno Park is nice.", np: "उएनो पार्क राम्रो छ।" }],
      },
      {
        word: "浅草",
        reading: "あさくさ",
        meaning_en: "Asakusa (place name)",
        meaning_np: "असाकुसा",
        examples: [{ ja: "浅草はにぎやかです。", en: "Asakusa is lively.", np: "असाकुसा賑やか छ।" }],
      },
      {
        word: "えっと、紅茶を四つください",
        reading: "えっと、こうちゃをよっつください",
        meaning_en: "Um, four black teas, please",
        meaning_np: "उम, चार कालो चिया दिनुहोस्",
        examples: [{ ja: "えっと、紅茶を四つください。", en: "Um, four black teas, please.", np: "उम, चार कालो चिया दिनुहोस्।" }],
      },
      {
        word: "電子レンジ",
        reading: "でんしレンジ",
        meaning_en: "Microwave",
        meaning_np: "माइक्रोवेभ",
        examples: [{ ja: "まだ電子レンジはありません。", en: "I still don't have a microwave.", np: "अझै माइक्रोवेभ छैन।" }],
      },
      {
        word: "たぶん",
        meaning_en: "Probably",
        meaning_np: "सायद",
        examples: [{ ja: "たぶんベッドを買います。", en: "I will probably buy a bed.", np: "सायद बेड किन्छु।" }],
      },
    ],
  },
  {
    day: 2,
    words: [
      {
        word: "新しい掃除機があります",
        reading: "あたらしいそうじきがあります",
        meaning_en: "I have a new vacuum cleaner",
        meaning_np: "मसँग नयाँ भ्याकुम क्लिनर छ",
        examples: [{ ja: "新しい掃除機があります。べんりです。", en: "I have a new vacuum cleaner. It's convenient.", np: "मसँग नयाँ भ्याकुम क्लिनर छ। सुविधाजनक छ।" }],
      },
      {
        word: "リビング",
        meaning_en: "Living room",
        meaning_np: "बस्ने कोठा",
        examples: [{ ja: "リビングはどうですか。", en: "How's the living room?", np: "बस्ने कोठा कस्तो छ?" }],
      },
      {
        word: "明るい",
        reading: "あかるい",
        meaning_en: "Well-lit, bright",
        meaning_np: "उज्यालो",
        examples: [{ ja: "とても明るいです。", en: "It's very well lit.", np: "धेरै उज्यालो छ।" }],
      },
      {
        word: "キッチン",
        meaning_en: "Kitchen",
        meaning_np: "भान्साकोठा",
        examples: [{ ja: "キッチンはせまいですが、きれいです。", en: "The kitchen is small but clean.", np: "भान्साकोठा सानो छ तर सफा छ।" }],
      },
      {
        word: "自販機",
        reading: "じはんき",
        meaning_en: "Vending machine",
        meaning_np: "भेन्डिङ मेसिन",
        examples: [{ ja: "自販機でジュースを買います。", en: "I buy juice from the vending machine.", np: "भेन्डिङ मेसिनबाट जुस किन्छु।" }],
      },
      {
        word: "ロマンスドラマ",
        meaning_en: "Romance drama",
        meaning_np: "रोमान्स नाटक",
        examples: [{ ja: "ロマンスドラマがまあまあです。", en: "Romance dramas are so-so.", np: "रोमान्स नाटक ठीकठाक छ।" }],
      },
      {
        word: "コメディ",
        meaning_en: "Comedy",
        meaning_np: "कमेडी",
        examples: [{ ja: "コメディはちょっと。", en: "I don't really like comedies.", np: "कमेडी त्यति मन पर्दैन।" }],
      },
      {
        word: "ファンタジー",
        meaning_en: "Fantasy",
        meaning_np: "फ्यान्टासी",
        examples: [{ ja: "ファンタジー映画が好きです。", en: "I like fantasy movies.", np: "फ्यान्टासी चलचित्र मन पर्छ।" }],
      },
      {
        word: "ホラー",
        meaning_en: "Horror",
        meaning_np: "हरर",
        examples: [{ ja: "ホラーはこわいです。", en: "Horror is scary.", np: "हरर डरलाग्दो हुन्छ।" }],
      },
      {
        word: "ミステリ",
        meaning_en: "Mystery",
        meaning_np: "मिस्ट्री",
        examples: [{ ja: "ミステリが好きです。", en: "I like mystery.", np: "मिस्ट्री मन पर्छ।" }],
      },
      {
        word: "バレーボール",
        meaning_en: "Volleyball",
        meaning_np: "भलिबल",
        examples: [{ ja: "バレーボールをします。", en: "I play volleyball.", np: "म भलिबल खेल्छु।" }],
      },
      {
        word: "カフェ",
        meaning_en: "Cafe",
        meaning_np: "क्याफे",
        examples: [{ ja: "カフェでコーヒーを飲みます。", en: "I drink coffee at a cafe.", np: "क्याफेमा कफी पिउँछु।" }],
      },
    ],
  },
  {
    day: 3,
    words: [
      {
        word: "コインロッカー",
        meaning_en: "Storage lockers",
        meaning_np: "सामान राख्ने लकर",
        examples: [{ ja: "コインロッカーはありません。", en: "There are no storage lockers.", np: "यहाँ लकर छैन।" }],
      },
      {
        word: "コンセント",
        meaning_en: "Outlet / socket",
        meaning_np: "बिजुली सकेट",
        examples: [{ ja: "コンセントはどこですか。", en: "Where is the outlet?", np: "बिजुली सकेट कहाँ छ?" }],
      },
      {
        word: "地下",
        reading: "ちか",
        meaning_en: "Underground level",
        meaning_np: "भुइँतल",
        examples: [{ ja: "ATMは地下です。", en: "The ATM is underground.", np: "ATM भुइँतलामा छ।" }],
      },
      {
        word: "お手洗い",
        reading: "おてあらい",
        meaning_en: "Restroom",
        meaning_np: "शौचालय",
        examples: [{ ja: "お手洗いはどこですか。", en: "Where is the restroom?", np: "शौचालय कहाँ छ?" }],
      },
      {
        word: "動画",
        reading: "どうが",
        meaning_en: "Videos",
        meaning_np: "भिडियो",
        examples: [{ ja: "おもしろい動画を見ます。", en: "I watch funny videos.", np: "म रमाइलो भिडियो हेर्छु।" }],
      },
      {
        word: "晴れ",
        reading: "はれ",
        meaning_en: "Sunny",
        meaning_np: "घाम लागेको",
        examples: [{ ja: "きょうは晴れです。", en: "Today is sunny.", np: "आज घाम लागेको छ।" }],
      },
      {
        word: "大好き",
        reading: "だいすき",
        meaning_en: "Love, to love",
        meaning_np: "धेरै मन पर्नु",
        examples: [{ ja: "ケーキが大好きです。", en: "I love cake.", np: "मलाई केक धेरै मन पर्छ।" }],
      },
      {
        word: "ちゃんと",
        meaning_en: "Make sure / properly",
        meaning_np: "राम्ररी / ध्यानपूर्वक",
        examples: [{ ja: "ちゃんと昼ごはんも食べよう。", en: "Make sure to eat lunch too.", np: "दिउँसोको खाना पनि राम्ररी खाऊ।" }],
      },
    ],
  },
  {
    day: 4,
    words: [
      {
        word: "はたらく",
        meaning_en: "To work",
        meaning_np: "काम गर्नु",
        examples: [{ ja: "まいにちはたらきます。", en: "I work every day.", np: "म हरेक दिन काम गर्छु।" }],
      },
      {
        word: "丸",
        reading: "まる",
        meaning_en: "Circle",
        meaning_np: "गोलो",
        examples: [{ ja: "でかい大きな円を描いて。", en: "Draw a big circle.", np: "ठूलो गोलो कोर्नुहोस्।" }],
      },
      {
        word: "ヘッド",
        meaning_en: "Cleaning head (of a vacuum)",
        meaning_np: "मेसिनको टाउको",
        examples: [{ ja: "ヘッドをかえます。", en: "I replace the head.", np: "टाउको बदल्छु।" }],
      },
      {
        word: "ハンドル",
        meaning_en: "Handle",
        meaning_np: "समाउने भाग",
        examples: [{ ja: "ハンドルをもちます。", en: "I hold the handle.", np: "ह्यान्डल समाउँछु।" }],
      },
      {
        word: "たまりだす",
        meaning_en: "To start accumulating",
        meaning_np: "जम्मा हुन थाल्नु",
        examples: [{ ja: "ゴミがたまりだします。", en: "Garbage starts accumulating.", np: "फोहोर जम्मा हुन थाल्छ।" }],
      },
      {
        word: "角",
        reading: "かど",
        meaning_en: "Corner",
        meaning_np: "कुना",
        examples: [{ ja: "角をそうじします。", en: "I clean the corner.", np: "कुना सफा गर्छु।" }],
      },
      {
        word: "モップ",
        meaning_en: "Mop",
        meaning_np: "पोछा",
        examples: [{ ja: "モップでゆかをそうじします。", en: "I clean the floor with a mop.", np: "पोछाले भुइँ सफा गर्छु।" }],
      },
      {
        word: "ラグ",
        meaning_en: "Rag / floor cloth",
        meaning_np: "कपडा",
        examples: [{ ja: "ラグでふきます。", en: "I wipe with a rag.", np: "कपडाले पुछ्छु।" }],
      },
      {
        word: "交換する",
        reading: "こうかんする",
        meaning_en: "To replace / swap",
        meaning_np: "बदल्नु / परिवर्तन गर्नु",
        examples: [{ ja: "フィルターを交換します。", en: "I replace the filter.", np: "फिल्टर बदल्छु।" }],
      },
      {
        word: "吸い込む",
        reading: "すいこむ",
        meaning_en: "To suck in (air/dust)",
        meaning_np: "तान्नु",
        examples: [{ ja: "そうじきがほこりを吸い込みます。", en: "The vacuum sucks in dust.", np: "भ्याकुमले धुलो तान्छ।" }],
      },
      {
        word: "乾く",
        reading: "かわく",
        meaning_en: "To dry",
        meaning_np: "सुक्नु",
        examples: [{ ja: "タオルがかわきます。", en: "The towel dries.", np: "तौलिया सुक्छ।" }],
      },
      {
        word: "拭き掃除",
        reading: "ふきそうじ",
        meaning_en: "Wiping clean with a wet cloth",
        meaning_np: "भिजेको कपडाले पुछ्नु",
        examples: [{ ja: "まいにち拭き掃除をします。", en: "I do wet-cloth cleaning every day.", np: "हरेक दिन भिजेको कपडाले पुछ्छु।" }],
      },
      {
        word: "乾拭き",
        reading: "からぶき",
        meaning_en: "Dry wiping",
        meaning_np: "सुख्खा पुछाइ",
        examples: [{ ja: "乾拭きでかがみをみがきます。", en: "I polish the mirror with dry wiping.", np: "सुख्खा कपडाले ऐना चम्काउँछु।" }],
      },
      {
        word: "便器",
        reading: "べんき",
        meaning_en: "Toilet bowl",
        meaning_np: "कमोड",
        examples: [{ ja: "便器をそうじします。", en: "I clean the toilet bowl.", np: "कमोड सफा गर्छु।" }],
      },
      {
        word: "手洗い台",
        reading: "てあらいだい",
        meaning_en: "Handwash basin",
        meaning_np: "हातमुख धुने बेसिन",
        examples: [{ ja: "手洗い台をふきます。", en: "I wipe the handwash basin.", np: "बेसिन पुछ्छु।" }],
      },
      {
        word: "蛇口",
        reading: "じゃぐち",
        meaning_en: "Tap / faucet",
        meaning_np: "धारो",
        examples: [{ ja: "蛇口からみずがでます。", en: "Water comes from the faucet.", np: "धाराबाट पानी आउँछ।" }],
      },
      {
        word: "人感センサー",
        reading: "じんかんセンサー",
        meaning_en: "Human presence sensor",
        meaning_np: "मानव उपस्थिति सेन्सर",
        examples: [{ ja: "人感センサーでライトがつきます。", en: "The light turns on with the motion sensor.", np: "सेन्सरले बत्ती बाल्छ।" }],
      },
      {
        word: "流す",
        reading: "ながす",
        meaning_en: "To flush / wash away",
        meaning_np: "बगाउनु",
        examples: [{ ja: "トイレをながします。", en: "I flush the toilet.", np: "टाइलेट फ्लस गर्छु।" }],
      },
    ],
  },
  {
    day: 5,
    words: [
      {
        word: "家事",
        reading: "かじ",
        meaning_en: "Housework",
        meaning_np: "घरको काम",
        examples: [{ ja: "家事はたいへんです。", en: "Housework is tough.", np: "घरको काम गाह्रो छ।" }],
      },
      {
        word: "はじめてです",
        meaning_en: "It's my first time",
        meaning_np: "पहिलो पटक हो",
        examples: [{ ja: "このりょうりははじめてです。", en: "This is my first time with this dish.", np: "यो खाना पहिलो पटक खाँदैछु।" }],
      },
      {
        word: "おすすめは何ですか",
        reading: "おすすめはなんですか",
        meaning_en: "What do you recommend?",
        meaning_np: "के सुझाव दिनुहुन्छ?",
        examples: [{ ja: "このみせのおすすめは何ですか。", en: "What do you recommend at this shop?", np: "यस पसलमा के सुझाव दिनुहुन्छ?" }],
      },
      {
        word: "カードで払いですか",
        reading: "カードではらいですか",
        meaning_en: "Can I pay by card?",
        meaning_np: "कार्डले तिर्न सकिन्छ?",
        examples: [{ ja: "カードで払いですか。げんきんだけですか。", en: "Can I pay by card, or is it cash only?", np: "कार्डले तिर्न सकिन्छ, या नगद मात्र?" }],
      },
      {
        word: "もう一度おねがいします",
        reading: "もういちどおねがいします",
        meaning_en: "One more time, please",
        meaning_np: "एकपटक फेरि गर्नुहोस्",
        examples: [{ ja: "すみません、もう一度おねがいします。", en: "Excuse me, one more time please.", np: "माफ गर्नुस्, एकपटक फेरि भन्नुहोस्।" }],
      },
      {
        word: "やばくない？",
        meaning_en: "Isn't that crazy?",
        meaning_np: "अचम्मको होइन?",
        examples: [{ ja: "このねだん、やばくない？", en: "Isn't this price crazy?", np: "यो मूल्य अचम्मको होइन?" }],
      },
      {
        word: "信じられない",
        reading: "しんじられない",
        meaning_en: "I can't believe it",
        meaning_np: "विश्वास गर्न सकिन्न",
        examples: [{ ja: "そんなはなし、信じられない。", en: "I can't believe such a story.", np: "त्यस्तो कुरा विश्वास गर्न सकिन्न।" }],
      },
      {
        word: "嘘でしょ？",
        reading: "うそでしょ？",
        meaning_en: "Are you kidding me?",
        meaning_np: "झुट होइन?",
        examples: [{ ja: "嘘でしょ？ほんとうに？", en: "Are you kidding? Really?", np: "झुट होइन? साँच्चिकै?" }],
      },
      {
        word: "ありえない！",
        meaning_en: "No way!",
        meaning_np: "हुनै सक्दैन!",
        examples: [{ ja: "あのねだんはありえない！", en: "That price is unbelievable!", np: "त्यो मूल्य हुनै सक्दैन!" }],
      },
      {
        word: "え、マジで",
        meaning_en: "Wait, seriously?",
        meaning_np: "के साँच्चिकै?",
        examples: [{ ja: "え、マジで？やばい！", en: "Wait, seriously? That's crazy!", np: "के साँच्चिकै? अचम्म!" }],
      },
      {
        word: "ほっといてください",
        meaning_en: "Leave me alone",
        meaning_np: "मलाई एक्लै छोड्नुहोस्",
        examples: [{ ja: "おねがいですからほっといてください。", en: "Please leave me alone.", np: "कृपया मलाई एक्लै छोड्नुहोस्।" }],
      },
      {
        word: "お持ち帰りできますか",
        reading: "おもちかえりできますか",
        meaning_en: "Can I take this to go?",
        meaning_np: "यो लिएर जान सकिन्छ?",
        examples: [{ ja: "このケーキ、お持ち帰りできますか。", en: "Can I take this cake to go?", np: "यो केक लिएर जान सकिन्छ?" }],
      },
      {
        word: "お会計おねがいします",
        reading: "おかいけいおねがいします",
        meaning_en: "Can I get the bill, please?",
        meaning_np: "बिल दिनुहोस् न",
        examples: [{ ja: "すみません、お会計おねがいします。", en: "Excuse me, can I get the bill?", np: "माफ गर्नुस्, बिल दिनुहोस् न।" }],
      },
    ],
  },
  {
    day: 6,
    words: [
      {
        word: "どんな感じになりましたか",
        reading: "どんなかんじになりましたか",
        meaning_en: "How did it turn out?",
        meaning_np: "कस्तो भयो?",
        examples: [{ ja: "ヘアカットはどんな感じになりましたか。", en: "How did the haircut turn out?", np: "कपाल काट्दा कस्तो भयो?" }],
      },
      {
        word: "まあまあでおきました",
        meaning_en: "It turned out okay",
        meaning_np: "ठीकठाक भयो",
        examples: [{ ja: "てんきはまあまあでおきました。", en: "The weather turned out okay.", np: "मौसम ठीकठाक भयो।" }],
      },
      {
        word: "彼女のことを心配しています",
        reading: "かのじょのことをしんぱいしています",
        meaning_en: "I worry about her",
        meaning_np: "म उनको बारेमा चिन्तित छु",
        examples: [{ ja: "かれしが彼女のことを心配しています。", en: "Her boyfriend worries about her.", np: "उनको प्रेमी उनको बारेमा चिन्तित छन्।" }],
      },
      {
        word: "町で会いました",
        reading: "まちであいました",
        meaning_en: "Met in town",
        meaning_np: "सहरमा भेट भयो",
        examples: [{ ja: "ともだちに町で会いました。", en: "I met my friend in town.", np: "सहरमा साथीसँग भेट भयो।" }],
      },
      {
        word: "スマホの電池が切れそうです",
        reading: "スマホのでんちがきれそうです",
        meaning_en: "Phone battery is about to die",
        meaning_np: "मोबाइलको ब्याट्री सकिन लाग्यो",
        examples: [{ ja: "もうすぐスマホの電池が切れそうです。", en: "My phone battery is about to die soon.", np: "अब छिट्टै मोबाइलको ब्याट्री सकिन्छ।" }],
      },
      {
        word: "ちょっと待ってください",
        reading: "ちょっとまってください",
        meaning_en: "Wait a sec",
        meaning_np: "अलिकति पर्खनुहोस्",
        examples: [{ ja: "ちょっと待ってください、すぐいきます。", en: "Wait a sec, I'll be right there.", np: "अलिकति पर्खनुहोस्, अहिलै आउँछु।" }],
      },
    ],
  },
  {
    day: 7,
    words: [
      {
        word: "紹介します",
        reading: "しょうかいします",
        meaning_en: "To introduce",
        meaning_np: "परिचय गर्नु",
        examples: [{ ja: "ともだちをしょうかいします。", en: "I will introduce my friend.", np: "साथीको परिचय गराउँछु।" }],
      },
      {
        word: "案内します",
        reading: "あんないします",
        meaning_en: "To guide, show around",
        meaning_np: "गाइड गर्नु",
        examples: [{ ja: "まちをあんないします。", en: "I will show you around town.", np: "सहर घुमाउँछु।" }],
      },
      {
        word: "説明します",
        reading: "せつめいします",
        meaning_en: "To explain",
        meaning_np: "व्याख्या गर्नु",
        examples: [{ ja: "りゆうをせつめいします。", en: "I will explain the reason.", np: "कारण व्याख्या गर्छु।" }],
      },
      {
        word: "調べます",
        reading: "しらべます",
        meaning_en: "To check, investigate",
        meaning_np: "अनुसन्धान गर्नु",
        examples: [{ ja: "インターネットでしらべます。", en: "I will look it up on the internet.", np: "इन्टरनेटमा खोज्छु।" }],
      },
      {
        word: "弱い",
        reading: "よわい",
        meaning_en: "Weak",
        meaning_np: "कमजोर",
        examples: [{ ja: "わたしはからだがよわいです。", en: "I have a weak body.", np: "मेरो शरीर कमजोर छ।" }],
      },
      {
        word: "交番",
        reading: "こうばん",
        meaning_en: "Police box",
        meaning_np: "प्रहरी बक्स",
        examples: [{ ja: "交番でちずをもらいました。", en: "I got a map at the police box.", np: "प्रहरी बक्सबाट नक्सा पाएँ।" }],
      },
      {
        word: "計画",
        reading: "けいかく",
        meaning_en: "Plan",
        meaning_np: "योजना",
        examples: [{ ja: "りょこうのけいかくをたてます。", en: "I make a travel plan.", np: "यात्राको योजना बनाउँछु।" }],
      },
      {
        word: "お知らせ",
        reading: "おしらせ",
        meaning_en: "Notice / announcement",
        meaning_np: "सूचना",
        examples: [{ ja: "がっこうのおしらせをよみます。", en: "I read the school announcement.", np: "विद्यालयको सूचना पढ्छु।" }],
      },
      {
        word: "スケジュール",
        meaning_en: "Schedule",
        meaning_np: "तालिका",
        examples: [{ ja: "スケジュールをかくにんします。", en: "I check the schedule.", np: "तालिका जाँच्छु।" }],
      },
      {
        word: "相談します",
        reading: "そうだんします",
        meaning_en: "To consult, discuss",
        meaning_np: "परामर्श गर्नु",
        examples: [{ ja: "せんせいにそうだんします。", en: "I will consult with my teacher.", np: "शिक्षकसँग परामर्श गर्छु।" }],
      },
      {
        word: "決めます",
        reading: "きめます",
        meaning_en: "To decide",
        meaning_np: "निर्णय गर्नु",
        examples: [{ ja: "じかんをきめます。", en: "I will decide the time.", np: "समय निर्णय गर्छु।" }],
      },
      {
        word: "集めます／まとめます",
        reading: "あつめます／まとめます",
        meaning_en: "To gather / collect",
        meaning_np: "जम्मा गर्नु",
        examples: [{ ja: "じょうほうをあつめます。", en: "I gather information.", np: "जानकारी जम्मा गर्छु।" }],
      },
      {
        word: "戻ります",
        reading: "もどります",
        meaning_en: "To go back, return",
        meaning_np: "फर्कनु",
        examples: [{ ja: "3じにもどります。", en: "I will return at 3 o'clock.", np: "३ बजे फर्कन्छु।" }],
      },
      {
        word: "出発します",
        reading: "しゅっぱつします",
        meaning_en: "To depart",
        meaning_np: "प्रस्थान गर्नु",
        examples: [{ ja: "あさ8じにしゅっぱつします。", en: "I depart at 8 in the morning.", np: "बिहान ८ बजे प्रस्थान गर्छु।" }],
      },
      {
        word: "到着します",
        reading: "とうちゃくします",
        meaning_en: "To arrive",
        meaning_np: "आइपुग्नु",
        examples: [{ ja: "えきにとうちゃくします。", en: "I arrive at the station.", np: "स्टेसनमा पुग्छु।" }],
      },
      {
        word: "ただいま",
        meaning_en: "I'm home",
        meaning_np: "म आएँ",
        examples: [{ ja: "ただいま！おかえり。", en: "I'm home! Welcome back.", np: "म आएँ! स्वागत छ।" }],
      },
    ],
  },
  {
    day: 8,
    words: [
      {
        word: "発音",
        reading: "はつおん",
        meaning_en: "Pronunciation",
        meaning_np: "उच्चारण",
        examples: [{ ja: "にほんごのはつおんはむずかしいです。", en: "Japanese pronunciation is difficult.", np: "जापानी भाषाको उच्चारण गाह्रो छ।" }],
      },
      {
        word: "もうしわけありません",
        meaning_en: "I am very sorry / Please excuse me",
        meaning_np: "म माफी माग्छु",
        examples: [{ ja: "もうしわけありません、おくれました。", en: "I'm very sorry, I'm late.", np: "म माफी माग्छु, ढिलो भयो।" }],
      },
      {
        word: "国連",
        reading: "こくれん",
        meaning_en: "United Nations",
        meaning_np: "संयुक्त राष्ट्र संघ",
        examples: [{ ja: "国連はニューヨークにあります。", en: "The United Nations is in New York.", np: "संयुक्त राष्ट्र संघ न्यू योर्कमा छ।" }],
      },
      {
        word: "調査",
        reading: "ちょうさ",
        meaning_en: "Investigation, survey",
        meaning_np: "अनुसन्धान",
        examples: [{ ja: "けいさつがちょうさをしています。", en: "The police are conducting an investigation.", np: "प्रहरीले अनुसन्धान गर्दैछ।" }],
      },
      {
        word: "収入",
        reading: "しゅうにゅう",
        meaning_en: "Income",
        meaning_np: "आय",
        examples: [{ ja: "しゅうにゅうがふえました。", en: "My income increased.", np: "मेरो आय बढ्यो।" }],
      },
      {
        word: "理由",
        reading: "りゆう",
        meaning_en: "Reason",
        meaning_np: "कारण",
        examples: [{ ja: "りゆうをおしえてください。", en: "Please tell me the reason.", np: "कारण बताइदिनुस्।" }],
      },
      {
        word: "基本的",
        reading: "きほんてき",
        meaning_en: "Standard, basic",
        meaning_np: "आधारभूत",
        examples: [{ ja: "これはきほんてきなルールです。", en: "This is a basic rule.", np: "यो आधारभूत नियम हो।" }],
      },
      {
        word: "つまらない",
        meaning_en: "Boring",
        meaning_np: "उबाउलो",
        examples: [{ ja: "このえいがはつまらないです。", en: "This movie is boring.", np: "यो चलचित्र उबाउलो छ।" }],
      },
      {
        word: "おかげさまで",
        meaning_en: "Thanks to you (set phrase)",
        meaning_np: "तपाईंको कृपाले",
        examples: [{ ja: "おかげさまで、げんきです。", en: "Thanks to you, I am well.", np: "तपाईंको कृपाले, म स्वस्थ छु।" }],
      },
      {
        word: "聞きましょう",
        reading: "ききましょう",
        meaning_en: "Let's ask / listen",
        meaning_np: "सोधौँ / सुनौँ",
        examples: [{ ja: "せんせいにききましょう。", en: "Let's ask the teacher.", np: "शिक्षकलाई सोधौँ।" }],
      },
      {
        word: "もっと",
        meaning_en: "More",
        meaning_np: "अझ बढी",
        examples: [{ ja: "もっと大きいのを買いましょう！", en: "Let's buy a bigger one!", np: "अझ ठूलो किनौँ!" }],
      },
      {
        word: "しょっぱい",
        meaning_en: "Salty",
        meaning_np: "नुनिलो",
        examples: [{ ja: "このスープはしょっぱいです。", en: "This soup is salty.", np: "यो सुप नुनिलो छ।" }],
      },
      {
        word: "コーラ",
        meaning_en: "Cola",
        meaning_np: "कोला",
        examples: [{ ja: "コーラをのみます。", en: "I drink cola.", np: "म कोला पिउँछु।" }],
      },
      {
        word: "とんかつ",
        meaning_en: "Pork cutlets",
        meaning_np: "सुँगुरको कटलेट",
        examples: [{ ja: "とんかつがすきです。", en: "I like pork cutlets.", np: "मलाई सुँगुरको कटलेट मन पर्छ।" }],
      },
      {
        word: "でも",
        meaning_en: "But, though, however",
        meaning_np: "तर",
        examples: [{ ja: "たかいです。でもおいしいです。", en: "It's expensive. But it's delicious.", np: "महँगो छ। तर मिठो छ।" }],
      },
      {
        word: "かっこいい",
        meaning_en: "Cool, stylish",
        meaning_np: "कुल / स्टाइलिश",
        examples: [{ ja: "あのひとはかっこいいです。", en: "That person is cool.", np: "त्यो मान्छे कुल छ।" }],
      },
      {
        word: "ライオン",
        meaning_en: "Lion",
        meaning_np: "सिंह",
        examples: [{ ja: "ライオンはどうぶつえんにいます。", en: "The lion is at the zoo.", np: "सिंह चिडियाखानामा छ।" }],
      },
      {
        word: "ガーデニング",
        meaning_en: "Gardening",
        meaning_np: "बगैँचा",
        examples: [{ ja: "まいにちガーデニングをします。", en: "I do gardening every day.", np: "म हरेक दिन बगैँचा गर्छु।" }],
      },
      {
        word: "料理",
        reading: "りょうり",
        meaning_en: "Cooking",
        meaning_np: "खाना पकाउनु",
        examples: [{ ja: "料理は楽しいです。", en: "Cooking is fun.", np: "खाना पकाउनु रमाइलो छ।" }],
      },
      {
        word: "ストレッチ",
        meaning_en: "Stretches",
        meaning_np: "स्ट्रेच",
        examples: [{ ja: "まいあさストレッチをします。", en: "I do stretches every morning.", np: "म हरेक बिहान स्ट्रेच गर्छु।" }],
      },
    ],
  },
  {
    day: 9,
    words: [
      {
        word: "パレード",
        meaning_en: "Parade",
        meaning_np: "परेड",
        examples: [{ ja: "パレードに行きませんか。", en: "Would you like to go to the parade?", np: "के तपाई परेडमा जानुहुन्छ?" }],
      },
      {
        word: "今週末",
        reading: "こんしゅうまつ",
        meaning_en: "This weekend",
        meaning_np: "यो हप्ताको अन्त",
        examples: [{ ja: "今週末、何をしますか。", en: "What are you doing this weekend?", np: "यो हप्ताको अन्तमा के गर्नुहुन्छ?" }],
      },
      {
        word: "太鼓のパフォーマンス",
        reading: "たいこのパフォーマンス",
        meaning_en: "Taiko drum performance",
        meaning_np: "ताइको ढोलको प्रदर्शन",
        examples: [{ ja: "えきで太鼓のパフォーマンスがあります。", en: "There's a taiko drum performance at the station.", np: "स्टेसनमा ताइको ढोलको प्रदर्शन छ।" }],
      },
      {
        word: "花火大会",
        reading: "はなびたいかい",
        meaning_en: "Fireworks display",
        meaning_np: "आतिशबाजी",
        examples: [{ ja: "花火大会に行きませんか。", en: "Would you like to go to the fireworks display?", np: "के तपाई आतिशबाजीमा जानुहुन्छ?" }],
      },
      {
        word: "ハロウィン",
        meaning_en: "Halloween",
        meaning_np: "हेलोउइन",
        examples: [{ ja: "ハロウィンのパーティーがあります。", en: "There's a Halloween party.", np: "हेलोउइनको पार्टी छ।" }],
      },
      {
        word: "ドキュメンタリー",
        meaning_en: "Documentary",
        meaning_np: "डकुमेन्टरी",
        examples: [{ ja: "ドキュメンタリーはすきですか。", en: "Do you like documentaries?", np: "तपाईलाई डकुमेन्टरी मन पर्छ?" }],
      },
      {
        word: "大晦日",
        reading: "おおみそか",
        meaning_en: "New Year's Eve",
        meaning_np: "नयाँ वर्षको पूर्वसन्ध्या",
        examples: [{ ja: "大晦日に何をしますか。", en: "What do you do on New Year's Eve?", np: "नयाँ वर्षको पूर्वसन्ध्यामा के गर्नुहुन्छ?" }],
      },
      {
        word: "テーマパーク",
        meaning_en: "Theme park",
        meaning_np: "थिम पार्क",
        examples: [{ ja: "テーマパークに行きませんか。", en: "Would you like to go to a theme park?", np: "के तपाई थिम पार्क जानुहुन्छ?" }],
      },
      {
        word: "チョコバナナ",
        meaning_en: "Chocolate-covered banana",
        meaning_np: "चकलेट केरा",
        examples: [{ ja: "チョコバナナをください。", en: "A chocolate-covered banana, please.", np: "एउटा चकलेट केरा दिनुहोस्।" }],
      },
      {
        word: "俳優",
        reading: "はいゆう",
        meaning_en: "Actor",
        meaning_np: "अभिनेता",
        examples: [{ ja: "ゆうめいな俳優です。", en: "They are a famous actor.", np: "उनी प्रसिद्ध अभिनेता हुन्।" }],
      },
      {
        word: "ポスター",
        meaning_en: "Poster",
        meaning_np: "पोस्टर",
        examples: [{ ja: "ポスターはいくらですか。", en: "How much is the poster?", np: "पोस्टर कति पर्छ?" }],
      },
      {
        word: "RPG",
        meaning_en: "Role-playing game",
        meaning_np: "रोल-प्लेइङ गेम",
        examples: [{ ja: "RPGはすきです。", en: "I like role-playing games.", np: "मलाई RPG मन पर्छ।" }],
      },
      {
        word: "SF",
        meaning_en: "Science fiction",
        meaning_np: "साइन्स फिक्सन",
        examples: [{ ja: "SFを見ます。", en: "I watch science fiction.", np: "म SF हेर्छु।" }],
      },
      {
        word: "ポップス",
        meaning_en: "Pop music",
        meaning_np: "पप संगीत",
        examples: [{ ja: "ポップスをききます。", en: "I listen to pop music.", np: "म पप संगीत सुन्छु।" }],
      },
      {
        word: "カードゲーム",
        meaning_en: "Card game",
        meaning_np: "कार्ड गेम",
        examples: [{ ja: "カードゲームをしましょう。", en: "Let's play card games.", np: "कार्ड गेम खेलौँ।" }],
      },
      {
        word: "パズル",
        meaning_en: "Puzzle",
        meaning_np: "पजल",
        examples: [{ ja: "パズルをしましょう。", en: "Let's do a puzzle.", np: "पजल गरौँ।" }],
      },
      {
        word: "アニソン",
        meaning_en: "Anime music",
        meaning_np: "एनिमे संगीत",
        examples: [{ ja: "アニソンはすきです。", en: "I like anime music.", np: "मलाई एनिमे संगीत मन पर्छ।" }],
      },
    ],
  },
];
