export type DuolingoExample = {
  ja: string;
  en: string;
  np: string;
};

export type DuolingoWord = {
  word: string;
  romaji: string;
  reading?: string;
  meaning_en: string;
  meaning_np: string;
  examples: DuolingoExample[];
};

export type DuolingoDay = {
  day: number;
  category: string;
  words: DuolingoWord[];
};

export const DUOLINGO_DAYS: DuolingoDay[] = [
  {
    day: 1,
    category: "Transport & Stations",
    words: [
      {
        word: "ホーム",
        romaji: "hōmu",
        meaning_en: "Platform",
        meaning_np: "प्लेटफर्म",
        examples: [{ ja: "ホームはあそこです。", en: "The platform is over there.", np: "प्लेटफर्म त्यहाँ छ।" }],
      },
      {
        word: "改札口",
        romaji: "kaisatsuguchi",
        reading: "かいさつぐち",
        meaning_en: "Ticket gate",
        meaning_np: "टिकट गेट",
        examples: [{ ja: "改札口は一階です。", en: "The ticket gate is on the first floor.", np: "टिकट गेट पहिलो तलामा छ।" }],
      },
      {
        word: "終点",
        romaji: "shūten",
        reading: "しゅうてん",
        meaning_en: "Final stop",
        meaning_np: "अन्तिम स्टप",
        examples: [{ ja: "ここは終点ですか。", en: "Is this the final stop?", np: "यो अन्तिम स्टप हो?" }],
      },
      {
        word: "上野公園",
        romaji: "Ueno Kōen",
        reading: "うえのこうえん",
        meaning_en: "Ueno Park",
        meaning_np: "उएनो पार्क",
        examples: [{ ja: "上野公園はいいです。", en: "Ueno Park is nice.", np: "उएनो पार्क राम्रो छ।" }],
      },
      {
        word: "浅草",
        romaji: "Asakusa",
        reading: "あさくさ",
        meaning_en: "Asakusa (place name)",
        meaning_np: "असाकुसा",
        examples: [{ ja: "浅草はにぎやかです。", en: "Asakusa is lively.", np: "असाकुसा賑やか छ।" }],
      },
      {
        word: "えっと、紅茶を四つください",
        romaji: "etto, kōcha wo yottsu kudasai",
        reading: "えっと、こうちゃをよっつください",
        meaning_en: "Um, four black teas, please",
        meaning_np: "उम, चार कालो चिया दिनुहोस्",
        examples: [{ ja: "えっと、紅茶を四つください。", en: "Um, four black teas, please.", np: "उम, चार कालो चिया दिनुहोस्।" }],
      },
      {
        word: "電子レンジ",
        romaji: "denshi renji",
        reading: "でんしレンジ",
        meaning_en: "Microwave",
        meaning_np: "माइक्रोवेभ",
        examples: [{ ja: "まだ電子レンジはありません。", en: "I still don't have a microwave.", np: "अझै माइक्रोवेभ छैन।" }],
      },
      {
        word: "たぶん",
        romaji: "tabun",
        meaning_en: "Probably",
        meaning_np: "सायद",
        examples: [{ ja: "たぶんベッドを買います。", en: "I will probably buy a bed.", np: "सायद बेड किन्छु।" }],
      },
    ],
  },
  {
    day: 2,
    category: "Home & Entertainment",
    words: [
      {
        word: "新しい掃除機があります",
        romaji: "atarashii sōjiki ga arimasu",
        reading: "あたらしいそうじきがあります",
        meaning_en: "I have a new vacuum cleaner",
        meaning_np: "मसँग नयाँ भ्याकुम क्लिनर छ",
        examples: [{ ja: "新しい掃除機があります。べんりです。", en: "I have a new vacuum cleaner. It's convenient.", np: "मसँग नयाँ भ्याकुम क्लिनर छ। सुविधाजनक छ।" }],
      },
      {
        word: "リビング",
        romaji: "ribingu",
        meaning_en: "Living room",
        meaning_np: "बस्ने कोठा",
        examples: [{ ja: "リビングはどうですか。", en: "How's the living room?", np: "बस्ने कोठा कस्तो छ?" }],
      },
      {
        word: "明るい",
        romaji: "akarui",
        reading: "あかるい",
        meaning_en: "Well-lit, bright",
        meaning_np: "उज्यालो",
        examples: [{ ja: "とても明るいです。", en: "It's very well lit.", np: "धेरै उज्यालो छ।" }],
      },
      {
        word: "キッチン",
        romaji: "kitchin",
        meaning_en: "Kitchen",
        meaning_np: "भान्साकोठा",
        examples: [{ ja: "キッチンはせまいですが、きれいです。", en: "The kitchen is small but clean.", np: "भान्साकोठा सानो छ तर सफा छ।" }],
      },
      {
        word: "自販機",
        romaji: "jihanki",
        reading: "じはんき",
        meaning_en: "Vending machine",
        meaning_np: "भेन्डिङ मेसिन",
        examples: [{ ja: "自販機でジュースを買います。", en: "I buy juice from the vending machine.", np: "भेन्डिङ मेसिनबाट जुस किन्छु।" }],
      },
      {
        word: "ロマンスドラマ",
        romaji: "romansu dorama",
        meaning_en: "Romance drama",
        meaning_np: "रोमान्स नाटक",
        examples: [{ ja: "ロマンスドラマがまあまあです。", en: "Romance dramas are so-so.", np: "रोमान्स नाटक ठीकठाक छ।" }],
      },
      {
        word: "コメディ",
        romaji: "komedī",
        meaning_en: "Comedy",
        meaning_np: "कमेडी",
        examples: [{ ja: "コメディはちょっと。", en: "I don't really like comedies.", np: "कमेडी त्यति मन पर्दैन।" }],
      },
      {
        word: "ファンタジー",
        romaji: "fantajī",
        meaning_en: "Fantasy",
        meaning_np: "फ्यान्टासी",
        examples: [{ ja: "ファンタジー映画が好きです。", en: "I like fantasy movies.", np: "फ्यान्टासी चलचित्र मन पर्छ।" }],
      },
      {
        word: "ホラー",
        romaji: "horā",
        meaning_en: "Horror",
        meaning_np: "हरर",
        examples: [{ ja: "ホラーはこわいです。", en: "Horror is scary.", np: "हरर डरलाग्दो हुन्छ।" }],
      },
      {
        word: "ミステリ",
        romaji: "misuteri",
        meaning_en: "Mystery",
        meaning_np: "मिस्ट्री",
        examples: [{ ja: "ミステリが好きです。", en: "I like mystery.", np: "मिस्ट्री मन पर्छ।" }],
      },
      {
        word: "バレーボール",
        romaji: "barēbōru",
        meaning_en: "Volleyball",
        meaning_np: "भलिबल",
        examples: [{ ja: "バレーボールをします。", en: "I play volleyball.", np: "म भलिबल खेल्छु।" }],
      },
      {
        word: "カフェ",
        romaji: "kafe",
        meaning_en: "Cafe",
        meaning_np: "क्याफे",
        examples: [{ ja: "カフェでコーヒーを飲みます。", en: "I drink coffee at a cafe.", np: "क्याफेमा कफी पिउँछु।" }],
      },
    ],
  },
  {
    day: 3,
    category: "Facilities & Daily Life",
    words: [
      {
        word: "コインロッカー",
        romaji: "koin rokkā",
        meaning_en: "Storage lockers",
        meaning_np: "सामान राख्ने लकर",
        examples: [{ ja: "コインロッカーはありません。", en: "There are no storage lockers.", np: "यहाँ लकर छैन।" }],
      },
      {
        word: "コンセント",
        romaji: "konsento",
        meaning_en: "Outlet / socket",
        meaning_np: "बिजुली सकेट",
        examples: [{ ja: "コンセントはどこですか。", en: "Where is the outlet?", np: "बिजुली सकेट कहाँ छ?" }],
      },
      {
        word: "地下",
        romaji: "chika",
        reading: "ちか",
        meaning_en: "Underground level",
        meaning_np: "भुइँतल",
        examples: [{ ja: "ATMは地下です。", en: "The ATM is underground.", np: "ATM भुइँतलामा छ।" }],
      },
      {
        word: "お手洗い",
        romaji: "otearai",
        reading: "おてあらい",
        meaning_en: "Restroom",
        meaning_np: "शौचालय",
        examples: [{ ja: "お手洗いはどこですか。", en: "Where is the restroom?", np: "शौचालय कहाँ छ?" }],
      },
      {
        word: "動画",
        romaji: "dōga",
        reading: "どうが",
        meaning_en: "Videos",
        meaning_np: "भिडियो",
        examples: [{ ja: "おもしろい動画を見ます。", en: "I watch funny videos.", np: "म रमाइलो भिडियो हेर्छु।" }],
      },
      {
        word: "晴れ",
        romaji: "hare",
        reading: "はれ",
        meaning_en: "Sunny",
        meaning_np: "घाम लागेको",
        examples: [{ ja: "きょうは晴れです。", en: "Today is sunny.", np: "आज घाम लागेको छ।" }],
      },
      {
        word: "大好き",
        romaji: "daisuki",
        reading: "だいすき",
        meaning_en: "Love, to love",
        meaning_np: "धेरै मन पर्नु",
        examples: [{ ja: "ケーキが大好きです。", en: "I love cake.", np: "मलाई केक धेरै मन पर्छ।" }],
      },
      {
        word: "ちゃんと",
        romaji: "chanto",
        meaning_en: "Make sure / properly",
        meaning_np: "राम्ररी / ध्यानपूर्वक",
        examples: [{ ja: "ちゃんと昼ごはんも食べよう。", en: "Make sure to eat lunch too.", np: "दिउँसोको खाना पनि राम्ररी खाऊ।" }],
      },
    ],
  },
  {
    day: 4,
    category: "Cleaning & Household",
    words: [
      {
        word: "はたらく",
        romaji: "hataraku",
        meaning_en: "To work",
        meaning_np: "काम गर्नु",
        examples: [{ ja: "まいにちはたらきます。", en: "I work every day.", np: "म हरेक दिन काम गर्छु।" }],
      },
      {
        word: "丸",
        romaji: "maru",
        reading: "まる",
        meaning_en: "Circle",
        meaning_np: "गोलो",
        examples: [{ ja: "でかい大きな円を描いて。", en: "Draw a big circle.", np: "ठूलो गोलो कोर्नुहोस्।" }],
      },
      {
        word: "ヘッド",
        romaji: "heddo",
        meaning_en: "Cleaning head (of a vacuum)",
        meaning_np: "मेसिनको टाउको",
        examples: [{ ja: "ヘッドをかえます。", en: "I replace the head.", np: "टाउको बदल्छु।" }],
      },
      {
        word: "ハンドル",
        romaji: "handoru",
        meaning_en: "Handle",
        meaning_np: "समाउने भाग",
        examples: [{ ja: "ハンドルをもちます。", en: "I hold the handle.", np: "ह्यान्डल समाउँछु।" }],
      },
      {
        word: "たまりだす",
        romaji: "tamaridasu",
        meaning_en: "To start accumulating",
        meaning_np: "जम्मा हुन थाल्नु",
        examples: [{ ja: "ゴミがたまりだします。", en: "Garbage starts accumulating.", np: "फोहोर जम्मा हुन थाल्छ।" }],
      },
      {
        word: "角",
        romaji: "kado",
        reading: "かど",
        meaning_en: "Corner",
        meaning_np: "कुना",
        examples: [{ ja: "角をそうじします。", en: "I clean the corner.", np: "कुना सफा गर्छु।" }],
      },
      {
        word: "モップ",
        romaji: "moppu",
        meaning_en: "Mop",
        meaning_np: "पोछा",
        examples: [{ ja: "モップでゆかをそうじします。", en: "I clean the floor with a mop.", np: "पोछाले भुइँ सफा गर्छु।" }],
      },
      {
        word: "ラグ",
        romaji: "ragu",
        meaning_en: "Rag / floor cloth",
        meaning_np: "कपडा",
        examples: [{ ja: "ラグでふきます。", en: "I wipe with a rag.", np: "कपडाले पुछ्छु।" }],
      },
      {
        word: "交換する",
        romaji: "kōkan suru",
        reading: "こうかんする",
        meaning_en: "To replace / swap",
        meaning_np: "बदल्नु / परिवर्तन गर्नु",
        examples: [{ ja: "フィルターを交換します。", en: "I replace the filter.", np: "फिल्टर बदल्छु।" }],
      },
      {
        word: "吸い込む",
        romaji: "suikomu",
        reading: "すいこむ",
        meaning_en: "To suck in (air/dust)",
        meaning_np: "तान्नु",
        examples: [{ ja: "そうじきがほこりを吸い込みます。", en: "The vacuum sucks in dust.", np: "भ्याकुमले धुलो तान्छ।" }],
      },
      {
        word: "乾く",
        romaji: "kawaku",
        reading: "かわく",
        meaning_en: "To dry",
        meaning_np: "सुक्नु",
        examples: [{ ja: "タオルがかわきます。", en: "The towel dries.", np: "तौलिया सुक्छ।" }],
      },
      {
        word: "拭き掃除",
        romaji: "fuki sōji",
        reading: "ふきそうじ",
        meaning_en: "Wiping clean with a wet cloth",
        meaning_np: "भिजेको कपडाले पुछ्नु",
        examples: [{ ja: "まいにち拭き掃除をします。", en: "I do wet-cloth cleaning every day.", np: "हरेक दिन भिजेको कपडाले पुछ्छु।" }],
      },
      {
        word: "乾拭き",
        romaji: "karabuki",
        reading: "からぶき",
        meaning_en: "Dry wiping",
        meaning_np: "सुख्खा पुछाइ",
        examples: [{ ja: "乾拭きでかがみをみがきます。", en: "I polish the mirror with dry wiping.", np: "सुख्खा कपडाले ऐना चम्काउँछु।" }],
      },
      {
        word: "便器",
        romaji: "benki",
        reading: "べんき",
        meaning_en: "Toilet bowl",
        meaning_np: "कमोड",
        examples: [{ ja: "便器をそうじします。", en: "I clean the toilet bowl.", np: "कमोड सफा गर्छु।" }],
      },
      {
        word: "手洗い台",
        romaji: "tearaidai",
        reading: "てあらいだい",
        meaning_en: "Handwash basin",
        meaning_np: "हातमुख धुने बेसिन",
        examples: [{ ja: "手洗い台をふきます。", en: "I wipe the handwash basin.", np: "बेसिन पुछ्छु।" }],
      },
      {
        word: "蛇口",
        romaji: "jaguchi",
        reading: "じゃぐち",
        meaning_en: "Tap / faucet",
        meaning_np: "धारो",
        examples: [{ ja: "蛇口からみずがでます。", en: "Water comes from the faucet.", np: "धाराबाट पानी आउँछ।" }],
      },
      {
        word: "人感センサー",
        romaji: "jinkan sensā",
        reading: "じんかんセンサー",
        meaning_en: "Human presence sensor",
        meaning_np: "मानव उपस्थिति सेन्सर",
        examples: [{ ja: "人感センサーでライトがつきます。", en: "The light turns on with the motion sensor.", np: "सेन्सरले बत्ती बाल्छ।" }],
      },
      {
        word: "流す",
        romaji: "nagasu",
        reading: "ながす",
        meaning_en: "To flush / wash away",
        meaning_np: "बगाउनु",
        examples: [{ ja: "トイレをながします。", en: "I flush the toilet.", np: "टाइलेट फ्लस गर्छु।" }],
      },
    ],
  },
  {
    day: 5,
    category: "Phrases & Restaurant",
    words: [
      {
        word: "家事",
        romaji: "kaji",
        reading: "かじ",
        meaning_en: "Housework",
        meaning_np: "घरको काम",
        examples: [{ ja: "家事はたいへんです。", en: "Housework is tough.", np: "घरको काम गाह्रो छ।" }],
      },
      {
        word: "はじめてです",
        romaji: "hajimete desu",
        meaning_en: "It's my first time",
        meaning_np: "पहिलो पटक हो",
        examples: [{ ja: "このりょうりははじめてです。", en: "This is my first time with this dish.", np: "यो खाना पहिलो पटक खाँदैछु।" }],
      },
      {
        word: "おすすめは何ですか",
        romaji: "osusume wa nan desu ka",
        reading: "おすすめはなんですか",
        meaning_en: "What do you recommend?",
        meaning_np: "के सुझाव दिनुहुन्छ?",
        examples: [{ ja: "このみせのおすすめは何ですか。", en: "What do you recommend at this shop?", np: "यस पसलमा के सुझाव दिनुहुन्छ?" }],
      },
      {
        word: "カードで払いですか",
        romaji: "kādo de harai desu ka",
        reading: "カードではらいですか",
        meaning_en: "Can I pay by card?",
        meaning_np: "कार्डले तिर्न सकिन्छ?",
        examples: [{ ja: "カードで払いですか。げんきんだけですか。", en: "Can I pay by card, or is it cash only?", np: "कार्डले तिर्न सकिन्छ, या नगद मात्र?" }],
      },
      {
        word: "もう一度おねがいします",
        romaji: "mō ichido onegaishimasu",
        reading: "もういちどおねがいします",
        meaning_en: "One more time, please",
        meaning_np: "एकपटक फेरि गर्नुहोस्",
        examples: [{ ja: "すみません、もう一度おねがいします。", en: "Excuse me, one more time please.", np: "माफ गर्नुस्, एकपटक फेरि भन्नुहोस्।" }],
      },
      {
        word: "やばくない？",
        romaji: "yabaku nai?",
        meaning_en: "Isn't that crazy?",
        meaning_np: "अचम्मको होइन?",
        examples: [{ ja: "このねだん、やばくない？", en: "Isn't this price crazy?", np: "यो मूल्य अचम्मको होइन?" }],
      },
      {
        word: "信じられない",
        romaji: "shinjirarenai",
        reading: "しんじられない",
        meaning_en: "I can't believe it",
        meaning_np: "विश्वास गर्न सकिन्न",
        examples: [{ ja: "そんなはなし、信じられない。", en: "I can't believe such a story.", np: "त्यस्तो कुरा विश्वास गर्न सकिन्न।" }],
      },
      {
        word: "嘘でしょ？",
        romaji: "uso deshō?",
        reading: "うそでしょ？",
        meaning_en: "Are you kidding me?",
        meaning_np: "झुट होइन?",
        examples: [{ ja: "嘘でしょ？ほんとうに？", en: "Are you kidding? Really?", np: "झुट होइन? साँच्चिकै?" }],
      },
      {
        word: "ありえない！",
        romaji: "arienai!",
        meaning_en: "No way!",
        meaning_np: "हुनै सक्दैन!",
        examples: [{ ja: "あのねだんはありえない！", en: "That price is unbelievable!", np: "त्यो मूल्य हुनै सक्दैन!" }],
      },
      {
        word: "え、マジで",
        romaji: "e, maji de",
        meaning_en: "Wait, seriously?",
        meaning_np: "के साँच्चिकै?",
        examples: [{ ja: "え、マジで？やばい！", en: "Wait, seriously? That's crazy!", np: "के साँच्चिकै? अचम्म!" }],
      },
      {
        word: "ほっといてください",
        romaji: "hottoite kudasai",
        meaning_en: "Leave me alone",
        meaning_np: "मलाई एक्लै छोड्नुहोस्",
        examples: [{ ja: "おねがいですからほっといてください。", en: "Please leave me alone.", np: "कृपया मलाई एक्लै छोड्नुहोस्।" }],
      },
      {
        word: "お持ち帰りできますか",
        romaji: "omochi kaeri dekimasu ka",
        reading: "おもちかえりできますか",
        meaning_en: "Can I take this to go?",
        meaning_np: "यो लिएर जान सकिन्छ?",
        examples: [{ ja: "このケーキ、お持ち帰りできますか。", en: "Can I take this cake to go?", np: "यो केक लिएर जान सकिन्छ?" }],
      },
      {
        word: "お会計おねがいします",
        romaji: "okaikei onegaishimasu",
        reading: "おかいけいおねがいします",
        meaning_en: "Can I get the bill, please?",
        meaning_np: "बिल दिनुहोस् न",
        examples: [{ ja: "すみません、お会計おねがいします。", en: "Excuse me, can I get the bill?", np: "माफ गर्नुस्, बिल दिनुहोस् न।" }],
      },
    ],
  },
  {
    day: 6,
    category: "Expressions & Social",
    words: [
      {
        word: "どんな感じになりましたか",
        romaji: "donna kanji ni narimashita ka",
        reading: "どんなかんじになりましたか",
        meaning_en: "How did it turn out?",
        meaning_np: "कस्तो भयो?",
        examples: [{ ja: "ヘアカットはどんな感じになりましたか。", en: "How did the haircut turn out?", np: "कपाल काट्दा कस्तो भयो?" }],
      },
      {
        word: "まあまあでおきました",
        romaji: "māmā de okimashita",
        meaning_en: "It turned out okay",
        meaning_np: "ठीकठाक भयो",
        examples: [{ ja: "てんきはまあまあでおきました。", en: "The weather turned out okay.", np: "मौसम ठीकठाक भयो।" }],
      },
      {
        word: "彼女のことを心配しています",
        romaji: "kanojo no koto wo shinpai shite imasu",
        reading: "かのじょのことをしんぱいしています",
        meaning_en: "I worry about her",
        meaning_np: "म उनको बारेमा चिन्तित छु",
        examples: [{ ja: "かれしが彼女のことを心配しています。", en: "Her boyfriend worries about her.", np: "उनको प्रेमी उनको बारेमा चिन्तित छन्।" }],
      },
      {
        word: "町で会いました",
        romaji: "machi de aimashita",
        reading: "まちであいました",
        meaning_en: "Met in town",
        meaning_np: "सहरमा भेट भयो",
        examples: [{ ja: "ともだちに町で会いました。", en: "I met my friend in town.", np: "सहरमा साथीसँग भेट भयो।" }],
      },
      {
        word: "スマホの電池が切れそうです",
        romaji: "sumaho no denchi ga kiresō desu",
        reading: "スマホのでんちがきれそうです",
        meaning_en: "Phone battery is about to die",
        meaning_np: "मोबाइलको ब्याट्री सकिन लाग्यो",
        examples: [{ ja: "もうすぐスマホの電池が切れそうです。", en: "My phone battery is about to die soon.", np: "अब छिट्टै मोबाइलको ब्याट्री सकिन्छ।" }],
      },
      {
        word: "ちょっと待ってください",
        romaji: "chotto matte kudasai",
        reading: "ちょっとまってください",
        meaning_en: "Wait a sec",
        meaning_np: "अलिकति पर्खनुहोस्",
        examples: [{ ja: "ちょっと待ってください、すぐいきます。", en: "Wait a sec, I'll be right there.", np: "अलिकति पर्खनुहोस्, अहिलै आउँछु।" }],
      },
    ],
  },
  {
    day: 7,
    category: "Verbs & Navigation",
    words: [
      {
        word: "紹介します",
        romaji: "shōkai shimasu",
        reading: "しょうかいします",
        meaning_en: "To introduce",
        meaning_np: "परिचय गर्नु",
        examples: [{ ja: "ともだちをしょうかいします。", en: "I will introduce my friend.", np: "साथीको परिचय गराउँछु।" }],
      },
      {
        word: "案内します",
        romaji: "annai shimasu",
        reading: "あんないします",
        meaning_en: "To guide, show around",
        meaning_np: "गाइड गर्नु",
        examples: [{ ja: "まちをあんないします。", en: "I will show you around town.", np: "सहर घुमाउँछु।" }],
      },
      {
        word: "説明します",
        romaji: "setsumei shimasu",
        reading: "せつめいします",
        meaning_en: "To explain",
        meaning_np: "व्याख्या गर्नु",
        examples: [{ ja: "りゆうをせつめいします。", en: "I will explain the reason.", np: "कारण व्याख्या गर्छु।" }],
      },
      {
        word: "調べます",
        romaji: "shirabemasu",
        reading: "しらべます",
        meaning_en: "To check, investigate",
        meaning_np: "अनुसन्धान गर्नु",
        examples: [{ ja: "インターネットでしらべます。", en: "I will look it up on the internet.", np: "इन्टरनेटमा खोज्छु।" }],
      },
      {
        word: "弱い",
        romaji: "yowai",
        reading: "よわい",
        meaning_en: "Weak",
        meaning_np: "कमजोर",
        examples: [{ ja: "わたしはからだがよわいです。", en: "I have a weak body.", np: "मेरो शरीर कमजोर छ।" }],
      },
      {
        word: "交番",
        romaji: "kōban",
        reading: "こうばん",
        meaning_en: "Police box",
        meaning_np: "प्रहरी बक्स",
        examples: [{ ja: "交番でちずをもらいました。", en: "I got a map at the police box.", np: "प्रहरी बक्सबाट नक्सा पाएँ।" }],
      },
      {
        word: "計画",
        romaji: "keikaku",
        reading: "けいかく",
        meaning_en: "Plan",
        meaning_np: "योजना",
        examples: [{ ja: "りょこうのけいかくをたてます。", en: "I make a travel plan.", np: "यात्राको योजना बनाउँछु।" }],
      },
      {
        word: "お知らせ",
        romaji: "oshirase",
        reading: "おしらせ",
        meaning_en: "Notice / announcement",
        meaning_np: "सूचना",
        examples: [{ ja: "がっこうのおしらせをよみます。", en: "I read the school announcement.", np: "विद्यालयको सूचना पढ्छु।" }],
      },
      {
        word: "スケジュール",
        romaji: "sukejūru",
        meaning_en: "Schedule",
        meaning_np: "तालिका",
        examples: [{ ja: "スケジュールをかくにんします。", en: "I check the schedule.", np: "तालिका जाँच्छु।" }],
      },
      {
        word: "相談します",
        romaji: "sōdan shimasu",
        reading: "そうだんします",
        meaning_en: "To consult, discuss",
        meaning_np: "परामर्श गर्नु",
        examples: [{ ja: "せんせいにそうだんします。", en: "I will consult with my teacher.", np: "शिक्षकसँग परामर्श गर्छु।" }],
      },
      {
        word: "決めます",
        romaji: "kimemasu",
        reading: "きめます",
        meaning_en: "To decide",
        meaning_np: "निर्णय गर्नु",
        examples: [{ ja: "じかんをきめます。", en: "I will decide the time.", np: "समय निर्णय गर्छु।" }],
      },
      {
        word: "集めます／まとめます",
        romaji: "atsumemasu / matomemasu",
        reading: "あつめます／まとめます",
        meaning_en: "To gather / collect",
        meaning_np: "जम्मा गर्नु",
        examples: [{ ja: "じょうほうをあつめます。", en: "I gather information.", np: "जानकारी जम्मा गर्छु।" }],
      },
      {
        word: "戻ります",
        romaji: "modorimasu",
        reading: "もどります",
        meaning_en: "To go back, return",
        meaning_np: "फर्कनु",
        examples: [{ ja: "3じにもどります。", en: "I will return at 3 o'clock.", np: "३ बजे फर्कन्छु।" }],
      },
      {
        word: "出発します",
        romaji: "shuppatsu shimasu",
        reading: "しゅっぱつします",
        meaning_en: "To depart",
        meaning_np: "प्रस्थान गर्नु",
        examples: [{ ja: "あさ8じにしゅっぱつします。", en: "I depart at 8 in the morning.", np: "बिहान ८ बजे प्रस्थान गर्छु।" }],
      },
      {
        word: "到着します",
        romaji: "tōchaku shimasu",
        reading: "とうちゃくします",
        meaning_en: "To arrive",
        meaning_np: "आइपुग्नु",
        examples: [{ ja: "えきにとうちゃくします。", en: "I arrive at the station.", np: "स्टेसनमा पुग्छु।" }],
      },
      {
        word: "ただいま",
        romaji: "tadaima",
        meaning_en: "I'm home",
        meaning_np: "म आएँ",
        examples: [{ ja: "ただいま！おかえり。", en: "I'm home! Welcome back.", np: "म आएँ! स्वागत छ।" }],
      },
    ],
  },
  {
    day: 8,
    category: "Mixed Vocabulary",
    words: [
      {
        word: "発音",
        romaji: "hatsuon",
        reading: "はつおん",
        meaning_en: "Pronunciation",
        meaning_np: "उच्चारण",
        examples: [{ ja: "にほんごのはつおんはむずかしいです。", en: "Japanese pronunciation is difficult.", np: "जापानी भाषाको उच्चारण गाह्रो छ।" }],
      },
      {
        word: "もうしわけありません",
        romaji: "mōshiwake arimasen",
        meaning_en: "I am very sorry / Please excuse me",
        meaning_np: "म माफी माग्छु",
        examples: [{ ja: "もうしわけありません、おくれました。", en: "I'm very sorry, I'm late.", np: "म माफी माग्छु, ढिलो भयो।" }],
      },
      {
        word: "国連",
        romaji: "kokuren",
        reading: "こくれん",
        meaning_en: "United Nations",
        meaning_np: "संयुक्त राष्ट्र संघ",
        examples: [{ ja: "国連はニューヨークにあります。", en: "The United Nations is in New York.", np: "संयुक्त राष्ट्र संघ न्यू योर्कमा छ।" }],
      },
      {
        word: "調査",
        romaji: "chōsa",
        reading: "ちょうさ",
        meaning_en: "Investigation, survey",
        meaning_np: "अनुसन्धान",
        examples: [{ ja: "けいさつがちょうさをしています。", en: "The police are conducting an investigation.", np: "प्रहरीले अनुसन्धान गर्दैछ।" }],
      },
      {
        word: "収入",
        romaji: "shūnyū",
        reading: "しゅうにゅう",
        meaning_en: "Income",
        meaning_np: "आय",
        examples: [{ ja: "しゅうにゅうがふえました。", en: "My income increased.", np: "मेरो आय बढ्यो।" }],
      },
      {
        word: "理由",
        romaji: "riyū",
        reading: "りゆう",
        meaning_en: "Reason",
        meaning_np: "कारण",
        examples: [{ ja: "りゆうをおしえてください。", en: "Please tell me the reason.", np: "कारण बताइदिनुस्।" }],
      },
      {
        word: "基本的",
        romaji: "kihonteki",
        reading: "きほんてき",
        meaning_en: "Standard, basic",
        meaning_np: "आधारभूत",
        examples: [{ ja: "これはきほんてきなルールです。", en: "This is a basic rule.", np: "यो आधारभूत नियम हो।" }],
      },
      {
        word: "つまらない",
        romaji: "tsumaranai",
        meaning_en: "Boring",
        meaning_np: "उबाउलो",
        examples: [{ ja: "このえいがはつまらないです。", en: "This movie is boring.", np: "यो चलचित्र उबाउलो छ।" }],
      },
      {
        word: "おかげさまで",
        romaji: "okagesama de",
        meaning_en: "Thanks to you (set phrase)",
        meaning_np: "तपाईंको कृपाले",
        examples: [{ ja: "おかげさまで、げんきです。", en: "Thanks to you, I am well.", np: "तपाईंको कृपाले, म स्वस्थ छु।" }],
      },
      {
        word: "聞きましょう",
        romaji: "kikimashō",
        reading: "ききましょう",
        meaning_en: "Let's ask / listen",
        meaning_np: "सोधौँ / सुनौँ",
        examples: [{ ja: "せんせいにききましょう。", en: "Let's ask the teacher.", np: "शिक्षकलाई सोधौँ।" }],
      },
      {
        word: "もっと",
        romaji: "motto",
        meaning_en: "More",
        meaning_np: "अझ बढी",
        examples: [{ ja: "もっと大きいのを買いましょう！", en: "Let's buy a bigger one!", np: "अझ ठूलो किनौँ!" }],
      },
      {
        word: "しょっぱい",
        romaji: "shoppai",
        meaning_en: "Salty",
        meaning_np: "नुनिलो",
        examples: [{ ja: "このスープはしょっぱいです。", en: "This soup is salty.", np: "यो सुप नुनिलो छ।" }],
      },
      {
        word: "コーラ",
        romaji: "kōra",
        meaning_en: "Cola",
        meaning_np: "कोला",
        examples: [{ ja: "コーラをのみます。", en: "I drink cola.", np: "म कोला पिउँछु।" }],
      },
      {
        word: "とんかつ",
        romaji: "tonkatsu",
        meaning_en: "Pork cutlets",
        meaning_np: "सुँगुरको कटलेट",
        examples: [{ ja: "とんかつがすきです。", en: "I like pork cutlets.", np: "मलाई सुँगुरको कटलेट मन पर्छ।" }],
      },
      {
        word: "でも",
        romaji: "demo",
        meaning_en: "But, though, however",
        meaning_np: "तर",
        examples: [{ ja: "たかいです。でもおいしいです。", en: "It's expensive. But it's delicious.", np: "महँगो छ। तर मिठो छ।" }],
      },
      {
        word: "かっこいい",
        romaji: "kakkoii",
        meaning_en: "Cool, stylish",
        meaning_np: "कुल / स्टाइलिश",
        examples: [{ ja: "あのひとはかっこいいです。", en: "That person is cool.", np: "त्यो मान्छे कुल छ।" }],
      },
      {
        word: "ライオン",
        romaji: "raion",
        meaning_en: "Lion",
        meaning_np: "सिंह",
        examples: [{ ja: "ライオンはどうぶつえんにいます。", en: "The lion is at the zoo.", np: "सिंह चिडियाखानामा छ।" }],
      },
      {
        word: "ガーデニング",
        romaji: "gādeningu",
        meaning_en: "Gardening",
        meaning_np: "बगैँचा",
        examples: [{ ja: "まいにちガーデニングをします。", en: "I do gardening every day.", np: "म हरेक दिन बगैँचा गर्छु।" }],
      },
      {
        word: "料理",
        romaji: "ryōri",
        reading: "りょうり",
        meaning_en: "Cooking",
        meaning_np: "खाना पकाउनु",
        examples: [{ ja: "料理は楽しいです。", en: "Cooking is fun.", np: "खाना पकाउनु रमाइलो छ।" }],
      },
      {
        word: "ストレッチ",
        romaji: "sutoretchī",
        meaning_en: "Stretches",
        meaning_np: "स्ट्रेच",
        examples: [{ ja: "まいあさストレッチをします。", en: "I do stretches every morning.", np: "म हरेक बिहान स्ट्रेच गर्छु।" }],
      },
    ],
  },
  {
    day: 9,
    category: "Events & Hobbies",
    words: [
      {
        word: "パレード",
        romaji: "parēdo",
        meaning_en: "Parade",
        meaning_np: "परेड",
        examples: [{ ja: "パレードに行きませんか。", en: "Would you like to go to the parade?", np: "के तपाई परेडमा जानुहुन्छ?" }],
      },
      {
        word: "今週末",
        romaji: "konshūmatsu",
        reading: "こんしゅうまつ",
        meaning_en: "This weekend",
        meaning_np: "यो हप्ताको अन्त",
        examples: [{ ja: "今週末、何をしますか。", en: "What are you doing this weekend?", np: "यो हप्ताको अन्तमा के गर्नुहुन्छ?" }],
      },
      {
        word: "太鼓のパフォーマンス",
        romaji: "taiko no pafōmansu",
        reading: "たいこのパフォーマンス",
        meaning_en: "Taiko drum performance",
        meaning_np: "ताइको ढोलको प्रदर्शन",
        examples: [{ ja: "えきで太鼓のパフォーマンスがあります。", en: "There's a taiko drum performance at the station.", np: "स्टेसनमा ताइको ढोलको प्रदर्शन छ।" }],
      },
      {
        word: "花火大会",
        romaji: "hanabi taikai",
        reading: "はなびたいかい",
        meaning_en: "Fireworks display",
        meaning_np: "आतिशबाजी",
        examples: [{ ja: "花火大会に行きませんか。", en: "Would you like to go to the fireworks display?", np: "के तपाई आतिशबाजीमा जानुहुन्छ?" }],
      },
      {
        word: "ハロウィン",
        romaji: "harowin",
        meaning_en: "Halloween",
        meaning_np: "हेलोउइन",
        examples: [{ ja: "ハロウィンのパーティーがあります。", en: "There's a Halloween party.", np: "हेलोउइनको पार्टी छ।" }],
      },
      {
        word: "ドキュメンタリー",
        romaji: "dokyumentarī",
        meaning_en: "Documentary",
        meaning_np: "डकुमेन्टरी",
        examples: [{ ja: "ドキュメンタリーはすきですか。", en: "Do you like documentaries?", np: "तपाईलाई डकुमेन्टरी मन पर्छ?" }],
      },
      {
        word: "大晦日",
        romaji: "ōmisoka",
        reading: "おおみそか",
        meaning_en: "New Year's Eve",
        meaning_np: "नयाँ वर्षको पूर्वसन्ध्या",
        examples: [{ ja: "大晦日に何をしますか。", en: "What do you do on New Year's Eve?", np: "नयाँ वर्षको पूर्वसन्ध्यामा के गर्नुहुन्छ?" }],
      },
      {
        word: "テーマパーク",
        romaji: "tēma pāku",
        meaning_en: "Theme park",
        meaning_np: "थिम पार्क",
        examples: [{ ja: "テーマパークに行きませんか。", en: "Would you like to go to a theme park?", np: "के तपाई थिम पार्क जानुहुन्छ?" }],
      },
      {
        word: "チョコバナナ",
        romaji: "choko banana",
        meaning_en: "Chocolate-covered banana",
        meaning_np: "चकलेट केरा",
        examples: [{ ja: "チョコバナナをください。", en: "A chocolate-covered banana, please.", np: "एउटा चकलेट केरा दिनुहोस्।" }],
      },
      {
        word: "俳優",
        romaji: "haiyū",
        reading: "はいゆう",
        meaning_en: "Actor",
        meaning_np: "अभिनेता",
        examples: [{ ja: "ゆうめいな俳優です。", en: "They are a famous actor.", np: "उनी प्रसिद्ध अभिनेता हुन्।" }],
      },
      {
        word: "ポスター",
        romaji: "posutā",
        meaning_en: "Poster",
        meaning_np: "पोस्टर",
        examples: [{ ja: "ポスターはいくらですか。", en: "How much is the poster?", np: "पोस्टर कति पर्छ?" }],
      },
      {
        word: "RPG",
        romaji: "ārupījī",
        meaning_en: "Role-playing game",
        meaning_np: "रोल-प्लेइङ गेम",
        examples: [{ ja: "RPGはすきです。", en: "I like role-playing games.", np: "मलाई RPG मन पर्छु।" }],
      },
      {
        word: "SF",
        romaji: "esuefū",
        meaning_en: "Science fiction",
        meaning_np: "साइन्स फिक्सन",
        examples: [{ ja: "SFを見ます。", en: "I watch science fiction.", np: "म SF हेर्छु।" }],
      },
      {
        word: "ポップス",
        romaji: "poppusu",
        meaning_en: "Pop music",
        meaning_np: "पप संगीत",
        examples: [{ ja: "ポップスをききます。", en: "I listen to pop music.", np: "म पप संगीत सुन्छु।" }],
      },
      {
        word: "カードゲーム",
        romaji: "kādogēmu",
        meaning_en: "Card game",
        meaning_np: "कार्ड गेम",
        examples: [{ ja: "カードゲームをしましょう。", en: "Let's play card games.", np: "कार्ड गेम खेलौँ।" }],
      },
      {
        word: "パズル",
        romaji: "pazuru",
        meaning_en: "Puzzle",
        meaning_np: "पजल",
        examples: [{ ja: "パズルをしましょう。", en: "Let's do a puzzle.", np: "पजल गरौँ।" }],
      },
      {
        word: "アニソン",
        romaji: "anison",
        meaning_en: "Anime music",
        meaning_np: "एनिमे संगीत",
        examples: [{ ja: "アニソンはすきです。", en: "I like anime music.", np: "मलाई एनिमे संगीत मन पर्छ।" }],
      },
    ],
  },
  {
    day: 10,
    category: "Books & Media",
    words: [
      {
        word: "DVD",
        romaji: "dī buidī",
        meaning_en: "DVD",
        meaning_np: "डिभिडि",
        examples: [{ ja: "あのDVDがほしいです。", en: "I want that DVD.", np: "त्यो DVD चाहन्छु।" }],
      },
      {
        word: "フィクション",
        romaji: "fikushon",
        meaning_en: "Fiction",
        meaning_np: "काल्पनिक कथा",
        examples: [{ ja: "フィクションを読みます。", en: "I read fiction.", np: "म काल्पनिक कथा पढ्छु।" }],
      },
      {
        word: "ノンフィクション",
        romaji: "non-fikushon",
        meaning_en: "Non-fiction",
        meaning_np: "गैर-काल्पनिक",
        examples: [{ ja: "ノンフィクションはすきですか。", en: "Do you like non-fiction?", np: "तपाईलाई गैर-काल्पनिक मन पर्छ?" }],
      },
      {
        word: "話",
        romaji: "hanashi",
        reading: "はなし",
        meaning_en: "Story / Talk",
        meaning_np: "कथा / कुरा",
        examples: [{ ja: "話はどうですか。", en: "How is the story?", np: "कथा कस्तो छ?" }],
      },
      {
        word: "本屋",
        romaji: "hon-ya",
        reading: "ほんや",
        meaning_en: "Bookstore",
        meaning_np: "किताब पसल",
        examples: [{ ja: "本屋に行きます。", en: "I'm going to the bookstore.", np: "किताब पसल जाँदैछु।" }],
      },
      {
        word: "あまり",
        romaji: "amari",
        meaning_en: "(not) really / not much",
        meaning_np: "त्यति (नकारात्मकमा)",
        examples: [{ ja: "本はあまり読みません。", en: "I don't really read books.", np: "म किताब त्यति पढ्दिनँ।" }],
      },
      {
        word: "漫画のコーナー",
        romaji: "manga no kōnā",
        reading: "まんがのコーナー",
        meaning_en: "Manga section",
        meaning_np: "मंगा सेक्सन",
        examples: [{ ja: "漫画のコーナーはあそこです。", en: "The manga section is over there.", np: "मंगा सेक्सन त्यहाँ छ।" }],
      },
      {
        word: "セール",
        romaji: "sēru",
        meaning_en: "Sale",
        meaning_np: "सेल / छुट",
        examples: [{ ja: "セールがあります。", en: "There is a sale.", np: "सेल छ।" }],
      },
    ],
  },
  {
    day: 11,
    category: "Food & Flavors",
    words: [
      {
        word: "バニラ",
        romaji: "banira",
        meaning_en: "Vanilla",
        meaning_np: "भेनिला",
        examples: [{ ja: "バニラがだいすきです。", en: "I love vanilla.", np: "मलाई भेनिला धेरै मन पर्छ।" }],
      },
      {
        word: "バニラのアイスクリーム",
        romaji: "banira no aisukurīmu",
        meaning_en: "Vanilla ice cream",
        meaning_np: "भेनिला आइसक्रिम",
        examples: [{ ja: "バニラのアイスクリームを買います。", en: "I'm going to buy vanilla ice cream.", np: "भेनिला आइसक्रिम किन्छु।" }],
      },
      {
        word: "チョコミント",
        romaji: "choko minto",
        meaning_en: "Mint chocolate chip",
        meaning_np: "चकलेट मिन्ट",
        examples: [{ ja: "チョコミントはすきですか。", en: "Do you like mint chocolate chip?", np: "तपाईलाई चकलेट मिन्ट मन पर्छ?" }],
      },
      {
        word: "味",
        romaji: "aji",
        reading: "あじ",
        meaning_en: "Flavor",
        meaning_np: "स्वाद",
        examples: [{ ja: "すきな味は何ですか。", en: "What's your favorite flavor?", np: "तपाईंको मनपर्ने स्वाद के हो?" }],
      },
      {
        word: "卵",
        romaji: "tamago",
        reading: "たまご",
        meaning_en: "Egg",
        meaning_np: "अण्डा",
        examples: [{ ja: "もっと卵を買いましょう。", en: "We should buy more eggs.", np: "अझ धेरै अण्डा किनौँ।" }],
      },
    ],
  },
  {
    day: 12,
    category: "Theme Parks & Attractions",
    words: [
      {
        word: "遊園地",
        romaji: "yūenchi",
        reading: "ゆうえんち",
        meaning_en: "Amusement park",
        meaning_np: "मनोरञ्जन पार्क",
        examples: [{ ja: "たのしい遊園地です。", en: "It's a fun amusement park.", np: "रमाइलो मनोरञ्जन पार्क छ।" }],
      },
      {
        word: "アトラクション",
        romaji: "atorakushon",
        meaning_en: "Attraction / ride",
        meaning_np: "आकर्षण / राइड",
        examples: [{ ja: "アトラクションに乗りましょう。", en: "Let's ride the attractions.", np: "राइडमा चढौँ।" }],
      },
      {
        word: "ジェットコースター",
        romaji: "jetto kōsutā",
        meaning_en: "Rollercoaster",
        meaning_np: "रोलरकोस्टर",
        examples: [{ ja: "ジェットコースターがすきです。", en: "I like rollercoasters.", np: "मलाई रोलरकोस्टर मन पर्छ।" }],
      },
      {
        word: "ゴーカート",
        romaji: "gōkāto",
        meaning_en: "Go-kart",
        meaning_np: "गो-कार्ट",
        examples: [{ ja: "はやいゴーカートです。", en: "The go-karts are fast.", np: "गो-कार्ट छिटो छ।" }],
      },
      {
        word: "ショー",
        romaji: "shō",
        meaning_en: "Show",
        meaning_np: "शो",
        examples: [{ ja: "おもしろいショーです。", en: "It's a funny show.", np: "रमाइलो शो छ।" }],
      },
      {
        word: "キャラクター",
        romaji: "kyarakutā",
        meaning_en: "Mascot / Character",
        meaning_np: "मासकट / किरदार",
        examples: [{ ja: "かわいいキャラクターです。", en: "It's a cute mascot.", np: "प्यारो किरदार छ।" }],
      },
      {
        word: "入場料",
        romaji: "nyūjōryō",
        reading: "にゅうじょうりょう",
        meaning_en: "Admission fee",
        meaning_np: "प्रवेश शुल्क",
        examples: [{ ja: "入場料はいくらですか。", en: "How much is the admission fee?", np: "प्रवेश शुल्क कति हो?" }],
      },
      {
        word: "大人",
        romaji: "otona",
        reading: "おとな",
        meaning_en: "Adult",
        meaning_np: "वयस्क",
        examples: [{ ja: "大人のチケットをください。", en: "An adult ticket, please.", np: "वयस्कको टिकट दिनुहोस्।" }],
      },
      {
        word: "チケット",
        romaji: "chiketto",
        meaning_en: "Ticket",
        meaning_np: "टिकट",
        examples: [{ ja: "チケットはどこですか。", en: "Where is the ticket?", np: "टिकट कहाँ छ?" }],
      },
      {
        word: "お菓子",
        romaji: "okashi",
        reading: "おかし",
        meaning_en: "Snack / Sweets",
        meaning_np: "मिठाई / स्न्याक्स",
        examples: [{ ja: "すきなお菓子は何ですか。", en: "What's your favorite snack?", np: "तपाईंको मनपर्ने मिठाई के हो?" }],
      },
    ],
  },
  {
    day: 13,
    category: "Places & Activities",
    words: [
      {
        word: "博物館",
        romaji: "hakubutsukan",
        reading: "はくぶつかん",
        meaning_en: "Museum (natural history / general)",
        meaning_np: "संग्रहालय",
        examples: [{ ja: "博物館に行きます。", en: "I'm going to the museum.", np: "संग्रहालय जाँदैछु।" }],
      },
      {
        word: "写真家",
        romaji: "shashin-ka",
        reading: "しゃしんか",
        meaning_en: "Photographer",
        meaning_np: "फोटोग्राफर",
        examples: [{ ja: "はい、写真家です。", en: "Yes, I'm a photographer.", np: "हो, म फोटोग्राफर हुँ।" }],
      },
      {
        word: "プロ",
        romaji: "puro",
        meaning_en: "Pro / Professional",
        meaning_np: "पेशेवर",
        examples: [{ ja: "プロのスポーツです。", en: "It's professional sports.", np: "यो पेशेवर खेल हो।" }],
      },
      {
        word: "毎週",
        romaji: "maishū",
        reading: "まいしゅう",
        meaning_en: "Every week",
        meaning_np: "हरेक हप्ता",
        examples: [{ ja: "毎週えいがを見ます。", en: "I watch movies every week.", np: "म हरेक हप्ता चलचित्र हेर्छु।" }],
      },
      {
        word: "旅行",
        romaji: "ryokō",
        reading: "りょこう",
        meaning_en: "Travel",
        meaning_np: "यात्रा",
        examples: [{ ja: "旅行がすきです。", en: "I like travelling.", np: "मलाई यात्रा मन पर्छ।" }],
      },
    ],
  },
  {
    day: 14,
    category: "Time, Going Out & Adjectives",
    words: [
      {
        word: "午後",
        romaji: "gogo",
        reading: "ごご",
        meaning_en: "Afternoon / PM",
        meaning_np: "दिउँसो",
        examples: [{ ja: "午後一時ですか。", en: "Is it 1 PM?", np: "दिउँसो एक बजे हो?" }],
      },
      {
        word: "今晩",
        romaji: "konban",
        reading: "こんばん",
        meaning_en: "Tonight",
        meaning_np: "आज राति",
        examples: [{ ja: "今晩でかけましょう。", en: "Let's go out tonight.", np: "आज राति बाहिर जाऊँ।" }],
      },
      {
        word: "出かける",
        romaji: "dekakeru",
        reading: "でかける",
        meaning_en: "To go out",
        meaning_np: "बाहिर जानु",
        examples: [{ ja: "今晩出かけましょう。", en: "Let's go out tonight.", np: "आज राति बाहिर जाऊँ।" }],
      },
      {
        word: "速い",
        romaji: "hayai",
        reading: "はやい",
        meaning_en: "Fast",
        meaning_np: "छिटो",
        examples: [{ ja: "はやいゴーカートです。", en: "The go-karts are fast.", np: "गो-कार्ट छिटो छ।" }],
      },
      {
        word: "黄色い",
        romaji: "kiiroi",
        reading: "きいろい",
        meaning_en: "Yellow",
        meaning_np: "पहेँलो",
        examples: [{ ja: "きいろいかばんです。", en: "It's a yellow bag.", np: "पहेँलो झोला छ।" }],
      },
    ],
  },
  {
    day: 15,
    category: "Travel & Directions",
    words: [
      {
        word: "タクシー",
        romaji: "takushī",
        meaning_en: "Taxi",
        meaning_np: "ट्याक्सी",
        examples: [{ ja: "あそこでタクシーをよびましょう。", en: "Let's call a taxi over there.", np: "त्यहाँ ट्याक्सी बोलाऔं।" }],
      },
      {
        word: "ゆっくりします",
        romaji: "yukkuri shimasu",
        meaning_en: "Relax / Take it easy",
        meaning_np: "आराम गर्नु",
        examples: [{ ja: "ここでゆっくりします。", en: "I'm going to relax here.", np: "म यहाँ आराम गर्छु।" }],
      },
      {
        word: "インフォメーション",
        romaji: "infōmēshon",
        meaning_en: "Information desk",
        meaning_np: "सूचना कक्ष",
        examples: [{ ja: "インフォメーションで聞きましょう。", en: "We should ask at the information desk.", np: "सूचना कक्षमा सोधौं।" }],
      },
      {
        word: "ツアー",
        romaji: "tsuā",
        meaning_en: "Tour",
        meaning_np: "भ्रमण / टुर",
        examples: [{ ja: "ツアーに行きます。", en: "I'm going on a tour.", np: "म टुरमा जान्छु।" }],
      },
      {
        word: "北口",
        romaji: "kitaguchi",
        reading: "きたぐち",
        meaning_en: "North exit",
        meaning_np: "उत्तर निकास",
        examples: [{ ja: "きたぐちで会いましょう。", en: "Let's meet at the north exit.", np: "उत्तर निकासमा भेटौं।" }],
      },
      {
        word: "かいそく",
        romaji: "kaisoku",
        meaning_en: "Rapid (train)",
        meaning_np: "द्रुत / छिटो",
        examples: [{ ja: "かいそくでんしゃに乗ります。", en: "I ride the rapid train.", np: "म द्रुत रेलमा चढ्छु।" }],
      },
      {
        word: "モノレール",
        romaji: "monorēru",
        meaning_en: "Monorail",
        meaning_np: "मोनोरेल",
        examples: [{ ja: "モノレールに乗ります。", en: "I ride the monorail.", np: "म मोनोरेलमा चढ्छु।" }],
      },
      {
        word: "うりば",
        romaji: "uriba",
        meaning_en: "Sales counter / place",
        meaning_np: "बिक्री काउन्टर",
        examples: [{ ja: "きっぷうりばはどこですか。", en: "Where is the ticket counter?", np: "टिकट काउन्टर कहाँ छ?" }],
      },
      {
        word: "ゆうえんち",
        romaji: "yūenchi",
        meaning_en: "Theme park / amusement park",
        meaning_np: "मनोरञ्जन पार्क",
        examples: [{ ja: "ゆうえんちに行きます。", en: "I go to the amusement park.", np: "म मनोरञ्जन पार्क जान्छु।" }],
      },
    ],
  },
  {
    day: 16,
    category: "Food, Movies & Fashion",
    words: [
      {
        word: "ステーキ",
        romaji: "sutēki",
        meaning_en: "Steak",
        meaning_np: "स्टेक (मासु)",
        examples: [{ ja: "ステーキを食べます。", en: "I eat steak.", np: "म स्टेक खान्छु।" }],
      },
      {
        word: "ポップコーン",
        romaji: "poppukōn",
        meaning_en: "Popcorn",
        meaning_np: "पपकर्न",
        examples: [{ ja: "ポップコーンを食べます。", en: "I eat popcorn.", np: "म पपकर्न खान्छु।" }],
      },
      {
        word: "せき",
        romaji: "seki",
        meaning_en: "Seat",
        meaning_np: "सिट / आसन",
        examples: [{ ja: "せきをよやくします。", en: "I reserve a seat.", np: "म सिट आरक्षण गर्छु।" }],
      },
      {
        word: "よやくします",
        romaji: "yoyaku shimasu",
        meaning_en: "To reserve / book",
        meaning_np: "आरक्षण गर्नु",
        examples: [{ ja: "せきをよやくします。", en: "I reserve a seat.", np: "म सिट आरक्षण गर्छु।" }],
      },
      {
        word: "ホットドッグ",
        romaji: "hotto doggu",
        meaning_en: "Hot dog",
        meaning_np: "हट डग",
        examples: [{ ja: "ホットドッグを食べます。", en: "I eat a hot dog.", np: "म हट डग खान्छु।" }],
      },
      {
        word: "かんとく",
        romaji: "kantoku",
        meaning_en: "Director",
        meaning_np: "निर्देशक",
        examples: [{ ja: "ゆうめいなかんとく。", en: "A famous director.", np: "एक प्रसिद्ध निर्देशक।" }],
      },
      {
        word: "ブラウス",
        romaji: "burausu",
        meaning_en: "Blouse",
        meaning_np: "ब्लाउज",
        examples: [{ ja: "みどりのブラウス。", en: "A green blouse.", np: "हरियो ब्लाउज।" }],
      },
      {
        word: "ネックレス",
        romaji: "nekkuresu",
        meaning_en: "Necklace",
        meaning_np: "हार / नेकलेस",
        examples: [{ ja: "かわいいネックレス。", en: "A cute necklace.", np: "प्यारो हार।" }],
      },
      {
        word: "おしゃれ",
        romaji: "oshare",
        meaning_en: "Stylish / fashionable",
        meaning_np: "फेसनेबल / स्टाइलिस",
        examples: [{ ja: "おしゃれなぼうしです。", en: "It's a stylish hat.", np: "यो स्टाइलिस टोपी हो।" }],
      },
    ],
  },
  {
    day: 17,
    category: "Personality & Shopping",
    words: [
      {
        word: "うでどけい",
        romaji: "udedokei",
        meaning_en: "Watch (wristwatch)",
        meaning_np: "हातघडी",
        examples: [{ ja: "うでどけいを買います。", en: "I buy a watch.", np: "म हातघडी किन्छु।" }],
      },
      {
        word: "げんき",
        romaji: "genki",
        meaning_en: "Lively / energetic / cheerful",
        meaning_np: "फुर्तिलो / जोसिलो",
        examples: [{ ja: "げんきなかのじょです。", en: "She's an energetic girlfriend.", np: "उनी फुर्तिलो साथी हुन्।" }],
      },
      {
        word: "やさしい",
        romaji: "yasashii",
        meaning_en: "Nice / kind / gentle",
        meaning_np: "दयालु / नरम",
        examples: [{ ja: "やさしいかのじょです。", en: "She's a nice girlfriend.", np: "उनी दयालु साथी हुन्।" }],
      },
      {
        word: "コーナー",
        romaji: "kōnā",
        meaning_en: "Corner / section",
        meaning_np: "कुना / सेक्सन",
        examples: [{ ja: "まんがのコーナーです。", en: "It's the manga section.", np: "यो मंगा सेक्सन हो।" }],
      },
      {
        word: "ほしい",
        romaji: "hoshii",
        meaning_en: "To want",
        meaning_np: "चाहनु",
        examples: [{ ja: "DVDがほしいです。", en: "I want a DVD.", np: "मलाई DVD चाहिन्छ।" }],
      },
    ],
  },
  {
    day: 18,
    category: "Festivals & Sightseeing",
    words: [
      {
        word: "はなび",
        romaji: "hanabi",
        meaning_en: "Fireworks",
        meaning_np: "आतिशबाजी",
        examples: [{ ja: "はなびを見ます。", en: "I watch fireworks.", np: "म आतिशबाजी हेर्छु।" }],
      },
      {
        word: "たいかい",
        romaji: "taikai",
        meaning_en: "Display / large gathering / tournament",
        meaning_np: "महोत्सव / ठूलो जमघट",
        examples: [{ ja: "はなびたいかいに行きます。", en: "I go to the fireworks display.", np: "म आतिशबाजी महोत्सवमा जान्छु।" }],
      },
      {
        word: "こんしゅう",
        romaji: "konshū",
        meaning_en: "This week",
        meaning_np: "यो हप्ता",
        examples: [{ ja: "こんしゅうはいそがしいです。", en: "This week is busy.", np: "यो हप्ता व्यस्त छ।" }],
      },
      {
        word: "しゅうまつ",
        romaji: "shūmatsu",
        meaning_en: "Weekend",
        meaning_np: "सप्ताहन्त",
        examples: [{ ja: "こんしゅうまつに行きます。", en: "I go this weekend.", np: "म यो सप्ताहन्त जान्छु।" }],
      },
      {
        word: "かんこう",
        romaji: "kankō",
        meaning_en: "Sightseeing",
        meaning_np: "पर्यटन / घुमफिर",
        examples: [{ ja: "かんこうします。", en: "I do sightseeing.", np: "म पर्यटन गर्छु।" }],
      },
    ],
  },
  {
    day: 19,
    category: "Family & Places",
    words: [
      {
        word: "おこさん",
        romaji: "okosan",
        meaning_en: "(Your) child / kid",
        meaning_np: "(तपाईंको) बच्चा",
        examples: [{ ja: "おこさんは何さいですか。", en: "How old is your kid?", np: "तपाईंको बच्चा कति वर्षको हो?" }],
      },
      {
        word: "ソウル",
        romaji: "souru",
        meaning_en: "Seoul",
        meaning_np: "सियोल",
        examples: [{ ja: "ソウルにすんでいます。", en: "I live in Seoul.", np: "म सियोलमा बस्छु।" }],
      },
      {
        word: "マレーシア",
        romaji: "marēshia",
        meaning_en: "Malaysia",
        meaning_np: "मलेसिया",
        examples: [{ ja: "マレーシアがすきです。", en: "I like Malaysia.", np: "मलाई मलेसिया मन पर्छ।" }],
      },
      {
        word: "ココア",
        romaji: "kokoa",
        meaning_en: "Cocoa / hot chocolate",
        meaning_np: "कोको / हट चकलेट",
        examples: [{ ja: "ココアがほしいです。", en: "I want cocoa.", np: "मलाई कोको चाहिन्छ।" }],
      },
      {
        word: "はらじゅく",
        romaji: "harajuku",
        meaning_en: "Harajuku",
        meaning_np: "हाराजुकु",
        examples: [{ ja: "はらじゅくはにぎやかです。", en: "Harajuku is lively.", np: "हाराजुकु चहलपहल छ।" }],
      },
    ],
  },
  {
    day: 20,
    category: "Jobs & City Life",
    words: [
      {
        word: "ジム",
        romaji: "jimu",
        meaning_en: "Gym",
        meaning_np: "जिम",
        examples: [{ ja: "だいがくのジムです。", en: "It's the university gym.", np: "यो विश्वविद्यालयको जिम हो।" }],
      },
      {
        word: "せんしゅ",
        romaji: "senshu",
        meaning_en: "Player / athlete",
        meaning_np: "खेलाडी",
        examples: [{ ja: "せんしゅです。", en: "I'm a player.", np: "म खेलाडी हुँ।" }],
      },
      {
        word: "イベント",
        romaji: "ibento",
        meaning_en: "Event",
        meaning_np: "कार्यक्रम / इभेन्ट",
        examples: [{ ja: "たのしいイベントです。", en: "It's a fun event.", np: "यो रमाइलो कार्यक्रम हो।" }],
      },
      {
        word: "ナビ",
        romaji: "nabi",
        meaning_en: "GPS / navigation",
        meaning_np: "जीपीएस / नेभिगेसन",
        examples: [{ ja: "ナビをつかいます。", en: "I use the GPS.", np: "म जीपीएस प्रयोग गर्छु।" }],
      },
      {
        word: "ほんやくか",
        romaji: "hon'yakuka",
        meaning_en: "Translator",
        meaning_np: "अनुवादक",
        examples: [{ ja: "ほんやくかです。", en: "I'm a translator.", np: "म अनुवादक हुँ।" }],
      },
      {
        word: "マネージャー",
        romaji: "manējā",
        meaning_en: "Manager",
        meaning_np: "प्रबन्धक / म्यानेजर",
        examples: [{ ja: "マネージャーです。", en: "I'm a manager.", np: "म प्रबन्धक हुँ।" }],
      },
      {
        word: "どうりょう",
        romaji: "dōryō",
        meaning_en: "Coworker / colleague",
        meaning_np: "सहकर्मी",
        examples: [{ ja: "どうりょうです。", en: "This is my coworker.", np: "यो मेरो सहकर्मी हो।" }],
      },
      {
        word: "なま",
        romaji: "nama",
        meaning_en: "Raw",
        meaning_np: "काँचो",
        examples: [{ ja: "なまの卵は食べません。", en: "I don't eat raw eggs.", np: "म काँचो अन्डा खाँदिनँ।" }],
      },
      {
        word: "たのしみ",
        romaji: "tanoshimi",
        meaning_en: "Looking forward to",
        meaning_np: "पर्खिरहेको / उत्सुक",
        examples: [{ ja: "何がたのしみですか。", en: "What are you looking forward to?", np: "तपाईं केको लागि उत्सुक हुनुहुन्छ?" }],
      },
      {
        word: "みそかつ",
        romaji: "misokatsu",
        meaning_en: "Miso pork cutlet",
        meaning_np: "मिसो पोर्क कटलेट",
        examples: [{ ja: "みそかつを食べます。", en: "I eat miso pork cutlet.", np: "म मिसो पोर्क कटलेट खान्छु।" }],
      },
      {
        word: "しろ",
        romaji: "shiro",
        meaning_en: "Castle",
        meaning_np: "किल्ला / दरबार",
        examples: [{ ja: "しろを見ます。", en: "I look at the castle.", np: "म किल्ला हेर्छु।" }],
      },
      {
        word: "ひろば",
        romaji: "hiroba",
        meaning_en: "Plaza / open square",
        meaning_np: "चोक / खुला मैदान",
        examples: [{ ja: "そのひろばでしゃしんをとります。", en: "I take a photo at that plaza.", np: "म त्यो चोकमा फोटो खिच्छु।" }],
      },
    ],
  },
  {
    day: 21,
    category: "Calendar & Preferences",
    words: [
      {
        word: "十月",
        romaji: "jūgatsu",
        meaning_en: "October",
        meaning_np: "अक्टोबर",
        examples: [{ ja: "十月です。", en: "It's October.", np: "यो अक्टोबर हो।" }],
      },
      {
        word: "がっき",
        romaji: "gakki",
        meaning_en: "Term / semester",
        meaning_np: "सत्र / शैक्षिक अवधि",
        examples: [{ ja: "あたらしいがっきです。", en: "It's a new semester.", np: "यो नयाँ सत्र हो।" }],
      },
      {
        word: "すきな",
        romaji: "sukina",
        meaning_en: "Favorite / (that one) likes",
        meaning_np: "मनपर्ने",
        examples: [{ ja: "すきなアトラクションは何ですか。", en: "What's your favorite attraction?", np: "तपाईंको मनपर्ने आकर्षण के हो?" }],
      },
      {
        word: "三千",
        romaji: "sanzen",
        meaning_en: "Three thousand",
        meaning_np: "तीन हजार",
        examples: [{ ja: "三千えんです。", en: "It's 3,000 yen.", np: "यो तीन हजार येन हो।" }],
      },
    ],
  },
  {
    day: 22,
    category: "Work & Job Vocabulary",
    words: [
      {
        word: "仕事",
        romaji: "shigoto",
        reading: "しごと",
        meaning_en: "Work / job",
        meaning_np: "काम",
        examples: [{ ja: "仕事はたのしいです。", en: "Work is fun.", np: "काम रमाइलो छ।" }],
      },
      {
        word: "会社",
        romaji: "kaisha",
        reading: "かいしゃ",
        meaning_en: "Company",
        meaning_np: "कम्पनी",
        examples: [{ ja: "会社はここです。", en: "The company is here.", np: "कम्पनी यहाँ छ।" }],
      },
      {
        word: "社員",
        romaji: "shain",
        reading: "しゃいん",
        meaning_en: "Employee",
        meaning_np: "कर्मचारी",
        examples: [{ ja: "わたしは社員です。", en: "I am an employee.", np: "म कर्मचारी हुँ।" }],
      },
      {
        word: "上司",
        romaji: "jōshi",
        reading: "じょうし",
        meaning_en: "Boss",
        meaning_np: "मालिक",
        examples: [{ ja: "上司とはなします。", en: "I talk with my boss.", np: "मालिकसँग कुरा गर्छु।" }],
      },
      {
        word: "同僚",
        romaji: "dōryō",
        reading: "どうりょう",
        meaning_en: "Colleague",
        meaning_np: "सहकर्मी",
        examples: [{ ja: "同僚とランチします。", en: "I have lunch with my colleague.", np: "सहकर्मीसँग खाजा खान्छु।" }],
      },
      {
        word: "店長",
        romaji: "tenchō",
        reading: "てんちょう",
        meaning_en: "Store manager",
        meaning_np: "पसल प्रबन्धक",
        examples: [{ ja: "店長に聞きます。", en: "I ask the store manager.", np: "पसल प्रबन्धकलाई सोध्छु।" }],
      },
      {
        word: "出勤",
        romaji: "shukkin",
        reading: "しゅっきん",
        meaning_en: "Going to work",
        meaning_np: "काम जानु",
        examples: [{ ja: "九時に出勤します。", en: "I go to work at 9 o'clock.", np: "९ बजे काम जान्छु।" }],
      },
      {
        word: "退勤",
        romaji: "taikin",
        reading: "たいきん",
        meaning_en: "Leaving work",
        meaning_np: "काम सकिनु",
        examples: [{ ja: "六時に退勤します。", en: "I leave work at 6 o'clock.", np: "६ बजे काम सकिन्छ।" }],
      },
      {
        word: "遅刻",
        romaji: "chikoku",
        reading: "ちこく",
        meaning_en: "Being late",
        meaning_np: "ढिला हुनु",
        examples: [{ ja: "今日は遅刻しました。", en: "I was late today.", np: "आज ढिला भयो।" }],
      },
      {
        word: "早退",
        romaji: "sōtai",
        reading: "そうたい",
        meaning_en: "Leaving early",
        meaning_np: "चाँडै निस्कनु",
        examples: [{ ja: "きょうは早退します。", en: "I'll leave early today.", np: "आज चाँडै निस्कन्छु।" }],
      },
      {
        word: "残業",
        romaji: "zangyō",
        reading: "ざんぎょう",
        meaning_en: "Overtime",
        meaning_np: "ओभरटाइम",
        examples: [{ ja: "今日は残業です。", en: "I have overtime today.", np: "आज ओभरटाइम छ।" }],
      },
      {
        word: "休み",
        romaji: "yasumi",
        reading: "やすみ",
        meaning_en: "Holiday / day off",
        meaning_np: "बिदा",
        examples: [{ ja: "あしたは休みです。", en: "Tomorrow is a day off.", np: "भोलि बिदा हो।" }],
      },
      {
        word: "時給",
        romaji: "jikyū",
        reading: "じきゅう",
        meaning_en: "Hourly wage",
        meaning_np: "प्रति घण्टा पैसा",
        examples: [{ ja: "時給はいくらですか。", en: "How much is the hourly wage?", np: "प्रति घण्टा पैसा कति हो?" }],
      },
      {
        word: "給料",
        romaji: "kyūryō",
        reading: "きゅうりょう",
        meaning_en: "Salary",
        meaning_np: "तलब",
        examples: [{ ja: "給料日はいつですか。", en: "When is payday?", np: "तलब दिन कहिले हो?" }],
      },
      {
        word: "交通費",
        romaji: "kōtsūhi",
        reading: "こうつうひ",
        meaning_en: "Transportation cost",
        meaning_np: "यातायात खर्च",
        examples: [{ ja: "交通費がでます。", en: "Transportation costs are covered.", np: "यातायात खर्च दिइन्छ।" }],
      },
      {
        word: "昇給",
        romaji: "shōkyū",
        reading: "しょうきゅう",
        meaning_en: "Salary increase",
        meaning_np: "तलब बढ्नु",
        examples: [{ ja: "らいねん昇給します。", en: "I'll get a raise next year.", np: "अर्को वर्ष तलब बढ्छ।" }],
      },
      {
        word: "支払い",
        romaji: "shiharai",
        reading: "しはらい",
        meaning_en: "Payment",
        meaning_np: "भुक्तानी",
        examples: [{ ja: "支払いはカードです。", en: "Payment is by card.", np: "भुक्तानी कार्डबाट हो।" }],
      },
      {
        word: "振り込み",
        romaji: "furikomi",
        reading: "ふりこみ",
        meaning_en: "Bank transfer",
        meaning_np: "बैंक ट्रान्सफर",
        examples: [{ ja: "給料は振り込みです。", en: "Salary is by bank transfer.", np: "तलब बैंक ट्रान्सफरबाट हुन्छ।" }],
      },
      {
        word: "働く",
        romaji: "hataraku",
        reading: "はたらく",
        meaning_en: "To work",
        meaning_np: "काम गर्नु",
        examples: [{ ja: "まいにち働きます。", en: "I work every day.", np: "म हरेक दिन काम गर्छु।" }],
      },
      {
        word: "休む",
        romaji: "yasumu",
        reading: "やすむ",
        meaning_en: "To take a break / rest",
        meaning_np: "बिदा लिनु",
        examples: [{ ja: "あした休みます。", en: "I'll take a day off tomorrow.", np: "भोलि बिदा लिन्छु।" }],
      },
      {
        word: "手伝う",
        romaji: "tetsudau",
        reading: "てつだう",
        meaning_en: "To help",
        meaning_np: "सहयोग गर्नु",
        examples: [{ ja: "仕事を手伝います。", en: "I help with work.", np: "काममा सहयोग गर्छु।" }],
      },
      {
        word: "確認",
        romaji: "kakunin",
        reading: "かくにん",
        meaning_en: "To confirm / check",
        meaning_np: "जाँच गर्नु",
        examples: [{ ja: "メールを確認します。", en: "I check the email.", np: "इमेल जाँच गर्छु।" }],
      },
      {
        word: "準備",
        romaji: "junbi",
        reading: "じゅんび",
        meaning_en: "To prepare",
        meaning_np: "तयारी गर्नु",
        examples: [{ ja: "かいぎの準備をします。", en: "I prepare for the meeting.", np: "बैठकको तयारी गर्छु।" }],
      },
      {
        word: "終わる",
        romaji: "owaru",
        reading: "おわる",
        meaning_en: "To finish",
        meaning_np: "सकिनु",
        examples: [{ ja: "仕事が終わりました。", en: "Work has finished.", np: "काम सकियो।" }],
      },
      {
        word: "お疲れ様です",
        romaji: "otsukaresama desu",
        meaning_en: "Good work / thanks for your hard work",
        meaning_np: "राम्रो काम गर्नुभयो",
        examples: [{ ja: "きょうもお疲れ様です。", en: "Thanks for your hard work today too.", np: "आज पनि धेरै मिहिनेत गर्नुभयो।" }],
      },
      {
        word: "すみません",
        romaji: "sumimasen",
        meaning_en: "Excuse me / sorry",
        meaning_np: "माफ गर्नुहोस्",
        examples: [{ ja: "すみません、ちこくしました。", en: "Sorry, I was late.", np: "माफ गर्नुहोस्, ढिलो भयो।" }],
      },
      {
        word: "お願いします",
        romaji: "onegaishimasu",
        reading: "おねがいします",
        meaning_en: "Please",
        meaning_np: "कृपया",
        examples: [{ ja: "かくにんおねがいします。", en: "Please confirm.", np: "कृपया जाँच गर्नुहोस्।" }],
      },
      {
        word: "大丈夫です",
        romaji: "daijōbu desu",
        meaning_en: "It's okay / I'm fine",
        meaning_np: "ठीक छ",
        examples: [{ ja: "だいじょうぶです、ありがとう。", en: "I'm fine, thank you.", np: "ठीक छ, धन्यवाद।" }],
      },
      {
        word: "無理です",
        romaji: "muri desu",
        meaning_en: "It's impossible / I can't",
        meaning_np: "सकिँदैन",
        examples: [{ ja: "きょうは無理です。", en: "I can't do it today.", np: "आज सकिँदैन।" }],
      },
    ],
  },
];
