import type { LessonDay } from "@/lib/learn/lesson-types";

const same = (en: string) => ({ en, np: en, jp: en });

export const PYTHON_DAY_4_LESSONS: LessonDay = {
  day: 4,
  label: same("Phase 0 · Python Foundations"),
  title: same("Operators & Expressions"),
  overview: same("Use arithmetic, comparisons, logic, membership, and identity correctly so your program can calculate values and make reliable decisions."),
  totalMinutes: 80,
  difficulty: same("Beginner"),
  lessons: [
    {
      id: "python-arithmetic",
      title: same("Arithmetic and assignment"),
      durationMinutes: 17,
      explanation: same("Arithmetic operators calculate values: `+`, `-`, `*`, `/`, `//`, `%`, and `**`. `/` always produces a float, `//` divides and rounds down, `%` gives the remainder, and `**` raises a value to a power. Assignment operators such as `+=` update an existing variable.\n\nIn an inventory app, `remaining = stock - ordered` is more useful than a bare calculation because it names the business result. Use parentheses when a calculation matters. They make both the intended order and a later code review clearer. For money, floats are fine for early learning but are not always exact enough for production financial systems. Use decimal-aware approaches when accuracy is business-critical."),
      diagram: "stock = 17\nordered = 5\n\nremaining = stock - ordered  → 12\nboxes = 17 // 5             → 3\nleftover = 17 % 5           → 2",
      codeExample: { title: same("Calculate an inventory update"), code: "stock = 17\nordered = 5\nbox_capacity = 5\n\nremaining = stock - ordered\nfull_boxes = stock // box_capacity\nleftover_items = stock % box_capacity\nstock -= ordered\n\nprint(remaining, full_boxes, leftover_items)" },
      keyTakeaways: [same("`/` produces a decimal result and `//` produces floor division."), same("`%` is the remainder operator."), same("`+=` and similar operators update a variable."), same("Parentheses make important calculations explicit.")],
      commonMistakes: [same("Using `/` when the business rule needs whole boxes."), same("Assuming `//` rounds to the nearest integer. It rounds down."), same("Using binary floats without thought for production currency totals.")],
      quiz: [{ question: same("What is `17 % 5`?"), options: [same("`2`"), same("`3`"), same("`3.4`"), same("`0`")], correctIndex: 0, explanation: same("Five fits into 17 three times, with 2 left over.") }],
    },
    {
      id: "python-comparisons",
      title: same("Compare values and chain ranges"),
      durationMinutes: 16,
      explanation: same("Comparison operators answer a yes-or-no question: `==`, `!=`, `<`, `<=`, `>`, and `>=`. They produce booleans. A chained comparison such as `0 <= discount <= 100` is readable Python for a value inside a range. It evaluates the middle value once.\n\nUse `==` for values, not `=`. In a checkout validation, compare the quantity and price separately when each failure needs a different user message. A combined expression is concise, but it can hide which rule failed. Write code for the decision a person needs to understand, not only the shortest expression."),
      diagram: "0 <= discount <= 100\n│    │            │\n│    └── valid range ──► True or False\n└─ lower limit",
      codeExample: { title: same("Validate a discount"), code: "discount_percent = 15\n\nis_valid_discount = 0 <= discount_percent <= 100\nis_free_shipping = discount_percent == 100\n\nprint(is_valid_discount)\nprint(is_free_shipping)" },
      keyTakeaways: [same("Comparisons produce `True` or `False`."), same("Use `==` to compare and `=` to assign."), same("Chained comparisons express a range clearly."), same("Separate rules when the user needs separate error messages.")],
      commonMistakes: [same("Writing `if quantity = 0`, which is invalid because `=` assigns."), same("Comparing a string number to an integer before conversion."), same("Using multiple partial range checks when one chained comparison is clearer.")],
      quiz: [{ question: same("What does `1 <= score <= 5` test?"), options: [same("Whether score is in the inclusive range 1 through 5"), same("Whether score equals 1 or 5 only"), same("Whether score is a string"), same("Whether score has an object identity")], correctIndex: 0, explanation: same("Both comparisons must be true for the chained comparison to be true.") }],
    },
    {
      id: "python-logic-truthiness",
      title: same("Combine rules with logical operators"),
      durationMinutes: 18,
      explanation: same("`and`, `or`, and `not` combine or reverse boolean conditions. An order can ship when it is paid <b>and</b> has stock. A user can sign in with an email <b>or</b> a phone number. `not` reverses a boolean result. Python evaluates `and` and `or` left to right and may stop early once it knows the answer.\n\nPython also treats certain values as false in a condition: `False`, `None`, zero numbers, and empty strings or collections. Everything else is truthy. `if email:` is a clean check for non-empty input, but it does not validate an email address. Be precise about the business rule. A blank note and a missing note may be equivalent for one workflow but different for another."),
      diagram: "is_paid ──┐\n          ├─ and ──► can_ship\nhas_stock ┘\n\nFalse, None, 0, \"\" → falsy",
      codeExample: { title: same("Decide whether to ship"), code: "is_paid = True\nhas_stock = True\nshipping_note = \"\"\n\ncan_ship = is_paid and has_stock\nneeds_default_note = not shipping_note\n\nprint(can_ship)\nprint(needs_default_note)" },
      keyTakeaways: [same("`and` requires both conditions; `or` requires at least one."), same("`not` reverses truthiness."), same("Empty strings, `None`, and zero are falsy."), same("Truthy checks are not full validation.")],
      commonMistakes: [same("Writing `if status == \"new\" or \"paid\"`, which is always truthy. Compare both values or use membership."), same("Using `or` when both security checks must pass."), same("Treating a truthy string like `\"False\"` as the boolean `False`.")],
      quiz: [{ question: same("When is `is_paid and has_stock` true?"), options: [same("Only when both values are true"), same("When either value is true"), same("Only when both are false"), same("Never")], correctIndex: 0, explanation: same("`and` requires every operand to be truthy.") }],
    },
    {
      id: "python-membership-identity",
      title: same("Membership and identity are different questions"),
      durationMinutes: 14,
      explanation: same("The membership operators `in` and `not in` ask whether a value appears in a collection or substring: `\"admin\" in roles` or `\"@\" in email`. They are often clearer than repeated `or` comparisons. Membership is not authorization by itself: an app must still verify who supplied the roles and enforce rules on the server.\n\nThe identity operators `is` and `is not` ask whether two names refer to the same object. Their everyday use is `value is None`. Do not use `is` for normal strings, integers, or content comparison. Sometimes Python reuses small immutable objects, which can make an incorrect identity comparison appear to work until it does not."),
      diagram: "\"manager\" in roles  → asks: contained?\nvalue is None       → asks: same singleton object?\nname == \"Mina\"     → asks: same content?",
      codeExample: { title: same("Check roles and missing input"), code: "roles = [\"viewer\", \"manager\"]\ncustomer_note = None\n\ncan_review_orders = \"manager\" in roles\nneeds_note = customer_note is None\n\nprint(can_review_orders)\nprint(needs_note)" },
      keyTakeaways: [same("Use `in` for membership checks."), same("Use `is None` for a missing sentinel value."), same("Use `==` for ordinary value equality."), same("Membership checks do not replace server-side authorization.")],
      commonMistakes: [same("Using `is` to compare two strings."), same("Checking `\"admin\" in user_input` as an authorization decision."), same("Using membership on a string when a whole-token match is required.")],
      quiz: [{ question: same("Which check is correct for a missing optional field?"), options: [same("`note is None`"), same("`note in None`"), same("`note is \"\"`"), same("`id(note) == 0`")], correctIndex: 0, explanation: same("`None` is a singleton used to represent a missing value.") }],
    },
    {
      id: "python-precedence",
      title: same("Make expression order obvious"),
      durationMinutes: 15,
      explanation: same("Operators have precedence rules. Arithmetic happens before comparisons, comparisons before `not`, then `and`, then `or`. That means `is_paid or has_credit and has_stock` is read as `is_paid or (has_credit and has_stock)`, not necessarily the rule you intended. Parentheses are cheap documentation.\n\nBreak a long expression into named booleans when it carries an important business decision. `has_valid_payment`, `has_stock`, and `is_shipping_address_valid` make a checkout rule easier to test and change than a compressed line. This is a correctness practice, not just a style preference."),
      diagram: "Parentheses decide intent:\n\n(is_paid or has_credit) and has_stock\n             │\n             ▼\n         can_fulfill",
      codeExample: { title: same("Name a fulfillment decision"), code: "is_paid = False\nhas_credit = True\nhas_stock = True\n\nhas_valid_payment = is_paid or has_credit\ncan_fulfill = has_valid_payment and has_stock\n\nprint(can_fulfill)" },
      keyTakeaways: [same("Parentheses beat guessing precedence."), same("`and` binds more tightly than `or`."), same("Name important intermediate conditions."), same("A readable expression is easier to test.")],
      commonMistakes: [same("Relying on remembered precedence for payment, permission, or safety rules."), same("Combining several unrelated checks into one line with no named pieces."), same("Using clever boolean expressions where an explicit condition is easier to review.")],
      quiz: [{ question: same("How does Python group `a or b and c` without parentheses?"), options: [same("`a or (b and c)`"), same("`(a or b) and c`"), same("`(a and b) or c`"), same("It is invalid")], correctIndex: 0, explanation: same("`and` has higher precedence than `or`.") }],
    },
  ],
  finalQuiz: [
    { question: same("What operator finds a remainder?"), options: [same("`%`"), same("`//`"), same("`**`"), same("`/`")], correctIndex: 0, explanation: same("Modulo returns the remainder after division.") },
    { question: same("Which check compares an order status to `\"paid\"`?"), options: [same("`status == \"paid\"`"), same("`status = \"paid\"`"), same("`status is \"paid\"`"), same("`status in None`")], correctIndex: 0, explanation: same("Use `==` for ordinary value equality.") },
    { question: same("Which value is falsy?"), options: [same("An empty string"), same("`\"False\"`"), same("`[0]`"), same("`\"0\"`")], correctIndex: 0, explanation: same("An empty string has no content and is falsy.") },
    { question: same("What is the clearest test for a status in two allowed values?"), options: [same("`status in {\"new\", \"paid\"}`"), same("`status == \"new\" or \"paid\"`"), same("`status is \"new\"`"), same("`type(status) == bool`")], correctIndex: 0, explanation: same("Membership cleanly compares the value against each allowed item.") },
    { question: same("Why split a long checkout condition into named values?"), options: [same("It makes the business rule readable and testable"), same("It changes Python's precedence"), same("It makes all values true"), same("It removes the need for validation")], correctIndex: 0, explanation: same("Named checks clarify the rule and isolate what failed.") },
    { question: same("What does `0 <= rating <= 5` protect against?"), options: [same("A rating outside the allowed range"), same("A missing package"), same("A Unicode string"), same("A shared list")], correctIndex: 0, explanation: same("The chained comparison requires the rating to be within both limits.") },
  ],
  project: {
    name: same("Order Eligibility Checker"),
    goal: same("Calculate an order total and decide whether it can be fulfilled."),
    brief: same("This extends the tracker with an explicit fulfillment rule: payment or approved credit, available stock, and a valid quantity."),
    steps: [same("Create `order_eligibility.py`."), same("Store stock, requested quantity, unit price, payment state, and credit approval."), same("Calculate total, full boxes, and leftover items."), same("Validate quantity with a chained comparison."), same("Create named boolean values for payment, stock, and fulfillment."), same("Use membership to check an allowed shipping status and `is None` for an optional note.")],
    acceptance: [same("The script prints a total and a fulfillment decision."), same("A quantity outside the allowed range cannot be fulfilled."), same("The business rule uses named conditions or clear parentheses."), same("The code uses `==`, `in`, and `is None` for their correct jobs.")],
    stretch: [same("Add a separate reason message for each rejected rule."), same("Test the script with an empty note, a missing note, and a real note.")],
  },
};
