import type { LessonDay } from "@/lib/learn/lesson-types";

const same = (en: string) => ({ en, np: en, jp: en });

export const PYTHON_DAY_5_LESSONS: LessonDay = {
  day: 5,
  label: same("Phase 0 · Python Foundations"),
  title: same("Conditional Logic"),
  overview: same("Turn boolean rules into readable `if`, `elif`, and `else` decisions that explain what the program should do next."),
  totalMinutes: 85,
  difficulty: same("Beginner"),
  lessons: [
    {
      id: "python-if-else",
      title: same("Choose a path with if, elif, and else"),
      durationMinutes: 18,
      explanation: same("Conditionals let a program choose a path. `if` runs when its condition is truthy. `elif` checks another condition only if the earlier branch did not run. `else` is the fallback when no earlier condition matched. Python runs only the first matching branch in one `if` chain.\n\nOrder branches from most specific to most general. In delivery tracking, check `\"delivered\"` before a generic `else` that reports an unknown status. A final `else` is useful when every possible case has a sensible fallback. If an unexpected value should be treated as an error, later code may raise or log it instead of quietly pretending it is valid."),
      diagram: "status == \"delivered\"? ─ yes ─► show delivered message\n             │ no\nstatus == \"delayed\"?   ─ yes ─► show delay message\n             │ no\n             └──────────────► show status needs review",
      codeExample: { title: same("Show delivery status"), code: "status = \"delayed\"\n\nif status == \"delivered\":\n    print(\"Package delivered\")\nelif status == \"delayed\":\n    print(\"Package is delayed\")\nelse:\n    print(\"Status needs review\")" },
      keyTakeaways: [same("Only the first matching branch in an `if` chain runs."), same("Use `elif` for an additional mutually exclusive case."), same("Use `else` for a meaningful fallback."), same("Put specific conditions before broad ones.")],
      commonMistakes: [same("Writing separate `if` statements when only one status message should appear."), same("Putting a broad condition before a specific one, making the specific branch unreachable."), same("Treating unknown input as a valid business state without a review path.")],
      quiz: [{ question: same("How many branches run in one matching `if`/`elif`/`else` chain?"), options: [same("At most one"), same("All true branches"), same("Always two"), same("None")], correctIndex: 0, explanation: same("Python stops the chain after the first true condition.") }],
    },
    {
      id: "python-readable-conditions",
      title: same("Write conditions people can review"),
      durationMinutes: 17,
      explanation: same("A good conditional reads like a policy. Prefer names such as `has_valid_address` and `can_ship` over repeating a long expression in several places. Keep each condition focused on one decision. Earlier, you learned that `and`, `or`, membership, and comparisons produce booleans. Conditional code is where those values become actions.\n\nAvoid double negatives like `if not is_not_paid:`. They slow down every reader. Prefer `if is_paid:`. When a condition gets long, calculate named booleans first, then combine them. This helps you test a rejected order and explain the failure to a customer or support teammate."),
      diagram: "has_valid_payment ─┐\nhas_stock         ├─► can_ship ─► if can_ship\nhas_valid_address ┘",
      codeExample: { title: same("Express a shipping policy"), code: "has_valid_payment = True\nhas_stock = True\nhas_valid_address = False\n\ncan_ship = has_valid_payment and has_stock and has_valid_address\n\nif can_ship:\n    print(\"Create shipping label\")\nelse:\n    print(\"Order needs attention\")" },
      keyTakeaways: [same("Name complex boolean rules before using them."), same("Prefer positive names such as `is_paid`."), same("One condition should answer one decision."), same("Readable conditions are easier to test and change.")],
      commonMistakes: [same("Repeating a long condition in several branches."), same("Using a variable name that hides whether `True` means approval or rejection."), same("Checking truthiness when the business rule needs specific validation.")],
      quiz: [{ question: same("Which variable name is clearest in an `if` condition?"), options: [same("`has_valid_address`"), same("`check`"), same("`not_invalid`"), same("`value2`")], correctIndex: 0, explanation: same("A positive, descriptive boolean makes the condition understandable without extra translation.") }],
    },
    {
      id: "python-nested-conditions",
      title: same("Nest only when decisions depend on earlier ones"),
      durationMinutes: 16,
      explanation: same("A nested conditional is an `if` inside another `if`. Use one when the inner decision only makes sense after the outer decision passes. For example, check whether an order is paid before deciding whether its delivery speed qualifies for same-day dispatch.\n\nDeep nesting can make code difficult to follow because every level adds indentation. If you find yourself three or four levels deep, consider a guard clause, a helper function, or named booleans. Nesting is not wrong; it should reflect a real dependency between decisions, not compensate for a condition that was never clearly designed."),
      diagram: "is_paid?\n  │ yes\n  ▼\nhas_stock?\n  │ yes\n  ▼\ncreate label",
      codeExample: { title: same("Nest a dependent check"), code: "is_paid = True\nhas_stock = True\n\nif is_paid:\n    if has_stock:\n        print(\"Create shipping label\")\n    else:\n        print(\"Payment received, waiting for stock\")\nelse:\n    print(\"Wait for payment\")" },
      keyTakeaways: [same("Nest when the second question depends on the first."), same("Keep nesting shallow."), same("A nested `else` belongs to the closest matching `if`."), same("Use guard clauses or helpers when indentation grows.")],
      commonMistakes: [same("Misaligning an `else` so it belongs to the wrong `if`."), same("Nesting unrelated checks instead of writing one clear combined rule."), same("Adding another nested level rather than handling an early rejection.")],
      quiz: [{ question: same("When is a nested `if` useful?"), options: [same("When the inner decision depends on the outer condition passing"), same("Whenever there are two variables"), same("To avoid using booleans"), same("To convert strings")], correctIndex: 0, explanation: same("Nesting shows that the second question matters only inside the first branch.") }],
    },
    {
      id: "python-guard-clauses",
      title: same("Stop early with guard clauses"),
      durationMinutes: 18,
      explanation: same("A <b>guard clause</b> handles an invalid, missing, or uninteresting case first, then lets the main path stay flat. Guard clauses are especially useful inside functions, where `return` can stop work immediately. They prevent the happy path from being buried under several levels of indentation.\n\nImagine an order-label function. If payment is missing, return a clear result. If stock is missing, return another. The remaining code can focus on creating the label. A guard clause should not hide cleanup that must happen later. When a function owns a file, lock, or network resource, use the right cleanup pattern as you learn those topics."),
      diagram: "missing payment? ─ yes ─► return reason\n      │ no\nmissing stock?   ─ yes ─► return reason\n      │ no\n      └──────────────► create label",
      codeExample: { title: same("Keep the happy path flat"), code: "def label_result(is_paid: bool, has_stock: bool) -> str:\n    if not is_paid:\n        return \"Waiting for payment\"\n    if not has_stock:\n        return \"Waiting for stock\"\n\n    return \"Shipping label created\"\n\nprint(label_result(True, True))" },
      keyTakeaways: [same("Guard clauses handle early exits first."), same("They keep the main path less indented."), same("A returned value should explain the outcome."), same("Use guards for genuine stop conditions, not every small branch.")],
      commonMistakes: [same("Returning a vague `False` when a caller needs to know why the order stopped."), same("Using guards outside a function and expecting `return` to work."), same("Skipping essential cleanup after an early exit in resource-owning code.")],
      quiz: [{ question: same("What is the main benefit of a guard clause?"), options: [same("It handles stop conditions early and keeps the main path flat"), same("It makes all conditions true"), same("It replaces tests"), same("It changes variable types")], correctIndex: 0, explanation: same("Early returns avoid unnecessary nesting around the successful case.") }],
    },
    {
      id: "python-conditional-expressions",
      title: same("Use a conditional expression for small choices"),
      durationMinutes: 16,
      explanation: same("A conditional expression, sometimes called a ternary expression, selects one value in a single line: `\"paid\" if is_paid else \"unpaid\"`. It is good for a short, obvious value choice, often when building a display label.\n\nDo not pack whole workflows, side effects, or long conditions into one. An ordinary `if` block is clearer when each branch does more than choose one simple value. The question is not whether one line is cleverer. It is whether a future reader sees the business decision immediately."),
      diagram: "is_paid?\n  │ yes          │ no\n  ▼              ▼\n\"Paid\"       \"Unpaid\"\n        │\n        ▼\nstatus_label",
      codeExample: { title: same("Make a small display choice"), code: "is_paid = True\nstatus_label = \"Paid\" if is_paid else \"Payment pending\"\nprint(status_label)\n\n# Use a full if block when each branch has several actions." },
      keyTakeaways: [same("Conditional expressions choose one of two values."), same("They are best for short, obvious choices."), same("Use an `if` block for multi-step actions."), same("Readability matters more than saving lines.")],
      commonMistakes: [same("Nesting several conditional expressions into a hard-to-read line."), same("Using a conditional expression for logging, database writes, or other side effects."), same("Confusing its order: the true value appears before `if`.")],
      quiz: [{ question: same("When is a conditional expression a good fit?"), options: [same("Choosing one short display value from two options"), same("Running a multi-step checkout workflow"), same("Replacing all error handling"), same("Checking object identity")], correctIndex: 0, explanation: same("It is concise and clear when it simply selects one value.") }],
    },
  ],
  finalQuiz: [
    { question: same("Why should specific conditions appear before broad fallbacks?"), options: [same("So the specific case is not hidden by an earlier match"), same("So Python runs every branch"), same("So indentation is ignored"), same("So `else` becomes required")], correctIndex: 0, explanation: same("An `if` chain stops at the first true branch.") },
    { question: same("What does a guard clause usually do?"), options: [same("Returns early for a condition that prevents the main work"), same("Runs both `if` and `else`"), same("Changes a string into a number"), same("Copies a list")], correctIndex: 0, explanation: same("It handles a stop condition before the primary path.") },
    { question: same("Which code is clearest for an order that needs payment, stock, and address?"), options: [same("Named booleans combined into `can_ship`"), same("One long unnamed condition repeated everywhere"), same("Nested ternaries for every action"), same("A comment that says it works")], correctIndex: 0, explanation: same("Named rules make the policy clear and independently testable.") },
    { question: same("When should you use an `elif`?"), options: [same("For another mutually exclusive case after an `if`"), same("To run every matching case"), same("To compare object identity"), same("To create a variable")], correctIndex: 0, explanation: same("`elif` is another branch in a single decision chain.") },
    { question: same("What is a risk of deep nesting?"), options: [same("The successful path becomes hard to read"), same("Python removes all booleans"), same("Strings become mutable"), same("It makes `return` invalid")], correctIndex: 0, explanation: same("Many indentation levels obscure the flow and make branches easier to misread.") },
    { question: same("Which is appropriate for `\"Paid\"` versus `\"Payment pending\"`?"), options: [same("A short conditional expression"), same("A five-level nested `if`"), same("`id()`"), same("A virtual environment")], correctIndex: 0, explanation: same("A simple two-value choice is an appropriate use of a conditional expression.") },
  ],
  project: {
    name: same("Delivery Decision Engine"),
    goal: same("Return a clear shipment decision from payment, stock, address, and priority data."),
    brief: same("This joins Days 1–4 into a simple delivery workflow. The goal is not a large app. It is code whose decisions are clear enough for a customer-support person to explain."),
    steps: [same("Create `delivery_decision.py`."), same("Define values for payment, stock, address, delivery status, and priority."), same("Use `if`/`elif`/`else` to present a status message."), same("Create positive named booleans for each shipment requirement."), same("Write a function with guard clauses that returns the first blocking reason or a success message."), same("Use a conditional expression only for a short priority label.")],
    acceptance: [same("The function returns a distinct message for missing payment, stock, and address."), same("Only one customer-facing status branch appears."), same("The happy path is not buried inside deep nesting."), same("Variable names make the decision policy understandable without extra comments.")],
    stretch: [same("Add a manager-review branch for an unknown status."), same("Write down three input combinations and the expected result before running the script.")],
  },
};
