import type { LessonDay, LessonQuizQuestion } from "@/lib/learn/lesson-types";

const same = (en: string) => ({ en, np: en, jp: en });
const q = (question: string, options: string[], correctIndex: number, explanation: string): LessonQuizQuestion => ({ question: same(question), options: options.map(same), correctIndex, explanation: same(explanation) });

export const PYTHON_DAY_2_LESSONS: LessonDay = {
  day: 2, label: same("Phase 0 · Python Foundations"), title: same("Variables & Data Types"), totalMinutes: 110, difficulty: same("Beginner"),
  overview: same("Model real application information with clear names, appropriate value types, safe conversions, and an understanding of when two names share one mutable object."),
  lessons: [
    {
      id: "python-variables", title: same("Variables name values, not boxes"), durationMinutes: 20,
      explanation: same("<b>A variable is a name that refers to a value.</b> `package_status = \"packed\"` lets the program use that value later without repeating it. Assignment with `=` creates or rebinds a name. Python names normally use lowercase `snake_case`: `customer_email`, `total_price`, and `is_paid` communicate the business meaning.\n\n<b>Beginner:</b> Names start with a letter or underscore, may contain digits and underscores, and cannot use spaces, hyphens, or Python keywords such as `class` and `for`. A descriptive name saves more time than a comment beside `x` explaining what it secretly means.\n\n<b>Practical scenario:</b> In an order flow, `quantity`, `unit_price`, and `is_paid` each represent a different fact. Reusing one name for unrelated values makes a later bug hard to spot because the program still runs but its meaning changes.\n\n<b>Production:</b> Keep names consistent across API payloads, database mapping, and business logic where possible. A clear name reduces mistakes in reviews and tests. Do not leak sensitive data into broadly visible names, logs, or debug output."),
      diagram: "package_status ───► \"packed\"\ncustomer_name ───► \"Mina\"\n\nNames refer to values.",
      codeExample: { title: same("Basic, practical, and production naming"), code: "# Basic\nname = \"Mina\"\n\n# Practical\npackage_id = \"PKG-4821\"\ncustomer_name = \"Mina\"\nis_delivered = False\n\n# Production-style: names express the rule\nis_ready_for_dispatch = is_paid and has_stock", details: same("Use a short name only when its meaning is obvious from a very small scope, such as a loop index. Use business names for values that survive beyond one expression.") },
      keyTakeaways: [same("`=` assigns a value to a name."), same("Use descriptive `snake_case` names."), same("A name can be rebound to a new value."), same("Avoid Python keywords and ambiguous names.")],
      commonMistakes: [same("<b>Using `data`, `x`, or `value` for important business facts.</b> A future reader cannot see whether the value is a price, status, or customer ID."), same("<b>Using `=` as a comparison.</b> Assignment changes a name; `==` compares two values.")],
      quiz: [q("Which name follows normal Python style for a customer's email?", ["`customer_email`", "`CustomerEmail`", "`customer-email`", "`customer email`"], 0, "Python variables conventionally use lowercase words joined with underscores."), q("Why is `is_ready_for_dispatch` better than `check`?", ["It states the boolean business rule", "It runs faster", "It changes the type", "It creates a class"], 0, "A descriptive boolean lets a reader understand what `True` means in a condition.")],
    },
    {
      id: "python-basic-types", title: same("Choose int, float, str, bool, and None deliberately"), durationMinutes: 22,
      explanation: same("<b>Data types describe what a value means and what operations are valid.</b> `int` holds whole numbers, `float` holds decimals, `str` holds text, and `bool` is exactly `True` or `False`. `None` means a value is deliberately absent or not assigned yet.\n\n<b>Beginner:</b> A booking can have `guest_count = 2`, `rating = 4.8`, `guest_name = \"Aki\"`, `is_confirmed = True`, and `room_number = None`. Do not use `0` or an empty string when the value is unknown if zero or an empty string could be real data.\n\n<b>Practical scenario:</b> A postal code should often remain text because leading zeroes matter. A price may display as a decimal, but production payment systems usually use `Decimal` or smallest currency units rather than binary float arithmetic.\n\n<b>Production:</b> Types are part of a system contract. Validate data at API, file, and user-input boundaries. Store clear missing-state rules so an unset field is not confused with false, zero, or an intentionally blank answer."),
      diagram: "2       → int\n4.8     → float\n\"Aki\"   → str\nTrue    → bool\nNone    → no value yet",
      codeExample: { title: same("Model booking information"), code: "guest_count = 2\nnightly_rate = 120.50\nguest_name = \"Aki\"\nis_confirmed = True\nroom_number = None\n\nprint(type(nightly_rate))", details: same("`type()` helps inspect a confusing runtime value. It is a debugging and learning tool, not a substitute for validating a real business rule.") },
      keyTakeaways: [same("Use `int` for whole numbers and `float` for decimals."), same("Use `str` for text, including IDs and codes."), same("Use `bool` for true or false state."), same("Use `None` for a meaningful missing value.")],
      commonMistakes: [same("<b>Storing postal codes as integers.</b> Leading zeroes can disappear."), same("<b>Using empty text for every missing value.</b> An empty note and an unknown phone number may need different handling."), same("<b>Using float blindly for money.</b> Rounding behavior can matter in financial systems.")],
      quiz: [q("Which value best represents an unassigned driver?", ["`None`", "`False`", "`0`", "`\"none\"`"], 0, "`None` clearly states that no driver has been assigned."), q("Why might a postal code be a string?", ["Leading zeroes and formatting can matter", "Strings are always faster", "Integers cannot hold digits", "It is a boolean"], 0, "A postal code identifies an area; it is not usually a number to calculate with.")],
    },
    {
      id: "python-dynamic-strong", title: same("Dynamic typing still has strong rules"), durationMinutes: 20,
      explanation: same("<b>Python is dynamically typed.</b> You do not declare a type beside every variable; Python determines the type from the value when code runs. A name can refer to an integer now and a string later, although changing a name's meaning inside one workflow is usually confusing.\n\n<b>Python is also strongly typed.</b> It does not silently guess how to combine unrelated values. `\"3\" + 2` fails because Python cannot know whether you meant text `\"32\"` or number `5`. This prevents hidden mistakes at the boundary between user input and program data.\n\n<b>Practical scenario:</b> Form and command-line input normally arrives as text. Convert it once when it enters the app, then let order calculations work with real numbers. Use `type()` to diagnose surprise values, but choose validation rules based on what the business accepts.\n\n<b>Production:</b> Type hints, validation libraries, and tests make dynamic Python safer in larger systems. They do not replace runtime checks for data arriving from browsers, APIs, files, or queues."),
      diagram: "quantity = \"3\"  → str\nint(quantity)   → 3\n\nPython permits reassignment,\nbut refuses unclear mixed-type operations.",
      codeExample: { title: same("Inspect and convert intentional input"), code: "quantity_from_form = \"3\"\nprint(type(quantity_from_form))\n\nquantity = int(quantity_from_form)\nprint(quantity + 2)\n\n# \"3\" + 2 raises TypeError", details: same("Convert at the input boundary. The rest of the application should not repeatedly guess whether quantity is text or a number.") },
      keyTakeaways: [same("Python infers value types at runtime."), same("Dynamic does not mean type-free."), same("Strong typing rejects ambiguous mixed-type operations."), same("Use `type()` to inspect surprising values.")],
      commonMistakes: [same("<b>Rebinding one variable from price to text in a long function.</b> The code becomes harder to reason about even if Python permits it."), same("<b>Assuming browser input is numeric.</b> Input arrives as text until you validate and convert it.")],
      quiz: [q("Why does `\"3\" + 2` fail?", ["Python will not guess how to combine text and a number", "Strings cannot contain digits", "Integers cannot be added", "The REPL is required"], 0, "Python is strongly typed and requires an explicit conversion."), q("When should an app convert a quantity from a form?", ["At the input boundary before calculations", "Only after displaying the total", "Never", "Inside every function"], 0, "Early conversion keeps the application core working with a known type.")],
    },
    {
      id: "python-conversion", title: same("Convert and validate input safely"), durationMinutes: 20,
      explanation: same("<b>Type conversion turns one kind of value into another.</b> `int(\"25\")`, `float(\"19.99\")`, and `str(42)` are explicit conversions. `bool(value)` follows truthiness rules, which is useful but can surprise beginners: `bool(\"False\")` is `True` because it is non-empty text.\n\n<b>Beginner:</b> Conversion can fail. `int(\"two\")` raises `ValueError`. That is useful evidence that input did not match the rule. Later, use `try` and `except` to turn that technical error into a helpful user message.\n\n<b>Practical scenario:</b> An order quantity from a form must become an integer before multiplying by a unit price. Convert once, reject invalid input, then continue with trusted numeric values.\n\n<b>Production:</b> Validate allowed ranges as well as types. A valid integer can still be an invalid quantity if it is negative, too large, or exceeds stock. Never treat conversion alone as complete business validation."),
      diagram: "Form input: \"3\"\n      │ int()\n      ▼\nProgram value: 3\n      │ validate range\n      ▼\nCalculate total",
      codeExample: { title: same("Convert an order quantity"), code: "quantity_text = \"3\"\nunit_price_text = \"14.50\"\n\nquantity = int(quantity_text)\nunit_price = float(unit_price_text)\ntotal = quantity * unit_price\nprint(f\"Total: ${total:.2f}\")", details: same("In a real checkout, validate quantity and currency rules before charging. Formatting with `:.2f` is for display; it does not solve financial precision by itself.") },
      keyTakeaways: [same("Use explicit conversion for external input."), same("Conversion can raise `ValueError`."), same("Validate ranges after type conversion."), same("Do not expect `bool(\"False\")` to be false.")],
      commonMistakes: [same("<b>Using `int()` for a decimal price.</b> It removes fractional data."), same("<b>Using truthiness as full validation.</b> A non-empty invalid email is still truthy."), same("<b>Converting the same input in every function.</b> Convert and validate at the boundary once.")],
      quiz: [q("What does `int(\"25\")` produce?", ["The integer `25`", "The string `\"25\"`", "The float `25.0`", "A boolean"], 0, "`int()` converts a valid whole-number string into an integer."), q("Why is `bool(\"False\")` true?", ["The string is non-empty", "Python reads its English meaning", "All booleans are true", "It converts to None"], 0, "Truthiness checks whether the string has content, not whether it spells a boolean word.")],
    },
    {
      id: "python-mutability", title: same("Understand mutability, identity, and shared references"), durationMinutes: 22,
      explanation: same("<b>Immutable values cannot change in place.</b> Strings, integers, floats, booleans, and tuples are common immutable values. When you appear to change a string, Python creates a new string and points the name at it. Lists and dictionaries are mutable: their contents can change while the object remains the same.\n\n<b>Identity:</b> `id()` shows an object's identity during one program run. It is useful for learning and debugging references, not as a database ID. Use `==` to ask whether values have equal content. Use `is` to ask whether two names are the same object, especially `value is None`.\n\n<b>Practical scenario:</b> If `orders_b = orders_a`, both names reference one list. Appending through one name changes the other view. This surprises new developers and can become a production bug when a function silently mutates a caller's cart or configuration.\n\n<b>Production:</b> Decide whether a function may mutate input. Make that behavior obvious through its name and documentation, or return a new value. Copy nested data deliberately: a shallow copy creates a new outer container but still shares nested mutable objects."),
      diagram: "orders_a ─┐\n          ├──► [\"A-101\"]\norders_b ─┘\n\nappend through either name changes one shared list.",
      codeExample: { title: same("Compare content and identity"), code: "orders_a = [\"A-101\"]\norders_b = orders_a\norders_b.append(\"A-102\")\n\nprint(orders_a)\nprint(orders_a is orders_b)\nprint(orders_a == orders_b)\nprint(id(orders_a))", details: same("Use `is None` for missing values. Do not use `is` for normal string or numeric equality, even if it sometimes appears to work.") },
      keyTakeaways: [same("Strings and numbers are immutable; lists and dictionaries are mutable."), same("Assignment can create another name for one mutable object."), same("Use `==` for equal content and `is None` for a missing sentinel."), same("`id()` is a learning tool, not a permanent identifier.")],
      commonMistakes: [same("<b>Using `is` for ordinary strings or numbers.</b> Identity is not value equality."), same("<b>Mutating a list passed into a function without warning.</b> The caller sees a change it did not request."), same("<b>Assuming a shallow copy duplicates nested lists.</b> Nested objects remain shared.")],
      quiz: [q("Which operator should check whether an optional value is missing?", ["`is None`", "`== None` only", "`id(None)`", "`in None`"], 0, "`None` is a singleton sentinel, so identity is the intended check."), q("Why can `orders_b.append()` change `orders_a`?", ["Both names refer to the same mutable list", "Lists are immutable", "Append copies every list", "Python loses variables"], 0, "Assignment shares the referenced object unless you make a copy.")],
    },
  ],
  finalQuiz: [
    q("Which name follows Python convention?", ["`delivery_status`", "`DeliveryStatus`", "`delivery-status`", "`delivery status`"], 0, "Python variables normally use lowercase words joined with underscores."),
    q("Which type best represents an unassigned room?", ["`None`", "`0`", "`False`", "`\"none\"`"], 0, "`None` makes the missing state explicit."),
    q("What does dynamic typing mean?", ["Python infers a value type at runtime", "Python has no types", "Every name is a string", "Only lists change type"], 0, "The interpreter determines the type from the assigned value."),
    q("What does strong typing prevent?", ["Ambiguous mixed-type operations", "Every conversion", "All reassignment", "All runtime errors"], 0, "Python asks you to convert deliberately instead of guessing."),
    q("Which conversion handles numeric form text?", ["`int(quantity_text)`", "`bool(quantity_text)`", "`id(quantity_text)`", "`list(quantity_text)`"], 0, "Use `int()` when the input must be a whole number."),
    q("What else must be checked after a quantity converts successfully?", ["Its allowed business range", "Its comment text", "Its file extension", "Its identity only"], 0, "A number can have the correct type but still be negative or exceed stock."),
    q("What is `bool(\"False\")`?", ["`True`", "`False`", "`None`", "An error"], 0, "The non-empty string is truthy regardless of its letters."),
    q("Which comparison checks equal content?", ["`==`", "`is`", "`id()`", "`=`"], 0, "`==` compares values; `is` compares object identity."),
    q("Why use `id()` carefully?", ["It only identifies an object during the current run", "It creates a copy", "It validates input", "It is a database key"], 0, "Object identity is not a persistent business identifier."),
    q("What is the risk of shared mutable input?", ["One caller can change another caller's view", "Strings stop working", "Types disappear", "Python cannot loop"], 0, "A list or dictionary reference can be changed through any name pointing to it."),
  ],
  project: {
    name: same("Order Summary Builder"),
    goal: same("Create a command-line order summary from typed, validated customer and product data."),
    brief: same("This adds trustworthy data handling to the delivery tracker. The script should keep numbers as numbers, use `None` for genuinely unknown data, and make shared mutable state visible."),
    steps: [same("Create `order_summary.py` in the delivery tracker folder."), same("Store customer name, product name, quantity, price, payment state, and an optional delivery note."), same("Convert a text quantity before calculating the total, then validate its allowed range."), same("Use `type()` while testing, then remove temporary inspection output."), same("Create a list of order IDs and demonstrate what happens when two names reference it."), same("Print a clear summary without treating missing and empty values as the same thing.")],
    acceptance: [same("The total uses numeric arithmetic, not text concatenation."), same("The script distinguishes `None` from an empty note."), same("Variable names use clear `snake_case`."), same("Invalid quantity text or range is recognized as a separate problem."), same("The shared-list demonstration is understood and does not become accidental application behavior.")],
    stretch: [same("Add `try` and `except ValueError` for invalid quantity text."), same("Create a shallow copy of nested order data and explain what remains shared."), same("Write a small test table of valid and invalid order inputs.")],
  },
};
