import type { LessonDay } from "@/lib/learn/lesson-types";

const same = (en: string) => ({ en, np: en, jp: en });

export const PYTHON_DAY_10_LESSONS: LessonDay = {
  day: 10, label: same("Phase 1 · Core Python"), title: same("Comprehensions"), totalMinutes: 75, difficulty: same("Beginner"),
  overview: same("Transform and filter collections concisely, while recognizing the point where a clear loop is easier to maintain."),
  lessons: [
    {
      id: "python-list-comprehensions", title: same("Build lists from a clear transformation"), durationMinutes: 20,
      explanation: same("A <b>list comprehension</b> creates a list by describing one output expression, the source iterable, and an optional filter. `[price * 0.9 for price in prices]` is concise because the transformation is small and direct. It is equivalent to a `for` loop that appends one result at a time.\n\nUse a comprehension when a reader can understand it in one glance. Use a normal loop when the work needs several steps, error handling, logging, or a meaningful name for intermediate values. Comprehensions create the entire result in memory, so do not use one blindly for a huge stream when a generator or incremental processing is a better fit."),
      diagram: "prices → for each price → price * 0.9 → sale_prices\n\n[price * 0.9 for price in prices]",
      codeExample: { title: same("Calculate sale prices"), code: "prices = [10.0, 25.0, 40.0]\nsale_prices = [price * 0.9 for price in prices]\n\nprint(sale_prices)" },
      keyTakeaways: [same("A list comprehension builds a new list."), same("Put the output expression before `for`."), same("Use one for a simple, visible transformation."), same("A normal loop is better for multi-step work.")],
      commonMistakes: [same("Using a comprehension only for side effects such as `print()` or database writes."), same("Hiding a complicated workflow in one line."), same("Creating a large list when results should be processed one at a time.")],
      quiz: [{ question: same("What does `[x * 2 for x in [1, 2]]` create?"), options: [same("`[2, 4]`"), same("`[1, 2]`"), same("A set"), same("Nothing")], correctIndex: 0, explanation: same("The expression doubles each source value and the comprehension collects the results.") }],
    },
    {
      id: "python-filtered-comprehensions", title: same("Filter values without losing the rule"), durationMinutes: 18,
      explanation: same("Add an `if` after the `for` to filter input: `[item for item in items if item.in_stock]`. This creates a new collection containing only values that pass the condition. Keep the condition readable and name it in a regular loop when it represents an important policy.\n\nA conditional expression before `for` chooses between two output values, while an `if` after `for` filters values out. They solve different problems. For example, `\"ready\" if paid else \"hold\"` transforms every order, while `for order in orders if order.paid` keeps only paid orders."),
      diagram: "orders\n  │ filter: paid?\n  ▼\npaid_orders\n  │ transform\n  ▼\norder IDs",
      codeExample: { title: same("Find ready-to-ship IDs"), code: "orders = [\n    {\"id\": \"A-1\", \"paid\": True, \"stock\": True},\n    {\"id\": \"A-2\", \"paid\": False, \"stock\": True},\n]\n\nready_ids = [order[\"id\"] for order in orders if order[\"paid\"] and order[\"stock\"]]\nlabels = [\"paid\" if order[\"paid\"] else \"hold\" for order in orders]\nprint(ready_ids, labels)" },
      keyTakeaways: [same("An `if` after `for` filters input."), same("A conditional expression before `for` transforms every item."), same("Comprehensions return new collections."), same("Name important business rules when a line grows long.")],
      commonMistakes: [same("Putting the filter condition in the wrong place."), same("Repeating an expensive computation in both expression and filter."), same("Using a comprehension when a policy deserves separate validation and error messages.")],
      quiz: [{ question: same("Where does a filtering condition go in a list comprehension?"), options: [same("After the `for` clause"), same("Before the output expression"), same("Inside square brackets only"), same("After `print`")], correctIndex: 0, explanation: same("The filter follows the iterable clause: `[result for item in items if rule]`.") }],
    },
    {
      id: "python-set-dict-comprehensions", title: same("Use set and dictionary comprehensions deliberately"), durationMinutes: 20,
      explanation: same("Set comprehensions use `{expression for item in items}` and naturally remove duplicates. Dictionary comprehensions use `{key_expression: value_expression for item in items}` to build a keyed lookup or report. They are useful for turning a list of records into an ID lookup or extracting unique delivery cities.\n\nDuplicate dictionary keys keep the later value, so define that collision rule before using a comprehension for records. Nested comprehensions can be correct for small grids, but they become hard to read quickly. Prefer a named loop whenever nesting hides what one input item becomes."),
      diagram: "shipments\n  │ set comprehension\n  ▼\nunique cities\n\nshipments\n  │ dict comprehension\n  ▼\nID → status lookup",
      codeExample: { title: same("Create delivery lookups"), code: "shipments = [\n    {\"id\": \"A-1\", \"city\": \"Tokyo\", \"status\": \"packed\"},\n    {\"id\": \"A-2\", \"city\": \"Osaka\", \"status\": \"shipped\"},\n]\n\ncities = {shipment[\"city\"] for shipment in shipments}\nstatus_by_id = {shipment[\"id\"]: shipment[\"status\"] for shipment in shipments}\nprint(cities, status_by_id)" },
      keyTakeaways: [same("Set comprehensions produce unique values."), same("Dictionary comprehensions build key-value mappings."), same("Later duplicate dictionary keys win."), same("Keep nested comprehensions shallow.")],
      commonMistakes: [same("Using a set comprehension when output order matters."), same("Ignoring duplicate IDs while building a dictionary lookup."), same("Writing a nested comprehension that nobody can safely change.")],
      quiz: [{ question: same("What does a set comprehension guarantee?"), options: [same("Duplicate output values are removed"), same("Output keeps input order"), same("Keys are required"), same("The source changes")], correctIndex: 0, explanation: same("Sets contain unique elements and do not promise ordering.") }],
    },
    {
      id: "python-comprehension-readability", title: same("Choose readability over compression"), durationMinutes: 17,
      explanation: same("A comprehension is successful when it makes a simple collection operation shorter without making it harder to understand. Stop using one when it needs nested loops, several conditions, exception handling, logging, or side effects. A regular loop gives each step a name and a place to handle failures.\n\nThis choice matters in production reviews. A dense one-liner may be technically correct yet hide a business rule. Favor the version that lets a teammate explain what happens to an invalid shipment, an unexpected status, or a large batch. Clear code is usually the faster code to fix."),
      diagram: "Simple map/filter? ─ yes ─► comprehension\nSeveral steps or failures? ─► named for loop\n\nReadability is the decision rule.",
      codeExample: { title: same("Use a loop for multi-step validation"), code: "ready_ids = []\nfor shipment in shipments:\n    if not shipment.get(\"id\"):\n        print(\"Skipping shipment with no ID\")\n        continue\n    if shipment.get(\"status\") == \"packed\":\n        ready_ids.append(shipment[\"id\"])\n\nprint(ready_ids)" },
      keyTakeaways: [same("Comprehensions are for simple collection building."), same("Do not use them for side effects."), same("Use loops for multiple decisions or failure handling."), same("Prefer code that explains the business rule.")],
      commonMistakes: [same("Nesting several `for` and `if` clauses to avoid writing a loop."), same("Using a comprehension where validation failures must be reported."), same("Optimizing code length before understanding the data size and behavior.")],
      quiz: [{ question: same("When is a regular loop better than a comprehension?"), options: [same("When each item needs validation, logging, and several actions"), same("When doubling every number"), same("When collecting unique cities"), same("When building a simple ID lookup")], correctIndex: 0, explanation: same("A loop gives each processing step a clear place and avoids hiding side effects.") }],
    },
  ],
  finalQuiz: [
    { question: same("What does a list comprehension return?"), options: [same("A new list"), same("The original list"), same("Always a generator"), same("A dictionary")], correctIndex: 0, explanation: same("The square-bracket syntax creates a list.") },
    { question: same("What is the difference between filtering and a conditional expression in a comprehension?"), options: [same("Filtering removes inputs; a conditional expression chooses each output"), same("They are identical"), same("Filtering creates sets only"), same("Conditional expressions remove inputs")], correctIndex: 0, explanation: same("Their placement and purpose are different.") },
    { question: same("What is a good use of a dictionary comprehension?"), options: [same("Building shipment ID to status lookup"), same("Appending to a queue"), same("Retrying a request"), same("Checking tuple identity")], correctIndex: 0, explanation: same("A dictionary comprehension derives named key-value access from records.") },
    { question: same("What should you do when a comprehension needs logging and error handling?"), options: [same("Use a regular loop"), same("Add more nested clauses"), same("Use `pass`"), same("Use a set")], correctIndex: 0, explanation: same("A normal loop is clearer for multi-step work and side effects.") },
  ],
  project: { name: same("Delivery Dashboard Data Builder"), goal: same("Build concise report data from a shipment list while keeping validation readable."), brief: same("The tracker now turns raw shipment records into ready-to-ship IDs, unique city filters, and a status lookup."), steps: [same("Create a list of shipment dictionaries."), same("Build ready-to-ship IDs with a filtered list comprehension."), same("Build a unique city set and an ID-to-status dictionary."), same("Create display labels with a conditional expression."), same("Write one regular loop that logs and skips invalid shipment records."), same("Explain which duplicate-ID rule your lookup applies.")], acceptance: [same("The dashboard inputs are new collections, not mutations of the source list."), same("Invalid records are handled in the explicit loop."), same("City output is sorted before display."), same("The code uses comprehensions only where each line stays clear.")], stretch: [same("Compare the list-comprehension result with an equivalent loop, then choose the clearer version.")] },
};
