import type { LessonDay, LessonQuizQuestion } from "@/lib/learn/lesson-types";

const same = (en: string) => ({ en, np: en, jp: en });
const q = (question: string, options: string[], correctIndex: number, explanation: string): LessonQuizQuestion => ({ question: same(question), options: options.map(same), correctIndex, explanation: same(explanation) });
const lesson = (id: string, title: string, explanation: string, diagram: string, code: string, quiz: LessonQuizQuestion[]) => ({ id, title: same(title), durationMinutes: 22, explanation: same(explanation), diagram, codeExample: { title: same("Basic, practical, and production example"), code, details: same("Start with the small example, then apply the same rule to validated real application data. Keep text handling explicit so user-facing output is predictable.") }, keyTakeaways: [same("Strings are immutable, so methods return new text."), same("Validate assumptions before relying on a fixed text format."), same("Use clear formatting for user-facing messages."), same("Keep untrusted text separate from executable commands.")], commonMistakes: [same("<b>Assuming every input has the expected length or separator.</b> Validate external text before indexing or splitting it."), same("<b>Using text formatting to build SQL or shell commands.</b> Use parameterized APIs so data stays separate from instructions.")], quiz });

export const PYTHON_DAY_3_LESSONS: LessonDay = {
  day: 3, label: same("Phase 0 · Python Foundations"), title: same("Strings"), totalMinutes: 110, difficulty: same("Beginner"),
  overview: same("Create, inspect, transform, and format text safely. The delivery tracker uses strings for IDs, names, statuses, messages, and paths."),
  lessons: [
    lesson("python-string-create-index", "Create strings and read characters", "<b>A string is ordered text.</b> Create it with single or double quotes. Python counts positions from zero, so `code[0]` is the first character and `code[-1]` is the last. Indexing is useful for controlled formats, but an invalid position raises `IndexError`.\n\n<b>Beginner:</b> Use indexing when the format is guaranteed. <b>Practical:</b> a tracking code may have a known country prefix. <b>Production:</b> do not rely on character positions for unvalidated user input; check its format first or use a dedicated parser.", "tracking_code = \"JP-4821\"\n                  0123456\n\ncode[0]  → J\ncode[-1] → 1", "tracking_code = \"JP-4821\"\nprint(tracking_code[0])\nprint(tracking_code[-1])\nprint(len(tracking_code))", [q("What is the first index in a Python string?", ["`0`", "`1`", "`-1`", "`len(text)`"], 0, "Python sequences begin at zero."), q("What does `text[-1]` select?", ["The final character", "The first character", "The string length", "Nothing"], 0, "Negative one counts from the end.")]),
    lesson("python-string-slice", "Extract text with slicing", "<b>A slice takes a range without changing the original string.</b> `text[start:stop]` includes start and excludes stop. `code[:2]` takes the first two characters; `code[3:]` takes from position three onward.\n\n<b>Beginner:</b> learn that the stop index is excluded. <b>Practical:</b> split a controlled tracking code after validating its separator. <b>Production:</b> do not silently slice malformed external identifiers; report invalid data rather than deriving a wrong value.", "\"JP-4821\"\n  0123456\n\n[:2] → \"JP\"\n[3:] → \"4821\"", "code = \"JP-4821\"\nif len(code) >= 4 and code[2] == \"-\":\n    country = code[:2]\n    number = code[3:]\n    print(country, number)", [q("What does `\"python\"[1:4]` return?", ["`\"yth\"`", "`\"ytho\"`", "`\"pyt\"`", "`\"tho\"`"], 0, "The stop position is excluded."), q("Why validate a code before slicing?", ["The expected format may be absent", "Slices mutate text", "Strings have no length", "Python sorts the code"], 0, "External input can be shorter or differently formatted than expected.")]),
    lesson("python-string-methods", "Normalize and search text with methods", "<b>String methods return new text because strings are immutable.</b> `strip()` removes outer whitespace, `lower()` normalizes case, `replace()` swaps text, and `split()` separates parts.\n\n<b>Beginner:</b> save the returned value. <b>Practical:</b> normalize an email before a case-insensitive comparison. <b>Production:</b> normalization is not full validation. A non-empty string can still be an invalid email, address, or tracking code.", "raw email\n  │ strip().lower()\n  ▼\nnormalized email", "raw_email = \"  Mina@Example.com  \"\nemail = raw_email.strip().lower()\nusername, domain = email.split(\"@\")\nprint(username, domain)", [q("Why save `text = text.strip()`?", ["`strip()` returns new text", "Strings mutate automatically", "It converts to a list", "It validates all text"], 0, "Strings are immutable, so methods return a separate value."), q("What does `strip()` remove?", ["Outer whitespace", "Every space", "All letters", "Unicode"], 0, "It removes whitespace at the beginning and end.")]),
    lesson("python-formatting", "Format messages with f-strings", "<b>F-strings build readable text from values.</b> Prefix the string with `f`, then use braces for values or simple expressions. Format specifications such as `:.2f` control display precision.\n\n<b>Beginner:</b> use f-strings for a clear message. <b>Practical:</b> create a customer receipt from an ID, item count, and total. <b>Production:</b> never use f-strings to build SQL or shell commands from untrusted input; parameterized APIs keep data separate from executable instructions.", "values\n  │ f-string\n  ▼\ncustomer message", "customer = \"Mina\"\ntotal = 42.5\nprint(f\"Hi {customer}, total: ${total:.2f}\")", [q("What prefix enables f-string interpolation?", ["`f`", "`s`", "`p`", "`@`"], 0, "The `f` prefix evaluates expressions inside braces."), q("Why avoid f-strings for SQL with user input?", ["It can enable injection", "F-strings cannot show text", "SQL needs tuples only", "Python blocks databases"], 0, "Use the database driver's parameterized query interface instead.")]),
    lesson("python-special-strings", "Use escapes, raw strings, Unicode, and multiline text", "<b>Escape characters represent special text.</b> `\\n` means a new line. Raw strings, written `r\"...\"`, keep most backslashes literal and help with paths and regular expressions. Python strings support Unicode, so Japanese, Nepali, and emoji are ordinary text.\n\n<b>Beginner:</b> use triple quotes for multiline content. <b>Practical:</b> create a pickup notification with a new line and a Unicode status icon. <b>Production:</b> keep long user-facing templates in a deliberate location so wording and translations do not become scattered through business logic.", "Normal: \"Line 1\\nLine 2\"\nRaw: r\"C:\\Users\\mina\"\nUnicode: \"📦 Ready\"", "note = \"\"\"Hello Mina,\nYour package is ready.\nありがとう!\"\"\"\npath = r\"C:\\Users\\mina\\labels\"\nprint(note)\nprint(path)", [q("When is a raw string useful?", ["When text contains literal backslashes", "When converting to int", "When changing a list", "When checking identity"], 0, "Raw strings reduce escaping for backslash-heavy text."), q("What does `\\n` represent?", ["A new line", "A number", "A type", "An error"], 0, "It is the newline escape sequence.")]),
  ],
  finalQuiz: [
    q("Which index selects the last string character?", ["`-1`", "`0`", "`1`", "`len(text)`"], 0, "Negative one counts from the end."), q("What does a string slice create?", ["New text", "A changed original", "A dictionary", "A set"], 0, "Strings are immutable, so slicing returns a new string."), q("Why normalize an email copy with `strip().lower()`?", ["For consistent comparison", "To validate every address", "To make it numeric", "To remove its domain"], 0, "Normalization helps comparison but is not full validation."), q("What is the best tool for readable receipt text?", ["An f-string", "`id()`", "A set", "A virtual environment"], 0, "F-strings combine text and display values clearly."), q("Which method separates `name@example.com`?", ["`split(\"@\")`", "`append()`", "`sort()`", "`id()`"], 0, "Split separates text around a delimiter."), q("Why validate before splitting external text?", ["The expected delimiter may be absent", "Split changes the input", "Strings cannot be checked", "Unicode forbids delimiters"], 0, "External data may not match your assumed format."), q("What does `:.2f` control?", ["Two decimal display places", "String length", "A list index", "Unicode encoding"], 0, "It formats a floating value for display."), q("What is a raw string good for?", ["A backslash-heavy path", "A money calculation", "A tuple key", "An import"], 0, "Raw strings reduce escape noise in path-like text."), q("Can Python strings contain Japanese or emoji?", ["Yes, strings support Unicode", "Only with a package", "Only in the REPL", "Never"], 0, "Unicode text is ordinary Python string data."), q("What should replace f-string SQL construction?", ["Parameterized database queries", "More escaping guesses", "A longer string", "A raw string"], 0, "Parameters keep data separate from executable SQL."),
  ],
  project: { name: same("Shipment Message Generator"), goal: same("Turn shipment data into a validated, readable pickup message."), brief: same("The delivery tracker now needs text handling for IDs, customer details, paths, and notifications."), steps: [same("Create `shipment_message.py`."), same("Store a controlled tracking code, customer name, email, pickup location, and weight."), same("Validate the tracking-code separator before slicing its prefix."), same("Normalize a copied email value."), same("Build a multiline f-string message with a formatted weight and Unicode icon."), same("Add a raw-string local label path.")], acceptance: [same("The output includes customer, tracking code, and pickup details."), same("The original display name remains unchanged."), same("Malformed tracking data does not silently produce a wrong prefix."), same("The project does not format untrusted text into executable commands.")], stretch: [same("Handle blank customer names with a fallback greeting."), same("Write tests for a valid and malformed tracking code.")] },
};
