#!/usr/bin/env python3
"""Extract English strings from day-*-detail.ts and fill BACKEND_COPY_MAP (MyMemory API)."""

from __future__ import annotations

import hashlib
import json
import re
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DETAIL_GLOB = ROOT / "lib" / "backend-learning" / "day-*-detail.ts"
OUT_TS = ROOT / "lib" / "backend-learning" / "backend-copy-map-data.ts"
CACHE_JSON = ROOT / "scripts" / ".backend-copy-cache.json"


def ts_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def extract_strings(text: str) -> list[str]:
    found: list[str] = []
    for label in (
        "text",
        "caption",
        "title",
        "question",
        "answer",
        "tag",
        "callout",
    ):
        for m in re.finditer(rf'{label}:\s*"((?:[^"\\]|\\.)*)"', text):
            found.append(bytes(m.group(1), "utf-8").decode("unicode_escape"))
    om = re.search(r"overview:\s*\[([\s\S]*?)\]\s*,\s*sections", text)
    if om:
        for sm in re.finditer(r'"((?:[^"\\]|\\.)*)"', om.group(1)):
            found.append(sm.group(1).replace('\\"', '"'))
    for m in re.finditer(r"bullets:\s*\[([\s\S]*?)\]\s*(?:,|\})", text):
        for sm in re.finditer(r'"((?:[^"\\]|\\.)*)"', m.group(1)):
            found.append(sm.group(1).replace('\\"', '"'))
    return found


def translate_pair(q: str, tgt: str, retries: int = 3) -> str:
    """tgt: ne | ja (MyMemory uses ja not jp)."""
    if len(q) > 480:
        q = q[:477] + "..."
    pair = f"en|{tgt}"
    url = "https://api.mymemory.translated.net/get?" + urllib.parse.urlencode({"q": q, "langpair": pair})
    for attempt in range(retries):
        try:
            raw = urllib.request.urlopen(url, timeout=30).read()
            data = json.loads(raw.decode())
            return data["responseData"]["translatedText"]
        except Exception:
            time.sleep(1.5 * (attempt + 1))
    return q


def main() -> None:
    keys: list[str] = []
    seen: set[str] = set()
    for fp in sorted(ROOT.glob("lib/backend-learning/day-*-detail.ts")):
        text = fp.read_text(encoding="utf-8")
        for s in extract_strings(text):
            if s not in seen:
                seen.add(s)
                keys.append(s)

    cache: dict[str, dict[str, str]] = {}
    if CACHE_JSON.exists():
        cache = json.loads(CACHE_JSON.read_text(encoding="utf-8"))

    total = len(keys)
    for i, key in enumerate(keys):
        h = hashlib.sha256(key.encode()).hexdigest()[:16]
        entry = cache.get(key)
        if entry is None or "np" not in entry or "jp" not in entry:
            print(f"[{i+1}/{total}] translate ({len(key)} chars)...")
            np = translate_pair(key, "ne")
            time.sleep(0.35)
            jp = translate_pair(key, "ja")
            time.sleep(0.35)
            cache[key] = {"np": np, "jp": jp}
            CACHE_JSON.write_text(json.dumps(cache, ensure_ascii=False, indent=0), encoding="utf-8")
        else:
            print(f"[{i+1}/{total}] cached")

    lines = [
        "/**",
        " * Auto-generated by `scripts/gen-backend-copy-map.py`. Do not edit by hand.",
        " */",
        "export const BACKEND_COPY_MAP: Record<string, { np: string; jp: string }> = {",
    ]
    for key in keys:
        row = cache[key]
        lines.append(f'  "{ts_escape(key)}": {{ np: "{ts_escape(row["np"])}", jp: "{ts_escape(row["jp"])}" }},')
    lines.append("};")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print("Wrote", OUT_TS, "entries:", len(keys))


if __name__ == "__main__":
    main()
