export interface SupabaseConcept {
  id: number;
  section: string;
  title: string;
  tagline: string;
  description: string;
  note?: string;
  diagram?: string;
  example: string;
  tip: string;
  tags: string[];
}

export const SUPABASE_SECTIONS = [
  "Introduction",
  "Database & Tables",
  "Authentication",
  "Row Level Security",
  "Real-time",
  "Storage",
  "Edge Functions",
  "Advanced Patterns",
] as const;

export const SUPABASE_CONCEPTS: SupabaseConcept[] = [

  // ─────────────────────────────────────────────
  // INTRODUCTION
  // ─────────────────────────────────────────────
  {
    id: 1,
    section: "Introduction",
    title: "What is Supabase?",
    tagline: "The open-source Firebase alternative built on top of PostgreSQL",
    description:
      "Supabase is a <b>Backend-as-a-Service (BaaS)</b> — it gives you a complete backend for your app without having to write server code from scratch.\n\nThink of it like hiring a fully-staffed kitchen at a restaurant. Instead of building the kitchen yourself (buying equipment, hiring chefs, setting up ventilation), you walk in, sit at the counter, and just place your order. Supabase provides the kitchen — you focus on your app.\n\n<b>What does Supabase give you?</b>\n\n• <b>Database</b> — a real PostgreSQL database (the same database used by companies like Instagram and Spotify)\n• <b>Authentication</b> — sign up, sign in, OAuth (Google, GitHub), magic links — all built-in\n• <b>Storage</b> — upload and serve images, videos, and files\n• <b>Real-time</b> — listen to database changes live, without polling\n• <b>Edge Functions</b> — run small pieces of server-side code close to your users\n• <b>Auto-generated API</b> — your database tables automatically become API endpoints — no REST or GraphQL code to write\n\n<b>Why not just use Firebase?</b>\n\nFirebase (by Google) is the most popular BaaS. But it uses a NoSQL database (Firestore) which is harder to query for complex data. Supabase uses <b>PostgreSQL</b> — a powerful, battle-tested relational database. You get proper tables, joins, and SQL. Also, Supabase is open-source — you can self-host it on your own server if you ever want to.\n\n<b>When should you use Supabase?</b>\n\nSupabase is a great fit when:\n• You are building a web or mobile app and need a backend fast\n• You want a real SQL database (not a document store)\n• You need user authentication without implementing it yourself\n• Your team is small and you cannot afford to maintain a full backend",
    note:
      "Supabase is not a replacement for a custom backend in every case. If your app has very complex business logic, heavy background processing, or strict compliance requirements, you may still need a custom server. But for most apps — especially early-stage products — Supabase removes weeks of backend work.",
    diagram:
      "  YOUR APP  (React, Next.js, React Native, etc.)\n       │\n       │  supabase-js client library\n       ↓\n  ┌─────────────────────────────────────────────┐\n  │              SUPABASE PROJECT               │\n  │                                             │\n  │  ┌──────────┐  ┌──────────┐  ┌──────────┐  │\n  │  │ Database │  │   Auth   │  │ Storage  │  │\n  │  │(Postgres)│  │(GoTrue)  │  │  (S3)    │  │\n  │  └──────────┘  └──────────┘  └──────────┘  │\n  │                                             │\n  │  ┌──────────┐  ┌──────────────────────────┐ │\n  │  │Real-time │  │   Edge Functions (Deno)  │ │\n  │  │(Phoenix) │  └──────────────────────────┘ │\n  │  └──────────┘                               │\n  └─────────────────────────────────────────────┘\n\n  One project URL + one anon key = access to all services",
    example:
      "// Install the Supabase JS client\n// npm install @supabase/supabase-js\n\nimport { createClient } from '@supabase/supabase-js';\n\n// These two values come from your Supabase project dashboard\n// Settings → API → Project URL and Project API Keys\nconst supabaseUrl = 'https://your-project-ref.supabase.co';\nconst supabaseAnonKey = 'your-anon-public-key';\n\n// Create a single client instance — reuse it across your app\nexport const supabase = createClient(supabaseUrl, supabaseAnonKey);\n\n// Test it with a simple query\nconst { data, error } = await supabase.from('users').select('*');\n\nif (error) {\n  console.error('Something went wrong:', error.message);\n} else {\n  console.log('Users from your database:', data);\n}",
    tip: "Store your Supabase URL and anon key in environment variables (`.env.local` in Next.js), never hardcode them in your source files. The anon key is safe to expose in the browser — it is a public key — but good habits matter. Your service role key (in server-only code) is secret and should never be sent to the browser.",
    tags: ["BaaS", "PostgreSQL", "Open Source", "Backend", "Firebase Alternative"],
  },

  {
    id: 2,
    section: "Introduction",
    title: "How Supabase Works — The Architecture",
    tagline: "What happens behind the scenes when you call supabase.from('table').select()",
    description:
      "Understanding how Supabase is built helps you use it correctly and debug it when things go wrong.\n\n<b>Your database is a real PostgreSQL instance</b>\n\nWhen you create a Supabase project, you get a dedicated PostgreSQL database. This is not a simplified or watered-down version — it is the full PostgreSQL running in the cloud. You can run raw SQL, create views, write triggers, add indexes, and use any PostgreSQL feature.\n\n<b>PostgREST — the auto-API layer</b>\n\nPostgREST is an open-source tool that sits in front of your database and automatically turns your tables into a REST API. When you write `supabase.from('posts').select('*')`, the JS client sends an HTTP request to PostgREST, which translates it to a SQL query and returns the result.\n\nYou never write a single API route for basic CRUD — PostgREST does it for you based on your table structure.\n\n<b>GoTrue — the auth service</b>\n\nGoTrue is the authentication microservice Supabase runs alongside your database. It handles user sign-up, login, JWTs (JSON Web Tokens), and OAuth providers. When a user logs in, GoTrue issues a JWT that contains the user's ID. That JWT is included in every database request so PostgreSQL knows who is asking.\n\n<b>Realtime — live database changes</b>\n\nSupabase runs a Phoenix (Elixir) server that listens to PostgreSQL's built-in change feed (called logical replication). When a row changes, the Realtime server broadcasts the change to any connected clients over WebSockets.\n\n<b>Storage — file hosting</b>\n\nSupabase Storage is an S3-compatible file service with its own access control system (also backed by PostgreSQL RLS policies).",
    note:
      "The most important thing to understand: Supabase is not magic — it is a collection of well-known open-source tools (PostgreSQL, PostgREST, GoTrue, Phoenix) wrapped with a nice dashboard and a unified JS client. This means everything you learn about PostgreSQL applies directly to Supabase.",
    diagram:
      "  supabase.from('posts').select('*')\n          │\n          │  HTTP GET /posts   (with Authorization: Bearer <JWT>)\n          ↓\n  ┌───────────────┐\n  │  PostgREST    │  Parses URL into SQL\n  │  (REST → SQL) │  SELECT * FROM posts WHERE ...\n  └───────┬───────┘\n          │  SQL query\n          ↓\n  ┌───────────────┐\n  │  PostgreSQL   │  Runs query, enforces RLS policies\n  │  Database     │  Returns rows\n  └───────┬───────┘\n          │  JSON result\n          ↓\n  ┌───────────────┐\n  │  PostgREST    │  Serialises to JSON\n  └───────┬───────┘\n          │  HTTP 200 { data: [...] }\n          ↓\n      Your App",
    example:
      "// You write this in your app:\nconst { data, error } = await supabase\n  .from('posts')\n  .select('id, title, created_at')\n  .eq('published', true)\n  .order('created_at', { ascending: false })\n  .limit(10);\n\n// Supabase JS client translates that chain into this HTTP request:\n// GET https://your-project.supabase.co/rest/v1/posts\n//   ?select=id,title,created_at\n//   &published=eq.true\n//   &order=created_at.desc\n//   &limit=10\n//\n// PostgREST turns it into SQL:\n// SELECT id, title, created_at\n// FROM posts\n// WHERE published = true\n// ORDER BY created_at DESC\n// LIMIT 10;\n\n// You never write that SQL or that HTTP request manually.\n// The client handles it for you.",
    tip: "When you hit a bug you cannot explain, open the browser Network tab and look at the actual HTTP request the Supabase client is making. The URL shows you the exact query being run. The response body will contain PostgREST's error message, which is usually more descriptive than what the JS client surfaces.",
    tags: ["PostgREST", "Architecture", "PostgreSQL", "GoTrue", "Realtime", "REST API"],
  },

  {
    id: 3,
    section: "Introduction",
    title: "Setting Up Your First Supabase Project",
    tagline: "Create a project, find your keys, install the client, run your first query",
    description:
      "Getting started with Supabase takes about five minutes. Here is the exact sequence.\n\n<b>Step 1 — Create a project</b>\n\nGo to supabase.com and sign up. Click 'New Project', give it a name, choose a region close to your users, and set a database password. Supabase takes about 1-2 minutes to spin up your project.\n\n<b>Step 2 — Find your project URL and anon key</b>\n\nIn your project dashboard, go to Settings → API. You will see:\n• <b>Project URL</b> — something like `https://abcdefgh.supabase.co` — this is your project's unique address\n• <b>anon public key</b> — a long JWT string. This key is safe to use in the browser. It has no special privileges — your RLS policies control what it can access.\n\nNever use the `service_role` key on the client side. It bypasses all security.\n\n<b>Step 3 — Install the client</b>\n\nIn your project: `npm install @supabase/supabase-js`\n\n<b>Step 4 — Create a single client instance</b>\n\nCreate a file like `lib/supabase.ts` and export the client from there. Import it wherever you need database access. Do not call `createClient()` multiple times — one instance per app.\n\n<b>Step 5 — Create your first table</b>\n\nIn the Supabase dashboard, click Table Editor → New Table. Or use the SQL Editor to write a `CREATE TABLE` statement. The table editor is great for beginners; the SQL editor is faster once you are comfortable.",
    note:
      "Always use environment variables for your Supabase URL and anon key. In Next.js, add them to `.env.local` as `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY`. The `NEXT_PUBLIC_` prefix means the variable is available in the browser. Never commit `.env.local` to git.",
    diagram:
      "  SETUP CHECKLIST\n\n  1. supabase.com → New Project\n     │\n     ├── Name: my-app\n     ├── Region: closest to users\n     └── Database password: (save this!)\n\n  2. Settings → API\n     │\n     ├── Project URL:    https://xxxx.supabase.co  ← copy this\n     └── anon public:    eyJhbGci...              ← copy this\n\n  3. Your project\n     │\n     ├── .env.local\n     │     NEXT_PUBLIC_SUPABASE_URL=https://xxxx.supabase.co\n     │     NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGci...\n     │\n     └── lib/supabase.ts\n           import { createClient } from '@supabase/supabase-js'\n           export const supabase = createClient(url, key)",
    example:
      "// .env.local  (never commit this file)\nNEXT_PUBLIC_SUPABASE_URL=https://abcdefgh.supabase.co\nNEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\n\n// lib/supabase.ts  — create the client once, export it\nimport { createClient } from '@supabase/supabase-js';\n\nconst url = process.env.NEXT_PUBLIC_SUPABASE_URL!;\nconst key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;\n\nexport const supabase = createClient(url, key);\n\n// pages/index.tsx or any component\nimport { supabase } from '@/lib/supabase';\n\nexport default function Home() {\n  async function loadPosts() {\n    const { data, error } = await supabase\n      .from('posts')\n      .select('*');\n\n    if (error) {\n      console.error(error);\n      return;\n    }\n\n    console.log(data); // array of post rows\n  }\n\n  return <button onClick={loadPosts}>Load posts</button>;\n}",
    tip: "If your query returns `null` data and no error, the table probably exists but RLS is enabled with no policies — so every row is hidden by default. Go to Authentication → Policies in the Supabase dashboard and add a policy, or temporarily disable RLS on the table while developing.",
    tags: ["Setup", "Environment Variables", "createClient", "Project URL", "Anon Key"],
  },

  // ─────────────────────────────────────────────
  // DATABASE & TABLES
  // ─────────────────────────────────────────────
  {
    id: 4,
    section: "Database & Tables",
    title: "Tables, Columns & Data Types",
    tagline: "How data is organised in Supabase — rows, columns, types, and primary keys",
    description:
      "Supabase uses PostgreSQL, which stores data in <b>tables</b>. A table is like a spreadsheet: it has columns (the fields) and rows (the records).\n\n<b>Anatomy of a table</b>\n\nEvery table has:\n• <b>Columns</b> — each column has a name and a data type (e.g. `title text`, `price numeric`, `is_published boolean`)\n• <b>Rows</b> — each row is one record (one user, one post, one order)\n• <b>Primary key</b> — a column that uniquely identifies each row. In Supabase, this is almost always `id`\n\n<b>Common data types in PostgreSQL</b>\n\n• `uuid` — a universally unique identifier (e.g. `a8f3b2c1-...`). Use this as the primary key — Supabase generates it automatically with `gen_random_uuid()`\n• `text` — any string of any length\n• `varchar(n)` — a string with a maximum length\n• `int4` / `int8` — integers (whole numbers)\n• `numeric` — decimal numbers (for prices, etc.)\n• `boolean` — `true` or `false`\n• `timestamptz` — a date and time with timezone information. Always prefer this over `timestamp` for storing times\n• `jsonb` — a JSON object stored in binary format. Queryable and indexable\n\n<b>Useful column defaults</b>\n\n• `id uuid default gen_random_uuid() primary key` — auto-generates a unique ID for every row\n• `created_at timestamptz default now()` — automatically records when the row was created\n• `updated_at timestamptz default now()` — records the last update time (pair with a trigger to keep it current)\n\n<b>Creating a table</b>\n\nYou can use the Supabase dashboard Table Editor (point and click) or the SQL Editor (write SQL). For beginners, the Table Editor is the fastest way to get started.",
    note:
      "Always add `created_at timestamptz default now()` to every table. You will almost always want to know when a record was created, and adding it later to a large table is painful. Same for a `user_id uuid references auth.users(id)` column on any table that holds user-owned data.",
    diagram:
      "  TABLE: posts\n  ┌──────────────────────────────────────────────────────┐\n  │  id (uuid, PK)  │ title (text) │ published (boolean) │ created_at (timestamptz) │\n  ├──────────────────────────────────────────────────────┤\n  │  a8f3b2c1-...   │ Hello World  │ true                │ 2024-01-15 09:30:00+00   │\n  │  b7e1a4d2-...   │ My second    │ false               │ 2024-01-16 14:22:00+00   │\n  │  c9f2b5e3-...   │ Tips & Tricks│ true                │ 2024-01-17 08:11:00+00   │\n  └──────────────────────────────────────────────────────┘\n\n  Each row = one post\n  Each column = one field\n  id = primary key (unique for every row, auto-generated)\n\n  FOREIGN KEY RELATIONSHIP:\n\n  users.id ──────────► posts.user_id\n  (one user can have many posts)",
    example:
      "-- Create a posts table in the SQL Editor\nCREATE TABLE posts (\n  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,\n  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE,\n  title       text NOT NULL,\n  body        text,\n  published   boolean DEFAULT false,\n  created_at  timestamptz DEFAULT now()\n);\n\n-- The same via supabase-js (just reading the table once created)\nimport { supabase } from '@/lib/supabase';\n\n// Select all columns of all posts\nconst { data, error } = await supabase\n  .from('posts')\n  .select('*');\n\n// Select only specific columns\nconst { data: titles } = await supabase\n  .from('posts')\n  .select('id, title, created_at');\n\nconsole.log(titles);\n// [\n//   { id: 'a8f3b2c1-...', title: 'Hello World', created_at: '2024-01-15T09:30:00+00:00' },\n//   ...\n// ]",
    tip: "Use `uuid` primary keys (not auto-incrementing integers). UUIDs can be generated on the client before inserting, which enables optimistic UI updates. Integer IDs require a round-trip to the database before you know the ID.",
    tags: ["Tables", "Columns", "Data Types", "PostgreSQL", "Primary Key", "UUID"],
  },

  {
    id: 5,
    section: "Database & Tables",
    title: "CRUD — Select, Insert, Update, Delete",
    tagline: "The four fundamental database operations and how to write them with supabase-js",
    description:
      "CRUD stands for <b>Create, Read, Update, Delete</b> — the four basic operations you perform on any database. In Supabase, these map directly to four methods.\n\n<b>SELECT — reading data</b>\n\n`supabase.from('table').select('*')` returns all rows. Use `.select('col1, col2')` to pick specific columns. The result is always `{ data, error }` — check `error` first before using `data`.\n\n<b>INSERT — creating data</b>\n\n`supabase.from('table').insert({ col: value })` inserts one row. Pass an array to insert multiple rows at once. Chain `.select()` at the end to get the newly created row back.\n\n<b>UPDATE — changing data</b>\n\n`supabase.from('table').update({ col: newValue }).eq('id', someId)` updates matching rows. Always add a filter (`.eq()`) — without one, you will update every row in the table.\n\n<b>DELETE — removing data</b>\n\n`supabase.from('table').delete().eq('id', someId)` deletes matching rows. Again, always filter — `.delete()` without a filter deletes everything.\n\n<b>The { data, error } pattern</b>\n\nEvery Supabase operation returns a Promise that resolves to `{ data, error }`. `data` is `null` on error; `error` is `null` on success. Always handle errors — never assume an operation succeeded.",
    note:
      "Always chain a filter when using `.update()` or `.delete()`. A bare `supabase.from('posts').delete()` with no filter will attempt to delete every row. Supabase will reject it by default if RLS is enabled, but it is a bad habit. Be explicit about what you are targeting.",
    diagram:
      "  CRUD OPERATIONS\n\n  CREATE (Insert)\n  supabase.from('posts').insert({ title: 'Hello' })\n  → SQL: INSERT INTO posts (title) VALUES ('Hello')\n\n  READ (Select)\n  supabase.from('posts').select('id, title')\n  → SQL: SELECT id, title FROM posts\n\n  UPDATE\n  supabase.from('posts').update({ title: 'Hi' }).eq('id', '123')\n  → SQL: UPDATE posts SET title = 'Hi' WHERE id = '123'\n\n  DELETE\n  supabase.from('posts').delete().eq('id', '123')\n  → SQL: DELETE FROM posts WHERE id = '123'\n\n  RESPONSE SHAPE (always the same)\n  { data: [...] | null, error: { message: '...' } | null }",
    example:
      "import { supabase } from '@/lib/supabase';\n\n// ── SELECT ──────────────────────────────────────────────────────\nconst { data: posts, error: fetchError } = await supabase\n  .from('posts')\n  .select('id, title, published');\n\nif (fetchError) console.error('Fetch failed:', fetchError.message);\nelse console.log(posts);\n\n// ── INSERT ──────────────────────────────────────────────────────\nconst { data: newPost, error: insertError } = await supabase\n  .from('posts')\n  .insert({ title: 'My first post', body: 'Hello world!', published: false })\n  .select()   // returns the inserted row (with generated id & created_at)\n  .single();  // unwrap the array — we only inserted one row\n\nif (!insertError) console.log('Created:', newPost.id);\n\n// ── UPDATE ──────────────────────────────────────────────────────\nconst { error: updateError } = await supabase\n  .from('posts')\n  .update({ published: true })\n  .eq('id', newPost.id);  // ALWAYS filter — never update without a WHERE\n\n// ── DELETE ──────────────────────────────────────────────────────\nconst { error: deleteError } = await supabase\n  .from('posts')\n  .delete()\n  .eq('id', newPost.id);  // ALWAYS filter",
    tip: "Chain `.select().single()` after `.insert()` to get the created row back (including the auto-generated `id` and `created_at`). Without `.select()`, the insert returns `data: null` on success — you get a 201 status but no row data.",
    tags: ["CRUD", "Select", "Insert", "Update", "Delete", "Data Fetching"],
  },

  {
    id: 6,
    section: "Database & Tables",
    title: "Filtering, Sorting & Pagination",
    tagline: "Query exactly the data you need — filters, ordering, limits, and ranges",
    description:
      "Fetching everything with `.select('*')` is fine for tiny tables, but in real apps you need to filter, sort, and paginate.\n\n<b>Filtering — WHERE clauses</b>\n\nSupabase provides a method for every PostgreSQL comparison operator:\n• `.eq('column', value)` — equal to (`=`)\n• `.neq('column', value)` — not equal (`!=`)\n• `.gt('column', value)` — greater than (`>`)\n• `.gte('column', value)` — greater than or equal (`>=`)\n• `.lt('column', value)` — less than (`<`)\n• `.lte('column', value)` — less than or equal (`<=`)\n• `.like('column', '%pattern%')` — SQL LIKE (case-sensitive)\n• `.ilike('column', '%pattern%')` — case-insensitive LIKE\n• `.in('column', [val1, val2])` — matches any value in a list\n• `.is('column', null)` — checks for NULL\n• `.not('column', 'is', null)` — checks for NOT NULL\n\n<b>Sorting — ORDER BY</b>\n\n`.order('column', { ascending: true/false })` sorts results. You can chain multiple `.order()` calls for multi-column sorts.\n\n<b>Pagination — LIMIT and OFFSET</b>\n\n`.limit(10)` returns at most 10 rows.\n`.range(0, 9)` returns rows 0 through 9 (10 rows). For the next page: `.range(10, 19)`. This is the standard way to paginate.\n\n<b>Single row — .single() and .maybeSingle()</b>\n\nWhen you expect exactly one row (like fetching by ID), chain `.single()`. It unwraps the array into a single object and returns an error if zero or more than one row is found. Use `.maybeSingle()` when the row might not exist — it returns `null` instead of an error when nothing is found.",
    note:
      "`.eq()` and other filter methods are chainable — you can stack multiple filters and they combine with AND. For OR conditions, use `.or('column1.eq.value1,column2.eq.value2')`. For complex conditions, consider a PostgreSQL view or a raw SQL query via `.rpc()`.",
    diagram:
      "  CHAINING FILTERS\n\n  supabase\n    .from('posts')\n    .select('id, title, created_at')   ← which columns\n    .eq('published', true)             ← WHERE published = true\n    .gte('created_at', '2024-01-01')   ← AND created_at >= '2024-01-01'\n    .order('created_at', { ascending: false })  ← ORDER BY created_at DESC\n    .limit(10);                        ← LIMIT 10\n\n  → SQL:\n  SELECT id, title, created_at\n  FROM posts\n  WHERE published = true\n    AND created_at >= '2024-01-01'\n  ORDER BY created_at DESC\n  LIMIT 10;\n\n  PAGINATION:\n  Page 1: .range(0, 9)   → rows 0-9\n  Page 2: .range(10, 19) → rows 10-19\n  Page 3: .range(20, 29) → rows 20-29",
    example:
      "import { supabase } from '@/lib/supabase';\n\n// Filter: published posts only, sorted by date\nconst { data: published } = await supabase\n  .from('posts')\n  .select('id, title, created_at')\n  .eq('published', true)\n  .order('created_at', { ascending: false })\n  .limit(10);\n\n// Search: case-insensitive title search\nconst { data: results } = await supabase\n  .from('posts')\n  .select('id, title')\n  .ilike('title', '%react%');  // matches 'React tips', 'learning react', etc.\n\n// Fetch a single post by ID\nconst { data: post, error } = await supabase\n  .from('posts')\n  .select('*')\n  .eq('id', 'a8f3b2c1-0001-0002-0003-abcdefabcdef')\n  .single();  // returns { data: {...}, error: null }\n\n// Fetch a post that might not exist\nconst { data: maybePost } = await supabase\n  .from('posts')\n  .select('*')\n  .eq('slug', 'hello-world')\n  .maybeSingle();  // data is null if not found (no error)\n\n// Pagination — page 2 (items 10 to 19)\nconst page = 2;\nconst pageSize = 10;\nconst from = (page - 1) * pageSize;\nconst to = from + pageSize - 1;\n\nconst { data: pageData } = await supabase\n  .from('posts')\n  .select('id, title')\n  .range(from, to);",
    tip: "Use `.single()` when fetching by primary key. If the row is missing, it returns an error with code `PGRST116`. Catch that specific code to distinguish 'row not found' from a real database error.",
    tags: ["Filtering", "Sorting", "Pagination", "eq", "order", "range", "single"],
  },

  {
    id: 7,
    section: "Database & Tables",
    title: "Joins & Relationships",
    tagline: "Fetch data from multiple related tables in a single query using foreign keys",
    description:
      "Real apps have data spread across multiple tables that relate to each other. Supabase makes it easy to fetch related data in a single query using <b>foreign key relationships</b>.\n\n<b>What is a foreign key?</b>\n\nA foreign key is a column in one table that points to the primary key of another table. For example, a `posts` table might have a `user_id` column that points to `users.id`. This creates a relationship: one user can have many posts.\n\n<b>How Supabase handles joins</b>\n\nSupabase (via PostgREST) can detect foreign key relationships in your schema and let you embed related rows directly in your select query using a special syntax. Instead of two separate queries, you write one.\n\n<b>One-to-many (user has many posts)</b>\n\nIf `posts.user_id` is a foreign key to `users.id`, you can fetch a user and all their posts in one query.\n\n<b>Many-to-one (post belongs to user)</b>\n\nYou can also go the other direction — fetch a post and embed the user who wrote it.\n\n<b>When PostgREST cannot figure out the relationship</b>\n\nIf you have multiple foreign keys between two tables, or the relationship is not obvious, you can use a <b>hint</b> in the select string to tell PostgREST which key to use: `select('*, comments!comments_post_id_fkey(*)')`. The part after `!` is the foreign key constraint name.",
    note:
      "Joins in Supabase are powerful but only work for direct foreign key relationships. For complex queries (multiple levels of nesting, aggregations, window functions), write a PostgreSQL <b>view</b> or a <b>stored function</b> and call it with `.rpc('function_name')`. Views let you write plain SQL and query them like a table.",
    diagram:
      "  TABLE: users              TABLE: posts\n  ┌─────────────────┐       ┌──────────────────────────┐\n  │ id (PK)         │◄──┐   │ id (PK)                  │\n  │ email           │   └───│ user_id (FK → users.id)  │\n  │ full_name       │       │ title                    │\n  └─────────────────┘       │ body                     │\n                            └──────────────────────────┘\n\n  ONE-TO-MANY: one user → many posts\n\n  QUERY:\n  supabase.from('users').select('id, email, posts(id, title)')\n\n  RESULT:\n  [\n    {\n      id: 'abc',\n      email: 'rajan@example.com',\n      posts: [\n        { id: 'p1', title: 'Hello World' },\n        { id: 'p2', title: 'My second post' }\n      ]\n    }\n  ]",
    example:
      "import { supabase } from '@/lib/supabase';\n\n// ONE-TO-MANY: fetch users and their posts\n// posts.user_id → users.id\nconst { data: users } = await supabase\n  .from('users')\n  .select(`\n    id,\n    email,\n    posts (\n      id,\n      title,\n      published,\n      created_at\n    )\n  `);\n// Result: each user has a 'posts' array of their posts\n\n// MANY-TO-ONE: fetch posts and embed the author\nconst { data: posts } = await supabase\n  .from('posts')\n  .select(`\n    id,\n    title,\n    users (\n      id,\n      email,\n      full_name\n    )\n  `);\n// Result: each post has a 'users' object (the author)\n\n// FILTER on related table: posts by a specific author email\nconst { data: filtered } = await supabase\n  .from('posts')\n  .select('id, title, users!inner(email)')\n  .eq('users.email', 'rajan@example.com');\n// !inner = only return posts that have a matching user",
    tip: "Use `!inner` in your select when you want to filter on the related table and only return rows where the join matches. Without `!inner`, Supabase does a left join — rows without a matching related row are still returned (with `null` for the relation).",
    tags: ["Joins", "Relationships", "Foreign Key", "One-to-Many", "Nested Select", "PostgREST"],
  },

  // ─────────────────────────────────────────────
  // AUTHENTICATION
  // ─────────────────────────────────────────────
  {
    id: 8,
    section: "Authentication",
    title: "Auth Basics — Sign Up, Sign In, Sign Out",
    tagline: "How to add user accounts to your app without writing any auth code",
    description:
      "Authentication is one of the hardest things to build correctly from scratch. Supabase gives you a complete auth system out of the box.\n\n<b>The three main sign-in methods</b>\n\n<b>1. Email + password</b> — the classic. Users create an account with their email and a password. You can optionally require email confirmation before they can log in.\n\n<b>2. Magic link</b> — the user enters their email, receives a one-time link, clicks it, and is logged in. No password needed. Great for apps where you want low friction.\n\n<b>3. OAuth</b> — 'Sign in with Google / GitHub / Facebook'. The user logs in via a third-party provider and Supabase handles the OAuth flow. You just call `signInWithOAuth({ provider: 'google' })`.\n\n<b>How it works under the hood</b>\n\nWhen a user signs in, Supabase's auth service (GoTrue) creates a <b>session</b>. The session contains two tokens:\n• <b>Access token (JWT)</b> — a short-lived token (1 hour by default) sent with every database request so the database knows who is asking\n• <b>Refresh token</b> — a long-lived token used to get a new access token when the old one expires\n\nThe Supabase JS client handles token refresh automatically. You do not need to think about it.\n\n<b>Where sessions are stored</b>\n\nBy default, the Supabase JS client stores the session in `localStorage` (in the browser) so the user stays logged in across page refreshes and browser restarts.",
    note:
      "Enable email confirmation in production (Supabase dashboard → Authentication → Settings). Without it, anyone can sign up with any email address without proving they own it. During development, you can turn it off to avoid checking your inbox every time you test.",
    diagram:
      "  EMAIL + PASSWORD FLOW\n\n  User fills in form\n       │\n       │  supabase.auth.signUp({ email, password })\n       ↓\n  Supabase Auth (GoTrue)\n       │\n       ├── Creates user in auth.users table\n       ├── Sends confirmation email (if enabled)\n       └── Returns { user, session } or { user, session: null } if unconfirmed\n\n  User clicks confirmation link\n       │\n       ↓\n  supabase.auth.signInWithPassword({ email, password })\n       │\n       ↓\n  Returns { data: { user, session }, error: null }\n       │\n       ├── session.access_token  (JWT, valid 1 hour)\n       └── session.refresh_token (long-lived, auto-refreshed)",
    example:
      "import { supabase } from '@/lib/supabase';\n\n// ── SIGN UP ─────────────────────────────────────────────────────\nconst { data, error } = await supabase.auth.signUp({\n  email: 'rajan@example.com',\n  password: 'super-secret-password',\n  options: {\n    data: { full_name: 'Rajan Magar' },  // stored in user_metadata\n  },\n});\n\nif (error) console.error(error.message);\nelse if (!data.session) console.log('Check your email for a confirmation link');\nelse console.log('Signed up and logged in:', data.user.email);\n\n// ── SIGN IN ─────────────────────────────────────────────────────\nconst { data: signInData, error: signInError } = await supabase.auth.signInWithPassword({\n  email: 'rajan@example.com',\n  password: 'super-secret-password',\n});\n\nif (signInError) console.error('Wrong email or password');\nelse console.log('Welcome back,', signInData.user.email);\n\n// ── MAGIC LINK ──────────────────────────────────────────────────\nawait supabase.auth.signInWithOtp({\n  email: 'rajan@example.com',\n  options: { emailRedirectTo: 'https://myapp.com/dashboard' },\n});\n// User receives an email with a magic link — no password required\n\n// ── OAUTH (Google) ───────────────────────────────────────────────\nawait supabase.auth.signInWithOAuth({\n  provider: 'google',\n  options: { redirectTo: 'https://myapp.com/auth/callback' },\n});\n// Redirects user to Google's login page\n\n// ── SIGN OUT ─────────────────────────────────────────────────────\nawait supabase.auth.signOut();\n// Clears the session from localStorage",
    tip: "Always handle the case where `data.session` is `null` after `signUp()`. This happens when email confirmation is enabled — the user is created but not yet confirmed. Show them a message like 'Check your email and click the confirmation link, then sign in.'",
    tags: ["Auth", "signUp", "signIn", "Magic Link", "OAuth", "Session", "GoTrue"],
  },

  {
    id: 9,
    section: "Authentication",
    title: "User Sessions & JWT Tokens",
    tagline: "What a session is, how tokens work, and how Supabase keeps users logged in",
    description:
      "A <b>session</b> is proof that a user is logged in. When a user signs in, Supabase creates a session and gives the browser two tokens.\n\n<b>What is a JWT?</b>\n\nA JWT (JSON Web Token) is a string that looks like `eyJhbGci...`. It contains encoded information — called <b>claims</b> — about the user: their ID, email, role, and metadata. The token is <b>signed</b> by Supabase's secret key, so the database can verify it is genuine without looking it up in a separate table.\n\nThink of it like a signed concert wristband. The bouncer (your database) can check the wristband is real and read what section you are allowed into — without calling the ticket office each time.\n\n<b>Access token vs refresh token</b>\n\n• <b>Access token</b> — the JWT. Sent with every request so the database knows who you are. Short-lived (1 hour by default) — if stolen, it expires quickly.\n• <b>Refresh token</b> — a long-lived token stored securely. When the access token expires, the Supabase JS client uses the refresh token to silently fetch a new access token. The user never has to log in again.\n\n<b>How Supabase stores the session</b>\n\nThe Supabase JS client stores the session in `localStorage` by default. On page load, it reads the stored session and automatically restores the user's login state. You do not have to write any session persistence code.\n\n<b>Decoding a JWT</b>\n\nYou can paste any JWT into jwt.io to see what is inside. A Supabase JWT contains: `sub` (the user's UUID), `email`, `role` (usually `authenticated`), `aud` (audience), `exp` (expiry timestamp).",
    note:
      "Never store your Supabase `service_role` key in the browser or in client-side code. The service role key creates a session that bypasses all RLS policies — it has full read/write access to your entire database. Use it only in server-side code (API routes, Edge Functions, server components).",
    diagram:
      "  SESSION LIFECYCLE\n\n  User signs in\n       │\n       ↓\n  Supabase returns:\n  ┌─────────────────────────────────────┐\n  │ access_token  (JWT, expires in 1h)  │  ← sent with every DB request\n  │ refresh_token (long-lived)          │  ← used to renew access_token\n  │ user          { id, email, ... }    │\n  └─────────────────────────────────────┘\n       │\n       │  Stored in localStorage by supabase-js\n       │\n  ┌────▼──────────────────────────────────────┐\n  │ After 1 hour: access_token expires        │\n  │   supabase-js automatically calls         │\n  │   /auth/v1/token?grant_type=refresh_token │\n  │   → gets a new access_token               │\n  │   → user stays logged in silently         │\n  └───────────────────────────────────────────┘\n\n  JWT PAYLOAD (decoded):\n  { sub: 'user-uuid', email: 'rajan@...', role: 'authenticated', exp: 1234567890 }",
    example:
      "import { supabase } from '@/lib/supabase';\n\n// Get the current session\nconst { data: { session } } = await supabase.auth.getSession();\n\nif (session) {\n  console.log('User ID:', session.user.id);          // UUID\n  console.log('Email:', session.user.email);\n  console.log('Access token:', session.access_token); // The JWT\n  console.log('Expires at:', new Date(session.expires_at * 1000));\n} else {\n  console.log('No active session — user is not logged in');\n}\n\n// Get just the user (no token details)\nconst { data: { user } } = await supabase.auth.getUser();\nconsole.log(user?.user_metadata?.full_name); // 'Rajan Magar'\n\n// Read custom data from user_metadata (set during signUp)\nconst name = user?.user_metadata?.full_name;\nconst avatar = user?.user_metadata?.avatar_url;\n\n// The access_token is automatically attached to every\n// supabase.from(...) call — you never pass it manually",
    tip: "Use `getUser()` instead of `getSession().user` when you need to verify the user is actually authenticated on the server side. `getSession()` reads from local storage and can be spoofed. `getUser()` makes a round-trip to Supabase to verify the JWT is still valid.",
    tags: ["JWT", "Session", "Access Token", "Refresh Token", "getSession", "getUser"],
  },

  {
    id: 10,
    section: "Authentication",
    title: "Managing Auth State in the Frontend",
    tagline: "Listen for login and logout events and protect routes with onAuthStateChange",
    description:
      "In a frontend app, the user's auth state can change at any moment — they might sign in, sign out, or their session might be refreshed in a background tab. You need a way to react to these changes.\n\n<b>onAuthStateChange — the auth event listener</b>\n\n`supabase.auth.onAuthStateChange(callback)` fires your callback every time the auth state changes. The callback receives an `event` string (`SIGNED_IN`, `SIGNED_OUT`, `TOKEN_REFRESHED`, `USER_UPDATED`) and the current `session` object.\n\nThis is the correct way to keep your app's state in sync with Supabase auth. Call it once when your app initialises.\n\n<b>Protecting routes</b>\n\nIn Next.js, you have two approaches:\n• <b>Client-side</b> — check the session in a component. If there is no session, redirect to the login page. Simple but shows a flash before redirect.\n• <b>Server-side (middleware)</b> — use Next.js middleware to check the session before rendering. No flash, but requires the `@supabase/ssr` package.\n\n<b>Reading the user on the server</b>\n\nIn Server Components (Next.js App Router), use `@supabase/ssr` to create a server-side Supabase client and call `supabase.auth.getUser()`. This reads the session from cookies (not localStorage), making it available on the server.\n\n<b>Cleaning up the listener</b>\n\n`onAuthStateChange` returns a `subscription` object. Call `subscription.unsubscribe()` when your component unmounts to prevent memory leaks.",
    note:
      "Always set up the `onAuthStateChange` listener before calling `getSession()`. There is a small window during page load where the stored session is being refreshed — without the listener, you might read an empty session and redirect the user to login, then redirect them back once the session loads. The listener ensures you react to the final auth state.",
    diagram:
      "  AUTH STATE MACHINE\n\n  App starts\n       │\n       ├── getSession() → reads localStorage\n       │         ↓\n       │   Session found?  ── Yes ──► user is logged in, show app\n       │         │\n       │         No\n       │         ↓\n       │   Show login page\n       │\n       └── onAuthStateChange listener is always running:\n\n  Event: SIGNED_IN   → session = { user, access_token, ... }  → update state\n  Event: SIGNED_OUT  → session = null                          → redirect to login\n  Event: TOKEN_REFRESHED → session = { new access_token }     → update token silently\n  Event: USER_UPDATED    → session = { updated user data }    → update profile UI",
    example:
      "// AuthProvider.tsx — wrap your app with this\n'use client';\nimport { createContext, useContext, useEffect, useState } from 'react';\nimport type { User } from '@supabase/supabase-js';\nimport { supabase } from '@/lib/supabase';\n\nconst AuthContext = createContext<{ user: User | null }>({{ user: null }});\n\nexport function AuthProvider({ children }: { children: React.ReactNode }) {\n  const [user, setUser] = useState<User | null>(null);\n\n  useEffect(() => {\n    // 1. Read the current session once on mount\n    supabase.auth.getSession().then(({ data: { session } }) => {\n      setUser(session?.user ?? null);\n    });\n\n    // 2. Listen for future changes (sign in, sign out, token refresh)\n    const { data: { subscription } } = supabase.auth.onAuthStateChange(\n      (_event, session) => {\n        setUser(session?.user ?? null);\n      }\n    );\n\n    // 3. Clean up the listener when the component unmounts\n    return () => subscription.unsubscribe();\n  }, []);\n\n  return <AuthContext.Provider value={{ user }}>{children}</AuthContext.Provider>;\n}\n\nexport const useAuth = () => useContext(AuthContext);\n\n// In any component:\nconst { user } = useAuth();\nif (!user) return <LoginPage />;\nreturn <Dashboard user={user} />;",
    tip: "In Next.js App Router, prefer `@supabase/ssr` for server-side auth. It stores the session in cookies (not just localStorage) so Server Components can read the user. The `createBrowserClient` / `createServerClient` pattern from that package replaces the basic `createClient` for Next.js apps.",
    tags: ["onAuthStateChange", "Auth State", "Protected Routes", "Session", "React Context"],
  },

  // ─────────────────────────────────────────────
  // ROW LEVEL SECURITY
  // ─────────────────────────────────────────────
  {
    id: 11,
    section: "Row Level Security",
    title: "What is Row Level Security?",
    tagline: "Let the database enforce who can read and write which rows — no backend code needed",
    description:
      "Row Level Security (RLS) is a PostgreSQL feature that lets you write rules — called <b>policies</b> — that control which rows a user can see or modify.\n\n<b>The problem RLS solves</b>\n\nImagine a `tasks` table where every user stores their own tasks. Without RLS, this query returns every task from every user:\n\n`supabase.from('tasks').select('*')`\n\nAny logged-in user could read anyone else's tasks just by calling this. That is a serious security problem.\n\nWith RLS enabled and a policy like 'users can only see their own tasks', the exact same query automatically returns only the calling user's tasks — filtered by PostgreSQL before the data ever leaves the database.\n\n<b>How RLS works</b>\n\n1. You enable RLS on a table: `ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;`\n2. You write policies — SQL expressions that evaluate to `true` or `false` for each row\n3. Every query against that table is filtered through the policies\n4. Rows where the policy evaluates to `false` are hidden — as if they do not exist\n\n<b>The default when RLS is enabled with no policies</b>\n\nWhen you enable RLS on a table without any policies, <b>no rows are accessible to anyone</b>. This is the safe default. It is why new Supabase users often see empty results — they enabled RLS but forgot to add policies.\n\n<b>auth.uid()</b>\n\n`auth.uid()` is a PostgreSQL function that returns the UUID of the currently authenticated user (from their JWT). It is the key ingredient in almost every RLS policy.",
    note:
      "RLS is the single most important security feature in Supabase. Without it, your database is essentially public — anyone with your anon key can read and write any table. Always enable RLS on tables that store user data, and always write policies before going to production.",
    diagram:
      "  WITHOUT RLS:\n\n  User A calls: supabase.from('tasks').select('*')\n  ─────────────────────────────────────────────────\n  Returns ALL tasks from ALL users ← security problem!\n\n  ─────────────────────────────────────────────────\n\n  WITH RLS + policy 'users see own tasks':\n\n  User A (id: 'aaa') calls: supabase.from('tasks').select('*')\n\n  PostgreSQL checks each row:\n  ┌────────────────────────────────────────────────┐\n  │ Row 1: user_id = 'aaa' → policy TRUE  → return │\n  │ Row 2: user_id = 'bbb' → policy FALSE → hide   │\n  │ Row 3: user_id = 'aaa' → policy TRUE  → return │\n  │ Row 4: user_id = 'ccc' → policy FALSE → hide   │\n  └────────────────────────────────────────────────┘\n\n  Returns only rows where user_id = 'aaa' ← safe!",
    example:
      "-- Step 1: Enable RLS on your table\nALTER TABLE tasks ENABLE ROW LEVEL SECURITY;\n\n-- Without any policies, the table is now completely locked down.\n-- supabase.from('tasks').select('*') returns [] for everyone.\n\n-- Step 2: Add a policy to allow users to see their own rows\nCREATE POLICY \"Users can view own tasks\"\n  ON tasks\n  FOR SELECT                          -- applies to SELECT queries\n  USING (auth.uid() = user_id);       -- only return rows where user_id = logged-in user\n\n-- Now supabase.from('tasks').select('*') automatically filters\n-- to only the current user's tasks. No extra .eq() needed!\n\n-- Check which tables have RLS enabled in the dashboard:\n-- Table Editor → click a table → RLS is shown at the top\n\n-- Or in SQL:\nSELECT tablename, rowsecurity\nFROM pg_tables\nWHERE schemaname = 'public';",
    tip: "When you enable RLS on a table but your query returns empty results with no error, it almost always means you have no policies (or the policy condition evaluates to false). Open the Supabase dashboard → Authentication → Policies and verify your policies exist and are enabled.",
    tags: ["RLS", "Row Level Security", "auth.uid()", "Policies", "Security", "PostgreSQL"],
  },

  {
    id: 12,
    section: "Row Level Security",
    title: "Writing RLS Policies",
    tagline: "The anatomy of a policy — FOR, USING, and WITH CHECK explained simply",
    description:
      "A policy is a SQL expression that PostgreSQL evaluates for each row to decide if the operation is allowed.\n\n<b>Policy anatomy</b>\n\n```sql\nCREATE POLICY \"policy name\"\n  ON table_name\n  FOR operation        -- SELECT, INSERT, UPDATE, DELETE, or ALL\n  TO role              -- optional: 'authenticated', 'anon', 'service_role'\n  USING (expression)   -- controls which rows are VISIBLE (for SELECT, UPDATE, DELETE)\n  WITH CHECK (expression); -- controls which rows can be WRITTEN (for INSERT, UPDATE)\n```\n\n<b>USING vs WITH CHECK</b>\n\n• <b>USING</b> — filters existing rows. Think of it as the WHERE clause PostgreSQL adds automatically. Used for SELECT, UPDATE, and DELETE.\n• <b>WITH CHECK</b> — validates new data before writing. Used for INSERT and UPDATE. If the expression evaluates to `false`, the write is rejected with a permission error.\n\nFor INSERT, only `WITH CHECK` applies (there is no existing row to filter).\nFor SELECT, only `USING` applies.\nFor UPDATE, both apply: USING controls which rows can be targeted; WITH CHECK validates the new data.\n\n<b>The role</b>\n\n• `authenticated` — the policy applies to logged-in users\n• `anon` — the policy applies to users who are not logged in (the anon key)\n• Omitting `TO` applies the policy to all roles\n\n<b>auth.uid() and auth.jwt()</b>\n\n`auth.uid()` — returns the UUID of the logged-in user from their JWT.\n`auth.jwt()` — returns the entire JWT payload as JSON. Useful for reading custom claims.",
    note:
      "A common mistake: writing a policy `FOR ALL` with only a `USING` clause. For INSERT operations, only `WITH CHECK` is evaluated — `USING` is ignored. If your INSERT policy is not working, make sure you have `WITH CHECK`, not just `USING`.",
    diagram:
      "  POLICY EVALUATION\n\n  Operation: SELECT\n  ──────────────────────────────────────────────\n  Each row is checked against USING expression:\n  USING (auth.uid() = user_id)\n  → TRUE  → row is returned to the user\n  → FALSE → row is silently hidden\n\n  Operation: INSERT\n  ──────────────────────────────────────────────\n  New row is checked against WITH CHECK expression:\n  WITH CHECK (auth.uid() = user_id)\n  → TRUE  → insert succeeds\n  → FALSE → insert rejected with 403 error\n\n  Operation: UPDATE\n  ──────────────────────────────────────────────\n  USING: can this row be targeted?\n  WITH CHECK: is the new data valid?\n  Both must be TRUE for the update to succeed",
    example:
      "-- FULL CRUD policy: users manage only their own tasks\n\n-- SELECT: users can read their own tasks\nCREATE POLICY \"select own tasks\"\n  ON tasks FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);\n\n-- INSERT: users can only insert rows where user_id is themselves\nCREATE POLICY \"insert own tasks\"\n  ON tasks FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);\n\n-- UPDATE: users can only update their own tasks\nCREATE POLICY \"update own tasks\"\n  ON tasks FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)         -- can only target own rows\n  WITH CHECK (auth.uid() = user_id);   -- new data must still belong to them\n\n-- DELETE: users can only delete their own tasks\nCREATE POLICY \"delete own tasks\"\n  ON tasks FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);\n\n-- Shorthand: one ALL policy with both clauses\nCREATE POLICY \"full access to own tasks\"\n  ON tasks FOR ALL\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);",
    tip: "When debugging a failing query due to RLS, temporarily log in to the Supabase SQL Editor and run `SELECT auth.uid();`. If it returns `null`, you are not authenticated in that session. In the dashboard's SQL Editor you are always running as the service role (bypasses RLS) — use the API to test RLS policies accurately.",
    tags: ["RLS Policy", "USING", "WITH CHECK", "FOR SELECT", "FOR INSERT", "Authenticated Role"],
  },

  {
    id: 13,
    section: "Row Level Security",
    title: "Common RLS Patterns",
    tagline: "Public read, private write, team data, admin bypass — ready-to-use policy templates",
    description:
      "Most apps need only a handful of RLS patterns. Here are the most common ones.\n\n<b>Pattern 1: User-owned data (most common)</b>\n\nUsers can only see and modify their own rows. The table has a `user_id` column.\n`USING (auth.uid() = user_id)` and `WITH CHECK (auth.uid() = user_id)`\n\n<b>Pattern 2: Public read, authenticated write</b>\n\nAnyone can read (like a blog), but only logged-in users can create, update, or delete.\nSELECT: `USING (true)` — everyone can read\nINSERT/UPDATE/DELETE: `TO authenticated` with `auth.uid() = user_id`\n\n<b>Pattern 3: Public read, owner write</b>\n\nAnyone can read, but only the row owner can modify.\nSELECT for `anon` and `authenticated`: `USING (true)`\nINSERT/UPDATE/DELETE for `authenticated`: `WITH CHECK (auth.uid() = user_id)`\n\n<b>Pattern 4: Team / organisation data</b>\n\nUsers belong to a team and can access all rows owned by their team.\nRequires a `team_members` table. The policy does a sub-query: check if the current user is a member of the team that owns the row.\n\n<b>Pattern 5: Admin bypass</b>\n\nAdmins can access everything. Store a `role` field in `user_metadata` or a separate `profiles` table. The policy checks the user's role.",
    note:
      "The `service_role` key already bypasses all RLS policies regardless of what you write. You do not need a special admin policy for server-side code that uses the service role key. Only use admin policies for users in the browser who have elevated permissions.",
    diagram:
      "  PATTERN 1: User-owned data\n  USING/WITH CHECK: auth.uid() = user_id\n  → Each user sees and modifies only their rows\n\n  PATTERN 2: Public blog posts\n  SELECT (anon + authenticated): USING (true)\n  INSERT/UPDATE/DELETE (authenticated): auth.uid() = user_id\n  → Anyone can read, owner can write\n\n  PATTERN 3: Team workspace\n  USING: EXISTS (\n    SELECT 1 FROM team_members\n    WHERE team_members.team_id = posts.team_id\n      AND team_members.user_id = auth.uid()\n  )\n  → Any member of the team can access the row\n\n  PATTERN 4: Admin\n  USING: auth.jwt() ->> 'role' = 'admin'\n  or\n  USING: EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)",
    example:
      "-- PATTERN 1: User-owned rows\nCREATE POLICY \"owner access\" ON tasks FOR ALL\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);\n\n-- PATTERN 2: Public read (blog posts)\nCREATE POLICY \"public can read published posts\" ON posts FOR SELECT\n  TO anon, authenticated\n  USING (published = true);\n\nCREATE POLICY \"author can manage own posts\" ON posts FOR ALL\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);\n\n-- PATTERN 3: Team data\nCREATE POLICY \"team members can access\" ON documents FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM team_members\n      WHERE team_members.team_id = documents.team_id\n        AND team_members.user_id = auth.uid()\n    )\n  );\n\n-- PATTERN 4: Admin bypass (using a profiles table)\nCREATE POLICY \"admins can do anything\" ON posts FOR ALL\n  TO authenticated\n  USING (\n    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)\n  )\n  WITH CHECK (\n    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)\n  );",
    tip: "Avoid using `auth.jwt() ->> 'user_metadata' ->> 'role'` for sensitive access control. `user_metadata` can be modified by the user themselves. Instead, store roles in a `profiles` table that only you (or server-side code) can update, and reference that in your policies.",
    tags: ["RLS Patterns", "Public Read", "Team Access", "Admin", "Owner Policy"],
  },

  // ─────────────────────────────────────────────
  // REAL-TIME
  // ─────────────────────────────────────────────
  {
    id: 14,
    section: "Real-time",
    title: "Real-time Subscriptions",
    tagline: "Listen to database changes live — no polling, no page refresh needed",
    description:
      "Supabase Real-time lets your app receive database changes as they happen, pushed over a WebSocket connection.\n\n<b>How it works</b>\n\nPostgreSQL has a feature called <b>logical replication</b> — it can broadcast every INSERT, UPDATE, and DELETE that happens in the database. Supabase's Realtime server listens to this stream and forwards matching events to subscribed clients over WebSockets.\n\nYour app stays connected to the Realtime server. When a row changes, the change is pushed to your app in milliseconds — without your app having to ask.\n\n<b>The channel API</b>\n\nReal-time subscriptions use a <b>channel</b> as the connection point. A channel is like a room — you create one, subscribe to events in it, and join it.\n\n<b>Subscribing to table changes</b>\n\nUse `.on('postgres_changes', { event, schema, table, filter }, callback)` to listen for specific changes. The `event` can be `INSERT`, `UPDATE`, `DELETE`, or `*` (all).\n\n<b>Cleaning up</b>\n\nAlways remove the channel when your component unmounts. Leaving subscriptions open wastes server connections and can cause memory leaks and duplicate updates.\n\n<b>RLS and real-time</b>\n\nBy default, Supabase Realtime does not apply RLS to `postgres_changes` events. Any authenticated user who subscribes to a table change will receive all events. Enable RLS for Realtime in the Supabase dashboard under Realtime settings, or use Broadcast/Presence channels for user-scoped updates.",
    note:
      "For most apps, real-time updates give a much better user experience than polling. Instead of polling every 5 seconds (`setInterval`), subscribe once and let the server push updates. Your app reacts instantly and uses far less network traffic.",
    diagram:
      "  DATABASE CHANGE → YOUR APP (in milliseconds)\n\n  Another client inserts a row into 'messages'\n       │\n       ↓\n  PostgreSQL logical replication stream\n       │\n       ↓\n  Supabase Realtime server (Phoenix)\n       │  broadcasts to all subscribed channels\n       ↓\n  WebSocket connection\n       │\n       ↓\n  Your app receives the event:\n  {\n    eventType: 'INSERT',\n    new: { id: '...', text: 'Hello!', created_at: '...' },\n    old: {},\n    table: 'messages'\n  }\n       │\n       ↓\n  React state update → UI re-renders with new message",
    example:
      "import { useEffect, useState } from 'react';\nimport { supabase } from '@/lib/supabase';\n\ntype Message = { id: string; text: string; created_at: string };\n\nexport function MessageList() {\n  const [messages, setMessages] = useState<Message[]>([]);\n\n  useEffect(() => {\n    // 1. Load existing messages\n    supabase\n      .from('messages')\n      .select('*')\n      .order('created_at')\n      .then(({ data }) => setMessages(data ?? []));\n\n    // 2. Subscribe to new messages in real-time\n    const channel = supabase\n      .channel('messages-channel')        // unique channel name\n      .on(\n        'postgres_changes',\n        { event: 'INSERT', schema: 'public', table: 'messages' },\n        (payload) => {\n          // payload.new is the newly inserted row\n          setMessages((prev) => [...prev, payload.new as Message]);\n        }\n      )\n      .on(\n        'postgres_changes',\n        { event: 'DELETE', schema: 'public', table: 'messages' },\n        (payload) => {\n          setMessages((prev) => prev.filter((m) => m.id !== payload.old.id));\n        }\n      )\n      .subscribe();\n\n    // 3. Clean up when component unmounts\n    return () => {\n      supabase.removeChannel(channel);\n    };\n  }, []);\n\n  return (\n    <ul>\n      {messages.map((m) => <li key={m.id}>{m.text}</li>)}\n    </ul>\n  );\n}",
    tip: "Filter your real-time subscription to only receive events relevant to the current user using the `filter` option: `{ event: '*', schema: 'public', table: 'tasks', filter: 'user_id=eq.' + userId }`. This reduces the volume of events your client receives and avoids leaking other users' data.",
    tags: ["Real-time", "WebSocket", "postgres_changes", "Channel", "INSERT", "Subscriptions"],
  },

  {
    id: 15,
    section: "Real-time",
    title: "Broadcast & Presence",
    tagline: "Send ephemeral messages between clients and track who is online right now",
    description:
      "Beyond database changes, Supabase Realtime offers two more primitives: <b>Broadcast</b> and <b>Presence</b>.\n\n<b>Broadcast — ephemeral messages</b>\n\nBroadcast lets you send a message to everyone subscribed to a channel without writing anything to the database. Think cursor positions, typing indicators, game state, or live votes. The message is transient — it is not stored anywhere.\n\nUse Broadcast when you need very low-latency, high-frequency updates that do not need to be persisted.\n\n<b>Presence — who is online</b>\n\nPresence lets each client publish a small state object (like `{ userId, name, cursor: { x, y } }`) and automatically syncs that state across all clients in the channel. The channel maintains a live map of everyone currently connected.\n\nPresence fires three events:\n• `sync` — fires whenever the presence state changes (someone joined or left)\n• `join` — fires when a new user joins the channel\n• `leave` — fires when a user leaves (disconnects or times out)\n\n<b>Use cases for Presence</b>\n\n• 'X users online now' badge\n• Google Docs-style 'who is viewing this document' avatars\n• Multiplayer cursor tracking\n• Live collaboration indicators",
    note:
      "Presence state is automatically cleaned up when a client disconnects — even if the browser crashes or loses internet. Supabase's Realtime server uses a heartbeat to detect disconnections and removes the presence state after a short timeout. You do not have to write cleanup code.",
    diagram:
      "  BROADCAST:\n\n  Client A                 Supabase Channel               Client B\n     │  channel.send({      │                                │\n     │    type: 'broadcast',│                                │\n     │    event: 'typing',  │                                │\n     │    payload: {...}    │                                │\n     │  })                  │                                │\n     └──────────────────────►  broadcasts to all subscribers ►───┘\n                                (not stored in database)         ↓\n                                                            Client B receives\n                                                            the typing event\n\n  PRESENCE:\n\n  All clients track({ userId, name })\n       ↓\n  Channel maintains live state:\n  {\n    'client-a': { userId: '1', name: 'Rajan' },\n    'client-b': { userId: '2', name: 'Alice' }\n  }\n  → sync event fires on every join/leave",
    example:
      "import { useEffect } from 'react';\nimport { supabase } from '@/lib/supabase';\n\n// ── BROADCAST: typing indicator ─────────────────────────────────\nconst channel = supabase.channel('doc-room-123');\n\n// Listen for typing events from other users\nchannel\n  .on('broadcast', { event: 'typing' }, ({ payload }) => {\n    console.log(payload.userName, 'is typing...');\n  })\n  .subscribe();\n\n// Send a typing event (does NOT write to database)\nfunction onUserTyping(userName: string) {\n  channel.send({\n    type: 'broadcast',\n    event: 'typing',\n    payload: { userName },\n  });\n}\n\n// ── PRESENCE: who is viewing this page ──────────────────────────\nconst presenceChannel = supabase.channel('online-users');\n\npresenceChannel\n  .on('presence', { event: 'sync' }, () => {\n    const state = presenceChannel.presenceState();\n    // state = { 'key1': [{ user_id, name }], 'key2': [...] }\n    const onlineCount = Object.keys(state).length;\n    console.log(onlineCount, 'users online');\n  })\n  .on('presence', { event: 'join' }, ({ newPresences }) => {\n    console.log('User joined:', newPresences);\n  })\n  .on('presence', { event: 'leave' }, ({ leftPresences }) => {\n    console.log('User left:', leftPresences);\n  })\n  .subscribe(async (status) => {\n    if (status === 'SUBSCRIBED') {\n      // Announce this user's presence\n      await presenceChannel.track({ user_id: 'abc', name: 'Rajan' });\n    }\n  });\n\n// Clean up\nreturn () => supabase.removeChannel(presenceChannel);",
    tip: "Use Broadcast for ephemeral, high-frequency events (cursor moves, keystrokes). Use `postgres_changes` for durable data that needs to survive disconnections. Use Presence for the 'who is online' state. Each tool fits a different use case — picking the right one keeps your architecture clean.",
    tags: ["Broadcast", "Presence", "Real-time", "Online Users", "Typing Indicator", "WebSocket"],
  },

  // ─────────────────────────────────────────────
  // STORAGE
  // ─────────────────────────────────────────────
  {
    id: 16,
    section: "Storage",
    title: "Buckets & File Uploads",
    tagline: "Upload, download, and list files — images, videos, and documents",
    description:
      "Supabase Storage lets you store and serve files — images, videos, PDFs, or any other binary data. It is an S3-compatible file storage system with tight integration with your Supabase project.\n\n<b>Buckets</b>\n\nFiles are organised into <b>buckets</b> — similar to folders at the top level. A bucket is like an S3 bucket or a Google Cloud Storage bucket. You create buckets in the Supabase dashboard (Storage → New bucket) or via the API.\n\nA bucket can be:\n• <b>Public</b> — any file in the bucket has a public URL accessible to anyone without authentication\n• <b>Private</b> — files require a signed URL or an authenticated request to access\n\n<b>Uploading files</b>\n\n`supabase.storage.from('bucket-name').upload(path, file)` uploads a file. The `path` is the file's location inside the bucket (e.g., `avatars/user-123.jpg`). The `file` can be a `File` object from a file input, a `Blob`, or a `Buffer`.\n\n<b>Downloading files</b>\n\nFor public buckets: use `getPublicUrl(path)` to get a direct URL.\nFor private buckets: use `createSignedUrl(path, expiresIn)` to generate a time-limited URL.\n\n<b>File organisation best practice</b>\n\nOrganise files by user: `avatars/user-id/filename.jpg`. This makes it easy to write storage policies that restrict each user to their own folder.",
    note:
      "Files in a public bucket are truly public — anyone with the URL can access them. Do not store sensitive files (medical records, private documents) in public buckets. For private content, always use private buckets with signed URLs or authenticated downloads.",
    diagram:
      "  SUPABASE STORAGE\n\n  Bucket: 'avatars' (public)\n  │\n  ├── user-abc123/\n  │     ├── profile.jpg    ← getPublicUrl('user-abc123/profile.jpg')\n  │     └── cover.png\n  │\n  └── user-def456/\n        └── profile.jpg\n\n  UPLOAD FLOW:\n  <input type=\"file\"> → File object\n       │\n       │  supabase.storage.from('avatars').upload(path, file)\n       ↓\n  Supabase Storage (S3-compatible)\n       │\n       ↓\n  Returns: { data: { path }, error }\n       │\n       ↓\n  Get public URL:\n  supabase.storage.from('avatars').getPublicUrl(path)\n  → 'https://xxxx.supabase.co/storage/v1/object/public/avatars/...'",
    example:
      "import { supabase } from '@/lib/supabase';\n\n// ── UPLOAD ──────────────────────────────────────────────────────\nasync function uploadAvatar(userId: string, file: File) {\n  const fileExt = file.name.split('.').pop();\n  const filePath = `${userId}/avatar.${fileExt}`; // e.g. 'abc123/avatar.jpg'\n\n  const { data, error } = await supabase.storage\n    .from('avatars')               // bucket name\n    .upload(filePath, file, {\n      cacheControl: '3600',        // CDN caches for 1 hour\n      upsert: true,                // overwrite if file already exists\n    });\n\n  if (error) {\n    console.error('Upload failed:', error.message);\n    return null;\n  }\n\n  return data.path; // 'abc123/avatar.jpg'\n}\n\n// ── GET PUBLIC URL (public bucket) ──────────────────────────────\nfunction getAvatarUrl(path: string) {\n  const { data } = supabase.storage.from('avatars').getPublicUrl(path);\n  return data.publicUrl;\n  // 'https://xxxx.supabase.co/storage/v1/object/public/avatars/abc123/avatar.jpg'\n}\n\n// ── SIGNED URL (private bucket) ─────────────────────────────────\nasync function getPrivateFileUrl(path: string) {\n  const { data, error } = await supabase.storage\n    .from('private-docs')\n    .createSignedUrl(path, 60 * 60); // expires in 1 hour (3600 seconds)\n\n  return data?.signedUrl;\n}\n\n// ── DELETE ──────────────────────────────────────────────────────\nawait supabase.storage.from('avatars').remove(['abc123/avatar.jpg']);",
    tip: "Always include the user's ID in the file path (e.g., `userId/filename.ext`). This makes it simple to write storage policies: `(storage.foldername(name))[1] = auth.uid()` — only allow access to files in the user's own folder. Without this, any user could overwrite any other user's file.",
    tags: ["Storage", "Buckets", "File Upload", "getPublicUrl", "Signed URL", "S3"],
  },

  {
    id: 17,
    section: "Storage",
    title: "Storage Policies",
    tagline: "Control who can upload, download, and delete files — storage uses RLS too",
    description:
      "Just like database tables, Supabase Storage uses <b>Row Level Security policies</b> to control access. Storage policies are applied to the `storage.objects` table — each file is a row.\n\n<b>Creating storage policies</b>\n\nGo to Storage → your bucket → Policies, or write SQL directly. Policies use the same `USING` and `WITH CHECK` syntax as database policies.\n\n<b>Useful storage helper functions</b>\n\nSupabase provides helper functions you can use inside storage policies:\n• `storage.foldername(name)` — returns an array of folder segments from the file path. `storage.foldername('abc123/profile.jpg')` returns `['abc123', 'profile.jpg']`\n• `storage.filename(name)` — returns just the filename part\n• `storage.extension(name)` — returns the file extension\n\n<b>Common storage policy patterns</b>\n\n• <b>Users manage own files</b> — check that the first folder in the path equals `auth.uid()`\n• <b>Public read</b> — just enable the bucket as public (no policy needed for downloads)\n• <b>Only allow images</b> — check `storage.extension(name)` is in `('jpg', 'jpeg', 'png', 'webp')`\n• <b>Size limit</b> — check `(metadata ->> 'size')::int < 5242880` (5 MB)",
    note:
      "For most use cases, the simplest approach is: make the bucket public for reads, and write a policy for `INSERT` and `DELETE` that restricts writes to the file owner. You rarely need to restrict read access for images like profile photos.",
    diagram:
      "  STORAGE POLICY CHECK\n\n  User (id: 'abc123') tries to upload:\n  supabase.storage.from('avatars').upload('abc123/photo.jpg', file)\n\n  PostgreSQL checks INSERT policy on storage.objects:\n  USING: (storage.foldername(name))[1] = auth.uid()\n       ↓\n  storage.foldername('abc123/photo.jpg') → ['abc123', 'photo.jpg']\n  [1] → 'abc123'\n  auth.uid() → 'abc123'\n  'abc123' = 'abc123' → TRUE → upload allowed\n\n  User (id: 'abc123') tries to upload:\n  supabase.storage.from('avatars').upload('xyz999/photo.jpg', file)\n       ↓\n  'xyz999' = 'abc123' → FALSE → upload rejected",
    example:
      "-- Storage policies are written in SQL (or via the dashboard)\n\n-- Allow users to upload files only in their own folder\nCREATE POLICY \"Users upload to own folder\"\n  ON storage.objects FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    bucket_id = 'avatars'\n    AND (storage.foldername(name))[1] = auth.uid()::text\n  );\n\n-- Allow users to delete only their own files\nCREATE POLICY \"Users delete own files\"\n  ON storage.objects FOR DELETE\n  TO authenticated\n  USING (\n    bucket_id = 'avatars'\n    AND (storage.foldername(name))[1] = auth.uid()::text\n  );\n\n-- Allow anyone to read files in a public bucket\n-- (or just set the bucket to public in the dashboard)\nCREATE POLICY \"Public read\"\n  ON storage.objects FOR SELECT\n  TO anon, authenticated\n  USING (bucket_id = 'avatars');\n\n-- Only allow image file types\nCREATE POLICY \"Images only\"\n  ON storage.objects FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    bucket_id = 'avatars'\n    AND storage.extension(name) IN ('jpg', 'jpeg', 'png', 'webp', 'gif')\n  );",
    tip: "If a user can upload a file but cannot read it back (even from a public bucket), check that the bucket is set to public in the Storage dashboard. File policies control writes; the bucket's public setting controls whether the CDN URL works without authentication.",
    tags: ["Storage Policies", "RLS", "foldername", "File Access", "Bucket Security"],
  },

  // ─────────────────────────────────────────────
  // EDGE FUNCTIONS
  // ─────────────────────────────────────────────
  {
    id: 18,
    section: "Edge Functions",
    title: "What are Edge Functions?",
    tagline: "Run server-side code close to your users — without managing a server",
    description:
      "Edge Functions are small pieces of server-side code that run on Supabase's global infrastructure, close to your users.\n\n<b>Why do you need server-side code at all?</b>\n\nThe Supabase JS client runs in the browser. Some things cannot or should not happen in the browser:\n• Calling a third-party API with a secret key (Stripe, OpenAI, SendGrid) — the key must not be exposed to the browser\n• Sending emails or SMS on user actions\n• Complex business logic that should not be trusted to the client\n• Webhook handling (Stripe payments, GitHub events, etc.)\n• Running code that requires a Node.js or server environment\n\n<b>Edge Functions vs traditional serverless</b>\n\nEdge Functions run on <b>Deno</b> (not Node.js) and are deployed to servers geographically close to each user. This reduces latency compared to a single-region server. They cold start in milliseconds, not seconds.\n\n<b>How they relate to your Supabase project</b>\n\nEdge Functions have access to your project's database and auth — you can create a Supabase client inside an Edge Function using the `service_role` key to do admin operations, or the user's JWT to act on behalf of the user.\n\n<b>When to use Edge Functions</b>\n\n• Stripe webhook receiver\n• Sending a welcome email on user sign-up (via a database webhook)\n• A custom auth flow or third-party login\n• An AI endpoint that calls OpenAI\n• Any operation requiring a secret key",
    note:
      "Edge Functions run Deno, not Node.js. Most npm packages do not work directly — but many popular ones have Deno-compatible versions (via `npm:` specifier or esm.sh CDN). The Supabase JS client (`@supabase/supabase-js`) works perfectly in Edge Functions.",
    diagram:
      "  WITHOUT EDGE FUNCTIONS (secret key exposed):\n\n  Browser → calls Stripe API directly → exposes Stripe secret key in browser ← BAD\n\n  ─────────────────────────────────────────────────────────────────────────────\n\n  WITH EDGE FUNCTIONS (secret key hidden):\n\n  Browser\n    │  POST /functions/v1/create-payment\n    │  { amount: 999, currency: 'usd' }\n    ↓\n  Edge Function (server-side, Deno)\n    │  Uses STRIPE_SECRET_KEY from environment (never sent to browser)\n    │  Calls Stripe API\n    ↓\n  Stripe\n    │  Returns payment intent\n    ↓\n  Edge Function returns { clientSecret } to browser\n    │\n    ↓\n  Browser uses clientSecret to complete payment (no secret key needed)",
    example:
      "// supabase/functions/send-welcome-email/index.ts\n// Deploy with: supabase functions deploy send-welcome-email\n\nimport { serve } from 'https://deno.land/std@0.168.0/http/server.ts';\n\nconst RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')!;\n\nserve(async (req: Request) => {\n  // Parse the request body\n  const { email, name } = await req.json();\n\n  // Call a third-party email API (key is safe — it never leaves the server)\n  const response = await fetch('https://api.resend.com/emails', {\n    method: 'POST',\n    headers: {\n      'Authorization': `Bearer ${RESEND_API_KEY}`,\n      'Content-Type': 'application/json',\n    },\n    body: JSON.stringify({\n      from: 'hello@myapp.com',\n      to: email,\n      subject: 'Welcome to MyApp!',\n      html: `<h1>Welcome, ${name}!</h1><p>Thanks for joining.</p>`,\n    }),\n  });\n\n  if (!response.ok) {\n    return new Response(JSON.stringify({ error: 'Failed to send email' }), {\n      status: 500,\n      headers: { 'Content-Type': 'application/json' },\n    });\n  }\n\n  return new Response(JSON.stringify({ success: true }), {\n    headers: { 'Content-Type': 'application/json' },\n  });\n});\n\n// Call it from your app:\nconst { data, error } = await supabase.functions.invoke('send-welcome-email', {\n  body: { email: 'rajan@example.com', name: 'Rajan' },\n});",
    tip: "Store secrets (API keys, webhook signing keys) as Edge Function secrets, not in environment variables committed to git. Use `supabase secrets set MY_KEY=value` to add them. In your function, read them with `Deno.env.get('MY_KEY')`. They are encrypted at rest and never appear in logs.",
    tags: ["Edge Functions", "Serverless", "Deno", "Server-side", "Webhooks", "API Keys"],
  },

  {
    id: 19,
    section: "Edge Functions",
    title: "Writing & Deploying Edge Functions",
    tagline: "The Supabase CLI, local development, environment secrets, and deploying to production",
    description:
      "Edge Functions are developed locally using the Supabase CLI and deployed with a single command.\n\n<b>Setting up the Supabase CLI</b>\n\nInstall with `npm install -g supabase` or `brew install supabase/tap/supabase`. Log in with `supabase login`.\n\n<b>Initialise your project</b>\n\nRun `supabase init` in your project root. This creates a `supabase/` folder where your functions live.\n\n<b>Creating a function</b>\n\n`supabase functions new my-function` creates `supabase/functions/my-function/index.ts` — a starter Deno TypeScript file.\n\n<b>Running locally</b>\n\n`supabase functions serve` starts a local server at `http://localhost:54321/functions/v1/`. It hot-reloads on file changes. You can test your function with `curl` or from your app pointing to `localhost`.\n\n<b>Environment secrets</b>\n\nDo not hardcode secrets. Use `supabase secrets set MY_KEY=value` to store them. They are available in your function via `Deno.env.get('MY_KEY')`. List them with `supabase secrets list`.\n\n<b>Deploying</b>\n\n`supabase functions deploy my-function` deploys the function to your project. The function is live at `https://your-project.supabase.co/functions/v1/my-function`.\n\n<b>Calling from the client</b>\n\nUse `supabase.functions.invoke('function-name', { body: {...} })`. This attaches the user's JWT automatically, so the function knows who called it.",
    note:
      "Edge Functions time out after 150 seconds (2.5 minutes). They are not meant for long-running jobs. For background work that takes longer — video processing, sending thousands of emails, batch imports — use a dedicated job queue or a cron-triggered Edge Function that processes work in batches.",
    diagram:
      "  DEVELOPMENT WORKFLOW\n\n  1. supabase init\n     └── creates supabase/ folder\n\n  2. supabase functions new process-payment\n     └── creates supabase/functions/process-payment/index.ts\n\n  3. supabase secrets set STRIPE_KEY=sk_test_...\n     └── stored encrypted, never committed to git\n\n  4. supabase functions serve\n     └── runs locally at localhost:54321/functions/v1/\n     └── hot-reloads on save\n\n  5. Test:\n     curl -X POST localhost:54321/functions/v1/process-payment \\\n       -H 'Authorization: Bearer <your-anon-key>' \\\n       -d '{\"amount\": 999}'\n\n  6. supabase functions deploy process-payment\n     └── live at https://xxxx.supabase.co/functions/v1/process-payment",
    example:
      "// supabase/functions/get-ai-summary/index.ts\nimport { serve } from 'https://deno.land/std@0.168.0/http/server.ts';\nimport { createClient } from 'npm:@supabase/supabase-js';\n\nserve(async (req: Request) => {\n  // 1. Get the user's JWT from the request header\n  const authHeader = req.headers.get('Authorization')!;\n\n  // 2. Create a Supabase client acting as the user\n  const supabase = createClient(\n    Deno.env.get('SUPABASE_URL')!,\n    Deno.env.get('SUPABASE_ANON_KEY')!,\n    { global: { headers: { Authorization: authHeader } } }\n  );\n\n  // 3. Read the request body\n  const { postId } = await req.json();\n\n  // 4. Fetch the post from the database (as the user — RLS applies)\n  const { data: post, error } = await supabase\n    .from('posts')\n    .select('title, body')\n    .eq('id', postId)\n    .single();\n\n  if (error) return new Response(JSON.stringify({ error: error.message }), { status: 400 });\n\n  // 5. Call OpenAI (secret key never reaches the browser)\n  const aiRes = await fetch('https://api.openai.com/v1/chat/completions', {\n    method: 'POST',\n    headers: {\n      Authorization: `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,\n      'Content-Type': 'application/json',\n    },\n    body: JSON.stringify({\n      model: 'gpt-4o-mini',\n      messages: [{ role: 'user', content: `Summarise in 2 sentences: ${post.body}` }],\n    }),\n  });\n\n  const aiData = await aiRes.json();\n  const summary = aiData.choices[0].message.content;\n\n  return new Response(JSON.stringify({ summary }), {\n    headers: { 'Content-Type': 'application/json' },\n  });\n});\n\n// From your React component:\nconst { data } = await supabase.functions.invoke('get-ai-summary', {\n  body: { postId: 'abc123' },\n});",
    tip: "Use `Deno.env.get('SUPABASE_URL')` and `Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')` inside Edge Functions — these are automatically injected by Supabase without you having to set them manually. Use the service role key only for admin operations; for user-scoped work, forward the user's JWT from the request.",
    tags: ["Supabase CLI", "Deploy", "Edge Functions", "Deno", "Secrets", "Local Development"],
  },

  // ─────────────────────────────────────────────
  // ADVANCED PATTERNS
  // ─────────────────────────────────────────────
  {
    id: 20,
    section: "Advanced Patterns",
    title: "Database Webhooks & Triggers",
    tagline: "Automatically run code when a row is inserted, updated, or deleted",
    description:
      "Database webhooks let you run code automatically in response to database changes — without the client having to do anything.\n\n<b>The use case</b>\n\nWhen a new user signs up, you want to:\n• Send a welcome email\n• Create a default profile row\n• Add them to a mailing list\n• Notify a Slack channel\n\nYou could do this in your frontend code after calling `signUp()`, but that is fragile — the user might close the browser before it runs. A database webhook fires reliably from the server, regardless of what the client does.\n\n<b>How Supabase database webhooks work</b>\n\n1. You create a webhook in the Supabase dashboard (Database → Webhooks)\n2. You specify which table and event to watch (INSERT on `auth.users`, for example)\n3. When the event happens, Supabase sends an HTTP POST to a URL you provide — typically one of your Edge Functions\n4. Your Edge Function receives the event payload and does whatever you need\n\n<b>PostgreSQL triggers</b>\n\nUnder the hood, Supabase webhooks use a PostgreSQL extension called `pg_net` which can make HTTP requests from within PostgreSQL trigger functions. This means the HTTP call happens at the database level — it is guaranteed to fire as part of the transaction.\n\n<b>The event payload</b>\n\nThe webhook sends a JSON payload with `type` (INSERT/UPDATE/DELETE), `table`, `schema`, `old_record`, and `new_record`.",
    note:
      "Supabase also has a `handle_new_user` pattern: create a PostgreSQL trigger function that runs `INSERT INTO public.profiles (id, email) VALUES (new.id, new.email)` whenever a new row is added to `auth.users`. This is the recommended way to automatically create a profile row for every new user.",
    diagram:
      "  DATABASE WEBHOOK FLOW\n\n  User signs up\n       │\n       ↓\n  New row inserted into auth.users\n       │\n       │  PostgreSQL trigger fires (pg_net)\n       ↓\n  HTTP POST to your Edge Function:\n  {\n    type: 'INSERT',\n    table: 'users',\n    schema: 'auth',\n    new_record: {\n      id: 'abc123',\n      email: 'rajan@example.com',\n      created_at: '2024-01-15T09:30:00+00:00'\n    },\n    old_record: null\n  }\n       │\n       ↓\n  Edge Function:\n  ├── Creates profile row in public.profiles\n  ├── Sends welcome email via Resend\n  └── Notifies Slack webhook",
    example:
      "-- Step 1: Create a profiles table that mirrors auth.users\nCREATE TABLE public.profiles (\n  id         uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,\n  email      text,\n  full_name  text,\n  avatar_url text,\n  created_at timestamptz DEFAULT now()\n);\n\n-- Step 2: Trigger function — runs when a new user signs up\nCREATE OR REPLACE FUNCTION public.handle_new_user()\nRETURNS trigger AS $$\nBEGIN\n  INSERT INTO public.profiles (id, email, full_name)\n  VALUES (\n    new.id,\n    new.email,\n    new.raw_user_meta_data ->> 'full_name'\n  );\n  RETURN new;\nEND;\n$$ LANGUAGE plpgsql SECURITY DEFINER;\n\n-- Step 3: Attach the trigger to auth.users\nCREATE TRIGGER on_auth_user_created\n  AFTER INSERT ON auth.users\n  FOR EACH ROW\n  EXECUTE FUNCTION public.handle_new_user();\n\n-- Now every time a user signs up:\n-- 1. Supabase creates the row in auth.users\n-- 2. The trigger fires and creates a row in public.profiles\n-- 3. You can query profiles just like any other table\n-- 4. RLS on profiles controls who sees what\n\n-- Query the profile of the logged-in user:\nconst { data: profile } = await supabase\n  .from('profiles')\n  .select('*')\n  .eq('id', user.id)\n  .single();",
    tip: "The `handle_new_user` trigger is the most common Supabase pattern. Add it to every project that has user accounts. It gives you a `public.profiles` table you can join to, add columns to, and write RLS policies against — without touching the read-only `auth.users` table.",
    tags: ["Webhooks", "Triggers", "PostgreSQL", "handle_new_user", "Profiles", "Automation"],
  },

  {
    id: 21,
    section: "Advanced Patterns",
    title: "Optimistic UI & Sync Patterns",
    tagline: "Update the UI instantly, sync to Supabase in the background, handle errors gracefully",
    description:
      "An <b>optimistic UI</b> update means updating the interface immediately when the user takes an action — before waiting for the server to confirm. If the server responds with an error, you roll back to the previous state.\n\n<b>Why optimistic updates?</b>\n\nWithout optimistic updates, every click waits for a network round-trip before the UI reacts. On a good connection that is 50-100ms. On a slow connection it is 500ms+. The UI feels sluggish.\n\nWith optimistic updates, the UI responds instantly (0ms perceived latency). The network call happens in the background. For 99% of operations that succeed, the user never notices the background sync. For the 1% that fail, you show an error and undo the change.\n\n<b>The pattern</b>\n\n1. User takes an action (checks a checkbox, types a message, deletes an item)\n2. Update local state immediately — UI reflects the change at once\n3. Fire the Supabase operation in the background (no `await` blocking the UI)\n4. If the operation succeeds: nothing to do — the local state is already correct\n5. If the operation fails: revert local state + show an error message\n\n<b>Combining with real-time</b>\n\nWhen multiple users are editing the same data, combine optimistic updates with real-time subscriptions. The optimistic update handles the local user's changes instantly; the real-time subscription brings in other users' changes.\n\n<b>Idempotent client IDs</b>\n\nGenerate a client-side ID (UUID) before inserting. This way, you can optimistically add the item to the UI immediately using the pre-generated ID, and the database uses the same ID — no mismatch when the insert completes.",
    note:
      "The pattern used in the Supabase-powered TodoPage in this app is a good example: localStorage is updated synchronously for an instant response, then Supabase is written to in the background. On page load, localStorage gives an instant first render; Supabase then replaces it with the authoritative data.",
    diagram:
      "  OPTIMISTIC UPDATE FLOW\n\n  User clicks 'Complete task'\n         │\n         ├──► Update local state immediately (0ms — instant)\n         │    setTasks(tasks.map(t => t.id === id ? {...t, done: true} : t))\n         │\n         └──► Fire Supabase in background (non-blocking)\n              supabase.from('tasks').update({ done: true }).eq('id', id)\n                    │\n                    ├── Success (99%): nothing to do — UI already correct\n                    │\n                    └── Error (1%): roll back\n                         setTasks(previousTasks)  ← undo the optimistic update\n                         showError('Failed to save. Please try again.')\n\n  PERCEIVED LATENCY:\n  Without optimistic: click → wait 200ms → UI updates\n  With optimistic:    click → UI updates instantly → syncs in background",
    example:
      "import { useState, useCallback } from 'react';\nimport { supabase } from '@/lib/supabase';\n\ntype Task = { id: string; text: string; completed: boolean };\n\nexport function TaskList({ initialTasks }: { initialTasks: Task[] }) {\n  const [tasks, setTasks] = useState(initialTasks);\n\n  const toggleTask = useCallback(async (id: string) => {\n    // 1. Save previous state in case we need to roll back\n    const previous = tasks;\n\n    // 2. Optimistic update — flip the completed state immediately\n    const next = tasks.map((t) =>\n      t.id === id ? { ...t, completed: !t.completed } : t\n    );\n    setTasks(next);\n\n    // 3. Sync to Supabase in the background\n    const updated = next.find((t) => t.id === id)!;\n    const { error } = await supabase\n      .from('tasks')\n      .update({ completed: updated.completed })\n      .eq('id', id);\n\n    // 4. Roll back if the update failed\n    if (error) {\n      setTasks(previous);\n      alert('Failed to save. Check your connection and try again.');\n    }\n  }, [tasks]);\n\n  async function addTask(text: string) {\n    // Pre-generate the ID — use it both in UI and in the insert\n    const id = crypto.randomUUID();\n\n    // Optimistic: add to UI immediately\n    setTasks((prev) => [...prev, { id, text, completed: false }]);\n\n    // Background sync\n    const { error } = await supabase\n      .from('tasks')\n      .insert({ id, text, completed: false });\n\n    // Roll back on error\n    if (error) setTasks((prev) => prev.filter((t) => t.id !== id));\n  }\n\n  return (\n    <ul>\n      {tasks.map((t) => (\n        <li key={t.id}>\n          <input type=\"checkbox\" checked={t.completed} onChange={() => toggleTask(t.id)} />\n          {t.text}\n        </li>\n      ))}\n    </ul>\n  );\n}",
    tip: "Always save the previous state before an optimistic update so you can roll back: `const previous = tasks; setTasks(next); const { error } = await ...; if (error) setTasks(previous);`. This three-line pattern handles rollback for any operation.",
    tags: ["Optimistic UI", "Sync", "localStorage", "Rollback", "UX", "State Management"],
  },

];

export const SUPABASE_CONCEPT_COUNT = SUPABASE_CONCEPTS.length;
