import { markdownLessonDay } from "@/lib/learn/markdown-lesson-day";
import { REACT_NATIVE_DAY_3_FINAL_QUIZ } from "@/lib/react-native-learning/react-native-final-quizzes";

const DAY_3_CONTENT = [
  "## Day 3 — Core Components & Layout",
  "",
  "### 1. `View` — the foundation of native UI",
  "",
  "**What you'll learn**",
  "",
  "* What `View` represents",
  "* `View` as the basic container",
  "* Important `View` props",
  "* Flexbox layout",
  "* Nested views",
  "* `style` and style arrays",
  "* `onLayout`",
  "* `pointerEvents`",
  "* Accessibility-related props",
  "",
  "**Important props**",
  "",
  "| Prop                 | Purpose                                                  |",
  "| -------------------- | -------------------------------------------------------- |",
  "| `style`              | Controls layout and appearance                           |",
  "| `onLayout`           | Receives the rendered size and position                  |",
  "| `testID`             | Identifier for testing                                   |",
  "| `accessible`         | Marks the view as an accessibility element               |",
  "| `accessibilityLabel` | Describes the element to assistive technologies          |",
  "| `accessibilityRole`  | Defines its semantic role                                |",
  "| `pointerEvents`      | Controls whether the view participates in touch handling |",
  "| `collapsable`        | Controls native view flattening behavior on Android      |",
  "",
  "```tsx",
  "import { View, Text } from \"react-native\";",
  "",
  "export function ProfileCard() {",
  "  return (",
  "    <View",
  "      style={{",
  "        padding: 16,",
  "        borderRadius: 12,",
  "        backgroundColor: \"white\",",
  "      }}",
  "    >",
  "      <Text>Rajan</Text>",
  "      <Text>Software Engineer</Text>",
  "    </View>",
  "  );",
  "}",
  "```",
  "",
  "### 2. `Text` — displaying text correctly",
  "",
  "React Native text must be rendered inside a `Text` component.",
  "",
  "Unlike the web, you cannot place raw text directly inside a `View`.",
  "",
  "**Important props**",
  "",
  "| Prop                    | Purpose                             |",
  "| ----------------------- | ----------------------------------- |",
  "| `style`                 | Typography and appearance           |",
  "| `numberOfLines`         | Limits displayed lines              |",
  "| `ellipsizeMode`         | Controls truncation                 |",
  "| `onTextLayout`          | Receives text layout information    |",
  "| `selectable`            | Allows text selection               |",
  "| `adjustsFontSizeToFit`  | Shrinks text to fit available space |",
  "| `minimumFontScale`      | Minimum scaling factor              |",
  "| `allowFontScaling`      | Allows system font scaling          |",
  "| `maxFontSizeMultiplier` | Limits accessibility font scaling   |",
  "| `onPress`               | Handles text presses                |",
  "| `accessibilityLabel`    | Accessibility description           |",
  "",
  "**Important text styles**",
  "",
  "```tsx",
  "<Text",
  "  numberOfLines={2}",
  "  ellipsizeMode=\"tail\"",
  "  style={{",
  "    fontSize: 18,",
  "    fontWeight: \"600\",",
  "    lineHeight: 26,",
  "    letterSpacing: 0.2,",
  "    textAlign: \"center\",",
  "    color: \"#111\",",
  "  }}",
  ">",
  "  A long piece of text that may need to be truncated.",
  "</Text>",
  "```",
  "",
  "**Key idea:** Text has its own layout behavior. Don't treat it exactly like a web `<div>`.",
  "",
  "---",
  "",
  "### 3. `Image` — displaying local and remote images",
  "",
  "`Image` renders images from local assets or remote URLs.",
  "",
  "**Important props**",
  "",
  "| Prop                 | Purpose                            |",
  "| -------------------- | ---------------------------------- |",
  "| `source`             | Image source                       |",
  "| `resizeMode`         | Controls how image fits its bounds |",
  "| `style`              | Size and appearance                |",
  "| `resizeMethod`       | Android image resize strategy      |",
  "| `defaultSource`      | Placeholder/default image          |",
  "| `onLoad`             | Image loaded                       |",
  "| `onLoadStart`        | Loading started                    |",
  "| `onLoadEnd`          | Loading finished                   |",
  "| `onError`            | Loading failed                     |",
  "| `onProgress`         | Loading progress                   |",
  "| `onLayout`           | Image layout information           |",
  "| `tintColor`          | Applies a tint                     |",
  "| `accessible`         | Accessibility support              |",
  "| `accessibilityLabel` | Image description                  |",
  "",
  "```tsx",
  "<Image",
  "  source={{ uri: \"https://example.com/avatar.jpg\" }}",
  "  style={{",
  "    width: 80,",
  "    height: 80,",
  "    borderRadius: 40,",
  "  }}",
  "  resizeMode=\"cover\"",
  "  accessibilityLabel=\"Rajan's profile picture\"",
  "/>",
  "```",
  "",
  "Common `resizeMode` values:",
  "",
  "```text",
  "cover",
  "contain",
  "stretch",
  "repeat",
  "center",
  "```",
  "",
  "Understand the difference between **cover** and **contain**:",
  "",
  "```text",
  "cover",
  "+----------------+",
  "|████████████████|",
  "|████ image █████|",
  "|████████████████|",
  "+----------------+",
  "",
  "contain",
  "+----------------+",
  "|                |",
  "|    ┌──────┐    |",
  "|    │image │    |",
  "|    └──────┘    |",
  "|                |",
  "+----------------+",
  "```",
  "",
  "---",
  "",
  "### 4. `ScrollView` — scrolling content",
  "",
  "`ScrollView` renders all of its children and allows the user to scroll through them.",
  "",
  "It is appropriate for content that is reasonably small or where virtualization is unnecessary.",
  "",
  "**Important props**",
  "",
  "| Prop                             | Purpose                             |",
  "| -------------------------------- | ----------------------------------- |",
  "| `horizontal`                     | Enables horizontal scrolling        |",
  "| `contentContainerStyle`          | Styles the inner content container  |",
  "| `showsVerticalScrollIndicator`   | Controls vertical scrollbar         |",
  "| `showsHorizontalScrollIndicator` | Controls horizontal scrollbar       |",
  "| `refreshControl`                 | Adds pull-to-refresh                |",
  "| `keyboardShouldPersistTaps`      | Controls keyboard/touch interaction |",
  "| `keyboardDismissMode`            | Controls keyboard dismissal         |",
  "| `onScroll`                       | Receives scroll events              |",
  "| `scrollEventThrottle`            | Controls scroll event frequency     |",
  "| `onContentSizeChange`            | Content size changed                |",
  "| `onLayout`                       | ScrollView layout                   |",
  "| `nestedScrollEnabled`            | Android nested scrolling            |",
  "| `bounces`                        | iOS bounce behavior                 |",
  "| `pagingEnabled`                  | Page-by-page scrolling              |",
  "| `snapToInterval`                 | Snap scrolling to intervals         |",
  "| `snapToOffsets`                  | Snap to specific offsets            |",
  "| `decelerationRate`               | Controls deceleration               |",
  "",
  "```tsx",
  "<ScrollView",
  "  contentContainerStyle={{",
  "    padding: 16,",
  "    gap: 16,",
  "  }}",
  "  showsVerticalScrollIndicator={false}",
  ">",
  "  <ProfileCard />",
  "  <ProfileCard />",
  "  <ProfileCard />",
  "</ScrollView>",
  "```",
  "",
  "### Important distinction",
  "",
  "```text",
  "ScrollView",
  "    |",
  "    +-- renders everything",
  "    |",
  "    +-- good for smaller content",
  "",
  "",
  "FlatList",
  "    |",
  "    +-- virtualizes items",
  "    |",
  "    +-- good for large collections",
  "```",
  "",
  "This becomes especially important when we reach lists and performance.",
  "",
  "---",
  "",
  "### 5. `Pressable` — handling interaction",
  "",
  "`Pressable` is the primary component for creating interactive touch targets.",
  "",
  "It provides interaction states such as:",
  "",
  "```text",
  "pressed",
  "hovered",
  "focused",
  "```",
  "",
  "depending on platform and input method.",
  "",
  "**Important props**",
  "",
  "| Prop                   | Purpose                                                  |",
  "| ---------------------- | -------------------------------------------------------- |",
  "| `onPress`              | Main press handler                                       |",
  "| `onLongPress`          | Long-press handler                                       |",
  "| `onPressIn`            | Press started                                            |",
  "| `onPressOut`           | Press ended                                              |",
  "| `disabled`             | Disables interaction                                     |",
  "| `delayLongPress`       | Delay before long press                                  |",
  "| `hitSlop`              | Expands touchable area                                   |",
  "| `pressRetentionOffset` | Controls how far finger can move while maintaining press |",
  "| `android_ripple`       | Android ripple configuration                             |",
  "| `style`                | Can receive the interaction state                        |",
  "| `children`             | Can receive the interaction state                        |",
  "",
  "```tsx",
  "<Pressable",
  "  onPress={() => console.log(\"Pressed\")}",
  "  style={({ pressed }) => ({",
  "    padding: 16,",
  "    borderRadius: 10,",
  "    backgroundColor: pressed ? \"#ddd\" : \"#eee\",",
  "    opacity: pressed ? 0.7 : 1,",
  "  })}",
  ">",
  "  <Text>Press me</Text>",
  "</Pressable>",
  "```",
  "",
  "This is the React Native equivalent of thinking:",
  "",
  "```text",
  "normal state",
  "     |",
  "     v",
  "user presses",
  "     |",
  "     v",
  "pressed state",
  "     |",
  "     v",
  "style changes",
  "```",
  "",
  "Do **not** try to use:",
  "",
  "```css",
  "button:hover",
  "button:active",
  "```",
  "",
  "React Native does not use browser CSS pseudo-classes.",
  "",
  "---",
  "",
  "### 6. Flexbox in React Native",
  "",
  "Flexbox is the primary layout system.",
  "",
  "The biggest difference from the web:",
  "",
  "> React Native defaults to `flexDirection: \"column\"`.",
  "",
  "Web CSS normally defaults to:",
  "",
  "```css",
  "flex-direction: row;",
  "```",
  "",
  "React Native defaults to:",
  "",
  "```tsx",
  "flexDirection: \"column\";",
  "```",
  "",
  "Important properties:",
  "",
  "```text",
  "flexDirection",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "flexWrap",
  "alignContent",
  "gap",
  "rowGap",
  "columnGap",
  "```",
  "",
  "Example:",
  "",
  "```tsx",
  "<View",
  "  style={{",
  "    flexDirection: \"row\",",
  "    justifyContent: \"space-between\",",
  "    alignItems: \"center\",",
  "    gap: 12,",
  "  }}",
  ">",
  "  <Text>Profile</Text>",
  "  <Text>Settings</Text>",
  "</View>",
  "```",
  "",
  "Understand the axes:",
  "",
  "```text",
  "flexDirection: \"row\"",
  "",
  "MAIN AXIS",
  "------------------------------------>",
  "[ A ][ B ][ C ]",
  "",
  "CROSS AXIS",
  "     |",
  "     |",
  "     v",
  "",
  "",
  "flexDirection: \"column\"",
  "",
  "MAIN AXIS",
  "     |",
  "     v",
  "[ A ]",
  "[ B ]",
  "[ C ]",
  "",
  "CROSS AXIS",
  "<-------->",
  "```",
  "",
  "---",
  "",
  "### 7. Dimensions and responsive layouts",
  "",
  "React Native provides:",
  "",
  "```tsx",
  "import {",
  "  Dimensions,",
  "  useWindowDimensions,",
  "} from \"react-native\";",
  "```",
  "",
  "`Dimensions` can read dimensions directly.",
  "",
  "```tsx",
  "const { width, height } = Dimensions.get(\"window\");",
  "```",
  "",
  "But for responsive components, prefer:",
  "",
  "```tsx",
  "const { width, height } = useWindowDimensions();",
  "```",
  "",
  "because it updates when the window dimensions change.",
  "",
  "```tsx",
  "function ResponsiveScreen() {",
  "  const { width } = useWindowDimensions();",
  "",
  "  const isLarge = width >= 768;",
  "",
  "  return (",
  "    <View",
  "      style={{",
  "        flexDirection: isLarge ? \"row\" : \"column\",",
  "      }}",
  "    >",
  "      <Sidebar />",
  "      <Content />",
  "    </View>",
  "  );",
  "}",
  "```",
  "",
  "You should understand:",
  "",
  "```text",
  "fixed dimensions",
  "percentage dimensions",
  "flexbox",
  "useWindowDimensions",
  "breakpoints",
  "```",
  "",
  "---",
  "",
  "### 8. Safe areas",
  "",
  "Modern phones have areas occupied by:",
  "",
  "* status bars",
  "* camera cutouts",
  "* Dynamic Island",
  "* home indicators",
  "* navigation areas",
  "",
  "Don't manually guess these dimensions.",
  "",
  "For production applications, learn:",
  "",
  "```tsx",
  "react-native-safe-area-context",
  "```",
  "",
  "Example:",
  "",
  "```tsx",
  "import {",
  "  SafeAreaView,",
  "} from \"react-native-safe-area-context\";",
  "",
  "export function Screen() {",
  "  return (",
  "    <SafeAreaView style={{ flex: 1 }}>",
  "      <Content />",
  "    </SafeAreaView>",
  "  );",
  "}",
  "```",
  "",
  "Also understand:",
  "",
  "```tsx",
  "useSafeAreaInsets()",
  "```",
  "",
  "when you need precise control.",
  "",
  "```tsx",
  "const insets = useSafeAreaInsets();",
  "",
  "<View",
  "  style={{",
  "    paddingTop: insets.top,",
  "    paddingBottom: insets.bottom,",
  "  }}",
  "/>",
  "```",
  "",
  "---",
  "",
  "### 9. `Platform`",
  "",
  "React Native applications run on multiple operating systems, but iOS and Android are not identical.",
  "",
  "Use:",
  "",
  "```tsx",
  "import { Platform } from \"react-native\";",
  "```",
  "",
  "Important APIs:",
  "",
  "```tsx",
  "Platform.OS",
  "Platform.select()",
  "Platform.Version",
  "Platform.isPad",
  "```",
  "",
  "Example:",
  "",
  "```tsx",
  "const padding = Platform.select({",
  "  ios: 20,",
  "  android: 16,",
  "  default: 16,",
  "});",
  "```",
  "",
  "You can also create platform-specific files:",
  "",
  "```text",
  "Button.tsx",
  "Button.ios.tsx",
  "Button.android.tsx",
  "```",
  "",
  "React Native automatically selects the platform-specific implementation.",
  "",
  "---",
  "",
  "### 10. `KeyboardAvoidingView`",
  "",
  "The software keyboard can cover inputs, especially on smaller screens.",
  "",
  "`KeyboardAvoidingView` helps adjust the layout when the keyboard appears.",
  "",
  "Important props:",
  "",
  "```text",
  "behavior",
  "keyboardVerticalOffset",
  "contentContainerStyle",
  "enabled",
  "```",
  "",
  "Example:",
  "",
  "```tsx",
  "<KeyboardAvoidingView",
  "  behavior={Platform.OS === \"ios\" ? \"padding\" : \"height\"}",
  "  style={{ flex: 1 }}",
  ">",
  "  <ScrollView>",
  "    <TextInput />",
  "  </ScrollView>",
  "</KeyboardAvoidingView>",
  "```",
  "",
  "You should understand that keyboard behavior differs between iOS and Android and should be tested on both.",
  "",
  "---",
  "",
  "### 11. `Modal`",
  "",
  "React Native also provides a native `Modal`.",
  "",
  "Important props include:",
  "",
  "```text",
  "visible",
  "animationType",
  "transparent",
  "presentationStyle",
  "onRequestClose",
  "statusBarTranslucent",
  "hardwareAccelerated",
  "```",
  "",
  "Example:",
  "",
  "```tsx",
  "<Modal",
  "  visible={visible}",
  "  transparent",
  "  animationType=\"fade\"",
  "  onRequestClose={() => setVisible(false)}",
  ">",
  "  <View>",
  "    <Text>Are you sure?</Text>",
  "  </View>",
  "</Modal>",
  "```",
  "",
  "Understand the difference:",
  "",
  "```text",
  "Modal component",
  "    |",
  "    +-- temporary UI overlay",
  "",
  "",
  "Navigation modal",
  "    |",
  "    +-- navigation destination",
  "    +-- can have route/deep-link semantics",
  "```",
  "",
  "---",
  "",
  "## Final project — Responsive profile screen",
  "",
  "Build a profile screen containing:",
  "",
  "```text",
  "┌─────────────────────────────┐",
  "│        Profile              │",
  "│                             │",
  "│       ┌──────────┐          │",
  "│       │  Avatar  │          │",
  "│       └──────────┘          │",
  "│                             │",
  "│       Rajan Magar           │",
  "│    Software Engineer        │",
  "│                             │",
  "│ ┌──────────┐ ┌───────────┐ │",
  "│ │ Projects │ │ Experience│ │",
  "│ └──────────┘ └───────────┘ │",
  "│                             │",
  "│       [ Edit Profile ]      │",
  "└─────────────────────────────┘",
  "```",
  "",
  "### Requirements",
  "",
  "* Use `View` for layout.",
  "* Use `Text` for all text.",
  "* Use `Image` for the profile image.",
  "* Use `Pressable` for the button.",
  "* Use `ScrollView` for the screen.",
  "* Use Flexbox for layout.",
  "* Use `useWindowDimensions()` for responsive behavior.",
  "* Handle safe-area insets.",
  "* Make the layout different on narrow and wide screens.",
  "* Make the button keyboard-safe if the screen later contains editable fields.",
  "* Test on both iOS and Android.",
  "",
  "### Self-check",
  "",
  "You should be able to explain:",
  "",
  "1. Why React Native defaults to column flex direction.",
  "2. Why `ScrollView` should not be used for every large list.",
  "3. How `Pressable` differs from a browser button.",
  "4. Why `useWindowDimensions()` is useful for responsive layouts.",
  "5. Why safe-area handling matters.",
  "6. When to use `Platform.select()`.",
  "7. When a `Modal` should be a navigation destination instead.",
  "8. Which important props each core component provides.",
  "",
].join("\n");

export const REACT_NATIVE_DAY_3_LESSONS = markdownLessonDay(
  3,
  "Core Components & Layout",
  DAY_3_CONTENT,
  REACT_NATIVE_DAY_3_FINAL_QUIZ,
);
