import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

type Input = { id: string; title: string; explanation: string; diagram: string; code: string; takeaways: string[]; mistakes: string[]; question: string; options: string[]; correctIndex: number; answer: string };
const lesson = (input: Input) => ({ id: input.id, title: input.title, durationMinutes: 13, explanation: input.explanation, diagram: input.diagram, codeExample: { title: `${input.title} example`, code: input.code }, keyTakeaways: input.takeaways, commonMistakes: input.mistakes, quiz: [{ question: input.question, options: input.options, correctIndex: input.correctIndex, explanation: input.answer }] });

export const NEXTJS_DAY_7_LESSONS = normalizePastedLessonDay({
  day: 7, title: "Data Fetching, Caching, Revalidation & Server-Side Data Patterns", totalMinutes: 80, difficulty: "Beginner",
  overview: "<b>Goal:</b> fetch data on the server, choose an appropriate freshness strategy, and avoid unnecessary request waterfalls.",
  lessons: [
    lesson({ id: "nextjs-server-data", title: "Server-side data fetching patterns", explanation: "Server Components can fetch data directly with `await`. You do not automatically need client `useEffect` and `useState` for the initial page data. Keep fetching code in focused functions, check failed responses, and render server data into the route.\n\nThis keeps server-only credentials private and sends useful UI instead of making every page wait for browser-side fetching.", diagram: "Request → Server Component → fetch / database → render UI → browser", code: `async function getUsers(): Promise<User[]> {\n  const response = await fetch("https://api.example.com/users");\n  if (!response.ok) throw new Error("Failed to fetch users");\n  return response.json();\n}\n\nexport default async function UsersPage() {\n  const users = await getUsers();\n  return <main>{users.map((user) => <p key={user.id}>{user.name}</p>)}</main>;\n}`, takeaways: ["Server Components can be async.", "Initial server data does not need `useEffect`.", "Handle unsuccessful responses."], mistakes: ["Fetching server-ready data in a Client Component by default.", "Sending server credentials to the browser."], question: "Where can an App Router Server Component await initial data?", options: ["Directly while rendering", "Only in useEffect", "Only after hydration", "Only in a client event"], correctIndex: 0, answer: "Server Components can await data directly." }),
    lesson({ id: "nextjs-data-sources", title: "Your backend, external APIs, and databases", explanation: "Next.js can fetch from your own backend, an external API, or a database through server-only code. The data source does not need to be built in Next.js. Keep integration code behind a small function so pages focus on route UI and failures are handled consistently.\n\nUse the server boundary for private API tokens and database credentials. A Client Component should receive only the serializable data it needs.", diagram: "Server Component\n ├── Your API\n ├── External API\n └── Database\n      ↓\nSerializable UI data", code: `async function getProjects() {\n  const response = await fetch("https://api.example.com/projects", {\n    headers: { Authorization: process.env.API_TOKEN! },\n  });\n  if (!response.ok) throw new Error("Could not load projects");\n  return response.json();\n}`, takeaways: ["Next.js can integrate with any server data source.", "Keep private tokens on the server."], mistakes: ["Calling a private backend directly from browser code.", "Mixing route UI and every API detail in one component."], question: "Where should a private API token be used?", options: ["Server-only code", "A public environment variable", "A Link component", "CSS"], correctIndex: 0, answer: "Secrets must remain on the server." }),
    lesson({ id: "nextjs-freshness", title: "Caching and data freshness", explanation: "Caching is a product decision. Some data can be reused, some may be briefly stale and revalidated, and some must be request-specific. Decide based on what the user needs, not habit.\n\nUse a time-based revalidation strategy for content that benefits from speed but changes periodically. Use fresh data for personalized or sensitive views. Revalidate affected paths or tags after mutations instead of refreshing unrelated data.", diagram: "Freshness requirement\n├── reuse → cached\n├── briefly stale → revalidate\n└── current per request → dynamic", code: `const products = await fetch("https://api.example.com/products", {\n  next: { revalidate: 60 },\n}).then((response) => response.json());`, takeaways: ["Freshness is a business requirement.", "Revalidation balances speed with updates."], mistakes: ["Caching every request identically.", "Refreshing the whole app after a small mutation."], question: "What should decide a cache strategy?", options: ["How fresh the product requires data to be", "The CSS framework", "The folder name", "The browser type"], correctIndex: 0, answer: "Choose caching based on allowed staleness and correctness." }),
    lesson({ id: "nextjs-request-time", title: "Dynamic data and request-time rendering", explanation: "A route needs request-time behavior when output depends on the current user, cookies, headers, search parameters, or data that cannot be stale. These request-specific inputs mean a static shared result would be wrong.\n\nUse server APIs deliberately and keep personalized data inside the server boundary.", diagram: "Request-specific input\n(cookies, headers, search params)\n          ↓\nDynamic server render\n          ↓\nPersonalized response", code: `import { cookies } from "next/headers";\n\nexport default async function Dashboard() {\n  const session = (await cookies()).get("session");\n  return <h1>{session ? "Your dashboard" : "Welcome"}</h1>;\n}`, takeaways: ["Personalized output needs request-specific rendering.", "Cookies and headers are server inputs."], mistakes: ["Serving one user's personalized result to every visitor.", "Reading server request APIs in a Client Component."], question: "Which input often requires request-time rendering?", options: ["A user session cookie", "A static logo", "A CSS class", "A TypeScript interface"], correctIndex: 0, answer: "Sessions are request-specific." }),
    lesson({ id: "nextjs-parallel-data", title: "Parallel data fetching", explanation: "Start independent requests together with `Promise.all`. It avoids a waterfall where one request waits unnecessarily for another. Keep the requests separate when they can succeed or fail independently, and use appropriate error handling when one failure should not block the rest.\n\nOnly use parallel fetching when no request needs a result from another request.", diagram: "Start users ─┐\nStart projects ├→ Promise.all → render\nStart alerts ─┘", code: `const [users, projects, alerts] = await Promise.all([\n  getUsers(),\n  getProjects(),\n  getAlerts(),\n]);`, takeaways: ["Independent requests should start together.", "Parallel fetching reduces avoidable waiting."], mistakes: ["Awaiting independent data sources one after another.", "Using Promise.all when later work depends on the first result."], question: "When should requests use `Promise.all`?", options: ["When they are independent", "When each needs the previous result", "When they run in CSS", "Only in Client Components"], correctIndex: 0, answer: "Independent work can run at the same time." }),
    lesson({ id: "nextjs-sequential-data", title: "Sequential data and dependency chains", explanation: "Some requests are genuinely sequential. For example, fetch a project first, then use its organization ID to fetch organization permissions. Keep this dependency explicit.\n\nDo not force dependent work into `Promise.all`; it would need values that do not exist yet. Once the dependency is resolved, start any remaining independent work in parallel.", diagram: "Fetch project\n    ↓ needs organizationId\nFetch organization permissions\n    ↓\nRender", code: `const project = await getProject(projectId);\nconst permissions = await getPermissions(project.organizationId);`, takeaways: ["Dependencies require sequence.", "After resolving a dependency, parallelize unrelated work."], mistakes: ["Treating every sequential fetch as a performance bug.", "Hiding dependencies inside deeply nested components."], question: "Why can project and project-permissions fetching be sequential?", options: ["Permissions may need the project's organization ID", "Promise.all cannot use fetch", "Server Components are synchronous", "URLs cannot have IDs"], correctIndex: 0, answer: "The second request depends on data returned by the first." }),
  ],
  finalQuiz: [{ question: "What avoids independent data-fetching waterfalls?", options: ["Promise.all", "usePathname", "redirect", "template.tsx"], correctIndex: 0, explanation: "Start independent promises together with `Promise.all`." }],
  project: { name: "Data-Driven Dashboard", goal: "Build a server-first dashboard that fetches several sources efficiently.", brief: "Render users, projects, and alerts from server data with intentional freshness and clear failure handling.", steps: ["Create focused server data functions.", "Load independent dashboard data in parallel.", "Add one request-specific dashboard value.", "Use revalidation for data that can be briefly stale."], acceptance: ["Initial data loads on the server.", "No unnecessary sequential waterfall remains.", "Secrets stay outside client code."] },
  footer: "<b>Day 7 mental model:</b> fetch server data directly, decide how fresh it must be, parallelize independent work, and make real dependencies explicit.",
});
