import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

const lesson = (id: string, title: string, explanation: string, diagram: string, code: string, takeaways: string[], mistakes: string[], question: string, options: string[], correctIndex: number, answer: string) => ({ id, title, durationMinutes: 13, explanation, diagram, codeExample: { title: `${title} example`, code }, keyTakeaways: takeaways, commonMistakes: mistakes, quiz: [{ question, options, correctIndex, explanation: answer }] });

export const NEXTJS_DAY_9_LESSONS = normalizePastedLessonDay({
  day: 9, title: "Authentication, Authorization, Cookies & Protected Routes", totalMinutes: 85, difficulty: "Beginner",
  overview: "<b>Goal:</b> identify users safely, decide what they may access, use secure cookies and sessions, and protect pages, actions, and APIs on the server.",
  lessons: [
    lesson("nextjs-auth-basics", "Authentication versus authorization", "<b>Authentication</b> answers who the user is. <b>Authorization</b> answers what that authenticated user may do. Logging in does not automatically grant access to every project, admin page, or API action.\n\nAlways enforce authorization on the server where data and mutations are performed, not only by hiding buttons in the UI.", "Credentials → authentication → session\n                              ↓\n                       authorization → allowed / denied", `const user = await getCurrentUser();\nif (!user) redirect("/login");\nif (user.role !== "admin") throw new Error("Forbidden");`, ["Authentication and authorization are separate checks.", "Server-side authorization protects data and mutations."], ["Treating login as permission to access every resource.", "Checking roles only in the browser UI."], "What does authorization answer?", ["What a user is allowed to do", "Who the user is", "Which CSS file to load", "How to cache a page"], 0, "Authorization determines permitted actions and resources."),
    lesson("nextjs-auth-flow", "Authentication request flow and sessions", "A typical flow validates credentials, creates a session, stores a session identifier in a secure cookie, and validates that session on future requests. The server should load the current user from the session before rendering protected content or mutating data.\n\nDo not treat a client-provided user ID as proof of identity. Derive identity from a validated server session.", "Login → validate credentials → create session → secure cookie\nRequest → validate session → current user", `async function requireUser() {\n  const session = await getSessionFromCookie();\n  if (!session) redirect("/login");\n  return session.user;\n}`, ["Sessions connect a browser request to an authenticated user.", "Validate sessions on every protected server request."], ["Trusting a user ID sent from the client.", "Using expired or unvalidated session data."], "What should identify a protected request's user?", ["A validated server session", "A query string user ID", "A hidden form field", "A CSS class"], 0, "Server-validated sessions are the trusted identity source."),
    lesson("nextjs-cookies", "Cookies and secure cookie options", "Cookies can hold a session identifier that the browser sends with matching requests. Use `httpOnly` so browser JavaScript cannot read the cookie, `secure` in HTTPS production, `sameSite` to reduce cross-site request risk, and a narrow `path` where appropriate.\n\nCookies are not automatically secure. Their options and the server-side validation behind them matter.", "Server sets secure cookie\n        ↓\nBrowser sends matching request cookie\n        ↓\nServer validates session", `import { cookies } from "next/headers";\n\nconst store = await cookies();\nstore.set("session", token, {\n  httpOnly: true,\n  secure: process.env.NODE_ENV === "production",\n  sameSite: "lax",\n  path: "/",\n});`, ["HttpOnly blocks direct browser JavaScript access.", "Secure cookie settings support session safety."], ["Putting a session token in localStorage by default.", "Forgetting secure production cookie settings."], "What does HttpOnly prevent?", ["Browser JavaScript reading the cookie", "The server reading the cookie", "The cookie expiring", "HTTPS"], 0, "HttpOnly prevents direct JavaScript access in the browser."),
    lesson("nextjs-protection", "Protecting pages, roles, and proxy checks", "Protect Server Components and Route Handlers by validating the session and checking roles before loading protected data. A proxy or middleware-style layer can redirect obvious unauthenticated traffic early, but it is not the only authorization boundary.\n\nThe final server page, action, or handler must still verify access to the specific resource, especially for role-based and ownership rules.", "Request → proxy check (optional) → server session check → role / ownership check → data", `export default async function AdminPage() {\n  const user = await requireUser();\n  if (user.role !== "admin") redirect("/forbidden");\n  return <AdminDashboard />;\n}`, ["Protect the actual server data boundary.", "Use roles and ownership for fine-grained authorization."], ["Relying only on proxy checks.", "Assuming an admin UI flag is authorization."], "Where must final authorization be enforced?", ["The server page, action, or handler", "Only navigation UI", "Only middleware", "Only CSS"], 0, "The server endpoint that returns or changes data must enforce it."),
  ],
  finalQuiz: [{ question: "Which is the safest place to check project ownership?", options: ["Server code before returning or mutating project data", "Only in a hidden client button", "In localStorage", "In a route name"], correctIndex: 0, explanation: "Authorization belongs at the trusted server data boundary." }],
  project: { name: "Protected Admin Dashboard", goal: "Build a role-protected dashboard using server session checks.", brief: "Create login simulation, secure session cookie handling, protected pages, and role-based admin access.", steps: ["Create a login action and session cookie.", "Protect dashboard pages on the server.", "Add an admin-only route and ownership check.", "Add an early redirect layer if useful."], acceptance: ["Unauthenticated visitors are redirected.", "Unauthorized users cannot access data by changing URLs.", "Cookies use appropriate secure settings."] },
  footer: "<b>Day 9 mental model:</b> authenticate identity, validate the session on the server, then authorize the exact resource and action.",
});
