import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

const emptyCode = { title: "Code example", code: "" };

export const NEXTJS_PHASE_0_LESSONS = normalizePastedLessonDay({
  day: 0,
  label: "Phase 0",
  title: "Before You Start",
  overview: "<b>Not part of the 11-day course.</b> Next.js connects React, browsers, servers, HTTP, APIs, databases, and deployment. This phase removes the gaps that would make those connections confusing without becoming another full React course.",
  totalMinutes: 90,
  difficulty: "Beginner",
  lessons: [
    {
      id: "nextjs-phase-react",
      title: "React foundations you already need",
      durationMinutes: 15,
      explanation: "You should be comfortable building a normal React application without following a tutorial line by line. That includes components, JSX, props, `children`, component composition, conditional rendering, lists and keys, state, derived state, lifting state up, controlled and uncontrolled inputs, forms, event handling, and custom hooks.\n\n<b>Hooks</b> are especially important. Know why you would use `useState`, `useEffect`, `useRef`, `useMemo`, `useCallback`, and `useContext`. Understand Hook rules, dependency arrays, cleanup, referential equality, stale closures, state preservation, and component identity.\n\n`useEffect` synchronizes React with something outside React, such as a subscription, browser event, timer, or network request. It is not a general place for code that happens after a render.",
      diagram: "Props and state\n\nParent component\n      │ props\n      ▼\nChild component\n      │ state change\n      ▼\nReact re-renders UI",
      codeExample: { title: "Props and state", code: `function Counter({ initialCount = 0 }: { initialCount?: number }) {\n  const [count, setCount] = useState(initialCount);\n  return <button onClick={() => setCount(count + 1)}>{count}</button>;\n}` },
      keyTakeaways: ["Props are input. State is component-owned data that can change.", "Keep one source of truth. Derive values during render when possible.", "Use effects only to synchronize with external systems."],
      commonMistakes: ["Using `useEffect` for values that can be calculated during render.", "Using array indexes as keys when a stable identity exists.", "Duplicating the same state in multiple components."],
      quiz: [{ question: "What is `useEffect` primarily for?", options: ["Synchronizing with something outside React", "Replacing event handlers", "Defining props", "Rendering JSX"], correctIndex: 0, explanation: "Effects connect React to external systems such as subscriptions, timers, or browser APIs." }],
    },
    {
      id: "nextjs-phase-react19",
      title: "React 19 and the React Compiler",
      durationMinutes: 10,
      explanation: "Have basic awareness of `useActionState`, `useOptimistic`, `useTransition`, `useEffectEvent`, Actions, Form Actions, and Suspense. You do not need mastery yet. You should recognize what problem each feature solves.\n\nThe React Compiler can automatically optimize many memoization cases. Understand memoization, referential equality, why `useMemo`, `useCallback`, and `React.memo` existed, and why rendering and identity still matter. Do not blindly add or remove manual memoization without understanding the work it protects.",
      diagram: "useOptimistic\n      ↓\nShow expected UI\n      ↓\nSend server request\n      ↓\nReconcile with real result",
      codeExample: emptyCode,
      keyTakeaways: ["React 19 features solve common async and transition problems.", "The compiler helps with optimization but does not remove the need to understand rendering."],
      commonMistakes: ["Treating `useMemo` and `useCallback` as always required or always obsolete."],
      quiz: [{ question: "What is the right mental model for the React Compiler?", options: ["It automates many optimizations, but rendering behavior still matters", "It makes React hooks unnecessary", "It turns React into a server", "It removes all re-renders"], correctIndex: 0, explanation: "The compiler can optimize many cases, but developers still need to reason about component identity and rendering." }],
    },
    {
      id: "nextjs-phase-javascript",
      title: "Modern JavaScript and modules",
      durationMinutes: 15,
      explanation: "Be comfortable with `let`, `const`, scope, functions, arrow functions, closures, objects, arrays, destructuring, spread and rest syntax, optional chaining, nullish coalescing, and template literals. Know which array operations mutate values and which return new values.\n\nUse `map`, `filter`, `find`, `findIndex`, `some`, `every`, `reduce`, `includes`, and `sort` comfortably. Understand `import`, `export`, `export default`, named exports, re-exports, dynamic imports, module boundaries, relative imports, and path aliases.",
      diagram: "Module boundary\n\nexport value\n    │\n    ▼\nimport value\n    │\n    ▼\nReusable code",
      codeExample: { title: "Immutable array update", code: `const activeUsers = users\n  .filter((user) => user.active)\n  .map((user) => ({ ...user, label: user.name }));` },
      keyTakeaways: ["Closures explain how functions retain surrounding values.", "Modules define clear boundaries between files.", "Immutability helps React recognize changes."],
      commonMistakes: ["Mutating state arrays with `sort`, `push`, or direct property assignment.", "Confusing a default export with a named export."],
      quiz: [{ question: "Which array method commonly returns a new array for rendering a list?", options: ["map", "push", "sort", "pop"], correctIndex: 0, explanation: "`map` transforms each item into a new array, which is commonly rendered in React." }],
    },
    {
      id: "nextjs-phase-async",
      title: "Async JavaScript, the event loop, and Fetch",
      durationMinutes: 15,
      explanation: "Understand synchronous and asynchronous execution, Promises, `async`, `await`, error handling, chaining, and concurrency. `await` pauses only its async function. It does not block the entire JavaScript runtime.\n\nKnow when to use `Promise.all`, `Promise.allSettled`, `Promise.race`, and `Promise.any`. Independent requests should generally run in parallel, while dependent requests must run in sequence. At a high level, understand the call stack, runtime APIs, task queue, microtask queue, timers, and the event loop.\n\nUse Fetch with request and response objects, headers, bodies, JSON, HTTP errors, network errors, and `AbortController` cancellation.",
      diagram: "Call stack\n    │\n    ▼\nRuntime APIs ──► task / microtask queues\n                         │\n                         ▼\n                    Event loop",
      codeExample: { title: "Parallel requests with safe response handling", code: `const [userResponse, postsResponse] = await Promise.all([\n  fetch("/api/user"),\n  fetch("/api/posts"),\n]);\n\nif (!userResponse.ok || !postsResponse.ok) {\n  throw new Error("Failed to load dashboard");\n}` },
      keyTakeaways: ["Promises represent future results.", "Parallel independent requests avoid unnecessary waterfalls.", "Abort requests that are no longer useful, such as stale searches."],
      commonMistakes: ["Assuming `await` freezes the browser.", "Forgetting to check `response.ok`.", "Running independent requests sequentially."],
      quiz: [{ question: "Why use `Promise.all`?", options: ["To run independent promises concurrently", "To convert JSON to TypeScript", "To cancel every request", "To make code synchronous"], correctIndex: 0, explanation: "`Promise.all` waits for multiple independent promises together." }],
    },
    {
      id: "nextjs-phase-typescript",
      title: "TypeScript foundations",
      durationMinutes: 12,
      explanation: "Know strings, numbers, booleans, arrays, objects, tuples, `null`, `undefined`, interfaces, type aliases, optional properties, literal types, union types, and intersection types.\n\nUnderstand generics for reusable functions, API responses, components, hooks, and utilities. Know narrowing with `typeof`, `instanceof`, `in`, type guards, discriminated unions, nullable values, and `unknown`. Avoid `any` because it removes TypeScript's protection. Recognize `Partial`, `Required`, `Pick`, `Omit`, `Record`, `Readonly`, `ReturnType`, `Parameters`, and `Awaited`.",
      diagram: "Unknown data\n    │ validate / narrow\n    ▼\nSafe TypeScript value\n    │\n    ▼\nApplication UI",
      codeExample: { title: "A discriminated union", code: `type Result =\n  | { status: "success"; data: string }\n  | { status: "error"; message: string };\n\nfunction show(result: Result) {\n  return result.status === "success" ? result.data : result.message;\n}` },
      keyTakeaways: ["TypeScript describes code at development time, not untrusted API data at runtime.", "Narrow before using unknown data."],
      commonMistakes: ["Using `any` to silence a useful type error.", "Assuming a TypeScript type validates a server response."],
      quiz: [{ question: "What is a primary reason to avoid `any`?", options: ["It disables much of TypeScript's safety", "It makes code faster", "It only works on servers", "It is required for generics"], correctIndex: 0, explanation: "`any` opts out of type checking for that value." }],
    },
    {
      id: "nextjs-phase-web",
      title: "Browser, HTTP, cookies, and CORS",
      durationMinutes: 15,
      explanation: "Know the browser at a high level: HTML becomes the DOM, CSS participates in rendering, JavaScript handles behavior, and events bubble through the page. Browser code can use `window`, `document`, `localStorage`, and `sessionStorage`. Server code can access databases, private environment variables, server files, and server-only APIs.\n\nKnow HTTP requests and responses, methods, status codes, headers, cookies, the same-origin policy, and CORS. A request carries a method, URL, headers, cookies, and body. A response carries a status code, headers, cookies, and body. Learn that `401` is not authenticated while `403` is authenticated but forbidden.\n\nUnderstand `HttpOnly`, `Secure`, and `SameSite` cookies. CORS is primarily a browser security mechanism, not a general server-to-server restriction.",
      diagram: "Browser ── HTTP request ──► Server\nBrowser ◄─ HTTP response ── Server",
      codeExample: { title: "A cancellable request", code: `const controller = new AbortController();\n\nfetch("/api/search?q=nextjs", { signal: controller.signal });\n\n// Cancel when the search term changes or the page closes.\ncontroller.abort();` },
      keyTakeaways: ["Browser APIs do not exist on the server.", "Cookies can use security attributes that browser storage cannot.", "CORS controls browser cross-origin access."],
      commonMistakes: ["Putting authentication secrets in `localStorage` by default.", "Treating 401 and 403 as the same error.", "Thinking CORS blocks all server-to-server requests."],
      quiz: [{ question: "What does `HttpOnly` mean for a cookie?", options: ["Browser JavaScript cannot read it directly", "It never expires", "It is public", "It only works on localhost"], correctIndex: 0, explanation: "HttpOnly cookies are inaccessible to JavaScript in the browser." }],
    },
    {
      id: "nextjs-phase-server",
      title: "Auth, APIs, rendering, data, and tools",
      durationMinutes: 8,
      explanation: "Know authentication as <b>who are you?</b> and authorization as <b>what are you allowed to do?</b>. Recognize sessions, cookies, tokens, JWT, OAuth, roles, permissions, RBAC, and resource ownership.\n\nKnow REST resources, endpoints, pagination, filtering, sorting, search, and error responses. Understand CSR, SSR, static generation, and hydration. Know relational database basics: tables, rows, columns, keys, relationships, SQL, indexes, transactions, connection pooling, and N+1 queries.\n\nBe comfortable with Node.js, npm, `package.json`, Git, browser DevTools, environment files, and the fact that `NEXT_PUBLIC_*` values are public.",
      diagram: "React 19\n    ↓\nJavaScript / TypeScript\n    ↓\nBrowser + HTTP\n    ↓\nNode + APIs + database\n    ↓\nNext.js",
      codeExample: emptyCode,
      keyTakeaways: ["Next.js works across browser and server boundaries.", "Server-rendered HTML becomes interactive through hydration.", "Never expose secrets through `NEXT_PUBLIC_*` variables."],
      commonMistakes: ["Treating client and server code as the same environment.", "Thinking a REST API is only any endpoint that returns JSON."],
      quiz: [{ question: "What should `NEXT_PUBLIC_*` values be treated as?", options: ["Public", "Server-only secrets", "Database passwords", "Git configuration"], correctIndex: 0, explanation: "Next.js exposes these values to the browser bundle." }],
    },
  ],
  finalQuiz: [
    { question: "What is Phase 0 for?", options: ["Checking the foundations that make Next.js understandable", "Learning every Next.js API", "Publishing an app", "Replacing React"], correctIndex: 0, explanation: "Phase 0 is a readiness check, not another full course." },
    { question: "Where can `window` be used?", options: ["In browser code", "In every Server Component", "In a database query", "Only in CSS"], correctIndex: 0, explanation: "`window` is a browser API." },
  ],
  footer: "You are ready when the foundations stop being the thing you are learning. The course can then focus on becoming effective with Next.js.",
});
