import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

const noCode = { title: "Code example", code: "" };

export const NEXTJS_DAY_2_LESSONS = normalizePastedLessonDay({
  day: 2,
  title: "App Router Fundamentals",
  overview: "<b>Goal:</b> understand how Next.js maps the filesystem to URLs and how layouts and route segments create an application's UI hierarchy.",
  totalMinutes: 100,
  difficulty: "Beginner",
  lessons: [
    {
      id: "nextjs-file-system-routing",
      title: "File-system routing",
      durationMinutes: 10,
      explanation: "In the App Router, folders and special files inside `app/` describe routes. A folder is a <b>route segment</b>. A `page.tsx` file makes that segment visitable. The file path becomes the URL path.\n\nThis is a convention. You do not write a central route table for ordinary pages. Instead, the filesystem is the route tree.",
      diagram: "app/\n├── page.tsx          → /\n├── about/page.tsx    → /about\n└── blog/post/page.tsx → /blog/post",
      codeExample: { title: "A route page", code: `// app/about/page.tsx\nexport default function AboutPage() {\n  return <h1>About</h1>;\n}` },
      keyTakeaways: ["Folders create route segments.", "A segment becomes a page URL when it contains `page.tsx`.", "Nested folders create nested URLs."],
      commonMistakes: ["Expecting every folder to create a public URL without a special route file."],
      quiz: [{ question: "What URL does `app/team/page.tsx` create?", options: ["/team", "/app/team", "/team/page", "/pages/team"], correctIndex: 0, explanation: "The `app/` directory is the route root, so `team/page.tsx` becomes `/team`." }],
    },
    {
      id: "nextjs-page-and-index",
      title: "Pages, index routes, and nested routes",
      durationMinutes: 10,
      explanation: "`app/page.tsx` creates the index route, `/`. A page at `app/docs/page.tsx` creates `/docs`. A deeper page at `app/docs/getting-started/page.tsx` creates `/docs/getting-started`.\n\nA page is the route-specific content the user sees. It is not the same as a layout, which provides shared structure around that content.",
      diagram: "app/\n├── page.tsx                 → /\n└── docs/\n    ├── page.tsx             → /docs\n    └── getting-started/\n        └── page.tsx         → /docs/getting-started",
      codeExample: { title: "Nested route page", code: `// app/docs/getting-started/page.tsx\nexport default function GettingStartedPage() {\n  return <h1>Getting started</h1>;\n}` },
      keyTakeaways: ["`app/page.tsx` is the home route.", "A nested segment maps naturally to a nested URL."],
      commonMistakes: ["Confusing a folder with its nested `page.tsx` route file."],
      quiz: [{ question: "What makes `app/docs/` visitable at `/docs`?", options: ["A `page.tsx` inside it", "Its folder name alone", "A `layout.tsx` only", "A file in `public/`"], correctIndex: 0, explanation: "A `page.tsx` supplies the UI for that route." }],
    },
    {
      id: "nextjs-root-layout",
      title: "The root layout",
      durationMinutes: 10,
      explanation: "Every App Router project needs a root `app/layout.tsx`. It defines the outer HTML document and wraps every route. It is the right place for document-level UI and providers that are needed everywhere.\n\nA layout receives `children`, which is the active page or nested layout rendered inside it.",
      diagram: "Root layout\n├── <html>\n├── <body>\n│   └── children\n└── shared document structure",
      codeExample: { title: "Root layout", code: `export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}` },
      keyTakeaways: ["The root layout wraps every route.", "`children` is where nested route UI appears.", "The root layout owns the document shell."],
      commonMistakes: ["Trying to render a complete document in every individual page."],
      quiz: [{ question: "What does `children` represent in a layout?", options: ["The nested route content", "Only a page title", "A database connection", "Static assets"], correctIndex: 0, explanation: "Next.js renders the active child route into `children`." }],
    },
    {
      id: "nextjs-nested-layouts",
      title: "Nested and multiple layouts",
      durationMinutes: 12,
      explanation: "Layouts can be nested. A `layout.tsx` inside `app/dashboard/` wraps the dashboard page and all descendant routes such as settings. This lets each application area own its sidebar, header, or navigation without duplicating it in every page.\n\nLayouts persist across navigation within their segment. When users move between matching child routes, shared layout UI can remain mounted while only the active page changes.",
      diagram: "Root layout\n    │\nDashboard layout\n ┌──┴───────┐\nDashboard  Settings\n page       page",
      codeExample: { title: "Dashboard layout", code: `// app/dashboard/layout.tsx\nexport default function DashboardLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <div className="dashboard">\n      <aside>Navigation</aside>\n      <main>{children}</main>\n    </div>\n  );\n}` },
      keyTakeaways: ["Nested layouts create nested shared UI.", "Layouts are for structure shared across related routes.", "Pages are route-specific content."],
      commonMistakes: ["Using a layout as if it were a page.", "Repeating the same sidebar in every nested page."],
      quiz: [{ question: "What does a dashboard layout wrap?", options: ["The dashboard route and its nested routes", "Only the root page", "Every route outside dashboard", "Nothing until it has a `route.ts`"], correctIndex: 0, explanation: "A segment layout wraps its descendant route UI." }],
    },
    {
      id: "nextjs-route-groups",
      title: "Route groups",
      durationMinutes: 12,
      explanation: "A folder wrapped in parentheses, such as `(marketing)`, is a <b>route group</b>. It organizes routes without adding that name to the URL. Route groups help organize large apps, apply different layouts, and separate areas such as marketing, auth, and dashboard UI.\n\nFor example, `app/(marketing)/pricing/page.tsx` becomes `/pricing`, not `/(marketing)/pricing`.",
      diagram: "app/\n├── (marketing)/pricing/page.tsx → /pricing\n├── (auth)/login/page.tsx        → /login\n└── (dashboard)/dashboard/page.tsx → /dashboard",
      codeExample: noCode,
      keyTakeaways: ["Parentheses organize the route tree without appearing in URLs.", "Route groups can give separate application areas their own layouts."],
      commonMistakes: ["Putting `(marketing)` into a link URL.", "Using route groups as a substitute for `page.tsx`."],
      quiz: [{ question: "What URL does `app/(marketing)/pricing/page.tsx` create?", options: ["/pricing", "/(marketing)/pricing", "/marketing/pricing", "/app/pricing"], correctIndex: 0, explanation: "Route-group names are omitted from the URL." }],
    },
    {
      id: "nextjs-private-folders",
      title: "Private folders and component folders",
      durationMinutes: 8,
      explanation: "A folder beginning with an underscore, such as `_components` or `_lib`, is private to routing. It helps keep supporting code near the route that uses it without turning that folder into a route segment.\n\nUse this when a component, utility, or query belongs only to one feature area. Move it to a shared folder only when it is truly used across unrelated features.",
      diagram: "app/docs/\n├── page.tsx          → /docs\n├── _components/      → not a URL\n│   └── Sidebar.tsx\n└── _lib/             → not a URL",
      codeExample: { title: "Keep route-only UI close", code: `app/docs/\n├── page.tsx\n├── layout.tsx\n└── _components/\n    └── DocsSidebar.tsx` },
      keyTakeaways: ["Private folders are organizational tools.", "Route-only code can stay close to the route that uses it."],
      commonMistakes: ["Assuming `/_components` is a public route.", "Putting every component in one global folder before it is actually shared."],
      quiz: [{ question: "Why use `_components` inside a route?", options: ["To keep route-only UI organized without creating a URL", "To make a public /_components page", "To disable layouts", "To store environment variables"], correctIndex: 0, explanation: "Private folders do not become route segments." }],
    },
    {
      id: "nextjs-route-tree",
      title: "Building a route tree",
      durationMinutes: 10,
      explanation: "Plan a route tree before writing pages. The tree communicates URLs, ownership, shared layouts, and private supporting code. A documentation site might have a global layout, a docs layout with sidebar, nested concept pages, API reference pages, and private docs-only components.\n\nThe filesystem is not just storage. In the App Router, it expresses product structure.",
      diagram: "app/\n├── layout.tsx\n├── page.tsx\n└── docs/\n    ├── layout.tsx\n    ├── page.tsx\n    ├── concepts/routing/page.tsx\n    └── api/users/page.tsx",
      codeExample: noCode,
      keyTakeaways: ["A route tree maps product areas to URLs and layouts.", "Plan the shared boundaries before duplicating UI."],
      commonMistakes: ["Creating unrelated deep folders with no clear route or layout ownership."],
      quiz: [{ question: "What does the App Router filesystem represent besides URLs?", options: ["UI and layout hierarchy", "Only CSS rules", "Git branches", "Database schema"], correctIndex: 0, explanation: "The route tree also describes nested UI structure." }],
    },
    {
      id: "nextjs-special-files",
      title: "Special files awareness",
      durationMinutes: 8,
      explanation: "Recognize these special App Router files: `page.tsx`, `layout.tsx`, `loading.tsx`, `error.tsx`, `not-found.tsx`, `template.tsx`, `default.tsx`, and `route.ts`. You do not need to master them all today.\n\n`loading.tsx` provides loading UI for a route segment. `error.tsx` provides an error boundary for a segment. `not-found.tsx` provides the missing-page UI. You will use these deeply later alongside Server Components, streaming, and Route Handlers.",
      diagram: "Route segment\n├── page.tsx       route UI\n├── layout.tsx     shared UI\n├── loading.tsx    pending UI\n├── error.tsx      failure UI\n└── route.ts       HTTP endpoint",
      codeExample: { title: "Loading UI", code: `// app/dashboard/loading.tsx\nexport default function Loading() {\n  return <p>Loading dashboard…</p>;\n}` },
      keyTakeaways: ["Special filenames give Next.js behavior without manual wiring.", "Loading and error boundaries can live close to the route they protect."],
      commonMistakes: ["Expecting `loading.tsx` to replace all data-fetching knowledge.", "Treating `route.ts` as a page component."],
      quiz: [{ question: "Which file provides route-segment loading UI?", options: ["loading.tsx", "pending.tsx", "spinner.tsx", "route.ts"], correctIndex: 0, explanation: "Next.js recognizes `loading.tsx` as a loading boundary." }],
    },
  ],
  finalQuiz: [
    { question: "What does `app/about/page.tsx` create?", options: ["/about", "/app/about", "/about/page", "/pages/about"], correctIndex: 0, explanation: "The folder name becomes the segment and `page.tsx` supplies the route UI." },
    { question: "What is the difference between a page and a layout?", options: ["A page is route-specific UI; a layout is shared structure", "They are identical", "Layouts only hold database code", "Pages cannot be nested"], correctIndex: 0, explanation: "Layouts wrap pages and nested layouts with shared UI." },
    { question: "Can a route have multiple nested layouts?", options: ["Yes", "No", "Only with Pages Router", "Only in production"], correctIndex: 0, explanation: "Layouts can nest through the route tree." },
  ],
  project: {
    name: "Multi-page Documentation Site",
    goal: "Build a route tree that makes the URL and UI hierarchy obvious.",
    brief: "Create a documentation site with global and docs layouts. Focus on route structure, nested layouts, reusable route-only components, and readable URLs rather than advanced data loading.",
    steps: ["Create home, docs, getting-started, concepts, and API reference pages.", "Add a root layout with a header and footer.", "Add a docs layout with a sidebar.", "Use an `_components` folder for docs-only UI.", "Use route groups when they clarify separate application areas."],
    acceptance: ["Every required path resolves to the intended page.", "The docs layout wraps every docs child route.", "Route-group names do not appear in URLs.", "No private folder is accidentally reachable as a page."],
  },
  footer: "You now have the route-tree mental model. Later lessons will add navigation, Server Components, data fetching, and rendering behavior to this structure.",
});
