import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

const lesson = (id: string, title: string, explanation: string, diagram: string, code: string, takeaways: string[], mistakes: string[], question: string, options: string[], correctIndex: number, answer: string) => ({ id, title, durationMinutes: 11, explanation, diagram, codeExample: { title: `${title} example`, code }, keyTakeaways: takeaways, commonMistakes: mistakes, quiz: [{ question, options, correctIndex, explanation: answer }] });

export const NEXTJS_DAY_10_LESSONS = normalizePastedLessonDay({
  day: 10, title: "Route Handlers, REST APIs, HTTP & Backend Integration", totalMinutes: 85, difficulty: "Beginner",
  overview: "<b>Goal:</b> build Route Handlers that read requests, validate input, authenticate callers, return correct HTTP responses, and receive trusted webhooks.",
  lessons: [
    lesson("nextjs-route-handlers", "Route Handlers and HTTP methods", "A Route Handler is a server endpoint defined in `route.ts`. Export `GET`, `POST`, `PATCH`, `DELETE`, or another HTTP method. It is useful for public or external HTTP APIs, webhooks, mobile clients, and integrations.\n\nA Route Handler is not a page. It returns a `Response` or `NextResponse` rather than JSX.", "HTTP request → app/api/projects/route.ts → validate / work → HTTP response", `export async function GET() {\n  const projects = await getProjects();\n  return Response.json({ projects });\n}\n\nexport async function POST(request: Request) {\n  const body = await request.json();\n  return Response.json(body, { status: 201 });\n}`, ["Route Handlers are HTTP endpoints.", "Method exports map to HTTP methods."], ["Putting a page component in `route.ts`.", "Using a Server Action when an external HTTP client needs the endpoint."], "What does `route.ts` return?", ["An HTTP response", "A React page", "A CSS module", "A layout"], 0, "Route Handlers serve HTTP responses."),
    lesson("nextjs-request-response", "Reading requests and returning responses", "Read JSON with `request.json()`, query values from `new URL(request.url).searchParams`, and headers or cookies from the request context. Validate every client value before using it.\n\nReturn explicit status codes and a stable JSON shape. Use 201 for created resources, 400 or 422 for invalid input, 401 for missing authentication, 403 for forbidden access, 404 for missing resources, and 500 for unexpected server failures.", "Request body / query / headers\n          ↓\nValidate\n          ↓\nResponse JSON + status", `export async function GET(request: Request) {\n  const url = new URL(request.url);\n  const page = Number(url.searchParams.get("page") ?? "1");\n  return Response.json({ page, projects: await getProjects(page) });\n}`, ["HTTP status codes communicate the result.", "Request data is untrusted until validated."], ["Returning 200 for every failure.", "Assuming JSON has the correct shape without validation."], "Which status means a resource was created?", ["201", "200", "401", "500"], 0, "201 Created signals successful resource creation."),
    lesson("nextjs-handler-auth", "Authentication and REST-style APIs", "Route Handlers must authenticate and authorize before returning private data or applying mutations. A valid session identifies the caller; roles and ownership decide whether that caller may access the requested resource.\n\nA REST-style API uses resource URLs and methods consistently, such as `GET /api/projects`, `POST /api/projects`, `GET /api/projects/:id`, and `DELETE /api/projects/:id`.", "Client → authenticate → authorize resource → handler → response", `export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) {\n  const user = await requireUser();\n  const { id } = await params;\n  await deleteProjectIfOwner(id, user.id);\n  return new Response(null, { status: 204 });\n}`, ["Handlers need the same server auth checks as pages.", "Resources and HTTP methods create predictable APIs."], ["Trusting an ID from the URL without ownership checks.", "Using a Server Action as an external public API."], "What protects `DELETE /api/projects/:id`?", ["Authentication and resource authorization", "A hidden client button", "A Link", "Static generation"], 0, "The server must verify the caller may delete that resource."),
    lesson("nextjs-actions-webhooks", "Route Handlers versus Server Actions and webhooks", "Use a Server Action for a mutation initiated by your Next.js UI, usually through a form. Use a Route Handler when another system or client needs an HTTP endpoint.\n\nWebhooks are external services calling your endpoint. Verify their signature using the raw request body before trusting the event, then make webhook processing idempotent so retries do not duplicate work.", "Next.js form → Server Action\nExternal service → webhook Route Handler → signature check → process event", `export async function POST(request: Request) {\n  const rawBody = await request.text();\n  const signature = request.headers.get("x-signature");\n  if (!verifySignature(rawBody, signature)) {\n    return Response.json({ error: "Invalid signature" }, { status: 401 });\n  }\n  await processWebhook(rawBody);\n  return Response.json({ received: true });\n}`, ["Actions serve your app UI; handlers serve HTTP clients and integrations.", "Webhook signatures must be verified."], ["Parsing a webhook before signature verification when raw bytes are required.", "Processing retry events twice without idempotency."], "Which should receive an external payment-provider webhook?", ["A Route Handler", "A Server Action form", "A layout", "A Client Component"], 0, "External services call HTTP endpoints, so use a Route Handler."),
  ],
  finalQuiz: [{ question: "When should you choose a Route Handler over a Server Action?", options: ["When an external HTTP client or webhook needs the endpoint", "For every internal form", "For CSS changes", "To render a page"], correctIndex: 0, explanation: "Route Handlers are HTTP APIs; Server Actions suit application UI mutations." }],
  project: { name: "Next.js API Layer", goal: "Build a validated, authenticated REST-style API layer.", brief: "Create project endpoints, correct HTTP responses, session checks, ownership rules, and one verified webhook endpoint.", steps: ["Add GET and POST project handlers.", "Add dynamic project GET and DELETE handlers.", "Validate bodies and return correct status codes.", "Add session and ownership checks.", "Create a signature-verified webhook handler."], acceptance: ["External clients receive stable JSON and meaningful status codes.", "Private resources require server authorization.", "Invalid webhook signatures are rejected."] },
  footer: "<b>Day 10 mental model:</b> Route Handlers expose HTTP contracts; Server Actions handle app UI mutations; both validate and authorize on the server.",
});
