import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

type Input = { id: string; title: string; explanation: string; diagram: string; code: string; takeaways: string[]; mistakes: string[]; question: string; options: string[]; correctIndex: number; answer: string };
const lesson = (input: Input) => ({ id: input.id, title: input.title, durationMinutes: 7, explanation: input.explanation, diagram: input.diagram, codeExample: { title: `${input.title} example`, code: input.code }, keyTakeaways: input.takeaways, commonMistakes: input.mistakes, quiz: [{ question: input.question, options: input.options, correctIndex: input.correctIndex, explanation: input.answer }] });

export const NEXTJS_DAY_4_LESSONS = normalizePastedLessonDay({
  day: 4,
  title: "Dynamic Routes, Route Parameters & Navigation Patterns",
  overview: "<b>Goal:</b> connect dynamic route patterns, URL parameters, query strings, navigation APIs, and redirects into one practical mental model.",
  totalMinutes: 90,
  difficulty: "Beginner",
  lessons: [
    lesson({ id: "nextjs-static-dynamic", title: "Static routes versus dynamic routes", explanation: "A <b>static route</b> has a fixed URL such as `/about`, `/contact`, or `/pricing`. A <b>dynamic route</b> has a changing segment, such as `/projects/1`, `/projects/2`, and `/projects/3`.\n\nInstead of creating a folder for every project, use one bracket segment: `app/projects/[id]/page.tsx`. The segment is a placeholder that lets one page handle many URLs.", diagram: "Static\napp/about/page.tsx → /about\n\nDynamic\napp/projects/[id]/page.tsx\n        ├→ /projects/1\n        └→ /projects/2", code: `type Props = { params: Promise<{ id: string }> };\n\nexport default async function ProjectPage({ params }: Props) {\n  const { id } = await params;\n  return <h1>Project {id}</h1>;\n}`, takeaways: ["Static segments are fixed.", "Bracket segments capture changing path values.", "One dynamic route can serve thousands of resources."], mistakes: ["Creating one folder per resource ID.", "Assuming `[id]` must be a database ID instead of a useful parameter name."], question: "Why use `[id]` in a route folder?", options: ["To handle a changing URL segment", "To create a CSS module", "To hide a folder", "To redirect a request"], correctIndex: 0, answer: "A bracket segment captures a value from the URL path." }),
    lesson({ id: "nextjs-parameters", title: "Dynamic route parameters", explanation: "A dynamic segment supplies its captured value through `params`. In modern App Router pages, await the `params` promise before reading it. Parameters are strings, even when the URL looks numeric, so validate and convert them before using them in a database query.\n\n`[id]`, `[slug]`, `[projectId]`, and `[username]` behave the same way. Choose a name that tells readers what the route represents.", diagram: "/projects/100\n      ↓\n[id]\n      ↓\nparams.id = \"100\"", code: `const { id } = await params;\nconst projectId = Number(id);\n\nif (!Number.isInteger(projectId)) {\n  return <p>Invalid project id</p>;\n}`, takeaways: ["Parameters come from dynamic path segments.", "Route parameters are strings first.", "Validate parameters before trusting them."], mistakes: ["Assuming a parameter is always a number.", "Using a parameter name that does not match the route folder."], question: "Where does `params.slug` come from?", options: ["A `[slug]` route segment", "A search parameter", "A layout", "A cookie"], correctIndex: 0, answer: "A matching bracket segment captures the pathname value." }),
    lesson({ id: "nextjs-multiple-segments", title: "Multiple dynamic segments", explanation: "A route can capture more than one dynamic value. `app/organizations/[org]/projects/[project]/page.tsx` represents a project inside a specific organization. Each dynamic segment becomes a property on `params`.\n\nUse multiple segments when the URL structure reflects real resource ownership. It makes links readable and gives the server enough context to check authorization.", diagram: "/organizations/acme/projects/portal\n             │              │\n          params.org    params.project", code: `type Props = { params: Promise<{ org: string; project: string }> };\n\nexport default async function Page({ params }: Props) {\n  const { org, project } = await params;\n  return <h1>{org} / {project}</h1>;\n}`, takeaways: ["Each bracket folder captures one path segment.", "Nested parameters can express resource ownership."], mistakes: ["Using query strings for resource hierarchy that belongs in the path.", "Skipping authorization checks after reading an organization or project parameter."], question: "How many parameter values can a nested dynamic route capture?", options: ["One for each dynamic segment", "Only one", "None", "Only numeric values"], correctIndex: 0, answer: "Each bracket segment creates one matching parameter." }),
    lesson({ id: "nextjs-catch-all-patterns", title: "Catch-all and optional catch-all routes", explanation: "`[...slug]` captures one or more remaining path segments as an array. It is useful for documentation paths such as `/docs/react/hooks/use-state`. `[[...slug]]` is optional catch-all: it can also match the base route, such as `/docs`.\n\nUse the normal catch-all when at least one segment is required. Use optional catch-all only when the base route and nested paths should use the same page.", diagram: "/docs/react/hooks\n      ↓\n[...slug]\n      ↓\n[\"react\", \"hooks\"]", code: `type Props = { params: Promise<{ slug?: string[] }> };\n\nexport default async function DocsPage({ params }: Props) {\n  const { slug = [] } = await params;\n  return <p>{slug.join(" / ") || "Documentation home"}</p>;\n}`, takeaways: ["Catch-all values are arrays.", "Optional catch-all can include the base route."], mistakes: ["Treating `slug` as a single string.", "Using an optional route when the base route should have different UI."], question: "Which route can match `/docs` and `/docs/react`?", options: ["[[...slug]]", "[slug]", "[...slug] only", "_slug"], correctIndex: 0, answer: "Optional catch-all makes the captured segment optional." }),
    lesson({ id: "nextjs-declarative-navigation", title: "Declarative navigation with Link", explanation: "Use `Link` from `next/link` for ordinary internal navigation. It is declarative: the link describes its destination in the rendered UI, and Next.js handles the transition. A normal external site should use a regular `<a>` element.\n\nUse a clear `href`, link text that describes the destination, and a normal link rather than a button when the user's intent is navigation.", diagram: "Link href=\"/projects\"\n       ↓\nNext.js Router\n       ↓\n/projects", code: `import Link from "next/link";\n\n<Link href="/projects">View projects</Link>\n\n<a href="https://github.com" target="_blank" rel="noreferrer">GitHub</a>`, takeaways: ["`Link` is the standard internal navigation API.", "External websites normally use `<a>`."], mistakes: ["Using `<a>` for every internal route.", "Using router calls for simple navigation links."], question: "Which API should link to `/projects` in normal page UI?", options: ["Link", "redirect", "router.refresh", "useSearchParams"], correctIndex: 0, answer: "`Link` is designed for normal internal navigation." }),
    lesson({ id: "nextjs-programmatic-navigation", title: "Programmatic navigation", explanation: "Use `useRouter` from `next/navigation` when code decides where to go after a user action, such as saving a form, creating a project, or completing onboarding. It must run in a Client Component because it responds to browser interaction.\n\nNormal navigation remains a `Link`. Programmatic navigation is for workflow decisions, not for replacing every anchor in the interface.", diagram: "User action\n    ↓\nuseRouter()\n    ↓\nrouter.push(\"/projects\")", code: `"use client";\nimport { useRouter } from "next/navigation";\n\nexport function CreateProjectButton() {\n  const router = useRouter();\n  return <button onClick={() => router.push("/projects")}>Create Project</button>;\n}`, takeaways: ["`useRouter` is a Client Component hook.", "Use it after an action changes the next destination."], mistakes: ["Importing from `next/router` in an App Router project.", "Using `useRouter` for a simple nav item."], question: "When is `useRouter` appropriate?", options: ["After a successful user action", "For every text link", "To define a server redirect", "To create a dynamic folder"], correctIndex: 0, answer: "Router methods are for action-based programmatic navigation." }),
    lesson({ id: "nextjs-history-refresh", title: "push, replace, back, forward, and refresh", explanation: "`push()` adds a history entry. `replace()` changes the current entry, which is useful after login or when a previous step should not remain reachable with Back. `back()` and `forward()` use browser history. `refresh()` requests fresh server-rendered output for the current route while preserving client state where possible.\n\nChoose the method based on the behavior a user should get from the browser's Back button and the data that changed.", diagram: "push: /home → /login → /dashboard\nreplace: /home → /dashboard\nback / forward: browser history\nrefresh: current route gets fresh server output", code: `router.push("/projects");\nrouter.replace("/dashboard");\nrouter.back();\nrouter.forward();\nrouter.refresh();`, takeaways: ["Push adds history; replace does not.", "Refresh updates server-rendered route output."], mistakes: ["Using replace for normal browsing.", "Calling refresh for every small client-only state change."], question: "Which method removes the current route from Back history?", options: ["replace", "push", "back", "refresh"], correctIndex: 0, answer: "`replace` overwrites the current browser history entry." }),
    lesson({ id: "nextjs-reading-url", title: "Reading the current URL", explanation: "`usePathname()` returns the current path, such as `/projects/100`, and is useful for active navigation. `useSearchParams()` reads query values after `?`, such as `?search=react&page=2`. Both are Client Component hooks.\n\nUse the path for resource identity and page location. Use query parameters for filters, pagination, sorting, and optional view state.", diagram: "/projects/100?tab=activity\n      │             │\nusePathname      useSearchParams\n/projects/100    tab=activity", code: `"use client";\nimport { usePathname, useSearchParams } from "next/navigation";\n\nconst pathname = usePathname();\nconst tab = useSearchParams().get("tab") ?? "overview";`, takeaways: ["Pathname excludes the query string.", "Search parameters can be absent and are strings."], mistakes: ["Expecting pathname to include `?page=2`.", "Using either hook in a Server Component."], question: "Which hook reads `?page=2`?", options: ["useSearchParams", "usePathname", "redirect", "Link"], correctIndex: 0, answer: "`useSearchParams` reads the query string." }),
    lesson({ id: "nextjs-url-construction", title: "Query parameters and safe URL construction", explanation: "When updating query strings, copy the current `URLSearchParams`, change only the values your control owns, and navigate to the result. This keeps filters, sorting, and pagination shareable through the URL without deleting unrelated options.\n\nUse `replace` for high-frequency updates such as a live search field when you do not want one Back-history item per keystroke.", diagram: "Current params\n    ↓\nCopy and change one value\n    ↓\nNew shareable URL", code: `const next = new URLSearchParams(params.toString());\nnext.set("page", String(page));\nrouter.push(\`/projects?\${next.toString()}\`);`, takeaways: ["Preserve existing parameters when changing one.", "URLs can represent filter and pagination state."], mistakes: ["Discarding another control's query values.", "Treating query input as trusted without validation."], question: "Why start from existing search parameters?", options: ["To preserve unrelated values", "To access a route parameter", "To create a layout", "To read cookies"], correctIndex: 0, answer: "Multiple controls can own different query values at once." }),
    lesson({ id: "nextjs-redirects", title: "Redirects and route protection", explanation: "Use `redirect()` from `next/navigation` when server-side logic decides the current route should not render. Common cases are an unauthenticated visitor, missing resource, insufficient permission, or invalid workflow state.\n\nA server redirect avoids rendering protected content and then moving the user from the browser after the fact.", diagram: "Request /dashboard\n      ↓\nCheck user\n  ┌───┴────┐\n user      no user\n  ↓          ↓\npage   redirect /login", code: `import { redirect } from "next/navigation";\n\nexport default async function DashboardPage() {\n  const user = await getCurrentUser();\n  if (!user) redirect("/login");\n  return <h1>Dashboard</h1>;\n}`, takeaways: ["Redirects can enforce server-side route decisions.", "Use them for auth, authorization, missing resources, and workflow state."], mistakes: ["Using client navigation when the server knows the user cannot view the route."], question: "What does `redirect()` do?", options: ["Stops the current route and sends the user elsewhere", "Adds a CSS class", "Reads a query value", "Creates a dynamic route"], correctIndex: 0, answer: "It performs a server-side navigation decision." }),
    lesson({ id: "nextjs-pattern-choice", title: "Choosing the correct navigation pattern", explanation: "Choose the narrowest tool for the job: normal internal link → `Link`; navigation after an action → `useRouter`; current pathname → `usePathname`; query values → `useSearchParams`; server decision → `redirect`; browser history → `back()` and `forward()`.\n\nThis keeps code easier to read because each API explains why navigation or URL access is happening.", diagram: "Normal link → Link\nAction → useRouter\nServer decision → redirect\nPath → usePathname\nQuery → useSearchParams\nHistory → back / forward", code: `<Link href="/about">About</Link>\nrouter.push("/dashboard");\nredirect("/login");`, takeaways: ["Navigation APIs have distinct responsibilities.", "Using the right tool improves accessibility and maintenance."], mistakes: ["Using `useRouter` everywhere.", "Using client navigation for a server-side access decision."], question: "Which tool should a server use for an unauthenticated dashboard request?", options: ["redirect", "Link", "useRouter", "usePathname"], correctIndex: 0, answer: "A server decision should use `redirect()`." }),
  ],
  finalQuiz: [
    { question: "What is the difference between a route parameter and a query parameter?", options: ["A route parameter is in the path; a query parameter follows ?", "They are identical", "Only query parameters are strings", "Only route parameters are URLs"], correctIndex: 0, explanation: "`/projects/123` has a path parameter while `/projects?page=2` has a query parameter." },
    { question: "Which navigation pattern is correct for a standard Projects menu item?", options: ["Link", "router.push inside a button", "redirect", "router.refresh"], correctIndex: 0, explanation: "A normal internal link should use `Link`." },
  ],
  project: {
    name: "Dynamic Documentation & Project Portal",
    goal: "Build a project portal that combines dynamic routes, docs paths, URL search, and protected navigation.",
    brief: "Extend the documentation site with a project list, dynamic project pages, catch-all docs, URL-backed search, action navigation, and a protected dashboard simulation.",
    steps: ["Create `/projects` and `app/projects/[id]/page.tsx`.", "Add `app/docs/[...slug]/page.tsx` for nested docs paths.", "Read `?search=react` with `useSearchParams`.", "Add Create Project using `router.push` and Back using `router.back`.", "Redirect a simulated unauthenticated `/dashboard` request to `/login`."],
    acceptance: ["Dynamic project and docs routes show their captured values.", "Query parameters are retained when controls change one value.", "The protected route redirects before rendering its content."],
  },
  footer: "<b>Day 4 mental model:</b> route parameters identify a resource in the path; search parameters describe a view; `Link` handles normal navigation; router methods follow client actions; `redirect()` handles server decisions.",
});
