import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

type Input = { id: string; title: string; explanation: string; diagram: string; code: string; takeaways: string[]; mistakes: string[]; question: string; options: string[]; correctIndex: number; answer: string };
const lesson = (input: Input) => ({ id: input.id, title: input.title, durationMinutes: 12, explanation: input.explanation, diagram: input.diagram, codeExample: { title: `${input.title} example`, code: input.code }, keyTakeaways: input.takeaways, commonMistakes: input.mistakes, quiz: [{ question: input.question, options: input.options, correctIndex: input.correctIndex, explanation: input.answer }] });

export const NEXTJS_DAY_5_LESSONS = normalizePastedLessonDay({
  day: 5,
  title: "Layouts, Templates, Loading & Error UI",
  overview: "<b>Goal:</b> build route-level shared UI and handle pending, missing, and failed states without duplicating page code.",
  totalMinutes: 80,
  difficulty: "Beginner",
  lessons: [
    lesson({ id: "nextjs-shared-layouts", title: "Shared and nested layouts", explanation: "A <b>layout</b> is UI that remains visible while users navigate between pages inside a route segment. Pages change while layouts remain mounted. The root layout is the outermost document shell, and a nested layout such as `app/dashboard/layout.tsx` wraps every route under `/dashboard`.\n\nUse layouts for shared navigation, sidebars, headers, providers, and other structure. `children` is the active page or nested layout that renders inside the shared shell.", diagram: "Root layout\n    ↓\nDashboard layout\n    ↓\nOverview / Users / Settings pages", code: `export default function DashboardLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <section>\n      <aside>Dashboard navigation</aside>\n      <main>{children}</main>\n    </section>\n  );\n}`, takeaways: ["`layout.tsx` creates shared UI.", "Layouts can nest by route segment.", "`children` is the nested route content."], mistakes: ["Putting dashboard-only UI in the root layout.", "Thinking a layout itself creates a URL."], question: "Where should a `/dashboard/*` sidebar live?", options: ["app/dashboard/layout.tsx", "app/layout.tsx only", "public/", "next.config.ts"], correctIndex: 0, answer: "A nested dashboard layout wraps only the dashboard route area." }),
    lesson({ id: "nextjs-templates", title: "Layout versus template", explanation: "Both `layout.tsx` and `template.tsx` wrap child routes. The difference is lifecycle: a layout persists across navigation inside its segment, while a template gets a fresh instance when navigating.\n\nUse a template when state, effects, animations, or analytics boundaries should reset between sibling pages. Use a layout for a persistent shell such as a dashboard sidebar.", diagram: "layout.tsx\n  persistent shell\n\ntemplate.tsx\n  fresh wrapper on navigation", code: `export default function Template({ children }: { children: React.ReactNode }) {\n  return <div className="page-transition">{children}</div>;\n}`, takeaways: ["Layouts persist; templates remount.", "Templates are for intentional resets between routes."], mistakes: ["Using a template when shared state should persist.", "Expecting layouts to reset local state on every navigation."], question: "Which wrapper remounts when navigating between child pages?", options: ["template.tsx", "layout.tsx", "page.tsx", "route.ts"], correctIndex: 0, answer: "Templates create a fresh wrapper instance for navigation." }),
    lesson({ id: "nextjs-loading-streaming", title: "Loading UI and streaming", explanation: "A route segment can include `loading.tsx` to show immediate pending UI while its page or nested Server Components are waiting. Next.js uses this boundary with Suspense so fast parts of the route can appear before slower content. This is called <b>streaming</b>.\n\nKeep loading UI close to the route it represents. A focused skeleton gives users useful feedback while the real content loads.", diagram: "Request route\n    ↓\nloading.tsx appears\n    ↓\nslow content resolves\n    ↓\npage content streams in", code: `// app/dashboard/loading.tsx\nexport default function Loading() {\n  return <div className="skeleton">Loading dashboard…</div>;\n}`, takeaways: ["`loading.tsx` is route-level pending UI.", "Streaming can show available UI before all data is ready."], mistakes: ["Using one generic spinner for every unrelated route.", "Assuming a loading file replaces proper data and error handling."], question: "What file supplies automatic route-segment loading UI?", options: ["loading.tsx", "pending.tsx", "spinner.tsx", "route.ts"], correctIndex: 0, answer: "Next.js recognizes `loading.tsx` as a loading boundary." }),
    lesson({ id: "nextjs-error-boundaries", title: "Error boundaries with error.tsx", explanation: "`error.tsx` handles failures inside a route segment and its children without necessarily crashing the whole application. It must be a Client Component because users need a retry interaction. Next.js passes an `error` and a `reset` function that retries the failed segment.\n\nPut error UI at the boundary where you can give the most useful recovery option. Use the root error handling strategy for failures that cannot be contained by a nested layout.", diagram: "Route segment\n    ↓\nError occurs\n    ↓\nerror.tsx\n    ↓\nShow recovery UI → reset()", code: `"use client";\n\nexport default function Error({ reset }: { error: Error; reset: () => void }) {\n  return (\n    <div>\n      <p>Something went wrong.</p>\n      <button onClick={() => reset()}>Try again</button>\n    </div>\n  );\n}`, takeaways: ["`error.tsx` creates a route-segment error boundary.", "It must be a Client Component.", "`reset()` retries the failed segment."], mistakes: ["Forgetting `'use client'`.", "Catching a failure without giving users a recovery path."], question: "Why is `error.tsx` a Client Component?", options: ["It needs interactive retry behavior", "It accesses the database", "It creates a route", "It is always static"], correctIndex: 0, answer: "The error UI can call `reset()` from a browser click." }),
    lesson({ id: "nextjs-not-found", title: "not-found.tsx and notFound", explanation: "Use `notFound()` when a requested resource does not exist or must not be shown. It stops the current route and renders the closest `not-found.tsx`. This is different from an unexpected error: missing content is an expected route outcome.\n\nUse it after a lookup returns no resource, and provide a route-specific missing state when that helps users recover.", diagram: "Dynamic page\n    ↓\nLookup resource\n ┌──┴─────┐\nfound      missing\n  ↓          ↓\npage      notFound() → not-found.tsx", code: `import { notFound } from "next/navigation";\n\nexport default async function ProductPage() {\n  const product = await getProduct();\n  if (!product) notFound();\n  return <h1>{product.name}</h1>;\n}`, takeaways: ["Use `notFound()` for missing route resources.", "`not-found.tsx` is distinct from `error.tsx`."], mistakes: ["Throwing a generic error for an ordinary missing record.", "Returning an empty page instead of a useful missing state."], question: "What should handle a missing product record?", options: ["notFound()", "router.refresh()", "usePathname()", "template.tsx"], correctIndex: 0, answer: "A missing resource should render the nearest not-found UI." }),
  ],
  finalQuiz: [
    { question: "What persists across child-route navigation?", options: ["A layout", "A template", "A page", "A loading file"], correctIndex: 0, explanation: "Layouts remain mounted while nested pages change." },
    { question: "Which file handles an expected missing resource?", options: ["not-found.tsx", "error.tsx", "loading.tsx", "template.tsx"], correctIndex: 0, explanation: "Missing content uses the not-found boundary." },
  ],
  project: { name: "Dashboard Shell", goal: "Create a resilient dashboard route area.", brief: "Build a nested dashboard layout with shared navigation, a template experiment, loading skeleton, recoverable error state, and a missing-resource page.", steps: ["Create `app/dashboard/layout.tsx` with sidebar and header.", "Add dashboard child pages for overview, users, and settings.", "Add `loading.tsx`, `error.tsx`, and `not-found.tsx`.", "Use `notFound()` for a simulated missing dashboard record."], acceptance: ["Dashboard navigation persists across dashboard child routes.", "Loading, error, and missing states render at the intended route boundary." ] },
  footer: "<b>Day 5 mental model:</b> layouts share structure, templates intentionally reset it, loading handles pending work, error handles unexpected failures, and not-found handles missing resources.",
});
