import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

type Input = { id: string; title: string; explanation: string; diagram: string; code: string; takeaways: string[]; mistakes: string[]; question: string; options: string[]; correctIndex: number; answer: string };
const lesson = (input: Input) => ({ id: input.id, title: input.title, durationMinutes: 13, explanation: input.explanation, diagram: input.diagram, codeExample: { title: `${input.title} example`, code: input.code }, keyTakeaways: input.takeaways, commonMistakes: input.mistakes, quiz: [{ question: input.question, options: input.options, correctIndex: input.correctIndex, explanation: input.answer }] });

export const NEXTJS_DAY_8_LESSONS = normalizePastedLessonDay({
  day: 8, title: "Forms, Server Actions & Mutations", totalMinutes: 80, difficulty: "Beginner",
  overview: "<b>Goal:</b> submit forms to server actions, validate input, show pending state, update affected UI, and redirect after a completed mutation.",
  lessons: [
    lesson({ id: "nextjs-forms", title: "Forms in Next.js", explanation: "Forms collect user input and submit an action. In Next.js, a form can call a Server Action directly through its `action` prop. This keeps the mutation near server-side validation and avoids creating a separate client API endpoint for every ordinary form.\n\nUse semantic inputs and labels. Treat every submitted value as untrusted until validated on the server.", diagram: "User input → form submit → Server Action → validate / mutate → response", code: `export default function ProjectForm() {\n  return (\n    <form action={createProject}>\n      <label htmlFor="name">Name</label>\n      <input id="name" name="name" required />\n      <button type="submit">Create project</button>\n    </form>\n  );\n}`, takeaways: ["Forms can call a Server Action through `action`.", "Use semantic, accessible form controls."], mistakes: ["Trusting browser validation as the only validation.", "Using a button click when a form submission is the real user intent."], question: "Where does a form's Server Action run?", options: ["On the server", "Only in the browser", "Inside CSS", "In public/"], correctIndex: 0, answer: "Server Actions run server-side." }),
    lesson({ id: "nextjs-server-actions", title: "Server Actions", explanation: "A Server Action is an async server function that can be invoked from a form or supported client interaction. Mark the function or module with `'use server'`. It is useful for mutations such as creating a project, updating a profile, or deleting a record.\n\nAuthenticate and authorize inside the action. A form reaching the action does not prove the user is allowed to make the change.", diagram: "Form action\n   ↓\n'use server' action\n   ↓\nAuth → validate → database mutation", code: `"use server";\n\nexport async function createProject(formData: FormData) {\n  const name = formData.get("name");\n  if (typeof name !== "string") throw new Error("Invalid name");\n  await db.project.create({ data: { name } });\n}`, takeaways: ["Server Actions handle server mutations.", "Actions still need auth, authorization, and validation."], mistakes: ["Treating a Server Action as a client-safe database function.", "Skipping authorization because the action came from a form."], question: "What directive marks a Server Action?", options: ["'use server'", "'use client'", "'use action'", "'use database'"], correctIndex: 0, answer: "`'use server'` marks server action code." }),
    lesson({ id: "nextjs-validation", title: "FormData and input validation", explanation: "Server Actions receive `FormData`. Read the values, check their types, and validate their shape before mutating data. Browser validation improves user experience, but server validation protects correctness and security.\n\nReturn or display clear field-level errors when possible. Do not let invalid input become a database error that users cannot understand.", diagram: "FormData\n  ↓\nRead values\n  ↓\nValidate\n ├── invalid → field error\n └── valid → mutation", code: `const rawName = formData.get("name");\nif (typeof rawName !== "string" || rawName.trim().length < 3) {\n  return { error: "Name must have at least 3 characters" };\n}\nawait createProjectRecord({ name: rawName.trim() });`, takeaways: ["FormData values require type checks.", "Validation must run on the server."], mistakes: ["Assuming all FormData values are strings.", "Using client validation as a security boundary."], question: "Why validate FormData on the server?", options: ["Client input can be changed or bypassed", "It makes CSS faster", "It creates routes", "It removes the need for forms"], correctIndex: 0, answer: "Server validation is the trusted validation boundary." }),
    lesson({ id: "nextjs-pending-ui", title: "Pending UI and form submission state", explanation: "Users need feedback while a mutation is running. Use React form state tools such as `useActionState` and `useFormStatus` in Client Component form controls to show pending status, disable duplicate submits, and render returned action state.\n\nKeep the Server Action responsible for the mutation and use a small client boundary only where the form needs interaction feedback.", diagram: "Submit\n  ↓\npending = true\n  ↓\nDisable button / show status\n  ↓\nAction settles → show result", code: `"use client";\nimport { useFormStatus } from "react-dom";\n\nexport function SubmitButton() {\n  const { pending } = useFormStatus();\n  return <button disabled={pending}>{pending ? "Creating…" : "Create project"}</button>;\n}`, takeaways: ["Pending UI prevents duplicate submission and gives feedback.", "Interactive form state belongs in a small Client Component."], mistakes: ["Letting users submit the same mutation repeatedly.", "Putting all form logic in client code just to show a spinner."], question: "What does pending form UI improve?", options: ["Feedback and duplicate-submit prevention", "Database indexing", "Route matching", "Static generation"], correctIndex: 0, answer: "Pending state tells users work is happening and prevents duplicate mutations." }),
    lesson({ id: "nextjs-mutation-ui", title: "Updating UI after a mutation", explanation: "After a mutation, update only the affected UI. Use revalidation to invalidate server-rendered data that changed, or return the needed action state for local feedback. The goal is that the screen reflects the new server truth without a broad unnecessary reload.\n\nChoose the smallest affected path or tag rather than invalidating unrelated dashboard data.", diagram: "Mutation succeeds\n    ↓\nRevalidate affected data\n    ↓\nServer UI reflects new truth", code: `"use server";\nimport { revalidatePath } from "next/cache";\n\nexport async function createProject(formData: FormData) {\n  await createProjectRecord({ name: String(formData.get("name")) });\n  revalidatePath("/projects");\n}`, takeaways: ["Mutations need a UI update strategy.", "Invalidate the smallest relevant server data scope."], mistakes: ["Refreshing every route after one small mutation.", "Showing success before the server mutation actually completes."], question: "What should revalidation target?", options: ["The affected path or data tag", "Every route", "Only the browser cache", "The root layout always"], correctIndex: 0, answer: "Target the data the mutation actually changed." }),
    lesson({ id: "nextjs-mutation-redirect", title: "Redirecting after mutations", explanation: "After a successful create, update, or workflow completion, a Server Action can call `redirect()` to send the user to the next route. Validate and persist first, then redirect. A redirect ends the action flow, so code after it should not be relied on.\n\nUse this for clear workflow transitions such as creating a project and moving to its details page.", diagram: "Submit create form\n    ↓\nValidate and persist\n    ↓\nredirect(/projects/id)\n    ↓\nNew route", code: `"use server";\nimport { redirect } from "next/navigation";\n\nexport async function createProject(formData: FormData) {\n  const project = await createProjectRecord({ name: String(formData.get("name")) });\n  redirect(\`/projects/\${project.id}\`);\n}`, takeaways: ["Redirect after a successful server mutation.", "Redirect ends the current server action flow."], mistakes: ["Redirecting before validation and persistence.", "Expecting code after redirect to run."], question: "When should a creation action redirect?", options: ["After successful validation and persistence", "Before reading form data", "Before authentication", "Instead of handling errors"], correctIndex: 0, answer: "The route should change only after the mutation succeeds." }),
  ],
  finalQuiz: [{ question: "Where must a mutation's validation happen?", options: ["On the server", "Only in browser HTML", "Only in CSS", "In a Link"], correctIndex: 0, explanation: "Server validation is the trusted boundary." }],
  project: { name: "Project Creation Flow", goal: "Create projects through a validated Server Action.", brief: "Build a new-project form with pending feedback, server validation, route revalidation, and a redirect to the created project.", steps: ["Create a semantic project form.", "Add a validated Server Action.", "Show pending state with a client submit button.", "Revalidate the project list and redirect to the new project."], acceptance: ["Invalid input returns useful feedback.", "Duplicate submissions are prevented while pending.", "The project list and detail route show server truth."] },
  footer: "<b>Day 8 mental model:</b> forms send untrusted input to the server; actions authenticate, validate, and mutate; focused UI state and revalidation show the result.",
});
