import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

type Input = { id: string; title: string; explanation: string; diagram: string; code: string; takeaways: string[]; mistakes: string[]; question: string; options: string[]; correctIndex: number; answer: string };
const lesson = (input: Input) => ({ id: input.id, title: input.title, durationMinutes: 13, explanation: input.explanation, diagram: input.diagram, codeExample: { title: `${input.title} example`, code: input.code }, keyTakeaways: input.takeaways, commonMistakes: input.mistakes, quiz: [{ question: input.question, options: input.options, correctIndex: input.correctIndex, explanation: input.answer }] });

export const NEXTJS_DAY_6_LESSONS = normalizePastedLessonDay({
  day: 6,
  title: "Server Components, Client Components & Data Fetching",
  overview: "<b>Goal:</b> choose the right side of the server-client boundary, pass data across it, fetch directly on the server, and reason about fresh versus cached data.",
  totalMinutes: 85,
  difficulty: "Beginner",
  lessons: [
    lesson({ id: "nextjs-server-client", title: "Server Components versus Client Components", explanation: "In the App Router, components are Server Components by default. They run on the server, can await data, access server-only resources, and do not send their implementation JavaScript to the browser. Client Components opt in when they need browser events, hooks, client state, or browser APIs.\n\nUse Server Components for data access and static UI. Use Client Components only at interactive leaves. This keeps secrets on the server and reduces client JavaScript.", diagram: "Server Component\nData, secrets, server APIs\n          │ props\n          ▼\nClient Component\nEvents, hooks, browser APIs", code: `// Server Component\nexport default async function Page() {\n  const products = await getProducts();\n  return <ProductList products={products} />;\n}\n\n// ProductList can be a Client Component if it needs interactions.`, takeaways: ["Server Components are the default.", "Client Components are for browser interactivity.", "Prefer a server parent with small interactive client leaves."], mistakes: ["Adding `'use client'` to an entire route by default.", "Trying to use browser APIs in a Server Component."], question: "Which component can safely read a private database credential?", options: ["Server Component", "Client Component", "A public Link", "CSS Module"], correctIndex: 0, answer: "Private resources belong in server-only code." }),
    lesson({ id: "nextjs-use-client", title: "The use client boundary", explanation: "`'use client'` at the top of a module marks a client boundary. That component and its imports become part of the client bundle, so keep the boundary low in the tree. A Client Component cannot import server-only code.\n\nServer Components can render Client Components and pass serializable props into them. This composition lets a server page fetch data while a small child handles interaction.", diagram: "Server page\n    ↓ renders\nClient boundary\n    ↓\nInteractive leaf", code: `"use client";\n\nimport { useState } from "react";\n\nexport function QuantityPicker() {\n  const [quantity, setQuantity] = useState(1);\n  return <button onClick={() => setQuantity(quantity + 1)}>{quantity}</button>;\n}`, takeaways: ["`'use client'` is a bundle boundary.", "Keep client boundaries as small as practical."], mistakes: ["Adding the directive to a layout just because one button is interactive.", "Importing a server-only database module into a Client Component."], question: "What does `'use client'` mark?", options: ["A client bundle boundary", "A database migration", "A route group", "A cache key"], correctIndex: 0, answer: "It opts that module into browser-side Client Component behavior." }),
    lesson({ id: "nextjs-pass-data", title: "Passing data across the boundary", explanation: "The common composition pattern is server fetch → serializable props → interactive client child. Pass plain values such as strings, numbers, arrays, and plain objects. Do not pass functions, database connections, class instances, or server-only objects across the boundary.\n\nKeep server data loading close to the server route and give the client child only the props it needs to render and interact.", diagram: "Server fetch\n    ↓\nSerializable props\n    ↓\nClient interaction", code: `// Server Component\nconst products = await getProducts();\nreturn <ProductFilters initialProducts={products} />;\n\n// Client Component\n"use client";\nexport function ProductFilters({ initialProducts }: { initialProducts: Product[] }) {\n  return <div>{initialProducts.length} products</div>;\n}`, takeaways: ["Server-to-client props must be serializable.", "Pass only the data the interactive component needs."], mistakes: ["Passing a server action or database client as ordinary client props.", "Fetching the same server data again in a client effect without a reason."], question: "What can a Server Component pass safely to a Client Component?", options: ["A plain array of product data", "A database connection", "A file-system handle", "A server-only environment object"], correctIndex: 0, answer: "Props crossing the boundary must be serializable data." }),
    lesson({ id: "nextjs-server-fetch", title: "Fetching data in Server Components", explanation: "Server Components can be async functions, so fetch data directly with `await` instead of using a client `useEffect` just to load the initial page. Handle unsuccessful responses and decide whether a failure is an error, a missing resource, or an empty state.\n\nFetching on the server keeps credentials private and lets the route render meaningful HTML before it reaches the browser.", diagram: "Request\n  ↓\nServer Component awaits data\n  ↓\nRender HTML / RSC payload\n  ↓\nBrowser receives UI", code: `export default async function ProductsPage() {\n  const response = await fetch("https://api.example.com/products");\n  if (!response.ok) throw new Error("Could not load products");\n  const products = await response.json();\n  return <ProductGrid products={products} />;\n}`, takeaways: ["Server Components can await data directly.", "Server fetching keeps secrets out of the browser."], mistakes: ["Using client effects for every initial data load.", "Skipping error checks on Fetch responses."], question: "Where can a Server Component await initial data?", options: ["Directly in the component", "Only inside useEffect", "Only in an event handler", "Only in middleware"], correctIndex: 0, answer: "Server Components can be async and await data while rendering." }),
    lesson({ id: "nextjs-fresh-data", title: "Caching, revalidation, and fresh data", explanation: "Data can be reused or refreshed based on the route's needs. Use the current Next.js caching APIs and conventions to decide whether data may be reused, revalidated after a period, or must be fresh for every request.\n\nThink from product requirements first: a marketing page can tolerate stale content, while a user dashboard or checkout often needs request-specific data. Revalidate deliberately after mutations rather than refreshing everything blindly.", diagram: "Data requirement\n ├── can be reused → cached\n ├── can be briefly stale → revalidate\n └── must be current → request-specific", code: `const products = await fetch("https://api.example.com/products", {\n  next: { revalidate: 60 },\n}).then((response) => response.json());`, takeaways: ["Caching is a product freshness decision.", "Revalidation balances speed and freshness."], mistakes: ["Assuming every server fetch should always be cached or never cached.", "Refreshing unrelated route data after a mutation."], question: "What should decide a data freshness strategy?", options: ["The product's freshness requirement", "The file name", "Whether the UI uses Tailwind", "The browser theme"], correctIndex: 0, answer: "Choose caching based on how stale the data is allowed to be." }),
    lesson({ id: "nextjs-component-decision", title: "Server or Client decision process", explanation: "Ask these questions in order: does this component need browser events, client state, effects, `window`, or `localStorage`? If yes, it needs a Client Component boundary. Does it need a database, secret, server-only package, or direct async data fetch? Keep it on the server.\n\nMost routes should be server-first. Add Client Components only to the interactive parts, such as a quantity picker, dialog, filter controls, or form fields.", diagram: "Needs events / hooks / browser API? → Client\nNeeds DB / secrets / direct data fetch? → Server\nOtherwise → Server by default", code: `// Good split\nexport default async function ProductPage() {\n  const product = await getProduct();\n  return <><ProductDetails product={product} /><AddToCart productId={product.id} /></>;\n}\n\n// AddToCart is the small Client Component leaf.`, takeaways: ["Start on the server and opt into client code only for interaction.", "Component boundaries are architecture and bundle-size decisions."], mistakes: ["Turning an entire page client-side because one child needs state.", "Putting secrets in props sent to a Client Component."], question: "What is the default choice for a component that needs neither browser APIs nor events?", options: ["Server Component", "Client Component", "Template", "Route Handler"], correctIndex: 0, answer: "App Router components are Server Components by default." }),
  ],
  finalQuiz: [
    { question: "What is the default component type in the App Router?", options: ["Server Component", "Client Component", "Route Handler", "Template"], correctIndex: 0, explanation: "Components are server-rendered by default until a client boundary is added." },
    { question: "Which UI part should usually be a Client Component?", options: ["An interactive quantity picker", "A database query", "A server secret", "A static product title"], correctIndex: 0, explanation: "Interactive state and event handlers need browser-side code." },
  ],
  project: { name: "Interactive Product Dashboard", goal: "Build a server-first product dashboard with small client interaction islands.", brief: "Fetch product data on the server, render product details as server UI, and add client-side filters, quantity controls, or a small interactive cart control.", steps: ["Fetch and render products in a Server Component.", "Pass serializable data to a Client Component filter.", "Add an interactive quantity or cart control.", "Choose and explain a refresh or revalidation strategy."], acceptance: ["No secrets or database code enter the client bundle.", "Interactive UI is isolated to Client Component leaves.", "The page handles loading, missing, and failed data appropriately." ] },
  footer: "<b>Day 6 mental model:</b> server components load data and protect server resources; client components handle browser interaction; a small, deliberate boundary connects them.",
});
