import type { LessonDay } from "@/lib/learn/lesson-types";

export const NEXTJS_DAY_35: LessonDay = {
  day: 35,
  title: "Production Scalability",
  overview: "Learn how a Next.js application grows from one server into a reliable multi-instance system. You will connect stateless servers, load balancing, CDN delivery, shared caching, PostgreSQL pooling, Redis, queues, and rate limits into one production architecture.",
  totalMinutes: 90,
  difficulty: "Advanced",
  lessons: [
    {
      id: "nextjs-35-1", title: "Stateless servers and horizontal scaling", durationMinutes: 18,
      explanation: "<b>Stateless means any Next.js instance can serve any request.</b> Do not keep sessions, uploaded files, or important job state only in one server's memory. Store shared state in durable services instead. This lets you add more instances when traffic grows and remove unhealthy instances safely.\n\n<b>Horizontal scaling</b> means running more copies of the same application. It helps only when each copy can work independently and shared dependencies, especially the database, can handle the extra traffic.",
      diagram: "Browser request\n  │\n  ▼\nLoad balancer\n  │\n  ├──► Next.js instance A\n  ├──► Next.js instance B\n  └──► Next.js instance C\n              │\n              ▼\n     Shared state outside instances",
      codeExample: { title: "Keep request state external", code: "// app/lib/session.ts\nimport { cookies } from \"next/headers\";\n\nexport async function getSessionId() {\n  return (await cookies()).get(\"session\")?.value;\n}\n\n// Store session data in a shared database or session store,\n// not in a module-level JavaScript variable." },
      keyTakeaways: ["Any instance should be able to serve the next request.", "Horizontal scaling needs shared state outside the application process."], commonMistakes: ["Keeping sessions only in memory.", "Adding instances without checking database capacity."], quiz: [], rawMiniQuiz: "<b>Why is in-memory session storage unsafe with multiple servers?</b>\nThe next request may reach a different server that does not have that memory." },
    {
      id: "nextjs-35-2", title: "CDN, load balancing, and request protection", durationMinutes: 18,
      explanation: "<b>A CDN serves cacheable assets close to users.</b> It can reduce work before a request reaches Next.js. A load balancer then distributes remaining requests across healthy application instances. Rate limiting protects expensive routes from abuse and prevents one client from consuming capacity needed by everyone else.\n\nDo not cache personalized HTML publicly. A route that reads request-specific data must stay private, while static assets and public pages are good CDN candidates.",
      diagram: "User\n  │\n  ▼\nCDN\n  │ cache miss\n  ▼\nRate limit\n  │\n  ▼\nLoad balancer\n  │\n  ├──► Next.js A\n  └──► Next.js B",
      codeExample: { title: "A simple route rate-limit boundary", code: "import { NextResponse } from \"next/server\";\n\nexport async function POST() {\n  const allowed = await rateLimit(\"create-order\");\n  if (!allowed) return NextResponse.json({ error: \"Too many requests\" }, { status: 429 });\n\n  return NextResponse.json({ ok: true });\n}" },
      keyTakeaways: ["CDNs remove repeat work for public content.", "Load balancers distribute dynamic work.", "Rate limiting protects limited resources."], commonMistakes: ["Publicly caching user-specific pages.", "Rate limiting only after expensive database work."], quiz: [], rawMiniQuiz: "<b>Where should a rate limit run?</b>\nAs early as practical, before expensive downstream work." },
    {
      id: "nextjs-35-3", title: "Shared cache and Redis", durationMinutes: 18,
      explanation: "<b>Redis is often used for short-lived shared data.</b> Common uses include rate-limit counters, cached API results, queues, and distributed locks. Redis is fast, but it is not automatically the source of truth for every type of data. PostgreSQL remains the durable source for business records.\n\nWith multiple Next.js instances, a process-local cache is different on every instance. Use a shared cache strategy when cached values or invalidation must stay consistent across servers.",
      diagram: "Next.js A ─┐\nNext.js B ─┼──► Redis / shared cache\nNext.js C ─┘             │\n                           ▼\n                      PostgreSQL source of truth",
      codeExample: { title: "Cache public product data", code: "export async function getProduct(id: string) {\n  const cached = await redis.get(`product:${id}`);\n  if (cached) return JSON.parse(cached);\n\n  const product = await db.product.findUniqueOrThrow({ where: { id } });\n  await redis.set(`product:${id}`, JSON.stringify(product), { EX: 60 });\n  return product;\n}" },
      keyTakeaways: ["Shared caches avoid repeated work across instances.", "Cache data can be stale, so define expiry and invalidation."], commonMistakes: ["Treating Redis as the only durable database.", "Caching without an expiration or invalidation plan."], quiz: [], rawMiniQuiz: "<b>Why use a shared cache in a multi-instance deployment?</b>\nEach application process has separate memory, so local caches are not coordinated." },
    {
      id: "nextjs-35-4", title: "PostgreSQL pooling and background jobs", durationMinutes: 18,
      explanation: "<b>Database connections are limited resources.</b> If every Next.js instance opens too many PostgreSQL connections, the database can become unavailable before CPU or memory is exhausted. Use the pooling strategy supported by your database provider or ORM, and keep queries efficient.\n\nSlow work such as email, reports, image processing, and imports should become background jobs. The web request stores the intent, places a job on a queue, and returns quickly. A worker handles the slow job separately and can retry failures.",
      diagram: "User action\n  │\n  ▼\nNext.js mutation\n  │\n  ├──► PostgreSQL transaction\n  │\n  └──► Queue\n          │\n          ▼\n        Worker\n          │\n          ▼\n       Email / report / media",
      codeExample: { title: "Queue slow work after a mutation", code: "export async function createInvoice(input: InvoiceInput) {\n  const invoice = await db.invoice.create({ data: input });\n  await jobs.add(\"send-invoice\", { invoiceId: invoice.id });\n  return invoice;\n}" },
      keyTakeaways: ["Pool and monitor database connections.", "Queues keep user-facing requests short and retryable."], commonMistakes: ["Generating a long report inside the request.", "Creating one database connection per request."], quiz: [], rawMiniQuiz: "<b>Why move email sending to a queue?</b>\nThe user receives a fast response and the worker can retry delivery safely." },
    {
      id: "nextjs-35-5", title: "Production scalability architecture", durationMinutes: 18,
      explanation: "<b>Scalability is a system design decision, not just adding servers.</b> Start with measurement: request rate, latency, errors, cache hit rate, queue depth, database pool use, and worker failures. Then scale the actual bottleneck.\n\nKeep the architecture simple until traffic proves you need more. A single Next.js server can be correct and useful. Add a CDN, shared cache, workers, and multiple instances when each solves a measured problem.",
      diagram: "              CDN\n               │\n               ▼\n        Load balancer\n          │       │\n          ▼       ▼\n       Next.js  Next.js\n          │       │\n          └──► Redis / Cache\n                    │\n                    ▼\n               PostgreSQL\n                    │\n                    ▼\n              Queue + workers",
      codeExample: { title: "Shared Next.js cache configuration", code: "// next.config.ts\nimport type { NextConfig } from \"next\";\n\nconst nextConfig: NextConfig = {\n  cacheHandlers: {\n    remote: require.resolve(\"./cache-handlers/remote.js\"),\n  },\n};\n\nexport default nextConfig;" },
      keyTakeaways: ["Scale the measured bottleneck.", "Multi-instance Next.js needs coordinated shared services.", "Observe the system after every scaling change."], commonMistakes: ["Adding Redis, queues, and replicas before they solve a real problem.", "Ignoring cache consistency during multi-instance deployments."], quiz: [], rawMiniQuiz: "<b>What should you measure after scaling?</b>\nLatency, errors, cache hits, queue depth, database pool pressure, and worker failures." },
  ],
  finalQuiz: [{ question: "Which component should hold durable business records?", options: ["PostgreSQL", "A load balancer", "A CDN", "One Next.js instance"], correctIndex: 0, explanation: "A relational database is the durable source of truth for business data." }],
  project: { name: "Scalable SaaS architecture", goal: "Design a resilient Next.js deployment for a growing SaaS app.", brief: "Separate fast web requests from shared state and slow work.", steps: ["Draw the request flow", "Choose shared state stores", "Move one slow action to a queue", "Define rate limits"], acceptance: ["The system can add a Next.js instance without losing sessions or cache coordination"] },
};
