import { normalizePastedLessonDay } from "@/lib/learn/normalize-pasted-lesson-day";

const noCode = { title: "Code example", code: "" };

export const NEXTJS_DAY_1_LESSONS = normalizePastedLessonDay({
  day: 1,
  title: "What Next.js Actually Is",
  overview: "<b>Goal:</b> understand what Next.js is, why it exists, how it differs from React, and how a Next.js application is structured and executed.",
  totalMinutes: 105,
  difficulty: "Beginner",
  lessons: [
    {
      id: "nextjs-what-it-is",
      title: "What Next.js is",
      durationMinutes: 10,
      explanation: "<b>Next.js is a React framework for building web applications.</b> React gives you the tools to build user interfaces. Next.js adds application-level features around React: routing, server and static rendering, Server Components, data fetching, backend endpoints, Server Actions, image and font optimization, metadata, caching, loading UI, error handling, production builds, and deployment support.\n\nNext.js does not replace React. It uses React as its UI foundation and adds the infrastructure needed to build and ship a complete web application.",
      diagram: "React\n  ↓\nBuild user interfaces\n\nNext.js\n  ↓\nBuild complete web applications with React",
      codeExample: { title: "A React component is still the UI building block", code: `export default function UserProfile() {\n  return (\n    <section>\n      <h1>Rajan</h1>\n      <p>Software Engineer</p>\n    </section>\n  );\n}` },
      keyTakeaways: ["Next.js is built on React.", "React handles UI. Next.js adds application infrastructure.", "You still use React components for every UI piece."],
      commonMistakes: ["Thinking Next.js is a React replacement.", "Thinking Next.js eliminates the need to understand React."],
      quiz: [{ question: "What is Next.js built on?", options: ["React", "Only HTML", "A database", "React Native"], correctIndex: 0, explanation: "Next.js is a framework built around React." }],
    },
    {
      id: "nextjs-react-vs-framework",
      title: "React versus Next.js",
      durationMinutes: 8,
      explanation: "React focuses on components, JSX, props, state, hooks, context, and rendering. On its own, React does not prescribe a complete architecture for routing, server rendering, SEO, image optimization, backend APIs, deployment, or authentication.\n\nNext.js makes those choices fit together through one framework. You can still choose supporting tools, but Next.js gives your application common conventions instead of making you wire unrelated libraries together first.",
      diagram: "React app from scratch\nReact + router + data library + SSR + SEO + backend\n\nNext.js\nReact + integrated routing, rendering, backend, optimization",
      codeExample: noCode,
      keyTakeaways: ["React is a UI library. Next.js is an application framework.", "Framework conventions reduce integration work."],
      commonMistakes: ["Calling a React app incomplete. React is useful on its own, but Next.js solves a different scope of problems."],
      quiz: [{ question: "Which concern does Next.js provide through built-in conventions?", options: ["File-system routing", "JavaScript syntax", "CSS color names", "Git commits"], correctIndex: 0, explanation: "Next.js uses files and folders to define routes." }],
    },
    {
      id: "nextjs-full-stack",
      title: "Full-stack React and two environments",
      durationMinutes: 10,
      explanation: "Next.js can run code in two environments. The <b>server</b> can access databases, private environment variables, server APIs, files, and server-only libraries. The <b>browser</b> handles user events, client state, the DOM, browser storage, and browser APIs.\n\nA Next.js app can include frontend UI, backend logic, API endpoints, and database access. This is why it is often called a full-stack React framework. The boundary matters: browser code cannot keep secrets, and server code cannot use `window` or `document`.",
      diagram: "Next.js application\n       │\n ┌─────┴─────┐\nServer      Browser\nDB, secrets  events, DOM\nAPIs         client state",
      codeExample: { title: "Keep a secret on the server", code: `// app/api/weather/route.ts\nexport async function GET() {\n  const key = process.env.WEATHER_API_KEY;\n  // The key stays on the server.\n  return Response.json({ configured: Boolean(key) });\n}` },
      keyTakeaways: ["Server and browser are different environments.", "Secrets and database access belong on the server.", "Interactive UI and browser APIs belong in client code."],
      commonMistakes: ["Putting database credentials in a client component.", "Using `window` in code that runs on the server."],
      quiz: [{ question: "Which environment can safely access a private database password?", options: ["The Next.js server", "The browser bundle", "A public `NEXT_PUBLIC_*` variable", "CSS"], correctIndex: 0, explanation: "Private secrets must stay in server-only code." }],
    },
    {
      id: "nextjs-app-router",
      title: "The App Router",
      durationMinutes: 8,
      explanation: "The modern Next.js routing system is the <b>App Router</b>. It uses the `app/` directory. Folders and special files create the route and UI hierarchy. App Router is more than URLs: it gives structure for layouts, loading states, error boundaries, not-found pages, Server Components, streaming, nested UI, route groups, parallel routes, and intercepting routes.\n\nFor now, remember the flow: filesystem → routing → UI hierarchy → rendering hierarchy.",
      diagram: "app/ filesystem\n      ↓\nRouting\n      ↓\nUI hierarchy\n      ↓\nRendering hierarchy",
      codeExample: { title: "A tiny App Router tree", code: `app/\n├── page.tsx          // /\n├── about/page.tsx    // /about\n└── contact/page.tsx  // /contact` },
      keyTakeaways: ["The App Router lives in `app/`.", "Folders and special files describe both routes and UI structure."],
      commonMistakes: ["Treating App Router as only a URL system. It also defines nested UI and rendering boundaries."],
      quiz: [{ question: "Which directory does the App Router use?", options: ["app/", "routes/", "screens/", "server/"], correctIndex: 0, explanation: "Modern Next.js App Router projects use the `app/` directory." }],
    },
    {
      id: "nextjs-create-project",
      title: "Creating a project with create-next-app",
      durationMinutes: 8,
      explanation: "Use `create-next-app` to create a project. Its questions choose the initial architecture: TypeScript, ESLint, Tailwind CSS, a `src/` directory, App Router, Turbopack, and import aliases. For this track, TypeScript, ESLint, and App Router are the sensible foundation.\n\nAfter creation, run the development server and open the local URL. Development mode prioritizes fast feedback and helpful errors rather than production optimization.",
      diagram: "create-next-app\n      ↓\nChoose project options\n      ↓\nGenerated application\n      ↓\nnpm run dev",
      codeExample: { title: "Create and run a project", code: `npx create-next-app@latest my-next-app\ncd my-next-app\nnpm run dev` },
      keyTakeaways: ["The CLI choices affect your initial project setup.", "Use development mode for fast local feedback."],
      commonMistakes: ["Choosing options blindly and not knowing what they configure."],
      quiz: [{ question: "Which command starts a standard local development server?", options: ["npm run dev", "npm run start", "npm run deploy", "next publish"], correctIndex: 0, explanation: "The `dev` script runs Next.js in development mode." }],
    },
    {
      id: "nextjs-project-structure",
      title: "Project structure and special files",
      durationMinutes: 14,
      explanation: "A typical project contains `app/`, `public/`, `package.json`, `tsconfig.json`, `eslint.config.mjs`, and `next.config.ts`. `app/` holds pages, layouts, loading UI, error UI, route handlers, and route segments.\n\n`page.tsx` defines the UI for a route. `layout.tsx` provides shared UI around pages. `public/` contains static assets served from the site root. `package.json` lists project metadata, dependencies, and scripts.",
      diagram: "my-next-app/\n├── app/\n│   ├── layout.tsx\n│   └── page.tsx\n├── public/\n├── package.json\n├── tsconfig.json\n└── next.config.ts",
      codeExample: { title: "A root layout", code: `export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <html lang="en">\n      <body>\n        <header>My Website</header>\n        {children}\n        <footer>© 2026</footer>\n      </body>\n    </html>\n  );\n}` },
      keyTakeaways: ["`app/page.tsx` is the home page.", "Layouts prevent shared UI from being copied across pages.", "A public asset such as `public/logo.png` is available as `/logo.png`."],
      commonMistakes: ["Putting route UI in `public/`.", "Duplicating a header and footer in every page instead of using a layout."],
      quiz: [{ question: "What does `app/about/page.tsx` represent?", options: ["The /about route", "A global layout", "A database migration", "A public asset"], correctIndex: 0, explanation: "A `page.tsx` inside `app/about/` creates the `/about` route." }],
    },
    {
      id: "nextjs-commands",
      title: "Development and production commands",
      durationMinutes: 8,
      explanation: "`next dev` starts the development server with Fast Refresh and development errors. `next build` compiles the application, optimizes assets, analyzes routes, and produces production output. `next start` runs a successful production build.\n\nThe production sequence is `npm run build` followed by `npm run start`. `next start` is not a replacement for building first.",
      diagram: "npm run dev → local development\n\nnpm run build\n      ↓\nProduction output\n      ↓\nnpm run start",
      codeExample: { title: "Production check", code: `npm run build\nnpm run start` },
      keyTakeaways: ["Development and production optimize for different goals.", "Run a production build before you call an app ready to ship."],
      commonMistakes: ["Running `next start` before building.", "Assuming development behavior always matches production."],
      quiz: [{ question: "What must normally happen before `npm run start`?", options: ["npm run build", "npm run dev", "git push", "npm install -g next"], correctIndex: 0, explanation: "`next start` serves the production output made by `next build`." }],
    },
    {
      id: "nextjs-configuration",
      title: "TypeScript, aliases, ESLint, config, and environment variables",
      durationMinutes: 12,
      explanation: "`tsconfig.json` configures TypeScript. A path alias such as `@/components/Button` avoids fragile `../../../` imports. ESLint catches likely mistakes and keeps code consistent. `next.config.ts` is for framework configuration such as remote image rules, redirects, headers, and experimental settings.\n\nEnvironment variables live in `.env*` files. Server-only values stay private. Variables beginning with `NEXT_PUBLIC_` are included in the browser bundle and must be treated as public.",
      diagram: "Environment variable\n       │\nNEXT_PUBLIC_*?\n  ┌────┴────┐\n yes       no\n  │         │\nBrowser   Server only",
      codeExample: { title: "A safe environment variable split", code: `// .env.local\nDATABASE_URL="postgres://private-value"\nNEXT_PUBLIC_APP_URL="https://example.com"\n\n// Server-only code\nconst databaseUrl = process.env.DATABASE_URL;` },
      keyTakeaways: ["Aliases make imports easier to read and move.", "Configuration belongs in the appropriate config file.", "Anything prefixed `NEXT_PUBLIC_` is public."],
      commonMistakes: ["Putting a secret in `NEXT_PUBLIC_*`.", "Editing generated TypeScript settings without understanding their effect."],
      quiz: [{ question: "Which variable can safely contain a database password?", options: ["DATABASE_URL", "NEXT_PUBLIC_DATABASE_URL", "NEXT_PUBLIC_SECRET", "PUBLIC_PASSWORD"], correctIndex: 0, explanation: "Only server-only variables can hold secrets." }],
    },
  ],
  finalQuiz: [
    { question: "Is Next.js a replacement for React?", options: ["No, it is built on React", "Yes, React cannot be used with it", "Only for mobile apps", "Only for databases"], correctIndex: 0, explanation: "Next.js uses React for its UI layer." },
    { question: "What is `layout.tsx` for?", options: ["Shared UI around pages", "Defining database tables", "Publishing static assets", "Making every component interactive"], correctIndex: 0, explanation: "Layouts wrap child pages with shared structure." },
    { question: "Why are `NEXT_PUBLIC_*` secrets unsafe?", options: ["They are sent to the browser", "They only work in production", "They disable TypeScript", "They are ignored by Next.js"], correctIndex: 0, explanation: "Those variables are bundled for client-side code." },
  ],
  project: {
    name: "Developer Portfolio",
    goal: "Create and understand a basic Next.js application without blindly following a tutorial.",
    brief: "Build the shell of a developer portfolio. Do not add advanced behavior yet. Practice the project structure, reusable components, layouts, TypeScript, development mode, and a production build.",
    steps: ["Create a project with TypeScript, ESLint, and App Router.", "Create Home, About, Projects, Skills, and Contact pages.", "Add reusable `Navbar`, `Footer`, `ProjectCard`, and `Section` components.", "Use the root layout for shared navigation and footer."],
    acceptance: ["Every page renders through the App Router.", "Shared UI comes from the layout and reusable components.", "`npm run build` completes successfully."],
  },
  footer: "Day 1 gives you the vocabulary and project structure. Day 2 explains how the route tree and layout tree work together.",
});
