export interface RabbitMQConcept {
  id: number;
  section: string;
  title: string;
  tagline: string;
  description: string;
  note?: string;
  diagram?: string;
  example: string;
  tip: string;
  tags: string[];
}

export const RABBITMQ_SECTIONS = [
  "Introduction",
  "Core Concepts",
  "Exchange Types",
  "Reliability",
  "Performance",
  "High Availability",
  "Patterns",
] as const;

export const RABBITMQ_CONCEPTS: RabbitMQConcept[] = [

  // ─────────────────────────────────────────────
  // INTRODUCTION
  // ─────────────────────────────────────────────
  {
    id: 1,
    section: "Introduction",
    title: "What is RabbitMQ?",
    tagline: "An open-source message broker that routes messages between services",
    description:
      "RabbitMQ is an open-source message broker. A message broker is a system that sits between services and handles message delivery — instead of Service A calling Service B directly, Service A sends a message to RabbitMQ, and RabbitMQ delivers it to Service B.\n\nThink of it like a postal system:\n• The sender (producer) drops a letter at the post office\n• The post office (RabbitMQ) sorts and holds the letter in a mailbox (queue)\n• The receiver (consumer) picks it up when they are ready\n\nThe sender does not need to know whether the receiver is currently online. The letter waits in the queue until it is collected.\n\n<b>Why not just call services directly?</b>\n\nWithout a broker, Service A calls Service B directly:\n\n`OrderService` → HTTP call → `EmailService`\n\nProblems with direct calls:\n• If `EmailService` is slow, `OrderService` is blocked and cannot continue\n• If `EmailService` crashes, the order flow fails too\n• `OrderService` must know `EmailService`'s exact address (tight coupling)\n\nRabbitMQ solves all three:\n• Async — `OrderService` publishes a message and returns immediately. No waiting.\n• Resilient — if `EmailService` is down, messages wait safely in the queue\n• Decoupled — `OrderService` only knows RabbitMQ's address, not `EmailService`'s\n\n<b>What is AMQP?</b>\n\nRabbitMQ speaks a protocol called AMQP (Advanced Message Queuing Protocol). Think of AMQP like HTTP — it is the standard language that producers, the broker, and consumers use to communicate. AMQP defines how to connect, publish, acknowledge messages, and handle errors.\n\n<b>The basic flow</b>\n\n1. Producer creates a message and publishes it to an exchange\n2. The exchange routes it to one or more queues based on rules\n3. The queue holds the message until a consumer picks it up\n4. Consumer processes the message and sends an acknowledgment\n5. RabbitMQ removes the message from the queue",
    note:
      "RabbitMQ vs other messaging tools:\n\n• Redis Streams — simple, fast, built into Redis. Good when you already use Redis for caching.\n• Amazon SQS — fully managed cloud queue. No setup needed for AWS apps.\n• Apache Kafka — built for very high throughput and event replay. Different use case.\n• RabbitMQ — best choice when you need complex routing, multiple exchange types, per-message acks, and flexible patterns.",
    diagram:
      "  WITHOUT BROKER (tight coupling)\n\n  OrderService ──── direct HTTP call ───► EmailService\n       │                                       │\n  (blocked if slow)              (if it crashes, order fails)\n\n  ──────────────────────────────────────────────────────────\n\n  WITH RABBITMQ (loose coupling)\n\n  OrderService ──publish──► [Exchange] ──► [Queue] ──► EmailService\n       │                                     │\n  (returns immediately)          (holds messages if EmailService is down)",
    example:
      "// Node.js — basic producer and consumer using amqplib\n\n// ── PRODUCER (publishes a message) ──────────────────────────────\nconst amqp = require('amqplib');\n\nasync function sendMessage() {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n\n  const queue   = 'order.emails';\n  const message = JSON.stringify({ orderId: 123, email: 'user@example.com' });\n\n  // Make sure the queue exists before publishing\n  await channel.assertQueue(queue, { durable: true });\n\n  channel.sendToQueue(queue, Buffer.from(message), { persistent: true });\n  console.log('Message sent:', message);\n\n  await channel.close();\n  await connection.close();\n}\n\nsendMessage();\n\n// ── CONSUMER (reads from the queue) ─────────────────────────────\nasync function receiveMessages() {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n  const queue      = 'order.emails';\n\n  await channel.assertQueue(queue, { durable: true });\n  channel.prefetch(1); // process one message at a time\n\n  console.log('Waiting for messages...');\n\n  channel.consume(queue, (msg) => {\n    if (!msg) return;\n    const data = JSON.parse(msg.content.toString());\n    console.log('Processing order:', data.orderId);\n    // ... send email ...\n    channel.ack(msg); // tell RabbitMQ: done successfully\n  });\n}\n\nreceiveMessages();",
    tip: "When asked about RabbitMQ in an interview, always lead with the problem it solves: 'Without a broker, a slow email service blocks checkout. With RabbitMQ, checkout publishes and returns immediately — email is decoupled and async.' Then walk through the flow: producer → exchange → queue → consumer.",
    tags: ["RabbitMQ", "Message Broker", "AMQP", "Producer", "Consumer", "Async", "Decoupling"],
  },

  // ─────────────────────────────────────────────
  // CORE CONCEPTS
  // ─────────────────────────────────────────────
  {
    id: 2,
    section: "Core Concepts",
    title: "Exchanges, Queues & Bindings",
    tagline: "The three building blocks of the RabbitMQ routing model",
    description:
      "RabbitMQ has three core concepts that work together to route messages. You must understand these three before anything else makes sense.\n\n<b>Exchange — The Router</b>\n\nA producer never sends a message directly to a queue. It always sends to an exchange first.\n\nThe exchange is a routing engine. It receives the message and decides which queue (or queues) should receive it, based on rules called bindings.\n\nThink of an exchange like an airport baggage sorter. Bags (messages) arrive at the sorter, and the sorter sends each bag to the correct conveyor belt (queue) based on the destination tag (routing key).\n\nIMPORTANT: exchanges do NOT store messages. If no queue is bound to receive a message, the message is silently discarded.\n\n<b>Queue — The Mailbox</b>\n\nA queue stores messages until a consumer is ready to process them. Queues deliver in FIFO order (first in, first out).\n\nWhen declaring a queue:\n• `durable: true` — queue definition survives RabbitMQ restart\n• `exclusive: true` — only one connection can use it; deleted on disconnect\n• `autoDelete: true` — deleted when the last consumer disconnects\n• `arguments` — extra options: message TTL, max length, dead letter exchange\n\n<b>Binding — The Rule</b>\n\nA binding connects an exchange to a queue. It says: 'messages matching this pattern go to this queue.'\n\nOne exchange can be bound to many queues. One queue can receive from many exchanges.\n\n<b>Routing Key — The Address Label</b>\n\nWhen publishing, the producer includes a routing key — a string like `order.created` or `payment.failed`. The exchange uses this key (plus its binding rules) to decide where to send the message.\n\n<b>Virtual Hosts (vhosts)</b>\n\nA vhost is an isolated namespace inside RabbitMQ. Different applications share one RabbitMQ server but each gets its own isolated set of exchanges, queues, users, and permissions. The default vhost is `/`.",
    note:
      "The complete flow in one line:\n\nProducer → Exchange → (binding matches routing key) → Queue → Consumer\n\nThe exchange routes but does NOT store. The queue stores but does NOT route. The binding is the rule connecting them.\n\nThe Default Exchange: every RabbitMQ server has a built-in exchange with empty name (`\"\"`). Every queue is automatically bound to it using the queue name as routing key. So publishing to `\"\"` with routing key `\"payments\"` goes directly to the queue named `payments`.",
    diagram:
      "  Producer\n     │\n     │  routing key: \"order.email\"\n     ▼\n  ┌─────────────────┐\n  │  Exchange        │  (routes, does NOT store)\n  │  \"orders\"        │\n  └────────┬────────┘\n           │\n    ┌──────┴───────┐\n    │              │\n    ▼              ▼\n  [email.queue]  [sms.queue]\n  binding key:  binding key:\n  order.email   order.sms\n    │              │\n    ▼              ▼\n  Email         SMS\n  Consumer      Consumer",
    example:
      "// Declare exchange, queues, and bindings using amqplib\n\nconst amqp = require('amqplib');\n\nasync function setup() {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n\n  // 1. Declare exchange\n  await channel.assertExchange('orders', 'direct', { durable: true });\n\n  // 2. Declare queues\n  await channel.assertQueue('email.queue', { durable: true });\n  await channel.assertQueue('sms.queue',   { durable: true });\n\n  // 3. Bind queues to exchange with routing keys\n  await channel.bindQueue('email.queue', 'orders', 'order.email');\n  await channel.bindQueue('sms.queue',   'orders', 'order.sms');\n\n  // 4. Publish — message goes to email.queue (routing key matches)\n  channel.publish('orders', 'order.email',\n    Buffer.from(JSON.stringify({ orderId: 99, to: 'user@example.com' }))\n  );\n\n  // 5. Publish — message goes to sms.queue (different routing key)\n  channel.publish('orders', 'order.sms',\n    Buffer.from(JSON.stringify({ orderId: 99, phone: '+1234567890' }))\n  );\n\n  console.log('Exchange, queues, bindings set up and messages sent.');\n  await channel.close();\n  await connection.close();\n}\n\nsetup();",
    tip: "Separate the three roles when explaining: 'Exchange routes, queue stores, binding is the rule. Producers publish to exchanges, consumers subscribe to queues — they never interact directly with each other.' This immediately shows you understand the AMQP model.",
    tags: ["Exchange", "Queue", "Binding", "Routing Key", "vhost", "AMQP", "assertExchange", "assertQueue"],
  },
  {
    id: 3,
    section: "Core Concepts",
    title: "Exchange Types",
    tagline: "Four strategies for routing messages: direct, fanout, topic, headers",
    description:
      "The exchange type controls how RabbitMQ matches routing keys to queues. There are four types, each solving a different routing problem.\n\n<b>1. Direct Exchange — Exact Match</b>\n\nRoutes to queues whose binding key exactly matches the message's routing key. Case-sensitive.\n\nExample: queue `email.service` bound with key `send_email`. Queue `sms.service` bound with key `send_sms`. Message with key `send_email` → only `email.service` gets it.\n\nUse when: you want to send to one specific destination.\n\n<b>2. Fanout Exchange — Broadcast</b>\n\nIgnores the routing key completely. Sends a copy to ALL queues bound to this exchange.\n\nExample: `user.events` exchange has 3 queues: `analytics`, `notifications`, `audit.log`. Every message → all 3 receive a copy.\n\nUse when: one event must reach many independent services.\n\n<b>3. Topic Exchange — Wildcard Routing</b>\n\nRoutes using dot-notation wildcard patterns on the routing key.\n\nTwo wildcards:\n• `*` matches exactly one word\n• `#` matches zero or more words\n\nExamples:\n• `order.*` matches `order.created` but NOT `order.payment.failed`\n• `order.#` matches `order.created` AND `order.payment.failed`\n• `*.failed` matches `payment.failed` and `auth.failed`\n\nUse when: you need flexible, hierarchical event routing. Most commonly used exchange type in production.\n\n<b>4. Headers Exchange — Attribute Match</b>\n\nIgnores routing key. Routes based on message header key-value pairs.\n\nBinding includes `x-match: all` (all headers must match) or `x-match: any` (any one header matches).\n\nUse when: routing depends on multiple metadata attributes, not just a string key.\n\n<b>Default Exchange</b>\n\nThe built-in exchange with empty name `\"\"`. Direct exchange. Every queue is auto-bound using its own name as the routing key. Useful for quick scripts without declaring an exchange explicitly.",
    note:
      "Quick rule:\n• Direct → one specific queue (exact key)\n• Fanout → all queues (broadcast)\n• Topic → flexible wildcard routing\n• Headers → route by message attributes\n\nIn real applications, Topic and Direct cover 90% of use cases. Start with Direct, upgrade to Topic when you need multi-level event categories.",
    diagram:
      "  DIRECT — exact match\n  Producer ──\"send_email\"──► [Direct Exchange] ──► email.queue only\n\n  FANOUT — broadcast\n  Producer ──────────────► [Fanout Exchange] ──► email.queue\n                                               ──► sms.queue\n                                               ──► analytics.queue\n\n  TOPIC — wildcards (* = 1 word, # = many words)\n  Producer ──\"order.created\"──► [Topic Exchange]\n                                   │\n               \"order.#\" binding ──►  all.orders.queue  (matches)\n             \"order.created\" binding ──► new.orders.queue (matches)\n               \"payment.#\" binding ──►  payments.queue   (no match)\n\n  HEADERS — metadata match\n  Producer ──[headers: format=pdf, type=report]──► [Headers Exchange]\n                                                       │\n            x-match:all, format=pdf, type=report ──►  pdf.reports.queue",
    example:
      "// Setup all four exchange types\n\nconst amqp = require('amqplib');\n\nasync function exchangeTypes() {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n\n  // ── Direct Exchange ─────────────────────────────────────────\n  await channel.assertExchange('logs.direct', 'direct', { durable: false });\n  await channel.assertQueue('error.queue');\n  await channel.bindQueue('error.queue', 'logs.direct', 'error');\n  channel.publish('logs.direct', 'error',\n    Buffer.from('Something broke!'));\n\n  // ── Fanout Exchange ─────────────────────────────────────────\n  await channel.assertExchange('user.events', 'fanout', { durable: false });\n  const q1 = (await channel.assertQueue('', { exclusive: true })).queue;\n  const q2 = (await channel.assertQueue('', { exclusive: true })).queue;\n  await channel.bindQueue(q1, 'user.events', ''); // routing key ignored\n  await channel.bindQueue(q2, 'user.events', '');\n  channel.publish('user.events', '', Buffer.from('user signed up'));\n  // Both q1 and q2 receive this message\n\n  // ── Topic Exchange ──────────────────────────────────────────\n  await channel.assertExchange('events', 'topic', { durable: false });\n  await channel.assertQueue('all.orders');\n  await channel.assertQueue('new.orders');\n  await channel.bindQueue('all.orders', 'events', 'order.#');    // all order events\n  await channel.bindQueue('new.orders', 'events', 'order.created'); // only created\n  channel.publish('events', 'order.created',\n    Buffer.from('New order placed'));  // both queues receive it\n  channel.publish('events', 'order.cancelled',\n    Buffer.from('Order cancelled'));   // only all.orders receives it\n\n  await channel.close();\n  await connection.close();\n}\n\nexchangeTypes();",
    tip: "Always match the exchange type to the routing need: 'I'd use a Topic exchange here because different consumers need different subsets of order events — the warehouse needs `order.placed`, the refund service needs `order.cancelled`, and the audit log needs `order.#` for everything.' This shows routing understanding, not just tool knowledge.",
    tags: ["Direct Exchange", "Fanout Exchange", "Topic Exchange", "Headers Exchange", "Wildcard", "Routing Key", "Broadcast"],
  },

  // ─────────────────────────────────────────────
  // RELIABILITY
  // ─────────────────────────────────────────────
  {
    id: 4,
    section: "Reliability",
    title: "Message Acknowledgments",
    tagline: "How RabbitMQ knows a message was successfully processed",
    description:
      "When RabbitMQ delivers a message to a consumer, it needs to know what happened to it. Was it processed successfully? Did it fail? Should it be retried? This is handled through acknowledgments (acks).\n\n<b>Auto-Acknowledgment — At-Most-Once</b>\n\nRabbitMQ removes the message from the queue the instant it is delivered to the consumer — before the consumer actually processes it.\n\n• Fastest option — no extra round-trip\n• Risk: if consumer crashes mid-processing, the message is permanently lost\n• RabbitMQ has no way to know processing failed\n\nUse only when losing messages is acceptable (e.g. analytics events).\n\n<b>Manual Acknowledgment — At-Least-Once</b>\n\nThe message stays in the queue as \"unacknowledged\" until the consumer explicitly sends a response.\n\nThree possible responses:\n\n`channel.ack(msg)` — \"I processed it. Remove it from the queue.\"\n`channel.nack(msg, false, true)` — \"I failed. Put it back in the queue for retry.\"\n`channel.nack(msg, false, false)` — \"I failed permanently. Send to Dead Letter Exchange.\"\n\n<b>What happens if the consumer crashes without acking?</b>\n\n1. RabbitMQ detects the TCP connection dropped\n2. All unacknowledged messages from that consumer go back in the queue\n3. Other consumers pick them up\n\nThis is redelivery — and it is what makes RabbitMQ fault-tolerant.\n\n<b>The Redelivered Flag</b>\n\nWhen a message is redelivered, RabbitMQ sets `msg.fields.redelivered = true`. Check this to detect and handle duplicates:\n\n`if (msg.fields.redelivered) { checkIfAlreadyProcessed(data.id); }`\n\n<b>Idempotent Consumers</b>\n\nBecause RabbitMQ can redeliver messages, your consumer must be idempotent — processing the same message twice produces the same result as once. Before doing the work, check if it was already done.",
    note:
      "Manual ack is the production standard.\n\nAt-most-once (auto-ack): fast, but possible loss.\nAt-least-once (manual ack): no data loss, but possible duplicate delivery on failure.\n\nFor true at-exactly-once: use manual ack + idempotent consumer + deduplication check (look up if work was already done before doing it).",
    diagram:
      "  MANUAL ACK FLOW\n\n  [Queue] ──deliver──► [Consumer]\n                           │\n                    processing...\n                           │\n             ┌─────────────┼─────────────┐\n             │             │             │\n        success          fail           crash\n             │             │             │\n       channel.ack()  channel.nack()   TCP drop\n             │         requeue=true     detected\n             ▼             │             │\n     message removed    back to      all unacked\n       from queue        queue       redelivered",
    example:
      "// Manual acknowledgment — the production standard\n\nconst amqp = require('amqplib');\n\nasync function consumer() {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n  const queue      = 'order.processing';\n\n  await channel.assertQueue(queue, { durable: true });\n  channel.prefetch(1); // process 1 at a time (important!)\n\n  channel.consume(queue, async (msg) => {\n    if (!msg) return;\n\n    const data = JSON.parse(msg.content.toString());\n    console.log('Received:', data.orderId);\n\n    // Handle redelivery — check for duplicate\n    if (msg.fields.redelivered) {\n      const alreadyDone = await checkIfProcessed(data.orderId);\n      if (alreadyDone) {\n        channel.ack(msg);  // already done, just ack and skip\n        return;\n      }\n    }\n\n    try {\n      await processOrder(data);\n      channel.ack(msg);  // success — remove from queue\n    } catch (err) {\n      console.error('Failed:', err.message);\n\n      const retryable = err.message !== 'PERMANENT_ERROR';\n      if (retryable) {\n        channel.nack(msg, false, true);  // requeue for retry\n      } else {\n        channel.nack(msg, false, false); // send to DLX\n      }\n    }\n  }, { noAck: false }); // noAck: false = manual ack mode\n}\n\nconsumer();",
    tip: "Always combine acks with idempotency: 'I use manual acks so no message is lost on consumer crash. Since RabbitMQ may redeliver, I also make consumers idempotent — before charging a card, check if that orderId was already charged in the database. If yes, just ack and skip.'",
    tags: ["basicAck", "basicNack", "Auto-Ack", "Manual Ack", "Redelivery", "Idempotent", "At-Least-Once", "noAck"],
  },
  {
    id: 5,
    section: "Reliability",
    title: "Message Durability & Publisher Confirms",
    tagline: "Making sure messages survive RabbitMQ restarts and network failures",
    description:
      "By default, RabbitMQ keeps everything in memory. If it restarts, all queues and messages are gone. For production systems, you need durability at three levels. Miss any one of them and messages can still be lost.\n\n<b>Level 1 — Durable Exchange</b>\n\nDeclare with `durable: true`.\n\nThe exchange definition is written to disk. After a restart, the exchange is automatically recreated. Without this, producers cannot publish until the exchange is manually re-declared.\n\n<b>Level 2 — Durable Queue</b>\n\nDeclare with `durable: true`.\n\nThe queue definition survives restart. The queue is recreated after reboot — but messages inside may still be lost without Level 3.\n\n<b>Level 3 — Persistent Messages</b>\n\nPublish with `{ persistent: true }` (sets `deliveryMode: 2`).\n\nRabbitMQ writes the message to disk before acknowledging. After restart, persisted messages are read from disk and restored to their queues.\n\n<b>All three must be set together</b>\n\n• Durable exchange only → exchange survives, messages do not\n• Durable queue only → queue survives, messages do not\n• Persistent message only → useless if the queue is not durable\n\nFor critical data — payments, orders — always set all three.\n\n<b>Publisher Confirms</b>\n\nBy default, RabbitMQ does not confirm whether it actually wrote the message to disk. Publisher Confirms close this gap:\n\n1. Enable confirm mode on the channel: `await channel.confirmSelect()`\n2. Publish the message\n3. RabbitMQ writes to disk and acks back to the producer\n4. The producer only considers it \"safe\" after receiving the ack\n\nWithout confirms: fire-and-forget. Fast, but possible silent loss.\nWith confirms: the producer knows the message is safe in the broker.\n\n<b>Performance note</b>\n\nDisk writes are slower than memory writes. Persistent messages have lower throughput than non-persistent. For high-volume, loss-tolerant data (analytics, logs), use non-persistent messages in durable queues. For critical data, accept the trade-off.",
    note:
      "For critical workflows, always combine all four:\n• Durable exchange\n• Durable queue\n• Persistent messages (`persistent: true`)\n• Publisher Confirms\n\nThis eliminates silent message loss both in transit and across restarts.",
    diagram:
      "  THREE LEVELS OF DURABILITY\n\n  Level 1: Durable Exchange\n  ┌─────────────────────────┐\n  │ Exchange (durable: true) │ ← survives restart\n  └─────────────────────────┘\n\n  Level 2: Durable Queue\n  ┌──────────────────────────┐\n  │ Queue (durable: true)    │ ← definition survives restart\n  └──────────────────────────┘\n\n  Level 3: Persistent Message\n  message.persistent = true   ← content written to disk\n\n  Publisher Confirms\n  Producer ──publish──► Broker ──disk write──► ack ──► Producer\n  (producer waits for ack before considering message safe)",
    example:
      "// Full durability setup — all three levels + publisher confirms\n\nconst amqp = require('amqplib');\n\nasync function durablePublisher() {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n\n  // Level 1: durable exchange\n  await channel.assertExchange('payments', 'direct', { durable: true });\n\n  // Level 2: durable queue\n  await channel.assertQueue('charge.jobs', { durable: true });\n  await channel.bindQueue('charge.jobs', 'payments', 'charge');\n\n  // Enable publisher confirms on this channel\n  await channel.confirmSelect();\n\n  // Level 3: persistent message + publisher confirm\n  const payload = Buffer.from(JSON.stringify({ orderId: 456, amount: 99.99 }));\n\n  channel.publish(\n    'payments',\n    'charge',\n    payload,\n    { persistent: true }  // deliveryMode: 2\n  );\n\n  // Wait for broker to confirm it was written to disk\n  await channel.waitForConfirms();\n  console.log('Message safely written to disk and queued.');\n\n  await channel.close();\n  await connection.close();\n}\n\ndurablePublisher();",
    tip: "Always mention all three levels together: 'I'd declare the exchange and queue as durable, set persistent: true on messages, and enable publisher confirms so the producer knows the message reached the broker safely. Missing any one of these three can cause silent data loss.'",
    tags: ["Durability", "Durable Queue", "Persistent Messages", "Publisher Confirms", "confirmSelect", "deliveryMode", "Reliability"],
  },
  {
    id: 6,
    section: "Reliability",
    title: "Dead Letter Exchanges & Retry Patterns",
    tagline: "Routing failed messages to a safe holding area instead of dropping them",
    description:
      "When a consumer fails to process a message, you have two bad options: retry forever (blocks the queue) or drop it (silent data loss). A Dead Letter Exchange (DLX) gives you a better third option — automatically route failed messages to a safe holding area.\n\n<b>What causes a message to die?</b>\n\nA message becomes dead (undeliverable) when:\n• Consumer sends `nack` with `requeue: false`\n• Message TTL (time-to-live) expires before being consumed\n• The queue hits its maximum length and must drop messages\n\n<b>Setting up a DLX</b>\n\nWhen declaring a queue, add arguments:\n• `x-dead-letter-exchange` — name of the DLX exchange to route dead messages to\n• `x-dead-letter-routing-key` — optional routing key to use on the DLX\n\nExample: queue `order.processing` with `x-dead-letter-exchange: \"orders.dlx\"`. When a message dies, it goes to `orders.dlx` automatically — landing in a dead letter queue for inspection.\n\n<b>Message TTL</b>\n\nTTL sets how long a message lives in a queue before dying.\n\nPer-message TTL: `{ expiration: \"30000\" }` (30 seconds, as a string in milliseconds)\nPer-queue TTL: `{ \"x-message-ttl\": 30000 }` in queue arguments\n\n<b>Automatic Retry with DLX + TTL</b>\n\nCombining DLX and TTL gives you delayed retry without any application timers:\n\n1. Consumer fails → `nack(msg, false, false)`\n2. Message goes to DLX\n3. DLX routes to a retry queue with TTL 30s and `x-dead-letter-exchange` pointing back to the original\n4. After 30 seconds, TTL expires → message goes back to the original processing queue\n5. Consumer tries again\n\n<b>Limiting retry count</b>\n\nAdd an `x-retry-count` header to track how many times a message has been retried. When it exceeds the maximum (e.g. 5 tries), route to a permanent dead letter queue for manual inspection instead of retrying again.",
    note:
      "DLX is essential for production. Without it:\n• `nack(requeue=false)` → message silently dropped forever\n• `nack(requeue=true)` → infinite retry loop, blocks the queue\n\nWith DLX:\n• Failed messages go to a safe holding area\n• Engineers can inspect, debug, fix, and replay them\n• Retry patterns are simple: just queue arguments, no application timers needed",
    diagram:
      "  DLX RETRY PATTERN\n\n  [Main Queue] ─────────► [Consumer]\n       ▲                      │\n       │                 fails (nack)\n       │                 requeue=false\n       │                      │\n       │                      ▼\n       │              [DLX Exchange]\n       │                      │\n       │                      ▼\n       │             [Retry Queue]\n       │             x-message-ttl: 30s\n       │             x-dead-letter-exchange: main\n       │                      │\n       └─── after 30s ────────┘\n            TTL expires\n\n  After max retries exceeded:\n  [Retry Queue] ──► [Permanent DLQ] (manual review)",
    example:
      "// Dead Letter Exchange + retry pattern\n\nconst amqp = require('amqplib');\n\nasync function setupDLX() {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n\n  // 1. Declare the Dead Letter Exchange\n  await channel.assertExchange('orders.dlx', 'direct', { durable: true });\n\n  // 2. Declare the retry queue (holds messages for 30s before returning)\n  await channel.assertQueue('orders.retry', {\n    durable: true,\n    arguments: {\n      'x-message-ttl':          30000,        // wait 30 seconds\n      'x-dead-letter-exchange': 'orders',     // then route back to original exchange\n    },\n  });\n  await channel.bindQueue('orders.retry', 'orders.dlx', 'retry');\n\n  // 3. Declare the permanent dead letter queue (after max retries)\n  await channel.assertQueue('orders.dead', { durable: true });\n  await channel.bindQueue('orders.dead', 'orders.dlx', 'dead');\n\n  // 4. Declare the main processing queue with DLX configured\n  await channel.assertExchange('orders', 'direct', { durable: true });\n  await channel.assertQueue('orders.processing', {\n    durable: true,\n    arguments: {\n      'x-dead-letter-exchange':    'orders.dlx',\n      'x-dead-letter-routing-key': 'retry',  // failed messages go to retry queue\n    },\n  });\n  await channel.bindQueue('orders.processing', 'orders', 'process');\n\n  // 5. Consumer with retry count tracking\n  channel.prefetch(1);\n  channel.consume('orders.processing', (msg) => {\n    if (!msg) return;\n    const data    = JSON.parse(msg.content.toString());\n    const retries = (msg.properties.headers['x-retry-count'] ?? 0);\n\n    try {\n      processOrder(data);           // if this throws...\n      channel.ack(msg);\n    } catch (err) {\n      if (retries >= 5) {\n        // Max retries hit — send to permanent dead letter queue\n        channel.nack(msg, false, false);\n        // Note: update routing key in headers to 'dead' in real implementation\n      } else {\n        // Increment retry count and nack — goes to retry queue\n        msg.properties.headers['x-retry-count'] = retries + 1;\n        channel.nack(msg, false, false);\n      }\n    }\n  }, { noAck: false });\n}\n\nsetupDLX();",
    tip: "Mention DLX proactively when discussing error handling: 'I configure a DLX on every processing queue. Failed messages go there automatically instead of being dropped or looping forever. For delayed retries, I combine DLX with a TTL-based retry queue — no application-level timers, just queue arguments.'",
    tags: ["DLX", "Dead Letter Exchange", "TTL", "Retry Pattern", "nack", "x-dead-letter-exchange", "x-message-ttl", "Poison Message"],
  },

  // ─────────────────────────────────────────────
  // PERFORMANCE
  // ─────────────────────────────────────────────
  {
    id: 7,
    section: "Performance",
    title: "Prefetch & Consumer Flow Control",
    tagline: "Controlling how many messages a consumer holds at once for fair distribution",
    description:
      "By default, RabbitMQ dispatches messages to consumers as fast as possible. When multiple consumers have different processing speeds, this creates a serious imbalance: slow consumers get overwhelmed while fast consumers sit idle.\n\n<b>The problem without prefetch</b>\n\nImagine 1,000 messages in a queue and 3 consumers:\n\n• RabbitMQ dispatches all 1,000 at once — ~333 to each\n• Consumer 1 is fast (10ms/message) → done in 3.3 seconds, then sits idle\n• Consumer 2 is slow (500ms/message) → still working after 2.7 minutes\n• Consumer 3 is medium speed\n\nConsumer 1 has been idle for over 2 minutes while Consumer 2 is drowning. RabbitMQ already dispatched everything and cannot redistribute. This wastes resources and slows throughput.\n\n<b>Setting prefetch count (QoS)</b>\n\n`channel.prefetch(1)` — QoS (Quality of Service) setting.\n\nWith `prefetch(1)`:\n• RabbitMQ sends 1 message to the consumer\n• The consumer acks it\n• Only then does RabbitMQ send the next message\n\nResult: fast consumers ack quickly and naturally receive more messages. Slow consumers hold exactly 1 message at a time. This is called fair dispatch.\n\n<b>Choosing the right prefetch count</b>\n\n`prefetch(1)` — maximum fairness, slightly higher overhead\n• Best when: processing time varies between messages\n• Best when: consumer crashes should lose the fewest messages\n\n`prefetch(10–20)` — balanced for moderate workloads\n• Reduces round-trip overhead by batching\n\n`prefetch(100+)` — maximum throughput, risk of imbalance\n• Best when: all messages take roughly equal time\n• Risk: a crashing consumer was holding 100+ messages that must all be redelivered\n\n<b>Global vs per-consumer</b>\n\n`channel.prefetch(count, false)` — per-consumer limit (default, use this)\n`channel.prefetch(count, true)` — limit across all consumers on the connection",
    note:
      "Always set prefetch in production. Without it:\n• RabbitMQ dispatches thousands of messages to a consumer about to crash\n• Slow consumers hold all the work while fast ones are idle\n\nStart with `prefetch(1)` for correctness. Increase after measuring throughput if needed.",
    diagram:
      "  WITHOUT PREFETCH (imbalanced)\n\n  [Queue: 1000 msgs]\n       │\n  ─────┼──────────────────────────────\n  │         │              │\n  ▼         ▼              ▼\n  Consumer1 Consumer2      Consumer3\n  333 msgs  333 msgs       334 msgs\n  (done in  (working for   (medium)\n  3.3s,     2.7 min)\n  then idle)\n\n  WITH PREFETCH(1) — fair dispatch\n\n  [Queue] ──1 msg──► Consumer1 ──ack──► next msg (fast, gets more)\n          ──1 msg──► Consumer2 ──ack──► next msg (slow, gets fewer)\n          ──1 msg──► Consumer3 ──ack──► next msg",
    example:
      "// prefetch(1) — fair dispatch between multiple workers\n\nconst amqp = require('amqplib');\n\nasync function worker(id) {\n  const connection = await amqp.connect('amqp://localhost');\n  const channel    = await connection.createChannel();\n  const queue      = 'image.resize';\n\n  await channel.assertQueue(queue, { durable: true });\n\n  // Only receive 1 message at a time\n  // The next message is only sent after ack\n  channel.prefetch(1);\n\n  console.log(`Worker ${id} waiting for messages...`);\n\n  channel.consume(queue, async (msg) => {\n    if (!msg) return;\n    const data = JSON.parse(msg.content.toString());\n\n    console.log(`Worker ${id} processing: ${data.imageUrl}`);\n    await resizeImage(data.imageUrl, data.width, data.height); // slow operation\n\n    channel.ack(msg); // done — RabbitMQ now sends the next message\n    console.log(`Worker ${id} done.`);\n  }, { noAck: false });\n}\n\n// Run 3 workers in parallel\n// Fast workers process more images, slow workers process fewer\nworker(1);\nworker(2);\nworker(3);",
    tip: "Mention prefetch when discussing worker scaling: 'I set channel.prefetch(1) on each worker for fair dispatch — fast workers automatically get more messages, slow ones get fewer. Without prefetch, one overloaded worker holds hundreds of messages while others sit idle, defeating the purpose of horizontal scaling.'",
    tags: ["Prefetch", "QoS", "Fair Dispatch", "Flow Control", "Consumer", "prefetch", "Throughput", "Workers"],
  },

  // ─────────────────────────────────────────────
  // HIGH AVAILABILITY
  // ─────────────────────────────────────────────
  {
    id: 8,
    section: "High Availability",
    title: "RabbitMQ Clustering & Quorum Queues",
    tagline: "Running RabbitMQ across multiple nodes so one crash doesn't stop everything",
    description:
      "A single RabbitMQ node is a single point of failure. If it crashes, all connections drop and all in-memory messages are gone. Clustering solves this by running multiple nodes together as one logical broker.\n\n<b>What a cluster shares</b>\n\nCluster nodes automatically share:\n• Exchange definitions\n• Queue definitions\n• User accounts and permissions\n• Virtual hosts\n\nWhat they do NOT share by default: the messages stored inside queues.\n\nThis means if Node A holds 10,000 messages and crashes, those messages are lost — even though Nodes B and C know the queue exists. For message data to survive, you need Quorum Queues.\n\n<b>Classic Mirrored Queues (legacy — avoid for new work)</b>\n\nOlder RabbitMQ used mirrored queues. A master node plus mirror nodes. Heavy overhead, slow resync, poor consistency guarantees. Being deprecated. Use Quorum Queues instead.\n\n<b>Quorum Queues — the modern standard</b>\n\nQuorum Queues use the Raft consensus algorithm (same as etcd, Consul). Messages are only confirmed when a quorum — majority — of nodes have written to disk.\n\nHow it works:\n• Each queue has a leader node and follower nodes\n• A write goes to leader AND majority of followers before ack is sent to producer\n• If the leader crashes, followers elect a new leader automatically via Raft\n• No messages in quorum are ever lost during failover\n\nQuorum formula:\n• 3 nodes → quorum = 2 (tolerates 1 failure)\n• 5 nodes → quorum = 3 (tolerates 2 failures)\n\nMinimum recommended cluster: 3 nodes.\n\n<b>Quorum queue limitations</b>\n\n• No per-message TTL (only per-queue TTL via policy)\n• No message priority\n• DLX, acks, and prefetch all work normally\n\n<b>Client connection failover</b>\n\nClients connect to one node. Configure all node addresses for automatic reconnection on failure:\n\n`amqp://user:pass@rabbit1:5672,rabbit2:5672,rabbit3:5672/`\n\n<b>The Erlang cookie</b>\n\nAll nodes must share the same `.erlang.cookie` secret file. This authenticates nodes to each other when joining the cluster.",
    note:
      "Use Quorum Queues for all new production deployments. Classic mirrored queues are legacy.\n\n3-node cluster minimum:\n• Tolerates 1 node failure\n• Quorum = 2 of 3 must agree\n\nFor full HA combine:\n• 3-node cluster + Quorum Queues\n• Durable queues + persistent messages\n• Publisher confirms\n• Client auto-reconnect with all node addresses",
    diagram:
      "  3-NODE QUORUM QUEUE CLUSTER\n\n  Producer\n     │ publish\n     ▼\n  [Node 1: Leader] ──Raft write──► [Node 2: Follower]\n         │           ──Raft write──► [Node 3: Follower]\n         │\n    quorum ack (2/3 nodes confirmed)\n         │\n  ack back to Producer\n\n  If Node 1 crashes:\n  [Node 2] and [Node 3] still have quorum (2/3)\n  → Raft election → Node 2 becomes new Leader\n  → Clients reconnect automatically",
    example:
      "// Declare a Quorum Queue (requires RabbitMQ 3.8+)\n\nconst amqp = require('amqplib');\n\nasync function setupQuorumQueue() {\n  // Connect with all 3 nodes for automatic failover\n  // amqplib tries each address in order on connection failure\n  const connection = await amqp.connect([\n    'amqp://user:pass@rabbit1:5672',\n    'amqp://user:pass@rabbit2:5672',\n    'amqp://user:pass@rabbit3:5672',\n  ]);\n\n  const channel = await connection.createChannel();\n\n  // Declare a Quorum Queue using the x-queue-type argument\n  await channel.assertQueue('payments.quorum', {\n    durable: true,  // required for quorum queues\n    arguments: {\n      'x-queue-type': 'quorum',   // enables Raft-based replication\n      // 'x-quorum-initial-group-size': 3  // default is 3\n    },\n  });\n\n  console.log('Quorum queue ready — messages replicated across 3 nodes.');\n\n  // Publish a persistent message\n  await channel.confirmSelect();\n  channel.sendToQueue(\n    'payments.quorum',\n    Buffer.from(JSON.stringify({ orderId: 789 })),\n    { persistent: true }\n  );\n  await channel.waitForConfirms();\n  console.log('Message written to quorum — safe even if one node fails.');\n\n  await channel.close();\n  await connection.close();\n}\n\nsetupQuorumQueue();",
    tip: "For RabbitMQ HA: 'I'd run a 3-node cluster with Quorum Queues — Raft-based replication means one node can fail without losing any data. Clients are configured with all three addresses for automatic failover. Combined with persistent messages and publisher confirms, this covers both broker availability and message durability.'",
    tags: ["RabbitMQ Cluster", "Quorum Queues", "Raft", "High Availability", "Leader Election", "x-queue-type", "Failover", "Erlang Cookie"],
  },

  // ─────────────────────────────────────────────
  // PATTERNS
  // ─────────────────────────────────────────────
  {
    id: 9,
    section: "Patterns",
    title: "RabbitMQ Messaging Patterns",
    tagline: "Six proven patterns for different async communication needs",
    description:
      "RabbitMQ is flexible enough to implement many different messaging patterns. Each pattern solves a different problem. Choosing the right one determines correctness — the wrong pattern causes silent bugs.\n\n<b>1. Simple Queue (Point-to-Point)</b>\n\nOne producer, one consumer, one queue. The simplest possible setup.\n\n`Producer → Queue → Consumer`\n\nUse when: move work from one service to another. Example: user uploads a CSV → one worker imports it.\n\n<b>2. Work Queue (Competing Consumers)</b>\n\nOne producer, one queue, many consumers. Workers compete. Each message goes to exactly ONE consumer.\n\n`Producer → Queue → (Worker 1 OR Worker 2 OR Worker 3)`\n\nUse when: CPU-intensive tasks you want to parallelize. Example: video encoding — 10 workers compete, each video encoded by one.\n\nAlways use `prefetch(1)` for fair dispatch.\n\n<b>3. Pub/Sub — Publish/Subscribe (Fanout)</b>\n\nOne producer, fanout exchange, many queues. Every consumer gets a COPY of every message.\n\n`Producer → Fanout Exchange → Queue A (Consumer A) AND Queue B (Consumer B) AND Queue C (Consumer C)`\n\nKey difference from Work Queue: ALL consumers get every message. Work Queue sends each message to ONE.\n\nUse when: one event triggers many independent actions. Example: order placed → email + warehouse + analytics all get notified.\n\n<b>4. Routing (Direct Exchange)</b>\n\nMessages go to specific queues based on exact routing key.\n\n`Producer → Direct Exchange → key \"error\" → error.queue`\n\nUse when: different consumers handle different message types. Example: error logs → PagerDuty, info logs → archive.\n\n<b>5. Topics (Topic Exchange)</b>\n\nLike Routing but with wildcard patterns. Multi-level event categorization.\n\n`Producer → Topic Exchange → \"order.#\" → all.orders.queue`\n\nUse when: routing logic is hierarchical. Example: `audit.log.#` captures all audit logs; `audit.log.payment.*` captures only payment ones.\n\n<b>6. RPC (Request/Reply)</b>\n\nSynchronous-style request-response over RabbitMQ.\n\n1. Client creates temporary reply queue\n2. Client publishes request with `replyTo: reply_queue` and `correlationId: unique_id`\n3. Server processes and publishes response to `replyTo`\n4. Client matches response using `correlationId`\n\nUse when: you need request-reply but want to route through the same broker. Less common in modern systems — prefer REST or gRPC for synchronous calls.",
    note:
      "Pattern cheat sheet:\n\n• Simple Queue → one-to-one\n• Work Queue → one message to ONE competing worker\n• Pub/Sub → one message to ALL consumers\n• Routing → selective by exact key\n• Topics → selective by wildcard pattern\n• RPC → async request-reply\n\nMost common confusion: Work Queue vs Pub/Sub.\nWork Queue: each message processed by one worker.\nPub/Sub: each message received by all consumers independently.",
    diagram:
      "  WORK QUEUE (each message to ONE worker)\n\n  [Producer] ──► [Queue] ──► Worker 1  (gets msg OR)\n                          ──► Worker 2  (gets msg OR)\n                          ──► Worker 3  (gets msg)\n\n  PUB/SUB (each message to ALL consumers)\n\n  [Publisher] ──► [Fanout Exchange] ──► [Queue A] ──► Consumer A\n                                    ──► [Queue B] ──► Consumer B\n                                    ──► [Queue C] ──► Consumer C\n\n  TOPIC ROUTING\n\n  [Producer] ──\"order.created\"──► [Topic Exchange]\n                 \"order.#\" binding ──► all.orders.queue  ✓\n              \"order.created\" binding ──► new.orders.queue  ✓\n               \"payment.#\" binding ──► payments.queue  ✗ no match",
    example:
      "// Three patterns in one file: Work Queue, Pub/Sub, and RPC\n\nconst amqp = require('amqplib');\n\n// ── 1. Work Queue ─────────────────────────────────────────────\nasync function workQueueDemo() {\n  const conn    = await amqp.connect('amqp://localhost');\n  const channel = await conn.createChannel();\n  await channel.assertQueue('resize.jobs', { durable: true });\n  channel.prefetch(1);\n\n  // Producer: send 10 resize jobs\n  for (let i = 1; i <= 10; i++) {\n    channel.sendToQueue('resize.jobs',\n      Buffer.from(JSON.stringify({ imageId: i })),\n      { persistent: true }\n    );\n  }\n\n  // Workers compete for jobs — each image processed once\n  for (let w = 1; w <= 3; w++) {\n    channel.consume('resize.jobs', (msg) => {\n      const { imageId } = JSON.parse(msg.content.toString());\n      console.log(`Worker ${w} resizing image ${imageId}`);\n      channel.ack(msg);\n    }, { noAck: false });\n  }\n}\n\n// ── 2. Pub/Sub ────────────────────────────────────────────────\nasync function pubSubDemo() {\n  const conn    = await amqp.connect('amqp://localhost');\n  const channel = await conn.createChannel();\n\n  await channel.assertExchange('order.events', 'fanout', { durable: false });\n\n  // Three independent subscribers — each gets every event\n  const services = ['email.service', 'warehouse.service', 'analytics.service'];\n  for (const name of services) {\n    await channel.assertQueue(name, { durable: true });\n    await channel.bindQueue(name, 'order.events', ''); // routing key ignored\n    channel.consume(name, (msg) => {\n      console.log(`${name} received: ${msg.content.toString()}`);\n      channel.ack(msg);\n    }, { noAck: false });\n  }\n\n  // Publish one event — ALL three services receive a copy\n  channel.publish('order.events', '',\n    Buffer.from(JSON.stringify({ orderId: 100, status: 'placed' }))\n  );\n}\n\nworkQueueDemo();\npubSubDemo();",
    tip: "Map each use case to a pattern explicitly: 'For processing orders I'd use a Work Queue — 10 workers compete, each order handled by exactly one. For broadcasting the order event I'd use Pub/Sub — email, warehouse, and analytics all independently receive every event.' This shows you understand semantics, not just tool names.",
    tags: ["Work Queue", "Pub/Sub", "Fanout", "Routing", "Topic", "RPC", "Competing Consumers", "Messaging Patterns", "correlationId"],
  },
];

export const RABBITMQ_CONCEPT_COUNT = RABBITMQ_CONCEPTS.length;
