import type { RoadmapDayDetail } from "@/lib/challenge-data";

const L = {
  o1: {
    en: "**Terraform state** (`terraform.tfstate`) is a JSON file that maps every resource block in your HCL configuration to a real infrastructure object. Without state, Terraform would have no way of knowing that `resource \"aws_instance\" \"web\"` in your configuration corresponds to instance `i-0abc123def456789` in AWS — it would blindly create a new instance every time you run apply, resulting in duplicate infrastructure and an ever-growing AWS bill. State stores the resource ID, every attribute (public IP, private IP, security group IDs, tags), provider metadata, and dependency relationships for every managed resource. This is what enables incremental changes: Terraform reads state to understand what currently exists, reads your HCL to understand what should exist, diffs the two, and executes only the necessary API calls to reconcile them. State also stores sensitive values — database passwords generated by AWS, private keys, connection strings — so the state file must be treated as a secret and protected accordingly. By default, state is stored locally as `terraform.tfstate` in your working directory. This is convenient for solo learning but catastrophic for teams: two engineers running `terraform apply` at the same time will both read the same state, independently compute plans, and each attempt to apply — potentially creating duplicate resources or overwriting each other's changes. There is no locking, no collaboration, and no history with local state. Additionally, the state file is not backed up: one `rm terraform.tfstate` and Terraform loses all knowledge of what it manages — the infrastructure still exists in AWS but Terraform can no longer manage, modify, or safely destroy it. These problems are solved by remote backends.",
    np: "**Terraform state** (`terraform.tfstate`) एउटा JSON file हो जसले HCL configuration मा हरेक resource block लाई real infrastructure object सँग map गर्छ। State बिना, Terraform लाई थाहा हुने उपाय छैन कि configuration मा `resource \"aws_instance\" \"web\"` AWS मा instance `i-0abc123def456789` सँग correspond गर्छ — यसले apply run गर्ने हरेक पटक blindly नयाँ instance create गर्थ्यो, जसले duplicate infrastructure र सधैं बढ्दो AWS bill ल्याउँथ्यो। State ले resource ID, हरेक attribute (public IP, private IP, security group ID, tag), provider metadata, र हरेक managed resource को dependency relationship store गर्छ। यही incremental change enable गर्छ: Terraform ले state पढेर currently के छ बुझ्छ, HCL पढेर के हुनुपर्छ बुझ्छ, दुईलाई diff गर्छ, र reconcile गर्न आवश्यक API call मात्र execute गर्छ। State ले sensitive value पनि store गर्छ — AWS ले generate गरेको database password, private key, connection string — त्यसैले state file लाई secret मान्नुपर्छ र accordingly protect गर्नुपर्छ। Default रूपमा, state working directory मा `terraform.tfstate` को रूपमा locally store हुन्छ। Solo learning को लागि convenient छ तर team को लागि catastrophic: एकै समयमा `terraform apply` run गर्ने दुई engineer दुवैले same state पढ्छन्, independently plan compute गर्छन्, र प्रत्येकले apply गर्ने प्रयास गर्छन् — सम्भवतः duplicate resource create हुन्छ वा एकले अर्काको change overwrite गर्छ। Local state सँग कुनै locking, collaboration, वा history छैन। थप, state file backup हुँदैन: एउटा `rm terraform.tfstate` र Terraform ले आफूले manage गरेको सबैको knowledge गुमाउँछ — infrastructure AWS मा अझसम्म छ तर Terraform ले अब manage, modify, वा safely destroy गर्न सक्दैन। Remote backend ले यी समस्या solve गर्छन्।",
    jp: "**Terraform 状態**（`terraform.tfstate`）は HCL 設定のすべてのリソースブロックを実際のインフラオブジェクトにマッピングする JSON ファイルです。状態なしでは、Terraform は設定内の `resource \"aws_instance\" \"web\"` が AWS のインスタンス `i-0abc123def456789` に対応していることを知る方法がありません — apply を実行するたびに盲目的に新しいインスタンスを作成し、重複したインフラと増え続ける AWS の請求書をもたらすでしょう。状態はリソース ID・すべての属性（パブリック IP・プライベート IP・セキュリティグループ ID・タグ）・プロバイダーメタデータ・すべての管理対象リソースの依存関係を保存します。これがインクリメンタルな変更を可能にします：Terraform は状態を読んで現在何が存在するかを理解し、HCL を読んで何が存在すべきかを理解し、2 つを比較し、調和させるために必要な API 呼び出しのみを実行します。状態は機密値も保存します — AWS が生成したデータベースパスワード・秘密鍵・接続文字列 — そのため状態ファイルはシークレットとして扱い、適切に保護する必要があります。デフォルトでは、状態は作業ディレクトリに `terraform.tfstate` としてローカルに保存されます。個人学習には便利ですが、チームには壊滅的です：同時に `terraform apply` を実行する 2 人のエンジニアは同じ状態を読み込み、独立してプランを計算し、それぞれ適用を試みます — 重複リソースを作成したり、お互いの変更を上書きする可能性があります。ローカル状態にはロック・コラボレーション・履歴がありません。さらに、状態ファイルはバックアップされません：`rm terraform.tfstate` 一発で Terraform は管理しているものすべての知識を失います — インフラは AWS にまだ存在しますが、Terraform はもはやそれを管理・変更・安全に破棄することができません。これらの問題はリモートバックエンドが解決します。",
  } as const,
  o2: {
    en: "**Remote backends** solve the team state problem by storing state in a shared, versioned, and locked location. The most common backend in AWS-centric teams is the **S3 backend with DynamoDB locking**: state is stored in an S3 bucket (versioned for history and rollback), and a DynamoDB table is used for **state locking** — before any `plan` or `apply`, Terraform writes a lock record to DynamoDB. If another engineer attempts an apply while the lock exists, Terraform immediately rejects their operation with a clear error, preventing concurrent modification. The backend configuration goes inside the `terraform {}` block: `terraform { backend \"s3\" { bucket = \"my-tfstate\" key = \"prod/terraform.tfstate\" region = \"us-east-1\" dynamodb_table = \"terraform-locks\" encrypt = true } }`. Run `terraform init` after adding or changing the backend block — Terraform will detect the change, offer to migrate existing local state to the remote backend, and configure the connection. **State commands** give you surgical control over the state file: `terraform state list` lists all managed resources by address (`aws_instance.web`, `module.vpc.aws_vpc.main`), `terraform state show aws_instance.web` dumps all current attributes of a specific resource, `terraform state mv aws_instance.web aws_instance.app` renames a resource address in state without destroying and recreating (critical for refactoring), `terraform state rm aws_instance.web` removes a resource from state without destroying the real resource (useful when you want Terraform to stop managing something it previously created). `terraform import aws_instance.legacy i-0abc123` brings an existing, manually-created resource under Terraform management by writing its state record — after import, any future `apply` will manage it declaratively. **Terraform Workspaces** provide isolated state namespaces within a single backend: `terraform workspace new staging` creates a new workspace with its own empty state, `terraform workspace select production` switches to the production state, `terraform workspace list` shows all workspaces. Each workspace stores its state at `env:/workspace-name/key` in the S3 backend. Workspaces are best for managing a small number of near-identical environments (dev/staging/prod) from the same codebase. For fundamentally different infrastructure stacks, separate directories with separate state keys (and potentially separate AWS accounts) are a better pattern.",
    np: "**Remote backend** ले shared, versioned, र locked location मा state store गरेर team state problem solve गर्छन्। AWS-centric team मा सबैभन्दा common backend **DynamoDB locking सहित S3 backend** हो: state S3 bucket मा store हुन्छ (history र rollback को लागि versioned), र DynamoDB table **state locking** को लागि प्रयोग हुन्छ — कुनै पनि `plan` वा `apply` अघि, Terraform ले DynamoDB मा lock record लेख्छ। Lock छँदै अर्को engineer ले apply गर्ने प्रयास गरेमा, Terraform ले तुरुन्त clear error सँग उनीहरूको operation reject गर्छ, concurrent modification रोक्छ। Backend configuration `terraform {}` block भित्र जान्छ: `terraform { backend \"s3\" { bucket = \"my-tfstate\" key = \"prod/terraform.tfstate\" region = \"us-east-1\" dynamodb_table = \"terraform-locks\" encrypt = true } }`। Backend block add वा change गरेपछि `terraform init` run गर्नुहोस् — Terraform ले change detect गर्छ, existing local state remote backend मा migrate गर्न offer गर्छ, र connection configure गर्छ। **State command** ले state file मा surgical control दिन्छ: `terraform state list` ले address (`aws_instance.web`, `module.vpc.aws_vpc.main`) अनुसार सबै managed resource list गर्छ, `terraform state show aws_instance.web` ले specific resource का सबै current attribute dump गर्छ, `terraform state mv aws_instance.web aws_instance.app` ले destroy र recreate नगरी state मा resource address rename गर्छ (refactoring को लागि critical), `terraform state rm aws_instance.web` ले real resource destroy नगरी state बाट resource remove गर्छ (Terraform ले previously create गरेको केही manage गर्न नरहोस् भन्दा useful)। `terraform import aws_instance.legacy i-0abc123` ले existing, manually-created resource लाई state record लेखेर Terraform management अन्तर्गत ल्याउँछ — import पछि, कुनै पनि future `apply` ले declaratively manage गर्छ। **Terraform Workspace** ले single backend भित्र isolated state namespace provide गर्छ: `terraform workspace new staging` ले आफ्नो empty state सहित नयाँ workspace create गर्छ, `terraform workspace select production` ले production state मा switch गर्छ, `terraform workspace list` ले सबै workspace देखाउँछ। प्रत्येक workspace ले S3 backend मा `env:/workspace-name/key` मा आफ्नो state store गर्छ। Workspace ले same codebase बाट थोरै near-identical environment (dev/staging/prod) manage गर्न best छ। Fundamentally different infrastructure stack को लागि, छुट्टाछुट्टै state key (र सम्भवतः छुट्टाछुट्टै AWS account) सहित छुट्टाछुट्टै directory राम्रो pattern हो।",
    jp: "**リモートバックエンド**は状態を共有・バージョン管理・ロックされた場所に保存することでチームの状態問題を解決します。AWS 中心のチームで最も一般的なバックエンドは **DynamoDB ロック付き S3 バックエンド**です：状態は S3 バケットに保存され（履歴とロールバックのためにバージョン管理）、DynamoDB テーブルが**状態ロック**に使用されます — `plan` や `apply` の前に Terraform は DynamoDB にロックレコードを書き込みます。ロックが存在する間に別のエンジニアが apply を試みると、Terraform は即座に明確なエラーでその操作を拒否し、同時変更を防ぎます。バックエンド設定は `terraform {}` ブロック内に入ります：`terraform { backend \"s3\" { bucket = \"my-tfstate\" key = \"prod/terraform.tfstate\" region = \"us-east-1\" dynamodb_table = \"terraform-locks\" encrypt = true } }`。バックエンドブロックを追加または変更した後に `terraform init` を実行します — Terraform は変更を検出し、既存のローカル状態をリモートバックエンドに移行することを提案し、接続を設定します。**状態コマンド**は状態ファイルに対する外科的な制御を提供します：`terraform state list` はアドレス（`aws_instance.web`・`module.vpc.aws_vpc.main`）ですべての管理対象リソースをリスト表示し、`terraform state show aws_instance.web` は特定リソースの現在の属性をすべてダンプし、`terraform state mv aws_instance.web aws_instance.app` は破棄・再作成せずに状態内のリソースアドレスを変更し（リファクタリングに重要）、`terraform state rm aws_instance.web` は実際のリソースを破棄せずに状態からリソースを削除します（Terraform が以前に作成したものの管理を停止したい場合に便利）。`terraform import aws_instance.legacy i-0abc123` は状態レコードを書き込むことで既存の手動作成リソースを Terraform 管理下に置きます — インポート後、将来の `apply` は宣言的に管理します。**Terraform ワークスペース**は単一バックエンド内で分離された状態名前空間を提供します：`terraform workspace new staging` は独自の空の状態を持つ新しいワークスペースを作成し、`terraform workspace select production` は本番状態に切り替え、`terraform workspace list` はすべてのワークスペースを表示します。各ワークスペースは S3 バックエンドの `env:/workspace-name/key` に状態を保存します。ワークスペースは同じコードベースから少数の非常に似た環境（dev/staging/prod）を管理するのに最適です。根本的に異なるインフラスタックには、別々の状態キー（場合によっては別々の AWS アカウント）を持つ別々のディレクトリがより良いパターンです。",
  } as const,
};

export const DEVOPS_DAY_80_DETAIL: RoadmapDayDetail = {
  overview: [L.o1, L.o2],
  sections: [
    {
      title: {
        en: "State file internals & why remote backends are required for teams",
        np: "State file internals र team को लागि remote backend किन चाहिन्छ",
        jp: "状態ファイルの内部構造とチームにリモートバックエンドが必要な理由",
      },
      blocks: [
        { type: "diagram", id: "devops-terraform-state" },
        {
          type: "table",
          caption: {
            en: "Remote backend options — choosing the right state backend for your team",
            np: "Remote backend option — team को लागि सही state backend छान्ने",
            jp: "リモートバックエンドの選択肢 — チームに適した状態バックエンドの選択",
          },
          headers: [
            { en: "Backend", np: "Backend", jp: "バックエンド" },
            { en: "State storage", np: "State storage", jp: "状態ストレージ" },
            { en: "Locking mechanism", np: "Locking mechanism", jp: "ロック機構" },
            { en: "Best for", np: "Best for", jp: "最適な用途" },
            { en: "Cost", np: "Cost", jp: "コスト" },
          ],
          rows: [
            [
              { en: "Local", np: "Local", jp: "ローカル" },
              { en: "`terraform.tfstate` on disk", np: "disk मा `terraform.tfstate`", jp: "ディスク上の `terraform.tfstate`" },
              { en: "None — no locking", np: "कुनै पनि छैन — locking छैन", jp: "なし — ロックなし" },
              { en: "Solo learning & experiments", np: "Solo learning र experiment", jp: "個人学習と実験" },
              { en: "Free", np: "निःशुल्क", jp: "無料" },
            ],
            [
              { en: "S3 + DynamoDB", np: "S3 + DynamoDB", jp: "S3 + DynamoDB" },
              { en: "S3 bucket (versioned, encrypted)", np: "S3 bucket (versioned, encrypted)", jp: "S3 バケット（バージョン管理・暗号化）" },
              { en: "DynamoDB table (put/delete item per operation)", np: "DynamoDB table (operation per put/delete item)", jp: "DynamoDB テーブル（操作ごとに put/delete アイテム）" },
              { en: "AWS-centric teams (most common)", np: "AWS-centric team (सबैभन्दा common)", jp: "AWS 中心のチーム（最も一般的）" },
              { en: "~$0.023/GB/month + minimal DynamoDB", np: "~$0.023/GB/month + minimal DynamoDB", jp: "約 $0.023/GB/月 + 最小限の DynamoDB" },
            ],
            [
              { en: "GCS", np: "GCS", jp: "GCS" },
              { en: "Google Cloud Storage bucket", np: "Google Cloud Storage bucket", jp: "Google Cloud Storage バケット" },
              { en: "Native GCS object lock", np: "Native GCS object lock", jp: "ネイティブ GCS オブジェクトロック" },
              { en: "GCP-centric teams", np: "GCP-centric team", jp: "GCP 中心のチーム" },
              { en: "~$0.020/GB/month", np: "~$0.020/GB/month", jp: "約 $0.020/GB/月" },
            ],
            [
              { en: "Azure Blob Storage", np: "Azure Blob Storage", jp: "Azure Blob Storage" },
              { en: "Azure Storage container", np: "Azure Storage container", jp: "Azure Storage コンテナー" },
              { en: "Azure Storage blob leases", np: "Azure Storage blob lease", jp: "Azure Storage BLOB リース" },
              { en: "Azure-centric teams", np: "Azure-centric team", jp: "Azure 中心のチーム" },
              { en: "~$0.018/GB/month", np: "~$0.018/GB/month", jp: "約 $0.018/GB/月" },
            ],
            [
              { en: "Terraform Cloud", np: "Terraform Cloud", jp: "Terraform Cloud" },
              { en: "HashiCorp-managed, encrypted at rest", np: "HashiCorp-managed, encrypted at rest", jp: "HashiCorp 管理型・保存時暗号化" },
              { en: "Built-in — automatic per-run locking", np: "Built-in — automatic per-run locking", jp: "組み込み — 実行ごとの自動ロック" },
              { en: "Teams wanting managed backend + CI/CD + RBAC", np: "Managed backend + CI/CD + RBAC चाहने team", jp: "管理型バックエンド + CI/CD + RBAC が必要なチーム" },
              { en: "Free (500 resources), paid tiers for teams", np: "Free (500 resource), team को लागि paid tier", jp: "無料（500 リソース）、チーム向け有料プラン" },
            ],
          ],
        },
      ],
    },
    {
      title: {
        en: "State commands, import, and workspace isolation",
        np: "State command, import, र workspace isolation",
        jp: "状態コマンド・インポート・ワークスペースの分離",
      },
      blocks: [
        {
          type: "code",
          title: {
            en: "S3 backend config, state commands, terraform import, and workspaces",
            np: "S3 backend config, state command, terraform import, र workspace",
            jp: "S3 バックエンド設定・状態コマンド・terraform import・ワークスペース",
          },
          code: `# ── 1. Create S3 bucket + DynamoDB table for remote state ────────────
# (Do this once — often with a separate bootstrap Terraform config)
aws s3api create-bucket \\
  --bucket my-terraform-state-bucket \\
  --region us-east-1

aws s3api put-bucket-versioning \\
  --bucket my-terraform-state-bucket \\
  --versioning-configuration Status=Enabled

aws s3api put-bucket-encryption \\
  --bucket my-terraform-state-bucket \\
  --server-side-encryption-configuration \\
    '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'

aws dynamodb create-table \\
  --table-name terraform-locks \\
  --attribute-definitions AttributeName=LockID,AttributeType=S \\
  --key-schema AttributeName=LockID,KeyType=HASH \\
  --billing-mode PAY_PER_REQUEST \\
  --region us-east-1

# ── 2. Configure S3 backend in main.tf ───────────────────────────────
terraform {
  required_version = ">= 1.5.0"

  backend "s3" {
    bucket         = "my-terraform-state-bucket"
    key            = "prod/terraform.tfstate"   # path inside the bucket
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"          # locking table
    encrypt        = true                       # encrypt state at rest
  }

  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

# ── 3. Migrate from local to remote backend ───────────────────────────
# Run init after adding/changing backend block — Terraform will offer migration
terraform init
# Output: Do you want to copy existing state to the new backend? (yes/no)
# Type: yes

# Verify — state is now in S3, local file is no longer used
aws s3 ls s3://my-terraform-state-bucket/prod/

# ── 4. State inspection commands ─────────────────────────────────────
# List all resources currently in state
terraform state list
# Output: aws_instance.web, aws_s3_bucket.assets, module.vpc.aws_vpc.main

# Show full attributes of a specific resource
terraform state show aws_instance.web
# Output: id = "i-0abc123def456789", ami = "ami-0...", public_ip = "1.2.3.4" ...

# Show a module resource
terraform state show module.vpc.aws_vpc.main

# ── 5. State manipulation commands ───────────────────────────────────
# Rename a resource in state (no destroy/recreate — just renames the address)
# Use case: you renamed resource "web" to "app" in HCL
terraform state mv aws_instance.web aws_instance.app

# Remove a resource from state without destroying it
# Use case: you want Terraform to stop managing this resource
terraform state rm aws_s3_bucket.assets
# The bucket still exists in AWS, Terraform just forgets about it

# ── 6. Importing existing resources ──────────────────────────────────
# Scenario: you created an EC2 instance manually — now bring it under Terraform

# Step 1: Add the resource block to your HCL (must match real resource)
# resource "aws_instance" "legacy" {
#   ami           = "ami-0abcdef1234567890"
#   instance_type = "t3.micro"
# }

# Step 2: Import — write the real resource's ID to state
terraform import aws_instance.legacy i-0abc123def456789
# Output: Import successful! aws_instance.legacy is now in state

# Step 3: Run plan to see if HCL matches state (fix any drift)
terraform plan
# If plan shows changes — update your HCL to match actual resource config

# ── 7. Workspace commands ─────────────────────────────────────────────
# List all workspaces (default is always there)
terraform workspace list
# * default

# Create a new workspace — gets its own empty state
terraform workspace new staging
# Switched to workspace "staging"

terraform workspace new production

# List again
terraform workspace list
#   default
#   staging
# * production   <- current

# Show current workspace
terraform workspace show
# production

# Switch workspace
terraform workspace select staging

# In S3 backend, state paths are:
#   default:    s3://bucket/prod/terraform.tfstate
#   staging:    s3://bucket/env:/staging/prod/terraform.tfstate
#   production: s3://bucket/env:/production/prod/terraform.tfstate

# Use workspace name in config to vary resources per environment
# resource "aws_instance" "web" {
#   instance_type = terraform.workspace == "production" ? "t3.large" : "t3.micro"
# }

# ── 8. State file structure (simplified) ─────────────────────────────
# terraform.tfstate is JSON — key fields:
# {
#   "version": 4,
#   "terraform_version": "1.7.5",
#   "serial": 12,            <- increments on every apply
#   "lineage": "uuid...",    <- unique ID for this state file
#   "resources": [
#     {
#       "mode": "managed",
#       "type": "aws_instance",
#       "name": "web",
#       "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
#       "instances": [{
#         "schema_version": 1,
#         "attributes": {
#           "id": "i-0abc123def456789",
#           "ami": "ami-0...",
#           "instance_type": "t3.micro",
#           "public_ip": "1.2.3.4",
#           "tags": { "Name": "web", "Environment": "dev" }
#         }
#       }]
#     }
#   ]
# }`,
        },
        {
          type: "list",
          variant: "number",
          items: [
            {
              en: "Set up a real S3 remote backend from scratch. First, use the AWS CLI to create an S3 bucket with versioning and server-side encryption enabled, and a DynamoDB table named `terraform-locks` with `LockID` as the partition key (PAY_PER_REQUEST billing). Then configure the S3 backend in your `main.tf` and run `terraform init` to migrate your existing local state to S3. Verify the migration by checking `aws s3 ls s3://your-bucket/` and confirming the state file appears. Run `terraform plan` to confirm Terraform can read remote state and the plan shows no changes. Then simulate a lock conflict: open two terminals, run `terraform apply` in both simultaneously — confirm the second terminal sees a lock error with the lock ID and who holds it.",
              np: "scratch बाट real S3 remote backend set up गर्नुहोस्। पहिले, AWS CLI प्रयोग गरेर versioning र server-side encryption enabled सहित S3 bucket, र `LockID` partition key (PAY_PER_REQUEST billing) सहित `terraform-locks` नामको DynamoDB table create गर्नुहोस्। त्यसपछि `main.tf` मा S3 backend configure गर्नुहोस् र existing local state S3 मा migrate गर्न `terraform init` run गर्नुहोस्। `aws s3 ls s3://your-bucket/` check गरेर migration verify गर्नुहोस् र state file appear भएको confirm गर्नुहोस्। Terraform ले remote state पढ्न सक्छ र plan ले कुनै change देखाउँदैन confirm गर्न `terraform plan` run गर्नुहोस्। त्यसपछि lock conflict simulate गर्नुहोस्: दुईवटा terminal खोल्नुहोस्, दुवैमा एकै समयमा `terraform apply` run गर्नुहोस् — दोस्रो terminal ले lock ID र कसले hold गरेको छ सहित lock error देख्छ confirm गर्नुहोस्।",
              jp: "スクラッチから実際の S3 リモートバックエンドをセットアップする。まず AWS CLI を使用して、バージョニングとサーバーサイド暗号化が有効な S3 バケットと、`LockID` をパーティションキーとする `terraform-locks` という名前の DynamoDB テーブル（PAY_PER_REQUEST 課金）を作成する。次に `main.tf` で S3 バックエンドを設定し、`terraform init` を実行して既存のローカル状態を S3 に移行する。`aws s3 ls s3://your-bucket/` を確認して移行を検証し、状態ファイルが表示されることを確認する。`terraform plan` を実行して Terraform がリモート状態を読み込め、プランが変更なしを示すことを確認する。次にロック競合をシミュレートする：2 つのターミナルを開き、両方で同時に `terraform apply` を実行する — 2 番目のターミナルがロック ID とロックを保持している人を含むロックエラーを表示することを確認する。",
            },
            {
              en: "Practice all four state manipulation commands on a live configuration. Deploy a small set of resources (at minimum: one `aws_s3_bucket`). Then: (1) run `terraform state list` and copy the resource address; (2) run `terraform state show <address>` and identify the `id` attribute — this is the real AWS resource ID; (3) rename the resource in your HCL (e.g., `my_bucket` → `primary_bucket`) and run `terraform state mv aws_s3_bucket.my_bucket aws_s3_bucket.primary_bucket` — then run `terraform plan` to confirm zero changes (the rename was done in state, HCL now matches); (4) run `terraform state rm aws_s3_bucket.primary_bucket`, then run `terraform plan` — confirm the plan now shows `1 to add` (Terraform forgot about the bucket but it still exists in AWS). Manually delete the bucket from the AWS console to clean up.",
              np: "Live configuration मा चारवटै state manipulation command practice गर्नुहोस्। Small set of resource deploy गर्नुहोस् (minimum: एउटा `aws_s3_bucket`)। त्यसपछि: (१) `terraform state list` run गर्नुहोस् र resource address copy गर्नुहोस्; (२) `terraform state show <address>` run गर्नुहोस् र `id` attribute identify गर्नुहोस् — यो real AWS resource ID हो; (३) HCL मा resource rename गर्नुहोस् (जस्तै, `my_bucket` → `primary_bucket`) र `terraform state mv aws_s3_bucket.my_bucket aws_s3_bucket.primary_bucket` run गर्नुहोस् — त्यसपछि zero change confirm गर्न `terraform plan` run गर्नुहोस् (rename state मा भयो, HCL अब match गर्छ); (४) `terraform state rm aws_s3_bucket.primary_bucket` run गर्नुहोस्, त्यसपछि `terraform plan` run गर्नुहोस् — plan ले `1 to add` देखाउँछ confirm गर्नुहोस् (Terraform ले bucket बिर्स्यो तर AWS मा अझसम्म छ)। Cleanup गर्न AWS console बाट manually bucket delete गर्नुहोस्।",
              jp: "ライブ設定ですべての 4 つの状態操作コマンドを練習する。小さなリソースセットをデプロイする（最低限：1 つの `aws_s3_bucket`）。次に：(1) `terraform state list` を実行してリソースアドレスをコピーする；(2) `terraform state show <address>` を実行して `id` 属性を特定する — これが実際の AWS リソース ID；(3) HCL でリソースを名前変更し（例：`my_bucket` → `primary_bucket`）`terraform state mv aws_s3_bucket.my_bucket aws_s3_bucket.primary_bucket` を実行する — 次に `terraform plan` を実行してゼロ変更を確認する（名前変更は状態で行われ、HCL が一致する）；(4) `terraform state rm aws_s3_bucket.primary_bucket` を実行し、`terraform plan` を実行する — プランが `1 to add` を示すことを確認する（Terraform はバケットを忘れたが AWS にはまだ存在する）。AWS コンソールからバケットを手動削除してクリーンアップする。",
            },
            {
              en: "Create three Terraform workspaces (`dev`, `staging`, `production`) and use `terraform.workspace` in your configuration to vary resource behavior per environment. In `main.tf`, create an `aws_s3_bucket` whose name includes `terraform.workspace` (e.g., `bucket = \"myapp-${terraform.workspace}-assets-$(random suffix)\"`). Add a local: `instance_type = terraform.workspace == \"production\" ? \"t3.large\" : \"t3.micro\"`. Switch through all three workspaces with `terraform workspace select` and run `terraform plan` in each — confirm each workspace shows its own bucket name. Apply in `dev` workspace, then switch to `staging` and run `terraform state list` — confirm the staging workspace state is empty (each workspace has isolated state). Finally, run `terraform workspace list` and observe the `*` marking the active workspace.",
              np: "तीनवटा Terraform workspace (`dev`, `staging`, `production`) create गर्नुहोस् र configuration मा `terraform.workspace` प्रयोग गरेर per environment resource behavior vary गर्नुहोस्। `main.tf` मा `aws_s3_bucket` create गर्नुहोस् जसको name मा `terraform.workspace` छ (जस्तै, `bucket = \"myapp-${terraform.workspace}-assets-$(random suffix)\"`)। Local add गर्नुहोस्: `instance_type = terraform.workspace == \"production\" ? \"t3.large\" : \"t3.micro\"`। `terraform workspace select` सँग तीनैवटा workspace मा switch गर्नुहोस् र प्रत्येकमा `terraform plan` run गर्नुहोस् — प्रत्येक workspace ले आफ्नै bucket name देखाउँछ confirm गर्नुहोस्। `dev` workspace मा apply गर्नुहोस्, त्यसपछि `staging` मा switch गर्नुहोस् र `terraform state list` run गर्नुहोस् — staging workspace state empty छ confirm गर्नुहोस् (प्रत्येक workspace को isolated state छ)। अन्तमा, `terraform workspace list` run गर्नुहोस् र `*` ले active workspace mark गरेको observe गर्नुहोस्।",
              jp: "3 つの Terraform ワークスペース（`dev`・`staging`・`production`）を作成し、設定で `terraform.workspace` を使って環境ごとにリソースの動作を変える。`main.tf` で名前に `terraform.workspace` を含む `aws_s3_bucket` を作成する（例：`bucket = \"myapp-${terraform.workspace}-assets-$(random suffix)\"`）。ローカルを追加する：`instance_type = terraform.workspace == \"production\" ? \"t3.large\" : \"t3.micro\"`。`terraform workspace select` で 3 つのワークスペースをすべて切り替え、それぞれで `terraform plan` を実行する — 各ワークスペースが独自のバケット名を示すことを確認する。`dev` ワークスペースで適用し、`staging` に切り替えて `terraform state list` を実行する — staging ワークスペースの状態が空であることを確認する（各ワークスペースは分離した状態を持つ）。最後に `terraform workspace list` を実行し、`*` がアクティブなワークスペースをマークしていることを確認する。",
            },
          ],
        },
      ],
    },
  ],
  faq: [
    {
      question: {
        en: "What happens if two engineers run `terraform apply` at the same time without state locking?",
        np: "State locking बिना दुई engineer एकै समयमा `terraform apply` run गरेमा के हुन्छ?",
        jp: "状態ロックなしで 2 人のエンジニアが同時に `terraform apply` を実行するとどうなるか？",
      },
      answer: {
        en: "Without state locking, concurrent `terraform apply` operations cause **state corruption** — one of the most dangerous failures in infrastructure management. Here is the exact sequence of events that leads to disaster. Both engineers run `terraform plan` at approximately the same time. Each reads the current state (which at this moment is identical for both), computes what changes need to be made, and proceeds to `apply`. Engineer A's apply starts first and creates a new EC2 instance `i-0aaa`. Terraform writes the new state to the state file with `i-0aaa`'s ID. Meanwhile, Engineer B's apply was running concurrently and also creates a new EC2 instance `i-0bbb`. When Engineer B's apply finishes, it writes its own version of the state file — overwriting Engineer A's version. Now the state file only knows about `i-0bbb`. Instance `i-0aaa` is running in AWS but is completely unknown to Terraform: it is an orphaned resource. If you run `terraform destroy`, only `i-0bbb` gets destroyed. `i-0aaa` runs forever, costing money, and cannot be managed or destroyed by Terraform without manual intervention. Things get worse with destructive operations: imagine both engineers read state showing `aws_db_instance.primary` exists. Engineer A changes the instance class (an in-place update). Engineer B independently decides to destroy and recreate the database. Both apply concurrently. The database is destroyed by B, recreated by B, then A's apply tries to modify the original instance ID (which no longer exists) — API error. The state is now in an indeterminate, corrupt state that requires manual forensics to recover. This is why state locking is not optional for teams. With S3+DynamoDB: before any apply, Terraform writes a `LockInfo` item to DynamoDB containing the lock ID, timestamp, who acquired it, and what operation is running. Any other `plan` or `apply` that starts while the lock exists immediately reads the DynamoDB table, sees the lock, and fails with a clear error: `Error: Error locking state: ConditionalCheckFailedException: Lock already acquired by [user], lock ID: [uuid]`. The engineer must wait for the current operation to finish (or use `terraform force-unlock [lock-id]` in emergency situations where a lock was left behind by a crashed process).",
        np: "State locking बिना, concurrent `terraform apply` operation ले **state corruption** गराउँछ — infrastructure management मा सबैभन्दा dangerous failure मध्ये एक। यो disaster ल्याउने exact sequence of event हो। दुवै engineer लगभग एकै समयमा `terraform plan` run गर्छन्। प्रत्येकले current state (जो यस क्षणमा दुवैको लागि identical छ) पढ्छ, के change गर्नुपर्छ compute गर्छ, र `apply` मा proceed गर्छ। Engineer A को apply पहिले start हुन्छ र नयाँ EC2 instance `i-0aaa` create गर्छ। Terraform ले `i-0aaa` को ID सहित नयाँ state state file मा write गर्छ। यसैबीच, Engineer B को apply concurrent running थियो र आफ्नै नयाँ EC2 instance `i-0bbb` पनि create गर्छ। Engineer B को apply सकिँदा, यसले आफ्नै version को state file write गर्छ — Engineer A को version overwrite गर्दै। अब state file ले `i-0bbb` मात्र जान्दछ। Instance `i-0aaa` AWS मा running छ तर Terraform को लागि completely unknown: यो orphaned resource हो। `terraform destroy` run गरेमा, `i-0bbb` मात्र destroy हुन्छ। `i-0aaa` सधैं running रहन्छ, पैसा खर्च गर्छ, र manual intervention बिना Terraform ले manage वा destroy गर्न सक्दैन। Destructive operation सँग झन् खराब हुन्छ: दुवै engineer ले state read गर्दा `aws_db_instance.primary` छ देख्छन्। Engineer A ले instance class change गर्छ (in-place update)। Engineer B ले independently database destroy र recreate गर्ने decide गर्छ। दुवैले concurrently apply गर्छन्। Database B ले destroy गर्छ, B ले recreate गर्छ, त्यसपछि A को apply ले original instance ID (जो अब छैन) modify गर्ने try गर्छ — API error। State अब indeterminate, corrupt state मा छ जसलाई recover गर्न manual forensics चाहिन्छ। यसैले team को लागि state locking optional छैन। S3+DynamoDB सँग: कुनै पनि apply अघि, Terraform ले DynamoDB मा lock ID, timestamp, कसले acquire गर्यो, र कुन operation running छ भएको `LockInfo` item write गर्छ। Lock छँदै start हुने अरू `plan` वा `apply` ले तुरुन्त DynamoDB table read गर्छ, lock देख्छ, र clear error सँग fail हुन्छ: `Error: Error locking state: ConditionalCheckFailedException: Lock already acquired by [user], lock ID: [uuid]`। Engineer ले current operation सकिन पर्खनुपर्छ (वा crashed process ले छाडेको lock भएको emergency situation मा `terraform force-unlock [lock-id]` प्रयोग गर्नुहोस्)।",
        jp: "状態ロックなしでは、並行する `terraform apply` 操作が**状態の破損**を引き起こします — インフラ管理で最も危険な障害の 1 つです。災害につながる正確なイベントシーケンスはこうです。両方のエンジニアがほぼ同時に `terraform plan` を実行します。各自が現在の状態（この時点では両者で同一）を読み込み、どの変更が必要かを計算し、`apply` に進みます。エンジニア A の適用が最初に開始し、新しい EC2 インスタンス `i-0aaa` を作成します。Terraform は `i-0aaa` の ID を含む新しい状態を状態ファイルに書き込みます。その間、エンジニア B の適用は並行して実行されており、独自の新しい EC2 インスタンス `i-0bbb` も作成します。エンジニア B の適用が終了すると、独自バージョンの状態ファイルを書き込みます — エンジニア A のバージョンを上書きします。今や状態ファイルは `i-0bbb` のことしか知りません。インスタンス `i-0aaa` は AWS で実行されていますが、Terraform には完全に未知のものです：これは孤立したリソースです。`terraform destroy` を実行すると `i-0bbb` のみが破棄されます。`i-0aaa` は永遠に実行され続け、お金を消費し、手動介入なしに Terraform で管理または破棄することができません。破壊的な操作ではさらに悪化します：両方のエンジニアが状態を読むと `aws_db_instance.primary` が存在することを確認します。エンジニア A はインスタンスクラスを変更します（インプレース更新）。エンジニア B は独立してデータベースを破棄して再作成することを決定します。両方が並行して適用します。データベースは B によって破棄され、B によって再作成され、その後 A の適用が元のインスタンス ID（もはや存在しない）を変更しようとします — API エラー。状態は今や不確定な破損した状態にあり、復旧するには手動の調査が必要です。これがチームにとって状態ロックが任意でない理由です。S3+DynamoDB を使用する場合：適用の前に Terraform は DynamoDB にロック ID・タイムスタンプ・誰が取得したか・実行中の操作を含む `LockInfo` アイテムを書き込みます。ロックが存在する間に開始される他の `plan` や `apply` はすぐに DynamoDB テーブルを読み込み、ロックを確認し、明確なエラーで失敗します：`Error: Error locking state: ConditionalCheckFailedException: Lock already acquired by [user], lock ID: [uuid]`。エンジニアは現在の操作が終わるまで待つ必要があります（またはクラッシュしたプロセスによって残されたロックの緊急事態では `terraform force-unlock [lock-id]` を使用します）。",
      },
      tag: {
        en: "state locking & concurrent apply",
        np: "state locking र concurrent apply",
        jp: "状態ロックと同時 apply",
      },
    },
    {
      question: {
        en: "When should you use Terraform workspaces vs separate state files in separate directories?",
        np: "Terraform workspace vs छुट्टाछुट्टै directory मा छुट्टाछुट्टै state file — कहिले कुन प्रयोग गर्ने?",
        jp: "Terraform ワークスペースと別々のディレクトリの別々の状態ファイル — いつどちらを使うべきか？",
      },
      answer: {
        en: "This is a common architectural question and the wrong choice causes significant pain. The answer depends on how similar your environments are and how much isolation you need. **Use workspaces when**: your environments are nearly identical — same resource types, same configuration structure, only small differences in sizes, counts, or names. The canonical example is dev/staging/production for the same application: the infrastructure looks the same, just t3.micro in dev vs t3.large in prod, 1 NAT gateway in dev vs 3 in prod. In a workspace setup, you have one set of `.tf` files and three states. You use `terraform.workspace` in your HCL to branch on environment: `instance_count = terraform.workspace == \"production\" ? 3 : 1`. **Do NOT use workspaces when**: (1) your environments have fundamentally different infrastructure — dev might use a SQLite RDS whereas production uses Aurora Global. The workspace approach forces you to use complex conditionals everywhere and the code becomes unmaintainable. (2) You need strict blast-radius isolation — in a workspace setup, a bug in your Terraform code can affect all workspaces. Separate directories mean a bad plan in staging cannot accidentally affect production because they are literally different Terraform invocations with different credentials. (3) You need per-environment AWS accounts (the security best practice) — workspaces within a single backend do not naturally map to cross-account deployments. The **separate directories pattern** (also called the `terragrunt` pattern or the \"root module per environment\" pattern) uses a directory structure like `environments/dev/main.tf`, `environments/staging/main.tf`, `environments/production/main.tf` — each with its own backend config, its own state file, and potentially its own AWS provider configuration (different account, different region). This provides maximum isolation but requires duplicating backend config in each directory (DRY violation) — which is why tools like Terragrunt exist to manage this. **Rule of thumb**: if you can describe your environments as 'same infrastructure, different sizes', use workspaces. If you'd describe them as 'different infrastructure', use separate directories. If you need separate AWS accounts, use separate directories.",
        np: "यो common architectural question हो र गलत choice ले significant pain ल्याउँछ। जवाफ तपाईंका environment कति similar छन् र कति isolation चाहिन्छ भन्नेमा निर्भर गर्छ। **Workspace प्रयोग गर्ने बेला**: तपाईंका environment लगभग identical छन् — same resource type, same configuration structure, size, count, वा name मा मात्र सानो फरक। Canonical example एउटै application को dev/staging/production हो: infrastructure उस्तै देखिन्छ, dev मा t3.micro vs prod मा t3.large मात्र, dev मा 1 NAT gateway vs prod मा 3। Workspace setup मा, एउटा set `.tf` file र तीनवटा state हुन्छ। HCL मा environment मा branch गर्न `terraform.workspace` प्रयोग गर्नुहोस्: `instance_count = terraform.workspace == \"production\" ? 3 : 1`। **Workspace प्रयोग नगर्ने बेला**: (१) तपाईंका environment मा fundamentally different infrastructure छ — dev मा SQLite RDS प्रयोग हुन सक्छ जहाँ production मा Aurora Global प्रयोग हुन्छ। Workspace approach ले सबैतिर complex conditional प्रयोग गर्न बाध्य पार्छ र code unmaintainable हुन्छ। (२) Strict blast-radius isolation चाहिन्छ — workspace setup मा, Terraform code मा bug ले सबै workspace affect गर्न सक्छ। Separate directory भनेको staging मा bad plan ले production accidentally affect गर्न सक्दैन किनभने ती literally different Terraform invocation हुन् different credential सहित। (३) Per-environment AWS account चाहिन्छ (security best practice) — single backend भित्रको workspace ले naturally cross-account deployment मा map गर्दैन। **Separate directory pattern** (Terragrunt pattern वा 'root module per environment' pattern पनि भनिन्छ) `environments/dev/main.tf`, `environments/staging/main.tf`, `environments/production/main.tf` जस्तो directory structure प्रयोग गर्छ — प्रत्येकको आफ्नै backend config, आफ्नै state file, र सम्भवतः आफ्नै AWS provider configuration (different account, different region) हुन्छ। यसले maximum isolation provide गर्छ तर प्रत्येक directory मा backend config duplicate गर्नुपर्छ (DRY violation) — यसैले Terragrunt जस्तो tool यो manage गर्न exist गर्छ। **Rule of thumb**: environment लाई 'same infrastructure, different sizes' को रूपमा describe गर्न सक्नुहुन्छ भने, workspace प्रयोग गर्नुहोस्। 'Different infrastructure' को रूपमा describe गर्नुहुन्छ भने, separate directory प्रयोग गर्नुहोस्। Separate AWS account चाहिन्छ भने, separate directory प्रयोग गर्नुहोस्।",
        jp: "これはよくあるアーキテクチャの質問であり、間違った選択は大きな苦痛をもたらします。答えは環境がどれほど似ているか、どれほどの分離が必要かによります。**ワークスペースを使う場合**：環境がほぼ同一である場合 — 同じリソースタイプ・同じ設定構造・サイズ・数・名前だけに小さな違いがある。典型的な例は同じアプリケーションの dev/staging/production です：インフラは同じに見え、dev では t3.micro、prod では t3.large、dev では NAT ゲートウェイ 1 つ、prod では 3 つという違いだけ。ワークスペース設定では、1 セットの `.tf` ファイルと 3 つの状態があります。HCL で環境に基づいて分岐するために `terraform.workspace` を使用します：`instance_count = terraform.workspace == \"production\" ? 3 : 1`。**ワークスペースを使わない場合**：(1) 環境に根本的に異なるインフラがある場合 — dev は SQLite RDS を使い、production は Aurora Global を使うかもしれない。ワークスペースアプローチはあらゆる場所で複雑な条件分岐を使うことを強いられ、コードがメンテナンス不可能になります。(2) 厳格な影響範囲の分離が必要な場合 — ワークスペース設定では Terraform コードのバグがすべてのワークスペースに影響する可能性があります。別々のディレクトリは staging での悪いプランが production に偶発的に影響できないことを意味します（文字通り異なる認証情報を持つ異なる Terraform 呼び出しだから）。(3) 環境ごとの AWS アカウントが必要な場合（セキュリティのベストプラクティス）— 単一バックエンド内のワークスペースはクロスアカウントデプロイに自然にマッピングされません。**別々のディレクトリパターン**（Terragrunt パターンまたは「環境ごとのルートモジュール」パターンとも呼ばれる）は `environments/dev/main.tf`・`environments/staging/main.tf`・`environments/production/main.tf` のようなディレクトリ構造を使用します — それぞれが独自のバックエンド設定・独自の状態ファイル・場合によっては独自の AWS プロバイダー設定（異なるアカウント・異なるリージョン）を持ちます。これは最大の分離を提供しますが、各ディレクトリでバックエンド設定を重複させる必要があります（DRY 違反）— これが Terragrunt のようなツールがこれを管理するために存在する理由です。**経験則**：環境を「同じインフラ、異なるサイズ」と説明できるなら、ワークスペースを使う。「異なるインフラ」と説明するなら、別々のディレクトリを使う。AWS アカウントを分離する必要があるなら、別々のディレクトリを使う。",
      },
      tag: {
        en: "workspaces vs directories",
        np: "workspace vs directory",
        jp: "ワークスペース vs ディレクトリ",
      },
    },
  ],
};
